PATCH /api/2.5/tenders/e234fb168a9a4eae96cf2776aac2c690/awards/f3d8f89b9552466cb3f84cae3e0deb5a/complaints/5adaa5b896494b82b07cecc2feb9c5ad HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 31
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "invalid"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "dateDecision": "2019-10-01T01:00:03+03:00", 
    "transfer_token": "61587954c3321f7b65149a685794fa4f424bcb2cfa6f3940c163e5daaaf9af4f3fb3ac91b4f6cff92e44177160b2ab41693a0a06a267ee9e2a1a2d6b7edd6961", 
    "title": "Недостатньо інформації", 
    "acceptance": false, 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2019-10-01T01:00:03+03:00", 
    "complaintID": "UA-2019-10-01-000001.2", 
    "date": "2019-10-01T01:00:03+03:00", 
    "type": "complaint", 
    "id": "5adaa5b896494b82b07cecc2feb9c5ad", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс."
  }
}

