POST /api/2.5/tenders/e234fb168a9a4eae96cf2776aac2c690/awards/f3d8f89b9552466cb3f84cae3e0deb5a/complaints/b7e603d352b84065ac337d4ed5348b8e/documents?acc_token=dbb7a016a8f44e3d8db91791300889dc HTTP/1.0
Authorization: Bearer broker
Content-Length: 157
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e234fb168a9a4eae96cf2776aac2c690/awards/f3d8f89b9552466cb3f84cae3e0deb5a/complaints/b7e603d352b84065ac337d4ed5348b8e/documents/bd4be7fbbbdf405899375929a0e50b28
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3d27a490aa5c43fea1629d2e49eeb9d4?KeyID=a8968c46&Signature=5WxrVJO29EexjbE5xbY0KQ%2FNe%2FNe5ocjqgdLHnnfhlNQ0hTFTYSF%2Fh2Uys37CB47A%252B21HMm9WTSJaV7sqrFpDQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-10-01T01:00:03+03:00", 
    "id": "bd4be7fbbbdf405899375929a0e50b28", 
    "dateModified": "2019-10-01T01:00:03+03:00"
  }
}

