PATCH /api/2.5/tenders/a41032bbcdec47df9273af568f595c1d/complaints/8db347bde49040188e3ed9a12bc4ac0a?acc_token=d9a48a7a96c34cf99167e709c8856cd6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "claim"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "claim", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/09add287b1f347b5be0d419eb003fa7a?KeyID=a8968c46&Signature=9fjn7SiJY3Ac5MgnoJjO4KBtrXygITAZOUywgMdyzlfaPmh5Mos1FxxiDaHsosJmcZA6HeESPpo%2FZyD7tVGBCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "05e151b6d0d0471e8527a4f9ed88ea4c", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "dateSubmitted": "2019-04-01T01:00:00+03:00", 
    "complaintID": "UA-2019-04-01-000001.1", 
    "date": "2019-04-01T01:00:00+03:00", 
    "type": "claim", 
    "id": "8db347bde49040188e3ed9a12bc4ac0a"
  }
}

