PATCH /api/2.5/tenders/6427779ef1904a858ed980c275f8eac4/awards/9e6d8342d23c45a6a140c88b60db287d/complaints/f04e480d25a64953a951c4dce690202c HTTP/1.0
Authorization: Bearer reviewer
Content-Length: 32
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "accepted"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "0da753f5904c4a159f596f5f86fd0fb7", 
    "status": "accepted", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/78350f97e68f48d1b0e7f1db70cca5cd?KeyID=a8968c46&Signature=S1yUbl%2FitVwn2Rq6Y%252BXZHqkOW3H5iOzLFsp%2Fwaf20XtQTV12d1sqL0EgBJMGqgCTu3ZDNogC%252Bu1qFpB6o0JUCQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-01T01:00:01+03:00", 
        "id": "c52ac3e6cbd243888bed156b02043f39", 
        "dateModified": "2019-10-01T01:00:01+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2019-10-01T01:00:01+03:00", 
    "dateSubmitted": "2019-10-01T01:00:01+03:00", 
    "complaintID": "UA-2019-10-01-000001.1", 
    "date": "2019-10-01T01:00:01+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "f04e480d25a64953a951c4dce690202c"
  }
}

