GET /api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/bids/410cb59a0945497eb61cc4461f661569?acc_token=7ba8d77208c04422b161882dc2c4b5c2 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/088e0915e8e74989bcb965918fc84e58?KeyID=a8968c46&Signature=i%252BXVXMR%2FAQUE5TktpC8QOswIoeGdyf0Q%252BDJxCAFlZt52P0KZJ7zgntKfIt1cA7SzpkdvHvCzE8ldKwJQvmpFAQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-25T01:00:00+03:00", 
        "id": "132ca22170d0430ea36297612e18cf10", 
        "dateModified": "2019-10-25T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/bids/410cb59a0945497eb61cc4461f661569/documents/3af2155766be48d79487c4077dbb00a0?download=a181a55c419945f69680dabe77c08fbc", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_top_secrets.pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-25T01:00:00+03:00", 
        "id": "3af2155766be48d79487c4077dbb00a0", 
        "dateModified": "2019-10-25T01:00:00+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0c646cfe36074f0480619097f8d92339?KeyID=a8968c46&Signature=a76DiSDzRUsGPXEMrsca7HQfHxy3EucsRLdSIeKN7aqP6Tuc43RdT1yCwekEdVbR9Fm35s%252BQ1BMi6txAiL5iDA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-25T01:00:00+03:00", 
        "id": "f0ab3f417fec458482a75e23a8ca25b2", 
        "dateModified": "2019-10-25T01:00:00+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "410cb59a0945497eb61cc4461f661569", 
    "lotValues": [
      {
        "relatedLot": "c7555f1bb878434d8815dea318304673", 
        "date": "2019-10-25T01:00:00+03:00", 
        "status": "active", 
        "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/e5172ebc4c4c411f84f376ce6ede43b8_c7555f1bb878434d8815dea318304673?key_for_bid=410cb59a0945497eb61cc4461f661569", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/bids/410cb59a0945497eb61cc4461f661569/financial_documents/99d644a14cca41eca9dc02f2111bd9df?download=6954200c07ee44fc81e9ff2428198ae7", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-25T01:00:00+03:00", 
        "id": "99d644a14cca41eca9dc02f2111bd9df", 
        "dateModified": "2019-10-25T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/bids/410cb59a0945497eb61cc4461f661569/financial_documents/64cd38caa44e49ecab8f5eae4e2a9b0d?download=37bd5ab21e3540d183f76f126c422b9c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-25T01:00:00+03:00", 
        "id": "64cd38caa44e49ecab8f5eae4e2a9b0d", 
        "dateModified": "2019-10-25T01:00:00+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-10-25T01:00:00+03:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/bids/410cb59a0945497eb61cc4461f661569/qualification_documents/3e7beab69c9347508ec4b9c4aa378263?download=cae90a03333b48e79d5e9f8cf8f9e62a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-25T01:00:00+03:00", 
        "id": "3e7beab69c9347508ec4b9c4aa378263", 
        "dateModified": "2019-10-25T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document2.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/bids/410cb59a0945497eb61cc4461f661569/qualification_documents/3e7beab69c9347508ec4b9c4aa378263?download=8471bbd9083e49bf9984ef1c0124a17f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-25T01:00:00+03:00", 
        "id": "3e7beab69c9347508ec4b9c4aa378263", 
        "dateModified": "2019-10-25T01:00:00+03:00"
      }
    ]
  }
}

