PATCH /api/2.5/tenders/eb9e3bc5967c4db0b2dac4faca46fa52/complaints/ec8930c1a14a45498cca3209c3bec8bd?acc_token=f0a6d9e72d0949759c1ef1fa5cea8650 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "claim"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "claim", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1ccd24b9721c4f37ba2b1f1caf2323cc?KeyID=a8968c46&Signature=IYe%252B4tMCdor5l6aNDM7HN%252BN%252BveslXIDY6SQ1b%252Bi7aytmzNKGyLw7KsRfbIn16LHsCJzRadpGwbUJzT2ke6mrDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "4bfbcbd67e234fdc858cc77e1edfcd3e", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "dateSubmitted": "2019-04-01T01:00:00+03:00", 
    "complaintID": "UA-2019-04-01-000001.1", 
    "date": "2019-04-01T01:00:00+03:00", 
    "type": "claim", 
    "id": "ec8930c1a14a45498cca3209c3bec8bd"
  }
}

