GET /api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/documents?acc_token=1e40f3cf3fd64b8ebca3076b70a86e71 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c61e728d3d044f26a2815e7469ee2d95?KeyID=a8968c46&Signature=P8NvKi0vJRXc0q7Z%2FWCauovoiZtp%2FM91bBSWpEgU%252BzESiayY8%2Fgn78ncEpJOPBo%252BCXlmM1BRsVLX345a2RzxCw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "215889aa876244759b39e64edf790119", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4aa1239666e0455785373f68969eed69?KeyID=a8968c46&Signature=KOiFb54wrnoyxxYO%2F%252BIkI6jkuNl3kQvY8ScEHO6FBfL32zzXHi5c4SQz723hN8ci54%252B2wl7N%252BIGh%252Bk4iXk1GBA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "d46430f773794e84836096230312e46a", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }
  ]
}

