POST /api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/bids/410cb59a0945497eb61cc4461f661569/financial_documents?acc_token=90deaa7bd79d4f6caaff4985ba3e3840 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 141
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="financial_doc.pdf"
Content-Type: application/pdf

1000$
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/bids/410cb59a0945497eb61cc4461f661569/financial_documents/e419dc2127a94e73aca08ed36af587a2
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "public", 
    "language": "uk", 
    "title": "financial_doc.pdf", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e5172ebc4c4c411f84f376ce6ede43b8/bids/410cb59a0945497eb61cc4461f661569/financial_documents/e419dc2127a94e73aca08ed36af587a2?download=d6c857c3ebe348eb9e525b1c3a8c4c32", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "e419dc2127a94e73aca08ed36af587a2", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

