PATCH /api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e/cancellations/6dfb91d83626494bbe1075af81f9149e?acc_token=4c2dfb06830a4541b4794b671b6f4e15 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/854882df0eca4b07a7e1eeddf3c5a998?KeyID=a01f97eb&Signature=cNhCTosuUZgg5SBGdLy7U8mvPisf0jWJIy11vj6vx0E0qeqpMjE4JZJlksH0bkNRkk5yicnJ5Lh23v5jg%252BmVCA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:27:49.664321+02:00", 
        "id": "d1df2de9f6fe44f09907b7f8f4342e6b", 
        "dateModified": "2019-03-18T16:27:49.664486+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "language": "uk", 
        "title": "Notice-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/f68e1eb35216484283551cbdabce1951?KeyID=a01f97eb&Signature=UdUDh0z2pyR2lKNdV3mkpVK%2Fp9TiSs7%2FPm1vOedEs26pEUhvk%2FgdJ3X2QJNAqlT5tm%2FXG3pdYC1QrokyfmB%252BCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:27:49.664321+02:00", 
        "id": "d1df2de9f6fe44f09907b7f8f4342e6b", 
        "dateModified": "2019-03-18T16:27:52.167128+02:00"
      }
    ], 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-03-18T16:27:53.474559+02:00", 
    "cancellationOf": "tender", 
    "id": "6dfb91d83626494bbe1075af81f9149e"
  }
}

