PATCH /api/2.5/tenders/aaae78af64524937a8ac48aace2715db/cancellations/b6c1912c502c4b208ef31fb5b2bf749f?acc_token=49425b1c4f744b00af62c89e9efd36e9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1df780ed0a4b4a69949eeb95d11f5b94?KeyID=f8180d36&Signature=669INjS6BW4sGhUJjRe54tyiGxkSXMYdVd%252B4qy8SakkY8Yzu%252BRTToufskOSiEqXVB7XeboJ%252Brw1MkTlrPJggBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:10:00+02:00", 
        "id": "740d5b9c487144579c5f1f7dd86ac596", 
        "dateModified": "2019-01-01T00:10:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "language": "uk", 
        "title": "Notice-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0e6f5c770c5341479955be4c4d98340c?KeyID=f8180d36&Signature=qhVzPA4XOuCXSUQJrmBPrH2uyBZF50eP%252BRbWyuvWvOejHmS%252B1SP3syGWt7NK9zFbpRzFD1qXXHYpwG1fD%2F8hBA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:10:00+02:00", 
        "id": "740d5b9c487144579c5f1f7dd86ac596", 
        "dateModified": "2019-01-01T00:10:00+02:00"
      }
    ], 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-01-01T00:10:00+02:00", 
    "cancellationOf": "tender", 
    "id": "b6c1912c502c4b208ef31fb5b2bf749f"
  }
}

