PATCH /api/2.5/tenders/aaae78af64524937a8ac48aace2715db/questions/44cb55756e174e51bcbb29e8c7346800?acc_token=49425b1c4f744b00af62c89e9efd36e9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2019-01-01T00:00:00+02:00", 
    "title": "Калорійність", 
    "date": "2019-01-01T00:00:00+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "44cb55756e174e51bcbb29e8c7346800", 
    "questionOf": "tender"
  }
}

