PATCH /api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/questions/8e545fd843144179a0b8b9826074aa08?acc_token=bab7c97c1f3249709899f382cd84f722 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2019-04-01T01:00:00+03:00", 
    "title": "Калорійність", 
    "date": "2019-04-01T01:00:00+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "8e545fd843144179a0b8b9826074aa08", 
    "questionOf": "tender"
  }
}

