PATCH /api/2.5/tenders/c368f2394a83454fbd86a8f66c5c1ab4/qualifications/58f221cb930b4a8ab99c3bec1dfaea42?acc_token=1b2bc07c22ac43e5811e5b0916da46b7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "56bafc45d19c4e6ea39e944d32dc5958", 
    "date": "2019-03-28T06:48:39.521570+02:00", 
    "id": "58f221cb930b4a8ab99c3bec1dfaea42"
  }
}

