PATCH /api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/qualifications/c31637c4bb484720adb4f17f93678ff7?acc_token=bab7c97c1f3249709899f382cd84f722 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "64b6fc65958b499fa4dead17d4f89c5a", 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "c31637c4bb484720adb4f17f93678ff7"
  }
}

