PATCH /api/2.4/tenders/a9ac809f24974fdba733fa494d18448a/qualifications/ba9b02ff260140e1a8a629768d6dba3a?acc_token=6e330b937a244a3aaf02a63e6a634bea HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "eb2aa540c0eb4af9a42863e297432cd6", 
    "date": "2018-09-21T05:24:32.387639+03:00", 
    "id": "ba9b02ff260140e1a8a629768d6dba3a"
  }
}

