PATCH /api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e/qualifications/5206c83eaf8d49a5b2d219cf5afb8f33?acc_token=4c2dfb06830a4541b4794b671b6f4e15 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "9996708dedc24b2ead4a7ff3b427e55b", 
    "date": "2019-03-18T16:27:34.067770+02:00", 
    "id": "5206c83eaf8d49a5b2d219cf5afb8f33"
  }
}

