GET /api/2.5/tenders/aaae78af64524937a8ac48aace2715db HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "selective", 
    "status": "active.auction", 
    "complaintPeriod": {
      "startDate": "2018-11-21T00:00:00+02:00", 
      "endDate": "2018-12-18T00:00:00+02:00"
    }, 
    "auctionUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/aaae78af64524937a8ac48aace2715db", 
    "enquiryPeriod": {
      "startDate": "2018-11-21T00:00:00+02:00", 
      "clarificationsUntil": "2018-12-17T00:00:00+02:00", 
      "endDate": "2018-12-12T00:00:00+02:00", 
      "invalidationDate": "2019-01-01T00:00:00+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procurementMethodType": "competitiveDialogueEU.stage2", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-01-01T00:00:00+02:00", 
        "title": "Калорійність", 
        "date": "2019-01-01T00:00:00+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "44cb55756e174e51bcbb29e8c7346800", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "aaae78af64524937a8ac48aace2715db", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b94160523d0c44d09a04c98e70b68b03?KeyID=f8180d36&Signature=5ujTNED%2Fjhigk%2FFWIOH5%252Bv8iarXpjjmkOVqNYErcwP1iPlfQstoXLuHB4K%2FOl7kig8fjLoIqmgP5kwU0InMBCA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "fbf9cda2a17e4abcb82507a2a1f9f52e", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/73965e203a3747eba23a6999a348b97c?KeyID=f8180d36&Signature=6iiSaEoRgk7j7Jf%2FXmF6%2F%2Fdn%252BIJRUDQSFz5DTxa1BESEW%252BU%2F%2FNENnSQEzJ9Jk3aP6G0aes6acRAX0nnLfz2OAA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "283d6f1c38c1425ab5fc211a477ed6e9", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/55cae7536fb7496a8b8e792b7465ac7d?KeyID=f8180d36&Signature=T5NPL90G9S%2Fa7pbohXBIuJ%2FVPIeU3V1%252BKP%252BUJZF7mzRIqk5m1v08%2Ft59rdl2C0nBRqqImU%2F81vmYpFyl7tsVDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "283d6f1c38c1425ab5fc211a477ed6e9", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2018-12-22T00:00:00+02:00", 
      "endDate": "2019-01-01T00:00:00+02:00"
    }, 
    "shortlistedFirms": [
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»"
      }
    ], 
    "tenderID": "UA-2019-01-01-000001", 
    "dateModified": "2019-01-01T00:00:00+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2018-11-21T00:00:00+02:00", 
      "endDate": "2018-12-22T00:00:00+02:00"
    }, 
    "auctionPeriod": {
      "startDate": "2019-01-01T00:00:00+02:00", 
      "shouldStartAfter": "2019-01-01T00:00:00+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "c65cc2e9e1344faa90371b52aed104d6", 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "ed02b3e84c6b4c7fa7ca9ec4deb2944a"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "8d4396d2ed3c4cefb9bd1f694d241373", 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "196eca0b9b7444379a907ee9c7d102e8"
      }, 
      {
        "status": "unsuccessful", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "eae56d6588704d86bf61ea2032f9c606", 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "8b00071bc4a14522b708dedc55639872"
      }
    ], 
    "date": "2019-01-01T00:00:00+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-01-21T00:00:00+02:00", 
          "endDate": "2019-01-31T00:00:10+02:00"
        }, 
        "id": "920d8bfd71ff4366ab8fd3bae30c1986", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9f882af15e814e91bdfbd908352ca2e1?KeyID=f8180d36&Signature=4pNvJOpzdg4OZN88q2unlAovsxZ7OHsRCHkFD11Xv6pF%252BsIX3osxiQ6S5X61EuXTMuDS%2FIFsxwmYA5G6kx%2FSDw%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-01-01T00:00:00+02:00", 
            "id": "f7eec34deeba497abc4d97a8a47a2b06", 
            "dateModified": "2019-01-01T00:00:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/aaae78af64524937a8ac48aace2715db/bids/c65cc2e9e1344faa90371b52aed104d6/documents/2b09c4267c254c32ab4029f4897db2f9?download=47c4ebcc8f264423b74b89cd0c4362ce", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_top_secrets.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-01-01T00:00:00+02:00", 
            "id": "2b09c4267c254c32ab4029f4897db2f9", 
            "dateModified": "2019-01-01T00:00:00+02:00"
          }
        ], 
        "id": "c65cc2e9e1344faa90371b52aed104d6", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "8d4396d2ed3c4cefb9bd1f694d241373", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "unsuccessful", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal_part1.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3041614e39fe47c8841694c29c887602?KeyID=f8180d36&Signature=a2rjCdJQbbVjgnAelPxLABqN6DXR30nZ1VymPnfWj%2FewweqLHPKiAUHb3ZpIOST7vjaRrTRmXrE%2FSgVpE6dDDg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-01-01T00:00:00+02:00", 
            "id": "e7d0c0e8285d46afae8c7b6a49eb8408", 
            "dateModified": "2019-01-01T00:00:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/aaae78af64524937a8ac48aace2715db/bids/eae56d6588704d86bf61ea2032f9c606/documents/633de4cc7bb349df97d6b7a50d21fd8d?download=6484dd5082134a5aad7d9ec71beed149", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_part2.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-01-01T00:00:00+02:00", 
            "id": "633de4cc7bb349df97d6b7a50d21fd8d", 
            "dateModified": "2019-01-01T00:00:00+02:00"
          }
        ], 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f77f25427a8e4d219ce06275bbcc0cf6?KeyID=f8180d36&Signature=RPa%2FvMJMU1JVPnPB5JvegdqBTN2EUR3jGM0SgJFMrkF%252BOz7NEzKBecaWLLxxTWOhgfzyBY4HJOd07OTMFEhIBg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-01-01T00:00:00+02:00", 
            "id": "4d0559b45dd34b079b8e23e302f162f4", 
            "dateModified": "2019-01-01T00:00:00+02:00"
          }
        ], 
        "selfEligible": true, 
        "selfQualified": true, 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Карпенко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137228", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Кенгуру»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Коцюбинського, 15", 
              "region": "м. Запоріжжя", 
              "locality": "м. Запоріжя"
            }
          }
        ], 
        "id": "eae56d6588704d86bf61ea2032f9c606"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "next_check": "2019-01-01T00:36:00+02:00", 
    "awardCriteria": "lowestCost"
  }
}

