GET /api/2.5/tenders/c368f2394a83454fbd86a8f66c5c1ab4/bids/639da32edcf5450b93bab9db8a95e0c9?acc_token=697b33e209334d999d045c830600735b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "639da32edcf5450b93bab9db8a95e0c9"
  }
}

