PATCH /api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e/bids/f24d9d3fbd44480d871561d085053047?acc_token=72596c7c805f4b7799eaed198223ba3f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e/bids/f24d9d3fbd44480d871561d085053047/documents/3bc31e405ab64b2bb60c15a117a6c14f?download=d1438bd974354eb2b24af27cca5da049", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:27:26.792252+02:00", 
        "id": "3bc31e405ab64b2bb60c15a117a6c14f", 
        "dateModified": "2019-03-18T16:27:26.792338+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e/bids/f24d9d3fbd44480d871561d085053047/documents/26e5731647b540fa8cdecfb55817a24b?download=d92a2b31ae474ae494a8c80860a5303a", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_top_secrets.pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:27:27.024812+02:00", 
        "id": "26e5731647b540fa8cdecfb55817a24b", 
        "dateModified": "2019-03-18T16:27:27.024843+02:00"
      }
    ], 
    "selfEligible": true, 
    "id": "f24d9d3fbd44480d871561d085053047", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e/bids/f24d9d3fbd44480d871561d085053047/financial_documents/99d251aa86014e03b76325bcc1bfde87?download=7c99ceebdf144e2f8c8f6b63ee3c7f77", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:27:27.404702+02:00", 
        "id": "99d251aa86014e03b76325bcc1bfde87", 
        "dateModified": "2019-03-18T16:27:27.404801+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e/bids/f24d9d3fbd44480d871561d085053047/financial_documents/be12821d5a1a41a7b70b123d993f587d?download=3a7486116ce04f1d9a05c301748184f9", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:27:27.817111+02:00", 
        "id": "be12821d5a1a41a7b70b123d993f587d", 
        "dateModified": "2019-03-18T16:27:27.817133+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-03-18T16:27:26.126624+02:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e/bids/f24d9d3fbd44480d871561d085053047/qualification_documents/d2d6438ea9a74666adf164f961338e3c?download=32eba57122f14d54b901e54545f05fb2", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:27:28.242369+02:00", 
        "id": "d2d6438ea9a74666adf164f961338e3c", 
        "dateModified": "2019-03-18T16:27:28.242395+02:00"
      }
    ]
  }
}

