GET /api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/f74c53e1c5994792be38bf1f5eddc97f?acc_token=8896b59ed7a64f12a0f9f93d529ce0bc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/f74c53e1c5994792be38bf1f5eddc97f/documents/d15145f34c1f4b07991d71b9d1a1ab8d?download=9f62ac5ff38743cabb60111ad9e2681e", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "d15145f34c1f4b07991d71b9d1a1ab8d", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/f74c53e1c5994792be38bf1f5eddc97f/documents/96b00c52ce4e4e598d093eac7351c0a7?download=f97c89de0c7540afbe548e21368afa01", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_top_secrets.pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "96b00c52ce4e4e598d093eac7351c0a7", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "f74c53e1c5994792be38bf1f5eddc97f", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/f74c53e1c5994792be38bf1f5eddc97f/financial_documents/3352f94bc61a4140a9e10030e0b8bf7c?download=b169505d1cf242d29a8b4f7a72e42404", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "3352f94bc61a4140a9e10030e0b8bf7c", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/f74c53e1c5994792be38bf1f5eddc97f/financial_documents/7d16f966590043dc9a1e67a847784b10?download=4e68045d26954336a8ad503e9868c2d0", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "7d16f966590043dc9a1e67a847784b10", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-04-01T01:00:00+03:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/f74c53e1c5994792be38bf1f5eddc97f/qualification_documents/487210f7f8564c399baf3b51d0fe7be5?download=7b3ff6d13060484da2d4a098d3834774", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "487210f7f8564c399baf3b51d0fe7be5", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ]
  }
}

