GET /api/2.5/tenders/aaae78af64524937a8ac48aace2715db/bids/c65cc2e9e1344faa90371b52aed104d6?acc_token=27c2ebabf7ce4154880e8e722cf9babd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "c65cc2e9e1344faa90371b52aed104d6"
  }
}

