PATCH /api/2.5/tenders/2933880765e44c6abd98096c6de321ed/cancellations/8964fdf65a784b25ba9e0ec24c583757/documents/3b80690d01f54530bb5dbb0f140f45ba?acc_token=437d8c5ad28e44c38d7e7394a20a507b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ca7488cbeb8648058fafb9c1eb39d090?KeyID=a8968c46&Signature=5M3wm90qr5Kh8WRQkzAnCSEBTHz0kCn6GpR%2FFtYAQnxyLe7H7yeO8JiWnLWdeZbYSrfD2Shy3l34NOzjgVpiDg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:10:00+03:00", 
    "id": "3b80690d01f54530bb5dbb0f140f45ba", 
    "dateModified": "2019-04-01T01:10:00+03:00"
  }
}

