PATCH /api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4?acc_token=bab7c97c1f3249709899f382cd84f722 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "selective", 
    "status": "active.pre-qualification.stand-still", 
    "complaintPeriod": {
      "startDate": "2019-03-01T01:00:00+03:00", 
      "endDate": "2019-03-28T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-03-01T01:00:00+03:00", 
      "clarificationsUntil": "2019-03-27T01:00:00+03:00", 
      "endDate": "2019-03-22T01:00:00+03:00", 
      "invalidationDate": "2019-04-01T01:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procurementMethodType": "competitiveDialogueEU.stage2", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-04-01T01:00:00+03:00", 
        "title": "Калорійність", 
        "date": "2019-04-01T01:00:00+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "8e545fd843144179a0b8b9826074aa08", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "bde976eab58547c8b33403fd4e53a9d4", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5646c34840824318a90df0212ff89317?KeyID=a8968c46&Signature=V6A0Ub4OSSU%2F5QdX0rC02oOyErSIibhNpbFKKo9MUsiQtltREk8j47Etcp%2F2afEa4Vbty%252BOwMjQpftsrEFfADg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "8774a99c45324f7d80f765c09379be0f", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d61058e567e04ff8b16324fb0b85f5c3?KeyID=a8968c46&Signature=TukVmmgFrkbcf%252BEgm62begNddH9jBERIlQ7tNGvPR8RwHVCM02GF0bRvhCTwAFwAKnL5Ep7Xiv41QYpclPPlDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "8b0c80ad138b4915b146bc11396b0f04", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6f390702e23d4f409829bcb95f98425d?KeyID=a8968c46&Signature=kyW5nr7r0S3GH1qC3OOcOlJWFznA3b47ESFZXTgAul0qIyf2tVnBmTb1CIkflWPRCBvOp3IjnP3PiaGcFjdNBw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "8b0c80ad138b4915b146bc11396b0f04", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2019-04-01T01:00:00+03:00", 
      "endDate": "2019-04-06T01:00:00+03:00"
    }, 
    "shortlistedFirms": [
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»"
      }
    ], 
    "tenderID": "UA-2019-04-01-000001", 
    "dateModified": "2019-04-01T01:00:00+03:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2019-03-01T01:00:00+03:00", 
      "endDate": "2019-04-01T01:00:00+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-04-07T00:00:00+03:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "f74c53e1c5994792be38bf1f5eddc97f", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "7f22af6afca84bce941dc75ca6ffa906"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "64b6fc65958b499fa4dead17d4f89c5a", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "c31637c4bb484720adb4f17f93678ff7"
      }, 
      {
        "status": "unsuccessful", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "fbbf7a3e65b74740a3ca9c9efc650e84", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "52d1907f064a443bbf87734c6a763289"
      }
    ], 
    "date": "2019-04-01T01:00:00+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-21T01:00:00+03:00", 
          "endDate": "2019-05-01T01:00:10+03:00"
        }, 
        "id": "2d4b90407a3e4a3f8d140263625db2af", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9f62ac5ff38743cabb60111ad9e2681e?KeyID=a8968c46&Signature=jFVbpg9sAMAhExM8pz7R8%252B9HgzLllW70TBjoiei4QwSlYB6gUayvkH6pHRPYjL1JIlVIqJLekr%2Fjs7XmtcSpCA%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "d15145f34c1f4b07991d71b9d1a1ab8d", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/f74c53e1c5994792be38bf1f5eddc97f/documents/96b00c52ce4e4e598d093eac7351c0a7?download=f97c89de0c7540afbe548e21368afa01", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_top_secrets.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "96b00c52ce4e4e598d093eac7351c0a7", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }
        ], 
        "id": "f74c53e1c5994792be38bf1f5eddc97f", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "scale": "micro", 
            "name": "ДКП «Школяр»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "64b6fc65958b499fa4dead17d4f89c5a", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "scale": "sme", 
            "name": "ДКП «Книга»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "unsuccessful", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal_part1.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4c62d14f81e94b8cab0e03452afd982f?KeyID=a8968c46&Signature=volGgRf6xi0M6vkIx%252B9u3reeTsv9oeAbjqu8W70QfhP0p87tyTjYF9iFUeaJsuGBdlBRvDWW8piPgR%2FA0uN8BA%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "5e4925e6d9814e20ad5fe8bbbba6ae33", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/fbbf7a3e65b74740a3ca9c9efc650e84/documents/b1b2a899213c426aa29eef6ef7b683cc?download=7775d8cf6c144352908be29e3c030783", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_part2.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "b1b2a899213c426aa29eef6ef7b683cc", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }
        ], 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f9c9786b57ee4cf39ae3018ac8464806?KeyID=a8968c46&Signature=dV%2Fyl%2Fx9gQ72AUJD81gWK2TbmVlzCqTeC%252BcW3H5ODjuwwx700vDIEeeaEMlzYgh%252BEkaAD%252BcQT8WTyal1ISxlDQ%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "0c1c6fcca44d4ce895090caa77748eb0", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }
        ], 
        "selfEligible": true, 
        "selfQualified": true, 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Карпенко"
            }, 
            "scale": "large", 
            "name": "«Кенгуру»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137228", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Коцюбинського, 15", 
              "region": "м. Запоріжжя", 
              "locality": "м. Запоріжя"
            }
          }
        ], 
        "id": "fbbf7a3e65b74740a3ca9c9efc650e84"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "next_check": "2019-04-06T01:00:00+03:00", 
    "awardCriteria": "lowestCost"
  }
}

