POST /api/2.4/tenders/a9ac809f24974fdba733fa494d18448a/cancellations?acc_token=6e330b937a244a3aaf02a63e6a634bea HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/a9ac809f24974fdba733fa494d18448a/cancellations/df9a62027d8846868ed05dbf07f0f029
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2018-09-21T05:24:38.202701+03:00", 
    "cancellationOf": "tender", 
    "id": "df9a62027d8846868ed05dbf07f0f029"
  }
}

