GET /api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e/bids?acc_token=4c2dfb06830a4541b4794b671b6f4e15 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/d1438bd974354eb2b24af27cca5da049?KeyID=a01f97eb&Signature=%2FUYbces50rLDexEj7CMB5JTjezKWGUxJigGENBjfXXdrC3MQABVA1w90s9Nce8h8Aq3jIIeZDsMkFouGxWz%252BBA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T16:27:26.792252+02:00", 
          "id": "3bc31e405ab64b2bb60c15a117a6c14f", 
          "dateModified": "2019-03-18T16:27:26.792338+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e/bids/f24d9d3fbd44480d871561d085053047/documents/26e5731647b540fa8cdecfb55817a24b?download=d92a2b31ae474ae494a8c80860a5303a", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_top_secrets.pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T16:27:27.024812+02:00", 
          "id": "26e5731647b540fa8cdecfb55817a24b", 
          "dateModified": "2019-03-18T16:27:27.024843+02:00"
        }
      ], 
      "id": "f24d9d3fbd44480d871561d085053047", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "9996708dedc24b2ead4a7ff3b427e55b", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal_part1.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/e004ef4dedad4931a4c44dd9a1143d01?KeyID=a01f97eb&Signature=SnTBiOco9wvifrXBE%2FgVE7PqU2esxhF2%2F9RHKXQCs0947J2gUcdY3TWn9Et77eluPv9S%252BpkqEB1EEfGU4JOkBA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T16:27:31.058180+02:00", 
          "id": "4b70f363c31843b49c2662440c42515d", 
          "dateModified": "2019-03-18T16:27:31.058375+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e/bids/4fddee876f904096a00dd04196685832/documents/17cb5b8b3dee4f80bdb0c5639a7bd6de?download=436ba7aa3a6d4cb2b6612b9d67345c68", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_part2.pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T16:27:31.067062+02:00", 
          "id": "17cb5b8b3dee4f80bdb0c5639a7bd6de", 
          "dateModified": "2019-03-18T16:27:31.067315+02:00"
        }
      ], 
      "eligibilityDocuments": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "eligibility_doc.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/54a4293a50d94b2592f950fc4eefa6ae?KeyID=a01f97eb&Signature=2KGRpFpUiO3kJJY1PFcmTFS9LFWGXlAVpWKgERHpW%252BH0nfVTlPgqgDWn36EjUe7l5Y6pyxSZgMnsNuCRR57aCw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T16:27:31.085780+02:00", 
          "id": "fb90f249e2b54856b0e05757eafae752", 
          "dateModified": "2019-03-18T16:27:31.085978+02:00"
        }
      ], 
      "selfEligible": true, 
      "selfQualified": true, 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Карпенко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137228", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Кенгуру»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Коцюбинського, 15", 
            "region": "м. Запоріжжя", 
            "locality": "м. Запоріжя"
          }
        }
      ], 
      "id": "4fddee876f904096a00dd04196685832"
    }
  ]
}

