GET /api/2.5/tenders/aaae78af64524937a8ac48aace2715db/bids?acc_token=49425b1c4f744b00af62c89e9efd36e9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9f882af15e814e91bdfbd908352ca2e1?KeyID=f8180d36&Signature=4pNvJOpzdg4OZN88q2unlAovsxZ7OHsRCHkFD11Xv6pF%252BsIX3osxiQ6S5X61EuXTMuDS%2FIFsxwmYA5G6kx%2FSDw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-01-01T00:00:00+02:00", 
          "id": "f7eec34deeba497abc4d97a8a47a2b06", 
          "dateModified": "2019-01-01T00:00:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/aaae78af64524937a8ac48aace2715db/bids/c65cc2e9e1344faa90371b52aed104d6/documents/2b09c4267c254c32ab4029f4897db2f9?download=47c4ebcc8f264423b74b89cd0c4362ce", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_top_secrets.pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-01-01T00:00:00+02:00", 
          "id": "2b09c4267c254c32ab4029f4897db2f9", 
          "dateModified": "2019-01-01T00:00:00+02:00"
        }
      ], 
      "id": "c65cc2e9e1344faa90371b52aed104d6", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "8d4396d2ed3c4cefb9bd1f694d241373", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal_part1.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3041614e39fe47c8841694c29c887602?KeyID=f8180d36&Signature=a2rjCdJQbbVjgnAelPxLABqN6DXR30nZ1VymPnfWj%2FewweqLHPKiAUHb3ZpIOST7vjaRrTRmXrE%2FSgVpE6dDDg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-01-01T00:00:00+02:00", 
          "id": "e7d0c0e8285d46afae8c7b6a49eb8408", 
          "dateModified": "2019-01-01T00:00:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/aaae78af64524937a8ac48aace2715db/bids/eae56d6588704d86bf61ea2032f9c606/documents/633de4cc7bb349df97d6b7a50d21fd8d?download=6484dd5082134a5aad7d9ec71beed149", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_part2.pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-01-01T00:00:00+02:00", 
          "id": "633de4cc7bb349df97d6b7a50d21fd8d", 
          "dateModified": "2019-01-01T00:00:00+02:00"
        }
      ], 
      "eligibilityDocuments": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "eligibility_doc.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f77f25427a8e4d219ce06275bbcc0cf6?KeyID=f8180d36&Signature=RPa%2FvMJMU1JVPnPB5JvegdqBTN2EUR3jGM0SgJFMrkF%252BOz7NEzKBecaWLLxxTWOhgfzyBY4HJOd07OTMFEhIBg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-01-01T00:00:00+02:00", 
          "id": "4d0559b45dd34b079b8e23e302f162f4", 
          "dateModified": "2019-01-01T00:00:00+02:00"
        }
      ], 
      "selfEligible": true, 
      "selfQualified": true, 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Карпенко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137228", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Кенгуру»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Коцюбинського, 15", 
            "region": "м. Запоріжжя", 
            "locality": "м. Запоріжя"
          }
        }
      ], 
      "id": "eae56d6588704d86bf61ea2032f9c606"
    }
  ]
}

