POST /api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2618
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "documents": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4c62d14f81e94b8cab0e03452afd982f?KeyID=a8968c46&Signature=cvUy1JDsubHohtVvTMnBCBT5EQwe6VMdxpYQ6UCDS6YXv8U%2BIHAqebHdyX6o945CBeUEgH3tVoKwoO0mcAuMBA%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "format": "application/pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7775d8cf6c144352908be29e3c030783?KeyID=a8968c46&Signature=Jn3%2F88drB48NT38rB1pujuUGfJZesY84cwq1iHtHeo4j1yf%2BvG6FtF20AEKXPb9hBPbfn0PDXVZck5K%2Bi56FBQ%3D%3D", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf"
      }
    ], 
    "eligibilityDocuments": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f9c9786b57ee4cf39ae3018ac8464806?KeyID=a8968c46&Signature=WcbU7H8JwO9Yw9CZWqNj26rX8skOdcKFvS9zjjEDnf6jyHua4HRCTpj8rBP3%2FcwuxPqJwBAMS0J36SSM0l47Cw%3D%3D", 
        "title": "eligibility_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "selfEligible": true, 
    "value": {
      "amount": 5
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7476c51d6c73456584a5d09ac037fbe3?KeyID=a8968c46&Signature=KJD39VaTbQNJ52mksH43XHFXFi9X43hz3XTLEdol%2BcFSeO58t8gr0u1qZSvwAX2boAacu88Zb7wCYROd9Wg%2BAA%3D%3D", 
        "title": "financial_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "name": "Іван Карпенко", 
          "telephone": "+380 (322) 12-34-56"
        }, 
        "scale": "large", 
        "name": "«Кенгуру»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Запоріжжя", 
          "streetAddress": "вул. Коцюбинського, 15", 
          "locality": "м. Запоріжя"
        }
      }
    ], 
    "qualificationDocuments": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a5cfa619f7934ddb898a176943057435?KeyID=a8968c46&Signature=sCD3g0Wu8jtx%2Bsnjk0yvJc7LrHHRQdysJZBFZY%2BhhvIchN8nm3ZTEYciUozGN6WWMosD4mssl7SlYVULyOwCCw%3D%3D", 
        "title": "qualification_document.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/fbbf7a3e65b74740a3ca9c9efc650e84
{
  "access": {
    "token": "1630eee776464b1dbcd468c3db280501"
  }, 
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/fbbf7a3e65b74740a3ca9c9efc650e84/documents/5e4925e6d9814e20ad5fe8bbbba6ae33?download=4c62d14f81e94b8cab0e03452afd982f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "5e4925e6d9814e20ad5fe8bbbba6ae33", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/fbbf7a3e65b74740a3ca9c9efc650e84/documents/b1b2a899213c426aa29eef6ef7b683cc?download=7775d8cf6c144352908be29e3c030783", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "b1b2a899213c426aa29eef6ef7b683cc", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/fbbf7a3e65b74740a3ca9c9efc650e84/eligibility_documents/0c1c6fcca44d4ce895090caa77748eb0?download=f9c9786b57ee4cf39ae3018ac8464806", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "0c1c6fcca44d4ce895090caa77748eb0", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "fbbf7a3e65b74740a3ca9c9efc650e84", 
    "value": {
      "currency": "UAH", 
      "amount": 5.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/fbbf7a3e65b74740a3ca9c9efc650e84/financial_documents/65046db00d1040338f266dfa04656279?download=7476c51d6c73456584a5d09ac037fbe3", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "65046db00d1040338f266dfa04656279", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Карпенко"
        }, 
        "scale": "large", 
        "name": "«Кенгуру»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Коцюбинського, 15", 
          "region": "м. Запоріжжя", 
          "locality": "м. Запоріжя"
        }
      }
    ], 
    "date": "2019-04-01T01:00:00+03:00", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/fbbf7a3e65b74740a3ca9c9efc650e84/qualification_documents/441cdf949d704c49b7d03987af8f6f5c?download=a5cfa619f7934ddb898a176943057435", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "441cdf949d704c49b7d03987af8f6f5c", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ]
  }
}

