POST /api/2.5/tenders/2933880765e44c6abd98096c6de321ed/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2622
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "documents": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/619d52389bfa4b2f97feffc79ea85b16?KeyID=a8968c46&Signature=Kk3pxomH5NgaBCLN8i16fC%2BlPZ70gkARy1i8c09SyOyqJcEsq7NldvS%2BVKfXuIpT30uvHCnJXvW3Da2bOM17Bg%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "format": "application/pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ab81f520d3e345b9a86b63e10869cb1f?KeyID=a8968c46&Signature=PgslY1kQ%2FH0MfJ6TV4BGfW1tljgAZtiE7E623HMAHqQRwyF9bGRfF4sxweflXd6kqa%2BFAZa7YTrZ7c%2B9V26lDA%3D%3D", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf"
      }
    ], 
    "eligibilityDocuments": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/27c06536af914a12bb5158f9f4184c56?KeyID=a8968c46&Signature=VZcsZoWxe%2BqqrcDIYvt2C6ZqXSo%2FeJ0861lAAt2nqu%2FD2Qqy8KbSXdR3PeLKHFqPL9rrK4pz8RLU9aoNO%2BSVAQ%3D%3D", 
        "title": "eligibility_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "selfEligible": true, 
    "value": {
      "amount": 5
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d2058679ccb84f8893fd84f6b8f67fea?KeyID=a8968c46&Signature=6rlvmAePpShmvSQyi4eGEq7P39Xgo73hcCsL5Q2VYOyqWjo%2BdrBU6311HVIX7gJGaJ6P4pwhV5odv17UkIqnBg%3D%3D", 
        "title": "financial_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "name": "Іван Карпенко", 
          "telephone": "+380 (322) 12-34-56"
        }, 
        "scale": "large", 
        "name": "«Кенгуру»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Запоріжжя", 
          "streetAddress": "вул. Коцюбинського, 15", 
          "locality": "м. Запоріжя"
        }
      }
    ], 
    "qualificationDocuments": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/161ee18c8d1a47029d87904dff845eda?KeyID=a8968c46&Signature=EoeQ3r0yOcEVJINH0WKERHmmONhHguMv6vDWiGf5cZuyByGSGX8PkZBN441ZxOGPh7p%2Fn6IjpbQDxZ9JAAbrDg%3D%3D", 
        "title": "qualification_document.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2933880765e44c6abd98096c6de321ed/bids/7fdfa3d97d0e4c9a9c80c208c2cef184
{
  "access": {
    "token": "30f89e21b754426ab9f46eb83b20b867"
  }, 
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2933880765e44c6abd98096c6de321ed/bids/7fdfa3d97d0e4c9a9c80c208c2cef184/documents/d80c08e4b5764d21ab8c0c17bef53060?download=619d52389bfa4b2f97feffc79ea85b16", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "d80c08e4b5764d21ab8c0c17bef53060", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2933880765e44c6abd98096c6de321ed/bids/7fdfa3d97d0e4c9a9c80c208c2cef184/documents/49822c62786d4e46ab78105098cdae15?download=ab81f520d3e345b9a86b63e10869cb1f", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "49822c62786d4e46ab78105098cdae15", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2933880765e44c6abd98096c6de321ed/bids/7fdfa3d97d0e4c9a9c80c208c2cef184/eligibility_documents/5c27740079a54a77809cc648047846c7?download=27c06536af914a12bb5158f9f4184c56", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "5c27740079a54a77809cc648047846c7", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "7fdfa3d97d0e4c9a9c80c208c2cef184", 
    "value": {
      "currency": "UAH", 
      "amount": 5.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2933880765e44c6abd98096c6de321ed/bids/7fdfa3d97d0e4c9a9c80c208c2cef184/financial_documents/562a506612004f84b34ee9509a23d5f2?download=d2058679ccb84f8893fd84f6b8f67fea", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "562a506612004f84b34ee9509a23d5f2", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Карпенко"
        }, 
        "scale": "large", 
        "name": "«Кенгуру»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Коцюбинського, 15", 
          "region": "м. Запоріжжя", 
          "locality": "м. Запоріжя"
        }
      }
    ], 
    "date": "2019-04-01T01:00:00+03:00", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2933880765e44c6abd98096c6de321ed/bids/7fdfa3d97d0e4c9a9c80c208c2cef184/qualification_documents/de4e46c1caf8475fa061a8c88566ab78?download=161ee18c8d1a47029d87904dff845eda", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "de4e46c1caf8475fa061a8c88566ab78", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ]
  }
}

