POST /api/2.5/tenders/c368f2394a83454fbd86a8f66c5c1ab4/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2624
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/e1b8d166c11148fdb711cc7b14a49d37?KeyID=2d509c5e&Signature=qbrMSlfEjKT1GJeWmP2eGIqndk1Kyq%2BTbAsys4I4xlEblhexW2Y1yHwPtzayfa6Bi%2BviZ6IMvJ8gyeHy5P8%2FBQ%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "title": "Proposal_part2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/d2af848c6d034e11aef8704ae7d7e0c4?KeyID=2d509c5e&Signature=j8YDq7p91%2B7KXSMAiAmYrVZuuKKsjzxO0E5VSFARlcZNqmSsv33nu8bvIinB9VvRpWvJeP2JhcY32kJ%2FiTqnBw%3D%3D", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf"
      }
    ], 
    "eligibilityDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/1d6266cea1f5449c8aab07ebf71d2a89?KeyID=2d509c5e&Signature=NXTUvMAYdVLlInyXyg9aoH8n4eXMsdBpHJn3TmlYf3vsTsVy4uKxxOBAvKZ40MJqSrTcFFqs9Yo0nj0H%2FOomAw%3D%3D", 
        "title": "eligibility_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "selfEligible": true, 
    "value": {
      "amount": 5
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/ddbc3b33b2164823a5c497d5af36b0fc?KeyID=2d509c5e&Signature=S4fyrZImKG1FDJlMElMnZjvh%2FpZroxMM%2F8rVPBn2pNksUdvPMdClDoCNzBA4GZijmmdaWGaW4dem4wConbE6AQ%3D%3D", 
        "title": "financial_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Карпенко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Запоріжжя", 
          "streetAddress": "вул. Коцюбинського, 15", 
          "locality": "м. Запоріжя"
        }
      }
    ], 
    "qualificationDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/aebe574f6b47478ebdce84a02fb6b08c?KeyID=2d509c5e&Signature=pB5YbbOEkbYco5dpd%2FsUi%2FurQHxW4EzxeaulDGvJwf2wDn4dHJXKNXPCoOaWzdTzNoM6jHbKrhuXB%2ByqIcGTDg%3D%3D", 
        "title": "qualification_document.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/c368f2394a83454fbd86a8f66c5c1ab4/bids/f3de6918129e4376a1e83586a7c95f10
{
  "access": {
    "token": "3d3dc447e1594259bb3c67759419a1df"
  }, 
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/c368f2394a83454fbd86a8f66c5c1ab4/bids/f3de6918129e4376a1e83586a7c95f10/documents/56ead05c05004ad5bb60aefc3313a0b2?download=e1b8d166c11148fdb711cc7b14a49d37", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:48:39.025278+02:00", 
        "id": "56ead05c05004ad5bb60aefc3313a0b2", 
        "dateModified": "2019-03-28T06:48:39.025291+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/c368f2394a83454fbd86a8f66c5c1ab4/bids/f3de6918129e4376a1e83586a7c95f10/documents/7101d7cc9b714fc4b81a63b1d8525b69?download=d2af848c6d034e11aef8704ae7d7e0c4", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:48:39.025710+02:00", 
        "id": "7101d7cc9b714fc4b81a63b1d8525b69", 
        "dateModified": "2019-03-28T06:48:39.025723+02:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/c368f2394a83454fbd86a8f66c5c1ab4/bids/f3de6918129e4376a1e83586a7c95f10/eligibility_documents/3e91aaed9da24e7db2824dbb7c1048ba?download=1d6266cea1f5449c8aab07ebf71d2a89", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:48:39.026596+02:00", 
        "id": "3e91aaed9da24e7db2824dbb7c1048ba", 
        "dateModified": "2019-03-28T06:48:39.026609+02:00"
      }
    ], 
    "selfEligible": true, 
    "id": "f3de6918129e4376a1e83586a7c95f10", 
    "value": {
      "currency": "UAH", 
      "amount": 5.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/c368f2394a83454fbd86a8f66c5c1ab4/bids/f3de6918129e4376a1e83586a7c95f10/financial_documents/73a5ac1014824c10b2097ae995b50af1?download=ddbc3b33b2164823a5c497d5af36b0fc", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:48:39.026149+02:00", 
        "id": "73a5ac1014824c10b2097ae995b50af1", 
        "dateModified": "2019-03-28T06:48:39.026162+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Карпенко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Коцюбинського, 15", 
          "region": "м. Запоріжжя", 
          "locality": "м. Запоріжя"
        }
      }
    ], 
    "date": "2019-03-28T06:48:39.024763+02:00", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/c368f2394a83454fbd86a8f66c5c1ab4/bids/f3de6918129e4376a1e83586a7c95f10/qualification_documents/6f7e157090c84daf9de073d2582aece5?download=aebe574f6b47478ebdce84a02fb6b08c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:48:39.027081+02:00", 
        "id": "6f7e157090c84daf9de073d2582aece5", 
        "dateModified": "2019-03-28T06:48:39.027094+02:00"
      }
    ]
  }
}

