GET /api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/fbbf7a3e65b74740a3ca9c9efc650e84?acc_token=bab7c97c1f3249709899f382cd84f722 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4c62d14f81e94b8cab0e03452afd982f?KeyID=a8968c46&Signature=volGgRf6xi0M6vkIx%252B9u3reeTsv9oeAbjqu8W70QfhP0p87tyTjYF9iFUeaJsuGBdlBRvDWW8piPgR%2FA0uN8BA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "5e4925e6d9814e20ad5fe8bbbba6ae33", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/fbbf7a3e65b74740a3ca9c9efc650e84/documents/b1b2a899213c426aa29eef6ef7b683cc?download=7775d8cf6c144352908be29e3c030783", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "b1b2a899213c426aa29eef6ef7b683cc", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f9c9786b57ee4cf39ae3018ac8464806?KeyID=a8968c46&Signature=dV%2Fyl%2Fx9gQ72AUJD81gWK2TbmVlzCqTeC%252BcW3H5ODjuwwx700vDIEeeaEMlzYgh%252BEkaAD%252BcQT8WTyal1ISxlDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "0c1c6fcca44d4ce895090caa77748eb0", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "selfEligible": true, 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Карпенко"
        }, 
        "scale": "large", 
        "name": "«Кенгуру»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Коцюбинського, 15", 
          "region": "м. Запоріжжя", 
          "locality": "м. Запоріжя"
        }
      }
    ], 
    "id": "fbbf7a3e65b74740a3ca9c9efc650e84"
  }
}

