PATCH /api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/qualifications/52d1907f064a443bbf87734c6a763289?acc_token=bab7c97c1f3249709899f382cd84f722 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "eligible": false, 
    "qualified": false, 
    "bidID": "fbbf7a3e65b74740a3ca9c9efc650e84", 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "52d1907f064a443bbf87734c6a763289"
  }
}

