PATCH /api/2.5/tenders/2933880765e44c6abd98096c6de321ed/qualifications/ed5af0749d9d4ea8b07f4425e0cdf994?acc_token=437d8c5ad28e44c38d7e7394a20a507b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "eligible": false, 
    "qualified": false, 
    "bidID": "7fdfa3d97d0e4c9a9c80c208c2cef184", 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "ed5af0749d9d4ea8b07f4425e0cdf994"
  }
}

