PATCH /api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e/qualifications/7a7ca809dcb4471ebdd5cdc32fd844d8?acc_token=4c2dfb06830a4541b4794b671b6f4e15 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "eligible": false, 
    "qualified": false, 
    "bidID": "4fddee876f904096a00dd04196685832", 
    "date": "2019-03-18T16:27:34.781917+02:00", 
    "id": "7a7ca809dcb4471ebdd5cdc32fd844d8"
  }
}

