PATCH /api/2.5/tenders/aaae78af64524937a8ac48aace2715db/contracts/34a546e300f747eba8319d63acf266ae?acc_token=49425b1c4f744b00af62c89e9efd36e9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 104
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "period": {
      "startDate": "2019-01-01T00:10:00+02:00", 
      "endDate": "2020-01-01T00:10:00+02:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-01-21T00:00:00+02:00", 
          "endDate": "2019-01-31T00:00:10+02:00"
        }, 
        "id": "920d8bfd71ff4366ab8fd3bae30c1986", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract#1", 
    "period": {
      "startDate": "2019-01-01T00:10:00+02:00", 
      "endDate": "2020-01-01T00:10:00+02:00"
    }, 
    "dateSigned": "2019-01-01T00:10:00+02:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-01-01T00:00:00+02:00", 
    "awardID": "11ac3a57a0ec488b979bc706e1787946", 
    "id": "34a546e300f747eba8319d63acf266ae", 
    "contractID": "UA-2019-01-01-000001-1"
  }
}

