GET /api/2.5/tenders/2933880765e44c6abd98096c6de321ed/documents?acc_token=437d8c5ad28e44c38d7e7394a20a507b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a39ec14b072a45478490dcb6f5617e3e?KeyID=a8968c46&Signature=NqB0VYOfu3RKL9R9MlSV6nbA42E3fqc2SuNrF%252Bl7uBPbB7WUiOF%252BTXgrIFOjTBShsO95hwwtMdnc2PXRNiyYCQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "bdcda9e8c67d4293924f219dfdda9a73", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d89b062c1ed34071b55d76a4c7d3fe84?KeyID=a8968c46&Signature=b2mV%252BQp5ecAD5KEJkM3gTzoqzdNuzLDTrKZZBXWfhJONKquBDHFM3SDmyyRzIUXdDRIQwFjnV2YJAzCKmAOwBQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "73d74d271875432793f8fa2441263f3b", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }
  ]
}

