PATCH /api/2.5/tenders/2933880765e44c6abd98096c6de321ed?acc_token=437d8c5ad28e44c38d7e7394a20a507b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active.tendering"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "selective", 
    "complaintPeriod": {
      "startDate": "2019-01-01T00:00:00+02:00", 
      "endDate": "2019-01-27T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-01-01T00:00:00+02:00", 
      "clarificationsUntil": "2019-01-24T00:00:10+02:00", 
      "endDate": "2019-01-21T00:00:10+02:00", 
      "invalidationDate": "2019-01-01T00:00:00+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-01-31T00:00:10+02:00", 
    "awardCriteria": "lowestCost", 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "2933880765e44c6abd98096c6de321ed", 
    "title": "Послуги шкільних їдалень", 
    "shortlistedFirms": [
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»"
      }
    ], 
    "tenderID": "UA-2019-01-01-000001", 
    "dateModified": "2019-01-01T00:00:00+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2019-01-01T00:00:00+02:00", 
      "endDate": "2019-01-31T00:00:10+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-03-08T00:00:00+02:00"
    }, 
    "procurementMethodType": "competitiveDialogueEU.stage2", 
    "date": "2019-01-01T00:00:00+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-05-08T11:23:35.862469+03:00", 
          "endDate": "2019-06-07T11:23:35.862525+03:00"
        }, 
        "id": "3d45751bf97c40ca9687cf80a0d47ffb", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-05-08T11:23:35.862539+03:00", 
          "endDate": "2019-06-07T11:23:35.862547+03:00"
        }, 
        "id": "832d47f38e544ed887edb53ab5a16217", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }
  }
}

