POST /api/2.5/tenders/2933880765e44c6abd98096c6de321ed/contracts/ad41cf8ed41948ebad74a706fa12947a/documents?acc_token=437d8c5ad28e44c38d7e7394a20a507b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 157
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="contract_second_document.doc"
Content-Type: application/msword

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2933880765e44c6abd98096c6de321ed/contracts/ad41cf8ed41948ebad74a706fa12947a/documents/50b27acc01b7431c82c832bff010e3ce
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "language": "uk", 
    "title": "contract_second_document.doc", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7c7032b7f94b4bc0a40c5460f9d370cd?KeyID=a8968c46&Signature=5yYjfW%252BWKPU%252B%2Fd%2FOwm6wOaAtuM0YEAYV%252BGkuz9KXJ0EFFr746njETwA9e0EA1rwP6oakf1j4D3thry9GeZDPAQ%253D%253D", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "50b27acc01b7431c82c832bff010e3ce", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

