GET /api/2.4/tenders/a9ac809f24974fdba733fa494d18448a/documents?acc_token=6e330b937a244a3aaf02a63e6a634bea HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/19117e3b4c194a808b3027c9d30d978f?KeyID=8a55098c&Signature=0pdWyVUDgzYRb4M7RPNv7HdKabuhNGMxpSa%2FtkI3A5dZ9906MQtKxDWAvH89a1ZN2Ht1LkyY2gVveJw%252BL4BLDA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-09-21T05:24:26.890671+03:00", 
      "id": "e4fe6251a9f549ceaafb33483f870be0", 
      "dateModified": "2018-09-21T05:24:26.890716+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/715fe1f7956b4278be3e5ba00d54d91a?KeyID=8a55098c&Signature=buRlMVGgIRNoTbXqxYQMZDX4XyUYEnA4X3XkcoO%2FmdfU522TJCkZN74NQOQfQ4OL76wVFTPgWh0uR4d6XN%252BYCQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-09-21T05:24:27.078207+03:00", 
      "id": "ea5bc4c6fd204fb4abc5bddbb8876752", 
      "dateModified": "2018-09-21T05:24:27.078276+03:00"
    }
  ]
}

