GET /api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e/documents?acc_token=4c2dfb06830a4541b4794b671b6f4e15 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/06d5550dd67e4939b08fb4990312ca1b?KeyID=a01f97eb&Signature=I2JwcqGgEp6%252B06Prrx%252B3Vaw7%2F1CmnjFRw3iIcRjqayBiIp0JQEH6XweWoU5XigaPXlS783Z1bZeQtVN4AkjoDQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-03-18T16:27:23.591539+02:00", 
      "id": "423e1e02996b44d9b8306a2fd17878d0", 
      "dateModified": "2019-03-18T16:27:23.591564+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/26129bd7d75940ea9e44303941ee85ed?KeyID=a01f97eb&Signature=8RO5tLYqMUfWajhnUogsO8ZSHg22dG%2FhxyUUXbOw93%2Fg0zBhgmV0ikKCOhsgLe098Af0AHCKf5WLrt0baNsCBQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-03-18T16:27:23.797355+02:00", 
      "id": "108a86b04c6f4d9f99c8552acf883aff", 
      "dateModified": "2019-03-18T16:27:23.797379+02:00"
    }
  ]
}

