GET /api/2.5/tenders/2933880765e44c6abd98096c6de321ed/contracts/ad41cf8ed41948ebad74a706fa12947a?acc_token=437d8c5ad28e44c38d7e7394a20a507b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "uk", 
        "title": "contract_first_document.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/bec9569bc8c642be934837780ee0c96a?KeyID=a8968c46&Signature=kMz7zvkeLKLYPJEROgVNBkUUUsPPUQByGSDoTahTFWIMOrCHWlCdZtWy1ZeqW7msrx4kkkbdfN8xnizZTQBICw%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:10:00+02:00", 
        "id": "83a7026f534c422dac89ee121dd1c0f4", 
        "dateModified": "2019-01-01T00:10:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "en", 
        "title": "contract_second_document.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7c7032b7f94b4bc0a40c5460f9d370cd?KeyID=a8968c46&Signature=5yYjfW%252BWKPU%252B%2Fd%2FOwm6wOaAtuM0YEAYV%252BGkuz9KXJ0EFFr746njETwA9e0EA1rwP6oakf1j4D3thry9GeZDPAQ%253D%253D", 
        "format": "application/msword", 
        "title_en": "Title of Document", 
        "description_en": "Description of Document", 
        "datePublished": "2019-01-01T00:10:00+02:00", 
        "documentOf": "tender", 
        "id": "50b27acc01b7431c82c832bff010e3ce", 
        "dateModified": "2019-01-01T00:10:00+02:00"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-01-21T00:00:00+02:00", 
          "endDate": "2019-01-31T00:00:10+02:00"
        }, 
        "id": "3d45751bf97c40ca9687cf80a0d47ffb", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract#1", 
    "period": {
      "startDate": "2019-01-01T00:10:00+02:00", 
      "endDate": "2020-01-01T00:10:00+02:00"
    }, 
    "dateSigned": "2019-01-01T00:10:00+02:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-01-01T00:00:00+02:00", 
    "awardID": "23ebc3d97eb5445c87e75eb8f59d7c55", 
    "id": "ad41cf8ed41948ebad74a706fa12947a", 
    "contractID": "UA-2019-01-01-000001-1"
  }
}

