PATCH /api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/cancellations/783c53f6ba404b11bd498804a86789d0?acc_token=bab7c97c1f3249709899f382cd84f722 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-04-01T01:10:00+03:00", 
    "cancellationOf": "tender", 
    "id": "783c53f6ba404b11bd498804a86789d0"
  }
}

