PUT /api/2.5/tenders/c368f2394a83454fbd86a8f66c5c1ab4/documents/921680ac697c48eabda9528ac1348ac7?acc_token=1b2bc07c22ac43e5811e5b0916da46b7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 196
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy710447191985$
Host: api-sandbox.openprocurement.org


Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/23556a9a854343b5be82a652bd75c3c8?KeyID=2d509c5e&Signature=qLLO7LVODLzb44RVoxR8c%2FLaX0sdjQTrN%2FrvcQpnn2Djj%2FPkMiHJ4ecb0a4t6hCfXpZfZG9o1nNsNYQA3agKDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-28T06:48:37.467938+02:00", 
    "id": "921680ac697c48eabda9528ac1348ac7", 
    "dateModified": "2019-03-28T06:48:37.529728+02:00"
  }
}

