PATCH /api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4?acc_token=bab7c97c1f3249709899f382cd84f722 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 81
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "items": [
      {
        "deliveryDate": {
          "endDate": "2019-05-01T01:00:10+03:00"
        }
      }
    ]
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "tenderPeriod should be extended by 7 days", 
      "location": "body", 
      "name": "data"
    }
  ]
}

