PATCH /api/2.5/tenders/50ac63ffb4c64d589feefdba04de4a6e?acc_token=4c2dfb06830a4541b4794b671b6f4e15 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 153
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "items": [
      {
        "deliveryDate": {
          "endDate": "2019-04-17T16:27:35.081929+02:00"
        }
      }
    ], 
    "tenderPeriod": {
      "endDate": "2019-03-26T16:27:25.483278+02:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "selective", 
    "complaintPeriod": {
      "startDate": "2019-02-18T16:27:24.938230+02:00", 
      "endDate": "2019-03-22T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-02-18T16:27:24.938230+02:00", 
      "clarificationsUntil": "2019-03-21T00:00:00+02:00", 
      "endDate": "2019-03-16T16:27:25.483278+02:00", 
      "invalidationDate": "2019-03-18T16:27:25.767021+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-03-26T16:27:25.483278+02:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-03-18T16:27:24.656885+02:00", 
        "title": "Калорійність", 
        "date": "2019-03-18T16:27:24.443828+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "13b7113703314a68929a917bab447a88", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "50ac63ffb4c64d589feefdba04de4a6e", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/06d5550dd67e4939b08fb4990312ca1b?KeyID=a01f97eb&Signature=I2JwcqGgEp6%252B06Prrx%252B3Vaw7%2F1CmnjFRw3iIcRjqayBiIp0JQEH6XweWoU5XigaPXlS783Z1bZeQtVN4AkjoDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:27:23.591539+02:00", 
        "id": "423e1e02996b44d9b8306a2fd17878d0", 
        "dateModified": "2019-03-18T16:27:23.591564+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/26129bd7d75940ea9e44303941ee85ed?KeyID=a01f97eb&Signature=8RO5tLYqMUfWajhnUogsO8ZSHg22dG%2FhxyUUXbOw93%2Fg0zBhgmV0ikKCOhsgLe098Af0AHCKf5WLrt0baNsCBQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:27:23.797355+02:00", 
        "id": "108a86b04c6f4d9f99c8552acf883aff", 
        "dateModified": "2019-03-18T16:27:23.797379+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/f65ad55f71b143a1b476a14ec28fcf47?KeyID=a01f97eb&Signature=Rd4shKzz42PQZ1AwUUum7iSTCXh5yfZe9kujqHvYCTttDL7qJ6GCoo1fBwjfag7mHElHK7jXpx4YhIGgKEaYAQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:27:23.797355+02:00", 
        "id": "108a86b04c6f4d9f99c8552acf883aff", 
        "dateModified": "2019-03-18T16:27:24.046809+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "shortlistedFirms": [
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»"
      }
    ], 
    "tenderID": "UA-2019-03-18-000001", 
    "dateModified": "2019-03-18T16:27:25.778856+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2019-02-18T16:27:24.938230+02:00", 
      "endDate": "2019-03-26T16:27:25.483278+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-05-01T00:00:00+02:00"
    }, 
    "procurementMethodType": "competitiveDialogueEU.stage2", 
    "date": "2019-03-18T16:27:23.365436+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-07T16:25:23.280978+02:00", 
          "endDate": "2019-04-17T16:27:35.081929+02:00"
        }, 
        "id": "4e157e9f244b47d69e8548f4c9b662e2", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

