POST /api/2.5/tenders/2933880765e44c6abd98096c6de321ed/bids/1f12fd2c196d4995a58c3a6e82e000a9/documents?acc_token=0dffffc62eaa4e4787b1ed1683d20355 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Proposal_top_secrets.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2933880765e44c6abd98096c6de321ed/bids/1f12fd2c196d4995a58c3a6e82e000a9/documents/ec82110efd774b089798df2dfc444600
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "public", 
    "language": "uk", 
    "title": "Proposal_top_secrets.pdf", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2933880765e44c6abd98096c6de321ed/bids/1f12fd2c196d4995a58c3a6e82e000a9/documents/ec82110efd774b089798df2dfc444600?download=417cca6fbdd44430a77e90a41fc2cee8", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "ec82110efd774b089798df2dfc444600", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

