POST /api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/f74c53e1c5994792be38bf1f5eddc97f/qualification_documents?acc_token=8896b59ed7a64f12a0f9f93d529ce0bc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 152
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="qualification_document.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/f74c53e1c5994792be38bf1f5eddc97f/qualification_documents/487210f7f8564c399baf3b51d0fe7be5
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "public", 
    "language": "uk", 
    "title": "qualification_document.pdf", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/f74c53e1c5994792be38bf1f5eddc97f/qualification_documents/487210f7f8564c399baf3b51d0fe7be5?download=7b3ff6d13060484da2d4a098d3834774", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "487210f7f8564c399baf3b51d0fe7be5", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

