POST /api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/f74c53e1c5994792be38bf1f5eddc97f/documents?acc_token=8896b59ed7a64f12a0f9f93d529ce0bc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Proposal_top_secrets.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/f74c53e1c5994792be38bf1f5eddc97f/documents/96b00c52ce4e4e598d093eac7351c0a7
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "public", 
    "language": "uk", 
    "title": "Proposal_top_secrets.pdf", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/bids/f74c53e1c5994792be38bf1f5eddc97f/documents/96b00c52ce4e4e598d093eac7351c0a7?download=f97c89de0c7540afbe548e21368afa01", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "96b00c52ce4e4e598d093eac7351c0a7", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

