POST /api/2.5/tenders/aaae78af64524937a8ac48aace2715db/cancellations/b6c1912c502c4b208ef31fb5b2bf749f/documents?acc_token=49425b1c4f744b00af62c89e9efd36e9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy520558332645$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/aaae78af64524937a8ac48aace2715db/cancellations/b6c1912c502c4b208ef31fb5b2bf749f/documents/740d5b9c487144579c5f1f7dd86ac596
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1df780ed0a4b4a69949eeb95d11f5b94?KeyID=f8180d36&Signature=669INjS6BW4sGhUJjRe54tyiGxkSXMYdVd%252B4qy8SakkY8Yzu%252BRTToufskOSiEqXVB7XeboJ%252Brw1MkTlrPJggBg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "740d5b9c487144579c5f1f7dd86ac596", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

