POST /api/2.5/tenders/aaae78af64524937a8ac48aace2715db/bids/c65cc2e9e1344faa90371b52aed104d6/documents?acc_token=27c2ebabf7ce4154880e8e722cf9babd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy70080766148$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/aaae78af64524937a8ac48aace2715db/bids/c65cc2e9e1344faa90371b52aed104d6/documents/f7eec34deeba497abc4d97a8a47a2b06
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "public", 
    "language": "uk", 
    "title": "Proposal.pdf", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/aaae78af64524937a8ac48aace2715db/bids/c65cc2e9e1344faa90371b52aed104d6/documents/f7eec34deeba497abc4d97a8a47a2b06?download=9f882af15e814e91bdfbd908352ca2e1", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "f7eec34deeba497abc4d97a8a47a2b06", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

