POST /api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/documents?acc_token=bab7c97c1f3249709899f382cd84f722 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 136
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Notice.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bde976eab58547c8b33403fd4e53a9d4/documents/8774a99c45324f7d80f765c09379be0f
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5646c34840824318a90df0212ff89317?KeyID=a8968c46&Signature=V6A0Ub4OSSU%2F5QdX0rC02oOyErSIibhNpbFKKo9MUsiQtltREk8j47Etcp%2F2afEa4Vbty%252BOwMjQpftsrEFfADg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "8774a99c45324f7d80f765c09379be0f", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

