POST /api/2.5/tenders/16a0247dd30047b490e2890ebc1530ff/awards/a83c789e3961471aba2da545a53b46cc/complaints?acc_token=9f9fdef7a1c04703ab6df6763b335367 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 775
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "title": "complaint title", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк", 
        "email": "soleksuk@gmail.com"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/16a0247dd30047b490e2890ebc1530ff/awards/a83c789e3961471aba2da545a53b46cc/complaints/ae25373d3ed443979c8ccf1279e74c51

{
  "access": {
    "token": "dd35e97eb67c4ccd83481c81dd2d2d4c"
  }, 
  "data": {
    "status": "draft", 
    "description": "complaint description", 
    "title": "complaint title", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "complaintID": "UA-2019-03-18-000001.5", 
    "date": "2019-03-18T09:26:22.890850+02:00", 
    "type": "claim", 
    "id": "ae25373d3ed443979c8ccf1279e74c51"
  }
}

