PATCH /api/2.5/tenders/4bdc8f70ca4d45b0956ab3afbadcc50c/awards/32a97e4b24054e2db5f8d16d4bdd4fc0/complaints/f8df28d4f77d43f3b2bfc7bf809df861?acc_token=1ed3777258d4412e8ab223b6582cfa11 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 52
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": false, 
    "dateAnswered": "2019-03-28T06:47:16.809549+02:00", 
    "dateSubmitted": "2019-03-28T06:47:16.264864+02:00", 
    "complaintID": "UA-2019-03-28-000001.6", 
    "date": "2019-03-28T06:47:16.961693+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "f8df28d4f77d43f3b2bfc7bf809df861"
  }
}

