POST /api/2.5/tenders/8f11f82d19b64b859827cc941fd7f839/awards/be28a579af2b47788dfb441328f844bc/complaints/4e28a045331943eb89c6be15c7a9f570/documents?acc_token=8d1e5808a00649e591881308a0be9958 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 335
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3cec94f61e6646d0afc3e00c0c83fa15?KeyID=a0b3a3fd&Signature=zWG4HZWIlViH%2BgTyWRhuKSH5RG7SH6dKOzTTDid7aZYmSgvbGMqzRo9BQdBWeYj5J3bviXTvNGFbK5d29FT0BQ%3D%3D", 
    "title": "Complaint_Attachement.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/8f11f82d19b64b859827cc941fd7f839/awards/be28a579af2b47788dfb441328f844bc/complaints/4e28a045331943eb89c6be15c7a9f570/documents/3444ef6c99be465b8f698c7a43ba5b8e
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3cec94f61e6646d0afc3e00c0c83fa15?KeyID=a0b3a3fd&Signature=ZV85ZDeTPAUjPKT5xlnX%2F1LQoapRnDH7CiAotn8UTvD1SavbkHgxPpCTrgkIDI2ZTQ78b9sf2kH5jpVUg7ZXBg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "3444ef6c99be465b8f698c7a43ba5b8e", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

