PATCH /api/2.4/tenders/94e7af37e39840cd925a424cda8e0bb8/complaints/48debdda14934bf5a89d2136bc2e9334?acc_token=aa4127005f3348c8afd41561f28044a2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "claim"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "claim", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/d9985c623b874186bf1c4c0c0a96b1d7?KeyID=82a13eea&Signature=h1i5X3GCuWBjF%2Fj8iX5qHlSgvlnWt%2FPeR4CPW2wgqYacapXdYpjj5q%252BTYFHQjXmUpwoMQtFnyzmKXpgPmXorDA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-14T19:03:47.820310+03:00", 
        "id": "b720acb4ced143b0bfdd7629c9daaea1", 
        "dateModified": "2018-08-14T19:03:47.820330+03:00"
      }
    ], 
    "description": "complaint description", 
    "title": "complaint title", 
    "dateSubmitted": "2018-08-14T19:03:47.944883+03:00", 
    "complaintID": "UA-2018-08-14-000001.1", 
    "date": "2018-08-14T19:03:47.947191+03:00", 
    "type": "claim", 
    "id": "48debdda14934bf5a89d2136bc2e9334"
  }
}

