PATCH /api/2.4/tenders/94e7af37e39840cd925a424cda8e0bb8/complaints/88e3c0b142cc40f39d82ea1e04fae8df?acc_token=9cb04ce35ae6465aa0c3f5e28983b19a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 52
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": false, 
    "dateAnswered": "2018-08-14T19:03:48.444764+03:00", 
    "dateSubmitted": "2018-08-14T19:03:48.063045+03:00", 
    "complaintID": "UA-2018-08-14-000001.2", 
    "date": "2018-08-14T19:03:48.576928+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "88e3c0b142cc40f39d82ea1e04fae8df"
  }
}

