POST /api/2.5/tenders/40c17dbea3ba43fab389cc55c80183fc/complaints/39ddbb1c096f483cbdec90ab91accf0f/documents?acc_token=3621126533bf4e96bb2cda7835e6e159 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 335
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/45ed78e325084af8afc0fd7db98d2fee?KeyID=a8968c46&Signature=0bZ4hn8Ofl6EJRMG2JUdgHCFIbLKJ1d6fjaaWBZNRwZ2N%2Bk5J1d4dNwfOJ2wXQZxMEXPMSjXX1bWhkeqhx5TAA%3D%3D", 
    "title": "Complaint_Attachement.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/40c17dbea3ba43fab389cc55c80183fc/complaints/39ddbb1c096f483cbdec90ab91accf0f/documents/5e007ea52d484ec7a44475b657a225c5
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/45ed78e325084af8afc0fd7db98d2fee?KeyID=a8968c46&Signature=TroU1amSiqtdBU%252BPQ3QUpbCuwyK62MJFUn8vnfJ%252B%252Bkdv78ibtm4qinFx9VlgFZTEsItVksl2IA0YVdqSIBaEBg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "5e007ea52d484ec7a44475b657a225c5", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

