PATCH /api/2.4/tenders/5723be5db56f4853b0a5f6ae6153b82f/complaints/f130e8d0ea584fbbb6474f22993397ec?acc_token=2d0d79868f2a4604a37ad83b34154ead HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 52
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json

{
  "data": {
    "status": "resolved", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": false, 
    "dateAnswered": "2018-09-21T05:23:02.468116+03:00", 
    "dateSubmitted": "2018-09-21T05:23:01.930493+03:00", 
    "complaintID": "UA-2018-09-21-000001.2", 
    "date": "2018-09-21T05:23:02.617097+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "f130e8d0ea584fbbb6474f22993397ec"
  }
}

