POST /api/2.5/tenders/16a0247dd30047b490e2890ebc1530ff/complaints/651324632cf84f969f408745ffb1a5f3/documents?acc_token=22968ca055314bbeae3d8bdf1f7c304f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 341
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/aad62bc595df41bba36252b18c46b74a?KeyID=eb72328f&Signature=KveDswJSRgNFAd%2Fc23xi58CTlYWo7uju3zusoR801uCesnLpMFmGgWg4svzNtuYZwTfm%2BL9L9nptvHqi6t3uBw%3D%3D", 
    "title": "Complaint_Attachement.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/16a0247dd30047b490e2890ebc1530ff/complaints/651324632cf84f969f408745ffb1a5f3/documents/2b383169f910444bad9abc15865458a7

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/aad62bc595df41bba36252b18c46b74a?KeyID=eb72328f&Signature=oEyNYCad2SX%2FAmvHZBTS2cP%2F4hWU60H%252BPuk8F4qwjYJOZZxP8O0H8Ps5esAQHP3i33aNVFkiR4ZEgH%2Ff%2Fw8OAQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-18T09:26:20.819395+02:00", 
    "id": "2b383169f910444bad9abc15865458a7", 
    "dateModified": "2019-03-18T09:26:20.819409+02:00"
  }
}

