POST /api/2.4/tenders/a7e6332ad01341cca08e5560a337c884/complaints/0dbc2745da554c4b9c41402382555aad/documents?acc_token=196228e2a8ba44858b3bff1cc06ab90e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 339
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/6f9a8f3490e542799c12ebf9b7f984df?KeyID=d0d2cc30&Signature=5k6Owkg3qqMIsYzjlxanxLt%2FTVXrvgJGSXbX0FCt1rSoHEY6Y8US0VDT2zqGmLe0wmAl7RyoiOkH1J2NTBZxCw%3D%3D", 
    "title": "Complaint_Attachement.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/a7e6332ad01341cca08e5560a337c884/complaints/0dbc2745da554c4b9c41402382555aad/documents/100734ac9ca84c71aa6a7f02d7c20640

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/6f9a8f3490e542799c12ebf9b7f984df?KeyID=d0d2cc30&Signature=obeQrCxakchZEH8yuH9usHGZlCuNpCmgr5nX0U731d%252BHy0yBc10D3p6GqUyomV6SL5RDIcE1zAtS5pavQdw6Dg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-14T18:52:57.778008+03:00", 
    "id": "100734ac9ca84c71aa6a7f02d7c20640", 
    "dateModified": "2018-08-14T18:52:57.778030+03:00"
  }
}

