PATCH /api/2.5/tenders/16a0247dd30047b490e2890ebc1530ff/complaints/a22528f335574964b5a6dab0c14f6b96?acc_token=0f013ac6187a4fb68ed0157057122c7c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 52
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "satisfied": false
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "resolved", 
    "description": "complaint description", 
    "title": "complaint title", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": false, 
    "dateAnswered": "2019-03-18T09:26:21.120712+02:00", 
    "dateSubmitted": "2019-03-18T09:26:20.912293+02:00", 
    "complaintID": "UA-2019-03-18-000001.2", 
    "date": "2019-03-18T09:26:21.173242+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "a22528f335574964b5a6dab0c14f6b96"
  }
}

