PATCH /api/2.4/tenders/c04c4b2ab1994ea3b48b80055b9db735?acc_token=a3cea2be754e47b2812f941112035567 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 161
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "milestones": [
      {}, 
      {
        "description": "Підозрілий опис", 
        "title": "anotherEvent"
      }
    ]
  }
}


200 OK
Content-Type: application/json

{
  "data": {
    "procurementMethod": "open", 
    "status": "active.enquiries", 
    "milestones": [
      {
        "code": "prepayment", 
        "sequenceNumber": 0, 
        "title": "signingTheContract", 
        "duration": {
          "type": "banking", 
          "days": 5
        }, 
        "percentage": 45.55, 
        "type": "financing", 
        "id": "7013ef14729448c48737975336477ecb"
      }, 
      {
        "code": "postpayment", 
        "description": "Підозрілий опис", 
        "sequenceNumber": 1, 
        "title": "anotherEvent", 
        "duration": {
          "type": "calendar", 
          "days": 7
        }, 
        "percentage": 54.45, 
        "type": "financing", 
        "id": "2fdbe2d1f4524cd88ac2654f8e298480"
      }
    ], 
    "awardCriteria": "lowestCost", 
    "tenderPeriod": {
      "startDate": "2019-01-04T18:37:46.381580+02:00", 
      "endDate": "2019-01-11T18:37:46.381580+02:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-12-30T18:37:46.381580+02:00", 
          "endDate": "2019-01-02T18:37:46.381580+02:00"
        }, 
        "id": "94084e6b9bd64957beba3782938ed37a", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "procurementMethodType": "belowThreshold", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2018-12-28T18:37:47.903773+02:00", 
    "next_check": "2019-01-04T18:37:46.381580+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "enquiryPeriod": {
      "startDate": "2018-12-28T18:37:47.903734+02:00", 
      "endDate": "2019-01-04T18:37:46.381580+02:00"
    }, 
    "owner": "broker", 
    "dateModified": "2018-12-28T18:37:47.952044+02:00", 
    "id": "c04c4b2ab1994ea3b48b80055b9db735", 
    "tenderID": "UA-2018-12-28-000001"
  }
}

