DELETE /api/2.5/tenders/cbc95e54451a454a991aef6965777305/lots/2000cd65adfb441f9f00a7a3d98c7b50?acc_token=d0f8b71cd5d44ff39e34b95674a5aa4d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 422 Unprocessable Entity
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": [
        {
          "relatedLot": [
            "relatedLot should be one of the lots."
          ]
        }, 
        {
          "relatedLot": [
            "relatedLot should be one of the lots."
          ]
        }
      ], 
      "location": "body", 
      "name": "milestones"
    }
  ]
}

