POST /api/2.5/tenders/e87a7400cc144ac9b69ec677303e3721/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 975
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "selfEligible": true, 
    "selfQualified": true, 
    "lotValues": [
      {
        "relatedLot": "eb5716cccb9747749c7ab89824466345"
      }, 
      {
        "relatedLot": "5f61ca4e5db1466f9154216af87a5638", 
        "subcontractingDetails": "ДКП «Укр Прінт», Україна"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137227", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 35", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e87a7400cc144ac9b69ec677303e3721/bids/76be5c3a95f74c0fa3cbacfa8ec84c0f
{
  "access": {
    "token": "c0260e45eb0a4fc9af1b0d6df8cb89cf"
  }, 
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "eb5716cccb9747749c7ab89824466345", 
        "date": "2019-01-01T00:00:00+02:00", 
        "status": "pending"
      }, 
      {
        "relatedLot": "5f61ca4e5db1466f9154216af87a5638", 
        "date": "2019-01-01T00:00:00+02:00", 
        "status": "pending", 
        "subcontractingDetails": "ДКП «Укр Прінт», Україна"
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137227", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 35", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "76be5c3a95f74c0fa3cbacfa8ec84c0f"
  }
}

