PATCH /api/2.5/tenders/e079d0f147d74fcebf76f53f477ad16c/bids/7d3f302088144e8c9a3713a68be51e56?acc_token=1486edcd22e34025b48fbaf2a5003f7a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 188
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "faa9f6fda9cb4f63bce56c634875eb06", 
        "subcontractingDetails": "ДКП «Орфей»"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "faa9f6fda9cb4f63bce56c634875eb06", 
        "date": "2019-04-01T01:00:00+03:00", 
        "status": "pending", 
        "subcontractingDetails": "ДКП «Орфей»"
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "7d3f302088144e8c9a3713a68be51e56"
  }
}

