PATCH /api/2.5/tenders/b0aac9eeadd141df8d39a01f620c6094/bids/66bfed6856374a99b035e4247079e82c?acc_token=2ec79c52660c4444a2759da536d5b705 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 98
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "e0b3133acf604b108de4823789caca6e"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "e0b3133acf604b108de4823789caca6e", 
        "date": "2019-03-18T16:26:15.722351+02:00", 
        "status": "pending"
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-03-18T16:26:15.721841+02:00", 
    "id": "66bfed6856374a99b035e4247079e82c"
  }
}

