PATCH /api/2.4/tenders/aaa82d074ff7415589f1142ca32078b1/bids/364e413e0dd5478583162504b755a27c?acc_token=f9a73abb4938423ea22e0d3aa62387bd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 188
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "5eecb2ade4d34b0ebb6ce28a02225580", 
        "subcontractingDetails": "ДКП «Орфей»"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "5eecb2ade4d34b0ebb6ce28a02225580", 
        "date": "2018-09-21T05:23:56.613354+03:00", 
        "status": "pending", 
        "subcontractingDetails": "ДКП «Орфей»"
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2018-09-21T05:23:56.612078+03:00", 
    "id": "364e413e0dd5478583162504b755a27c"
  }
}

