GET /api/2.5/tenders/c79e08c6a0e5419cabffd9243348f55e/bids/1cfa6572b5844df4bea8e46def1fef70?acc_token=eb5830a6d00f4ac7837a3aa450c5de1a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "1cfa6572b5844df4bea8e46def1fef70"
  }
}

