GET /api/2.5/tenders/b0aac9eeadd141df8d39a01f620c6094/qualifications?acc_token=b98389283c364068933bdda1f1d6e207 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "pending", 
      "lotID": "e0b3133acf604b108de4823789caca6e", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "a0b3af50282e4673aa7b715c39e4ba97", 
      "date": "2019-03-18T16:26:18.313685+02:00", 
      "id": "88c74c6adeb84b82affbc8ad98fbcbc5"
    }, 
    {
      "status": "pending", 
      "lotID": "e0b3133acf604b108de4823789caca6e", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "66bfed6856374a99b035e4247079e82c", 
      "date": "2019-03-18T16:26:18.314207+02:00", 
      "id": "a65eb89160d24789bc479b69b9c181ca"
    }, 
    {
      "status": "pending", 
      "lotID": "e0b3133acf604b108de4823789caca6e", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "a41f59b8f01743c0991f1309f460d1a9", 
      "date": "2019-03-18T16:26:18.314618+02:00", 
      "id": "d5ee3c0f8e384ffbbf6512fcbb0ca51a"
    }
  ]
}

