GET /api/2.5/tenders/e87a7400cc144ac9b69ec677303e3721?acc_token=bf617dbbe0274dbcb038442a3d21275c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.stage2.pending", 
    "complaintPeriod": {
      "startDate": "2018-11-21T00:00:00+02:00", 
      "endDate": "2018-12-18T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2018-11-21T00:00:00+02:00", 
      "clarificationsUntil": "2018-12-17T00:00:00+02:00", 
      "endDate": "2018-12-12T00:00:00+02:00", 
      "invalidationDate": "2019-01-01T00:00:00+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "e87a7400cc144ac9b69ec677303e3721", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "eb5716cccb9747749c7ab89824466345"
      }, 
      {
        "status": "unsuccessful", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 400.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "5f61ca4e5db1466f9154216af87a5638"
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2018-12-22T00:00:00+02:00", 
      "endDate": "2019-01-01T00:00:00+02:00"
    }, 
    "tenderID": "UA-2019-01-01-000001", 
    "dateModified": "2019-01-01T00:00:00+02:00", 
    "numberOfBids": 3, 
    "tenderPeriod": {
      "startDate": "2018-11-21T00:00:00+02:00", 
      "endDate": "2018-12-22T00:00:00+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "lotID": "eb5716cccb9747749c7ab89824466345", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "589fb7d7812e4579b2222bbc4e888691", 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "4cc1e43fd69a41ffa9d749e331ad8169"
      }, 
      {
        "status": "active", 
        "lotID": "eb5716cccb9747749c7ab89824466345", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "48bbcc4b502f4186a6bc03d66daf78fd", 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "5bc411f9c3bf4b6b86f31651db03f335"
      }, 
      {
        "status": "active", 
        "lotID": "eb5716cccb9747749c7ab89824466345", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "76be5c3a95f74c0fa3cbacfa8ec84c0f", 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "74205eef418e4f3cb55919750c172427"
      }
    ], 
    "procurementMethodType": "competitiveDialogueEU", 
    "date": "2019-01-01T00:00:00+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "eb5716cccb9747749c7ab89824466345", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-05-08T06:49:21.594579+03:00", 
          "endDate": "2019-06-07T06:49:21.594605+03:00"
        }, 
        "id": "0b5822816e8e41ce82f18106e70f9ded", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }, 
      {
        "relatedLot": "5f61ca4e5db1466f9154216af87a5638", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-05-08T06:49:21.594619+03:00", 
          "endDate": "2019-06-07T06:49:21.594627+03:00"
        }, 
        "id": "d5b43472c10c4f288b1415a9a1c9fed1", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "id": "589fb7d7812e4579b2222bbc4e888691", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "48bbcc4b502f4186a6bc03d66daf78fd", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "76be5c3a95f74c0fa3cbacfa8ec84c0f", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137227", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 900.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

