GET /api/2.5/tenders/e079d0f147d74fcebf76f53f477ad16c?acc_token=5ae97b21ba424d95bb8004e7f3835124 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "complete", 
    "complaintPeriod": {
      "startDate": "2019-02-19T01:00:00+03:00", 
      "endDate": "2019-03-18T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-02-19T01:00:00+03:00", 
      "clarificationsUntil": "2019-03-15T01:00:00+03:00", 
      "endDate": "2019-03-12T01:00:00+03:00", 
      "invalidationDate": "2019-04-01T01:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "e079d0f147d74fcebf76f53f477ad16c", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "faa9f6fda9cb4f63bce56c634875eb06"
      }, 
      {
        "status": "unsuccessful", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 400.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "d0775ff07b4d4b88976c6eedc6df8fb2"
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2019-03-22T01:00:00+03:00", 
      "endDate": "2019-04-01T01:00:00+03:00"
    }, 
    "tenderID": "UA-2019-04-01-000001", 
    "dateModified": "2019-04-01T01:00:00+03:00", 
    "numberOfBids": 3, 
    "tenderPeriod": {
      "startDate": "2019-02-19T01:00:00+03:00", 
      "endDate": "2019-03-22T01:00:00+03:00"
    }, 
    "stage2TenderID": "863817cf11d640efae1cab0922c1d341", 
    "qualifications": [
      {
        "status": "active", 
        "lotID": "faa9f6fda9cb4f63bce56c634875eb06", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "7d3f302088144e8c9a3713a68be51e56", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "b8c0f79680aa46589e33167f790919b0"
      }, 
      {
        "status": "active", 
        "lotID": "faa9f6fda9cb4f63bce56c634875eb06", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "c272f463989c4fd3b38beb15a21e3d82", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "cb2b55e888de4daabe7fae110aec211f"
      }, 
      {
        "status": "active", 
        "lotID": "faa9f6fda9cb4f63bce56c634875eb06", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "4db56ab06ab94a9a92fd67b7cf21f35d", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "d955b773f4a24366b32aa024d5315a60"
      }
    ], 
    "procurementMethodType": "competitiveDialogueEU", 
    "date": "2019-04-01T01:00:00+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "faa9f6fda9cb4f63bce56c634875eb06", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-21T00:00:00+02:00", 
          "endDate": "2019-05-21T00:00:00+02:00"
        }, 
        "id": "431f103482084ba3aef4afb82d5324fb", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }, 
      {
        "relatedLot": "d0775ff07b4d4b88976c6eedc6df8fb2", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-21T00:00:00+02:00", 
          "endDate": "2019-05-21T00:00:00+02:00"
        }, 
        "id": "b2a658f3fe6649dda848fa8f61657bdc", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "selfEligible": true, 
        "lotValues": [
          {
            "relatedLot": "faa9f6fda9cb4f63bce56c634875eb06", 
            "date": "2019-04-01T01:00:00+03:00", 
            "status": "active", 
            "subcontractingDetails": "ДКП «Орфей»"
          }
        ], 
        "selfQualified": true, 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "7d3f302088144e8c9a3713a68be51e56"
      }, 
      {
        "status": "active", 
        "selfEligible": true, 
        "lotValues": [
          {
            "relatedLot": "faa9f6fda9cb4f63bce56c634875eb06", 
            "date": "2019-04-01T01:00:00+03:00", 
            "status": "active"
          }
        ], 
        "selfQualified": true, 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "c272f463989c4fd3b38beb15a21e3d82"
      }, 
      {
        "status": "active", 
        "selfEligible": true, 
        "lotValues": [
          {
            "relatedLot": "faa9f6fda9cb4f63bce56c634875eb06", 
            "date": "2019-04-01T01:00:00+03:00", 
            "status": "active"
          }
        ], 
        "selfQualified": true, 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137227", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "4db56ab06ab94a9a92fd67b7cf21f35d"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 900.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

