GET /api/2.5/tenders/000c8f7d39974ccfa431f03fd95eedd5?acc_token=c2cf440d719a468c91384967750da24a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification", 
    "complaintPeriod": {
      "startDate": "2019-02-26T06:48:25.545043+02:00", 
      "endDate": "2019-03-24T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-02-26T06:48:25.545043+02:00", 
      "clarificationsUntil": "2019-03-21T06:48:25.545043+02:00", 
      "endDate": "2019-03-18T06:48:25.545043+02:00", 
      "invalidationDate": "2019-03-28T06:48:25.252140+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "000c8f7d39974ccfa431f03fd95eedd5", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-03-28T06:48:24.894080+02:00", 
        "id": "84376ace1c0042948424738474323549"
      }, 
      {
        "status": "unsuccessful", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 400.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-03-28T06:48:25.657508+02:00", 
        "id": "2128fe74540742438dc3e16e02b9876c"
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2019-03-28T06:48:25.646954+02:00"
    }, 
    "tenderID": "UA-2019-03-28-000001", 
    "dateModified": "2019-03-28T06:48:25.657508+02:00", 
    "numberOfBids": 3, 
    "tenderPeriod": {
      "startDate": "2019-02-26T06:48:25.545043+02:00", 
      "endDate": "2019-03-28T06:48:25.545043+02:00"
    }, 
    "qualifications": [
      {
        "status": "pending", 
        "lotID": "84376ace1c0042948424738474323549", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "d1bb3d8e92754c43a615dab375e2a109", 
        "date": "2019-03-28T06:48:25.649413+02:00", 
        "id": "d24903a2009b46fd8ad52eaf2e5a1c52"
      }, 
      {
        "status": "pending", 
        "lotID": "84376ace1c0042948424738474323549", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "0a32e33894d444038342aeecc9780fca", 
        "date": "2019-03-28T06:48:25.649774+02:00", 
        "id": "c46b155e51d641daaecde2f17cee2332"
      }, 
      {
        "status": "pending", 
        "lotID": "84376ace1c0042948424738474323549", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "355f5962dc954c85a0ae704769081070", 
        "date": "2019-03-28T06:48:25.650090+02:00", 
        "id": "d973b45651634fd9b1b8d22e57ef11a1"
      }
    ], 
    "procurementMethodType": "competitiveDialogueEU", 
    "date": "2019-03-28T06:48:25.657508+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "84376ace1c0042948424738474323549", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-17T06:47:07.975510+02:00", 
          "endDate": "2019-05-17T06:47:07.975543+02:00"
        }, 
        "id": "ed7e8081247d4a03bcba687edbce3a53", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }, 
      {
        "relatedLot": "2128fe74540742438dc3e16e02b9876c", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-17T06:47:07.975557+02:00", 
          "endDate": "2019-05-17T06:47:07.975571+02:00"
        }, 
        "id": "584e0a542e594e61aa7511171763415f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "bids": [
      {
        "status": "pending", 
        "id": "d1bb3d8e92754c43a615dab375e2a109", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "pending", 
        "id": "0a32e33894d444038342aeecc9780fca", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "pending", 
        "id": "355f5962dc954c85a0ae704769081070", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137227", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 900.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

