PATCH /api/2.5/tenders/e079d0f147d74fcebf76f53f477ad16c/lots/d0775ff07b4d4b88976c6eedc6df8fb2?acc_token=5ae97b21ba424d95bb8004e7f3835124 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "value": {
      "amount": 400
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №2", 
    "title": "Лот №2", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 400.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "d0775ff07b4d4b88976c6eedc6df8fb2"
  }
}

