PATCH /api/2.5/tenders/184103734dab411bb82825f6d09bd241?acc_token=be0988edbb994fa288dcaea8f7e20870 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active.tendering"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "selective", 
    "complaintPeriod": {
      "startDate": "2019-03-18T16:26:22.724393+02:00", 
      "endDate": "2019-04-13T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-03-18T16:26:22.724393+02:00", 
      "clarificationsUntil": "2019-04-11T00:00:00+02:00", 
      "endDate": "2019-04-07T16:26:22.724393+02:00", 
      "invalidationDate": "2019-03-18T16:26:24.127978+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-04-17T17:26:22.724393+03:00", 
    "awardCriteria": "lowestCost", 
    "owner": "broker", 
    "id": "184103734dab411bb82825f6d09bd241", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2019-05-23T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-03-18T16:26:24.127616+02:00", 
        "id": "e0b3133acf604b108de4823789caca6e"
      }, 
      {
        "status": "active", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2019-05-23T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 400.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-03-18T16:26:24.127616+02:00", 
        "id": "60821104ce234bb8ae3295cfd87e2aee"
      }
    ], 
    "shortlistedFirms": [
      {
        "lots": [
          {
            "id": "e0b3133acf604b108de4823789caca6e"
          }
        ], 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»"
      }, 
      {
        "lots": [
          {
            "id": "e0b3133acf604b108de4823789caca6e"
          }, 
          {
            "id": "60821104ce234bb8ae3295cfd87e2aee"
          }
        ], 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»"
      }, 
      {
        "lots": [
          {
            "id": "e0b3133acf604b108de4823789caca6e"
          }, 
          {
            "id": "60821104ce234bb8ae3295cfd87e2aee"
          }
        ], 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»"
      }
    ], 
    "tenderID": "UA-2019-03-18-000002", 
    "dateModified": "2019-03-18T16:26:24.155759+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2019-03-18T16:26:22.724393+02:00", 
      "endDate": "2019-04-17T16:26:22.724393+02:00"
    }, 
    "title_en": "Services in school canteens", 
    "procurementMethodType": "competitiveDialogueEU.stage2", 
    "date": "2019-03-18T16:26:24.127616+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "e0b3133acf604b108de4823789caca6e", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-07T16:25:23.279560+02:00", 
          "endDate": "2019-05-07T16:25:23.279783+02:00"
        }, 
        "id": "135b27e1cc984d29a59dd36c9c01817d", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }, 
      {
        "relatedLot": "60821104ce234bb8ae3295cfd87e2aee", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-07T16:25:23.279854+02:00", 
          "endDate": "2019-05-07T16:25:23.279919+02:00"
        }, 
        "id": "18ddb94db5164c01be749aa960dca6fa", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 900.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }
  }
}

