PATCH /api/2.5/tenders/b0aac9eeadd141df8d39a01f620c6094/qualifications/88c74c6adeb84b82affbc8ad98fbcbc5?acc_token=b98389283c364068933bdda1f1d6e207 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "lotID": "e0b3133acf604b108de4823789caca6e", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "a0b3af50282e4673aa7b715c39e4ba97", 
    "date": "2019-03-18T16:26:18.991644+02:00", 
    "id": "88c74c6adeb84b82affbc8ad98fbcbc5"
  }
}

