PATCH /api/2.4/tenders/9cd95216cbd74c4c9e268142351d73b7/awards/0281ac2f39d64312bf5e53b9807e5549/complaints/f53abd5930694b428b16e75442735a8b HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "accepted"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "accepted", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/9cd95216cbd74c4c9e268142351d73b7/awards/0281ac2f39d64312bf5e53b9807e5549/complaints/f53abd5930694b428b16e75442735a8b/documents/56778cea2fa549349908cccbbc2dbc28?download=0b0dd26e7e9040f084b5bd79237ac425", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-02-06T06:11:53.934961+02:00", 
        "id": "56778cea2fa549349908cccbbc2dbc28", 
        "dateModified": "2019-02-06T06:11:53.934976+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "scale": "micro", 
      "name": "ДКП «Школяр»", 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2019-02-06T06:11:55.237673+02:00", 
    "dateSubmitted": "2019-02-06T06:11:53.996975+02:00", 
    "complaintID": "UA-2019-02-06-000001.1", 
    "date": "2019-02-06T06:11:55.243471+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "f53abd5930694b428b16e75442735a8b"
  }
}

