PATCH /api/2.5/tenders/45041579bba84caf848f885741c0d7ed/awards/c36e3374da74452384b4098c957664c5/complaints/3d92102fdf3d4a789a151dc02b08b367?acc_token=7491002ae64a4e7cacbd4b920286e83e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "claim"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "claim", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "dateSubmitted": "2019-03-18T09:27:20.321209+02:00", 
    "complaintID": "UA-2019-03-18-000001.8", 
    "date": "2019-03-18T09:27:20.326533+02:00", 
    "type": "claim", 
    "id": "3d92102fdf3d4a789a151dc02b08b367"
  }
}

