POST /api/2.5/tenders/8bbbf1f4060944ebad43e1a68e72cb38/awards/6cbaa9eddb444226a7714f082577fd46/complaints/a237331b41014e298048b747586a08a5/documents?acc_token=1518dde89d664f1782c316255e6d6bbb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 151
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/8bbbf1f4060944ebad43e1a68e72cb38/awards/6cbaa9eddb444226a7714f082577fd46/complaints/a237331b41014e298048b747586a08a5/documents/f82dcf44645b45b29ca1f0d568b6e2be
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7a4aa8249d284e8c981314ef69f1982b?KeyID=a8968c46&Signature=IK%2FyfChcJgMeQLzXRye0untsLrEQxmTFMB7dBpvIjiOC2Ncpgg1%252BzzRgmjAhJBGP3U6JJJBUDYXCSFdsHYjUAg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:10:00+03:00", 
    "id": "f82dcf44645b45b29ca1f0d568b6e2be", 
    "dateModified": "2019-04-01T01:10:00+03:00"
  }
}

