GET /api/2.4/tenders/c64849e48c0743a2b39a143e5fa5cbf5/awards/dffe8f97545945a1bc2d22c7de570321/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "satisfied", 
      "dateDecision": "2018-08-15T10:18:02.104583+03:00", 
      "documents": [
        {
          "author": "complaint_owner", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/c64849e48c0743a2b39a143e5fa5cbf5/awards/dffe8f97545945a1bc2d22c7de570321/complaints/62efca9c1deb4ca6af4c7bdbf4d4c3e4/documents/a9183e14caed40b99a4b33882e3a0d46?download=5d638ab674f84f79a24b6310a3ce33dc", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T10:17:58.880625+03:00", 
          "id": "a9183e14caed40b99a4b33882e3a0d46", 
          "dateModified": "2018-08-15T10:17:58.880649+03:00"
        }, 
        {
          "author": "aboveThresholdReviewers", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/c64849e48c0743a2b39a143e5fa5cbf5/awards/dffe8f97545945a1bc2d22c7de570321/complaints/62efca9c1deb4ca6af4c7bdbf4d4c3e4/documents/14a0f8c60ee1418f905cdd30eb16b648?download=7367e94d44544aa9822f1a8d134aa7c0", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T10:18:01.922508+03:00", 
          "id": "14a0f8c60ee1418f905cdd30eb16b648", 
          "dateModified": "2018-08-15T10:18:01.922531+03:00"
        }
      ], 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateAccepted": "2018-08-15T10:18:01.237994+03:00", 
      "dateSubmitted": "2018-08-15T10:17:59.040168+03:00", 
      "complaintID": "UA-2018-08-15-000001.1", 
      "date": "2018-08-15T10:18:02.111835+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "id": "62efca9c1deb4ca6af4c7bdbf4d4c3e4"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2018-08-15T10:18:01.070564+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2018-08-15T10:17:59.190139+03:00", 
      "complaintID": "UA-2018-08-15-000001.2", 
      "date": "2018-08-15T10:18:01.077561+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "ff18ede90df04d9d962faf44ab89bde8"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2018-08-15T10:18:02.282000+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2018-08-15T10:18:01.408098+03:00", 
      "dateSubmitted": "2018-08-15T10:17:59.349025+03:00", 
      "complaintID": "UA-2018-08-15-000001.3", 
      "date": "2018-08-15T10:18:02.290735+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "62accb31b1584040b386ebc949c81d5f"
    }, 
    {
      "status": "accepted", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2018-08-15T10:18:01.578782+03:00", 
      "dateSubmitted": "2018-08-15T10:17:59.514536+03:00", 
      "complaintID": "UA-2018-08-15-000001.4", 
      "date": "2018-08-15T10:18:01.586262+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "e8bf38f8662d452799940ce43682222a"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-08-15T10:18:02.458798+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2018-08-15T10:18:02.458820+03:00", 
      "dateAccepted": "2018-08-15T10:18:01.747353+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-08-15T10:17:59.681676+03:00", 
      "complaintID": "UA-2018-08-15-000001.5", 
      "date": "2018-08-15T10:18:02.466081+03:00", 
      "type": "complaint", 
      "id": "158e7219d2254f8a963c5f362b49a5fd"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "resolutionType": "resolved", 
      "type": "claim", 
      "title": "Недостатньо інформації", 
      "satisfied": true, 
      "dateAnswered": "2018-08-15T10:17:59.972319+03:00", 
      "dateSubmitted": "2018-08-15T10:17:59.822841+03:00", 
      "complaintID": "UA-2018-08-15-000001.6", 
      "date": "2018-08-15T10:17:59.978366+03:00", 
      "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
      "id": "38ee3683330a403face8a4a3b1bedd31"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "resolutionType": "invalid", 
      "type": "claim", 
      "title": "Недостатньо інформації", 
      "satisfied": false, 
      "dateAnswered": "2018-08-15T10:18:00.428128+03:00", 
      "dateSubmitted": "2018-08-15T10:18:00.268200+03:00", 
      "complaintID": "UA-2018-08-15-000001.7", 
      "date": "2018-08-15T10:18:00.434786+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "6073ae0efa6c4ab8b017953d51ca2c89"
    }, 
    {
      "status": "claim", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "dateSubmitted": "2018-08-15T10:18:00.901451+03:00", 
      "complaintID": "UA-2018-08-15-000001.8", 
      "date": "2018-08-15T10:18:00.908318+03:00", 
      "type": "claim", 
      "id": "0cf8d695456f41828f875f6c42cf5890"
    }
  ]
}

