PATCH /api/2.5/tenders/ac935cfbfbd34309a964891a8d29e35e/awards/86f7a213eac2456d84d2f679a49e8706/complaints/9b9aa4d603a64d54a1d8960bd210cbcc?acc_token=ef57e1c0890e4cab91ad2de704f583fe HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 228
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "stopping", 
    "cancellationReason": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "stopping", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "cancellationReason": "Тендер скасовується замовником", 
    "dateCanceled": "2019-01-01T00:10:00+02:00", 
    "dateAccepted": "2019-01-01T00:10:00+02:00", 
    "dateSubmitted": "2019-01-01T00:10:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.4", 
    "date": "2019-01-01T00:10:00+02:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "9b9aa4d603a64d54a1d8960bd210cbcc"
  }
}

