PATCH /api/2.4/tenders/65905370ed6c4984b9bf0be9033520d5/awards/2219cab9dd204c779537dbdf873b6f80/complaints/667d1bd8411643689b9c90f41fd9f539?acc_token=b95d3705bf3a40308cef8c0d8127aaaa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "satisfied": true
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "claim", 
    "title": "Недостатньо інформації", 
    "satisfied": true, 
    "dateAnswered": "2018-09-21T05:28:32.249982+03:00", 
    "dateSubmitted": "2018-09-21T05:28:31.858934+03:00", 
    "complaintID": "UA-2018-09-21-000001.6", 
    "date": "2018-09-21T05:28:32.293043+03:00", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
    "id": "667d1bd8411643689b9c90f41fd9f539"
  }
}

