PATCH /api/2.4/tenders/c64849e48c0743a2b39a143e5fa5cbf5/awards/dffe8f97545945a1bc2d22c7de570321/complaints/6073ae0efa6c4ab8b017953d51ca2c89?acc_token=5d22ab97232d43ec8b494c6ef672026a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "satisfied": false
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "invalid", 
    "type": "claim", 
    "title": "Недостатньо інформації", 
    "satisfied": false, 
    "dateAnswered": "2018-08-15T10:18:00.428128+03:00", 
    "dateSubmitted": "2018-08-15T10:18:00.268200+03:00", 
    "complaintID": "UA-2018-08-15-000001.7", 
    "date": "2018-08-15T10:18:00.434786+03:00", 
    "resolution": "Вимога не відповідає предмету закупівлі", 
    "id": "6073ae0efa6c4ab8b017953d51ca2c89"
  }
}

