GET /api/2.4/tenders/65905370ed6c4984b9bf0be9033520d5/awards/2219cab9dd204c779537dbdf873b6f80/complaints/69bd2ae5486241f3be86b7ffbec1602e HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2018-09-21T05:28:37.538198+03:00", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/65905370ed6c4984b9bf0be9033520d5/awards/2219cab9dd204c779537dbdf873b6f80/complaints/69bd2ae5486241f3be86b7ffbec1602e/documents/bb7124f9393b4813a4e917cb54015e0d?download=b9391acecfa542629aeb78c611d04274", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:28:29.777158+03:00", 
        "id": "bb7124f9393b4813a4e917cb54015e0d", 
        "dateModified": "2018-09-21T05:28:29.777219+03:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/65905370ed6c4984b9bf0be9033520d5/awards/2219cab9dd204c779537dbdf873b6f80/complaints/69bd2ae5486241f3be86b7ffbec1602e/documents/600b1dead2f142a081741bcaf4fa3818?download=596a2c679b4a4678acc5d7cbba5b4786", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:28:37.059155+03:00", 
        "id": "600b1dead2f142a081741bcaf4fa3818", 
        "dateModified": "2018-09-21T05:28:37.059256+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2018-09-21T05:28:35.465114+03:00", 
    "dateSubmitted": "2018-09-21T05:28:30.084264+03:00", 
    "complaintID": "UA-2018-09-21-000001.1", 
    "date": "2018-09-21T05:28:37.560094+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "69bd2ae5486241f3be86b7ffbec1602e"
  }
}

