POST /api/2.5/tenders/3c2f3bb4c2f6449fbe0ca1ab1fd768f7/awards/f764e0a5b6274bb89ce6e731d7003a7a/complaints/ba4a717cd04246c2a294b92e0140fada/documents?acc_token=90d643c279dc4cadb0e6f0a4193b1d8e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 201
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy765495266123$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/3c2f3bb4c2f6449fbe0ca1ab1fd768f7/awards/f764e0a5b6274bb89ce6e731d7003a7a/complaints/ba4a717cd04246c2a294b92e0140fada/documents/84bcfedf09664893a60c4c596cdb5ddb
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dd797ea0a1b943d39e52ec928075cd1d?KeyID=36670427&Signature=g1Pv2j2rp79Cl%2FDwj7p9aZYsRDoJPninoEpdkc8yNLcNKaCAb0KAYtwV9lOWMuYCBTAOtf6XOTmoH3mZjwlqBA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "84bcfedf09664893a60c4c596cdb5ddb", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

