GET /api/2.4/tenders/a7482daaaa934bffb176efde3bf39072/bids/e25189e366dd45689107cebbb3bf7763?acc_token=88a0d997829045b6b79760d2538ea35c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/a7482daaaa934bffb176efde3bf39072/bids/e25189e366dd45689107cebbb3bf7763/documents/fb7cf90ab32747fca97b1948bf42b90d?download=ce53934fe5474e59adc0c88f5d3a876f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:18:11.664239+03:00", 
        "id": "fb7cf90ab32747fca97b1948bf42b90d", 
        "dateModified": "2018-08-15T10:18:11.664258+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "e25189e366dd45689107cebbb3bf7763", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "subcontractingDetails": "ДКП «книга», Україна, м. Львів, вул. Островського, 33", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2018-08-15T10:18:11.532053+03:00", 
    "selfQualified": true, 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/a7482daaaa934bffb176efde3bf39072?key_for_bid=e25189e366dd45689107cebbb3bf7763"
  }
}

