PATCH /api/2.5/tenders/dc07cf2d5fae45f88da7ef5b0917cd1f/bids/087bb709d3fc4e1d9be1fac5e91c1b53?acc_token=34e4f4f169d54a0db853ee5c9f678b88 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/dc07cf2d5fae45f88da7ef5b0917cd1f/bids/087bb709d3fc4e1d9be1fac5e91c1b53/documents/41f3a85f20d34c29b95a13e0f21c3d5f?download=f681ad2482664e859f9f356beaab1aa3", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:48:58.345401+02:00", 
        "id": "41f3a85f20d34c29b95a13e0f21c3d5f", 
        "dateModified": "2019-03-28T06:48:58.345415+02:00"
      }
    ], 
    "selfEligible": true, 
    "id": "087bb709d3fc4e1d9be1fac5e91c1b53", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "subcontractingDetails": "ДКП «книга», Україна, м. Львів, вул. Островського, 33", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-03-28T06:48:58.299028+02:00", 
    "selfQualified": true
  }
}

