GET /api/2.4/tenders/2262b66765a443d99a994aaa48fa9b36/bids/8054bfe84ae74982a351cd43bd5aec7e?acc_token=99e471a1da2b4946aac8f1e7e3a83a5b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "invalid", 
    "id": "8054bfe84ae74982a351cd43bd5aec7e"
  }
}

