GET /api/2.4/tenders/649db2e8fe4745f1b024fde9cbe15d1e/bids/9620ac4afef74d128369d107e4c78ab7?acc_token=d68e28034acb4ee8b6e297464c92648a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "selfEligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "9620ac4afef74d128369d107e4c78ab7", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2018-09-21T05:28:55.589342+03:00", 
    "selfQualified": true, 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/649db2e8fe4745f1b024fde9cbe15d1e?key_for_bid=9620ac4afef74d128369d107e4c78ab7"
  }
}

