PATCH /api/2.5/tenders/27234283651d49e196b8b3c218231f9d/bids/ae0eedb45f8e4de99cb7fbfa4836c60b?acc_token=9ad3a825eaab458e9c43137a4a2082f6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/27234283651d49e196b8b3c218231f9d/bids/ae0eedb45f8e4de99cb7fbfa4836c60b/documents/ecc600904a554ccd8c2b0131df224498?download=595767f8374840618324ee3c367af13f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:01+03:00", 
        "id": "ecc600904a554ccd8c2b0131df224498", 
        "dateModified": "2019-04-01T01:00:01+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "ae0eedb45f8e4de99cb7fbfa4836c60b", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-04-01T01:00:01+03:00", 
    "selfQualified": true
  }
}

