GET /api/2.5/tenders/8a94b71fce4541bb922d7c42567e4a19/bids/eec7fb9ee08347e5afd0e0ef91312f9b?acc_token=10d1420edfdf49aea96624c30e675f9f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/8a94b71fce4541bb922d7c42567e4a19/bids/eec7fb9ee08347e5afd0e0ef91312f9b/documents/8b7a93f1e3f64ea09b9f326f1f9501cd?download=f77e0b5befe74d35bf1f7e6b1bd0538a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:27:25.614608+02:00", 
        "id": "8b7a93f1e3f64ea09b9f326f1f9501cd", 
        "dateModified": "2019-03-18T09:27:25.614620+02:00"
      }
    ], 
    "selfEligible": true, 
    "id": "eec7fb9ee08347e5afd0e0ef91312f9b", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "subcontractingDetails": "ДКП «книга», Україна, м. Львів, вул. Островського, 33", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-03-18T09:27:25.569416+02:00", 
    "selfQualified": true, 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/8a94b71fce4541bb922d7c42567e4a19?key_for_bid=eec7fb9ee08347e5afd0e0ef91312f9b"
  }
}

