GET /api/2.5/tenders/8a94b71fce4541bb922d7c42567e4a19/bids/eec7fb9ee08347e5afd0e0ef91312f9b?acc_token=10d1420edfdf49aea96624c30e675f9f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "eec7fb9ee08347e5afd0e0ef91312f9b"
  }
}

