GET /api/2.5/tenders/dc07cf2d5fae45f88da7ef5b0917cd1f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "awardCriteria": "lowestCost", 
    "tenderPeriod": {
      "startDate": "2019-03-28T06:48:57.577034+02:00", 
      "endDate": "2019-04-13T06:47:08.227127+02:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "enquiryPeriod": {
      "startDate": "2019-03-28T06:48:57.577034+02:00", 
      "clarificationsUntil": "2019-04-12T00:00:00+02:00", 
      "endDate": "2019-04-10T00:00:00+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2019-03-28T06:48:57.577034+02:00", 
      "endDate": "2019-04-11T00:00:00+03:00"
    }, 
    "procurementMethodType": "aboveThresholdUA.defense", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2019-03-28T06:48:57.591424+02:00", 
    "next_check": "2019-04-13T07:47:08.227127+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "kind": "defense", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "name": "ЗОСШ #10 м.Вінниці"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-04-14T00:00:00+02:00"
    }, 
    "owner": "broker", 
    "dateModified": "2019-03-28T06:48:57.593664+02:00", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-17T06:47:08.227086+02:00", 
          "endDate": "2019-05-17T06:47:08.227116+02:00"
        }, 
        "id": "bed8b4c1bf15429e9392a61a0b20eaa2", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "id": "dc07cf2d5fae45f88da7ef5b0917cd1f", 
    "tenderID": "UA-2019-03-28-000001"
  }
}

