PATCH /api/2.5/tenders/d760a4ded940413c8a3c085d30c4a3f1/complaints/80e41a2f093646d1996622d38c74dd4a?acc_token=db77bd90712545bebc80310774c26d4d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 250
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "resolution": "Виправлено неконкурентні умови"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "dateAnswered": "2019-01-01T00:00:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.2", 
    "date": "2019-01-01T00:00:00+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "80e41a2f093646d1996622d38c74dd4a"
  }
}

