PATCH /api/2.4/tenders/8b900d0ee61b42a7ba150e5716aa7e1d/complaints/60b7bfc39e1a49a3b229eb6809960704 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "declined"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "declined", 
    "dateDecision": "2019-02-06T06:11:58.408921+02:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "scale": "micro", 
      "name": "ДКП «Школяр»", 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "dateAccepted": "2019-02-06T06:11:58.095231+02:00", 
    "dateSubmitted": "2019-02-06T06:11:57.552960+02:00", 
    "complaintID": "UA-2019-02-06-000001.3", 
    "date": "2019-02-06T06:11:58.412806+02:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "60b7bfc39e1a49a3b229eb6809960704"
  }
}

