PATCH /api/2.4/tenders/273795efc033431cbfbf88167b710baf/complaints/a0f6a342acab4bc4a724f36b342bdeda?acc_token=de1fa9cefc3e41a19ce571d0d901d2a2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 145
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "resolved", 
    "tendererAction": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "resolved", 
    "dateDecision": "2018-09-21T05:28:49.118620+03:00", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/273795efc033431cbfbf88167b710baf/complaints/a0f6a342acab4bc4a724f36b342bdeda/documents/cda9f0de9b40401aa835d8f4c5afaa26?download=0f2d14e0d8974730a1cae931bffd109c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:28:45.079269+03:00", 
        "id": "cda9f0de9b40401aa835d8f4c5afaa26", 
        "dateModified": "2018-09-21T05:28:45.079356+03:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/273795efc033431cbfbf88167b710baf/complaints/a0f6a342acab4bc4a724f36b342bdeda/documents/08c029ab314043079aff53ef800f3a20?download=29e5c26ecbdc44fbb127d6be7c2e22d5", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:28:48.887961+03:00", 
        "id": "08c029ab314043079aff53ef800f3a20", 
        "dateModified": "2018-09-21T05:28:48.888014+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "tendererAction": "Умови виправлено", 
    "tendererActionDate": "2018-09-21T05:28:49.835973+03:00", 
    "dateSubmitted": "2018-09-21T05:28:46.159626+03:00", 
    "complaintID": "UA-2018-09-21-000001.1", 
    "date": "2018-09-21T05:28:49.845577+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "a0f6a342acab4bc4a724f36b342bdeda", 
    "dateAccepted": "2018-09-21T05:28:48.053259+03:00"
  }
}

