POST /api/2.4/tenders/b0d5eb2ae52543d0a982f225750418d8/complaints/f8a9ebd0d4dd4f22a1f162e1aeebacf6/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 201
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy0717578225623$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/b0d5eb2ae52543d0a982f225750418d8/complaints/f8a9ebd0d4dd4f22a1f162e1aeebacf6/documents/a1e265bcf84f41c0a05200d6d30eb0ce
{
  "data": {
    "author": "aboveThresholdReviewers", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/b0d5eb2ae52543d0a982f225750418d8/complaints/f8a9ebd0d4dd4f22a1f162e1aeebacf6/documents/a1e265bcf84f41c0a05200d6d30eb0ce?download=d660e2dee66341e09dd23b7177ffeedb", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-15T10:18:07.540304+03:00", 
    "id": "a1e265bcf84f41c0a05200d6d30eb0ce", 
    "dateModified": "2018-08-15T10:18:07.540328+03:00"
  }
}

