PATCH /api/2.5/tenders/48b14561c9f44d339fdf26f0d4cdb624/complaints/d8b4c61723504dad9f5d975051034c82?acc_token=2376723326c744e88dc9e7468a6132b6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 250
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "resolution": "Виправлено неконкурентні умови"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "dateAnswered": "2019-04-01T01:00:00+03:00", 
    "complaintID": "UA-2019-04-01-000001.2", 
    "date": "2019-04-01T01:00:00+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "d8b4c61723504dad9f5d975051034c82"
  }
}

