POST /api/2.4/tenders/273795efc033431cbfbf88167b710baf/complaints/a0f6a342acab4bc4a724f36b342bdeda/documents?acc_token=6b31650c79454d94844b4ba71a4ffa86 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 201
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy860182875347$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/273795efc033431cbfbf88167b710baf/complaints/a0f6a342acab4bc4a724f36b342bdeda/documents/cda9f0de9b40401aa835d8f4c5afaa26
{
  "data": {
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/273795efc033431cbfbf88167b710baf/complaints/a0f6a342acab4bc4a724f36b342bdeda/documents/cda9f0de9b40401aa835d8f4c5afaa26?download=0f2d14e0d8974730a1cae931bffd109c", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-09-21T05:28:45.079269+03:00", 
    "id": "cda9f0de9b40401aa835d8f4c5afaa26", 
    "dateModified": "2018-09-21T05:28:45.079356+03:00"
  }
}

