POST /api/2.4/tenders/b0d5eb2ae52543d0a982f225750418d8/complaints/f8a9ebd0d4dd4f22a1f162e1aeebacf6/documents?acc_token=9d4ae49f8cee4d6592a0b36610fd7943 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 201
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy703688366675$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/b0d5eb2ae52543d0a982f225750418d8/complaints/f8a9ebd0d4dd4f22a1f162e1aeebacf6/documents/75fa2feb10c644e8863fbce498c6fc10
{
  "data": {
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/b0d5eb2ae52543d0a982f225750418d8/complaints/f8a9ebd0d4dd4f22a1f162e1aeebacf6/documents/75fa2feb10c644e8863fbce498c6fc10?download=be6c25711a98496eba626bdd72f63de7", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-15T10:18:05.086179+03:00", 
    "id": "75fa2feb10c644e8863fbce498c6fc10", 
    "dateModified": "2018-08-15T10:18:05.086201+03:00"
  }
}

