PATCH /api/2.5/tenders/48b14561c9f44d339fdf26f0d4cdb624/complaints/8963f92202204406ba37027dd8a8f1e2?acc_token=9e7f54f8cb04461c9e429faacce44e36 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2019-01-01T00:00:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.7", 
    "date": "2019-01-01T00:00:00+02:00", 
    "type": "claim", 
    "id": "8963f92202204406ba37027dd8a8f1e2"
  }
}

