PATCH /api/2.5/tenders/97c85910204e45aca789969e8a136e76/awards/fdb33c47c76549019fce9871ceb51b60?acc_token=cdd57014a34946a58cef647597fd9e87 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-01-01T00:00:00+02:00", 
      "endDate": "2019-01-10T00:00:00+02:00"
    }, 
    "bid_id": "92cd04c11b3a4b03bcc9a665dd49d002", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "fdb33c47c76549019fce9871ceb51b60"
  }
}

