PATCH /api/2.4/tenders/649db2e8fe4745f1b024fde9cbe15d1e/awards/56cb122534cf4a3fb04939e0453b5fa0?acc_token=800a8baa27f84f6ba428e97b8ed38cb6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-09-21T05:28:56.672027+03:00", 
      "endDate": "2018-09-28T00:00:00+03:00"
    }, 
    "bid_id": "9620ac4afef74d128369d107e4c78ab7", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "date": "2018-09-21T05:28:56.944448+03:00", 
    "id": "56cb122534cf4a3fb04939e0453b5fa0"
  }
}

