GET /api/2.5/tenders/8a94b71fce4541bb922d7c42567e4a19/questions/ae19c5cb2273404d9bcbfd6752b4f52b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2019-03-18T09:27:25.328671+02:00", 
    "title": "Калорійність", 
    "date": "2019-03-18T09:27:25.289189+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "ae19c5cb2273404d9bcbfd6752b4f52b", 
    "questionOf": "tender"
  }
}

