PATCH /api/2.5/tenders/24f6a0b9c9d24eb5887a9d6015b64218/cancellations/ec666afd32df4fc9b6b32b57cf65ace0/documents/6dde0e2713ce49e1a36e8efbbc1e5f01?acc_token=b62db9cb6b1149fcb62b0e5276c5b724 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1704efc19c8f4be6ae4735695a1e5866?KeyID=a8968c46&Signature=rCMcvJfVEEMZI1mrqTPVpOC4xi%252BLynjN61vErbAzykOzLLW9eOehtWfTHa50upquQbHYXLIJLb2WimXRosdbAA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:30:00+03:00", 
    "id": "6dde0e2713ce49e1a36e8efbbc1e5f01", 
    "dateModified": "2019-04-01T01:30:00+03:00"
  }
}

