PATCH /api/2.5/tenders/dc07cf2d5fae45f88da7ef5b0917cd1f/cancellations/f04b381ec0184f4c95f0dae177f03d64/documents/b563d13debcc49f095a28d54fe33b7a1?acc_token=41072074f75f4d3b9830f4c04d744a6d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/dc07cf2d5fae45f88da7ef5b0917cd1f/cancellations/f04b381ec0184f4c95f0dae177f03d64/documents/b563d13debcc49f095a28d54fe33b7a1?download=12c54dbe5c6b43419f44abf8cd9fcbbf", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-28T06:48:59.910370+02:00", 
    "id": "b563d13debcc49f095a28d54fe33b7a1", 
    "dateModified": "2019-03-28T06:48:59.910400+02:00"
  }
}

