POST /api/2.4/tenders/2262b66765a443d99a994aaa48fa9b36/cancellations?acc_token=4d201ddaac3e4898afb848bd28191241 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/2262b66765a443d99a994aaa48fa9b36/cancellations/4a6249192d4e45698939e263d4ab61c9
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2019-02-06T06:12:00.726026+02:00", 
    "cancellationOf": "tender", 
    "id": "4a6249192d4e45698939e263d4ab61c9"
  }
}

