POST /api/2.4/tenders/649db2e8fe4745f1b024fde9cbe15d1e/cancellations?acc_token=800a8baa27f84f6ba428e97b8ed38cb6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/649db2e8fe4745f1b024fde9cbe15d1e/cancellations/1df237320e224fe199b407c47505a0d5
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2018-09-21T05:28:58.673195+03:00", 
    "cancellationOf": "tender", 
    "id": "1df237320e224fe199b407c47505a0d5"
  }
}

