PATCH /api/2.5/tenders/8a94b71fce4541bb922d7c42567e4a19?acc_token=98129298172442eeb10a10b9a05a3120 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 57
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "guarantee": {
      "currency": "USD", 
      "amount": 8
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "auctionPeriod": {
      "shouldStartAfter": "2019-04-03T00:00:00+02:00"
    }, 
    "awardCriteria": "lowestCost", 
    "tenderPeriod": {
      "startDate": "2019-03-18T09:27:25.012245+02:00", 
      "endDate": "2019-04-02T09:27:35.064257+02:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "enquiryPeriod": {
      "startDate": "2019-03-18T09:27:25.012245+02:00", 
      "clarificationsUntil": "2019-04-01T09:27:35.064257+02:00", 
      "endDate": "2019-03-28T09:27:35.064257+02:00", 
      "invalidationDate": "2019-03-18T09:27:25.144025+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2019-03-18T09:27:25.012245+02:00", 
      "endDate": "2019-03-29T00:00:00+03:00"
    }, 
    "procurementMethodType": "aboveThresholdUA.defense", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2019-03-18T09:27:25.031099+02:00", 
    "next_check": "2019-04-02T10:27:35.064257+03:00", 
    "tenderID": "UA-2019-03-18-000001", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-07T09:26:16.016278+02:00", 
          "endDate": "2019-05-07T09:26:16.016307+02:00"
        }, 
        "id": "fe01b54664f64908a533033f33949381", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "owner": "broker", 
    "dateModified": "2019-03-18T09:27:25.145513+02:00", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "id": "8a94b71fce4541bb922d7c42567e4a19", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "kind": "defense", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "name": "ЗОСШ #10 м.Вінниці"
    }
  }
}

