GET /api/2.5/tenders/27234283651d49e196b8b3c218231f9d/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/efc40249eb6c4cc9955da3d88bd7246e?KeyID=a8968c46&Signature=KG%252B63UEipb4rzv03ij0OuJDDvomGetsWPWa69PxQfbU5bWdYfGg3tmoiKdHljT%2FMeA7uoiu5J0is2zgPJVLBBg%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "4010490c608343b2b5ddadf6b5f6b787", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/fa7dac6f54b742319ca8b04679b12aab?KeyID=a8968c46&Signature=8lcTI7rBjrAy7a4AGeMJ%2F5HR0kBG0lvq3iB5ekno0tfc4emjXZgrgDL9f4DpsHw3jCf7HALjZI16YAFV4VBFBg%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "8353c30db82545c2b980007da3da78e5", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }
  ]
}

