GET /api/2.4/tenders/a7482daaaa934bffb176efde3bf39072/contracts/3c077131a54a454fa255f72e169c5148?acc_token=26683abba0f94098a6efc1ac8109f06a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "title": "contract_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/a7482daaaa934bffb176efde3bf39072/contracts/3c077131a54a454fa255f72e169c5148/documents/8fdc3fb6d2704cf78d096f114cbab409?download=b5b287005a984f719a9ca71e12c357c2", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:18:13.891583+03:00", 
        "id": "8fdc3fb6d2704cf78d096f114cbab409", 
        "dateModified": "2018-08-15T10:18:13.891607+03:00"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-04T10:17:55.977040+03:00", 
          "endDate": "2018-10-04T10:17:55.977085+03:00"
        }, 
        "id": "89dfab701691447ebda7283fa6283949", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2018-08-15T10:18:13.650188+03:00", 
      "endDate": "2019-08-15T10:18:13.650219+03:00"
    }, 
    "dateSigned": "2018-08-15T10:18:13.486347+03:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardID": "87504212a3e846a19ec5be840cf70c5a", 
    "id": "3c077131a54a454fa255f72e169c5148", 
    "contractID": "UA-2018-08-15-000001-1"
  }
}

