GET /api/2.4/tenders?opt_pretty=1 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "next_page": {
    "path": "/api/2.4/tenders?offset=2018-09-21T05%3A28%3A52.608007%2B03%3A00", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.4/tenders?offset=2018-09-21T05%3A28%3A52.608007%2B03%3A00", 
    "offset": "2018-09-21T05:28:52.608007+03:00"
  }, 
  "data": [
    {
      "id": "649db2e8fe4745f1b024fde9cbe15d1e", 
      "dateModified": "2018-09-21T05:28:52.608007+03:00"
    }
  ]
}

