PATCH /api/2.4/tenders/2262b66765a443d99a994aaa48fa9b36/contracts/e505b49ca76d49ebb8661bec238be968?acc_token=4d201ddaac3e4898afb848bd28191241 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 118
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "period": {
      "startDate": "2019-02-06T06:12:00.534030+02:00", 
      "endDate": "2020-02-06T06:12:00.534048+02:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-02-26T06:11:52.563885+02:00", 
          "endDate": "2019-03-28T06:11:52.563912+02:00"
        }, 
        "id": "280c564f9736451d89d1863b5384df21", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2019-02-06T06:12:00.534030+02:00", 
      "endDate": "2020-02-06T06:12:00.534048+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2019-02-06T06:12:00.459914+02:00", 
    "awardID": "2ed6be868b7647b3976e1519d072aeac", 
    "id": "e505b49ca76d49ebb8661bec238be968", 
    "contractID": "UA-2019-02-06-000001-1"
  }
}

