POST /api/2.5/tenders/24f6a0b9c9d24eb5887a9d6015b64218/contracts/f360042dbad34624b8944356e3b044ad/documents?acc_token=b62db9cb6b1149fcb62b0e5276c5b724 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="contract_document.doc"
Content-Type: application/msword

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/24f6a0b9c9d24eb5887a9d6015b64218/contracts/f360042dbad34624b8944356e3b044ad/documents/05dc81f7ef984d7591b77373d700f4df
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "contract_document.doc", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/556547596a1640b78d1689a42b40efe8?KeyID=a8968c46&Signature=kvePlePTL9r6kxKofAhzsQHXceIqbsLqJgl7bc9iqDmOPcYJwepMzaejEQrKRlnB3xsA0iKR0UOofIv4ZJ3vDw%253D%253D", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:30:00+03:00", 
    "id": "05dc81f7ef984d7591b77373d700f4df", 
    "dateModified": "2019-04-01T01:30:00+03:00"
  }
}

