GET /api/2.5/tenders/dc07cf2d5fae45f88da7ef5b0917cd1f/documents/ce8d71f7af8543bba4d3acaa71e1b0d4?acc_token=41072074f75f4d3b9830f4c04d744a6d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/dc07cf2d5fae45f88da7ef5b0917cd1f/documents/ce8d71f7af8543bba4d3acaa71e1b0d4?download=b9025bafe62e48f486a8ef86b09fe48c", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-28T06:48:57.774368+02:00", 
    "previousVersions": [], 
    "id": "ce8d71f7af8543bba4d3acaa71e1b0d4", 
    "dateModified": "2019-03-28T06:48:57.774382+02:00"
  }
}

