GET /api/2.5/tenders/27234283651d49e196b8b3c218231f9d/contracts/287cb11d2a344b2ea6dd5e8619e25963?acc_token=9649a8a44fb640b3a6dc2b2265dc17b2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_document.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3353f08391244599b6b6a333f3288797?KeyID=a8968c46&Signature=MBjGhLQTvqmjhyFCiPlIr7MANYuGSLWeZdbtq6rB9vb%2F9bGPjPcqtdE3mZdtxcj2BrbA6PNbPOHxMZ8pKy8hDA%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:30:00+03:00", 
        "id": "501aca79b9af4e6f988ac39acd17279f", 
        "dateModified": "2019-04-01T01:30:00+03:00"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-21T00:00:00+02:00", 
          "endDate": "2019-05-21T00:00:00+02:00"
        }, 
        "id": "0fca193cc1e941308e0c3afda2039ffd", 
        "quantity": 1.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2019-04-01T01:30:00+03:00", 
      "endDate": "2020-03-31T01:30:00+03:00"
    }, 
    "dateSigned": "2019-04-01T01:30:00+03:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-04-01T01:10:00+03:00", 
    "awardID": "00483f3578e54de6947c48e4d453364c", 
    "id": "287cb11d2a344b2ea6dd5e8619e25963", 
    "contractID": "UA-2019-04-01-000001-1"
  }
}

