PATCH /api/2.5/tenders/7ca938a74b3b44a7979818052b0a8788/complaints/111d259044414031904ab03cb3202c17 HTTP/1.0
Authorization: Bearer reviewer
Content-Length: 33
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "satisfied"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2019-10-01T01:00:00+03:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/85cada103b3041d9be26ae4208404de2?KeyID=a8968c46&Signature=qjjlLcD9%2FsvgNuHfA%2F4MLa3qmGkTxtZ76S5xwFiwCiTTZ5Esc14M4KGvnTghg6PbGO3OPi3GXbNPOf2SBakfAw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-01T01:00:00+03:00", 
        "id": "aac34d33f40d41ff849ea4ba5b298bef", 
        "dateModified": "2019-10-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d6daf636632b4861b4700ecfb4b44a16?KeyID=a8968c46&Signature=5Mq%2F85wmYGlHsIA1pxBzMb3AgfCJgBFxRaQufDJWyXP0y5ab%252B2%252BE5sUvjYFKgHJ2lgR4veE6i%2F5TMm2V0WLyAw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-10-01T01:00:00+03:00", 
        "id": "0db053c12af044408f09d72c66e6d916", 
        "dateModified": "2019-10-01T01:00:00+03:00"
      }
    ], 
    "transfer_token": "4341e2f2528b3cb1c1dedb4d69a555b146e59a6aea50003b2463cf811a6e39b206074716062378497f4a87e2f99a2deeea19a93fd8d77cebd0ca004be6e16756", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2019-10-01T01:00:00+03:00", 
    "dateSubmitted": "2019-10-01T01:00:00+03:00", 
    "complaintID": "UA-2019-10-01-000001.1", 
    "date": "2019-10-01T01:00:00+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "111d259044414031904ab03cb3202c17", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс."
  }
}

