POST /api/2.5/tenders/7ca938a74b3b44a7979818052b0a8788/complaints/111d259044414031904ab03cb3202c17/documents?acc_token=fd3ee7f853ca434fad1437a160e41e64 HTTP/1.0
Authorization: Bearer broker
Content-Length: 157
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/7ca938a74b3b44a7979818052b0a8788/complaints/111d259044414031904ab03cb3202c17/documents/aac34d33f40d41ff849ea4ba5b298bef
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/85cada103b3041d9be26ae4208404de2?KeyID=a8968c46&Signature=qjjlLcD9%2FsvgNuHfA%2F4MLa3qmGkTxtZ76S5xwFiwCiTTZ5Esc14M4KGvnTghg6PbGO3OPi3GXbNPOf2SBakfAw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-10-01T01:00:00+03:00", 
    "id": "aac34d33f40d41ff849ea4ba5b298bef", 
    "dateModified": "2019-10-01T01:00:00+03:00"
  }
}

