POST /api/2.5/tenders/7898ec9992af47ccbc9b8bf1b8539660/cancellations/802ef4ff261240fab60666d4b7d339c6/documents?acc_token=62607c36ce4a4d64961ecc0d0a21540e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 142
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="Notice.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/7898ec9992af47ccbc9b8bf1b8539660/cancellations/802ef4ff261240fab60666d4b7d339c6/documents/356979e830bb4f919afaa598586ec7ae
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d659349143d944498d86dd32779a706d?KeyID=a8968c46&Signature=YFMnkExnY%252Br8VStXylgNqVHzJ%2FTIIfE%252B729%2FHAb%252BzM31TVduaUFZsII209ft74CqO%252B5%2Ft6xlW%2FiSCO7neN84AA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-10-01T01:00:01+03:00", 
    "id": "356979e830bb4f919afaa598586ec7ae", 
    "dateModified": "2019-10-01T01:00:01+03:00"
  }
}

