PATCH /api/2.5/tenders/50c82523038349969f53f3e238932c46/qualifications/ea453efb20174cc695653f5d04d2cf46?acc_token=90e5c1d7c0414b99a392234aee8cd1dc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "dc595a39267248abbf3e85d759d6c1ab", 
    "date": "2019-10-01T01:00:00+03:00", 
    "id": "ea453efb20174cc695653f5d04d2cf46"
  }
}

