GET /api/2.5/tenders/50c82523038349969f53f3e238932c46/documents?acc_token=90e5c1d7c0414b99a392234aee8cd1dc HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/91bc0537567841cbaae2c2d7bd7fb994?KeyID=a8968c46&Signature=yPOjjM2yh9h4csp3C%252BYe2GMdbYu5GTsZi1YZDr4BJwNDDUDg4YLWoNZIpaPC8j9OrYes2G%252BMRLygX5vFELSrCw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-10-01T01:00:00+03:00", 
      "id": "afbdb1755db541099b76dfd495f91d3c", 
      "dateModified": "2019-10-01T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/fc65b95f9d954c649fc957418acc1e06?KeyID=a8968c46&Signature=2WeKdZ1ZvKbKZRf1MwsYCPKywP2cSaY1%252BB4ZB%252BzRkaUXXGrhqjcMbwvcPVVhpSdmrkryna7ovJdcWhXuEqq9AA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-10-01T01:00:00+03:00", 
      "id": "e42642870c5248a7ada19e8344bed447", 
      "dateModified": "2019-10-01T01:00:00+03:00"
    }
  ]
}

