POST /api/2.5/tenders/50c82523038349969f53f3e238932c46/bids/dc595a39267248abbf3e85d759d6c1ab/financial_documents?acc_token=4983fc47c71047729730599c7b0329ae HTTP/1.0
Authorization: Bearer broker
Content-Length: 147
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="financial_doc.pdf"
Content-Type: application/pdf

1000$
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/50c82523038349969f53f3e238932c46/bids/dc595a39267248abbf3e85d759d6c1ab/financial_documents/fc6adf2bc580434eb5b5badc0231028d
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "public", 
    "language": "uk", 
    "title": "financial_doc.pdf", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/50c82523038349969f53f3e238932c46/bids/dc595a39267248abbf3e85d759d6c1ab/financial_documents/fc6adf2bc580434eb5b5badc0231028d?download=aea76fe9b89744b29e6d17524ecffaf9", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-10-01T01:00:00+03:00", 
    "id": "fc6adf2bc580434eb5b5badc0231028d", 
    "dateModified": "2019-10-01T01:00:00+03:00"
  }
}

