POST /api/2.5/tenders/bd77618b8d904261bcbdeb67bbf0a695/awards/0c1710d159af462585b4aa19194f1aab/documents?acc_token=2e1ede01f7d34a9eb1db0fcc503916fc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 331
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/202da44fbd4a476ab11b90bd9ced7836?KeyID=a8968c46&Signature=srD89yDUpSMROmjhrGTee7qiY2zlkE4vSCFqdgUncKtRCy5YMD14y57a3IgZbPM7jZ2I5t4mXbWhfpmxJK5ABg%3D%3D", 
    "title": "Cancellation_Reason.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bd77618b8d904261bcbdeb67bbf0a695/awards/0c1710d159af462585b4aa19194f1aab/documents/4344cd13743b4c93bf4c5750a99b40e2
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Cancellation_Reason.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/202da44fbd4a476ab11b90bd9ced7836?KeyID=a8968c46&Signature=rehA9N6KolRKnxG5ygjtgzct88rEE5YUxJJ7HaBbKiGVgFdmfyPPUMqb%2Fi43kxXqgQYOtAsGveBR1aBura4kBw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "4344cd13743b4c93bf4c5750a99b40e2", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

