PATCH /api/2.5/tenders/2741dfda90ec4955a16232b29654f06e/questions/22dd9841b45746d1a09df905399ded5f?acc_token=d3a8bbfc3ee34918a43986ccc34184ca HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2019-04-01T01:00:00+03:00", 
    "title": "Калорійність", 
    "date": "2019-04-01T01:00:00+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "22dd9841b45746d1a09df905399ded5f", 
    "questionOf": "tender"
  }
}

