GET /api/2.5/tenders/2741dfda90ec4955a16232b29654f06e/bids/111b9f74b7b54ab889caa2f8826c0ee1?acc_token=6b997a9685e84d25a06a891bffc3907d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2741dfda90ec4955a16232b29654f06e/bids/111b9f74b7b54ab889caa2f8826c0ee1/documents/1a95add0b1f24a8fb42e5a9ae1ed53c8?download=30ab1a77d600492c9204d2fdb8a63ccb", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "1a95add0b1f24a8fb42e5a9ae1ed53c8", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "selfEligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "111b9f74b7b54ab889caa2f8826c0ee1", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-01-01T00:00:00+02:00", 
    "selfQualified": true, 
    "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/2741dfda90ec4955a16232b29654f06e?key_for_bid=111b9f74b7b54ab889caa2f8826c0ee1"
  }
}

