GET /api/2.5/tenders/721d337eefaf4ebf8e73f0edef07f382/bids/015ccd38230b4285bb9ff36ecd2d5341?acc_token=2bdf6e65fd9f4cbab4bfcb72f6e8660a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "015ccd38230b4285bb9ff36ecd2d5341"
  }
}

