PATCH /api/2.5/tenders/fee4f0ba21ee453cb3dddf9df0e43730/bids/0f5b8544f0e34e6b990da380269efdc2?acc_token=228a1f1babb141b3a362da71e918a027 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/fee4f0ba21ee453cb3dddf9df0e43730/bids/0f5b8544f0e34e6b990da380269efdc2/documents/c4dbfb2f640c4569a6c5ca7def93f3a4?download=034a7a13498e472fab0ddae36dd33529", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-18T09:22:09.216863+03:00", 
        "id": "c4dbfb2f640c4569a6c5ca7def93f3a4", 
        "dateModified": "2019-04-18T09:22:09.216879+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "0f5b8544f0e34e6b990da380269efdc2", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-04-18T09:22:09.126527+03:00", 
    "selfQualified": true
  }
}

