PATCH /api/2.5/tenders/fee4f0ba21ee453cb3dddf9df0e43730/awards/1345b57f469d4d9689fcb375dbc8feb4?acc_token=97843e1d2cec4bfa92c1bb389aea30a4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-04-18T09:22:09.799093+03:00", 
      "endDate": "2019-04-29T00:00:00+03:00"
    }, 
    "bid_id": "e2f19c6667a9401dbd50b4fde141d7b1", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "date": "2019-04-18T09:22:09.898382+03:00", 
    "id": "1345b57f469d4d9689fcb375dbc8feb4"
  }
}

