PATCH /api/2.5/tenders/ecf287a696234915834e93bd9c09f0f4/awards/a27ebf97efac4e43b276097e5e2da846?acc_token=7cd5e8ac1cdc400b9d0f5f1ada3976be HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-03-28T06:48:46.143649+02:00", 
      "endDate": "2019-04-08T00:00:00+02:00"
    }, 
    "bid_id": "a458a4a7fbfd49f0b437b76fc21a8189", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "date": "2019-03-28T06:48:46.269607+02:00", 
    "id": "a27ebf97efac4e43b276097e5e2da846"
  }
}

