GET /api/2.5/tenders/7c8c978fa6554fc187f93dc3ed43a9c2/questions/05b5bd06975b4e7ebe8c8abe8253b4c5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2019-04-18T06:51:44.925217+03:00", 
    "title": "Калорійність", 
    "date": "2019-04-18T06:51:44.885003+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "05b5bd06975b4e7ebe8c8abe8253b4c5", 
    "questionOf": "tender"
  }
}

