GET /api/2.5/tenders/0961fe2d5614420f9158a7db00eae734/questions/82b506020e26401890d5e930a3bf7bed HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2019-04-18T12:56:39.779731+03:00", 
    "title": "Калорійність", 
    "date": "2019-04-18T12:56:39.740993+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "82b506020e26401890d5e930a3bf7bed", 
    "questionOf": "tender"
  }
}

