GET /api/2.4/tenders/3b55cefa2396418db56d896da668b1cb/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "dateAnswered": "2018-09-21T05:24:46.189045+03:00", 
      "title": "Калорійність", 
      "date": "2018-09-21T05:24:46.042161+03:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "0d5b5e9d5fb84e9c9a073f7c71a4e48f", 
      "questionOf": "tender"
    }
  ]
}

