PATCH /api/2.5/tenders/0961fe2d5614420f9158a7db00eae734/cancellations/13418ddd4243497f8d76dde2bb129510/documents/d497f722b21f4c379d9567386fa97d0b?acc_token=17807c5f5bfd4facb419c3e0cfe1e2be HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c5fbae6a4f724a6787cdc3f1fcc3c470?KeyID=a8968c46&Signature=Om44VYzggdHDZ0hEUvx6B9XMqP51X2qdPJ6pF%252B7VUF2WkQsT7rB6iGQxvfMgPsrgJH1K3AdsPpwqN5CC9iN4BQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-18T12:56:41.543704+03:00", 
    "id": "d497f722b21f4c379d9567386fa97d0b", 
    "dateModified": "2019-04-18T12:56:41.543719+03:00"
  }
}

