POST /api/2.5/tenders/7c8c978fa6554fc187f93dc3ed43a9c2/cancellations?acc_token=cb5263ac741e46298e9888a5a80aea29 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/7c8c978fa6554fc187f93dc3ed43a9c2/cancellations/bed4fc9886d3413ead289655bd233c71
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2019-04-18T06:51:46.333808+03:00", 
    "cancellationOf": "tender", 
    "id": "bed4fc9886d3413ead289655bd233c71"
  }
}

