POST /api/2.5/tenders/06b9364fdced45db9dfab3d2cb29360a/cancellations?acc_token=1e7e40493b384af1a9f78232e0fceddd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/06b9364fdced45db9dfab3d2cb29360a/cancellations/55eb15425b894b43a800f8d4f44ecb2d
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2019-04-18T11:25:59.320169+03:00", 
    "cancellationOf": "tender", 
    "id": "55eb15425b894b43a800f8d4f44ecb2d"
  }
}

