POST /api/2.5/tenders/721d337eefaf4ebf8e73f0edef07f382/cancellations?acc_token=f35cd70165a644e8a5a6eda2fbe34df6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/721d337eefaf4ebf8e73f0edef07f382/cancellations/14c7832445d4415a9f8afbc545f7c5eb
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2019-04-01T01:30:00+03:00", 
    "cancellationOf": "tender", 
    "id": "14c7832445d4415a9f8afbc545f7c5eb"
  }
}

