POST /api/2.4/tenders/3b55cefa2396418db56d896da668b1cb/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1090
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/773a4d7f2d654f479eaa182ab2704ff1?KeyID=b0f44a83&Signature=blgbp5TIMA5ZSf7mfOOMEj%2FfOYrbZCU1Y1fORxG0DWBXm0a%2FSFQ8GPl7yYJOAphW8DX4s0MtAq8KmHbMSph1AA%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "selfQualified": true, 
    "value": {
      "amount": 499
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/3b55cefa2396418db56d896da668b1cb/bids/9f1bfacc9b744b62a43ad0cfd879694d
{
  "access": {
    "token": "fbc106ab86374a2f9216ab2e65244bba"
  }, 
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3b55cefa2396418db56d896da668b1cb/bids/9f1bfacc9b744b62a43ad0cfd879694d/documents/f255db79c9544942b540fb56737de1ba?download=773a4d7f2d654f479eaa182ab2704ff1", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:24:48.332853+03:00", 
        "id": "f255db79c9544942b540fb56737de1ba", 
        "dateModified": "2018-09-21T05:24:48.332890+03:00"
      }
    ], 
    "selfEligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "9f1bfacc9b744b62a43ad0cfd879694d", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2018-09-21T05:24:48.331547+03:00", 
    "selfQualified": true
  }
}

