POST /api/2.5/tenders/5024f5304a88457b8be641b86915fca2/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1086
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "selfEligible": true, 
    "documents": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3bd193cba05c4d938d941467d8657732?KeyID=a8968c46&Signature=%2FbpNiuZ9LmhJ7Ncypq46XRN%2FpD22dc05dHhVo4Hh5JoSpgZBC2WifWlqXWV8nntXw1d578UHnNZDukDnxAvXCA%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "selfQualified": true, 
    "value": {
      "amount": 499
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "name": "Андрій Олексюк", 
          "telephone": "+380 (322) 91-69-30"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5024f5304a88457b8be641b86915fca2/bids/bb38269ef0d844069ba346b632f8eca5
{
  "access": {
    "token": "67f292dc037a45e88cc75e8e5d093c04"
  }, 
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5024f5304a88457b8be641b86915fca2/bids/bb38269ef0d844069ba346b632f8eca5/documents/0c1ed29494474bd885492f6939f99d00?download=3bd193cba05c4d938d941467d8657732", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-18T09:36:47.317154+03:00", 
        "id": "0c1ed29494474bd885492f6939f99d00", 
        "dateModified": "2019-04-18T09:36:47.317166+03:00"
      }
    ], 
    "selfEligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "bb38269ef0d844069ba346b632f8eca5", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-04-18T09:36:47.316745+03:00", 
    "selfQualified": true
  }
}

