GET /api/2.4/tenders/3b55cefa2396418db56d896da668b1cb/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/46e52fd8864b4ad59819c6ba3b523309?KeyID=b0f44a83&Signature=jT7XkzwSblz%252B%252BVbaWfpm2uRKS2wJk1KTV2FXefB1JiOfscboms5PgL%252B25sRw7rW6mZ9iVYdDf%2Fh%252BTuG2otspAw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-09-21T05:24:45.518381+03:00", 
      "id": "0dba421476bc40b896170bd834c4d46c", 
      "dateModified": "2018-09-21T05:24:45.518427+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/c5503649bd83481c9aea18d47f0309d8?KeyID=b0f44a83&Signature=F33W%252BAnu8HGT2CE6TitcVW0w%252BvwzLP%252BPH1%252B4lOa5NKJb7AStEb09Z7O4Mfh71s8nBW4EfvA5qPnQvexk34odCQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-09-21T05:24:45.692136+03:00", 
      "id": "356295eb75d444f18e29fd3ede7900c6", 
      "dateModified": "2018-09-21T05:24:45.831342+03:00"
    }
  ]
}

