GET /api/2.5/tenders/e88963ba5b4f426e9c7a665f8cfd988a/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b29915c1f70447f99a46b80aead3d5a8?KeyID=a8968c46&Signature=GjYI0yTiUlKbGib5yzxtPVGdZ6vA4dPG56Ihow6tO7fOQvJSYkFCRfEHyJZjczaMkjabHbscA1263CWaJ2LuDg%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-18T13:07:15.236574+03:00", 
      "id": "f8f8e952353d442aa9ae51c610907438", 
      "dateModified": "2019-04-18T13:07:15.236588+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b372c2d4455e466ebfa20bba271f8796?KeyID=a8968c46&Signature=ATNyddDg3nBPpCxSLn1XqGhVR0KWv1vEyh%252BVuPrrgikiQk6yI0iuUn7iRPrLY9oA%252BsgDHv8emv%252BeTjrajhwrBg%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-18T13:07:15.278533+03:00", 
      "id": "ddc23071c36148c7858efb69bb5f1d36", 
      "dateModified": "2019-04-18T13:07:15.323240+03:00"
    }
  ]
}

