GET /api/2.5/tenders/7c8c978fa6554fc187f93dc3ed43a9c2/documents?acc_token=cb5263ac741e46298e9888a5a80aea29 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7cfbf3207c974a4e893d2d7dee4b91fd?KeyID=8af4a23b&Signature=mbdYv9W2eSYnq2rAtjbNERPC8PmVtELdMpCRd1hlXO7s6dHiZjrmwpu8n9ayXYUK8IQMRIAjIuyXrZC2rwj4Bw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-18T06:51:44.745536+03:00", 
      "id": "31a4b53018b64e93a95a10e004ef5687", 
      "dateModified": "2019-04-18T06:51:44.745551+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/00c6ab1b71844fc28b9cf9420dbf35cd?KeyID=8af4a23b&Signature=KRdHokFSiZrHqWAHwSLiI8XplmvsOtq0wrj9gCtdLBgOc8jxz21SMzPyovmisMMWaIxDUi6veTnF%252BPH%2FsODcBQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-18T06:51:44.782103+03:00", 
      "id": "229b4449f4f74554865bf144b1f895b7", 
      "dateModified": "2019-04-18T06:51:44.782116+03:00"
    }
  ]
}

