PATCH /api/2.5/tenders/06b9364fdced45db9dfab3d2cb29360a/contracts/8b8c0a9f5d714f00b024cb953fe0eded?acc_token=1e7e40493b384af1a9f78232e0fceddd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 54
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "value": {
      "amount": 238, 
      "amountNet": 230
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-05-08T11:23:35.862731+03:00", 
          "endDate": "2019-05-18T11:26:07.880163+03:00"
        }, 
        "id": "878a94840394414faf6733a10b1f8bd7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-04-18T11:25:58.858227+03:00", 
    "awardID": "0b9c3f112aad4aeaac293576f9739449", 
    "id": "8b8c0a9f5d714f00b024cb953fe0eded", 
    "contractID": "UA-2019-04-18-000001-1"
  }
}

