GET /api/2.5/tenders?opt_pretty=1 HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "next_page": {
    "path": "/api/2.5/tenders?offset=2019-04-18T09%3A22%3A08.663491%2B03%3A00", 
    "uri": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders?offset=2019-04-18T09%3A22%3A08.663491%2B03%3A00", 
    "offset": "2019-04-18T09:22:08.663491+03:00"
  }, 
  "data": [
    {
      "id": "fee4f0ba21ee453cb3dddf9df0e43730", 
      "dateModified": "2019-04-18T09:22:08.663491+03:00"
    }
  ]
}

