PATCH /api/2.5/tenders/5024f5304a88457b8be641b86915fca2/contracts/57dad7194a7e4bd496e57af7e2bb2df9?acc_token=6a7fea14754a4d18a2781c6d9cd674fa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 118
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "period": {
      "startDate": "2019-04-18T09:36:47.986551+03:00", 
      "endDate": "2020-04-17T09:36:47.986573+03:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-05-08T09:34:10.497990+03:00", 
          "endDate": "2019-05-18T09:36:56.651701+03:00"
        }, 
        "id": "abd78e19cc0b40de822de627837a4971", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2019-04-18T09:36:47.986551+03:00", 
      "endDate": "2020-04-17T09:36:47.986573+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2019-04-18T09:36:47.907243+03:00", 
    "date": "2019-04-18T09:36:47.755092+03:00", 
    "awardID": "598c3d6d51d0408fb3ceff2bc80799df", 
    "id": "57dad7194a7e4bd496e57af7e2bb2df9", 
    "contractID": "UA-2019-04-18-000001-1"
  }
}

