GET /api/2.5/tenders/2741dfda90ec4955a16232b29654f06e/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/fb8e1160dd464bc281ae1e0e98639c09?KeyID=a8968c46&Signature=XVOpl6FlqiLLa5fYxMQxbHnUy8GsCctl6V7FlymLyMlIynzmOWkJGYBJtdk8%2FThpOl3UEN%252BodGsmpvPF4dnrBQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "907cca0303ec41ceb413a9467a30bbf8", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/598c341ea25e40a0b8d38764e0a08c48?KeyID=a8968c46&Signature=cLEj37u8cJRsLpY5cFOxcjiyrHw7TPOXyMPllvc3lSv2xzf%252Bnw7502r%2FjlkKFcXRHrvPq5fR1cyTD13yDVuTAQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "7e217ea67b02400aac93c88b3fd0f77e", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }
  ]
}

