GET /api/2.5/tenders/e88963ba5b4f426e9c7a665f8cfd988a/documents/f8f8e952353d442aa9ae51c610907438?acc_token=cf3b24da4e174f928a46e671dee5d8fd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b29915c1f70447f99a46b80aead3d5a8?KeyID=a8968c46&Signature=GjYI0yTiUlKbGib5yzxtPVGdZ6vA4dPG56Ihow6tO7fOQvJSYkFCRfEHyJZjczaMkjabHbscA1263CWaJ2LuDg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-18T13:07:15.236574+03:00", 
    "previousVersions": [], 
    "id": "f8f8e952353d442aa9ae51c610907438", 
    "dateModified": "2019-04-18T13:07:15.236588+03:00"
  }
}

