PATCH /api/2.5/tenders/ecf287a696234915834e93bd9c09f0f4?acc_token=7cd5e8ac1cdc400b9d0f5f1ada3976be HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 88
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "items": [
      {
        "deliveryDate": {
          "endDate": "2019-04-27T06:48:55.040240+02:00"
        }
      }
    ]
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "tenderPeriod should be extended by 7 days", 
      "location": "body", 
      "name": "data"
    }
  ]
}

