PUT /api/2.5/tenders/06b9364fdced45db9dfab3d2cb29360a/documents/aa12937c810348de8c036a312fb7f746?acc_token=1e7e40493b384af1a9f78232e0fceddd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 196
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy128517242786$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3eba6d2f66cd4b9b81d3a30ffe8d98df?KeyID=a8968c46&Signature=wCzhyvGhpNlJnuEkjD8vedaruYkzWXhtDXR%252B27MxHj82pRB1Y9ijAfqJS4jwsktaBYegGdO1XRDcwtcUqnBtDg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-18T11:25:57.660482+03:00", 
    "id": "aa12937c810348de8c036a312fb7f746", 
    "dateModified": "2019-04-18T11:25:57.701378+03:00"
  }
}

