PATCH /api/2.5/tenders/2741dfda90ec4955a16232b29654f06e/cancellations/1b098c7eee174deba055afb4ae635549?acc_token=d3a8bbfc3ee34918a43986ccc34184ca HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-04-01T01:30:00+03:00", 
    "cancellationOf": "tender", 
    "id": "1b098c7eee174deba055afb4ae635549"
  }
}

