PATCH /api/2.5/tenders/5024f5304a88457b8be641b86915fca2?acc_token=6a7fea14754a4d18a2781c6d9cd674fa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 153
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "items": [
      {
        "deliveryDate": {
          "endDate": "2019-05-18T09:36:56.651701+03:00"
        }
      }
    ], 
    "tenderPeriod": {
      "endDate": "2019-04-26T09:36:46.715445+03:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "selective", 
    "complaintPeriod": {
      "startDate": "2019-03-21T09:36:46.633306+03:00", 
      "endDate": "2019-04-22T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-03-21T09:36:46.633306+03:00", 
      "clarificationsUntil": "2019-04-19T09:36:46.715445+03:00", 
      "endDate": "2019-04-16T09:36:46.715445+03:00", 
      "invalidationDate": "2019-04-18T09:36:46.769836+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-04-26T09:36:46.715445+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "kind": "special", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-04-18T09:36:46.591000+03:00", 
        "title": "Калорійність", 
        "date": "2019-04-18T09:36:46.554569+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "d1b5603f04f74f44af417d7026fb8d95", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "5024f5304a88457b8be641b86915fca2", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a62e72678e0147a2bd6632c0ec3442dd?KeyID=a8968c46&Signature=h4XKApo8zB4bkwZvROvB9EBn2H1cp47XNVrvhJpvzelnYmWSCux%2FOkAxquL%2FBvsKRu7YSkua29ORSoAmjkvKDg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-18T09:36:46.410425+03:00", 
        "id": "a374b249a5c840c794472d64e42e51e3", 
        "dateModified": "2019-04-18T09:36:46.410440+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1189b3cb598d48c5b4e12caa8ec249e0?KeyID=a8968c46&Signature=eh5kzkA%252BPys14Fu8BhzuTDbzZJUm%252BuYDeab3VmjHBwN06FYHx283t1%2F%2Fxky1S8ZlayfmSVY%252Bir%2Fksz9B%2FD6zCg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-18T09:36:46.448249+03:00", 
        "id": "f1708247b92c4a35b20a058fe7ba4b90", 
        "dateModified": "2019-04-18T09:36:46.448262+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5eadf874f1164f16879fae68c91a3d4b?KeyID=a8968c46&Signature=2Y8vEurHSuQ%252BD%252BnNt3bTvvoYm82BuUL66D0h5mntxb579y7ab7RpplGG0w17yUmAU8LBC8rGtnkjvkdBYy56DQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-18T09:36:46.448249+03:00", 
        "id": "f1708247b92c4a35b20a058fe7ba4b90", 
        "dateModified": "2019-04-18T09:36:46.487884+03:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "shortlistedFirms": [
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»"
      }
    ], 
    "tenderID": "UA-2019-04-18-000001", 
    "dateModified": "2019-04-18T09:36:46.772121+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2019-03-21T09:36:46.633306+03:00", 
      "endDate": "2019-04-26T09:36:46.715445+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-04-27T00:00:00+03:00"
    }, 
    "procurementMethodType": "competitiveDialogueUA.stage2", 
    "date": "2019-04-18T09:36:46.372240+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-05-08T09:34:10.497990+03:00", 
          "endDate": "2019-05-18T09:36:56.651701+03:00"
        }, 
        "id": "abd78e19cc0b40de822de627837a4971", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

