PATCH /api/2.5/tenders/06b9364fdced45db9dfab3d2cb29360a?acc_token=1e7e40493b384af1a9f78232e0fceddd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 153
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "items": [
      {
        "deliveryDate": {
          "endDate": "2019-05-18T11:26:07.880163+03:00"
        }
      }
    ], 
    "tenderPeriod": {
      "endDate": "2019-04-26T11:25:57.947220+03:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "selective", 
    "complaintPeriod": {
      "startDate": "2019-03-21T11:25:57.855875+03:00", 
      "endDate": "2019-04-22T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-03-21T11:25:57.855875+03:00", 
      "clarificationsUntil": "2019-04-19T11:25:57.947220+03:00", 
      "endDate": "2019-04-16T11:25:57.947220+03:00", 
      "invalidationDate": "2019-04-18T11:25:58.002563+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-04-26T11:25:57.947220+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "kind": "special", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-04-18T11:25:57.807774+03:00", 
        "title": "Калорійність", 
        "date": "2019-04-18T11:25:57.766562+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "a9de1528c4204169bcd56eed21958d51", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "06b9364fdced45db9dfab3d2cb29360a", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3440a9af8e9d410d99a7fa35ea641068?KeyID=a8968c46&Signature=JzdE0zX63XtlDKTieP3JnbV78U7u9F6VbjSx9G7n6dVgrI15WN%252BU3rVH%252ByYRCrVFdc%2FtwtMUHfP4BThbQzO3Ag%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-18T11:25:57.622118+03:00", 
        "id": "acfa75e16d1e4f71b4486717bf84cda0", 
        "dateModified": "2019-04-18T11:25:57.622132+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/13ca09c4eea946299f078f8c56150a10?KeyID=a8968c46&Signature=u%2FRXIfve2cXvJ%2FmWdhspXCyaNATYD6QM6nzvnV3raDBXefCTwKro60jDtc5YWc%2FTOkY%2FujXao9gDpX1LUlxCAA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-18T11:25:57.660482+03:00", 
        "id": "aa12937c810348de8c036a312fb7f746", 
        "dateModified": "2019-04-18T11:25:57.660496+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3eba6d2f66cd4b9b81d3a30ffe8d98df?KeyID=a8968c46&Signature=wCzhyvGhpNlJnuEkjD8vedaruYkzWXhtDXR%252B27MxHj82pRB1Y9ijAfqJS4jwsktaBYegGdO1XRDcwtcUqnBtDg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-18T11:25:57.660482+03:00", 
        "id": "aa12937c810348de8c036a312fb7f746", 
        "dateModified": "2019-04-18T11:25:57.701378+03:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "shortlistedFirms": [
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»"
      }
    ], 
    "tenderID": "UA-2019-04-18-000001", 
    "dateModified": "2019-04-18T11:25:58.004989+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2019-03-21T11:25:57.855875+03:00", 
      "endDate": "2019-04-26T11:25:57.947220+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-04-27T00:00:00+03:00"
    }, 
    "procurementMethodType": "competitiveDialogueUA.stage2", 
    "date": "2019-04-18T11:25:57.571805+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-05-08T11:23:35.862731+03:00", 
          "endDate": "2019-05-18T11:26:07.880163+03:00"
        }, 
        "id": "878a94840394414faf6733a10b1f8bd7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

