PATCH /api/2.5/tenders/0961fe2d5614420f9158a7db00eae734/cancellations/13418ddd4243497f8d76dde2bb129510?acc_token=17807c5f5bfd4facb419c3e0cfe1e2be HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-04-18T12:56:41.466589+03:00", 
    "cancellationOf": "tender", 
    "id": "13418ddd4243497f8d76dde2bb129510"
  }
}

