PATCH /api/2.5/tenders/7c8c978fa6554fc187f93dc3ed43a9c2?acc_token=cb5263ac741e46298e9888a5a80aea29 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 153
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "items": [
      {
        "deliveryDate": {
          "endDate": "2019-05-18T06:51:54.986581+03:00"
        }
      }
    ], 
    "tenderPeriod": {
      "endDate": "2019-04-26T06:51:45.052526+03:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "selective", 
    "complaintPeriod": {
      "startDate": "2019-03-21T06:51:44.967703+03:00", 
      "endDate": "2019-04-22T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-03-21T06:51:44.967703+03:00", 
      "clarificationsUntil": "2019-04-19T06:51:45.052526+03:00", 
      "endDate": "2019-04-16T06:51:45.052526+03:00", 
      "invalidationDate": "2019-04-18T06:51:45.104622+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-04-26T06:51:45.052526+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "kind": "special", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-04-18T06:51:44.925217+03:00", 
        "title": "Калорійність", 
        "date": "2019-04-18T06:51:44.885003+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "05b5bd06975b4e7ebe8c8abe8253b4c5", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "7c8c978fa6554fc187f93dc3ed43a9c2", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7cfbf3207c974a4e893d2d7dee4b91fd?KeyID=8af4a23b&Signature=mbdYv9W2eSYnq2rAtjbNERPC8PmVtELdMpCRd1hlXO7s6dHiZjrmwpu8n9ayXYUK8IQMRIAjIuyXrZC2rwj4Bw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-18T06:51:44.745536+03:00", 
        "id": "31a4b53018b64e93a95a10e004ef5687", 
        "dateModified": "2019-04-18T06:51:44.745551+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/00c6ab1b71844fc28b9cf9420dbf35cd?KeyID=8af4a23b&Signature=KRdHokFSiZrHqWAHwSLiI8XplmvsOtq0wrj9gCtdLBgOc8jxz21SMzPyovmisMMWaIxDUi6veTnF%252BPH%2FsODcBQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-18T06:51:44.782103+03:00", 
        "id": "229b4449f4f74554865bf144b1f895b7", 
        "dateModified": "2019-04-18T06:51:44.782116+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c1db8c5a4c7142579f5235503b3aeeed?KeyID=8af4a23b&Signature=gyh0mu%252BSjokCa84OUFtek9b%2FWexLXIGL3e%2FybJekXnkKQLwFA0UVaKdb2Qa%2FehZgO9MS65BErBw2vc3lZoliDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-18T06:51:44.782103+03:00", 
        "id": "229b4449f4f74554865bf144b1f895b7", 
        "dateModified": "2019-04-18T06:51:44.823226+03:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "shortlistedFirms": [
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»"
      }, 
      {
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»"
      }
    ], 
    "tenderID": "UA-2019-04-18-000001", 
    "dateModified": "2019-04-18T06:51:45.106880+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2019-03-21T06:51:44.967703+03:00", 
      "endDate": "2019-04-26T06:51:45.052526+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-04-27T00:00:00+03:00"
    }, 
    "procurementMethodType": "competitiveDialogueUA.stage2", 
    "date": "2019-04-18T06:51:44.711441+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-05-08T06:49:21.594749+03:00", 
          "endDate": "2019-05-18T06:51:54.986581+03:00"
        }, 
        "id": "a256b9862354434a99a7544f3e9b0eea", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

