PATCH /api/2.5/tenders/e88963ba5b4f426e9c7a665f8cfd988a/cancellations/57b4618b029e429db9fb6eda4556a8cd?acc_token=cf3b24da4e174f928a46e671dee5d8fd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-04-18T13:07:17.305651+03:00", 
    "cancellationOf": "tender", 
    "id": "57b4618b029e429db9fb6eda4556a8cd"
  }
}

