PUT /api/2.5/tenders/7c8c978fa6554fc187f93dc3ed43a9c2/documents/229b4449f4f74554865bf144b1f895b7?acc_token=cb5263ac741e46298e9888a5a80aea29 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 196
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy111758147073$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c1db8c5a4c7142579f5235503b3aeeed?KeyID=8af4a23b&Signature=gyh0mu%252BSjokCa84OUFtek9b%2FWexLXIGL3e%2FybJekXnkKQLwFA0UVaKdb2Qa%2FehZgO9MS65BErBw2vc3lZoliDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-18T06:51:44.782103+03:00", 
    "id": "229b4449f4f74554865bf144b1f895b7", 
    "dateModified": "2019-04-18T06:51:44.823226+03:00"
  }
}

