POST /api/2.5/tenders/0961fe2d5614420f9158a7db00eae734/documents?acc_token=17807c5f5bfd4facb419c3e0cfe1e2be HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 193
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy766675161028$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/0961fe2d5614420f9158a7db00eae734/documents/f3aecba41fd0408b8377c4a0413090ad
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "AwardCriteria.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ccf552b5c21e4a05bb3123e022a322a0?KeyID=a8968c46&Signature=cwDpOXwADtJVz%252BLhyC1aC8snEm1f9jWjtWq7SrhdqnI8ljDTOBq5c4NvPnLQEeUB5bpVtCOnB4jFObONLGutAw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-18T12:56:39.634290+03:00", 
    "id": "f3aecba41fd0408b8377c4a0413090ad", 
    "dateModified": "2019-04-18T12:56:39.634302+03:00"
  }
}

