POST /api/2.5/tenders/7ae73430bdc6461fbba58d7acfc04599/documents?acc_token=b2324bfe62894781a05b58070c3634ac HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 193
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy378113058187$
Host: api-sandbox.openprocurement.org


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/7ae73430bdc6461fbba58d7acfc04599/documents/00356de29a624a66bc9505145b22431f
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "AwardCriteria.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/b1134d2179f64376a0bf69240c2a52f6?KeyID=649bd9e2&Signature=OsGWjcN3iFOVuATS%2F%2F4R5ly%2FYA49USzHvjNSXWcJQHeYNQDGtw7Nl1Tda9dXzWZEJ%252BpUbTjv3tLQ3W82gAH5Bg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-18T16:28:06.394272+02:00", 
    "id": "00356de29a624a66bc9505145b22431f", 
    "dateModified": "2019-03-18T16:28:06.394299+02:00"
  }
}

