PATCH /api/2.5/tenders/87314e175bd440d98b59c1ddc4ea4428/questions/56fdf791d567471e898406190ce7ad43?acc_token=5b1e9d0b338449568122e0f4bf11fba9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2019-03-18T16:12:49.001188+02:00", 
    "title": "Калорійність", 
    "date": "2019-03-18T16:12:48.801251+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "56fdf791d567471e898406190ce7ad43", 
    "questionOf": "tender"
  }
}

