PATCH /api/2.5/tenders/19e26a9aabb84578920993b1d57f719d/qualifications/f688cf3e3ef045b3bf8bd112a91cc384?acc_token=dee9fca567cd400c87a7c52c22c6eaec HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "f1339086825247fa913cc0c496fba95d", 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "f688cf3e3ef045b3bf8bd112a91cc384"
  }
}

