PATCH /api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167/qualifications/7132747f2b4843d380e28e20b59ed063?acc_token=621ec741ce984bc194cb9cd44865825f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "107bedb54045460e9ba6d3e067fd666f", 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "7132747f2b4843d380e28e20b59ed063"
  }
}

