PATCH /api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167/qualifications/e34b5de9369a40a6a864cb748c72307b?acc_token=621ec741ce984bc194cb9cd44865825f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "6a8a88f9250f47f48785a858b5ceec52", 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "e34b5de9369a40a6a864cb748c72307b"
  }
}

