PATCH /api/2.4/tenders/6c51b2b430784297b2ce60215c18535f/qualifications/dbac9854df8d4ce98d456b9231333f73?acc_token=d5ed31fb489d4729a424b512f9b723f0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "496679c775144b1ba6c266e3b51accb4", 
    "date": "2018-09-21T05:47:15.402356+03:00", 
    "id": "dbac9854df8d4ce98d456b9231333f73"
  }
}

