PATCH /api/2.5/tenders/87314e175bd440d98b59c1ddc4ea4428/qualifications/2fcc0259f35847999360b3c83f321183?acc_token=5b1e9d0b338449568122e0f4bf11fba9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "e5507fd565d94b65bcb744fcfee811a6", 
    "date": "2019-03-18T16:12:57.676182+02:00", 
    "id": "2fcc0259f35847999360b3c83f321183"
  }
}

