GET /api/2.5/tenders/f643605221c54eb4b38a3f56b6b2215b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.auction", 
    "complaintPeriod": {
      "startDate": "2018-11-21T00:00:00+02:00", 
      "endDate": "2018-12-18T00:00:00+02:00"
    }, 
    "auctionUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/f643605221c54eb4b38a3f56b6b2215b", 
    "enquiryPeriod": {
      "startDate": "2018-11-21T00:00:00+02:00", 
      "clarificationsUntil": "2018-12-17T00:00:00+02:00", 
      "endDate": "2018-12-12T00:00:00+02:00", 
      "invalidationDate": "2019-01-01T00:00:00+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "title_en": "Services in school canteens", 
    "next_check": "2019-01-01T00:36:00+02:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-01-01T00:00:00+02:00", 
        "title": "Калорійність", 
        "date": "2019-01-01T00:00:00+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "db25fa86f31d483d8655dfac9e6b3e3e", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "qualifications": [
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "769546be5a3a4c6fb5e4777e21c2dff9", 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "ce3be4b6cc2b45368d1aaa4397b486cb"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "7c2121abfa0b41bc833029e33230db1c", 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "bb2444ecb8f74cefae56eded89f0a6f3"
      }, 
      {
        "status": "unsuccessful", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "fe11dab82d88488b955774056d12a884", 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "0b4f0e893e8749d49b14986dc4cc7fc1"
      }
    ], 
    "id": "f643605221c54eb4b38a3f56b6b2215b", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dc83c629e80a4d99961f30535f84a001?KeyID=3ccbc1c3&Signature=Ly5vN8B5Bw2JN1Jv43rsMImIRfeBd0VQ0h90Qpb7h6H6HNjpUYTmxXgsnZJJZP4Vm1GIHSrqHplAowYz6F53DQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "6d103ecff7824fcb83751d0e3a006419", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e3629449646543debe674e6cb5e5dcee?KeyID=3ccbc1c3&Signature=SKf%252B%2FWLaNiHKrEzLUhAGdC30jLptsieAsyNFB3xhd%2F9oLvNTxMkuOJZHhrfrHd2Y1cTt7VIlH%252B2hQbQGAXoaDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "177526642f9540caa432ebff58f06b2f", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0b0431bf2ff5490b9b91a5d6dc5afa50?KeyID=3ccbc1c3&Signature=RsEgGLu6oiOofqejORVqp%2Fr2P4am%2Fv6jUTK%252B1%2FGU9Z5mrIgzK7HhKpTqWj2j4ikiIc%2F4jApif1qNC10G0RZACg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "177526642f9540caa432ebff58f06b2f", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2018-12-22T00:00:00+02:00", 
      "endDate": "2019-01-01T00:00:00+02:00"
    }, 
    "tenderID": "UA-2019-01-01-000001", 
    "minimalStepPercentage": 0.006, 
    "auctionPeriod": {
      "startDate": "2019-01-01T00:00:00+02:00", 
      "shouldStartAfter": "2019-01-01T00:00:00+02:00"
    }, 
    "dateModified": "2019-01-01T00:00:00+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2018-11-21T00:00:00+02:00", 
      "endDate": "2018-12-22T00:00:00+02:00"
    }, 
    "NBUdiscountRate": 0.22986, 
    "yearlyPaymentsPercentageRange": 0.8, 
    "procurementMethodType": "esco", 
    "date": "2019-01-01T00:00:00+02:00", 
    "minValue": {
      "currency": "UAH", 
      "amount": 0.0, 
      "valueAddedTaxIncluded": true
    }, 
    "fundingKind": "other", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "a52b66c3bac44ded99f595cc088f1a85", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "c07f62aaa7ec4bfca4a94d68c69c0210", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/de0b58cd08c64c3893c1a164f04617bf?KeyID=3ccbc1c3&Signature=Cm3QYy8g9Ugk2XlO7dwk3WAb3sP1EsZOix6j6QFPaKtl9IN57pT%252BXiy5o5DXzqhBytejD80lyvftcNMddwnICg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-01-01T00:00:00+02:00", 
            "id": "23f01a832b43429a8a627edc4823d4ad", 
            "dateModified": "2019-01-01T00:00:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/f643605221c54eb4b38a3f56b6b2215b/bids/769546be5a3a4c6fb5e4777e21c2dff9/documents/560f8e86a70b49b19ad2119898b03e57?download=7143144019da4a669b99e70421ec0ff3", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_top_secrets.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-01-01T00:00:00+02:00", 
            "id": "560f8e86a70b49b19ad2119898b03e57", 
            "dateModified": "2019-01-01T00:00:00+02:00"
          }
        ], 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "id": "769546be5a3a4c6fb5e4777e21c2dff9", 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4bb186a44b0f45508b8aca2ad1efe717?KeyID=3ccbc1c3&Signature=x5LfgYx5DU7vhBKVxIzf%252BR9R1e2FEdZHFC6xgv%252BiNvk22keOkvLwV%252BJZcWh7R%2Fj%2FsWMC3ncOX8adNYPgooT%2FBA%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-01-01T00:00:00+02:00", 
            "id": "b36f8c3525ed4766b996dd49a211034f", 
            "dateModified": "2019-01-01T00:00:00+02:00"
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "7c2121abfa0b41bc833029e33230db1c", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "unsuccessful", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal_part1.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c3c272b01c5741f1b42d6c0c164b1dff?KeyID=3ccbc1c3&Signature=zX9ThsaXQRXUHIYd58F6vxBk1Qk7QMjbaB6Rs9L47jFlTgk7Tc0fcbneXAi3Ytw0n2j0CI5WR5QOUzsaPfFMAQ%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-01-01T00:00:00+02:00", 
            "id": "25a787a53b4e4157ad4487e74e5c053a", 
            "dateModified": "2019-01-01T00:00:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/f643605221c54eb4b38a3f56b6b2215b/bids/fe11dab82d88488b955774056d12a884/documents/26f7ede3d5fb4211bd51189390a2e3b7?download=4696b8c0706f48d7b08344d97fce006d", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_part2.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-01-01T00:00:00+02:00", 
            "id": "26f7ede3d5fb4211bd51189390a2e3b7", 
            "dateModified": "2019-01-01T00:00:00+02:00"
          }
        ], 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9a0e55a488d64b07a6bb32530aae3073?KeyID=3ccbc1c3&Signature=CWmxm8EOKL%2FychJhlgWtbF76AlhMhteWpOgYfQj4m24N84e9VVtLWXCyjsqV4pn3b6GysuC9QDRrWom4b2BuCg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-01-01T00:00:00+02:00", 
            "id": "f2d30f7b24e746079d867f961a2a5f5a", 
            "dateModified": "2019-01-01T00:00:00+02:00"
          }
        ], 
        "selfEligible": true, 
        "selfQualified": true, 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "id": "fe11dab82d88488b955774056d12a884"
      }
    ], 
    "noticePublicationDate": "2019-01-01T00:00:00+02:00", 
    "awardCriteria": "ratedCriteria"
  }
}

