GET /api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.auction", 
    "complaintPeriod": {
      "startDate": "2019-02-19T01:00:00+03:00", 
      "endDate": "2019-03-18T00:00:00+02:00"
    }, 
    "auctionUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/b92b4800a6a44cf2b362dba94c21c167", 
    "enquiryPeriod": {
      "startDate": "2019-02-19T01:00:00+03:00", 
      "clarificationsUntil": "2019-03-15T01:00:00+03:00", 
      "endDate": "2019-03-12T01:00:00+03:00", 
      "invalidationDate": "2019-04-01T01:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "title_en": "Services in school canteens", 
    "next_check": "2019-04-01T01:36:00+03:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-04-01T01:00:00+03:00", 
        "title": "Калорійність", 
        "date": "2019-04-01T01:00:00+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "a49d2b85c4c74d9db36c40977ee72c76", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "qualifications": [
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "6a8a88f9250f47f48785a858b5ceec52", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "e34b5de9369a40a6a864cb748c72307b"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "107bedb54045460e9ba6d3e067fd666f", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "7132747f2b4843d380e28e20b59ed063"
      }, 
      {
        "status": "unsuccessful", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "f6d07c2fcf8c49079a0deaf1fb4fa06e", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "1b18b0860f6e4b88a6d952bd768a84b2"
      }
    ], 
    "id": "b92b4800a6a44cf2b362dba94c21c167", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0eb14a2189b243379c13a34eee161655?KeyID=a8968c46&Signature=BL9zHxGwatthHKQWEqr5bDi3jWsf0n5NaZHRQtBCd2ZQRbDWA2%2F%252B4OG%2FjlKE0oUQ1BPsbLJWQIgQIIPY7ugPAA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "624fdaa373a448869b399878eb2c9a6e", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/641fe1f649eb43aead3af963a21979bc?KeyID=a8968c46&Signature=gZ0%252BC2AIyYH0%252BzLLk42gXP1k9gwD3dppFdeUH%252BsOI3Kp%252Bxv3mO8fKzx5LLMVp9ZXXaU%2F6qcu9hqgwzPoxa%252BWBA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "a7419f558bbe4cd69faf8272c653f9a2", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0829b8fd2b604102be97bd337d3fa0eb?KeyID=a8968c46&Signature=WWrBA4eaVbp43Up9BR2tu0nXBYEu3FaXB6BUEw0bHb9sCpAJA%252By631pKJ7632PxDSk8QIopoH8%252BaYFZzhG9oAA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "a7419f558bbe4cd69faf8272c653f9a2", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2019-03-22T01:00:00+03:00", 
      "endDate": "2019-04-01T01:00:00+03:00"
    }, 
    "tenderID": "UA-2019-04-01-000001", 
    "minimalStepPercentage": 0.006, 
    "auctionPeriod": {
      "startDate": "2019-04-01T01:00:00+03:00", 
      "shouldStartAfter": "2019-04-02T00:00:00+03:00"
    }, 
    "dateModified": "2019-04-01T01:00:00+03:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2019-02-19T01:00:00+03:00", 
      "endDate": "2019-03-22T01:00:00+03:00"
    }, 
    "NBUdiscountRate": 0.22986, 
    "yearlyPaymentsPercentageRange": 0.8, 
    "procurementMethodType": "esco", 
    "date": "2019-04-01T01:00:00+03:00", 
    "minValue": {
      "currency": "UAH", 
      "amount": 0.0, 
      "valueAddedTaxIncluded": true
    }, 
    "fundingKind": "other", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "1b1c65d5299a4072a9f57fcbb2025f0e", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "d16b49fc6d704036a4af2e35dd8d961d", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/86092f57f022415faf7df559fefa69ea?KeyID=a8968c46&Signature=8ytdG5Tz5jHmFbwj7krOAq9AqlE4FVYqQuGxRsmF6z6retJcYkStydWZtaFXL0RVOt5fh3m2fYhbw%252BYyTnTrDQ%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "6189219af77840e28cf765abcffca6f3", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167/bids/6a8a88f9250f47f48785a858b5ceec52/documents/2aaf4ef6adb040278f752998db520ad5?download=7e47caaec7004c36867d7350813f49ea", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_top_secrets.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "2aaf4ef6adb040278f752998db520ad5", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }
        ], 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "scale": "micro", 
            "name": "ДКП «Школяр»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "id": "6a8a88f9250f47f48785a858b5ceec52", 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/74b2b2b64ab44f5c97a8e74b1ad5128e?KeyID=a8968c46&Signature=ijOJNoLjHNxpBMxkRF9cWSXOUPfAXQp1FMXJXroQgIJ4O3Z%252Bj4UeCC9f9yOsbQuoh7WfcCQptlF7OuILhrxLDw%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "97f5208e4d814afdbf228220c28d96c5", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "107bedb54045460e9ba6d3e067fd666f", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "scale": "sme", 
            "name": "ДКП «Книга»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "unsuccessful", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal_part1.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a975591d95b244ecb9c7db6f69a3961a?KeyID=a8968c46&Signature=VC127KxC8Y5KHNgvbjji5m0pd1d%252BMe9%2FqXWBNkrxrSQyvgfkYqgwuJ3bNqcSFA7IA8j7PZJChVR6QIarkopHAQ%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "8438cda5633c400992496a6d91c9f403", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167/bids/f6d07c2fcf8c49079a0deaf1fb4fa06e/documents/d77d8496af234829872b57cae731e786?download=b8e4debb4ab1498abc828d0a9b207f33", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_part2.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "d77d8496af234829872b57cae731e786", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }
        ], 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f44e75a41ab7403896620fbbe1eddaa4?KeyID=a8968c46&Signature=3TVOWzSmw7fnfMXhF7vlipha2wdz4%2FDYdo1AKC6kRFPdLPmnNr7a6C%2FNhyDoM28iHpFBAKZs%2FbT%252BmvPYXeezDA%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "8eab4097d516420191a20ad12901b742", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }
        ], 
        "selfEligible": true, 
        "selfQualified": true, 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "scale": "sme", 
            "name": "ДКП «Книга»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "id": "f6d07c2fcf8c49079a0deaf1fb4fa06e"
      }
    ], 
    "noticePublicationDate": "2019-04-01T01:00:00+03:00", 
    "awardCriteria": "ratedCriteria"
  }
}

