PATCH /api/2.5/tenders/47c299215c6a46e584aeee1bc8fef16e/awards/23586334393648aba50bf73b09995fae/complaints/10748eb6db9f4a7da1cd19c8405fa762?acc_token=73598f0420474aaaae22af9c5549e265 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 228
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "stopping", 
    "cancellationReason": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "stopping", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "cancellationReason": "Тендер скасовується замовником", 
    "dateCanceled": "2019-03-18T16:12:32.165918+02:00", 
    "dateAccepted": "2019-03-18T16:12:26.597004+02:00", 
    "dateSubmitted": "2019-03-18T16:12:17.870527+02:00", 
    "complaintID": "UA-2019-03-18-000001.4", 
    "date": "2019-03-18T16:12:32.224688+02:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "10748eb6db9f4a7da1cd19c8405fa762"
  }
}

