POST /api/2.5/tenders/cdac51b77e724fe48cf283c942aea9d9/awards/4bfe2d4d2cff45a4837a2944d947d3ba/complaints/b52c3416c4614bd9a683e015dacd6395/documents?acc_token=b2ebfdbeacda4573b047d0b036591677 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 199
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy82381026889$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/cdac51b77e724fe48cf283c942aea9d9/awards/4bfe2d4d2cff45a4837a2944d947d3ba/complaints/b52c3416c4614bd9a683e015dacd6395/documents/d3e890f3797b4ef898fc78724f132d43
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/94abe325c7944a6d932bb042d3c2308f?KeyID=df2c4570&Signature=NWMnsSL9FP7wO3DAM9u0m9Z74i%252B3ssUKSDgDLknbmfNfKwd5OeL5omKUJgtVgc0he6oeUTzVyxdd%2FkwCZXCzAQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:30:00+02:00", 
    "id": "d3e890f3797b4ef898fc78724f132d43", 
    "dateModified": "2019-01-01T00:30:00+02:00"
  }
}

