POST /api/2.5/tenders/4e74deb4a2fc4935b49c9179e2b990f9/awards/5677a802219b4f8ea54c2bb1d7768b59/complaints/23e09f9d61da4422a582e2f42d315932/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 201
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy0489957300736$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/4e74deb4a2fc4935b49c9179e2b990f9/awards/5677a802219b4f8ea54c2bb1d7768b59/complaints/23e09f9d61da4422a582e2f42d315932/documents/5fad213e5b2c427bad19ae93c9ffa5b3
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/aacedbbe12ad42dabc537ee628c3d542?KeyID=6a9b54e8&Signature=QfiiSnRNSjfbuPx01ejjbb5BwfsdN%2FPsJjbf9g8r4TERe9OvHz0XsKp73uyzFKXHPmiGUfvBIgrQeOQq7WViAA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-28T06:49:06.427726+02:00", 
    "id": "5fad213e5b2c427bad19ae93c9ffa5b3", 
    "dateModified": "2019-03-28T06:49:06.427743+02:00"
  }
}

