PATCH /api/2.4/tenders/37704dbce00e43b29b51748e4276a5c3/awards/b486cdd6577b4e90a14870655b8f5c38/complaints/4f3bc5ec3e0c4677a180ef76fc442863 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "declined"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "declined", 
    "dateDecision": "2018-09-21T05:46:49.930663+03:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "dateAccepted": "2018-09-21T05:46:47.178690+03:00", 
    "dateSubmitted": "2018-09-21T05:46:40.743429+03:00", 
    "complaintID": "UA-2018-09-21-000001.3", 
    "date": "2018-09-21T05:46:49.994953+03:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "4f3bc5ec3e0c4677a180ef76fc442863"
  }
}

