POST /api/2.5/tenders/cdac51b77e724fe48cf283c942aea9d9/awards/4bfe2d4d2cff45a4837a2944d947d3ba/complaints/b52c3416c4614bd9a683e015dacd6395/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 197
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy83655241911$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/cdac51b77e724fe48cf283c942aea9d9/awards/4bfe2d4d2cff45a4837a2944d947d3ba/complaints/b52c3416c4614bd9a683e015dacd6395/documents/7e0456c1556f45da84c704b227386c41
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ffa7a3144ffd4602842ac84a4ffbb687?KeyID=df2c4570&Signature=08hs%2FXH3ZnhMm66CS2jKDiFabLcDTnpa2UfPvmfcBu3%252BNoeieNexo%2FQqGYZGmuAwKUz42GdVfr4O2ibpJogjCw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:30:00+02:00", 
    "id": "7e0456c1556f45da84c704b227386c41", 
    "dateModified": "2019-01-01T00:30:00+02:00"
  }
}

