PATCH /api/2.5/tenders/bde326779f8742d7ad93431f9c1f6dce/awards/ae69af4c17fb4b2b8df97ac8d6c007ec/complaints/81cda75dfa6341a5a611c6563dd991a9?acc_token=07658b16e9f24636ab08313ad0bb65bb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/44313eeab466475b8c360bf9ee1b0bfd?KeyID=a8968c46&Signature=WU3vSfo0%252BfR5DamXIp1%252Bu0CyO8be%252BDZlkS1eP9S9hChBDizYT4y%252BbCvZ1TR8Lgabg%2FQk%252BkrXQdCehfUAVSP8AA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:30:00+02:00", 
        "id": "50694bf6767f4e4db01d4258186a96c1", 
        "dateModified": "2019-01-01T00:30:00+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "dateSubmitted": "2019-01-01T00:30:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.1", 
    "date": "2019-01-01T00:30:00+02:00", 
    "type": "complaint", 
    "id": "81cda75dfa6341a5a611c6563dd991a9"
  }
}

