PATCH /api/2.4/tenders/37704dbce00e43b29b51748e4276a5c3/awards/75c7361aade94883b1b7f942efa68209/complaints/fe732d6ce7b0494aa62171e5dfd682b2?acc_token=464442df939f4a7f90ef42ab9812987e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2018-09-21T05:46:56.597189+03:00", 
    "complaintID": "UA-2018-09-21-000001.9", 
    "date": "2018-09-21T05:46:56.667723+03:00", 
    "type": "claim", 
    "id": "fe732d6ce7b0494aa62171e5dfd682b2"
  }
}

