PATCH /api/2.5/tenders/e234fb168a9a4eae96cf2776aac2c690/awards/f3d8f89b9552466cb3f84cae3e0deb5a/complaints/bcea3ffc19114180bb3608ecdb7c335f?acc_token=19bed42acaa242d294ab854d8f429eb6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 387
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "transfer_token": "8f47211a0a7a1c515e9a9a0dfa0baa78ddce9c0122c3f0f4a73e969fc07dd72a2911c11683abbc51fb4668e9f564ad7d9a0ec278a551e4802c0bbcd21bded7c3", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAnswered": "2019-04-01T01:00:03+03:00", 
    "dateSubmitted": "2019-04-01T01:00:03+03:00", 
    "complaintID": "UA-2019-04-01-000001.6", 
    "date": "2019-04-01T01:00:03+03:00", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
    "id": "bcea3ffc19114180bb3608ecdb7c335f", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс."
  }
}

