PATCH /api/2.4/tenders/37704dbce00e43b29b51748e4276a5c3/awards/b486cdd6577b4e90a14870655b8f5c38?acc_token=c31aa388184b401d8c3bcc8131a4401a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/37704dbce00e43b29b51748e4276a5c3/awards/75c7361aade94883b1b7f942efa68209
{
  "data": {
    "status": "cancelled", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-09-21T05:46:37.729772+03:00", 
      "endDate": "2018-09-21T05:46:54.165242+03:00"
    }, 
    "bid_id": "b20dc6aa29604e1bb76211bccf390458", 
    "value": {
      "yearlyPaymentsPercentage": 0.9, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 9383.42, 
      "contractDuration": {
        "days": 74, 
        "years": 10
      }, 
      "amountPerformance": 860.12, 
      "annualCostsReduction": [
        500.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0
      ]
    }, 
    "date": "2018-09-21T05:46:54.305152+03:00", 
    "qualified": true, 
    "complaints": [
      {
        "status": "resolved", 
        "dateDecision": "2018-09-21T05:46:49.305098+03:00", 
        "tendererActionDate": "2018-09-21T05:46:51.787398+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Недостатньо інформації", 
        "id": "d4c82846d2cf4e7dab154dbed8d2e5b2", 
        "tendererAction": "Умови виправлено, вибір переможня буде розгянуто повторно", 
        "dateSubmitted": "2018-09-21T05:46:39.866890+03:00", 
        "complaintID": "UA-2018-09-21-000001.1", 
        "date": "2018-09-21T05:46:51.865378+03:00", 
        "acceptance": true, 
        "type": "complaint", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "complaint_owner", 
            "language": "uk", 
            "title": "Complaint_Attachement.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/0a4393d4643b4a4f8438caac701461eb?KeyID=0fbd1044&Signature=LeeWBFFH6viIdEZ5DejUjT19cqVE1yG3XDbpJEpSmf2BV8SLTaXs2MJ7XQ%252B9sXc2IZR0WEnm2kxbceqkTAgTCQ%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2018-09-21T05:46:39.442764+03:00", 
            "id": "0114718fcd574a24b81546255b3cbf29", 
            "dateModified": "2018-09-21T05:46:39.442860+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "aboveThresholdReviewers", 
            "language": "uk", 
            "title": "ComplaintResolution.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/ce584b0cac9e4dd699361ef9c2b93e11?KeyID=0fbd1044&Signature=8dVHvVXNnw1LMlmAYXHYu865A2UvAlqRq2ToxM%252BnNGu%252BUgNjX6adlNOaUeknO7jp7ssW6Y7wo7jSS649VdxVCw%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2018-09-21T05:46:48.645926+03:00", 
            "id": "9382f5c1541d489a80200cc48811d706", 
            "dateModified": "2018-09-21T05:46:48.645978+03:00"
          }
        ], 
        "dateAccepted": "2018-09-21T05:46:46.699522+03:00"
      }, 
      {
        "status": "invalid", 
        "dateDecision": "2018-09-21T05:46:46.243146+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": false, 
        "dateSubmitted": "2018-09-21T05:46:40.281128+03:00", 
        "complaintID": "UA-2018-09-21-000001.2", 
        "date": "2018-09-21T05:46:46.300874+03:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "454d17d967754b32851baab7396b457c"
      }, 
      {
        "status": "declined", 
        "dateDecision": "2018-09-21T05:46:49.930663+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": true, 
        "dateAccepted": "2018-09-21T05:46:47.178690+03:00", 
        "dateSubmitted": "2018-09-21T05:46:40.743429+03:00", 
        "complaintID": "UA-2018-09-21-000001.3", 
        "date": "2018-09-21T05:46:49.994953+03:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "4f3bc5ec3e0c4677a180ef76fc442863"
      }, 
      {
        "status": "stopped", 
        "dateDecision": "2018-09-21T05:46:53.233590+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "decision": "Тендер скасовується замовником", 
        "acceptance": true, 
        "cancellationReason": "Тендер скасовується замовником", 
        "dateCanceled": "2018-09-21T05:46:52.498580+03:00", 
        "dateAccepted": "2018-09-21T05:46:47.600884+03:00", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateSubmitted": "2018-09-21T05:46:41.182770+03:00", 
        "complaintID": "UA-2018-09-21-000001.4", 
        "date": "2018-09-21T05:46:53.316689+03:00", 
        "type": "complaint", 
        "id": "b7b3292615fc427991562604174c3c80"
      }, 
      {
        "status": "stopped", 
        "dateDecision": "2018-09-21T05:46:50.528186+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "decision": "Тендер скасовується замовником", 
        "acceptance": true, 
        "dateCanceled": "2018-09-21T05:46:50.528267+03:00", 
        "dateAccepted": "2018-09-21T05:46:48.111855+03:00", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateSubmitted": "2018-09-21T05:46:41.614163+03:00", 
        "complaintID": "UA-2018-09-21-000001.5", 
        "date": "2018-09-21T05:46:50.653993+03:00", 
        "type": "complaint", 
        "id": "a4e739a64ef04d68928e1c351e1ecad6"
      }, 
      {
        "status": "answered", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "Недостатньо інформації", 
        "satisfied": true, 
        "dateAnswered": "2018-09-21T05:46:42.700366+03:00", 
        "dateSubmitted": "2018-09-21T05:46:42.093073+03:00", 
        "complaintID": "UA-2018-09-21-000001.6", 
        "date": "2018-09-21T05:46:42.765479+03:00", 
        "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
        "id": "7b11da5f212a4c5aa30a20fe02745885"
      }, 
      {
        "status": "answered", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "invalid", 
        "type": "claim", 
        "title": "Недостатньо інформації", 
        "satisfied": false, 
        "dateAnswered": "2018-09-21T05:46:44.264066+03:00", 
        "dateSubmitted": "2018-09-21T05:46:43.693740+03:00", 
        "complaintID": "UA-2018-09-21-000001.7", 
        "date": "2018-09-21T05:46:44.313989+03:00", 
        "resolution": "Вимога не відповідає предмету закупівлі", 
        "id": "0c1795ef83164c27a17c5bc17c13abb4"
      }, 
      {
        "status": "claim", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Недостатньо інформації", 
        "dateSubmitted": "2018-09-21T05:46:45.824434+03:00", 
        "complaintID": "UA-2018-09-21-000001.8", 
        "date": "2018-09-21T05:46:45.877255+03:00", 
        "type": "claim", 
        "id": "a216aaca383f406d8c008d1f4e92d926"
      }
    ], 
    "id": "b486cdd6577b4e90a14870655b8f5c38"
  }
}

