GET /api/2.4/tenders/6c51b2b430784297b2ce60215c18535f/bids/e653edb5210b4af5a612fc85a04c8edd?acc_token=5e1c9fe2ecd04447b94dd9d6affec843 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "value": {
      "yearlyPaymentsPercentage": 0.85, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 9727.49, 
      "contractDuration": {
        "days": 200, 
        "years": 12
      }, 
      "amountPerformance": 794.73, 
      "annualCostsReduction": [
        400.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0
      ]
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2018-09-21T05:47:13.510800+03:00", 
    "id": "e653edb5210b4af5a612fc85a04c8edd", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/6c51b2b430784297b2ce60215c18535f?key_for_bid=e653edb5210b4af5a612fc85a04c8edd"
  }
}

