GET /api/2.5/tenders/deb082b3f3004fc1b115e78ee2d59f6c/bids/e7ddcaff2a3341cea8c596ac0db6c4c0?acc_token=f59d7a2c9ac143f3b35d73ac3134b037 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "value": {
      "yearlyPaymentsPercentage": 0.85, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 9356.52, 
      "contractDuration": {
        "days": 200, 
        "years": 12
      }, 
      "amountPerformance": 737.02, 
      "annualCostsReduction": [
        400.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0
      ]
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-03-28T06:49:14.152654+02:00", 
    "id": "e7ddcaff2a3341cea8c596ac0db6c4c0", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/deb082b3f3004fc1b115e78ee2d59f6c?key_for_bid=e7ddcaff2a3341cea8c596ac0db6c4c0"
  }
}

