GET /api/2.5/tenders/87314e175bd440d98b59c1ddc4ea4428/bids/e5507fd565d94b65bcb744fcfee811a6?acc_token=5e43f4091ed441b18478e0355965ad31 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "value": {
      "yearlyPaymentsPercentage": 0.85, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 9335.56, 
      "contractDuration": {
        "days": 200, 
        "years": 12
      }, 
      "amountPerformance": 734.21, 
      "annualCostsReduction": [
        400.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0, 
        900.0
      ]
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-03-18T16:12:54.336616+02:00", 
    "id": "e5507fd565d94b65bcb744fcfee811a6", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/87314e175bd440d98b59c1ddc4ea4428?key_for_bid=e5507fd565d94b65bcb744fcfee811a6"
  }
}

