PATCH /api/2.5/tenders/1e249c65e82a47b9b2edfb76505c3da5/complaints/006889248bf84b91800c4681ca2ab7f0?acc_token=84ffec67099a48e4ac27348c53b20bc5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2019-01-01T00:00:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.7", 
    "date": "2019-01-01T00:00:00+02:00", 
    "type": "claim", 
    "id": "006889248bf84b91800c4681ca2ab7f0"
  }
}

