POST /api/2.5/tenders/6410c40f39774997b547e4e4925b8861/complaints/8f0042a691124f27beb9fd28c5d68009/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 149
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="ComplaintResolution.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/6410c40f39774997b547e4e4925b8861/complaints/8f0042a691124f27beb9fd28c5d68009/documents/03b4cc4f7eb546ff9d6ffe65140b1869
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/461e4e65ea4b4d6790640d14ab7ec603?KeyID=a8968c46&Signature=BpvRHe%2FDgB6%2FZTd0Xp3M7r4%252BcjiBDQsx%252BV7uS2gLyGSN82EM7jiZ0Wihf4AvGXlKeI%252BrCjPjj3w8qctLI87JAQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "03b4cc4f7eb546ff9d6ffe65140b1869", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

