GET /api/2.5/tenders/6673d5975aba4f22ad8d0a00dcb628c5/complaints HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2019-04-01T01:00:00+03:00", 
      "tendererActionDate": "2019-04-01T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "36fd400143634cc5af07260977873d96", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.1", 
      "date": "2019-04-01T01:00:00+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/27b491885070432da79c60c21fd449f9?KeyID=a8968c46&Signature=xVVNgrxb%2FAC%2FdIH%252Beq3FNRTRLflBjKD23JqVtZf7S3oK3n4KdjrLCu6X9wBHpJ0VSua9EqB5CNa6uxW0YueACA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:00+03:00", 
          "id": "6575db1f2f804ddb80f455e75b8c00f5", 
          "dateModified": "2019-04-01T01:00:00+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6ee1160d64c24656b791bb24849c7cbb?KeyID=a8968c46&Signature=8SKQdX387OpTlrFchpuNyFoL%252BqZ1OG8RAa8iwibllt1U237hNO%252BTbi8gNQ3I8qsy5SerZxRm3pN8kLdj%2Fjb5Bw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:00+03:00", 
          "id": "81b28af0e2974afea3b5d96b152db21f", 
          "dateModified": "2019-04-01T01:00:00+03:00"
        }
      ], 
      "dateAccepted": "2019-04-01T01:00:00+03:00"
    }, 
    {
      "status": "resolved", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "dateAnswered": "2019-04-01T01:00:00+03:00", 
      "dateSubmitted": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.2", 
      "date": "2019-04-01T01:00:00+03:00", 
      "resolution": "Виправлено неконкурентні умови", 
      "id": "58bd04b10ed04320a8794efd953d0599"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2019-04-01T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2019-04-01T01:00:00+03:00", 
      "dateSubmitted": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.3", 
      "date": "2019-04-01T01:00:00+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "205e35730f264d89aae119d129045001"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2019-04-01T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "complaint", 
      "acceptance": false, 
      "satisfied": false, 
      "dateEscalated": "2019-04-01T01:00:00+03:00", 
      "dateAnswered": "2019-04-01T01:00:00+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.4", 
      "date": "2019-04-01T01:00:00+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "28627d943c204f3aae1ae806139d1de0"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-04-01T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2019-04-01T01:00:00+03:00", 
      "dateAccepted": "2019-04-01T01:00:00+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.5", 
      "date": "2019-04-01T01:00:00+03:00", 
      "type": "complaint", 
      "id": "5d82b0dfda294d37b19beef85f39345e"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-04-01T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2019-04-01T01:00:00+03:00", 
      "dateAccepted": "2019-04-01T01:00:00+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.6", 
      "date": "2019-04-01T01:00:00+03:00", 
      "type": "complaint", 
      "id": "b88b16476dd1453d945e8386fb97c2a8"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.7", 
      "date": "2019-04-01T01:00:00+03:00", 
      "type": "claim", 
      "id": "7c2fc46ab39942a7aa6d87d604beb7fb"
    }
  ]
}

