POST /api/2.5/tenders/6410c40f39774997b547e4e4925b8861/complaints/8f0042a691124f27beb9fd28c5d68009/documents?acc_token=43dbfaf867f24263b04d74818e2d4311 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 151
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/6410c40f39774997b547e4e4925b8861/complaints/8f0042a691124f27beb9fd28c5d68009/documents/8d791ae32c654c1bbad41822506f1383
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/72f82421e1964f6f94cfadc00c3071e5?KeyID=a8968c46&Signature=av%252BSLFG4FAMYs7xdvi1GMAaL38YMS4sFSM4diQ%252BICCXi%2F0V8rm7Vln0kyjbxEirsdHTfsvLC6MKitkL%2F5giTCg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "8d791ae32c654c1bbad41822506f1383", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

