PATCH /api/2.5/tenders/c1ff56f8f36644269a8023a68d7ba2e6/complaints/5c9211ae14e849a49e9cd6786b837f6b?acc_token=e2941a4223334d4ba48818be129140d7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 250
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "resolution": "Виправлено неконкурентні умови"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "dateAnswered": "2019-03-28T06:49:09.819269+02:00", 
    "dateSubmitted": "2019-03-28T06:49:09.568431+02:00", 
    "complaintID": "UA-2019-03-28-000001.2", 
    "date": "2019-03-28T06:49:09.823006+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "5c9211ae14e849a49e9cd6786b837f6b"
  }
}

