POST /api/2.5/tenders/1e249c65e82a47b9b2edfb76505c3da5/complaints/9cdfbc540dde48159c4a5f6c8d84a693/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 199
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy252856274995$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/1e249c65e82a47b9b2edfb76505c3da5/complaints/9cdfbc540dde48159c4a5f6c8d84a693/documents/f2c65709c1574c7fbaedad66a7cdf11e
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b4e262690c134facb9c87204ffcbbe39?KeyID=55ede853&Signature=Um4FIVlDQcha5ksIX76tSmCIIdVhtk8xi2M5uGEdVcHDEYF9wtX8w2RJD1912n4z3yB5pyNeiBc8OX3bRxHcDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "f2c65709c1574c7fbaedad66a7cdf11e", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

