GET /api/2.4/tenders/9a5ceb4265114ad98e4e8d76ddc552f6/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2018-09-21T05:47:03.612172+03:00", 
      "tendererActionDate": "2018-09-21T05:47:04.538883+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "d98f03ba86354f65bee9e32d64b0a113", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2018-09-21T05:47:00.047400+03:00", 
      "complaintID": "UA-2018-09-21-000001.1", 
      "date": "2018-09-21T05:47:04.553797+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/fd6b5c7396364ab8a329ca9276e893ed?KeyID=cd9add92&Signature=DiZK%2FthqpLQgw8gf452c9d%2Ftbne1gKvwXCieC2irbmFmeO3c3ywddabaMWsOmJhcBLqnu27Kbp9w%252BTahYkOmBg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-09-21T05:46:59.068001+03:00", 
          "id": "8ce5519a3fe84ce3a50e066c48c52737", 
          "dateModified": "2018-09-21T05:46:59.068093+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/f865b50df9864fc8875d6845decc492b?KeyID=cd9add92&Signature=cuVwfQ7kA%2F57rgiI7BmGbMAd5s8QbrJQn0iZxdB1xGAsclg91iAN32V499RZojUd8ZYur7%252BrHEq8LuuYfLDmCg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-09-21T05:47:03.264459+03:00", 
          "id": "5e2a7926c54d42079347bfcea8a74699", 
          "dateModified": "2018-09-21T05:47:03.264545+03:00"
        }
      ], 
      "dateAccepted": "2018-09-21T05:47:02.117175+03:00"
    }, 
    {
      "status": "resolved", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "dateAnswered": "2018-09-21T05:47:00.266403+03:00", 
      "dateSubmitted": "2018-09-21T05:46:59.340321+03:00", 
      "complaintID": "UA-2018-09-21-000001.2", 
      "date": "2018-09-21T05:47:00.728759+03:00", 
      "resolution": "Виправлено неконкурентні умови", 
      "id": "b2fec273b2144984a2f8750f0b037fd5"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2018-09-21T05:47:03.912236+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2018-09-21T05:47:02.381687+03:00", 
      "dateSubmitted": "2018-09-21T05:46:59.545878+03:00", 
      "complaintID": "UA-2018-09-21-000001.3", 
      "date": "2018-09-21T05:47:03.926036+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "3acf43fea91040da898a6a0fb95f28fb"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2018-09-21T05:47:01.830738+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "complaint", 
      "acceptance": false, 
      "satisfied": false, 
      "dateEscalated": "2018-09-21T05:47:01.027070+03:00", 
      "dateAnswered": "2018-09-21T05:47:00.473925+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-09-21T05:46:59.751536+03:00", 
      "complaintID": "UA-2018-09-21-000001.4", 
      "date": "2018-09-21T05:47:01.844130+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "0f81435c63bf488991a587228bd8f9cb"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-09-21T05:47:04.236366+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2018-09-21T05:47:04.236450+03:00", 
      "dateAccepted": "2018-09-21T05:47:02.632276+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-09-21T05:47:01.269968+03:00", 
      "complaintID": "UA-2018-09-21-000001.5", 
      "date": "2018-09-21T05:47:04.251128+03:00", 
      "type": "complaint", 
      "id": "43a82afc1a8c4b42925beb19337bfdf7"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-09-21T05:47:04.992424+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2018-09-21T05:47:04.769758+03:00", 
      "dateAccepted": "2018-09-21T05:47:02.929371+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-09-21T05:47:01.521774+03:00", 
      "complaintID": "UA-2018-09-21-000001.6", 
      "date": "2018-09-21T05:47:05.004445+03:00", 
      "type": "complaint", 
      "id": "3c1143e5db2c4e6b9ed88177130337c4"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2018-09-21T05:47:05.442398+03:00", 
      "complaintID": "UA-2018-09-21-000001.7", 
      "date": "2018-09-21T05:47:05.454032+03:00", 
      "type": "claim", 
      "id": "9fc0a1597ac94fb8882c9f7176ba18d9"
    }
  ]
}

