PATCH /api/2.5/tenders/19e26a9aabb84578920993b1d57f719d/awards/bf6214d4adf74c0287f135a4ebded475?acc_token=dee9fca567cd400c87a7c52c22c6eaec HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-01-01T00:00:00+02:00", 
      "endDate": "2019-01-12T00:00:00+02:00"
    }, 
    "bid_id": "2f36b22a71644508b4c978b6736da64c", 
    "value": {
      "yearlyPaymentsPercentage": 0.9, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 8734.93, 
      "contractDuration": {
        "days": 74, 
        "years": 10
      }, 
      "amountPerformance": 801.01, 
      "annualCostsReduction": [
        500.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0, 
        1000.0
      ]
    }, 
    "qualified": true, 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "bf6214d4adf74c0287f135a4ebded475"
  }
}

