POST /api/2.4/tenders/6c51b2b430784297b2ce60215c18535f/cancellations?acc_token=d5ed31fb489d4729a424b512f9b723f0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/6c51b2b430784297b2ce60215c18535f/cancellations/eef881b041e64891af84c3525cd2ed03
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2018-09-21T05:47:24.308748+03:00", 
    "cancellationOf": "tender", 
    "id": "eef881b041e64891af84c3525cd2ed03"
  }
}

