PATCH /api/2.5/tenders/37d9f9c8f1734692bc4958b73cd220e6/qualifications/aae340b510b64b258a82677c2f271a45/complaints/100ad8070b4a43638371412648a74697?acc_token=bcb1014dfebd4ee0abda16d459e0cfc1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "3ffba8d99a234b1d824b032600c7d2bf", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2019-04-01T01:10:00+03:00", 
    "complaintID": "UA-2019-04-01-000001.9", 
    "date": "2019-04-01T01:10:00+03:00", 
    "type": "claim", 
    "id": "100ad8070b4a43638371412648a74697"
  }
}

