PATCH /api/2.5/tenders/af9d87e1eb144d71a571c4941211c112/qualifications/7857d0a2d8544ca8a094e8aa7614b674/complaints/f07afa9d6ef34576b64fe8ae1bcbfb31?acc_token=75a02b6868c24dd78fcb400c9421fe86 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "satisfied": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": true, 
    "bid_id": "2e2fd282dd12463eae1e996c4d3f8c5b", 
    "dateAnswered": "2019-01-01T00:10:00+02:00", 
    "dateSubmitted": "2019-01-01T00:10:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.6", 
    "date": "2019-01-01T00:10:00+02:00", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
    "id": "f07afa9d6ef34576b64fe8ae1bcbfb31"
  }
}

