PATCH /api/2.5/tenders/76a47711227a4dbbb943008da264324e/qualifications/9fa3e3e47b314b08924359c928bdfd92/complaints/0da703c041384dd3959074abe0ba419b?acc_token=4ba114285ca848bf8983cb287a05ddb9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 387
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "bid_id": "828276a99597414b9bfd0e33022aa9ed", 
    "dateAnswered": "2019-01-01T00:10:00+02:00", 
    "dateSubmitted": "2019-01-01T00:10:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.6", 
    "date": "2019-01-01T00:10:00+02:00", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
    "id": "0da703c041384dd3959074abe0ba419b"
  }
}

