POST /api/2.5/tenders/37d9f9c8f1734692bc4958b73cd220e6/qualifications/aae340b510b64b258a82677c2f271a45/complaints/d1d343244559496f99d151d9e6942b78/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 149
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="ComplaintResolution.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/37d9f9c8f1734692bc4958b73cd220e6/qualifications/aae340b510b64b258a82677c2f271a45/complaints/d1d343244559496f99d151d9e6942b78/documents/600e972a1d4649a896bfa7edcb78f2ef
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b9b4f3b2179d4f948a6703eadef3fdfe?KeyID=a8968c46&Signature=Y0jLVtacAtq7ZLdGY5sxA14qTgW0PANAAaWr2tHgkU1qr%252B8mI8j1zRfmawFwcj9k8iyo3TOhx1kyUqS23ah7DA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:10:00+03:00", 
    "id": "600e972a1d4649a896bfa7edcb78f2ef", 
    "dateModified": "2019-04-01T01:10:00+03:00"
  }
}

