POST /api/2.5/tenders/37d9f9c8f1734692bc4958b73cd220e6/qualifications/aae340b510b64b258a82677c2f271a45/complaints?acc_token=11050b824deb4babb2c317acfbe23984 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1317
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "claim", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }, 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/37d9f9c8f1734692bc4958b73cd220e6/qualifications/aae340b510b64b258a82677c2f271a45/complaints/7ff590f916d04c0db1ad63949019a6b7
{
  "access": {
    "token": "21e48e213b2a41b69da5dc0b055abbe4"
  }, 
  "data": {
    "status": "claim", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "3ffba8d99a234b1d824b032600c7d2bf", 
    "dateSubmitted": "2019-04-01T01:10:00+03:00", 
    "complaintID": "UA-2019-04-01-000001.6", 
    "date": "2019-04-01T01:10:00+03:00", 
    "type": "claim", 
    "id": "7ff590f916d04c0db1ad63949019a6b7"
  }
}

