PATCH /api/2.5/tenders/0ca9713a8a8b4efb9233be1f445fb0d0/qualifications/b9d2f2f7775b4b6a9641dcad0abb8119/complaints/e9c904c083f7417ebd1c087a4a6742d0?acc_token=cf0ef37a2c5b4508aa5fda7b2c905497 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "claim"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "claim", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "e7527052d38547768fb5655afc78b27b", 
    "dateSubmitted": "2019-03-18T16:13:54.805202+02:00", 
    "complaintID": "UA-2019-03-18-000001.8", 
    "date": "2019-03-18T16:13:54.866241+02:00", 
    "type": "claim", 
    "id": "e9c904c083f7417ebd1c087a4a6742d0"
  }
}

