PATCH /api/2.5/tenders/af9d87e1eb144d71a571c4941211c112/qualifications/7857d0a2d8544ca8a094e8aa7614b674/complaints/80bef5551e534cbaa2fbbef8a23ca397?acc_token=281e301f9c61435b89bf66794265ab4c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "claim"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "claim", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "2e2fd282dd12463eae1e996c4d3f8c5b", 
    "dateSubmitted": "2019-01-01T00:10:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.8", 
    "date": "2019-01-01T00:10:00+02:00", 
    "type": "claim", 
    "id": "80bef5551e534cbaa2fbbef8a23ca397"
  }
}

