POST /api/2.5/tenders/0ca9713a8a8b4efb9233be1f445fb0d0/qualifications/b9d2f2f7775b4b6a9641dcad0abb8119/complaints/5eb0d59c32ca4bfab60355a32c232d43/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 199
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy646116410679$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/0ca9713a8a8b4efb9233be1f445fb0d0/qualifications/b9d2f2f7775b4b6a9641dcad0abb8119/complaints/5eb0d59c32ca4bfab60355a32c232d43/documents/000966af0e2044829a234ad960273b5f
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/74758b0d2e01421b8e1ff2acf47affa2?KeyID=be3ff0fa&Signature=pm3gjp4a3Z8CPj7qJiBSrZVIkQEpMk%2FBYjLGAeEwx7%2FzFuh5wdLvayCrO9QARGFKpTrquPJ6bh0Y57E9LjY4Aw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-18T16:13:58.235240+02:00", 
    "id": "000966af0e2044829a234ad960273b5f", 
    "dateModified": "2019-03-18T16:13:58.235262+02:00"
  }
}

