GET /api/2.5/tenders/0ca9713a8a8b4efb9233be1f445fb0d0/qualifications/b9d2f2f7775b4b6a9641dcad0abb8119/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2019-03-18T16:13:58.419930+02:00", 
      "tendererActionDate": "2019-03-18T16:13:58.894098+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "5eb0d59c32ca4bfab60355a32c232d43", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2019-03-18T16:13:43.951010+02:00", 
      "complaintID": "UA-2019-03-18-000001.1", 
      "date": "2019-03-18T16:13:58.910248+02:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/ac07cb9ebe8743ee8e39c50e7a58e40c?KeyID=be3ff0fa&Signature=QqDAQ7X9IcajD7bf1YdAKRv8y1my%2FPGdkFZ0KAsGrGVjrcvqkrulC5STlY6nh9Engptld2N%252BM42QJ52aVKqHDQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T16:13:43.115870+02:00", 
          "id": "782614e358584e8cbd803cf873542a8d", 
          "dateModified": "2019-03-18T16:13:43.116334+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/74758b0d2e01421b8e1ff2acf47affa2?KeyID=be3ff0fa&Signature=pm3gjp4a3Z8CPj7qJiBSrZVIkQEpMk%2FBYjLGAeEwx7%2FzFuh5wdLvayCrO9QARGFKpTrquPJ6bh0Y57E9LjY4Aw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T16:13:58.235240+02:00", 
          "id": "000966af0e2044829a234ad960273b5f", 
          "dateModified": "2019-03-18T16:13:58.235262+02:00"
        }
      ], 
      "dateAccepted": "2019-03-18T16:13:57.587027+02:00"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2019-03-18T16:13:56.847497+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2019-03-18T16:13:44.517953+02:00", 
      "complaintID": "UA-2019-03-18-000001.2", 
      "date": "2019-03-18T16:13:56.934705+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "3b52d0901d2a43429c04e92171382a16"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2019-03-18T16:13:58.571089+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2019-03-18T16:13:57.794610+02:00", 
      "dateSubmitted": "2019-03-18T16:13:45.501231+02:00", 
      "complaintID": "UA-2019-03-18-000001.3", 
      "date": "2019-03-18T16:13:58.586922+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "3cc7804242264272b0619d9bce422caf"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-03-18T16:13:59.203709+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2019-03-18T16:13:59.050626+02:00", 
      "dateAccepted": "2019-03-18T16:13:57.942753+02:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-03-18T16:13:46.244284+02:00", 
      "complaintID": "UA-2019-03-18-000001.4", 
      "date": "2019-03-18T16:13:59.220494+02:00", 
      "type": "complaint", 
      "id": "491ee42cb3d6483c94cf34f62414e6e7"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-03-18T16:13:58.733330+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2019-03-18T16:13:58.733358+02:00", 
      "dateAccepted": "2019-03-18T16:13:58.093382+02:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-03-18T16:13:47.376813+02:00", 
      "complaintID": "UA-2019-03-18-000001.5", 
      "date": "2019-03-18T16:13:58.749756+02:00", 
      "type": "complaint", 
      "id": "5550d2566ac14f38a8d7e87dbf8f55ad"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "bid_id": "e7527052d38547768fb5655afc78b27b", 
      "dateAnswered": "2019-03-18T16:13:49.855745+02:00", 
      "dateSubmitted": "2019-03-18T16:13:48.703840+02:00", 
      "complaintID": "UA-2019-03-18-000001.6", 
      "date": "2019-03-18T16:13:50.006658+02:00", 
      "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
      "id": "90bd460788074630a897ac7812e7fad8"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "claim", 
      "satisfied": false, 
      "bid_id": "e7527052d38547768fb5655afc78b27b", 
      "dateAnswered": "2019-03-18T16:13:52.699195+02:00", 
      "dateSubmitted": "2019-03-18T16:13:51.942415+02:00", 
      "complaintID": "UA-2019-03-18-000001.7", 
      "date": "2019-03-18T16:13:52.827880+02:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "deb81bbcfba54eb7944e4f2ad2b137c3"
    }, 
    {
      "status": "claim", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "bid_id": "e7527052d38547768fb5655afc78b27b", 
      "dateSubmitted": "2019-03-18T16:13:54.805202+02:00", 
      "complaintID": "UA-2019-03-18-000001.8", 
      "date": "2019-03-18T16:13:54.866241+02:00", 
      "type": "claim", 
      "id": "e9c904c083f7417ebd1c087a4a6742d0"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "bid_id": "e7527052d38547768fb5655afc78b27b", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2019-03-18T16:13:56.216184+02:00", 
      "complaintID": "UA-2019-03-18-000001.9", 
      "date": "2019-03-18T16:13:56.262867+02:00", 
      "type": "claim", 
      "id": "3a4473650ade4d97aa45fac9d6a34688"
    }
  ]
}

