PATCH /api/2.5/tenders/db62d144fe4b4d4fa661839d7095f95a/qualifications/d93afb5447f64b5883700239cffa68f8/complaints/b474c030d45442b8b2ff4d05bed0affe?acc_token=63d58b61741d4e9a8b5c6331cbe43f33 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "satisfied": false
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "invalid", 
    "type": "claim", 
    "satisfied": false, 
    "bid_id": "b53f85a45d1040a19b6a15256caba6bd", 
    "dateAnswered": "2019-03-28T06:49:24.739382+02:00", 
    "dateSubmitted": "2019-03-28T06:49:24.590108+02:00", 
    "complaintID": "UA-2019-03-28-000001.7", 
    "date": "2019-03-28T06:49:24.753863+02:00", 
    "resolution": "Вимога не відповідає предмету закупівлі", 
    "id": "b474c030d45442b8b2ff4d05bed0affe"
  }
}

