POST /api/2.5/tenders/deb082b3f3004fc1b115e78ee2d59f6c/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2724
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/b6094824640147479863eae365601773?KeyID=4f21d124&Signature=T3stmHpNnF96rQzUzztBf3wn%2FTJb6rda2HjqSHk%2BQmMpXSWG6yWbkl4uRFx7rBpp%2Fy208BsLAvjIDpYQEi5IAA%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "title": "Proposal_part2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/de0b7ddc6759418891568c6fb4d1fc2d?KeyID=4f21d124&Signature=JUt4TM2ETzgKFk1yxIyHRIGYBOx5d2J2XYaLs9CBJdcqLux%2BPPhdb2iF4FJnMYIGfZirfZ7wwwqAaQKpjkkFBA%3D%3D", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf"
      }
    ], 
    "eligibilityDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/90c9eb0afa30439fafbac3d2491d2b72?KeyID=4f21d124&Signature=oXIBT8KpSOZEkccpt5tSX%2BpNrLNMHmPf0gLM7klGC3K26gOvaF3k%2Bku6FDn%2FyadGKJChuUrZWohszGMqGFwiDA%3D%3D", 
        "title": "eligibility_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "value": {
      "contractDuration": {
        "days": 40, 
        "years": 13
      }, 
      "yearlyPaymentsPercentage": 0.86, 
      "annualCostsReduction": [
        200, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800
      ]
    }, 
    "financialDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/cc29a3e8bc9d4e7da97436455183abb8?KeyID=4f21d124&Signature=EZrsBWGgQjC2XhjkXJ1dzs8ryOzO%2FwGfn0XAOvdJHrIukXZIHNeTik9qc98gwWG0utVudunw1xXdbzHP709tBA%3D%3D", 
        "title": "financial_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко", 
          "email": "fake@mail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 35", 
          "locality": "м. Львів"
        }
      }
    ], 
    "qualificationDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/9c6185c907824b468a8071546baf113c?KeyID=4f21d124&Signature=SK79kx42DHwC9FUZiRo3BVkTSNgmZqJVmXgYi4smGGhMrn4k8f4FjX63102N97%2BlJ5v%2FncjVKUQ0YJAKHaa%2FCQ%3D%3D", 
        "title": "qualification_document.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/deb082b3f3004fc1b115e78ee2d59f6c/bids/f87c5f06e68b415cbe550efc7006d0ec
{
  "access": {
    "token": "72bda513384a4bafa69c3b8963885cbb"
  }, 
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/deb082b3f3004fc1b115e78ee2d59f6c/bids/f87c5f06e68b415cbe550efc7006d0ec/documents/62bdadaba08641de894a57057cb3bb01?download=b6094824640147479863eae365601773", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:49:14.295773+02:00", 
        "id": "62bdadaba08641de894a57057cb3bb01", 
        "dateModified": "2019-03-28T06:49:14.295786+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/deb082b3f3004fc1b115e78ee2d59f6c/bids/f87c5f06e68b415cbe550efc7006d0ec/documents/a87ee69ec00349a780a13ce2aebd9d22?download=de0b7ddc6759418891568c6fb4d1fc2d", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:49:14.296171+02:00", 
        "id": "a87ee69ec00349a780a13ce2aebd9d22", 
        "dateModified": "2019-03-28T06:49:14.296183+02:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/deb082b3f3004fc1b115e78ee2d59f6c/bids/f87c5f06e68b415cbe550efc7006d0ec/eligibility_documents/6f60909e91594bc6a1d30dfa397d172d?download=90c9eb0afa30439fafbac3d2491d2b72", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:49:14.296974+02:00", 
        "id": "6f60909e91594bc6a1d30dfa397d172d", 
        "dateModified": "2019-03-28T06:49:14.296986+02:00"
      }
    ], 
    "value": {
      "yearlyPaymentsPercentage": 0.86, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 8667.39, 
      "contractDuration": {
        "days": 40, 
        "years": 13
      }, 
      "amountPerformance": 582.27, 
      "annualCostsReduction": [
        200.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0
      ]
    }, 
    "id": "f87c5f06e68b415cbe550efc7006d0ec", 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/deb082b3f3004fc1b115e78ee2d59f6c/bids/f87c5f06e68b415cbe550efc7006d0ec/financial_documents/12c920dc0fed4da29d166a872491574f?download=cc29a3e8bc9d4e7da97436455183abb8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:49:14.296573+02:00", 
        "id": "12c920dc0fed4da29d166a872491574f", 
        "dateModified": "2019-03-28T06:49:14.296585+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 35", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-03-28T06:49:14.295400+02:00", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/deb082b3f3004fc1b115e78ee2d59f6c/bids/f87c5f06e68b415cbe550efc7006d0ec/qualification_documents/b199d29c7a3f4196be27eec6d55a6f2a?download=9c6185c907824b468a8071546baf113c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:49:14.297368+02:00", 
        "id": "b199d29c7a3f4196be27eec6d55a6f2a", 
        "dateModified": "2019-03-28T06:49:14.297380+02:00"
      }
    ]
  }
}

