POST /api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2787
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "documents": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a975591d95b244ecb9c7db6f69a3961a?KeyID=a8968c46&Signature=R9i7gaIqvShhQEMdpSIeFMDZOBTJluzLQsTJAW54FG6nS4fINBpegtJBzKWnBGzi%2Bk5IhkS3ktxe%2FSOlKD%2BMAw%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "format": "application/pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b8e4debb4ab1498abc828d0a9b207f33?KeyID=a8968c46&Signature=Ny%2B1HzOWls50rZYIW3Ne97%2Fd59lPfqMimbzHVf5cx1apzgwkCf7ilM9Q16gP6HBuNu0aokCgKfw3RRYF%2BAhPBw%3D%3D", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf"
      }
    ], 
    "eligibilityDocuments": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f44e75a41ab7403896620fbbe1eddaa4?KeyID=a8968c46&Signature=pxLjE8zJxzvE6jLrScnNYL3SIiXFRQtMZQeS93toHYVy6f%2FcNjKNo8daPhOOlSYjIJqqGT23kJuGDzMs2jrNAA%3D%3D", 
        "format": "application/pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "title": "eligibility_doc.pdf"
      }
    ], 
    "selfEligible": true, 
    "value": {
      "contractDuration": {
        "days": 40, 
        "years": 13
      }, 
      "yearlyPaymentsPercentage": 0.86, 
      "annualCostsReduction": [
        200, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800
      ]
    }, 
    "qualificationDocuments": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a3e3b53a27e2403d882f388314487153?KeyID=a8968c46&Signature=ODU%2BDmqovHAiHiVq%2FBOETGNGCWkMHvCUOmio45E3gsUOY8%2Fxv3i%2BOhvPUCB6gezbbgr268XFSQRLXpfDiZqEDg%3D%3D", 
        "format": "application/pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "title": "qualification_document.pdf"
      }
    ], 
    "financialDocuments": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c882c1ab5da648a2b02c85b18b16e1b5?KeyID=a8968c46&Signature=dfqXS3uY67AcBopGYOTnSuF4vYHzUN0vnWLs1xz67HOSlL7TVFRwr0s5vjIQhjbI4mWicPGreYJEeRX8OC%2B7Bw%3D%3D", 
        "format": "application/pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "title": "financial_doc.pdf"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "name": "Андрій Олексюк", 
          "telephone": "+380 (322) 91-69-30"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ], 
    "selfQualified": true
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167/bids/f6d07c2fcf8c49079a0deaf1fb4fa06e
{
  "access": {
    "token": "54159fb8235f466c94a158037371f492"
  }, 
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167/bids/f6d07c2fcf8c49079a0deaf1fb4fa06e/documents/8438cda5633c400992496a6d91c9f403?download=a975591d95b244ecb9c7db6f69a3961a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "8438cda5633c400992496a6d91c9f403", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167/bids/f6d07c2fcf8c49079a0deaf1fb4fa06e/documents/d77d8496af234829872b57cae731e786?download=b8e4debb4ab1498abc828d0a9b207f33", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "d77d8496af234829872b57cae731e786", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167/bids/f6d07c2fcf8c49079a0deaf1fb4fa06e/eligibility_documents/8eab4097d516420191a20ad12901b742?download=f44e75a41ab7403896620fbbe1eddaa4", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "8eab4097d516420191a20ad12901b742", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "f6d07c2fcf8c49079a0deaf1fb4fa06e", 
    "value": {
      "yearlyPaymentsPercentage": 0.86, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 8674.93, 
      "contractDuration": {
        "days": 40, 
        "years": 13
      }, 
      "amountPerformance": 583.21, 
      "annualCostsReduction": [
        200.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0
      ]
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167/bids/f6d07c2fcf8c49079a0deaf1fb4fa06e/financial_documents/0dd1d531b05242d8aeccf56dddaca2c5?download=c882c1ab5da648a2b02c85b18b16e1b5", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "0dd1d531b05242d8aeccf56dddaca2c5", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-04-01T01:00:00+03:00", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167/bids/f6d07c2fcf8c49079a0deaf1fb4fa06e/qualification_documents/db90c4f74217464fb24b57e6637d9d0a?download=a3e3b53a27e2403d882f388314487153", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "db90c4f74217464fb24b57e6637d9d0a", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ]
  }
}

