POST /api/2.5/tenders/19e26a9aabb84578920993b1d57f719d/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2785
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "documents": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/14e5ee2de1114d0583cec29d67a53142?KeyID=a8968c46&Signature=XHmnq2PYBBzXokoTqEDjhVJz1mq9aiiQRG4UzOz%2Bs%2FnQBxo6T7ZCCQvPoo5xqFJaEAY7DXusqq9W9%2FEpUvxkCA%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "format": "application/pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a7e4111429bd43479a394ba49c69bc99?KeyID=a8968c46&Signature=IQYe9ooudAILFybSsYP6ttkArPV80SiqUAaNGWTqXd1B1CexbNUZ9yikXEPl6EwpMXp5eq2ejs8EKBKF04pLCQ%3D%3D", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf"
      }
    ], 
    "eligibilityDocuments": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1e3a3a4687d6489ba5de829c5383429d?KeyID=a8968c46&Signature=hdb7ctkXwo%2FKDDUibmGqaLJ%2BDLxjsc%2FgQQRr9ciLsHLyvqQC44wTy7dkU3UflkS7kQbyJy6UVLewy3aF%2ByabBw%3D%3D", 
        "format": "application/pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "title": "eligibility_doc.pdf"
      }
    ], 
    "selfEligible": true, 
    "value": {
      "contractDuration": {
        "days": 40, 
        "years": 13
      }, 
      "yearlyPaymentsPercentage": 0.86, 
      "annualCostsReduction": [
        200, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800, 
        800
      ]
    }, 
    "qualificationDocuments": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/409ca1f7dbdc4ed1b299b294d10e10d7?KeyID=a8968c46&Signature=%2FQz6gJTMk7M8Sj0IP7ItbQlVHcLoU%2BnHucvsOI659His%2BkJ2SDSKj1%2FEBvUvo%2FjgfHd0eAEPysEjDhzd1ZyuBg%3D%3D", 
        "format": "application/pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "title": "qualification_document.pdf"
      }
    ], 
    "financialDocuments": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f27fb01d658340b0b9de5186a6df006b?KeyID=a8968c46&Signature=QZIKyhYWjBoIPkWOu%2Fwe4%2BMJ%2Fn75ovLz0QB9FdOvT3Dr4tH96BJ48tnr%2FrP%2BnVIu5B1Scw%2BFNUVbR7jz4dI%2BDQ%3D%3D", 
        "format": "application/pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "title": "financial_doc.pdf"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "name": "Андрій Олексюк", 
          "telephone": "+380 (322) 91-69-30"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ], 
    "selfQualified": true
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/19e26a9aabb84578920993b1d57f719d/bids/593a75ac634f4b54bf6b95f5d8621788
{
  "access": {
    "token": "155c1100fec449448cd0ffce7fc2cd40"
  }, 
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/19e26a9aabb84578920993b1d57f719d/bids/593a75ac634f4b54bf6b95f5d8621788/documents/c3f4a58df54d4d788ed902f21e6b5dc0?download=14e5ee2de1114d0583cec29d67a53142", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "c3f4a58df54d4d788ed902f21e6b5dc0", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/19e26a9aabb84578920993b1d57f719d/bids/593a75ac634f4b54bf6b95f5d8621788/documents/ecd87f46a9934cffacea3eea354d8dad?download=a7e4111429bd43479a394ba49c69bc99", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "ecd87f46a9934cffacea3eea354d8dad", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/19e26a9aabb84578920993b1d57f719d/bids/593a75ac634f4b54bf6b95f5d8621788/eligibility_documents/0ca7e5b4ed964968b5ef886e0e284184?download=1e3a3a4687d6489ba5de829c5383429d", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "0ca7e5b4ed964968b5ef886e0e284184", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "selfEligible": true, 
    "id": "593a75ac634f4b54bf6b95f5d8621788", 
    "value": {
      "yearlyPaymentsPercentage": 0.86, 
      "valueAddedTaxIncluded": true, 
      "currency": "UAH", 
      "amount": 8505.28, 
      "contractDuration": {
        "days": 40, 
        "years": 13
      }, 
      "amountPerformance": 562.72, 
      "annualCostsReduction": [
        200.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0, 
        800.0
      ]
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/19e26a9aabb84578920993b1d57f719d/bids/593a75ac634f4b54bf6b95f5d8621788/financial_documents/0be4e45cf1eb48f9b2d6bb473bd25a8b?download=f27fb01d658340b0b9de5186a6df006b", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "0be4e45cf1eb48f9b2d6bb473bd25a8b", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-01-01T00:00:00+02:00", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/19e26a9aabb84578920993b1d57f719d/bids/593a75ac634f4b54bf6b95f5d8621788/qualification_documents/97b32c923e7d4c92b2561538056a9a5d?download=409ca1f7dbdc4ed1b299b294d10e10d7", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "97b32c923e7d4c92b2561538056a9a5d", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ]
  }
}

