PATCH /api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167/qualifications/1b18b0860f6e4b88a6d952bd768a84b2?acc_token=621ec741ce984bc194cb9cd44865825f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "eligible": false, 
    "qualified": false, 
    "bidID": "f6d07c2fcf8c49079a0deaf1fb4fa06e", 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "1b18b0860f6e4b88a6d952bd768a84b2"
  }
}

