PATCH /api/2.5/tenders/deb082b3f3004fc1b115e78ee2d59f6c/qualifications/9c7ef42bbec44ec7bf8b0b2cf1e5cbbd?acc_token=88277d181c4c406caa00d3386e096304 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "eligible": false, 
    "qualified": false, 
    "bidID": "f87c5f06e68b415cbe550efc7006d0ec", 
    "date": "2019-03-28T06:49:15.265191+02:00", 
    "id": "9c7ef42bbec44ec7bf8b0b2cf1e5cbbd"
  }
}

