GET /api/2.4/tenders/6c51b2b430784297b2ce60215c18535f/bids/ecb40352ec6344d692c488fd4fec4739?acc_token=d5ed31fb489d4729a424b512f9b723f0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/594a5c29a9194c3eb372a68cd8327a7d?KeyID=8a9737e9&Signature=UeHeWOILSuOp0HhtTBf88aWFPIhGMgc7QHOkbFDT7Rp%2F33dOnIyztgUuCxm4C5%2F7xRjK0cH6wPq7i1qLjY%2FRBQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:47:13.867451+03:00", 
        "id": "4c78b409733c4c9892343bba6555e5ec", 
        "dateModified": "2018-09-21T05:47:13.867536+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/6c51b2b430784297b2ce60215c18535f/bids/ecb40352ec6344d692c488fd4fec4739/documents/ff20b1915938457a8669b9871db304c3?download=fe08d949e4e149c4b9d12a0aec2e6f2c", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:47:13.868621+03:00", 
        "id": "ff20b1915938457a8669b9871db304c3", 
        "dateModified": "2018-09-21T05:47:13.868656+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 35", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "id": "ecb40352ec6344d692c488fd4fec4739", 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/30e62e40ec064c939dc4ece6bad7a3ed?KeyID=8a9737e9&Signature=nFAzPVoWWF7oy%252Bszy4gS%252Bqzc3T8qImKUd8bn5jkJPlnHUik0BiuIf4s4tn1wRR5CcLzQIlWQ%252BxXd04hX%2F1qmAA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:47:13.870646+03:00", 
        "id": "9d9202ecee5f49f5acb8ae5416112beb", 
        "dateModified": "2018-09-21T05:47:13.870682+03:00"
      }
    ]
  }
}

