GET /api/2.5/tenders/deb082b3f3004fc1b115e78ee2d59f6c/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/41a9f4aaabfd4982a4b65e3460c5eb71?KeyID=4f21d124&Signature=x83QYMS%252B1ooVOqFMY%2Fumrcb7gB4RzMMnvHi0IvjAbskqokTdrZniMLyxMHkjoUSAkGESsLNkT2k3USVfvNE1Bw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-03-28T06:49:12.264549+02:00", 
      "id": "04e5e88d493545619c86d79a0a818f30", 
      "dateModified": "2019-03-28T06:49:12.264597+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/18fc17d10d314f1389535f6daeaa9417?KeyID=4f21d124&Signature=fZ2I8KXsEGLP6y%2FLFv4Y2LFLIHGlhi3nm3SFwo%2FI%2Fe5v06grriLpW0T2oCT5ny3POBCnIG%2FMAhOYwWfqEqr5BA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-03-28T06:49:12.309112+02:00", 
      "id": "eb29307d552448f1b6821f6e0ead091f", 
      "dateModified": "2019-03-28T06:49:12.359674+02:00"
    }
  ]
}

