GET /api/2.4/tenders/6c51b2b430784297b2ce60215c18535f/contracts/982f86631e124d7688fdfd50f3cdcff4/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "language": "uk", 
      "title": "contract_first_document.doc", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/008339c7f2c541368c88a2313a98c30f?KeyID=8a9737e9&Signature=LSxF3AYeM9thodDzx%2FTzUjhenTBBsd7PqGO%2FRDR9gSKeU9X6M6N2Kn0hsR9gFRpDMdgqDgMh9Jl9zw2sCGXWBg%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2018-09-21T05:47:22.374294+03:00", 
      "id": "f3a4de9d06304e56b1d482f541a09583", 
      "dateModified": "2018-09-21T05:47:22.374349+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "language": "en", 
      "title": "contract_second_document.doc", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/ef23252ccdaa4cae80df382c1b2db167?KeyID=8a9737e9&Signature=kQ9UtJG4MnPkwU37MFBa97sflmSlqV8ul%252BPbsf4f9fjtflHMwYY8ZFRsAy%2FK%252BPGRdVXhkMKSj1vwH9DWlBJYCA%253D%253D", 
      "format": "application/msword", 
      "title_en": "Title of Document", 
      "description_en": "Description of Document", 
      "datePublished": "2018-09-21T05:47:23.012475+03:00", 
      "documentOf": "tender", 
      "id": "ca9beb033d3b4c0c9d5ba517601abb9e", 
      "dateModified": "2018-09-21T05:47:23.012569+03:00"
    }
  ]
}

