GET /api/2.5/tenders/19e26a9aabb84578920993b1d57f719d/contracts/56f576b75b9c405081622d75cad21bf2/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "language": "uk", 
      "title": "contract_first_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3e27b252b1d14f239a66791d4a137b11?KeyID=a8968c46&Signature=tjVAkjmWPdT%2FlaHMH8Ty6cOg6VbZ2QLMzDoyHJOnyx%2FnNCTNFhHj0rz25WaP4LrXgMDJr%252BJY794DL3iNQNpGBA%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:10:00+03:00", 
      "id": "b2d82eac34844a13aee8e4c22ed13bbe", 
      "dateModified": "2019-04-01T01:10:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "language": "en", 
      "title": "contract_second_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5ca15840e1a54cb6a55d79605f1c7801?KeyID=a8968c46&Signature=CR1HU4lAJwSiew3xUCU8gYNG1pS6x5ih3FmvajdYmfgb3ydTrtpelloPEoSdXAS5qAKgXrE1rITmX9pOFCScBg%253D%253D", 
      "format": "application/msword", 
      "title_en": "Title of Document", 
      "description_en": "Description of Document", 
      "datePublished": "2019-04-01T01:10:00+03:00", 
      "documentOf": "tender", 
      "id": "ba109df16d9a4c3c984a7e5dbec5c5d7", 
      "dateModified": "2019-04-01T01:10:00+03:00"
    }
  ]
}

