GET /api/2.5/tenders/b92b4800a6a44cf2b362dba94c21c167/contracts/432e1c66688d48b38db0326ce5ff9610/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "language": "uk", 
      "title": "contract_first_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1a62cc25ecfa40f9b098a5fc5f49ac2c?KeyID=a8968c46&Signature=QlJhD1QSH1xm3gwwFuO3UAcX%2F9a3OwP%2FnOFaoKc32eFqR%252BNIw27jd4n3D6y%2Frm4IpxWY%2FOyz84e2UfS68QsaAw%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:10:00+03:00", 
      "id": "9d9b3bbda9f0485bbc826e481960c627", 
      "dateModified": "2019-04-01T01:10:00+03:00"
    }
  ]
}

