GET /api/2.5/tenders/87314e175bd440d98b59c1ddc4ea4428?acc_token=5b1e9d0b338449568122e0f4bf11fba9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "cancelled", 
    "awardPeriod": {
      "startDate": "2019-03-18T16:13:09.319450+02:00", 
      "endDate": "2019-03-18T16:13:10.592911+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2019-02-05T16:12:04.623186+02:00", 
      "endDate": "2019-03-04T00:00:00+02:00"
    }, 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/87314e175bd440d98b59c1ddc4ea4428", 
    "enquiryPeriod": {
      "startDate": "2019-02-05T16:12:04.623186+02:00", 
      "clarificationsUntil": "2019-03-01T16:12:04.623186+02:00", 
      "endDate": "2019-02-26T16:12:04.623186+02:00", 
      "invalidationDate": "2019-03-18T16:12:53.351748+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "title_en": "Services in school canteens", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "00137226", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Калорійність", 
        "date": "2019-03-18T16:12:48.801251+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "dateAnswered": "2019-03-18T16:12:49.001188+02:00", 
        "id": "56fdf791d567471e898406190ce7ad43", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "qualifications": [
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "3bf8562836aa4e32954f94f92bd01b9f", 
        "date": "2019-03-18T16:12:57.137666+02:00", 
        "id": "22143d3622bd484781ae3894a82f127f"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "e5507fd565d94b65bcb744fcfee811a6", 
        "date": "2019-03-18T16:12:57.676182+02:00", 
        "id": "2fcc0259f35847999360b3c83f321183"
      }, 
      {
        "status": "unsuccessful", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "8926a8f36b484d9ea59418370195cc39", 
        "date": "2019-03-18T16:12:58.212997+02:00", 
        "id": "ebd284c22640420492eee72bec56351e"
      }
    ], 
    "id": "87314e175bd440d98b59c1ddc4ea4428", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/2a8700a2150d47909ecdbfa47221b62a?KeyID=2f5e2da4&Signature=pD7%252Bxg0p7egh9UXtUKLqTXTAeJ64H7DO8nkrdJ3SUDD9Ta7LpJC6%2FudyxiZASaVLg7hmPY583NEtkLlRsnMJBA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:12:48.122662+02:00", 
        "id": "8c8bba7eedf644daba55d02c7ff671e5", 
        "dateModified": "2019-03-18T16:12:48.122688+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/75e44437cc5846c68b82f81a07aab423?KeyID=2f5e2da4&Signature=NK4Zzh1xoRRZT48fnnpAiPCitSBceNTkqFqnrR4HeGXYV6vlZv12UEMG9GtBjL0MzpJngvMn4wMsxXuhOygVCg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:12:48.376065+02:00", 
        "id": "4e166055bf0f4cfab614daf6142fc7b2", 
        "dateModified": "2019-03-18T16:12:48.376090+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/ab74c18026d346d5a727c29e2cd77a65?KeyID=2f5e2da4&Signature=TFicFXIZUTLTW7jklf9o55xEmmTtIPDyJZ0iX4br%252B2SlrgE1IQEHWhKC75pF4NWI%252B5EAAcijhIE6nfegyf1nBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:12:48.376065+02:00", 
        "id": "4e166055bf0f4cfab614daf6142fc7b2", 
        "dateModified": "2019-03-18T16:12:48.568376+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2019-03-08T16:12:04.623186+02:00", 
      "endDate": "2019-03-18T16:12:04.623186+02:00"
    }, 
    "tenderID": "UA-2019-03-18-000001", 
    "minimalStepPercentage": 0.006, 
    "auctionPeriod": {
      "startDate": "2019-03-18T16:12:04.623186+02:00", 
      "endDate": "2019-03-18T16:13:09.177959+02:00"
    }, 
    "dateModified": "2019-03-18T16:13:27.462414+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2019-02-05T16:12:04.623186+02:00", 
      "endDate": "2019-03-08T16:12:04.623186+02:00"
    }, 
    "contracts": [
      {
        "status": "pending", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "language": "uk", 
            "title": "contract_first_document.doc", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/1164100410394674863d27944abc25c2?KeyID=2f5e2da4&Signature=XTYZr424WbAL44TozQzwi7tJ%2F23voBZJIMYfG10d6OhTWWL6en9LFUS8Srm6G6wWsKPbqwUkgoGK3iYY3poYAQ%253D%253D", 
            "format": "application/msword", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T16:13:14.730500+02:00", 
            "id": "a5e101aafcb442fa8de4a06d9d0a86c0", 
            "dateModified": "2019-03-18T16:13:14.730851+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "language": "en", 
            "title": "contract_second_document.doc", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/cae9e3b9af15415b9d4987f1272286f7?KeyID=2f5e2da4&Signature=6bkxDfGNFG7Q9tDPkscOG8kaIVjnf2FwH8IlBsP1odgLNDGhicGwfTofEKxAGiw%2FLHtbv01aE6LYwQ7uuCoOCw%253D%253D", 
            "format": "application/msword", 
            "title_en": "Title of Document", 
            "description_en": "Description of Document", 
            "datePublished": "2019-03-18T16:13:15.692744+02:00", 
            "documentOf": "tender", 
            "id": "7768bf98f19944dc834959a541c97c2e", 
            "dateModified": "2019-03-18T16:13:15.692791+02:00"
          }
        ], 
        "items": [
          {
            "description": "Послуги шкільних їдалень", 
            "classification": {
              "scheme": "ДК021", 
              "description": "Test", 
              "id": "37810000-9"
            }, 
            "description_en": "Services in school canteens", 
            "additionalClassifications": [
              {
                "scheme": "ДКПП", 
                "id": "17.21.1", 
                "description": "Послуги шкільних їдалень"
              }
            ], 
            "deliveryAddress": {
              "postalCode": "79000", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "id": "77b359d32cbf49b9bfb437ac379244fd", 
            "unit": {
              "code": "44617100-9", 
              "name": "item"
            }
          }, 
          {
            "description": "Послуги шкільних їдалень", 
            "classification": {
              "scheme": "ДК021", 
              "description": "Test", 
              "id": "37810000-9"
            }, 
            "description_en": "Services in school canteens", 
            "additionalClassifications": [
              {
                "scheme": "ДКПП", 
                "id": "17.21.1", 
                "description": "Послуги шкільних їдалень"
              }
            ], 
            "deliveryAddress": {
              "postalCode": "79000", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "id": "6615aa193cd045188a830eaf79869c54", 
            "unit": {
              "code": "44617100-9", 
              "name": "item"
            }
          }
        ], 
        "suppliers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "contractNumber": "contract#1", 
        "period": {
          "startDate": "2019-03-18T16:13:13.444668+02:00", 
          "endDate": "2020-03-17T16:13:13.444834+02:00"
        }, 
        "dateSigned": "2019-03-18T16:13:12.538553+02:00", 
        "value": {
          "yearlyPaymentsPercentage": 0.9, 
          "valueAddedTaxIncluded": true, 
          "currency": "UAH", 
          "amount": 8922.33, 
          "contractDuration": {
            "days": 74, 
            "years": 10
          }, 
          "amountPerformance": 816.72, 
          "annualCostsReduction": [
            500.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0
          ]
        }, 
        "date": "2019-03-18T16:13:10.591118+02:00", 
        "awardID": "23adc3e9c47348da8c43d50a7337f120", 
        "id": "13bbfc24e144445390ebf3624aa7444b", 
        "contractID": "UA-2019-03-18-000001-1"
      }
    ], 
    "NBUdiscountRate": 0.22986, 
    "yearlyPaymentsPercentageRange": 0.8, 
    "procurementMethodType": "esco", 
    "awards": [
      {
        "status": "active", 
        "eligible": true, 
        "suppliers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "complaintPeriod": {
          "startDate": "2019-03-18T16:13:09.381996+02:00", 
          "endDate": "2019-03-18T16:13:09.381996+02:00"
        }, 
        "bid_id": "3bf8562836aa4e32954f94f92bd01b9f", 
        "value": {
          "yearlyPaymentsPercentage": 0.9, 
          "valueAddedTaxIncluded": true, 
          "currency": "UAH", 
          "amount": 8922.33, 
          "contractDuration": {
            "days": 74, 
            "years": 10
          }, 
          "amountPerformance": 816.72, 
          "annualCostsReduction": [
            500.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0
          ]
        }, 
        "qualified": true, 
        "date": "2019-03-18T16:13:10.709472+02:00", 
        "id": "23adc3e9c47348da8c43d50a7337f120"
      }
    ], 
    "date": "2019-03-18T16:13:27.462414+02:00", 
    "minValue": {
      "currency": "UAH", 
      "amount": 0.0, 
      "valueAddedTaxIncluded": true
    }, 
    "fundingKind": "other", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "77b359d32cbf49b9bfb437ac379244fd", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "6615aa193cd045188a830eaf79869c54", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/e4b3d7a500dd4411bc3729e5663ba624?KeyID=2f5e2da4&Signature=J5ytyP4ROEMjzb4t6KsaNH3BWWPNKPcg4bAU%2FbjHjxKcBB4K%252BU6MIRdO36Y5QwQw%2FWIS7%2FiLzaKcq1kbpwOLAw%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T16:12:50.649370+02:00", 
            "id": "f696dfe573234621b10603182271256d", 
            "dateModified": "2019-03-18T16:12:50.649391+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/87314e175bd440d98b59c1ddc4ea4428/bids/3bf8562836aa4e32954f94f92bd01b9f/documents/2ea0b0993e0e4ba99aedf1c4135bcc1d?download=21a892b368b247108d2d2288950e3109", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_top_secrets.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T16:12:50.919580+02:00", 
            "id": "2ea0b0993e0e4ba99aedf1c4135bcc1d", 
            "dateModified": "2019-03-18T16:12:50.919606+02:00"
          }
        ], 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/6a81f62b0f5f48368ec33dba59c6e298?KeyID=2f5e2da4&Signature=S1oKZoWc3N0lTcseUKb4Fj5QA93iY57%2FbVEQGd9F7ITIs5R3e6JE4eyqS8lhJtrCZfwf6H8Lihhg2ja9wjcfAw%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T16:12:52.214854+02:00", 
            "id": "745dbd9c112c4707ad849e9c516e6e9f", 
            "dateModified": "2019-03-18T16:12:52.214875+02:00"
          }
        ], 
        "id": "3bf8562836aa4e32954f94f92bd01b9f", 
        "value": {
          "yearlyPaymentsPercentage": 0.9, 
          "valueAddedTaxIncluded": true, 
          "currency": "UAH", 
          "amount": 8922.33, 
          "contractDuration": {
            "days": 74, 
            "years": 10
          }, 
          "amountPerformance": 816.72, 
          "annualCostsReduction": [
            500.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0
          ]
        }, 
        "subcontractingDetails": "ДКП «Орфей», Україна", 
        "financialDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "financial_doc.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/15c4fcf346f54aca9dd049ffbbb0bd63?KeyID=2f5e2da4&Signature=ipmsfivtydf00DjZ1DOdRWQJkgzeJQ6uxQGCGQmGUdZY34D67MU9cYakbh2u7v5xcVzOiHRRlp3QzZGgMjqTAg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T16:12:51.464912+02:00", 
            "id": "dc017ab22ba444ed809b76e862218832", 
            "dateModified": "2019-03-18T16:12:51.464936+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "financial_doc2.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/53d20bf32b3f41e6ae92565a53eb34b3?KeyID=2f5e2da4&Signature=GQbsV70yAiVF8rAYlic0bypPQasZS6Vu97DTKJh6KQDwUdlSoR5QdKsBiuyVK6ktResmiIyUf6zsjLEcJsTYCg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T16:12:51.739831+02:00", 
            "id": "8807a6bdf4d04fd1912f8f941e060e46", 
            "dateModified": "2019-03-18T16:12:51.740139+02:00"
          }
        ], 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "date": "2019-03-18T16:12:50.053330+02:00", 
        "qualificationDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "qualification_document.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/4c1592e08c76400a89b6130ca0e7b068?KeyID=2f5e2da4&Signature=DXHQf91Em32NeDw3rn1vfFsqGo8i9s3MYpEvryCWqJK1hPKEiTaCUuwbWv%252BnjpMLfj2%252BMIPFs6mOXMzRw1gwBg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T16:12:52.530966+02:00", 
            "id": "6f5c051786f14927aa95f329c8d12ea1", 
            "dateModified": "2019-03-18T16:12:52.530989+02:00"
          }
        ], 
        "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/87314e175bd440d98b59c1ddc4ea4428?key_for_bid=3bf8562836aa4e32954f94f92bd01b9f"
      }, 
      {
        "status": "active", 
        "value": {
          "yearlyPaymentsPercentage": 0.85, 
          "valueAddedTaxIncluded": true, 
          "currency": "UAH", 
          "amount": 9335.56, 
          "contractDuration": {
            "days": 200, 
            "years": 12
          }, 
          "amountPerformance": 734.21, 
          "annualCostsReduction": [
            400.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0, 
            900.0
          ]
        }, 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "date": "2019-03-18T16:12:54.336616+02:00", 
        "id": "e5507fd565d94b65bcb744fcfee811a6", 
        "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/87314e175bd440d98b59c1ddc4ea4428?key_for_bid=e5507fd565d94b65bcb744fcfee811a6"
      }, 
      {
        "status": "unsuccessful", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal_part1.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/082337ec30c94fefbd1ab163e6a21f76?KeyID=2f5e2da4&Signature=QTrieK3fUzmcJBU78IKlsIcOa0du2U1qscb2G0hYUxAK7VPy1Q4WWhpjenFzg8F018EzQJPsjmhUxtxuL7HaCw%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T16:12:54.895020+02:00", 
            "id": "95652e5d4ac04e17ab1b987d179a556b", 
            "dateModified": "2019-03-18T16:12:54.895191+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/87314e175bd440d98b59c1ddc4ea4428/bids/8926a8f36b484d9ea59418370195cc39/documents/334f4f8af4a548e0b05cd5eff6b0960e?download=20ae2fea5c114ffb8c353fb8e81a536a", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_part2.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T16:12:54.901470+02:00", 
            "id": "334f4f8af4a548e0b05cd5eff6b0960e", 
            "dateModified": "2019-03-18T16:12:54.901607+02:00"
          }
        ], 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "id": "8926a8f36b484d9ea59418370195cc39", 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/257d39fe1d914c97b8e5a23365819edc?KeyID=2f5e2da4&Signature=fMoaI0mzjYv5OCs7X3ZZh%252BQKzYwUGBOKNav%2FXH76NJ%252BZhYU1FZpV6%2FPf9I3adJmOofJp%2F6DCto3eQng1QTQhCQ%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T16:12:54.903903+02:00", 
            "id": "3e1b11076ba54dd99e0d7908dd7c77b6", 
            "dateModified": "2019-03-18T16:12:54.903924+02:00"
          }
        ]
      }
    ], 
    "cancellations": [
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "description": "Changed description", 
            "language": "uk", 
            "title": "Notice.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/30cf58ecb40045a8978a8572b4e2fa8e?KeyID=2f5e2da4&Signature=u1SB39IjAFrHZlllB50CvS2PVC5bDSFgfK9mKaedRZxb9gHVp2u6Q4WZOiwRQicFxkSjUlIX6vaoshkTdnONAA%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T16:13:23.463241+02:00", 
            "id": "9cbbd9a5f3eb4266b7ecfbb3044e8b97", 
            "dateModified": "2019-03-18T16:13:23.463295+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "description": "Changed description", 
            "language": "uk", 
            "title": "Notice-2.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/d2494e0e7bc9406e9a82f68aca7390dd?KeyID=2f5e2da4&Signature=7V5joGwlZXJIOTdSj9XGIq%252BJex9Ns%252BtekXGBK3qQ%252BbNOWxJYjdr9XsZAOqJO3DMjU%2FwMY5wjmZ896HQ1N2SWAg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T16:13:23.463241+02:00", 
            "id": "9cbbd9a5f3eb4266b7ecfbb3044e8b97", 
            "dateModified": "2019-03-18T16:13:26.294176+02:00"
          }
        ], 
        "reason": "cancellation reason", 
        "reasonType": "unsuccessful", 
        "date": "2019-03-18T16:13:27.462414+02:00", 
        "cancellationOf": "tender", 
        "id": "d6c3159edcf3480796311d08371d288d"
      }
    ], 
    "noticePublicationDate": "2019-03-18T16:12:47.352342+02:00", 
    "awardCriteria": "ratedCriteria"
  }
}

