PUT /api/2.5/tenders/19e26a9aabb84578920993b1d57f719d/documents/8e771b56e1604a3d9706c5683cebfc35?acc_token=dee9fca567cd400c87a7c52c22c6eaec HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 146
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="AwardCriteria-2.pdf"
Content-Type: application/pdf

content2
--BOUNDARY--


Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dc759cc1cb42472b9781fd2871cdc9b6?KeyID=a8968c46&Signature=0TDO6lhLUXJoeOPbsH2Qkj9y9xUhCSzQXydvRtUMcii4x934VpFBmBBr9L1Z43X9n6w8ANY96GnNvgO5tvCLAw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "8e771b56e1604a3d9706c5683cebfc35", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

