GET /api/2.5/tenders/19e26a9aabb84578920993b1d57f719d?acc_token=dee9fca567cd400c87a7c52c22c6eaec HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2019-03-04T01:00:00+03:00", 
      "endDate": "2019-03-30T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-03-04T01:00:00+03:00", 
      "clarificationsUntil": "2019-03-28T00:00:00+03:00", 
      "endDate": "2019-03-24T01:00:00+03:00", 
      "invalidationDate": "2019-04-01T01:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-04-03T01:00:00+03:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-04-01T01:00:00+03:00", 
        "title": "Калорійність", 
        "date": "2019-04-01T01:00:00+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "44e542af00a84d56ad4c48f17c3a7886", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "19e26a9aabb84578920993b1d57f719d", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9c428b4b4ceb465683a95c4874a206e6?KeyID=a8968c46&Signature=QnqBHhGNbw8KxzsxouZUhkhDUWxc0NcrAMKuQtGGDrkBxBTI9DgALdHMEfkRQhK97ABJWweh%2F5T%2FwhuEu9VfCA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "0ee0b808d2214d50bf26d3526b121ac8", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0830d4843f9540aa9f713f66f3ad9467?KeyID=a8968c46&Signature=74bFgIkFLbdn29k33CxXfqr5%252B1%252BIZ8mlVzys7GNtKqUmYXYz7hlwLTgnNoLEQhCwc91NSUKP2a4oUf0BkZm0DA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "8e771b56e1604a3d9706c5683cebfc35", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/dc759cc1cb42472b9781fd2871cdc9b6?KeyID=a8968c46&Signature=0TDO6lhLUXJoeOPbsH2Qkj9y9xUhCSzQXydvRtUMcii4x934VpFBmBBr9L1Z43X9n6w8ANY96GnNvgO5tvCLAw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "8e771b56e1604a3d9706c5683cebfc35", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "tenderID": "UA-2019-04-01-000001", 
    "minimalStepPercentage": 0.006, 
    "yearlyPaymentsPercentageRange": 0.8, 
    "dateModified": "2019-04-01T01:00:00+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2019-03-04T01:00:00+03:00", 
      "endDate": "2019-04-03T01:00:00+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-05-09T00:00:00+03:00"
    }, 
    "procurementMethodType": "esco", 
    "date": "2019-04-01T01:00:00+03:00", 
    "NBUdiscountRate": 0.22986, 
    "minValue": {
      "currency": "UAH", 
      "amount": 0.0, 
      "valueAddedTaxIncluded": true
    }, 
    "fundingKind": "other", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "c8ddcb8c6d6f42ca9aa3b608d01f1494", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "874a5db4734d4df39097f4426dcd637f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }
      }
    ], 
    "noticePublicationDate": "2019-04-01T01:00:00+03:00", 
    "awardCriteria": "ratedCriteria"
  }
}

PATCH /api/2.5/tenders/19e26a9aabb84578920993b1d57f719d?acc_token=dee9fca567cd400c87a7c52c22c6eaec HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 41
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "minValue": {
      "amount": 501.0
    }
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "tenderPeriod should be extended by 7 days", 
      "location": "body", 
      "name": "data"
    }
  ]
}

