PATCH /api/2.5/tenders/19e26a9aabb84578920993b1d57f719d/cancellations/f354e6e7bdd54b5ca26f4b29f456b9fc?acc_token=dee9fca567cd400c87a7c52c22c6eaec HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-04-01T01:10:00+03:00", 
    "cancellationOf": "tender", 
    "id": "f354e6e7bdd54b5ca26f4b29f456b9fc"
  }
}

