GET /api/2.5/tenders/0cd37a4798fe40d1b45324a394f61c9f HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "limited", 
    "status": "active", 
    "causeDescription": "оригінальний тендер не вдався двічі", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "value": {
          "currency": "UAH", 
          "amount": 500000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "28f98cde22964c8ea8bbc1fda693580e"
      }
    ], 
    "items": [
      {
        "relatedLot": "28f98cde22964c8ea8bbc1fda693580e", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-21T00:00:00+02:00", 
          "endDate": "2019-05-21T00:00:00+02:00"
        }, 
        "id": "a7fc62340ce04601af5b3ab66b3cf6a7", 
        "quantity": 1.0
      }
    ], 
    "procurementMethodType": "negotiation.quick", 
    "value": {
      "currency": "UAH", 
      "amount": 500000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateModified": "2019-04-01T01:00:00+03:00", 
    "causeDescription_ru": "оригинальный тендер не получился дважды", 
    "date": "2019-04-01T01:00:00+03:00", 
    "causeDescription_en": "original tender has failed twice", 
    "description_ru": "Услуги школьных столовых", 
    "description_en": "Services in school canteens", 
    "title_ru": "Услуги школьных столовых", 
    "owner": "broker", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "kind": "special", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title_en": "Services in school canteens", 
    "id": "0cd37a4798fe40d1b45324a394f61c9f", 
    "tenderID": "UA-2019-04-01-000001"
  }
}

