POST /api/2.5/agreements/812a4fd5803c47b19b57627d99c10f7f/documents?acc_token=c9e67b4fcc7b4af5b8821e6411afb46f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 202
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy0711739975214$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/agreements/812a4fd5803c47b19b57627d99c10f7f/documents/2bca23ff740f4b9f9a8ba2c1eb8b5527
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "agreement_changes.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/d300b6b565294cb59892cfb5c45ad1d0?KeyID=c1a97147&Signature=Ov9EwEEyJHb4P%252BIDwcdagWkptITZIXTEy37GFFV7VB1a4kP%252BaQqyAv9scXh6RGgtzsF1Mb%252BltnahifZrrZDJDA%253D%253D", 
    "format": "application/msword", 
    "documentOf": "agreement", 
    "datePublished": "2019-03-18T09:26:18.771929+02:00", 
    "id": "2bca23ff740f4b9f9a8ba2c1eb8b5527", 
    "dateModified": "2019-03-18T09:26:18.771947+02:00"
  }
}

