POST /api/2.5/agreements/83456a89ad0143b5b9dde8ca7ac28456/documents?acc_token=7b93503ebb914e35ac86ce4cf565018f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 200
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy766004184161$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/agreements/83456a89ad0143b5b9dde8ca7ac28456/documents/5ceee6c63deb4c589565d79c218a47d2
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "agreement_changes.doc", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4c2559fa65ed4e2f8ca862087917cccb?KeyID=a8968c46&Signature=%252By7xaIB10V4BINMfDUBiJehtssjiAYEqAryH84Nq5nwnFJ6SQq6NL55yYaajSxJgTdBhhXVQI6%2FGYeR0NXoIDA%253D%253D", 
    "format": "application/msword", 
    "documentOf": "agreement", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "5ceee6c63deb4c589565d79c218a47d2", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

