POST /api/2.5/agreements/9a49a7db3ada48519aa5b2c9a4ec5d30/changes?acc_token=76b0c07026994e7089d5f9716acfc3e7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 244
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "rationaleType": "taxRate", 
    "rationale_en": "Agreement change cause", 
    "rationale": "Опис причини змін егріменту"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "rationaleType": "taxRate", 
    "rationale_en": "Agreement change cause", 
    "rationale": "Опис причини змін егріменту", 
    "date": "2019-10-01T01:00:00+03:00", 
    "id": "563cc544379744ed9b023a88ff6e415b"
  }
}

