PATCH /api/2.5/agreements/83456a89ad0143b5b9dde8ca7ac28456/changes/0662e627533a4d1b98e1b3bbf5b704e1?acc_token=7b93503ebb914e35ac86ce4cf565018f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 95
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "modifications": [
      {
        "itemId": "22fe9211ced0491ebc00beedf36fcedd", 
        "factor": 0.1605
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "modifications": [
      {
        "itemId": "22fe9211ced0491ebc00beedf36fcedd", 
        "factor": 0.1605
      }
    ], 
    "rationaleType": "taxRate", 
    "rationale_en": "Agreement change cause", 
    "rationale": "Друга і третя поставка має бути розфасована", 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "0662e627533a4d1b98e1b3bbf5b704e1"
  }
}

