PATCH /api/2.5/agreements/01d3f2813ee344a2adffb8d4b7f11a75/credentials?acc_token=31846f9fd11b43ff9740caab41bcfa74 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 0
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "access": {
    "token": "8659eb98404f4ea4b35c225050fe0f57"
  }, 
  "data": {
    "agreementID": "UA-2019-01-01-000001-d20d3c98c4bd4a3cb66b667a20b4ea6c1", 
    "status": "active", 
    "contracts": [
      {
        "status": "active", 
        "unitPrices": [
          {
            "value": {
              "currency": "UAH", 
              "amount": 93, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "1785dbc0c6e546b6b35797ba5571b8f2"
          }
        ], 
        "suppliers": [
          {
            "contactPoint": {
              "name_en": "State administration", 
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "legalName_en": "dus.gov.ua", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name_en": "State administration", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "name": "Державне управління справами"
          }
        ], 
        "bidID": "e7f2b760c732497ea8d46dcad1c42c92", 
        "date": "2019-01-01T00:00:00+02:00", 
        "awardID": "ab14434c3bd94ea1a33a3b83949e491c", 
        "id": "900682c3083c4b46bc219393d8ace5b0"
      }, 
      {
        "status": "active", 
        "unitPrices": [
          {
            "value": {
              "currency": "UAH", 
              "amount": 93, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "1785dbc0c6e546b6b35797ba5571b8f2"
          }
        ], 
        "suppliers": [
          {
            "contactPoint": {
              "name_en": "State administration", 
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "legalName_en": "dus.gov.ua", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name_en": "State administration", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "name": "Державне управління справами"
          }
        ], 
        "bidID": "4f6fa0b52e96437d80f2574a49ae00d1", 
        "date": "2019-01-01T00:00:00+02:00", 
        "awardID": "3b3bd9642fd54f51a7b310bb1a3a9d88", 
        "id": "9701a9a820794615a5cc94fddcddc599"
      }, 
      {
        "status": "active", 
        "unitPrices": [
          {
            "value": {
              "currency": "UAH", 
              "amount": 93, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "1785dbc0c6e546b6b35797ba5571b8f2"
          }
        ], 
        "suppliers": [
          {
            "contactPoint": {
              "name_en": "State administration", 
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "legalName_en": "dus.gov.ua", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name_en": "State administration", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "name": "Державне управління справами"
          }
        ], 
        "bidID": "210f53415f41477f8f161e3adb840a67", 
        "date": "2019-01-01T00:00:00+02:00", 
        "awardID": "4e6e5649e2ee44d89abadb56590bd937", 
        "id": "b6b061e4ffc344079dd2a5e658f91866"
      }
    ], 
    "items": [
      {
        "relatedLot": "fd9f66a19a8a44a89ee4a1019b7010ac", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases for state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00", 
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        }, 
        "id": "1785dbc0c6e546b6b35797ba5571b8f2", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "id": "01d3f2813ee344a2adffb8d4b7f11a75", 
    "numberOfContracts": 3, 
    "procuringEntity": {
      "kind": "general", 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }, 
      "contactPoint": {
        "name_en": "State administration", 
        "name": "Державне управління справами", 
        "availableLanguage": "uk", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "dus.gov.ua", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name_en": "State administration"
    }, 
    "owner": "broker", 
    "dateModified": "2019-01-01T00:00:00+02:00", 
    "tender_id": "cc7eacf6d8ca4feaafda4c9b7d6e73d1"
  }
}

