PATCH /api/2.5/agreements/9a49a7db3ada48519aa5b2c9a4ec5d30?acc_token=76b0c07026994e7089d5f9716acfc3e7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 34
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "terminated"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "agreementID": "UA-2019-04-01-000001-c0020a8c90ab4fa5b812bce6fc90c3871", 
    "status": "terminated", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "agreement_changes.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/324a4d1ffe3f4d1b8b0d04070f66bb14?KeyID=a8968c46&Signature=Ow%252B24cuNpLybH6QHsjZPn2iRmMgsJiYm7QrnAgIYFofQ5haOGV4faUJZb9wjLanuWHs7JscqtACkuK8iID2mAA%253D%253D", 
        "format": "application/msword", 
        "documentOf": "change", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "b50c55e02e674288acaabe0a5add3b78", 
        "relatedItem": "563cc544379744ed9b023a88ff6e415b", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "agreement.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f454dfeb012943b285f0edd2c34236ad?KeyID=a8968c46&Signature=kPttcj%252BWNu5YjH5PfyOJcBgTwzY5J40mmB1cGieq0OsGWr30mTOsfxoW9shGCgEmHUBhah7G26HTqfWVcMhpAg%253D%253D", 
        "format": "application/msword", 
        "documentOf": "agreement", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "6fae581fdc4245c8ba603746e3fe69f0", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "agreement_additional_docs.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3f66b6aef6a0421ba98012912c20406b?KeyID=a8968c46&Signature=cPDzwPawNAsP7xYHBesz1TcJJX6sUlPjaYkPEMEcDl%2FrDwL5%2FzaqoR6IY7XmY1nC6unCE9Vo3RQ4dDUncTUCBw%253D%253D", 
        "format": "application/msword", 
        "documentOf": "agreement", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "09a8f95409ba4f729ce2b9b055ace601", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "agreement_additional_docs.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2bdd749561c6467ab2861546e39addb8?KeyID=a8968c46&Signature=UMzfv4G3FccZWVvsufobHsZyn2lYD1BPPNjwZJpz%2FVZLHg3JaJ5Lqv34wT%252BSk5tQCxnrqH2sFfHuzuzRjyrCAQ%253D%253D", 
        "format": "application/msword", 
        "documentOf": "agreement", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "09a8f95409ba4f729ce2b9b055ace601", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "contracts": [
      {
        "status": "active", 
        "unitPrices": [
          {
            "value": {
              "currency": "UAH", 
              "amount": 14.93, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "4f89f9d4a4214593b43c21ddd0d9e035"
          }
        ], 
        "suppliers": [
          {
            "scale": "micro", 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "name_en": "State administration", 
            "identifier": {
              "scheme": "UA-EDR", 
              "legalName_en": "dus.gov.ua", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "contactPoint": {
              "name_en": "State administration", 
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }
          }
        ], 
        "bidID": "a980f94421f24fbe92f9d910e9858ea2", 
        "date": "2019-04-01T01:00:00+03:00", 
        "awardID": "578b2f5fc4704697a33639c665d658f6", 
        "id": "8aa8074ea3fd4e45afccbf42693eb919"
      }, 
      {
        "status": "active", 
        "unitPrices": [
          {
            "value": {
              "currency": "UAH", 
              "amount": 14.93, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "4f89f9d4a4214593b43c21ddd0d9e035"
          }
        ], 
        "suppliers": [
          {
            "scale": "micro", 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "name_en": "State administration", 
            "identifier": {
              "scheme": "UA-EDR", 
              "legalName_en": "dus.gov.ua", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "contactPoint": {
              "name_en": "State administration", 
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }
          }
        ], 
        "bidID": "d3387930d21c46e78c6411b4de2727d1", 
        "date": "2019-04-01T01:00:00+03:00", 
        "awardID": "c93cd768c20f4d559e42a751e508911a", 
        "id": "5745deb462a74af28cfe4f38b0007c7c"
      }, 
      {
        "status": "active", 
        "unitPrices": [
          {
            "value": {
              "currency": "UAH", 
              "amount": 14.93, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "4f89f9d4a4214593b43c21ddd0d9e035"
          }
        ], 
        "suppliers": [
          {
            "scale": "micro", 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "name_en": "State administration", 
            "identifier": {
              "scheme": "UA-EDR", 
              "legalName_en": "dus.gov.ua", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "contactPoint": {
              "name_en": "State administration", 
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }
          }
        ], 
        "bidID": "9546133ebacc4fa884a2bcf107e07f4f", 
        "date": "2019-04-01T01:00:00+03:00", 
        "awardID": "6d5c60d61d324b02b18e3661e46d63fd", 
        "id": "fa8bfba5854949d58ec92b2f7400eb6b"
      }
    ], 
    "items": [
      {
        "relatedLot": "2b33a80c73cb4c39957170a963adfe52", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases for state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00", 
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        }, 
        "id": "4f89f9d4a4214593b43c21ddd0d9e035", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "id": "9a49a7db3ada48519aa5b2c9a4ec5d30", 
    "numberOfContracts": 3, 
    "procuringEntity": {
      "kind": "general", 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }, 
      "contactPoint": {
        "name_en": "State administration", 
        "name": "Державне управління справами", 
        "availableLanguage": "uk", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "dus.gov.ua", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name_en": "State administration"
    }, 
    "owner": "broker", 
    "changes": [
      {
        "status": "active", 
        "modifications": [
          {
            "itemId": "4f89f9d4a4214593b43c21ddd0d9e035", 
            "factor": 0.1605
          }
        ], 
        "rationaleType": "taxRate", 
        "rationale_en": "Agreement change cause", 
        "dateSigned": "2019-04-01T01:00:00+03:00", 
        "rationale": "Друга і третя поставка має бути розфасована", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "563cc544379744ed9b023a88ff6e415b"
      }
    ], 
    "dateModified": "2019-04-01T01:00:00+03:00", 
    "tender_id": "3b7af763f1e2441080bbb1c6bdb75005"
  }
}

