PATCH /api/2.5/agreements/9a49a7db3ada48519aa5b2c9a4ec5d30/changes/563cc544379744ed9b023a88ff6e415b?acc_token=76b0c07026994e7089d5f9716acfc3e7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 73
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "dateSigned": "2019-04-01T01:00:00+03:00"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "modifications": [
      {
        "itemId": "4f89f9d4a4214593b43c21ddd0d9e035", 
        "factor": 0.1605
      }
    ], 
    "rationaleType": "taxRate", 
    "rationale_en": "Agreement change cause", 
    "dateSigned": "2019-04-01T01:00:00+03:00", 
    "rationale": "Друга і третя поставка має бути розфасована", 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "563cc544379744ed9b023a88ff6e415b"
  }
}

