GET /api/2.5/tenders/3b7af763f1e2441080bbb1c6bdb75005 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "complete", 
    "awardPeriod": {
      "startDate": "2019-09-15T01:00:00+03:00", 
      "endDate": "2019-09-25T01:00:00+03:00"
    }, 
    "mainProcurementCategory": "goods", 
    "complaintPeriod": {
      "startDate": "2019-08-04T01:00:00+03:00", 
      "endDate": "2019-08-31T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-08-04T01:00:00+03:00", 
      "clarificationsUntil": "2019-08-30T00:00:00+03:00", 
      "endDate": "2019-08-25T01:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procurementMethodType": "closeFrameworkAgreementUA", 
    "procuringEntity": {
      "kind": "general", 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }, 
      "contactPoint": {
        "name_en": "State administration", 
        "name": "Державне управління справами", 
        "availableLanguage": "uk", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "dus.gov.ua", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name_en": "State administration"
    }, 
    "owner": "broker", 
    "id": "3b7af763f1e2441080bbb1c6bdb75005", 
    "contractPeriod": {
      "startDate": "2019-09-25T01:00:00+03:00", 
      "clarificationsUntil": "2019-09-30T01:00:00+03:00", 
      "endDate": "2019-10-01T01:00:00+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "lots": [
      {
        "status": "active", 
        "description": "lot description", 
        "title": "lot title", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "startDate": "2019-09-14T01:00:00+03:00", 
          "endDate": "2019-09-15T01:00:00+03:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-10-01T01:00:00+03:00", 
        "id": "2b33a80c73cb4c39957170a963adfe52"
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2019-09-04T01:00:00+03:00", 
      "endDate": "2019-09-14T01:00:00+03:00"
    }, 
    "maxAwardsCount": 4, 
    "agreements": [
      {
        "agreementID": "UA-2019-10-01-000001-c0020a8c90ab4fa5b812bce6fc90c3871", 
        "status": "active", 
        "contracts": [
          {
            "status": "active", 
            "unitPrices": [
              {
                "value": {
                  "currency": "UAH", 
                  "amount": 93, 
                  "valueAddedTaxIncluded": true
                }, 
                "relatedItem": "4f89f9d4a4214593b43c21ddd0d9e035"
              }
            ], 
            "suppliers": [
              {
                "scale": "micro", 
                "name": "Державне управління справами", 
                "address": {
                  "postalCode": "01220", 
                  "countryName": "Україна", 
                  "streetAddress": "вул. Банкова, 11, корпус 1", 
                  "region": "м. Київ", 
                  "locality": "м. Київ"
                }, 
                "name_en": "State administration", 
                "identifier": {
                  "scheme": "UA-EDR", 
                  "legalName_en": "dus.gov.ua", 
                  "id": "00037256", 
                  "uri": "http://www.dus.gov.ua/"
                }, 
                "contactPoint": {
                  "name_en": "State administration", 
                  "name": "Державне управління справами", 
                  "telephone": "0440000000"
                }
              }
            ], 
            "bidID": "a980f94421f24fbe92f9d910e9858ea2", 
            "date": "2019-10-01T01:00:00+03:00", 
            "awardID": "578b2f5fc4704697a33639c665d658f6", 
            "id": "8aa8074ea3fd4e45afccbf42693eb919"
          }, 
          {
            "status": "active", 
            "unitPrices": [
              {
                "value": {
                  "currency": "UAH", 
                  "amount": 93, 
                  "valueAddedTaxIncluded": true
                }, 
                "relatedItem": "4f89f9d4a4214593b43c21ddd0d9e035"
              }
            ], 
            "suppliers": [
              {
                "scale": "micro", 
                "name": "Державне управління справами", 
                "address": {
                  "postalCode": "01220", 
                  "countryName": "Україна", 
                  "streetAddress": "вул. Банкова, 11, корпус 1", 
                  "region": "м. Київ", 
                  "locality": "м. Київ"
                }, 
                "name_en": "State administration", 
                "identifier": {
                  "scheme": "UA-EDR", 
                  "legalName_en": "dus.gov.ua", 
                  "id": "00037256", 
                  "uri": "http://www.dus.gov.ua/"
                }, 
                "contactPoint": {
                  "name_en": "State administration", 
                  "name": "Державне управління справами", 
                  "telephone": "0440000000"
                }
              }
            ], 
            "bidID": "d3387930d21c46e78c6411b4de2727d1", 
            "date": "2019-10-01T01:00:00+03:00", 
            "awardID": "c93cd768c20f4d559e42a751e508911a", 
            "id": "5745deb462a74af28cfe4f38b0007c7c"
          }, 
          {
            "status": "active", 
            "unitPrices": [
              {
                "value": {
                  "currency": "UAH", 
                  "amount": 93, 
                  "valueAddedTaxIncluded": true
                }, 
                "relatedItem": "4f89f9d4a4214593b43c21ddd0d9e035"
              }
            ], 
            "suppliers": [
              {
                "scale": "micro", 
                "name": "Державне управління справами", 
                "address": {
                  "postalCode": "01220", 
                  "countryName": "Україна", 
                  "streetAddress": "вул. Банкова, 11, корпус 1", 
                  "region": "м. Київ", 
                  "locality": "м. Київ"
                }, 
                "name_en": "State administration", 
                "identifier": {
                  "scheme": "UA-EDR", 
                  "legalName_en": "dus.gov.ua", 
                  "id": "00037256", 
                  "uri": "http://www.dus.gov.ua/"
                }, 
                "contactPoint": {
                  "name_en": "State administration", 
                  "name": "Державне управління справами", 
                  "telephone": "0440000000"
                }
              }
            ], 
            "bidID": "9546133ebacc4fa884a2bcf107e07f4f", 
            "date": "2019-10-01T01:00:00+03:00", 
            "awardID": "6d5c60d61d324b02b18e3661e46d63fd", 
            "id": "fa8bfba5854949d58ec92b2f7400eb6b"
          }
        ], 
        "items": [
          {
            "relatedLot": "2b33a80c73cb4c39957170a963adfe52", 
            "description": "футляри до державних нагород", 
            "classification": {
              "scheme": "ДК021", 
              "description": "Cartons", 
              "id": "44617100-9"
            }, 
            "description_en": "Cases for state awards", 
            "additionalClassifications": [
              {
                "scheme": "ДКПП", 
                "id": "17.21.1", 
                "description": "папір і картон гофровані, паперова й картонна тара"
              }
            ], 
            "deliveryAddress": {
              "postalCode": "79000", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "deliveryDate": {
              "startDate": "2018-06-27T13:39:09.362837+03:00", 
              "endDate": "2018-06-30T13:39:09.362837+03:00"
            }, 
            "id": "4f89f9d4a4214593b43c21ddd0d9e035", 
            "unit": {
              "code": "44617100-9", 
              "name": "item"
            }, 
            "quantity": 5.0
          }
        ], 
        "date": "2019-10-01T01:00:00+03:00", 
        "id": "9a49a7db3ada48519aa5b2c9a4ec5d30"
      }
    ], 
    "auctionPeriod": {
      "startDate": "2019-09-14T01:00:00+03:00", 
      "endDate": "2019-09-15T01:00:00+03:00"
    }, 
    "dateModified": "2019-10-01T01:00:00+03:00", 
    "tenderID": "UA-2019-10-01-000001", 
    "numberOfBids": 3, 
    "tenderPeriod": {
      "startDate": "2019-08-04T01:00:00+03:00", 
      "endDate": "2019-09-04T01:00:00+03:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "lotID": "2b33a80c73cb4c39957170a963adfe52", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "a980f94421f24fbe92f9d910e9858ea2", 
        "date": "2019-09-04T01:00:00+03:00", 
        "id": "b3c48de2c44149a0af08482f1183cbe2"
      }, 
      {
        "status": "active", 
        "lotID": "2b33a80c73cb4c39957170a963adfe52", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "d3387930d21c46e78c6411b4de2727d1", 
        "date": "2019-09-04T01:00:00+03:00", 
        "id": "693d4a4a10df4db6b818582a49ba0b46"
      }, 
      {
        "status": "active", 
        "lotID": "2b33a80c73cb4c39957170a963adfe52", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "9546133ebacc4fa884a2bcf107e07f4f", 
        "date": "2019-09-04T01:00:00+03:00", 
        "id": "77eb33bf7ab345f6ab2f8d9e644a24da"
      }
    ], 
    "title_en": "Cases for state awards", 
    "agreementDuration": "P3Y3M3D", 
    "awards": [
      {
        "status": "active", 
        "lotID": "2b33a80c73cb4c39957170a963adfe52", 
        "complaintPeriod": {
          "startDate": "2019-09-15T01:00:00+03:00", 
          "endDate": "2019-09-25T01:00:00+03:00"
        }, 
        "suppliers": [
          {
            "scale": "micro", 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "name_en": "State administration", 
            "identifier": {
              "scheme": "UA-EDR", 
              "legalName_en": "dus.gov.ua", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "contactPoint": {
              "name_en": "State administration", 
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }
          }
        ], 
        "bid_id": "a980f94421f24fbe92f9d910e9858ea2", 
        "value": {
          "currency": "UAH", 
          "amount": 469, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-09-15T01:00:00+03:00", 
        "id": "578b2f5fc4704697a33639c665d658f6"
      }, 
      {
        "status": "active", 
        "lotID": "2b33a80c73cb4c39957170a963adfe52", 
        "complaintPeriod": {
          "startDate": "2019-09-15T01:00:00+03:00", 
          "endDate": "2019-09-25T01:00:00+03:00"
        }, 
        "suppliers": [
          {
            "scale": "micro", 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "name_en": "State administration", 
            "identifier": {
              "scheme": "UA-EDR", 
              "legalName_en": "dus.gov.ua", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "contactPoint": {
              "name_en": "State administration", 
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }
          }
        ], 
        "bid_id": "d3387930d21c46e78c6411b4de2727d1", 
        "value": {
          "currency": "UAH", 
          "amount": 470.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-09-15T01:00:00+03:00", 
        "id": "c93cd768c20f4d559e42a751e508911a"
      }, 
      {
        "status": "active", 
        "lotID": "2b33a80c73cb4c39957170a963adfe52", 
        "complaintPeriod": {
          "startDate": "2019-09-15T01:00:00+03:00", 
          "endDate": "2019-09-25T01:00:00+03:00"
        }, 
        "suppliers": [
          {
            "scale": "micro", 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "name_en": "State administration", 
            "identifier": {
              "scheme": "UA-EDR", 
              "legalName_en": "dus.gov.ua", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "contactPoint": {
              "name_en": "State administration", 
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }
          }
        ], 
        "bid_id": "9546133ebacc4fa884a2bcf107e07f4f", 
        "value": {
          "currency": "UAH", 
          "amount": 471, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-09-15T01:00:00+03:00", 
        "id": "6d5c60d61d324b02b18e3661e46d63fd"
      }
    ], 
    "date": "2019-10-01T01:00:00+03:00", 
    "milestones": [
      {
        "code": "prepayment", 
        "sequenceNumber": 0, 
        "title": "signingTheContract", 
        "duration": {
          "type": "banking", 
          "days": 2
        }, 
        "percentage": 100.0, 
        "type": "financing", 
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      }
    ], 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "2b33a80c73cb4c39957170a963adfe52", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases for state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00", 
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        }, 
        "id": "4f89f9d4a4214593b43c21ddd0d9e035", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "selfEligible": true, 
        "lotValues": [
          {
            "relatedLot": "2b33a80c73cb4c39957170a963adfe52", 
            "date": "2019-10-01T01:00:00+03:00", 
            "status": "active", 
            "value": {
              "currency": "UAH", 
              "amount": 469, 
              "valueAddedTaxIncluded": true
            }
          }
        ], 
        "selfQualified": true, 
        "tenderers": [
          {
            "scale": "micro", 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "name_en": "State administration", 
            "identifier": {
              "scheme": "UA-EDR", 
              "legalName_en": "dus.gov.ua", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "contactPoint": {
              "name_en": "State administration", 
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }
          }
        ], 
        "date": "2019-08-04T01:00:01+03:00", 
        "id": "a980f94421f24fbe92f9d910e9858ea2"
      }, 
      {
        "status": "active", 
        "selfEligible": true, 
        "lotValues": [
          {
            "relatedLot": "2b33a80c73cb4c39957170a963adfe52", 
            "date": "2019-10-01T01:00:00+03:00", 
            "status": "active", 
            "value": {
              "currency": "UAH", 
              "amount": 470.0, 
              "valueAddedTaxIncluded": true
            }
          }
        ], 
        "selfQualified": true, 
        "tenderers": [
          {
            "scale": "micro", 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "name_en": "State administration", 
            "identifier": {
              "scheme": "UA-EDR", 
              "legalName_en": "dus.gov.ua", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "contactPoint": {
              "name_en": "State administration", 
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }
          }
        ], 
        "date": "2019-08-04T01:00:02+03:00", 
        "id": "d3387930d21c46e78c6411b4de2727d1"
      }, 
      {
        "status": "active", 
        "selfEligible": true, 
        "lotValues": [
          {
            "relatedLot": "2b33a80c73cb4c39957170a963adfe52", 
            "date": "2019-10-01T01:00:00+03:00", 
            "status": "active", 
            "value": {
              "currency": "UAH", 
              "amount": 471, 
              "valueAddedTaxIncluded": true
            }
          }
        ], 
        "selfQualified": true, 
        "tenderers": [
          {
            "scale": "micro", 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "name_en": "State administration", 
            "identifier": {
              "scheme": "UA-EDR", 
              "legalName_en": "dus.gov.ua", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "contactPoint": {
              "name_en": "State administration", 
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }
          }
        ], 
        "date": "2019-08-04T01:00:03+03:00", 
        "id": "9546133ebacc4fa884a2bcf107e07f4f"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

