GET /api/2.5/agreements/812a4fd5803c47b19b57627d99c10f7f/documents/2bea1af6371843a9ab3f9a7ebaa89b59?acc_token=c9e67b4fcc7b4af5b8821e6411afb46f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "agreement_additional_docs.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/90969287054d401097315faabb8c66cd?KeyID=c1a97147&Signature=wJs7pQvhe%252BUhvAeHzOnsk1TEeVj3xjrTMuuGcIWXxAPFyPKqQL9G0cDtPSx%2FcAPSxaQq%2FlRRfTT1bT2yADXsDg%253D%253D", 
    "format": "application/msword", 
    "documentOf": "agreement", 
    "datePublished": "2019-03-18T09:26:19.043072+02:00", 
    "previousVersions": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "agreement_additional_docs.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/f381819794dd42d0b338e978f49008c1?KeyID=c1a97147&Signature=P%252BkWqHWvxeAyp2CkDUYA%252B3pyfc33XwQosspROuU0WyHmxVNg7%2FXZbhevSUHtI1Mk28btXlpSmq2mAcuxsa7uAQ%253D%253D", 
        "format": "application/msword", 
        "documentOf": "agreement", 
        "datePublished": "2019-03-18T09:26:19.043072+02:00", 
        "id": "2bea1af6371843a9ab3f9a7ebaa89b59", 
        "dateModified": "2019-03-18T09:26:19.043094+02:00"
      }
    ], 
    "id": "2bea1af6371843a9ab3f9a7ebaa89b59", 
    "dateModified": "2019-03-18T09:26:19.084917+02:00"
  }
}

