GET /api/2.5/agreements/83456a89ad0143b5b9dde8ca7ac28456/documents/bfa4de68c400402daf26f99f0b6f0ac5?acc_token=7b93503ebb914e35ac86ce4cf565018f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "agreement_additional_docs.doc", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ebf268e3fa1c43e7b77f0a323c2f0a7e?KeyID=a8968c46&Signature=HYqBadirUwrdJYzIGRucNYyGQAdP%252BD4BlH6Z3mGcaIZPHJCqITc%2Fq0v6DgYwJ12DS5Z82NJzuGY0uSjyh2%252BkDA%253D%253D", 
    "format": "application/msword", 
    "documentOf": "agreement", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "previousVersions": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "agreement_additional_docs.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7452a0b9ad044867b72addc031725961?KeyID=a8968c46&Signature=bmP%2Fcu%2FpvWoAA%252BWBwoXKjggwdyjaz%252BL9MUoN61f%252B2Z2q07ai3C47Fg1MrbqUahb55F6m5u8bUF14NKZnlh27Bw%253D%253D", 
        "format": "application/msword", 
        "documentOf": "agreement", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "bfa4de68c400402daf26f99f0b6f0ac5", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "id": "bfa4de68c400402daf26f99f0b6f0ac5", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

