POST /api/2.5/agreements/5288ba4e6b2548228693339fe56536b8/documents?acc_token=75ba8ec62fef493fa0322013ff4a6752 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 166
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="agreement_additional_docs.doc"
Content-Type: application/msword

additional info
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/agreements/5288ba4e6b2548228693339fe56536b8/documents/09c8642181984bbda32f5c674effaee0
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "agreement_additional_docs.doc", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9b9fa3cdc7404b1abf2d555d2784560d?KeyID=a8968c46&Signature=2W4g1zlLuectg93LQC5bY37FLBU7inXT2mDe8UnsOprNde4zZ6WbfJPD9Fu8l99Nuy4CbSBJsaxDtaP2ayCdBw%253D%253D", 
    "format": "application/msword", 
    "documentOf": "agreement", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "09c8642181984bbda32f5c674effaee0", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

