POST /api/2.5/agreements/812a4fd5803c47b19b57627d99c10f7f/documents?acc_token=c9e67b4fcc7b4af5b8821e6411afb46f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 192
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy977155440111$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/agreements/812a4fd5803c47b19b57627d99c10f7f/documents/3ff766dbb2da4d1d886c537255e99151
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "agreement.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/b0fffafca6c745a6ab24dbed4313c177?KeyID=c1a97147&Signature=fxx5ZpXheksTBQG%2F9xrkfdBj40V%2FqRacQ0%2FCFyajl4a%252BTGZbyyu7oF%2FuzKIgORfdJd%2FXLYojpIhgYVdYK%2FPODw%253D%253D", 
    "format": "application/msword", 
    "documentOf": "agreement", 
    "datePublished": "2019-03-18T09:26:18.986311+02:00", 
    "id": "3ff766dbb2da4d1d886c537255e99151", 
    "dateModified": "2019-03-18T09:26:18.986332+02:00"
  }
}

