GET /api/2.5/agreements/c37f8569c6104df8b9c909a2bd5e591d/changes/61f8b06f662e467d87a1854331f446bd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "rationaleType": "taxRate", 
    "rationale_en": "Agreement change cause", 
    "rationale": "Опис причини змін егріменту", 
    "date": "2019-03-28T06:47:11.108337+02:00", 
    "id": "61f8b06f662e467d87a1854331f446bd"
  }
}

