PATCH /api/2.5/tenders/4cdd6b38d69c459284b31ab81cbea097/cancellations/e0a569edf2bb4ebe8a2186cba90df92b?acc_token=55a1ff7e4b9c4fec90bca39c8e96fbd7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e357afb689f54b1bbe79b3d1776c4c5d?KeyID=a8968c46&Signature=rHYdycvUv3eKW7uE367QIq1POK0XCl%2F4e%2F0%252BtLhhbbc0HsdNDsy0cxNszq%2Fo0rHLcTQswEuzQb1At9Svhyw0Ag%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "de6c0686e83d49f7bfb66753e59c3185", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/797ab4fc0e7a4c748d593da4652c966b?KeyID=a8968c46&Signature=X7dh%2FIJ8EJ13iMtPvSlydh2heqheBsK%2FltUOJHzUKfAydLYICyTU%2FjKb7iCNvXcW7CWbPMqCkxHA2IupsvTCAQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "de6c0686e83d49f7bfb66753e59c3185", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2019-04-01T01:00:00+03:00", 
    "cancellationOf": "tender", 
    "id": "e0a569edf2bb4ebe8a2186cba90df92b"
  }
}

