PATCH /api/2.5/tenders/949046045b7b4af884185f44873d6333/bids/0a33c847627c40f29be398012d54872d?acc_token=1590cd650808460fbb0b3b6675654de6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "parameters": [
      {
        "code": "OCDS-123454-AIR-INTAKE", 
        "value": 0.1
      }, 
      {
        "code": "OCDS-123454-YEARS", 
        "value": 0.1
      }
    ], 
    "lotValues": [
      {
        "relatedLot": "2eb770a1b04c40e6a7dedd0203f3e41c", 
        "date": "2019-04-03T14:33:54.288744+03:00", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "date": "2019-04-03T14:33:54.288213+03:00", 
    "id": "0a33c847627c40f29be398012d54872d"
  }
}

