PATCH /api/2.5/tenders/4cdd6b38d69c459284b31ab81cbea097/bids/a8258103df2e418e92148e15c8e0b4ff?acc_token=1fd07021263f459784a13cdcd1083767 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "parameters": [
      {
        "code": "OCDS-123454-AIR-INTAKE", 
        "value": 0.1
      }, 
      {
        "code": "OCDS-123454-YEARS", 
        "value": 0.1
      }
    ], 
    "lotValues": [
      {
        "relatedLot": "1facee4c8a8742b280f9a3456f62ae41", 
        "date": "2019-01-01T00:00:00+02:00", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "a8258103df2e418e92148e15c8e0b4ff"
  }
}

