POST /api/2.5/tenders/ae3adab91a6741b7b7c081c7f99632aa/awards/1dc71b55721546e2b3694a48957437ae/documents?acc_token=dcfda2d9335b41a9814dc01c39bd9a03 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 325
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f097819e8bf54da4a7f911de9c66ad1c?KeyID=a1aff1ca&Signature=cl3uXSdWggJHWJxFy9fKHsXZQHkNiHMURGh9vGRm%2FFOEqhtWSihGF2TfKKNTlE3hbR2NPmvhr8cUHl1Ju6UIDg%3D%3D", 
    "title": "explanation.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ae3adab91a6741b7b7c081c7f99632aa/awards/1dc71b55721546e2b3694a48957437ae/documents/d8f082bf274b42ea9c551a8b183c97c4
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "explanation.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f097819e8bf54da4a7f911de9c66ad1c?KeyID=a1aff1ca&Signature=fmEwnGi8yUAsl3Ya9YkwnUfb1eo1%2FtGWXw86oWy6%2FYeu3Z1nxgISD36BihMDewNbOBvu9KUEjBW9yp%2FZsaLyCA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "d8f082bf274b42ea9c551a8b183c97c4", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

