PATCH /api/2.5/tenders/ae8a7a3627f44c8abb4a52c7627b32bc/awards/549ac1d9c0044ef2aeb0b51476e6e9ec?acc_token=050c83ebfd4e43dab16376874d5b59e6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/ae8a7a3627f44c8abb4a52c7627b32bc/awards/a5be8e6bcf674af78b093716d5420353

{
  "data": {
    "status": "unsuccessful", 
    "lotID": "d873580630ad4256938558786a55bb52", 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037257", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "fda8ed6098c94802be9f72d2dbe9e471", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-26T13:54:42.813037+02:00", 
    "id": "549ac1d9c0044ef2aeb0b51476e6e9ec"
  }
}

