PATCH /api/2.5/tenders/949046045b7b4af884185f44873d6333/awards/181b063346ec47f5b8676d87456c96bd?acc_token=3d89223d197942ab80412ef30c104bc9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/949046045b7b4af884185f44873d6333/awards/f46a3baa7e1c46d880150192748ccaa1

{
  "data": {
    "status": "cancelled", 
    "lotID": "2eb770a1b04c40e6a7dedd0203f3e41c", 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037257", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "1eda265259254eae91d34999a6d449c0", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-04-03T14:33:56.184031+03:00", 
    "id": "181b063346ec47f5b8676d87456c96bd"
  }
}

