PATCH /api/2.5/tenders/4cdd6b38d69c459284b31ab81cbea097/awards/b502e88ae8124d6fbb27b44565ceed27?acc_token=55a1ff7e4b9c4fec90bca39c8e96fbd7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "Can't update award status to unsuccessful, if tender status is active.qualification and there is no cancelled award with the same bid_id", 
      "location": "body", 
      "name": "data"
    }
  ]
}

