GET /api/2.5/tenders/4cdd6b38d69c459284b31ab81cbea097/bids/6b6fe9bb3ef647d8ac5b8be0f8873c31?acc_token=628dcd2f31a74c9e807d71999912b5a8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/4cdd6b38d69c459284b31ab81cbea097/bids/6b6fe9bb3ef647d8ac5b8be0f8873c31/documents/8674559edc784ee191203c1aaf697f0d?download=4d664f20da954b5a9c0db7551b7a33dc", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "8674559edc784ee191203c1aaf697f0d", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part2.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/4cdd6b38d69c459284b31ab81cbea097/bids/6b6fe9bb3ef647d8ac5b8be0f8873c31/documents/5b2bf6b93e66458ba575611bb2182594?download=d8b01693edf34934981026078162ed9d", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "5b2bf6b93e66458ba575611bb2182594", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "parameters": [
      {
        "code": "OCDS-123454-AIR-INTAKE", 
        "value": 0.1
      }, 
      {
        "code": "OCDS-123454-YEARS", 
        "value": 0.1
      }
    ], 
    "lotValues": [
      {
        "relatedLot": "1facee4c8a8742b280f9a3456f62ae41", 
        "date": "2019-01-01T00:00:00+02:00", 
        "value": {
          "currency": "UAH", 
          "amount": 499.0, 
          "valueAddedTaxIncluded": true
        }, 
        "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/4cdd6b38d69c459284b31ab81cbea097_1facee4c8a8742b280f9a3456f62ae41?key_for_bid=6b6fe9bb3ef647d8ac5b8be0f8873c31"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037257", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "6b6fe9bb3ef647d8ac5b8be0f8873c31"
  }
}

