GET /api/2.5/tenders/ae3adab91a6741b7b7c081c7f99632aa/bids/a69f65653c6645b7b03b670879e046f2?acc_token=4b67513fad05488d93b09efae472dba4 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ae3adab91a6741b7b7c081c7f99632aa/bids/a69f65653c6645b7b03b670879e046f2/documents/2cc764ce990040f9a0e685c460d8ca06?download=3097619d74b04754b3623b4b8c367a1f", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "2cc764ce990040f9a0e685c460d8ca06", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "parameters": [
      {
        "code": "OCDS-123454-AIR-INTAKE", 
        "value": 0.1
      }, 
      {
        "code": "OCDS-123454-YEARS", 
        "value": 0.1
      }
    ], 
    "lotValues": [
      {
        "relatedLot": "be6fe65d43f14d3d838990f21c3d2d69", 
        "date": "2019-01-01T00:00:00+02:00", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/ae3adab91a6741b7b7c081c7f99632aa_be6fe65d43f14d3d838990f21c3d2d69?key_for_bid=a69f65653c6645b7b03b670879e046f2"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "a69f65653c6645b7b03b670879e046f2"
  }
}

