GET /api/2.5/tenders/7a805885546c48c1bcdeaf1c72cc7f5d/bids/d5d41b6d48084b00952a9d92b5fa8e23?acc_token=4e0e864b4c2c47cdba69ee23c22f3997 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/7a805885546c48c1bcdeaf1c72cc7f5d/bids/d5d41b6d48084b00952a9d92b5fa8e23/documents/bc245b8a049f4ca5ab886228e97c1146?download=dd08f1c549ee43eeb7e5b2c57831c9e4", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:40.525189+02:00", 
        "id": "bc245b8a049f4ca5ab886228e97c1146", 
        "dateModified": "2019-03-18T09:26:40.525201+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/7a805885546c48c1bcdeaf1c72cc7f5d/bids/d5d41b6d48084b00952a9d92b5fa8e23/documents/5a2611ef52c64e249380860c96e9fa44?download=100f5d59b3854e188be8bff6c83fbf54", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:40.525532+02:00", 
        "id": "5a2611ef52c64e249380860c96e9fa44", 
        "dateModified": "2019-03-18T09:26:40.525543+02:00"
      }
    ], 
    "parameters": [
      {
        "code": "OCDS-123454-AIR-INTAKE", 
        "value": 0.1
      }, 
      {
        "code": "OCDS-123454-YEARS", 
        "value": 0.1
      }
    ], 
    "lotValues": [
      {
        "relatedLot": "01a475ba65af458ca805d6770e8cee95", 
        "date": "2019-03-18T09:26:40.526016+02:00", 
        "value": {
          "currency": "UAH", 
          "amount": 499.0, 
          "valueAddedTaxIncluded": true
        }, 
        "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/7a805885546c48c1bcdeaf1c72cc7f5d_01a475ba65af458ca805d6770e8cee95?key_for_bid=d5d41b6d48084b00952a9d92b5fa8e23"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037257", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "date": "2019-03-18T09:26:40.524882+02:00", 
    "id": "d5d41b6d48084b00952a9d92b5fa8e23"
  }
}

