PATCH /api/2.5/tenders/ae3adab91a6741b7b7c081c7f99632aa/awards/459fc6df79cd4840973a2f8b81f36a07?acc_token=dcfda2d9335b41a9814dc01c39bd9a03 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "lotID": "be6fe65d43f14d3d838990f21c3d2d69", 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037258", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "8af407a0516b4dcd976cb42c287ec49f", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "459fc6df79cd4840973a2f8b81f36a07"
  }
}

