PATCH /api/2.5/tenders/ae3adab91a6741b7b7c081c7f99632aa/cancellations/69d7432c98dc4fe1afbb3e2465b0be4b/documents/6e56a61f2f6444bc82d413f70f8c7025?acc_token=dcfda2d9335b41a9814dc01c39bd9a03 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c30c47be1cb84bb0ba57641a3ca10ae5?KeyID=a1aff1ca&Signature=K7OA3lPELqe7gQ2dY6Aqjacc%252BWaXNil0YAHXboMlakmHMZxxKzI3NVGnkuWpWDv2fxpF5GI2ODpmmKg2%252B2mgAg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "6e56a61f2f6444bc82d413f70f8c7025", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

