PATCH /api/2.5/tenders/4cdd6b38d69c459284b31ab81cbea097/cancellations/e0a569edf2bb4ebe8a2186cba90df92b/documents/de6c0686e83d49f7bfb66753e59c3185?acc_token=55a1ff7e4b9c4fec90bca39c8e96fbd7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a10411a06b8d4364bd73e765f7258a9d?KeyID=a8968c46&Signature=4cCDHCJNWgcdqNxFhHCrt3wLUpKEk0uQjCXucE4J4%2FHpgl81dnnJQ8gYHBpxN6dbDmQy6KM7CXryb1PA2WJfDQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "de6c0686e83d49f7bfb66753e59c3185", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

