POST /api/2.5/tenders/ae8a7a3627f44c8abb4a52c7627b32bc/cancellations?acc_token=050c83ebfd4e43dab16376874d5b59e6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reason": "cancellation reason"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/ae8a7a3627f44c8abb4a52c7627b32bc/cancellations/3a4e3bc7a5f94c708423202070926a61

{
  "data": {
    "date": "2019-03-26T13:54:47.108361+02:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "3a4e3bc7a5f94c708423202070926a61"
  }
}

