POST /api/2.5/tenders/dfcf142d4b674c9392b10e98e3ee5060/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 953
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "draft", 
    "lotValues": [
      {
        "relatedLot": "e74b7c92ab634829a22f7d7ca3bf7021", 
        "value": {
          "amount": 500
        }
      }
    ], 
    "parameters": [
      {
        "code": "OCDS-123454-AIR-INTAKE", 
        "value": 0.1
      }, 
      {
        "code": "OCDS-123454-YEARS", 
        "value": 0.1
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ]
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "Bid is not a member of agreement", 
      "location": "body", 
      "name": "data"
    }
  ]
}

