PATCH /api/2.5/tenders/7a805885546c48c1bcdeaf1c72cc7f5d/lots/01a475ba65af458ca805d6770e8cee95?acc_token=3a37ff35bdc94e49ae549b2688693071 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 57
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "guarantee": {
      "currency": "USD", 
      "amount": 8
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "description": "lot description", 
    "title": "lot title", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 2.5, 
      "valueAddedTaxIncluded": true
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 600.67, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-18T09:26:38.315283+02:00", 
    "id": "01a475ba65af458ca805d6770e8cee95", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }
  }
}

