GET /api/2.5/tenders/4cdd6b38d69c459284b31ab81cbea097/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/058845deea5e44a2924d126939dc17b8?KeyID=a8968c46&Signature=ukiyus04BgWaA%252B5uVmBkAVAHJEEr5VZRj05WiGq0nc6QeHQiQ6L84MLrXzuSRevfDnnLM%252BzOy5R5jx5RJftNBw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "author": "tender_owner", 
      "documentType": "technicalSpecifications", 
      "id": "75f46ad3e0094b93a0cbc45a8f289735", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/85a12e05b46d4a4384045bd1723e9b06?KeyID=a8968c46&Signature=mdXMe1f0hIM9HYazuJrUg%252B3iXwnTyeOJezsO8Jgn3xGQUGKv22i4vqZdc8HemEjVQxfPeK6pLMkj8eM6xMEUAg%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "57a426ae3ae9439589d421cb9abd0f64", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }
  ]
}

