PATCH /api/2.5/tenders/ae8a7a3627f44c8abb4a52c7627b32bc/contracts/03eaa7c3888c487cb2ef3556189a7975?acc_token=050c83ebfd4e43dab16376874d5b59e6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_first_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/f897cd4f28ca4e8da931a026f7aeaab7?KeyID=c4137a63&Signature=QQ8vq342n9CO6AP21kKW1oKUqbQJexUm%2FmGqXFcL3eMKaXNO8cVsFE%2FLBFMn3jDh08OcLEkllQtmtKpHq2NAAg%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2019-03-26T13:54:44.854151+02:00", 
        "id": "6a5b9c9980ac4375b25fc08fd2a709f9", 
        "dateModified": "2019-03-26T13:54:44.854171+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_second_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/c8c087de3df4478d90f2438dafbe97dc?KeyID=c4137a63&Signature=DGNRBPte6CqHJGPoZSSD2r8sBjtQlczizhfy%2F%2F4n16oucot1AZjOWeA30LDrE7d2ETcK8fm6MkHh3LWXgenaCg%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2019-03-26T13:54:45.244914+02:00", 
        "id": "ea93a79d4f0c49ab811495dc85bffa0d", 
        "dateModified": "2019-03-26T13:54:45.244961+02:00"
      }
    ], 
    "items": [
      {
        "relatedLot": "d873580630ad4256938558786a55bb52", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "New Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "futliary do derzhavnyh nagorod", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-28T13:54:25.198916+02:00", 
          "endDate": "2019-03-31T13:54:25.198916+02:00"
        }, 
        "id": "1662b0e1d59f4e2f8e2c5bd48e03a7bc", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 6.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037258", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "period": {
      "startDate": "2019-03-26T13:54:25.220994+02:00", 
      "endDate": "2020-03-25T13:54:25.220994+02:00"
    }, 
    "dateSigned": "2019-03-26T13:54:45.625956+02:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-26T13:54:46.377415+02:00", 
    "awardID": "a5be8e6bcf674af78b093716d5420353", 
    "id": "03eaa7c3888c487cb2ef3556189a7975", 
    "contractID": "UA-2019-03-26-000004-2"
  }
}

