GET /api/2.5/tenders/dfcf142d4b674c9392b10e98e3ee5060/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e03f777b0dd44f3faf26f358bb40ecc6?KeyID=a8968c46&Signature=3R9L58Wd82mluYT9mte96bMA1%2FOMo19BtbBxfqi3UxGvJqPKS9c4Le3S5kcn7S63wjCZn5HI0mdh3UbStmA8DA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "fe62ca99ff8d44d0854f65a68614418d", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f929da880f7e4d4ab8c6d26f1410f480?KeyID=a8968c46&Signature=KRFZJwFtwhg%252BXBhZhaMg07ftuLu6mATWE5PLx2mF%252BqeeBsd9z5%2FPrA5pFUlZZMxuArbqScFi0I11tYpEQYUWDg%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "author": "tender_owner", 
      "documentType": "technicalSpecifications", 
      "id": "f1d5a23570df4df099a7ac7ad410c26e", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }
  ]
}

