POST /api/2.5/tenders?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 4412
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "features": [
      {
        "code": "OCDS-123454-AIR-INTAKE", 
        "description": "Ефективна потужність всмоктування пилососа, в ватах (аероватах)", 
        "title": "Потужність всмоктування", 
        "enum": [
          {
            "value": 0.1, 
            "title": "До 1000 Вт"
          }, 
          {
            "value": 0.15, 
            "title": "Більше 1000 Вт"
          }
        ], 
        "title_en": "Air Intake", 
        "relatedItem": "1662b0e1d59f4e2f8e2c5bd48e03a7bc", 
        "featureOf": "item"
      }, 
      {
        "code": "OCDS-123454-YEARS", 
        "description": "Кількість років, які організація учасник працює на ринку", 
        "title": "Років на ринку", 
        "enum": [
          {
            "value": 0.05, 
            "title": "До 3 років"
          }, 
          {
            "value": 0.1, 
            "title": "Більше 3 років, менше 5 років"
          }, 
          {
            "value": 0.15, 
            "title": "Більше 5 років"
          }
        ], 
        "title_en": "Years trading", 
        "featureOf": "tenderer"
      }
    ], 
    "title": "футляри до державних нагород", 
    "lots": [
      {
        "title": "lot title", 
        "id": "01a475ba65af458ca805d6770e8cee95", 
        "description": "lot description"
      }
    ], 
    "items": [
      {
        "relatedLot": "01a475ba65af458ca805d6770e8cee95", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "id": "44617100-9", 
          "description": "New Cartons"
        }, 
        "description_en": "futliary do derzhavnyh nagorod", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-20T09:26:15.326761+02:00", 
          "endDate": "2019-03-23T09:26:15.326761+02:00"
        }, 
        "id": "1662b0e1d59f4e2f8e2c5bd48e03a7bc", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "procurementMethodType": "closeFrameworkAgreementSelectionUA", 
    "procuringEntity": {
      "kind": "general", 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }, 
      "additionalContactPoints": [
        {
          "name": "Державне управління справами 1", 
          "availableLanguage": "uk", 
          "telephone": "0440000000"
        }
      ], 
      "contactPoint": {
        "name": "Державне управління справами", 
        "availableLanguage": "en", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }
    }, 
    "agreements": [
      {
        "id": "56a40c4f887f48a0873ec12bac92b706"
      }
    ]
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/ff0d38e97aeb438491ab990f9cb747a6

{
  "access": {
    "token": "ac7d0ac7b50a4da685b91c3ff31ebddb"
  }, 
  "data": {
    "status": "draft", 
    "procurementMethod": "selective", 
    "tenderID": "UA-2019-03-18-000001", 
    "title": "футляри до державних нагород", 
    "lots": [
      {
        "date": "2019-03-18T09:26:29.800543+02:00", 
        "status": "active", 
        "title": "lot title", 
        "description": "lot description", 
        "id": "01a475ba65af458ca805d6770e8cee95"
      }
    ], 
    "items": [
      {
        "relatedLot": "01a475ba65af458ca805d6770e8cee95", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "New Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "futliary do derzhavnyh nagorod", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-20T09:26:15.326761+02:00", 
          "endDate": "2019-03-23T09:26:15.326761+02:00"
        }, 
        "id": "1662b0e1d59f4e2f8e2c5bd48e03a7bc", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "procurementMethodType": "closeFrameworkAgreementSelectionUA", 
    "submissionMethod": "electronicAuction", 
    "date": "2019-03-18T09:26:29.800543+02:00", 
    "agreements": [
      {
        "id": "56a40c4f887f48a0873ec12bac92b706"
      }
    ], 
    "awardCriteria": "lowestCost", 
    "owner": "broker", 
    "dateModified": "2019-03-18T09:26:29.802990+02:00", 
    "id": "ff0d38e97aeb438491ab990f9cb747a6", 
    "procuringEntity": {
      "kind": "general", 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }, 
      "additionalContactPoints": [
        {
          "name": "Державне управління справами 1", 
          "availableLanguage": "uk", 
          "telephone": "0440000000"
        }
      ], 
      "contactPoint": {
        "name": "Державне управління справами", 
        "availableLanguage": "en", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }
    }
  }
}

