GET /api/2.5/tenders?opt_pretty=1 HTTP/1.0
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.5/tenders?offset=2019-04-03T14%3A34%3A34.226396%2B03%3A00", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.5/tenders?offset=2019-04-03T14%3A34%3A34.226396%2B03%3A00", 
    "offset": "2019-04-03T14:34:34.226396+03:00"
  }, 
  "data": [
    {
      "id": "bfc38e0727544f8bbcacbf60bd82358d", 
      "dateModified": "2019-04-03T14:34:34.226396+03:00"
    }
  ]
}

