GET /api/2.5/tenders/ae3adab91a6741b7b7c081c7f99632aa/contracts/da6dae5c78ac4ef6bdc6ae0b4958aaf6/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_second_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8d5c3d03a0374d2eba204c4550abd171?KeyID=a1aff1ca&Signature=CIlDqW%252BH%2FM8mHcv8zkjRkPNsojuL2bY5OK2y7b3WEoQ3WDUtCUBHzLf3iwvbQ%2FA9nfVd3%252BCj8UagLbF7dvuxCg%253D%253D", 
      "format": "application/msword", 
      "datePublished": "2019-01-01T00:00:00+02:00", 
      "id": "0f6e9487051944e3b7f77ee8b9469769", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_first_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0dc1ce5790c446b48316718aaece3b62?KeyID=a1aff1ca&Signature=z%252BZO52aBJQnqZ7hzJtlJ1yCHjEjC3SEA1dNNsseULLohC9QBpjDtet5vEcKbOR51aep0THokpADVTg1lK7K9Bg%253D%253D", 
      "format": "application/msword", 
      "datePublished": "2019-01-01T00:00:00+02:00", 
      "id": "dfa142dfece04ac39bd0aff1473f2095", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }
  ]
}

