PATCH /api/2.5/tenders/4cdd6b38d69c459284b31ab81cbea097/contracts/dcf3565417d44143b47ae2a316a85892?acc_token=55a1ff7e4b9c4fec90bca39c8e96fbd7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_first_document.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/af4543f4f97d411f88ea1c4c812b6bd3?KeyID=a8968c46&Signature=gmQC4dMAqr0MqvJuhfyW8RtnIKlwTVq7suusgsb6Qs6YSqv5dT6dpkzhpFk7iq7MwWcxTAIN%252BTH0Wgl4c%2FoxDQ%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "a9c2fe0cee044bda9a9520a9c83dc581", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_second_document.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/35bc340e85774e2a8c7018cd7aae1dd1?KeyID=a8968c46&Signature=y64GFO%2FAoxzyA%2FRJebVUXtSZeMTK1Fpe8NFatPd7Ofe4q5wVn%2FXSR7r1vnuboCpRujLNIc6Ewx2SAi7WPwulAw%253D%253D", 
        "format": "application/msword", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "cefd0fdccb3148c1b10ff96a07be09c1", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "items": [
      {
        "relatedLot": "1facee4c8a8742b280f9a3456f62ae41", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "New Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "futliary do derzhavnyh nagorod", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-20T09:34:10.508253+03:00", 
          "endDate": "2019-04-23T09:34:10.508253+03:00"
        }, 
        "id": "1662b0e1d59f4e2f8e2c5bd48e03a7bc", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 6.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037258", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "period": {
      "startDate": "2019-01-01T00:00:00+02:00", 
      "endDate": "2020-01-01T00:00:00+02:00"
    }, 
    "dateSigned": "2019-01-01T00:00:00+02:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-01-01T00:00:00+02:00", 
    "awardID": "2bbb5853ac2f4d47943ea6507406edf7", 
    "id": "dcf3565417d44143b47ae2a316a85892", 
    "contractID": "UA-2019-01-01-000004-2"
  }
}

