GET /api/2.5/tenders/4cdd6b38d69c459284b31ab81cbea097/contracts/dcf3565417d44143b47ae2a316a85892/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_second_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/35bc340e85774e2a8c7018cd7aae1dd1?KeyID=a8968c46&Signature=y64GFO%2FAoxzyA%2FRJebVUXtSZeMTK1Fpe8NFatPd7Ofe4q5wVn%2FXSR7r1vnuboCpRujLNIc6Ewx2SAi7WPwulAw%253D%253D", 
      "format": "application/msword", 
      "datePublished": "2019-01-01T00:00:00+02:00", 
      "id": "cefd0fdccb3148c1b10ff96a07be09c1", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_first_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/af4543f4f97d411f88ea1c4c812b6bd3?KeyID=a8968c46&Signature=gmQC4dMAqr0MqvJuhfyW8RtnIKlwTVq7suusgsb6Qs6YSqv5dT6dpkzhpFk7iq7MwWcxTAIN%252BTH0Wgl4c%2FoxDQ%253D%253D", 
      "format": "application/msword", 
      "datePublished": "2019-01-01T00:00:00+02:00", 
      "id": "a9c2fe0cee044bda9a9520a9c83dc581", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }
  ]
}

