PATCH /api/2.5/tenders/ae3adab91a6741b7b7c081c7f99632aa/contracts/da6dae5c78ac4ef6bdc6ae0b4958aaf6?acc_token=dcfda2d9335b41a9814dc01c39bd9a03 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 91
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "contractNumber": "contract #13111", 
    "value": {
      "amount": 238, 
      "amountNet": 230
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "relatedLot": "be6fe65d43f14d3d838990f21c3d2d69", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "New Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "futliary do derzhavnyh nagorod", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-20T06:49:21.606012+03:00", 
          "endDate": "2019-04-23T06:49:21.606012+03:00"
        }, 
        "id": "1662b0e1d59f4e2f8e2c5bd48e03a7bc", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 6.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037258", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-01-01T00:00:00+02:00", 
    "awardID": "459fc6df79cd4840973a2f8b81f36a07", 
    "id": "da6dae5c78ac4ef6bdc6ae0b4958aaf6", 
    "contractID": "UA-2019-01-01-000004-2"
  }
}

