PATCH /api/2.5/tenders/dfcf142d4b674c9392b10e98e3ee5060/documents/f1d5a23570df4df099a7ac7ad410c26e?acc_token=7383a672062f4576a707d8e09f6d7464 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 58
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "document description modified"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "document description modified", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f929da880f7e4d4ab8c6d26f1410f480?KeyID=a8968c46&Signature=KRFZJwFtwhg%252BXBhZhaMg07ftuLu6mATWE5PLx2mF%252BqeeBsd9z5%2FPrA5pFUlZZMxuArbqScFi0I11tYpEQYUWDg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "author": "tender_owner", 
    "documentType": "technicalSpecifications", 
    "id": "f1d5a23570df4df099a7ac7ad410c26e", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

