PUT /api/2.5/tenders/ae3adab91a6741b7b7c081c7f99632aa/documents/fd2deefb78db4ccabe071ac2c8ca630f?acc_token=dcfda2d9335b41a9814dc01c39bd9a03 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 333
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7e8816bf0f8641089bf0ca8e76f178ce?KeyID=a1aff1ca&Signature=QSk4fUN7LLL8nf7MZ3u0X6Fq2vRocKDP0gLlsG3tcERJQRq%2BOTNEpDUnuAcaQktTbBQSxqRktsDLSdx%2F%2BrvxDw%3D%3D", 
    "title": "AwardCriteria-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7e8816bf0f8641089bf0ca8e76f178ce?KeyID=a1aff1ca&Signature=xCM9ZW8ojrt53WSGkQSl%252BUUZf%2FQZzqmUeBHIJq9RJX0Py%252BlF1Rvgqvbc%2Fyq1tYvmyn3pfGh%252BpAu2woYVEjGCDQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "fd2deefb78db4ccabe071ac2c8ca630f", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

