POST /api/2.5/tenders/dfcf142d4b674c9392b10e98e3ee5060/documents?acc_token=7383a672062f4576a707d8e09f6d7464 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 329
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c100d7f0388847298ad2a9ea3280e6af?KeyID=a8968c46&Signature=f2zWM565W5GLHuaLgfr1ojCdXfjPXAhfc79YU%2BCAN0%2F1qIRz2vHmiJ2o8Ss64i19t3WecMeYxNP1JHOJk2dxDA%3D%3D", 
    "title": "AwardCriteria.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/dfcf142d4b674c9392b10e98e3ee5060/documents/fe62ca99ff8d44d0854f65a68614418d
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "AwardCriteria.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c100d7f0388847298ad2a9ea3280e6af?KeyID=a8968c46&Signature=QSQFbFh8c%252BNPAMqMD4%2FGKkkz6ErI62%252BX%2Fi%252Bwzlx%252B1LYsoTsZ2dtKYzRAPm6L5%2FXi%2F8jr4sPO0n8xJHsXx7l6Aw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "fe62ca99ff8d44d0854f65a68614418d", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

