PATCH /api/2.5/tenders/127bd59fdd464def8d1189b954eefcbb/cancellations/2c8220ea5a244315811d83251e9ff4f1?acc_token=d46e4857fb9140a1902f9cd7090bd1bb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c3a2288c77c44774b4822712296d9931?KeyID=a8968c46&Signature=WGJ1DxhP3VeRv68g8skMMff%2FZSw7MQkao5tUVEDe74IVfNyPqmohRfeUZpPA9pLqxwtKjDZiEUBiY3M%252BsRrVDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:03+03:00", 
        "id": "75159f8f408b4e7e96a5662f9e6a633f", 
        "dateModified": "2019-04-01T01:00:03+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0e87ceb7fd3640dea400a0c5a713eb69?KeyID=a8968c46&Signature=eTBb4Jm8c43q125PhhZIHF0UeaaYLR40KLdh9tsk92zC65lHFC%2F%252BVkGIa%252ByfsDKbDA6gkx6f9OuPO5OW%2FNuxDg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:03+03:00", 
        "id": "75159f8f408b4e7e96a5662f9e6a633f", 
        "dateModified": "2019-04-01T01:00:03+03:00"
      }
    ], 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-04-01T01:00:03+03:00", 
    "cancellationOf": "tender", 
    "id": "2c8220ea5a244315811d83251e9ff4f1"
  }
}

