POST /api/2.5/tenders/12de7035f98f441388cc86e2a6086c64/awards/cc92f7a9fc3a478ba2aab6489c7dc51e/complaints?acc_token=f205b69bfc854e9e85c765da43dbbf06 HTTP/1.0
Authorization: Bearer broker
Content-Length: 1319
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "pending", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }, 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/12de7035f98f441388cc86e2a6086c64/awards/cc92f7a9fc3a478ba2aab6489c7dc51e/complaints/3a4c0ae08568432aa92664c32a5ee4ca
{
  "access": {
    "transfer": "ba0af1bd3b844a34bae6e9ad15dfac4a", 
    "token": "05eed15c65254d9d9d66fb94af245d84"
  }, 
  "data": {
    "status": "pending", 
    "transfer_token": "1fa2e584aff44613a188c05ebef18c303b9f58d48d5a42643c5539f6b6beef5bf1c514fefbbd07f8b31bf31ace2382fd59ae71f4fe64fe545a5110bc81352dba", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2019-10-01T01:00:01+03:00", 
    "complaintID": "UA-2019-10-01-000001.2", 
    "date": "2019-10-01T01:00:01+03:00", 
    "type": "complaint", 
    "id": "3a4c0ae08568432aa92664c32a5ee4ca", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс."
  }
}

