GET /api/2.5/tenders/127bd59fdd464def8d1189b954eefcbb/documents/1d597c57dc434114b163cd1d42b6f7b1?acc_token=78250e99c9974266933e656d51b30048 HTTP/1.0
Authorization: Bearer broker
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ee7828a657034226bbf1d5b06160cd27?KeyID=a8968c46&Signature=P9feWIlpkmVaVer5MrUILg6wUqIrp5Ay0zy%2FlE9SULubBMBrTAvW8ocd5Jko%2F21PFnWlo%252Bgm30ykrvQu7YcdCg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-10-01T01:00:00+03:00", 
    "previousVersions": [], 
    "id": "1d597c57dc434114b163cd1d42b6f7b1", 
    "dateModified": "2019-10-01T01:00:00+03:00"
  }
}

