PUT /api/2.5/tenders/127bd59fdd464def8d1189b954eefcbb/cancellations/2c8220ea5a244315811d83251e9ff4f1/documents/75159f8f408b4e7e96a5662f9e6a633f?acc_token=d46e4857fb9140a1902f9cd7090bd1bb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 139
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Notice-2.pdf"
Content-Type: application/pdf

content2
--BOUNDARY--


Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice-2.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0e87ceb7fd3640dea400a0c5a713eb69?KeyID=a8968c46&Signature=eTBb4Jm8c43q125PhhZIHF0UeaaYLR40KLdh9tsk92zC65lHFC%2F%252BVkGIa%252ByfsDKbDA6gkx6f9OuPO5OW%2FNuxDg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:03+03:00", 
    "id": "75159f8f408b4e7e96a5662f9e6a633f", 
    "dateModified": "2019-04-01T01:00:03+03:00"
  }
}

