POST /api/2.5/tenders/127bd59fdd464def8d1189b954eefcbb/bids/0fa7c814dd0e42e3b1f8b4f2623ab07d/documents?acc_token=d2f6e6c8a7a54d2cb138ef2ef5de765a HTTP/1.0
Authorization: Bearer broker
Content-Length: 144
Content-Type: multipart/form-data; boundary=---BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
-----BOUNDARY
Content-Disposition: form-data; name="file"; filename="Proposal.pdf"
Content-Type: application/pdf

content
-----BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/127bd59fdd464def8d1189b954eefcbb/bids/0fa7c814dd0e42e3b1f8b4f2623ab07d/documents/49ae93cd55a94d2c83a32fa49434277a
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "Proposal.pdf", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/127bd59fdd464def8d1189b954eefcbb/bids/0fa7c814dd0e42e3b1f8b4f2623ab07d/documents/49ae93cd55a94d2c83a32fa49434277a?download=e688a3d01c724b60b7d6f52bb8a354b0", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-10-01T01:00:01+03:00", 
    "id": "49ae93cd55a94d2c83a32fa49434277a", 
    "dateModified": "2019-10-01T01:00:01+03:00"
  }
}

