PATCH /api/2.5/tenders/23fc3b938f5d4c309f682dabc068667a/complaints/7dfbcf5c7d7e45bab929bab9b37b8723?acc_token=a8494c00b8f04cad831330e32ed3b637 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 228
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "stopping", 
    "cancellationReason": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "stopping", 
    "transfer_token": "4d7999c7cde22eb73b32556fecbd4a0fffec5576281e5f6d11da8ef3f638803ef9988b59e350f76084a11a27de72eb12e0e64ddb50d2bb417a44d4fe1e38bb98", 
    "title": "Недостатньо інформації", 
    "acceptance": true, 
    "cancellationReason": "Тендер скасовується замовником", 
    "dateCanceled": "2019-04-01T01:00:01+03:00", 
    "dateAccepted": "2019-04-01T01:00:01+03:00", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2019-04-01T01:00:01+03:00", 
    "complaintID": "UA-2019-04-01-000001.6", 
    "date": "2019-04-01T01:00:01+03:00", 
    "type": "complaint", 
    "id": "7dfbcf5c7d7e45bab929bab9b37b8723", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс."
  }
}

