POST /api/2.5/tenders/5133e89c95af4bea9a9c805c6e02f950/qualifications/7062a8144cf74f999eff42e04151db9b/complaints/2c1728b7a8854d37a7b701160f6e5564/documents?acc_token=8dff1e7646c14b24ab007f76a849ef02 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 151
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/5133e89c95af4bea9a9c805c6e02f950/qualifications/7062a8144cf74f999eff42e04151db9b/complaints/2c1728b7a8854d37a7b701160f6e5564/documents/239c700e025f4021b61da13c49a045c4
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/84adc90ce6e741a4abe11979ed9381dc?KeyID=a8968c46&Signature=R8wcASyfa0ZGrqMyggygw2yFq9Qot93nxKDktXRSnVwZYBD1VMZ6qU0R7IwkPIDr3yjzapvuaSYmVv1wy705CA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:03+03:00", 
    "id": "239c700e025f4021b61da13c49a045c4", 
    "dateModified": "2019-04-01T01:00:03+03:00"
  }
}

