GET /api/2.5/tenders/35f93e8dd5484abb8b90687952c82010/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c459610809404e05bf4745675221c93c?KeyID=a8968c46&Signature=QVOeVblTrt8gGyXf9gMk9Fo3lpMBD%252BEVxt7tiahcZif9e2aB5DOPF44zjUI2I8bSqLgU3Y7RISmig41XeBUTDg%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "1c2f807ab6db47498bf9096ff1b1f81e", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1f9c47abfab3467e8cb930908a169ed5?KeyID=a8968c46&Signature=3WnYnjsDu8ikjYUnGOwuewjGOKRufZ3KH89s3SwkfHndq2kV%252BNw3CP1La8VP8szZbghLMubHUjxPhROOhG%252BKDw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "571cc7e521f64b6b95fe308416cd83f9", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }
  ]
}

