GET /api/2.5/tenders/69b2e0ceffcf46899710d0fbbca43d16/agreements/90a23cd9a0ba47079f799787ed23e53d/contracts?acc_token=94c3cae73f8a42dd8e34733966513d31 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "unitPrices": [
        {
          "value": {
            "currency": "UAH", 
            "valueAddedTaxIncluded": true
          }, 
          "relatedItem": "c02b11e2bb654c169699d7e28341a753"
        }, 
        {
          "value": {
            "currency": "UAH", 
            "valueAddedTaxIncluded": true
          }, 
          "relatedItem": "a0bde9d4798c4f1aaf63dee3ea8d1ffc"
        }
      ], 
      "suppliers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137227", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "bidID": "f30029f85828476b9933ec082f123e69", 
      "date": "2019-01-01T00:00:00+02:00", 
      "awardID": "ef3d119d596d4832a0b13f17c01a9553", 
      "id": "05b696860290436289631a8f9ce7b352"
    }, 
    {
      "status": "active", 
      "unitPrices": [
        {
          "value": {
            "currency": "UAH", 
            "valueAddedTaxIncluded": true
          }, 
          "relatedItem": "c02b11e2bb654c169699d7e28341a753"
        }, 
        {
          "value": {
            "currency": "UAH", 
            "valueAddedTaxIncluded": true
          }, 
          "relatedItem": "a0bde9d4798c4f1aaf63dee3ea8d1ffc"
        }
      ], 
      "suppliers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "bidID": "d0bae9fc4c104aaf870a44b6181547f4", 
      "date": "2019-01-01T00:00:00+02:00", 
      "awardID": "e61ac71cb2cf4e36948e6d65943b4b26", 
      "id": "97baaa9f55f04467a3a283c8bec11849"
    }, 
    {
      "status": "active", 
      "unitPrices": [
        {
          "value": {
            "currency": "UAH", 
            "valueAddedTaxIncluded": true
          }, 
          "relatedItem": "c02b11e2bb654c169699d7e28341a753"
        }, 
        {
          "value": {
            "currency": "UAH", 
            "valueAddedTaxIncluded": true
          }, 
          "relatedItem": "a0bde9d4798c4f1aaf63dee3ea8d1ffc"
        }
      ], 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bidID": "072db6b8dba749d9bd50c5e1dc33459a", 
      "date": "2019-01-01T00:00:00+02:00", 
      "awardID": "0c09750bc38142fe999fc03ab5c0f30c", 
      "id": "12970ffe75e14e579679c3da6ef34584"
    }
  ]
}

