PATCH /api/2.5/tenders/edf1ec35dd2442928d2473f51384621f/agreements/b75fa2d9a34149bb92d0434eb71b7968/contracts/05a0c07f90fc4198a54c85d4265deb40?acc_token=cbe41c0fba54453ea52434ea6c0e1867 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 184
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "unitPrices": [
      {
        "value": {
          "amount": 0.5
        }, 
        "relatedItem": "90759460567841e0aacf5d7c20c47baf"
      }, 
      {
        "value": {
          "amount": 0.5
        }, 
        "relatedItem": "2846075b9a7c45d7a6ba8384aabe5f37"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "unitPrices": [
      {
        "value": {
          "currency": "UAH", 
          "amount": 0.5, 
          "valueAddedTaxIncluded": true
        }, 
        "relatedItem": "90759460567841e0aacf5d7c20c47baf"
      }, 
      {
        "value": {
          "currency": "UAH", 
          "amount": 0.5, 
          "valueAddedTaxIncluded": true
        }, 
        "relatedItem": "2846075b9a7c45d7a6ba8384aabe5f37"
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bidID": "b4589ca9eb684602b65a37e136f22c04", 
    "date": "2019-03-28T06:48:01.541665+02:00", 
    "awardID": "8328c443e83c49f6b0cf6c1597da0f10", 
    "id": "05a0c07f90fc4198a54c85d4265deb40"
  }
}

