PATCH /api/2.5/tenders/eeda351577cb475894b560d00bb57c20/agreements/9c9b9267b5f045c5898d6d4ae2ba3855/contracts/0f601a4a29704b72a84a77f5fac2c0ed?acc_token=084aca35cabe4d629dd5a4fbe8b47c05 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 184
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "unitPrices": [
      {
        "value": {
          "amount": 0.5
        }, 
        "relatedItem": "cfa79c4a7e2041d3812508870da99986"
      }, 
      {
        "value": {
          "amount": 0.5
        }, 
        "relatedItem": "0dc90ed37b0446b5b48e9695a5ef4a73"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "unitPrices": [
      {
        "value": {
          "currency": "UAH", 
          "amount": 0.5, 
          "valueAddedTaxIncluded": true
        }, 
        "relatedItem": "cfa79c4a7e2041d3812508870da99986"
      }, 
      {
        "value": {
          "currency": "UAH", 
          "amount": 0.5, 
          "valueAddedTaxIncluded": true
        }, 
        "relatedItem": "0dc90ed37b0446b5b48e9695a5ef4a73"
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "bidID": "19d5bd6c111c4b8d8fd79bc5c0ba6f6a", 
    "date": "2019-04-01T01:00:00+03:00", 
    "awardID": "adb090daca2d4a559a1edfb75e583e59", 
    "id": "0f601a4a29704b72a84a77f5fac2c0ed"
  }
}

