PATCH /api/2.5/tenders/eeda351577cb475894b560d00bb57c20/qualifications/141f0e0a9b7b492581a70296895a114c?acc_token=084aca35cabe4d629dd5a4fbe8b47c05 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "lotID": "f074dc96c19a4b2ab186871f70f47fd9", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "3cb5698d987f4fc7a12c4fe9b19637e3", 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "141f0e0a9b7b492581a70296895a114c"
  }
}

