PATCH /api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/qualifications/dd52d961a4ab42d6a4f91f1391d048c7?acc_token=4fedc6c367a94e00ac51cd25b92bb6f8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "lotID": "94215f9e744a4046a0730758942e2a9e", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "7ded07f482ac44dd815b1cd075d9b64c", 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "dd52d961a4ab42d6a4f91f1391d048c7"
  }
}

