PATCH /api/2.5/tenders/eeda351577cb475894b560d00bb57c20/qualifications/0142b47468e64590b1d327a1be5a01fa?acc_token=084aca35cabe4d629dd5a4fbe8b47c05 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "lotID": "f074dc96c19a4b2ab186871f70f47fd9", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "19d5bd6c111c4b8d8fd79bc5c0ba6f6a", 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "0142b47468e64590b1d327a1be5a01fa"
  }
}

