GET /api/2.5/tenders/c2be6cc98391434da02ceb5260928191/awards/b3ea07978dfa4489a4143af66ef6d18b/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "relatedLot": "2e6f1f49c8894974a1c36e2b463b5b86", 
      "status": "satisfied", 
      "dateDecision": "2019-03-28T06:47:46.841978+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/d048801338f640faadb38d04b87f2dcd?KeyID=25f399ce&Signature=KKzUjUNmCO3R7m6sqIxDY9VqQQbcQC6iMDYiCEVGxrqPGsZtvY%252Bp7gcvWrmNvLEhvUPxrDoS3RiQbi2jPH55AQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:47:43.727861+02:00", 
          "id": "1af38b18fa754368a132b95e2902f57d", 
          "dateModified": "2019-03-28T06:47:43.727890+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/da9d5773d0944fd59347b861340e0821?KeyID=25f399ce&Signature=FqE1m39kxYjYXzLLF6f16zB1lJP%2FCLpU%252Bl4oVa8ifzgYFVc87rwciqfAm8m%2FWgZuHUDCyw3jZammVpWeQpJODA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:47:46.678729+02:00", 
          "id": "09a0c358579c40c2ae0c2c3643cd377d", 
          "dateModified": "2019-03-28T06:47:46.678748+02:00"
        }
      ], 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "dateAccepted": "2019-03-28T06:47:45.939996+02:00", 
      "dateSubmitted": "2019-03-28T06:47:43.849036+02:00", 
      "complaintID": "UA-2019-03-28-000001.1", 
      "date": "2019-03-28T06:47:46.850823+02:00", 
      "acceptance": true, 
      "type": "complaint", 
      "id": "2a3afee011924c8fb39f5459cad480de"
    }, 
    {
      "relatedLot": "2e6f1f49c8894974a1c36e2b463b5b86", 
      "status": "invalid", 
      "dateDecision": "2019-03-28T06:47:45.755127+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2019-03-28T06:47:43.981165+02:00", 
      "complaintID": "UA-2019-03-28-000001.2", 
      "date": "2019-03-28T06:47:45.763978+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "d474217279504e6fbc255c1dbec675ec"
    }, 
    {
      "relatedLot": "2e6f1f49c8894974a1c36e2b463b5b86", 
      "status": "declined", 
      "dateDecision": "2019-03-28T06:47:46.992268+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2019-03-28T06:47:46.105021+02:00", 
      "dateSubmitted": "2019-03-28T06:47:44.143346+02:00", 
      "complaintID": "UA-2019-03-28-000001.3", 
      "date": "2019-03-28T06:47:47.001166+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "9e92cba0e6434a07a27647cf84dbfe5a"
    }, 
    {
      "relatedLot": "2e6f1f49c8894974a1c36e2b463b5b86", 
      "status": "accepted", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "acceptance": true, 
      "dateAccepted": "2019-03-28T06:47:46.320879+02:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-03-28T06:47:44.262641+02:00", 
      "complaintID": "UA-2019-03-28-000001.4", 
      "date": "2019-03-28T06:47:46.332330+02:00", 
      "type": "complaint", 
      "id": "61433581ec0d40af962b6a511776df6b"
    }, 
    {
      "relatedLot": "2e6f1f49c8894974a1c36e2b463b5b86", 
      "status": "stopped", 
      "dateDecision": "2019-03-28T06:47:47.190535+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2019-03-28T06:47:47.190558+02:00", 
      "dateAccepted": "2019-03-28T06:47:46.529160+02:00", 
      "dateSubmitted": "2019-03-28T06:47:44.377054+02:00", 
      "complaintID": "UA-2019-03-28-000001.5", 
      "date": "2019-03-28T06:47:47.201576+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "4e3754a233374ec5855cd32147754374"
    }, 
    {
      "relatedLot": "2e6f1f49c8894974a1c36e2b463b5b86", 
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "resolutionType": "resolved", 
      "type": "claim", 
      "title": "Недостатньо інформації", 
      "satisfied": true, 
      "dateAnswered": "2019-03-28T06:47:44.633421+02:00", 
      "dateSubmitted": "2019-03-28T06:47:44.498840+02:00", 
      "complaintID": "UA-2019-03-28-000001.6", 
      "date": "2019-03-28T06:47:44.642883+02:00", 
      "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
      "id": "454d0d1397744bafb129654345ad9617"
    }, 
    {
      "relatedLot": "2e6f1f49c8894974a1c36e2b463b5b86", 
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "resolutionType": "invalid", 
      "type": "claim", 
      "title": "Недостатньо інформації", 
      "satisfied": false, 
      "dateAnswered": "2019-03-28T06:47:45.093813+02:00", 
      "dateSubmitted": "2019-03-28T06:47:44.942641+02:00", 
      "complaintID": "UA-2019-03-28-000001.7", 
      "date": "2019-03-28T06:47:45.108516+02:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "61fcc41460fd45d6a60df6c22f3aec66"
    }, 
    {
      "relatedLot": "2e6f1f49c8894974a1c36e2b463b5b86", 
      "status": "claim", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-03-28T06:47:45.608844+02:00", 
      "complaintID": "UA-2019-03-28-000001.8", 
      "date": "2019-03-28T06:47:45.618225+02:00", 
      "type": "claim", 
      "id": "b97831f5a5ba47b1943ecabd5221f780"
    }
  ]
}

