GET /api/2.5/tenders/bcd53594a1a245cdbecf00f8aa09cc36/awards/06d30f82e6b94bdfa1580f01aadfd48b/complaints/715e24d936174f29a289414ea9a60ea5 HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "e805ca07bcfd4410a873ceff155e669f", 
    "status": "satisfied", 
    "dateDecision": "2019-01-01T00:10:00+02:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7d62b510cbb54ec98b6096a0ba5d471b?KeyID=a8968c46&Signature=r0kBT1yfdxjOMg%2FNCToB4HtI7o8IgHbuq2q77Cj9l6PEup5Z1Ltzt1CYQTt0v7xK1v8NOOZF75GtKKGT0rZXDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:10:00+02:00", 
        "id": "f2e1ee3b805d451a807e97e0be99253b", 
        "dateModified": "2019-01-01T00:10:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/2e652ec2372741f6a1ca2251c8bb1ef4?KeyID=a8968c46&Signature=fJkZXw41uRNCcbc7b5jWzbUupozMCZo7ay5ZF5WYObAd9TkDt6oFdorAzwex%252B59Y6Y%252BEHiQ6P4HKw0ztWNAiDg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:10:00+02:00", 
        "id": "38addc149e964b0eb464b428ed07af32", 
        "dateModified": "2019-01-01T00:10:00+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "dateAccepted": "2019-01-01T00:10:00+02:00", 
    "dateSubmitted": "2019-01-01T00:10:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.1", 
    "date": "2019-01-01T00:10:00+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "715e24d936174f29a289414ea9a60ea5"
  }
}

