PATCH /api/2.5/tenders/7b005fa4dbfc44f588d4b10b52c9d64f/awards/89a7ba79e27c4a1e8c7a88dbb8959661/complaints/3db97a9828bb44a58587e44937703f0a?acc_token=ccf1523080b840a39830c79988f180cb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "satisfied": false
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "98be3ab3e0504351a55c9391a9e1a061", 
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "invalid", 
    "type": "claim", 
    "title": "Недостатньо інформації", 
    "satisfied": false, 
    "dateAnswered": "2019-04-01T01:00:01+03:00", 
    "dateSubmitted": "2019-04-01T01:00:01+03:00", 
    "complaintID": "UA-2019-04-01-000001.7", 
    "date": "2019-04-01T01:00:01+03:00", 
    "resolution": "Вимога не відповідає предмету закупівлі", 
    "id": "3db97a9828bb44a58587e44937703f0a"
  }
}

