POST /api/2.5/tenders/bcd53594a1a245cdbecf00f8aa09cc36/awards/06d30f82e6b94bdfa1580f01aadfd48b/complaints/715e24d936174f29a289414ea9a60ea5/documents?acc_token=a7ca0a2f2ac24c40bcdf63064ab9ee2d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 201
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy340393534728$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/bcd53594a1a245cdbecf00f8aa09cc36/awards/06d30f82e6b94bdfa1580f01aadfd48b/complaints/715e24d936174f29a289414ea9a60ea5/documents/f2e1ee3b805d451a807e97e0be99253b
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7d62b510cbb54ec98b6096a0ba5d471b?KeyID=a8968c46&Signature=r0kBT1yfdxjOMg%2FNCToB4HtI7o8IgHbuq2q77Cj9l6PEup5Z1Ltzt1CYQTt0v7xK1v8NOOZF75GtKKGT0rZXDQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "f2e1ee3b805d451a807e97e0be99253b", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

