POST /api/2.5/tenders/7b005fa4dbfc44f588d4b10b52c9d64f/awards/89a7ba79e27c4a1e8c7a88dbb8959661/complaints/2fd245ad97014eda9dbb95fe2949f4b0/documents?acc_token=a9ad2d8080d340e8841948a58cb1d112 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 151
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/7b005fa4dbfc44f588d4b10b52c9d64f/awards/89a7ba79e27c4a1e8c7a88dbb8959661/complaints/2fd245ad97014eda9dbb95fe2949f4b0/documents/093fdefce74f4837aa2650a4edf773f6
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ab6be0be2e0c468994ddfd65c81cc5c3?KeyID=a8968c46&Signature=SwvV1e6UjSUUUIPMSl%2Famc%2FZjOOkmD%2FPD3TvAxtnsQ2ntTrj1ttC7y4tDkoBBzhOYdfCLHOWwkF5xOel73qGBA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:01+03:00", 
    "id": "093fdefce74f4837aa2650a4edf773f6", 
    "dateModified": "2019-04-01T01:00:01+03:00"
  }
}

