PATCH /api/2.5/tenders/2fa83d3442ba4956a2f5bcde852d7d32/awards/d74cc31f7f69485eb30dca7e2ef452ba/complaints/8192a2dee0e646678cc4ff0c7054d7dd HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "accepted"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
    "status": "accepted", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d5014d0356bb4efb9ca9a57efa85309e?KeyID=e8294d53&Signature=rf3P4lV1kSurZR3pk3H%2Fo8Fp%252BCwf87a315HK6zznQnMFSh1nDU9JvWb%252Bd7bXOhOr%252BCprMaq52yOu7tYSnc%252BQCQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:10:00+02:00", 
        "id": "9ec781facce34d5b98bbf726af3684dd", 
        "dateModified": "2019-01-01T00:10:00+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2019-01-01T00:10:00+02:00", 
    "dateSubmitted": "2019-01-01T00:10:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.1", 
    "date": "2019-01-01T00:10:00+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "8192a2dee0e646678cc4ff0c7054d7dd"
  }
}

