PATCH /api/2.5/tenders/7b005fa4dbfc44f588d4b10b52c9d64f/awards/89a7ba79e27c4a1e8c7a88dbb8959661/complaints/cfd66d61f8e8478996486b8cc232d035?acc_token=67228510eb684717839f23f61a218659 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 387
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "98be3ab3e0504351a55c9391a9e1a061", 
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "resolved", 
    "type": "claim", 
    "title": "Недостатньо інформації", 
    "dateAnswered": "2019-04-01T01:10:00+03:00", 
    "dateSubmitted": "2019-04-01T01:10:00+03:00", 
    "complaintID": "UA-2019-04-01-000001.6", 
    "date": "2019-04-01T01:10:00+03:00", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
    "id": "cfd66d61f8e8478996486b8cc232d035"
  }
}

