PATCH /api/2.5/tenders/2fa83d3442ba4956a2f5bcde852d7d32/awards/d74cc31f7f69485eb30dca7e2ef452ba/complaints/7c035de77e40423c88ddc73ec0ddbce6?acc_token=abfa11c037d1420cb1a4c348f34eb4bd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "claim"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
    "status": "claim", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2019-01-01T00:10:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.8", 
    "date": "2019-01-01T00:10:00+02:00", 
    "type": "claim", 
    "id": "7c035de77e40423c88ddc73ec0ddbce6"
  }
}

