POST /api/2.5/tenders/2fa83d3442ba4956a2f5bcde852d7d32/awards/d74cc31f7f69485eb30dca7e2ef452ba/complaints/8192a2dee0e646678cc4ff0c7054d7dd/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 197
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy82886074556$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2fa83d3442ba4956a2f5bcde852d7d32/awards/d74cc31f7f69485eb30dca7e2ef452ba/complaints/8192a2dee0e646678cc4ff0c7054d7dd/documents/96ac589622df4dba903659796ee33831
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/13359927f86e4454baeb46dd6bcc2002?KeyID=e8294d53&Signature=D3%252B6rkzAkDOMaPFJs1E6kvNDYIooDKilPMNCWodOQ%2F1qvv5RNC%2F1r%252BxgLUf0Mq%252BacToQTkcD2jNSnJvLWuziCw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "96ac589622df4dba903659796ee33831", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

