GET /api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/bids/a21960990261432faab44db6275676d5?acc_token=0e870fadbea7429aaec0ca006ff3f959 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "474a13302d414c40b95a16f154cdd263", 
        "date": "2019-04-01T01:00:00+03:00", 
        "status": "active", 
        "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/239ab2b4b65a46f8ac603eebcd77771c_474a13302d414c40b95a16f154cdd263?key_for_bid=a21960990261432faab44db6275676d5", 
        "value": {
          "currency": "UAH", 
          "amount": 499, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "a21960990261432faab44db6275676d5"
  }
}

