GET /api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/bids/6eb4f1ad6ddf4998bec6805fae37e912?acc_token=70459bce567241528f0aee386cc83d0c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/a634bd9ba5fe4d01bd0df27a33871f18?KeyID=a4ab2441&Signature=Eg9TDcxWIa8LTFPzQg8OpjWgfwIKviqXiH083N%2F8YftA3m9HuAi9IYryMTf4GVTcXxc5LPWZzqZmiJdFt1OzBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:57.444447+02:00", 
        "id": "51d997de6f814556b28d1f9372906c8c", 
        "dateModified": "2019-03-18T09:26:57.444460+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/bids/6eb4f1ad6ddf4998bec6805fae37e912/documents/dbcf34cf616c47159ccc2fa2774be7cd?download=d1f16eeae4804114a63bd765678b5586", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_top_secrets.pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:57.502415+02:00", 
        "id": "dbcf34cf616c47159ccc2fa2774be7cd", 
        "dateModified": "2019-03-18T09:26:57.502428+02:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/57df759e0d2d4263b5e38887fbef2351?KeyID=a4ab2441&Signature=F1u1NiwuUK22WVntttihahY30r1jpRjMcFcHRVwZ%252Bk29c%252B8%2FDbT7I%252Bgms77MT72s8E66CpsMMErykT5xhplMAQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:57.829135+02:00", 
        "id": "730874684aa94bcd8b28af299e8a1300", 
        "dateModified": "2019-03-18T09:26:57.829148+02:00"
      }
    ], 
    "selfEligible": true, 
    "id": "6eb4f1ad6ddf4998bec6805fae37e912", 
    "lotValues": [
      {
        "relatedLot": "0ba62781d4414b1c9736434c0c1e1e9e", 
        "date": "2019-03-18T09:26:57.326536+02:00", 
        "status": "active", 
        "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/a27a2edadf6a442eb7f17020c7d789fd_0ba62781d4414b1c9736434c0c1e1e9e?key_for_bid=6eb4f1ad6ddf4998bec6805fae37e912", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/bids/6eb4f1ad6ddf4998bec6805fae37e912/financial_documents/b772bcba6458480aae1e6e3085684306?download=e4c83026c8e649d2aff545652893175a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:57.644265+02:00", 
        "id": "b772bcba6458480aae1e6e3085684306", 
        "dateModified": "2019-03-18T09:26:57.644278+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/bids/6eb4f1ad6ddf4998bec6805fae37e912/financial_documents/c3a1b182e9c044a9879628b87c75c5ae?download=73cc85541ad6433f807151a25ff6f7f5", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:57.704654+02:00", 
        "id": "c3a1b182e9c044a9879628b87c75c5ae", 
        "dateModified": "2019-03-18T09:26:57.704667+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-03-18T09:26:57.326322+02:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/bids/6eb4f1ad6ddf4998bec6805fae37e912/qualification_documents/7d160141a29f407eb91bebffedd881de?download=652c4516fd994e26a3255a7cfb3e6b8a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:57.920016+02:00", 
        "id": "7d160141a29f407eb91bebffedd881de", 
        "dateModified": "2019-03-18T09:26:57.920030+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/bids/6eb4f1ad6ddf4998bec6805fae37e912/qualification_documents/7d160141a29f407eb91bebffedd881de?download=19d8b82017214688b1e2a981c134841c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:57.920016+02:00", 
        "id": "7d160141a29f407eb91bebffedd881de", 
        "dateModified": "2019-03-18T09:26:57.990385+02:00"
      }
    ]
  }
}

