PATCH /api/2.5/tenders/edf1ec35dd2442928d2473f51384621f/bids/b4589ca9eb684602b65a37e136f22c04?acc_token=111a5f976f3847669922c1dee355c4ad HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/edf1ec35dd2442928d2473f51384621f/bids/b4589ca9eb684602b65a37e136f22c04/documents/2e81f311abc24c6eb2899f5e5b834752?download=2cdaabebb0f5408d8fa35a79096ed032", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:47:55.496997+02:00", 
        "id": "2e81f311abc24c6eb2899f5e5b834752", 
        "dateModified": "2019-03-28T06:47:55.497015+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/edf1ec35dd2442928d2473f51384621f/bids/b4589ca9eb684602b65a37e136f22c04/documents/2710393ef8154373a06c3fae809bd875?download=55b2e8c8f6dd42899c94536961e852ee", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_top_secrets.pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:47:55.573145+02:00", 
        "id": "2710393ef8154373a06c3fae809bd875", 
        "dateModified": "2019-03-28T06:47:55.573162+02:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/edf1ec35dd2442928d2473f51384621f/bids/b4589ca9eb684602b65a37e136f22c04/eligibility_documents/5d1800dde28a4693aa0424a7bfbd132c?download=a5cb631e4d0247f98b1da6d0e822cde7", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:47:55.976609+02:00", 
        "id": "5d1800dde28a4693aa0424a7bfbd132c", 
        "dateModified": "2019-03-28T06:47:55.976623+02:00"
      }
    ], 
    "selfEligible": true, 
    "id": "b4589ca9eb684602b65a37e136f22c04", 
    "lotValues": [
      {
        "relatedLot": "2e6f1f49c8894974a1c36e2b463b5b86", 
        "date": "2019-03-28T06:47:55.344733+02:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/edf1ec35dd2442928d2473f51384621f/bids/b4589ca9eb684602b65a37e136f22c04/financial_documents/bf358f6886fd4a66aeda2142bd5684cf?download=9034f5db7d454a8aa7a21542f305e5c0", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:47:55.802004+02:00", 
        "id": "bf358f6886fd4a66aeda2142bd5684cf", 
        "dateModified": "2019-03-28T06:47:55.802022+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/edf1ec35dd2442928d2473f51384621f/bids/b4589ca9eb684602b65a37e136f22c04/financial_documents/8a23a5550a974f93ab7077bb65e347f3?download=baebc5ad69644d20b01d0432e5c27ff4", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:47:55.879196+02:00", 
        "id": "8a23a5550a974f93ab7077bb65e347f3", 
        "dateModified": "2019-03-28T06:47:55.879212+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-03-28T06:47:55.344493+02:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/edf1ec35dd2442928d2473f51384621f/bids/b4589ca9eb684602b65a37e136f22c04/qualification_documents/b953d1dbe97940ba927d8b49eec02f45?download=a0feb97aa4254734ad6e0d339dae17e3", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:47:56.049207+02:00", 
        "id": "b953d1dbe97940ba927d8b49eec02f45", 
        "dateModified": "2019-03-28T06:47:56.049220+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/edf1ec35dd2442928d2473f51384621f/bids/b4589ca9eb684602b65a37e136f22c04/qualification_documents/b953d1dbe97940ba927d8b49eec02f45?download=f3073339d8a641f98acdb212750c0630", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:47:56.049207+02:00", 
        "id": "b953d1dbe97940ba927d8b49eec02f45", 
        "dateModified": "2019-03-28T06:47:56.119835+02:00"
      }
    ]
  }
}

