GET /api/2.5/tenders/69b2e0ceffcf46899710d0fbbca43d16/bids/072db6b8dba749d9bd50c5e1dc33459a/documents?acc_token=8414238c4de84d7b87421cd7f690a5cf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "confidentiality": "public", 
      "language": "uk", 
      "title": "Proposal.pdf", 
      "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/69b2e0ceffcf46899710d0fbbca43d16/bids/072db6b8dba749d9bd50c5e1dc33459a/documents/1dc33db237484680a7928c5d9dedb457?download=4836fc52400b4d60b5479a9493221ccb", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-01-01T00:00:00+02:00", 
      "id": "1dc33db237484680a7928c5d9dedb457", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "confidentiality": "buyerOnly", 
      "language": "uk", 
      "format": "application/pdf", 
      "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/69b2e0ceffcf46899710d0fbbca43d16/bids/072db6b8dba749d9bd50c5e1dc33459a/documents/7b8d0d296c0040b6aec5edd7688c4909?download=5eb512959ef14c1fa5444e6622cb5c5d", 
      "confidentialityRationale": "Only our company sells badgers with pink hair.", 
      "title": "Proposal_top_secrets.pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-01-01T00:00:00+02:00", 
      "id": "7b8d0d296c0040b6aec5edd7688c4909", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }
  ]
}

