GET /api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/bids/7ded07f482ac44dd815b1cd075d9b64c?acc_token=8482745c7ed0486f9c0f825d27383197 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/bb2f2b5318734ba1bdce7853d52a665a?KeyID=a8968c46&Signature=5ajLW%252By6FoWWR229UvY%2F%2FUD8bye%2FczwbWTIsOWjGaaVwvoOXyfRRyBs%2FQqJcPPwxXMENmAdWxN1GGR0BuIe2Aw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "77bcfb8cdd424beab7904abef6a8411b", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/bids/7ded07f482ac44dd815b1cd075d9b64c/documents/c5be635ac53d4272a9bf13d7c0c0555f?download=509bc518046140c7b461b5c7d424daca", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "c5be635ac53d4272a9bf13d7c0c0555f", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1b391d4d74d44b309b5d6c27c088548f?KeyID=a8968c46&Signature=AzWR6IGwKaiz5ddYRJFmA93Q7jDZxAVIq84oU8g%252BwcU8rNHNHIOQICbLScqu4V7E7TiVR6sLUVE4%2FMb7xc5OBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "5d4b6cf8b5e74e93a90e5091a42070f4", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "7ded07f482ac44dd815b1cd075d9b64c", 
    "lotValues": [
      {
        "relatedLot": "474a13302d414c40b95a16f154cdd263", 
        "date": "2019-04-01T01:00:00+03:00", 
        "status": "active", 
        "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/239ab2b4b65a46f8ac603eebcd77771c_474a13302d414c40b95a16f154cdd263?key_for_bid=7ded07f482ac44dd815b1cd075d9b64c", 
        "value": {
          "currency": "UAH", 
          "amount": 5, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/bids/7ded07f482ac44dd815b1cd075d9b64c/financial_documents/85b1a0638950449a9a6ea60fc0033a9e?download=3f7196a9fbb244e188afee5a41db34af", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "85b1a0638950449a9a6ea60fc0033a9e", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "scale": "mid", 
        "name": "«Снігур»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137227", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 35", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-04-01T01:00:00+03:00", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/bids/7ded07f482ac44dd815b1cd075d9b64c/qualification_documents/0768edcb5d294b85af4c66a27e6a2a31?download=b1fbabd03d7a4287acb65642d8d858f5", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "0768edcb5d294b85af4c66a27e6a2a31", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ]
  }
}

