POST /api/2.5/tenders/34170fd3a6a0456aa6ce2cbfe4a4fb9b/complaints/7034302b057d4b55a499b37052d52fd9/documents?acc_token=dc9913bd7e104b7e9601b32a0dff7a60 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 151
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/34170fd3a6a0456aa6ce2cbfe4a4fb9b/complaints/7034302b057d4b55a499b37052d52fd9/documents/18ae1737060b4d1aa3fed92069ffeda1
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4f63471c92b14e36b2ddc56b8169a94a?KeyID=a8968c46&Signature=NxRar6arcge6kng4%252B1FcYzQ9T%252BHPETqOvaMCXP%252B1I8THVCtPx91TLtuSTjL249fup0jL0WjRrvgAY6eoqjGOAg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "18ae1737060b4d1aa3fed92069ffeda1", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

