PATCH /api/2.5/tenders/08f7eadd1d344575b11f8b60e29cfd66/complaints/b8f302d183b74365900464f12d55465c HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 33
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "satisfied"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2019-01-01T00:00:00+02:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6a9cac17e9554f0dbe3fff5fa9714141?KeyID=594431fa&Signature=hZvS4CSztJ4NHc578HBQ6fS%2FgiEf4MXCEXIlbXvqBE27oKOA8%2FpSXEeuTYsqpBo9TrCeCtmQupQbGrgO9GqjBA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "e349bf9b34ed46cfaf8be2d7194f96d4", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/be01d098c5414a4c9c584a0633f9a7d5?KeyID=594431fa&Signature=kZNeGWunqQYTv5bscSdFt%252BxkDeuvO7iaEaQp7mCNCksApjn%2FkrLV%2Fn83lsAbd3qGXY5w8ZGn6PYjaZeDucNQCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "5b137817dd864994a12150c9055def62", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "dateAccepted": "2019-01-01T00:00:00+02:00", 
    "dateSubmitted": "2019-01-01T00:00:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.1", 
    "date": "2019-01-01T00:00:00+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "b8f302d183b74365900464f12d55465c"
  }
}

