POST /api/2.5/tenders/07498e54a6b549ebbac4abb82359b858/complaints/d6aed705205d47dabdc56fe0910d85f1/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 199
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy133760933721$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/07498e54a6b549ebbac4abb82359b858/complaints/d6aed705205d47dabdc56fe0910d85f1/documents/e6c2b00c87584c2f950bea3bf936ad0d
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/73cd15a36c6849ae9ef53a116b85b28d?KeyID=aa2f1067&Signature=I5AeESgD0wgvvRQAHISSDOZ00A5GOmZwwWvai9PF9XNIWIboHKweM9%2FX973DbSEFr8dnQZZyrK6nSI4VgcegDA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-28T06:47:51.144909+02:00", 
    "id": "e6c2b00c87584c2f950bea3bf936ad0d", 
    "dateModified": "2019-03-28T06:47:51.144925+02:00"
  }
}

