PATCH /api/2.5/tenders/07498e54a6b549ebbac4abb82359b858/complaints/25084f980e8740448911ff8d1b4bbd61?acc_token=fb80e4bf71524f64b699ea37e1472487 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 250
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "resolution": "Виправлено неконкурентні умови"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "dateAnswered": "2019-03-28T06:47:50.239145+02:00", 
    "dateSubmitted": "2019-03-28T06:47:49.951048+02:00", 
    "complaintID": "UA-2019-03-28-000001.2", 
    "date": "2019-03-28T06:47:50.244479+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "25084f980e8740448911ff8d1b4bbd61"
  }
}

