POST /api/2.5/tenders/545af3241b1c4572b0ad2c3cd05054af/complaints/2361fcad20eb477b973124f76503ceeb/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 149
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="ComplaintResolution.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/545af3241b1c4572b0ad2c3cd05054af/complaints/2361fcad20eb477b973124f76503ceeb/documents/cc513bfd6b0446bc82c7e8f2cb6788e7
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/865d5f8fb37046ecb8713ba537687f58?KeyID=a8968c46&Signature=L7htmAbAXj5b03sJ7PGP%2FKBxqwR6%252BjJY6FaswlE3skXXBmnNURghqfuE1QaDwmW3lTyFNa%252BUG9f3fxq%2FtlQ3Bg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "cc513bfd6b0446bc82c7e8f2cb6788e7", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

