PATCH /api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/cancellations/b314c6b707c44afda70eae84203a7a5a/documents/1b99bc3bc0af4122bf9fa67cc98fc611?acc_token=4fedc6c367a94e00ac51cd25b92bb6f8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8c1cdc8cdba2471eb45cec7b549ea043?KeyID=a8968c46&Signature=imsYBtJatKEaR4QulMVu6mYxdmxR9ZvEb3qhr4T3sC5vJdQil2xF5YZFrnOoqG746KhoPvQHceV1ohadSZaAAw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "1b99bc3bc0af4122bf9fa67cc98fc611", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

