PATCH /api/2.5/tenders/eeda351577cb475894b560d00bb57c20?acc_token=084aca35cabe4d629dd5a4fbe8b47c05 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification.stand-still", 
    "complaintPeriod": {
      "startDate": "2019-03-01T01:00:00+03:00", 
      "endDate": "2019-03-28T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-03-01T01:00:00+03:00", 
      "clarificationsUntil": "2019-03-27T01:00:00+03:00", 
      "endDate": "2019-03-22T01:00:00+03:00", 
      "invalidationDate": "2019-04-01T01:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-04-07T00:00:00+03:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }, 
      "contactPoint": {
        "name_en": "State administration", 
        "name": "Державне управління справами", 
        "availableLanguage": "uk", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "dus.gov.ua", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name_en": "State administration"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-04-01T01:00:00+03:00", 
        "title": "Калорійність", 
        "date": "2019-04-01T01:00:00+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "df766d0b965d492bbe0e3dcf8edc25b2", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "eeda351577cb475894b560d00bb57c20", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/596a0caec2c643428d829633d65ce247?KeyID=a8968c46&Signature=Xj1dsTv2ahNjM%252BrRi58IBeRDvNLH9nlO8KAN%2FV4A3YYvGFWAezgXiQbMByIMZXepXhEBTm1BdkaUdByIWSjqDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "b7c355ebd7bb42b2a6b45a4133aa7824", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8ad188fade8b4039818c8183ad69cb8d?KeyID=a8968c46&Signature=OAI7iGfo5v1ibbsE6Vf4%252BgFe%252B5LGGwsJDSx%252Bp9rda%252BDyYORIwIKhUP0QIXsg%2F8BzYPxYSoyeHhoNkLhV36qVBw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "7ed5f15b0c6644d9a2e7fb9ab20237ea", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6570bf00774f40b9898c8932dd5e32ca?KeyID=a8968c46&Signature=XCk3eNLNrREVU2QLCckkLbBgrYkwBvuzqaZ3EyjoRlezNE0n%2FlKwGgVEDehD0BaxannApVrvLZledWpq1DI9Bw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "7ed5f15b0c6644d9a2e7fb9ab20237ea", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2019-04-07T00:00:00+03:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "f074dc96c19a4b2ab186871f70f47fd9", 
        "guarantee": {
          "currency": "USD", 
          "amount": 8.0
        }
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2019-04-01T01:00:00+03:00", 
      "endDate": "2019-04-07T00:00:00+03:00"
    }, 
    "maxAwardsCount": 4, 
    "tenderID": "UA-2019-04-01-000001", 
    "dateModified": "2019-04-01T01:00:00+03:00", 
    "numberOfBids": 3, 
    "tenderPeriod": {
      "startDate": "2019-03-01T01:00:00+03:00", 
      "endDate": "2019-04-01T01:00:00+03:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "lotID": "f074dc96c19a4b2ab186871f70f47fd9", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "3cb5698d987f4fc7a12c4fe9b19637e3", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "141f0e0a9b7b492581a70296895a114c"
      }, 
      {
        "status": "active", 
        "lotID": "f074dc96c19a4b2ab186871f70f47fd9", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "19d5bd6c111c4b8d8fd79bc5c0ba6f6a", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "0142b47468e64590b1d327a1be5a01fa"
      }, 
      {
        "status": "unsuccessful", 
        "lotID": "f074dc96c19a4b2ab186871f70f47fd9", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "b9d6f3a7955d47f8868d9b9ed63dda85", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "c5f0f0b0cf8a43a595cd385e5a4fc3b2"
      }, 
      {
        "status": "active", 
        "lotID": "f074dc96c19a4b2ab186871f70f47fd9", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "1f042d35e8464a89aa530d18a5ea7f18", 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "96c5d1f5dfae4b4a9f457719f769a6e1"
      }
    ], 
    "title_en": "Cases for state awards", 
    "agreementDuration": "P3Y3M3D", 
    "date": "2019-04-01T01:00:00+03:00", 
    "procurementMethodType": "closeFrameworkAgreementUA", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "f074dc96c19a4b2ab186871f70f47fd9", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases for state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00", 
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        }, 
        "id": "cfa79c4a7e2041d3812508870da99986", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }, 
      {
        "relatedLot": "f074dc96c19a4b2ab186871f70f47fd9", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases for state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00", 
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        }, 
        "id": "0dc90ed37b0446b5b48e9695a5ef4a73", 
        "unit": {
          "code": "44617100-8", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3280fbb5c4314f8b8b64518b2aa70b04?KeyID=a8968c46&Signature=ClnfVP8nlx2rQSM5%252Bu8A8JJw%2FXTJG9hS1R0%252BCAdJYn7%252Bg9s4bSzwZoLcGyBZt2Fwst6nxZdSIs5%2FkY9v%252BVPSAg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "5ae9cd6028a74acf830a7aee315a0832", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/eeda351577cb475894b560d00bb57c20/bids/3cb5698d987f4fc7a12c4fe9b19637e3/documents/779c318ff1024b92819100b89a14ab05?download=cf1fdb6a736f4d2698e7d07b33815250", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_top_secrets.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "779c318ff1024b92819100b89a14ab05", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }
        ], 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "scale": "micro", 
            "name": "ДКП «Школяр»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "id": "3cb5698d987f4fc7a12c4fe9b19637e3", 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7a87a7385b6e466faf97cb2f4a24c66b?KeyID=a8968c46&Signature=cH0%252BtG%252BCwMSI6f%252BZKAIf4hSbo07DNwL2LGKc%2FwebBX3kta8mHiYa%252B9JV6b%2FF74lx%2F49yx2HcoHAJInVnlfh3DA%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "09073a9dfc034dae86704fc7431d43cd", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "19d5bd6c111c4b8d8fd79bc5c0ba6f6a", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "scale": "sme", 
            "name": "ДКП «Книга»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "unsuccessful", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal_part1.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f804c029ecfa42559846304431910b31?KeyID=a8968c46&Signature=lRedmSn4q0zAxbwdFublFzUbPaWaQgK6cly8Jhv%252B3tm2BuRm4Xul7WH6TMyFszIr%252B3oyVDguwb6h6QimwGCxAQ%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "e0d5b6bde4dc4636839af57f65d72137", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/eeda351577cb475894b560d00bb57c20/bids/b9d6f3a7955d47f8868d9b9ed63dda85/documents/a58c27f090404ff69a34538ebefeec6d?download=396b1aae5ae1484a9070a7b6dacf1275", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_part2.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "a58c27f090404ff69a34538ebefeec6d", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }
        ], 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0b17dc1b9b7842c8a1db63f864459e11?KeyID=a8968c46&Signature=yiUn3OwSYgMxtiLr4qhRjoeJNxTFKXyVzQNNJVgs9wJ7Jvr0DQF5f2wBQf14mewzs3evdAUvFeZ6nKFtAT9rCA%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "73715263157040a3a53bf5bfaaf20e17", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }
        ], 
        "selfEligible": true, 
        "selfQualified": true, 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "scale": "mid", 
            "name": "«Снігур»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137227", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "id": "b9d6f3a7955d47f8868d9b9ed63dda85"
      }, 
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal_part1.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f804c029ecfa42559846304431910b31?KeyID=a8968c46&Signature=lRedmSn4q0zAxbwdFublFzUbPaWaQgK6cly8Jhv%252B3tm2BuRm4Xul7WH6TMyFszIr%252B3oyVDguwb6h6QimwGCxAQ%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "4ff70d8ca2f042418f9a73f34aa198bd", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/eeda351577cb475894b560d00bb57c20/bids/1f042d35e8464a89aa530d18a5ea7f18/documents/34edca4751234723bfd4297a5c47eb6a?download=396b1aae5ae1484a9070a7b6dacf1275", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_part2.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "34edca4751234723bfd4297a5c47eb6a", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }
        ], 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "scale": "mid", 
            "name": "«Снігур»", 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137227", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "id": "1f042d35e8464a89aa530d18a5ea7f18", 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0b17dc1b9b7842c8a1db63f864459e11?KeyID=a8968c46&Signature=yiUn3OwSYgMxtiLr4qhRjoeJNxTFKXyVzQNNJVgs9wJ7Jvr0DQF5f2wBQf14mewzs3evdAUvFeZ6nKFtAT9rCA%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:00+03:00", 
            "id": "2faacde3c4d741458a3c7b347a8feb7b", 
            "dateModified": "2019-04-01T01:00:00+03:00"
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

