POST /api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/cancellations?acc_token=21b8da1c2cfe46e0b009093843400d60 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/cancellations/085ae5c7498e427a81a579387d17fed3
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2019-03-18T09:27:04.929264+02:00", 
    "cancellationOf": "tender", 
    "id": "085ae5c7498e427a81a579387d17fed3"
  }
}

