POST /api/2.5/tenders/730c9fdb8cfb40e2a17a836fa466fa1f/qualifications/fff064036a314888b26e7bd6bef19980/complaints/d383f45e46e942a9b7e0033eb2dba5d1/documents?acc_token=bddc664beac54cdebdd29208cf155dcb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 151
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/730c9fdb8cfb40e2a17a836fa466fa1f/qualifications/fff064036a314888b26e7bd6bef19980/complaints/d383f45e46e942a9b7e0033eb2dba5d1/documents/956ea0bc28eb4e189394ae90d45999a5
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ad0cba04b49f4cd2b43ed5f387cab02a?KeyID=a8968c46&Signature=EfgaRWdrSrrlFkZ5C4zhpfmOoaEAdgKsPq000nCOwbqg%252B6keAH2q%252BrDXq0QsqEDWqzykdmQJpxyWRx9iru4jCA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "956ea0bc28eb4e189394ae90d45999a5", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

