PATCH /api/2.5/tenders/987b976f65b44ddf8a0c582b1dfc3752/qualifications/911df99dc44242fa8bb4eb1084631b31/complaints/6a2b3205c49c462fbfc758038d9d9daf?acc_token=16c2198e06be401384f7a6912e12a146 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 387
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "280f6507375343409fd2564fc7ede48e", 
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "bid_id": "4cc4025498c24ad0a2bffffe25715c0c", 
    "dateAnswered": "2019-04-01T01:10:00+03:00", 
    "dateSubmitted": "2019-04-01T01:10:00+03:00", 
    "complaintID": "UA-2019-04-01-000001.6", 
    "date": "2019-04-01T01:10:00+03:00", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
    "id": "6a2b3205c49c462fbfc758038d9d9daf"
  }
}

