GET /api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/awards?acc_token=21b8da1c2cfe46e0b009093843400d60 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "pending", 
      "lotID": "0ba62781d4414b1c9736434c0c1e1e9e", 
      "suppliers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "bid_id": "faab39a561a643348ec4cf4323509620", 
      "value": {
        "currency": "UAH", 
        "amount": 5, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2019-03-18T09:27:00.655752+02:00", 
      "id": "5ac24396da054a5cba654ff539eadd45"
    }, 
    {
      "status": "pending", 
      "lotID": "0ba62781d4414b1c9736434c0c1e1e9e", 
      "suppliers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "bid_id": "be97dbf3b3bb453184e1058f629e1ef3", 
      "value": {
        "currency": "UAH", 
        "amount": 499, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2019-03-18T09:27:00.656055+02:00", 
      "id": "819391752ba04ca29b303cd5f542549a"
    }, 
    {
      "status": "pending", 
      "lotID": "0ba62781d4414b1c9736434c0c1e1e9e", 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "6eb4f1ad6ddf4998bec6805fae37e912", 
      "value": {
        "currency": "UAH", 
        "amount": 500.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2019-03-18T09:27:00.656328+02:00", 
      "id": "c35bd343031e46c4bcca7b4055bf30a6"
    }
  ]
}

