PATCH /api/2.5/tenders/987b976f65b44ddf8a0c582b1dfc3752/qualifications/911df99dc44242fa8bb4eb1084631b31/complaints/42b73d0a41a24b34a3db71f9cf8d1eb3?acc_token=2d8fd0f7ec944c7fb0f6aed154c34acc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "claim"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "280f6507375343409fd2564fc7ede48e", 
    "status": "claim", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "4cc4025498c24ad0a2bffffe25715c0c", 
    "dateSubmitted": "2019-04-01T01:10:00+03:00", 
    "complaintID": "UA-2019-04-01-000001.8", 
    "date": "2019-04-01T01:10:00+03:00", 
    "type": "claim", 
    "id": "42b73d0a41a24b34a3db71f9cf8d1eb3"
  }
}

