PATCH /api/2.5/tenders/536b6f8fb8f34ed9bd06f45f731077cd/qualifications/64bd3fb0f1564edcbfb134e28d24387c/complaints/ec7d91be05a54a438fe7c373b558d250 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 31
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "invalid"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
    "status": "invalid", 
    "dateDecision": "2019-01-01T00:10:00+02:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": false, 
    "dateSubmitted": "2019-01-01T00:10:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.2", 
    "date": "2019-01-01T00:10:00+02:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "ec7d91be05a54a438fe7c373b558d250"
  }
}

