PATCH /api/2.5/tenders/536b6f8fb8f34ed9bd06f45f731077cd/qualifications/64bd3fb0f1564edcbfb134e28d24387c/complaints/a991dba9a8b54ebb99a413b348a4cb02?acc_token=1d19dcc5fcf34ce6816b89971e2ba8cd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a6a8b1d57c1542b38e7db04885cf5a2c?KeyID=2d50b01d&Signature=HkjBEnvbnGWWC9smhTQkeFEXVmQaeDXEPwHPsq8H5qA0SVU%252BBeVEml94MOLqc1%252BNYPfIbJBoGNzu%2FteAKMK0AA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:10:00+02:00", 
        "id": "c990d9c2f938417fbb32ff6f371464b3", 
        "dateModified": "2019-01-01T00:10:00+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2019-01-01T00:10:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.1", 
    "date": "2019-01-01T00:10:00+02:00", 
    "type": "complaint", 
    "id": "a991dba9a8b54ebb99a413b348a4cb02"
  }
}

