GET /api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/bids?acc_token=4fedc6c367a94e00ac51cd25b92bb6f8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/231b822a07e64a4e80227d91e9c92ccc?KeyID=a8968c46&Signature=%252BuPlMa9KxPGiOYT5eHCwa7kLDioRMtlrBikphll%252B%2FvZy02qMbDMAdt5REwKhCFTa7nA1vz6HEmTVp9tIkYw5Bg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:00+03:00", 
          "id": "4345c1573ab64285ae5b581958e6914f", 
          "dateModified": "2019-04-01T01:00:00+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/bids/5b1584c69800457d9ea9df290ddb42ae/documents/2cc05f224b3e42a0ae5713bcd1c7b982?download=479494c860814218982f719f4b2321b1", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_top_secrets.pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:00+03:00", 
          "id": "2cc05f224b3e42a0ae5713bcd1c7b982", 
          "dateModified": "2019-04-01T01:00:00+03:00"
        }
      ], 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "id": "5b1584c69800457d9ea9df290ddb42ae", 
      "eligibilityDocuments": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "eligibility_doc.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b70cb436f2b54594b3f3bff673eb120c?KeyID=a8968c46&Signature=cMED8V6qUTZ77ZUuQuWi7lcHwQNHnOnp%252Bn7R6WaKoKNqZln4kDU3DqQdMhvFlnnFvD48F3nkoa4Dlm743NwVDQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:00+03:00", 
          "id": "e3be2be9a5804b948ef612689a2aef15", 
          "dateModified": "2019-04-01T01:00:00+03:00"
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "a21960990261432faab44db6275676d5", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal_part1.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/881579ab81ed4db48c7ebda31fd795be?KeyID=a8968c46&Signature=SzO0bE6x0Ce8cCKcDna7%252BmdsmLL2DEpikwSYZ56B86%252BVmD1eoMKavkUWv2kYxTiStu37hur%252B2YwUqLjfJ4szBA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:00+03:00", 
          "id": "78c31c350cd94dedb25360d1dbb3199e", 
          "dateModified": "2019-04-01T01:00:00+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/bids/7dad4f355e2b4bb1b757c38127de7628/documents/7a7524c55307467da3a357cd8460aa1b?download=ee33845a73fb48be97b0c99afa1b5cd6", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_part2.pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:00+03:00", 
          "id": "7a7524c55307467da3a357cd8460aa1b", 
          "dateModified": "2019-04-01T01:00:00+03:00"
        }
      ], 
      "eligibilityDocuments": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "eligibility_doc.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a387f4f4f8cd4b7b8b233b1122a1a1f7?KeyID=a8968c46&Signature=IxhppvJObyzjAZQYdRBxflHj3VuDgrCUZYIBuO%2FXepDd2NYPgdOtBRc0mLawTKi0EW8yo2FvVcgYxr%2F03SYICQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:00+03:00", 
          "id": "a8f2d273da09456d8b71430829acfc92", 
          "dateModified": "2019-04-01T01:00:00+03:00"
        }
      ], 
      "selfEligible": true, 
      "selfQualified": true, 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137227", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "id": "7dad4f355e2b4bb1b757c38127de7628"
    }, 
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal_part1.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/881579ab81ed4db48c7ebda31fd795be?KeyID=a8968c46&Signature=SzO0bE6x0Ce8cCKcDna7%252BmdsmLL2DEpikwSYZ56B86%252BVmD1eoMKavkUWv2kYxTiStu37hur%252B2YwUqLjfJ4szBA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:00+03:00", 
          "id": "77bcfb8cdd424beab7904abef6a8411b", 
          "dateModified": "2019-04-01T01:00:00+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/bids/7ded07f482ac44dd815b1cd075d9b64c/documents/c5be635ac53d4272a9bf13d7c0c0555f?download=ee33845a73fb48be97b0c99afa1b5cd6", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_part2.pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:00+03:00", 
          "id": "c5be635ac53d4272a9bf13d7c0c0555f", 
          "dateModified": "2019-04-01T01:00:00+03:00"
        }
      ], 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137227", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "id": "7ded07f482ac44dd815b1cd075d9b64c", 
      "eligibilityDocuments": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "eligibility_doc.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a387f4f4f8cd4b7b8b233b1122a1a1f7?KeyID=a8968c46&Signature=IxhppvJObyzjAZQYdRBxflHj3VuDgrCUZYIBuO%2FXepDd2NYPgdOtBRc0mLawTKi0EW8yo2FvVcgYxr%2F03SYICQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:00+03:00", 
          "id": "5d4b6cf8b5e74e93a90e5091a42070f4", 
          "dateModified": "2019-04-01T01:00:00+03:00"
        }
      ]
    }
  ]
}

