GET /api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/bids?acc_token=21b8da1c2cfe46e0b009093843400d60 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/a634bd9ba5fe4d01bd0df27a33871f18?KeyID=a4ab2441&Signature=Eg9TDcxWIa8LTFPzQg8OpjWgfwIKviqXiH083N%2F8YftA3m9HuAi9IYryMTf4GVTcXxc5LPWZzqZmiJdFt1OzBg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T09:26:57.444447+02:00", 
          "id": "51d997de6f814556b28d1f9372906c8c", 
          "dateModified": "2019-03-18T09:26:57.444460+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/bids/6eb4f1ad6ddf4998bec6805fae37e912/documents/dbcf34cf616c47159ccc2fa2774be7cd?download=d1f16eeae4804114a63bd765678b5586", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_top_secrets.pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T09:26:57.502415+02:00", 
          "id": "dbcf34cf616c47159ccc2fa2774be7cd", 
          "dateModified": "2019-03-18T09:26:57.502428+02:00"
        }
      ], 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "id": "6eb4f1ad6ddf4998bec6805fae37e912", 
      "eligibilityDocuments": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "eligibility_doc.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/57df759e0d2d4263b5e38887fbef2351?KeyID=a4ab2441&Signature=F1u1NiwuUK22WVntttihahY30r1jpRjMcFcHRVwZ%252Bk29c%252B8%2FDbT7I%252Bgms77MT72s8E66CpsMMErykT5xhplMAQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T09:26:57.829135+02:00", 
          "id": "730874684aa94bcd8b28af299e8a1300", 
          "dateModified": "2019-03-18T09:26:57.829148+02:00"
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "be97dbf3b3bb453184e1058f629e1ef3", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal_part1.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/a5f7c57e5ac34457ae041e0627ead68d?KeyID=a4ab2441&Signature=pVSfFcf51Wjg8NJP22v7EdJCMrK3vH4p7CR3I9niUDsUfKxz%2FEZu83ms2RfArvgxBkfOPybAGufRqwcd9Xo1BQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T09:26:58.501130+02:00", 
          "id": "d06e6d7dfbce4e1690e6568f97fd4cb8", 
          "dateModified": "2019-03-18T09:26:58.501144+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/bids/7b0602f81dbf45598ce719bef84dcd5f/documents/7a1ab45e15cb42828ea5b3261eefead2?download=f8a3279192dc4f5abcf33eecc1abe8bf", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_part2.pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T09:26:58.501589+02:00", 
          "id": "7a1ab45e15cb42828ea5b3261eefead2", 
          "dateModified": "2019-03-18T09:26:58.501603+02:00"
        }
      ], 
      "eligibilityDocuments": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "eligibility_doc.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/877e352c32b4424682227b96ca117ad3?KeyID=a4ab2441&Signature=Xpb7WqFweojBXiygUjlU27H9kBcEf8pVYfjA%252BfqPER5i3AaBECGzVLhAssYpxRMonYwkfX%252BlNQDadHhEAhWpDA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T09:26:58.502510+02:00", 
          "id": "4c4cea2547424474baa2867016710ef5", 
          "dateModified": "2019-03-18T09:26:58.502524+02:00"
        }
      ], 
      "selfEligible": true, 
      "selfQualified": true, 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "id": "7b0602f81dbf45598ce719bef84dcd5f"
    }, 
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal_part1.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/42e0033bef2e434d9a4dabe891bb2a7c?KeyID=a4ab2441&Signature=0ghuxc0irm1DBSpshPpSn42O0GjL3j%252B%252B4j6WvwOlG5Hf9bGJBEFetOh4P7tpV6hEll9UPNmZo0XnHbkHb3fbDw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T09:26:58.611579+02:00", 
          "id": "fa500294f9b54785b2c454c9830ade7b", 
          "dateModified": "2019-03-18T09:26:58.611590+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/bids/faab39a561a643348ec4cf4323509620/documents/8751077d18ca44d4ad49d5887b66488c?download=f48fa7a38daf48e6b43e08e532c458db", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_part2.pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T09:26:58.611930+02:00", 
          "id": "8751077d18ca44d4ad49d5887b66488c", 
          "dateModified": "2019-03-18T09:26:58.611940+02:00"
        }
      ], 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "id": "faab39a561a643348ec4cf4323509620", 
      "eligibilityDocuments": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "eligibility_doc.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/717918fce37041da90c705541ffdd6b1?KeyID=a4ab2441&Signature=zNY%252BLpdgwb%252BoW%252B8DwDdbLXWv1IrhfTisr7ddgkL3dt9C1I1OeH0c7He8wmHJZpGS1Fi3CqMrGEavGGbFU4CNAg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-18T09:26:58.612624+02:00", 
          "id": "0a3f77af1bf544838563122af2e211f4", 
          "dateModified": "2019-03-18T09:26:58.612635+02:00"
        }
      ]
    }
  ]
}

