GET /api/2.5/tenders/69b2e0ceffcf46899710d0fbbca43d16/awards?acc_token=94c3cae73f8a42dd8e34733966513d31 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "pending", 
      "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
      "suppliers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137227", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "bid_id": "f30029f85828476b9933ec082f123e69", 
      "value": {
        "currency": "UAH", 
        "amount": 5, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2019-01-01T00:00:00+02:00", 
      "id": "e45f418c1d2f495981647e639901ebf3"
    }, 
    {
      "status": "pending", 
      "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
      "suppliers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "bid_id": "d0bae9fc4c104aaf870a44b6181547f4", 
      "value": {
        "currency": "UAH", 
        "amount": 499, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2019-01-01T00:00:00+02:00", 
      "id": "5afc678a76a04da9887e528f68373c8a"
    }, 
    {
      "status": "pending", 
      "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "072db6b8dba749d9bd50c5e1dc33459a", 
      "value": {
        "currency": "UAH", 
        "amount": 500.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2019-01-01T00:00:00+02:00", 
      "id": "6c72521b0ed24792b5eea2aeeda54182"
    }
  ]
}

