PATCH /api/2.5/tenders/6cd8a1d635fb4c56b981335cbe1bc96d/qualifications/ae2182a4f1a745f2aaabf8e58162a691/complaints/b1e5a8fe66974751b4f5506225cf8a46 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 217
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "stopped", 
    "decision": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "relatedLot": "2e6f1f49c8894974a1c36e2b463b5b86", 
    "status": "stopped", 
    "dateDecision": "2019-03-28T06:48:11.664023+02:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "decision": "Тендер скасовується замовником", 
    "acceptance": true, 
    "dateCanceled": "2019-03-28T06:48:11.664045+02:00", 
    "dateAccepted": "2019-03-28T06:48:10.914689+02:00", 
    "dateSubmitted": "2019-03-28T06:48:08.745990+02:00", 
    "complaintID": "UA-2019-03-28-000001.5", 
    "date": "2019-03-28T06:48:11.672925+02:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "b1e5a8fe66974751b4f5506225cf8a46"
  }
}

