POST /api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1003
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "draft", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "474a13302d414c40b95a16f154cdd263", 
        "value": {
          "amount": 500
        }
      }
    ], 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "selfQualified": true
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/bids/5b1584c69800457d9ea9df290ddb42ae
{
  "access": {
    "token": "117ebc612ee44d1e94e699f91e64bc22"
  }, 
  "data": {
    "status": "draft", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "474a13302d414c40b95a16f154cdd263", 
        "date": "2019-01-01T00:00:00+02:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "5b1584c69800457d9ea9df290ddb42ae"
  }
}

