PATCH /api/2.5/tenders/eeda351577cb475894b560d00bb57c20/lots/f074dc96c19a4b2ab186871f70f47fd9?acc_token=084aca35cabe4d629dd5a4fbe8b47c05 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 57
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "guarantee": {
      "currency": "USD", 
      "amount": 8
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №1", 
    "title": "Лот №1", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-06-06T00:00:00+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "f074dc96c19a4b2ab186871f70f47fd9", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }
  }
}

