GET /api/2.5/tenders/69b2e0ceffcf46899710d0fbbca43d16 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "unsuccessful", 
    "awardPeriod": {
      "startDate": "2018-12-22T00:00:00+02:00", 
      "endDate": "2019-01-01T00:00:00+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2018-11-10T00:00:00+02:00", 
      "endDate": "2018-12-07T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2018-11-10T00:00:00+02:00", 
      "clarificationsUntil": "2018-12-06T00:00:00+02:00", 
      "endDate": "2018-12-01T00:00:00+02:00", 
      "invalidationDate": "2019-01-01T00:00:00+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procurementMethodType": "closeFrameworkAgreementUA", 
    "procuringEntity": {
      "kind": "general", 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }, 
      "contactPoint": {
        "name_en": "State administration", 
        "name": "Державне управління справами", 
        "availableLanguage": "uk", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "dus.gov.ua", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name_en": "State administration"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "author": {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }, 
        "title": "Калорійність", 
        "date": "2019-01-01T00:00:00+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "dateAnswered": "2019-01-01T00:00:00+02:00", 
        "id": "0dc962f7dde64d15b2ca8a116c61470a", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "69b2e0ceffcf46899710d0fbbca43d16", 
    "contractPeriod": {
      "startDate": "2018-12-26T00:00:00+02:00", 
      "clarificationsUntil": "2018-12-31T00:00:00+02:00", 
      "endDate": "2019-01-01T00:10:00+02:00"
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e6a32fb2951d4c1296ca5f10c3c83857?KeyID=bca3de5f&Signature=WDunMJjHWnqDor6PRS%252Bi%252BPPijIjyUunhiV7VUo1e7PuDiZNajO1zEyIP38u3oPMphFJpauU93fN%252Bbh0Xt%2Fc%2FAQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "0203e1fe07324409a7435b3b1813f09c", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/74a0ad9bdb894ab4bb998c0a5e336e41?KeyID=bca3de5f&Signature=inMZyiB6FkTpR0uBAUe23tidry2whqZ%252B%252BZ4TYmB6I2xBu9iIYZejSIn%252BGj9OA4wF5ARg6haIxRmbvM9rDwvVDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "92005e1a1c9840f2a9fd8aa4e46c1507", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/cbc228e3242649ee8f66d44d5c3a5ce7?KeyID=bca3de5f&Signature=SJp7H%2FOS%252Bm3TSmPk%252BK0hXkAVAgKrKU%252BI6uBIthU2InEFgrBv63ZFjKOY30gocoFHm9CAxQFBUzMFfRFRWtgoCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "92005e1a1c9840f2a9fd8aa4e46c1507", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "auctionUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/69b2e0ceffcf46899710d0fbbca43d16_a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "auctionPeriod": {
          "startDate": "2018-12-21T00:00:00+02:00", 
          "endDate": "2018-12-22T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "guarantee": {
          "currency": "USD", 
          "amount": 8.0
        }
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2018-12-11T00:00:00+02:00", 
      "endDate": "2018-12-21T00:00:00+02:00"
    }, 
    "maxAwardsCount": 4, 
    "tenderID": "UA-2019-01-01-000001", 
    "auctionPeriod": {
      "startDate": "2018-12-21T00:00:00+02:00", 
      "endDate": "2018-12-22T00:00:00+02:00"
    }, 
    "guarantee": {
      "currency": "USD", 
      "amount": 8
    }, 
    "dateModified": "2019-01-01T00:10:00+02:00", 
    "agreements": [
      {
        "agreementID": "UA-2019-01-01-000001-3763a3f4d7e94ac7836fca892cccd7f11", 
        "status": "unsuccessful", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "title": "agreement_first_document.doc", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/50b283f2ac994328a9f1b247da9db677?KeyID=bca3de5f&Signature=F4pkJVYKZO0%252Bl9K7SPhGttHrHBvEVGtNwnOM517K4%2F4jDh8JJk64a8LRwnbRCZSDEP7xvrt6aPOV7e85i9DxBA%253D%253D", 
            "format": "application/msword", 
            "documentOf": "tender", 
            "datePublished": "2019-01-01T00:00:00+02:00", 
            "id": "c0604c268f6f4c1291bf36db9845d0e7", 
            "dateModified": "2019-01-01T00:00:00+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "language": "en", 
            "title": "agreement_second_document.doc", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/df8161d185fe4a068cc624ffa7c8038f?KeyID=bca3de5f&Signature=beGqpCvy7MPxqSI0utF1tn1BPdFrOYqlTVRthp9olytjyx1l9X1PfxCwri1lGAOW9S6pf16mOMCoDJ6a8TVrAg%253D%253D", 
            "format": "application/msword", 
            "title_en": "Title of Document", 
            "description_en": "Description of Document", 
            "datePublished": "2019-01-01T00:00:00+02:00", 
            "documentOf": "tender", 
            "id": "5b27d9f3a11c45f9b7d9dbb00eb8b8c0", 
            "dateModified": "2019-01-01T00:00:00+02:00"
          }
        ], 
        "contracts": [
          {
            "status": "active", 
            "unitPrices": [
              {
                "value": {
                  "currency": "UAH", 
                  "amount": 0.5, 
                  "valueAddedTaxIncluded": true
                }, 
                "relatedItem": "c02b11e2bb654c169699d7e28341a753"
              }, 
              {
                "value": {
                  "currency": "UAH", 
                  "amount": 0.5, 
                  "valueAddedTaxIncluded": true
                }, 
                "relatedItem": "a0bde9d4798c4f1aaf63dee3ea8d1ffc"
              }
            ], 
            "suppliers": [
              {
                "contactPoint": {
                  "email": "fake@mail.com", 
                  "telephone": "+380 (322) 12-34-56", 
                  "name": "Іван Іваненко"
                }, 
                "identifier": {
                  "scheme": "UA-EDR", 
                  "id": "00137227", 
                  "uri": "http://www.sc.gov.ua/"
                }, 
                "name": "«Снігур»", 
                "address": {
                  "postalCode": "79013", 
                  "countryName": "Україна", 
                  "streetAddress": "вул. Островського, 35", 
                  "region": "м. Львів", 
                  "locality": "м. Львів"
                }
              }
            ], 
            "bidID": "f30029f85828476b9933ec082f123e69", 
            "date": "2019-01-01T00:00:00+02:00", 
            "awardID": "ef3d119d596d4832a0b13f17c01a9553", 
            "id": "05b696860290436289631a8f9ce7b352"
          }, 
          {
            "status": "active", 
            "unitPrices": [
              {
                "value": {
                  "currency": "UAH", 
                  "amount": 0.5, 
                  "valueAddedTaxIncluded": true
                }, 
                "relatedItem": "c02b11e2bb654c169699d7e28341a753"
              }, 
              {
                "value": {
                  "currency": "UAH", 
                  "amount": 0.5, 
                  "valueAddedTaxIncluded": true
                }, 
                "relatedItem": "a0bde9d4798c4f1aaf63dee3ea8d1ffc"
              }
            ], 
            "suppliers": [
              {
                "contactPoint": {
                  "email": "aagt@gmail.com", 
                  "telephone": "+380 (322) 91-69-30", 
                  "name": "Андрій Олексюк"
                }, 
                "identifier": {
                  "scheme": "UA-EDR", 
                  "id": "00137226", 
                  "uri": "http://www.sc.gov.ua/"
                }, 
                "name": "ДКП «Книга»", 
                "address": {
                  "postalCode": "79013", 
                  "countryName": "Україна", 
                  "streetAddress": "вул. Островського, 34", 
                  "region": "м. Львів", 
                  "locality": "м. Львів"
                }
              }
            ], 
            "bidID": "d0bae9fc4c104aaf870a44b6181547f4", 
            "date": "2019-01-01T00:00:00+02:00", 
            "awardID": "e61ac71cb2cf4e36948e6d65943b4b26", 
            "id": "97baaa9f55f04467a3a283c8bec11849"
          }, 
          {
            "status": "active", 
            "unitPrices": [
              {
                "value": {
                  "currency": "UAH", 
                  "amount": 0.5, 
                  "valueAddedTaxIncluded": true
                }, 
                "relatedItem": "c02b11e2bb654c169699d7e28341a753"
              }, 
              {
                "value": {
                  "currency": "UAH", 
                  "amount": 0.5, 
                  "valueAddedTaxIncluded": true
                }, 
                "relatedItem": "a0bde9d4798c4f1aaf63dee3ea8d1ffc"
              }
            ], 
            "suppliers": [
              {
                "contactPoint": {
                  "email": "soleksuk@gmail.com", 
                  "telephone": "+380 (432) 21-69-30", 
                  "name": "Сергій Олексюк"
                }, 
                "identifier": {
                  "scheme": "UA-EDR", 
                  "id": "00137256", 
                  "uri": "http://www.sc.gov.ua/"
                }, 
                "name": "ДКП «Школяр»", 
                "address": {
                  "postalCode": "21100", 
                  "countryName": "Україна", 
                  "streetAddress": "вул. Островського, 33", 
                  "region": "м. Вінниця", 
                  "locality": "м. Вінниця"
                }
              }
            ], 
            "bidID": "072db6b8dba749d9bd50c5e1dc33459a", 
            "date": "2019-01-01T00:00:00+02:00", 
            "awardID": "0c09750bc38142fe999fc03ab5c0f30c", 
            "id": "12970ffe75e14e579679c3da6ef34584"
          }
        ], 
        "items": [
          {
            "relatedLot": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
            "description": "футляри до державних нагород", 
            "classification": {
              "scheme": "ДК021", 
              "description": "Cartons", 
              "id": "44617100-9"
            }, 
            "description_en": "Cases for state awards", 
            "additionalClassifications": [
              {
                "scheme": "ДКПП", 
                "id": "17.21.1", 
                "description": "папір і картон гофровані, паперова й картонна тара"
              }
            ], 
            "deliveryAddress": {
              "postalCode": "79000", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "deliveryDate": {
              "startDate": "2018-06-27T13:39:09.362837+03:00", 
              "endDate": "2018-06-30T13:39:09.362837+03:00"
            }, 
            "id": "c02b11e2bb654c169699d7e28341a753", 
            "unit": {
              "code": "44617100-9", 
              "name": "item"
            }, 
            "quantity": 5.0
          }, 
          {
            "relatedLot": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
            "description": "футляри до державних нагород", 
            "classification": {
              "scheme": "ДК021", 
              "description": "Cartons", 
              "id": "44617100-9"
            }, 
            "description_en": "Cases for state awards", 
            "additionalClassifications": [
              {
                "scheme": "ДКПП", 
                "id": "17.21.1", 
                "description": "папір і картон гофровані, паперова й картонна тара"
              }
            ], 
            "deliveryAddress": {
              "postalCode": "79000", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "deliveryDate": {
              "startDate": "2018-06-27T13:39:09.362837+03:00", 
              "endDate": "2018-06-30T13:39:09.362837+03:00"
            }, 
            "id": "a0bde9d4798c4f1aaf63dee3ea8d1ffc", 
            "unit": {
              "code": "44617100-8", 
              "name": "item"
            }, 
            "quantity": 5.0
          }
        ], 
        "period": {
          "startDate": "2019-04-18T06:49:21.550339+03:00", 
          "endDate": "2023-04-17T06:49:21.550339+03:00"
        }, 
        "dateSigned": "2019-01-01T00:10:00+02:00", 
        "date": "2019-01-01T00:10:00+02:00", 
        "id": "90a23cd9a0ba47079f799787ed23e53d"
      }
    ], 
    "numberOfBids": 0, 
    "tenderPeriod": {
      "startDate": "2018-11-10T00:00:00+02:00", 
      "endDate": "2018-12-11T00:00:00+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "072db6b8dba749d9bd50c5e1dc33459a", 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "b6dd114ae59a4ad4a81fcdb9955faab8"
      }, 
      {
        "status": "active", 
        "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "d0bae9fc4c104aaf870a44b6181547f4", 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "869e1b7bdc17429da1a1067cbf4e2b3c"
      }, 
      {
        "status": "unsuccessful", 
        "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "26ecccb810cb48f6a2f31672245a52b7", 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "e3866564095e4bea9e4b9c96699b5483"
      }, 
      {
        "status": "active", 
        "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "f30029f85828476b9933ec082f123e69", 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "02202d4604e441df8676415a97d3304f"
      }
    ], 
    "title_en": "Cases for state awards", 
    "agreementDuration": "P3Y3M3D", 
    "awards": [
      {
        "status": "cancelled", 
        "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "eligible": true, 
        "suppliers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137227", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "bid_id": "f30029f85828476b9933ec082f123e69", 
        "value": {
          "currency": "UAH", 
          "amount": 5, 
          "valueAddedTaxIncluded": true
        }, 
        "qualified": true, 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "e45f418c1d2f495981647e639901ebf3"
      }, 
      {
        "status": "cancelled", 
        "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "eligible": true, 
        "suppliers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "bid_id": "d0bae9fc4c104aaf870a44b6181547f4", 
        "value": {
          "currency": "UAH", 
          "amount": 499, 
          "valueAddedTaxIncluded": true
        }, 
        "qualified": true, 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "5afc678a76a04da9887e528f68373c8a"
      }, 
      {
        "status": "cancelled", 
        "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "eligible": true, 
        "suppliers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "bid_id": "072db6b8dba749d9bd50c5e1dc33459a", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "qualified": true, 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "6c72521b0ed24792b5eea2aeeda54182"
      }, 
      {
        "status": "cancelled", 
        "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "suppliers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137227", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "bid_id": "f30029f85828476b9933ec082f123e69", 
        "value": {
          "currency": "UAH", 
          "amount": 5, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "ade1486ee5b745338c1ef87e4f4f1fa4"
      }, 
      {
        "status": "active", 
        "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "eligible": true, 
        "suppliers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137227", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "complaintPeriod": {
          "startDate": "2018-12-22T00:00:00+02:00", 
          "endDate": "2019-01-01T00:00:00+02:00"
        }, 
        "bid_id": "f30029f85828476b9933ec082f123e69", 
        "value": {
          "currency": "UAH", 
          "amount": 5, 
          "valueAddedTaxIncluded": true
        }, 
        "qualified": true, 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "ef3d119d596d4832a0b13f17c01a9553"
      }, 
      {
        "status": "active", 
        "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "eligible": true, 
        "suppliers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "complaintPeriod": {
          "startDate": "2018-12-22T00:00:00+02:00", 
          "endDate": "2019-01-01T00:00:00+02:00"
        }, 
        "bid_id": "d0bae9fc4c104aaf870a44b6181547f4", 
        "value": {
          "currency": "UAH", 
          "amount": 499, 
          "valueAddedTaxIncluded": true
        }, 
        "qualified": true, 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "e61ac71cb2cf4e36948e6d65943b4b26"
      }, 
      {
        "status": "active", 
        "lotID": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "eligible": true, 
        "suppliers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "complaintPeriod": {
          "startDate": "2018-12-22T00:00:00+02:00", 
          "endDate": "2019-01-01T00:00:00+02:00"
        }, 
        "bid_id": "072db6b8dba749d9bd50c5e1dc33459a", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "qualified": true, 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "0c09750bc38142fe999fc03ab5c0f30c"
      }
    ], 
    "date": "2019-01-01T00:10:00+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases for state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00", 
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        }, 
        "id": "c02b11e2bb654c169699d7e28341a753", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }, 
      {
        "relatedLot": "a7bb6ac2dc0f4b4c8f3fa5874c402305", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases for state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00", 
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        }, 
        "id": "a0bde9d4798c4f1aaf63dee3ea8d1ffc", 
        "unit": {
          "code": "44617100-8", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

