GET /api/2.5/tenders/69b2e0ceffcf46899710d0fbbca43d16/agreements/90a23cd9a0ba47079f799787ed23e53d/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "language": "en", 
      "title": "agreement_second_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/df8161d185fe4a068cc624ffa7c8038f?KeyID=bca3de5f&Signature=beGqpCvy7MPxqSI0utF1tn1BPdFrOYqlTVRthp9olytjyx1l9X1PfxCwri1lGAOW9S6pf16mOMCoDJ6a8TVrAg%253D%253D", 
      "format": "application/msword", 
      "title_en": "Title of Document", 
      "description_en": "Description of Document", 
      "datePublished": "2019-01-01T00:00:00+02:00", 
      "documentOf": "tender", 
      "id": "5b27d9f3a11c45f9b7d9dbb00eb8b8c0", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "agreement_first_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/50b283f2ac994328a9f1b247da9db677?KeyID=bca3de5f&Signature=F4pkJVYKZO0%252Bl9K7SPhGttHrHBvEVGtNwnOM517K4%2F4jDh8JJk64a8LRwnbRCZSDEP7xvrt6aPOV7e85i9DxBA%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2019-01-01T00:00:00+02:00", 
      "id": "c0604c268f6f4c1291bf36db9845d0e7", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }
  ]
}

