PATCH /api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/agreements/537065690fe34d19895c085d0e4aabb1/documents/e64ca6d35eeb47a197ba09c7b691c6e3?acc_token=4fedc6c367a94e00ac51cd25b92bb6f8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 106
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "title_en": "Title of Document", 
    "language": "en", 
    "description_en": "Description of Document"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "language": "en", 
    "title": "agreement_second_document.doc", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/741d8b9e5e9f4f759e3059ef6f212962?KeyID=a8968c46&Signature=cgtOXU77MbLBfARuGq8V7MbCW79Z98kh3VKYbuU81KgIjoZSjvmBX6khW6vqBQeoFLfBBeN%2F8oflwD1OBW%2FKAg%253D%253D", 
    "format": "application/msword", 
    "title_en": "Title of Document", 
    "description_en": "Description of Document", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "documentOf": "tender", 
    "id": "e64ca6d35eeb47a197ba09c7b691c6e3", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

