GET /api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/documents/4e6fa5162eb147afb947f582bc3fa49b?acc_token=4fedc6c367a94e00ac51cd25b92bb6f8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ec7409ca0a774c4c904e90bad64e6229?KeyID=a8968c46&Signature=qjmaVeOOBlkxJ5h3R0Y0kUyAsWf7w%2FeCWAcBvJf2Uyr%2Fo3oZRWQyIA8YWU1E9w%2FIBo3C1xBcubJr8XwV3nHKDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "previousVersions": [], 
    "id": "4e6fa5162eb147afb947f582bc3fa49b", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

