GET /api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/documents?acc_token=4fedc6c367a94e00ac51cd25b92bb6f8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/625c9edc30be4aa3acab470c93670fcd?KeyID=a8968c46&Signature=OZSKKisz1Ys04TuQN9jODI%2FjeDFEPi03ckPd7fJGgQ2eVZVjH8SvZfc2sbIIXfyU%252Bbd1eVsQc4nG8ouCooMVAw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "4e6fa5162eb147afb947f582bc3fa49b", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1861716372954b42a0468782597cb9d3?KeyID=a8968c46&Signature=PWeg49bDvjE5QPGQod5KYk62C%2FDQdB4f2FvhK4K0Mn3P44OeSrQkSLACzaNnr0Pnb16lZK3r10vMgVwSysSkAQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "6ac2be61881f4b65a396cad52b8faf73", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }
  ]
}

