GET /api/2.5/tenders/eeda351577cb475894b560d00bb57c20/agreements/9c9b9267b5f045c5898d6d4ae2ba3855/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "language": "en", 
      "title": "agreement_second_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5d3ed5054f7f4435b39ba0e0069c7d25?KeyID=a8968c46&Signature=1YQ9FjQl%252BtWQzyuc7%252BuTUpbaL1hD0vF%252BMt6BqX%252BmDxiaXnqaFDuhIz7aY5C2Uw%2FDWKhefvYawxCnAoMQF9YlDA%253D%253D", 
      "format": "application/msword", 
      "title_en": "Title of Document", 
      "description_en": "Description of Document", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "documentOf": "tender", 
      "id": "62cbc169988b442fa43b88e63ce2f6ba", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "agreement_first_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/aca7d141756245db8ac8b692b3c58a87?KeyID=a8968c46&Signature=kNHulgSlpGmulWN8ECAXGbG7g9Gq%252BiagFvEw7jzIVkkHNPazg2Kp4KRnAX14lXYKJ3cNg4vnbFsiqkcNnoDMCQ%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "3b34c3f614d34aa9925a7fab9a174152", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }
  ]
}

