PATCH /api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/agreements/ab2aaef988ce4ddea2bc472e2f27f9d4?acc_token=21b8da1c2cfe46e0b009093843400d60 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 138
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "period": {
      "startDate": "2019-03-18T09:26:15.271820+02:00", 
      "endDate": "2023-03-17T09:26:15.271820+02:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "agreementID": "UA-2019-03-18-000001-df5b7964425c450c9184757dfcec18a11", 
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "agreement_first_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/5999b2b1c70f43588b0e786b33e41125?KeyID=a4ab2441&Signature=5oCu2atSsWuR5Rbu%2FxQFG3QntDdU1AAaBnXuXWmUQJb6UjrS6SNHlmammtAijMFNSaYioXKWLu7qmkiciKn5Aw%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:27:03.474385+02:00", 
        "id": "752300fd24d340059e9d0fda263a9051", 
        "dateModified": "2019-03-18T09:27:03.474400+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "en", 
        "title": "agreement_second_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/3ab610c7f8cf4c72bfdb024529a88bdd?KeyID=a4ab2441&Signature=nmsSEOMKhzx6gy385RhQJreOM0%252BiGc1IKz0MDh0axZ2ff0lfEhNN1TqU6FdvtoBau7idZPsPx6nL41rjJlW%252BCg%253D%253D", 
        "format": "application/msword", 
        "title_en": "Title of Document", 
        "description_en": "Description of Document", 
        "datePublished": "2019-03-18T09:27:03.787809+02:00", 
        "documentOf": "tender", 
        "id": "f563c104724747e381847c70eb047426", 
        "dateModified": "2019-03-18T09:27:03.787826+02:00"
      }
    ], 
    "contracts": [
      {
        "status": "active", 
        "unitPrices": [
          {
            "value": {
              "currency": "UAH", 
              "amount": 0.5, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "5898867557fc405ea1b00cdd947e2142"
          }, 
          {
            "value": {
              "currency": "UAH", 
              "amount": 0.5, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "065b559633864555bd31f3b0e1eb9a2b"
          }
        ], 
        "suppliers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "bidID": "faab39a561a643348ec4cf4323509620", 
        "date": "2019-03-18T09:27:02.349342+02:00", 
        "awardID": "0149afe7262c4ede8832f11dc7a8bb29", 
        "id": "5126b938958f4191989309444e4addc7"
      }, 
      {
        "status": "active", 
        "unitPrices": [
          {
            "value": {
              "currency": "UAH", 
              "amount": 0.5, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "5898867557fc405ea1b00cdd947e2142"
          }, 
          {
            "value": {
              "currency": "UAH", 
              "amount": 0.5, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "065b559633864555bd31f3b0e1eb9a2b"
          }
        ], 
        "suppliers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "bidID": "be97dbf3b3bb453184e1058f629e1ef3", 
        "date": "2019-03-18T09:27:02.349392+02:00", 
        "awardID": "7cb28983a0a4461091f3cc6392f1f8f8", 
        "id": "2fab87712e404d21980ce0c5ca3b48fb"
      }, 
      {
        "status": "active", 
        "unitPrices": [
          {
            "value": {
              "currency": "UAH", 
              "amount": 0.5, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "5898867557fc405ea1b00cdd947e2142"
          }, 
          {
            "value": {
              "currency": "UAH", 
              "amount": 0.5, 
              "valueAddedTaxIncluded": true
            }, 
            "relatedItem": "065b559633864555bd31f3b0e1eb9a2b"
          }
        ], 
        "suppliers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "bidID": "6eb4f1ad6ddf4998bec6805fae37e912", 
        "date": "2019-03-18T09:27:02.349429+02:00", 
        "awardID": "af32488dd2644681a37771f68f42ab16", 
        "id": "c0eabc5e6c2b44fbb41f21b8adb0b7c6"
      }
    ], 
    "items": [
      {
        "relatedLot": "0ba62781d4414b1c9736434c0c1e1e9e", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases for state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00", 
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        }, 
        "id": "5898867557fc405ea1b00cdd947e2142", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }, 
      {
        "relatedLot": "0ba62781d4414b1c9736434c0c1e1e9e", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases for state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00", 
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        }, 
        "id": "065b559633864555bd31f3b0e1eb9a2b", 
        "unit": {
          "code": "44617100-8", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "period": {
      "startDate": "2019-03-18T09:26:15.271820+02:00", 
      "endDate": "2023-03-17T09:26:15.271820+02:00"
    }, 
    "dateSigned": "2019-03-18T09:27:04.258767+02:00", 
    "date": "2019-03-18T09:27:04.645596+02:00", 
    "id": "ab2aaef988ce4ddea2bc472e2f27f9d4"
  }
}

