POST /api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/agreements/ab2aaef988ce4ddea2bc472e2f27f9d4/documents?acc_token=21b8da1c2cfe46e0b009093843400d60 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 209
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy0667621780217$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/a27a2edadf6a442eb7f17020c7d789fd/agreements/ab2aaef988ce4ddea2bc472e2f27f9d4/documents/752300fd24d340059e9d0fda263a9051
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "agreement_first_document.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/5999b2b1c70f43588b0e786b33e41125?KeyID=a4ab2441&Signature=5oCu2atSsWuR5Rbu%2FxQFG3QntDdU1AAaBnXuXWmUQJb6UjrS6SNHlmammtAijMFNSaYioXKWLu7qmkiciKn5Aw%253D%253D", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2019-03-18T09:27:03.474385+02:00", 
    "id": "752300fd24d340059e9d0fda263a9051", 
    "dateModified": "2019-03-18T09:27:03.474400+02:00"
  }
}

