GET /api/2.5/tenders/eeda351577cb475894b560d00bb57c20?acc_token=084aca35cabe4d629dd5a4fbe8b47c05 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "mainProcurementCategory": "goods", 
    "complaintPeriod": {
      "startDate": "2019-03-04T01:00:00+03:00", 
      "endDate": "2019-03-30T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-03-04T01:00:00+03:00", 
      "clarificationsUntil": "2019-03-28T00:00:00+03:00", 
      "endDate": "2019-03-24T01:00:00+03:00", 
      "invalidationDate": "2019-04-01T01:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-04-03T01:00:00+03:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }, 
      "contactPoint": {
        "name_en": "State administration", 
        "name": "Державне управління справами", 
        "availableLanguage": "uk", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "dus.gov.ua", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name_en": "State administration"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-04-01T01:00:00+03:00", 
        "title": "Калорійність", 
        "date": "2019-04-01T01:00:00+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "df766d0b965d492bbe0e3dcf8edc25b2", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "eeda351577cb475894b560d00bb57c20", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/596a0caec2c643428d829633d65ce247?KeyID=a8968c46&Signature=Xj1dsTv2ahNjM%252BrRi58IBeRDvNLH9nlO8KAN%2FV4A3YYvGFWAezgXiQbMByIMZXepXhEBTm1BdkaUdByIWSjqDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "b7c355ebd7bb42b2a6b45a4133aa7824", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8ad188fade8b4039818c8183ad69cb8d?KeyID=a8968c46&Signature=OAI7iGfo5v1ibbsE6Vf4%252BgFe%252B5LGGwsJDSx%252Bp9rda%252BDyYORIwIKhUP0QIXsg%2F8BzYPxYSoyeHhoNkLhV36qVBw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "7ed5f15b0c6644d9a2e7fb9ab20237ea", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6570bf00774f40b9898c8932dd5e32ca?KeyID=a8968c46&Signature=XCk3eNLNrREVU2QLCckkLbBgrYkwBvuzqaZ3EyjoRlezNE0n%2FlKwGgVEDehD0BaxannApVrvLZledWpq1DI9Bw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "7ed5f15b0c6644d9a2e7fb9ab20237ea", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2019-05-09T00:00:00+03:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-04-01T01:00:00+03:00", 
        "id": "f074dc96c19a4b2ab186871f70f47fd9", 
        "guarantee": {
          "currency": "USD", 
          "amount": 8.0
        }
      }
    ], 
    "maxAwardsCount": 4, 
    "tenderID": "UA-2019-04-01-000001", 
    "dateModified": "2019-04-01T01:00:00+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2019-03-04T01:00:00+03:00", 
      "endDate": "2019-04-03T01:00:00+03:00"
    }, 
    "title_en": "Cases for state awards", 
    "procurementMethodType": "closeFrameworkAgreementUA", 
    "agreementDuration": "P3Y3M3D", 
    "date": "2019-04-01T01:00:00+03:00", 
    "milestones": [
      {
        "code": "prepayment", 
        "sequenceNumber": 0, 
        "title": "signingTheContract", 
        "duration": {
          "type": "banking", 
          "days": 2
        }, 
        "percentage": 100.0, 
        "type": "financing", 
        "id": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      }
    ], 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "f074dc96c19a4b2ab186871f70f47fd9", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases for state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00", 
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        }, 
        "id": "cfa79c4a7e2041d3812508870da99986", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }, 
      {
        "relatedLot": "f074dc96c19a4b2ab186871f70f47fd9", 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases for state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-06-27T13:39:09.362837+03:00", 
          "endDate": "2018-06-30T13:39:09.362837+03:00"
        }, 
        "id": "0dc90ed37b0446b5b48e9695a5ef4a73", 
        "unit": {
          "code": "44617100-8", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

PATCH /api/2.5/tenders/eeda351577cb475894b560d00bb57c20?acc_token=084aca35cabe4d629dd5a4fbe8b47c05 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 38
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "value": {
      "amount": 501.0
    }
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "tenderPeriod should be extended by 7 days", 
      "location": "body", 
      "name": "data"
    }
  ]
}

