PUT /api/2.5/tenders/239ab2b4b65a46f8ac603eebcd77771c/documents/6ac2be61881f4b65a396cad52b8faf73?acc_token=4fedc6c367a94e00ac51cd25b92bb6f8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 196
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy536632989049$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a9d7f82659d747d790aaae6bb8a81e27?KeyID=a8968c46&Signature=f8UHsymuRS1CL%2Fr1jpaycVJqrTrGHKDZ49GFkfHFaZc4LiFdmuTsv5NWodN5xf%252BApbprhxRm7qV4uBiIgScMAw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "6ac2be61881f4b65a396cad52b8faf73", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

