PUT /api/2.5/tenders/69b2e0ceffcf46899710d0fbbca43d16/documents/92005e1a1c9840f2a9fd8aa4e46c1507?acc_token=94c3cae73f8a42dd8e34733966513d31 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 196
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy390620298714$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/cbc228e3242649ee8f66d44d5c3a5ce7?KeyID=bca3de5f&Signature=SJp7H%2FOS%252Bm3TSmPk%252BK0hXkAVAgKrKU%252BI6uBIthU2InEFgrBv63ZFjKOY30gocoFHm9CAxQFBUzMFfRFRWtgoCw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "92005e1a1c9840f2a9fd8aa4e46c1507", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

