POST /api/2.5/tenders/69b2e0ceffcf46899710d0fbbca43d16/documents?acc_token=94c3cae73f8a42dd8e34733966513d31 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 193
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy872278461882$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/69b2e0ceffcf46899710d0fbbca43d16/documents/92005e1a1c9840f2a9fd8aa4e46c1507
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "AwardCriteria.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/74a0ad9bdb894ab4bb998c0a5e336e41?KeyID=bca3de5f&Signature=inMZyiB6FkTpR0uBAUe23tidry2whqZ%252B%252BZ4TYmB6I2xBu9iIYZejSIn%252BGj9OA4wF5ARg6haIxRmbvM9rDwvVDQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "92005e1a1c9840f2a9fd8aa4e46c1507", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

