POST /api/2.5/tenders/eeda351577cb475894b560d00bb57c20/bids/3cb5698d987f4fc7a12c4fe9b19637e3/financial_documents?acc_token=68c78b9b1da24d37bdf110962b1cec17 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 195
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="prices.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

<raw_file_data>
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/eeda351577cb475894b560d00bb57c20/bids/3cb5698d987f4fc7a12c4fe9b19637e3/financial_documents/2d2bb154b27b4155b2c9ba486bdc09dc
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "public", 
    "language": "uk", 
    "title": "prices.xlsx", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/12aa5e0838a947ce9cec3fe180ed9fc3?KeyID=a8968c46&Signature=nZSTVXS92pkyEwYn8iM560alhH3ZIvKpx3%2FHtLmrE6SwZLpJDeZDZtaT1XHnDSivloLB%252By7odIjiaFOobr%2FhBQ%253D%253D", 
    "format": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "2d2bb154b27b4155b2c9ba486bdc09dc", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

