PATCH /api/2.4/tenders/a9fa8c33df924d25b648931e89bd8ea8/cancellations/d3c1e450803344efac7a043a970da163?acc_token=b3696ab04e114fd79a1f01177d689f22 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/2a8c2ae8d1ea4bbab24878243bd31723?KeyID=dfcba93d&Signature=aRTeoe73UYAzkr%2FX8ZkG6r0tF8aVCw6pyWNDBPGX3KmdlrOMCxNbNvY7cCNCPX8hHCB8SJgkFDijZABmX8xjDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-02-06T06:09:50.440864+02:00", 
        "id": "2d9fdd89b40d4158b65fdcc0b03e5c99", 
        "dateModified": "2019-02-06T06:09:50.440877+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "title": "Notice-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/35c8a4b1fbd142909d31b43ebb4d89c2?KeyID=dfcba93d&Signature=6ANDmdw6PWfUFv%252B62tPIW0t0p3liWsoDDw%252BvvFBVg0%252BFol1O7LotHn%252BARRO5AjSWTQSwN9XpXIBYlJPY7%2FnyDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-02-06T06:09:50.440864+02:00", 
        "id": "2d9fdd89b40d4158b65fdcc0b03e5c99", 
        "dateModified": "2019-02-06T06:09:50.590125+02:00"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2019-02-06T06:09:50.706180+02:00", 
    "cancellationOf": "tender", 
    "id": "d3c1e450803344efac7a043a970da163"
  }
}

