PATCH /api/2.4/tenders/2208281bd1694de2a6f4b2fa36d47a52/questions/17470c311f364d448c586cd20d607d67?acc_token=96e4d8f1b0524eae8883e050dace84d7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


200 OK
Content-Type: application/json

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2018-09-21T05:23:15.681343+03:00", 
    "title": "Калорійність", 
    "date": "2018-09-21T05:23:15.562554+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "17470c311f364d448c586cd20d607d67", 
    "questionOf": "tender"
  }
}

