PATCH /api/2.5/tenders/4e72a84032424e519ab51eb3c1c98dbf/questions/c17fa52911844d7387b8446638b0fdde?acc_token=40505a9e3a774f6e9cd51e16d68e457a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2019-03-28T06:47:20.404736+02:00", 
    "title": "Калорійність", 
    "date": "2019-03-28T06:47:20.349883+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "c17fa52911844d7387b8446638b0fdde", 
    "questionOf": "tender"
  }
}

