PATCH /api/2.4/tenders/73a450aa50d44d2d820e3de760464c72/questions/f0b4690659df497cbfd25f117f5e05d1?acc_token=28085084532948b6a59f88f952000daa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2018-08-14T19:03:57.331473+03:00", 
    "title": "Калорійність", 
    "date": "2018-08-14T19:03:57.214021+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "f0b4690659df497cbfd25f117f5e05d1", 
    "questionOf": "tender"
  }
}

