GET /api/2.4/tenders/73a450aa50d44d2d820e3de760464c72 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/73a450aa50d44d2d820e3de760464c72", 
    "enquiryPeriod": {
      "startDate": "2018-07-31T19:03:39.833852+03:00", 
      "endDate": "2018-08-07T19:03:39.833852+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-08-14T19:39:39.833852+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2018-08-14T19:03:57.331473+03:00", 
        "title": "Калорійність", 
        "date": "2018-08-14T19:03:57.214021+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "f0b4690659df497cbfd25f117f5e05d1", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "73a450aa50d44d2d820e3de760464c72", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "document description modified", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/d7d30c35ce31410c8209c8b0e8bf3609?KeyID=912fcd33&Signature=uE1zpBLAU2icckAXtMpe57aBPvAGnjsB5hm4vkAH0btm%2F4hHNiUv8VkeA%2FteHHex1wJeCVRE97GZTvK%2FEyrcAQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-14T19:03:56.615797+03:00", 
        "author": "tender_owner", 
        "documentType": "technicalSpecifications", 
        "id": "da071f29bd024efa8b63b7ccae6b100c", 
        "dateModified": "2018-08-14T19:03:56.615818+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/3c59070e3956488d976a77b6f481b5f9?KeyID=912fcd33&Signature=BsACh3n6AmP3JdR54GbfGtduazt2oC%252B0zevXE9u40oVRv8UOriFv0SsbKkxmq2J02Nzcp31dtuOxswjE2yW0CQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-14T19:03:56.955332+03:00", 
        "id": "cf96ecef4ac24f6a876972ae07ff746e", 
        "dateModified": "2018-08-14T19:03:56.955353+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/5006630773334b4a81fe0e22febec56a?KeyID=912fcd33&Signature=gxuZ42uaOU29tCCTT6F%252BK%252Brjo6FMKpAmqn5og7wvwuMu%2FtL0CC89oNG%2FYj4MFAvNFSq4muw0g8vWk9dK9frgDA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-14T19:03:56.955332+03:00", 
        "id": "cf96ecef4ac24f6a876972ae07ff746e", 
        "dateModified": "2018-08-14T19:03:57.081622+03:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderID": "UA-2018-08-14-000001", 
    "dateModified": "2018-08-14T19:03:58.376741+03:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2018-08-07T19:03:39.833852+03:00", 
      "endDate": "2018-08-14T19:03:39.833852+03:00"
    }, 
    "auctionPeriod": {
      "startDate": "2018-08-14T19:03:39.833852+03:00", 
      "shouldStartAfter": "2018-08-15T00:00:00+03:00"
    }, 
    "procurementMethodType": "belowThreshold", 
    "date": "2018-08-14T19:03:55.834503+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-08-16T19:03:39.833852+03:00", 
          "endDate": "2018-08-19T19:03:39.833852+03:00"
        }, 
        "id": "9567dc9ea31b4e8caa35ad3f19d5e12a", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

