GET /api/2.5/tenders/c144d0002ce84223b070a0f3dd0e4b96 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "funders": [
      {
        "contactPoint": {
          "url": "https://www.theglobalfund.org/en/", 
          "email": "ccm@theglobalfund.org", 
          "telephone": "+41 58 791 1700", 
          "name": "", 
          "faxNumber": "+41 44 580 6820"
        }, 
        "identifier": {
          "scheme": "XM-DAC", 
          "id": "47045", 
          "legalName": "Глобальний Фонд для боротьби зі СНІДом, туберкульозом і малярією"
        }, 
        "name": "Глобальний фонд", 
        "address": {
          "postalCode": "1218", 
          "countryName": "Switzerland", 
          "streetAddress": "Global Health Campus, Chemin du Pommier 40", 
          "region": "Grand-Saconnex", 
          "locality": "Geneva"
        }
      }
    ], 
    "procurementMethod": "open", 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/c144d0002ce84223b070a0f3dd0e4b96", 
    "enquiryPeriod": {
      "startDate": "2019-03-04T09:26:15.267842+02:00", 
      "endDate": "2019-03-11T09:26:15.267842+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-03-18T10:02:15.267842+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-03-18T09:26:26.737375+02:00", 
        "title": "Калорійність", 
        "date": "2019-03-18T09:26:26.696138+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "feceebd2f52f4f249c276849c38bdb12", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "c144d0002ce84223b070a0f3dd0e4b96", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "document description modified", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/38d35c7276b741a880393eb16b98c7a6?KeyID=2a7aab19&Signature=DIkEl1mY9kB9ck6tkbSfPYWO10OFtt%252BaHW5vWjHFsjN%252Bx4l0vKaEsacqlQxItNZiX%252BX9lR6LCTi%252Bp4yPGbeDCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:26.490921+02:00", 
        "author": "tender_owner", 
        "documentType": "technicalSpecifications", 
        "id": "a7db6924f00c4d6881ab41998c11065d", 
        "dateModified": "2019-03-18T09:26:26.490941+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/3634eb224ade41859f1c0c2f6c9cb955?KeyID=2a7aab19&Signature=x0uU5rcbegV%252B7UY6vjEMnZeYjO5d8zEQIb7j11%252BSRdg4XNHrXhkskHMbImAooJe63rDnvfpk91LeNlpcu%252B2gCQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:26.598986+02:00", 
        "id": "0a8161e0d8d44ff589b01e5164eb3f95", 
        "dateModified": "2019-03-18T09:26:26.599000+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/fac00d6642194fae91854efa0ad578d3?KeyID=2a7aab19&Signature=%2FHQciudh29E7rRg5r21fI1mVX8VpATgw32TJ3B5auoSPHDZBq3A3n0pYw9NhQd9YiFvBEow%2FJa%2F2YVKw3tbKBA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:26.598986+02:00", 
        "id": "0a8161e0d8d44ff589b01e5164eb3f95", 
        "dateModified": "2019-03-18T09:26:26.644157+02:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderID": "UA-2019-03-18-000001", 
    "dateModified": "2019-03-18T09:26:27.208125+02:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2019-03-11T09:26:15.267842+02:00", 
      "endDate": "2019-03-18T09:26:15.267842+02:00"
    }, 
    "auctionPeriod": {
      "startDate": "2019-03-18T09:26:15.267842+02:00", 
      "shouldStartAfter": "2019-03-19T00:00:00+02:00"
    }, 
    "procurementMethodType": "belowThreshold", 
    "date": "2019-03-18T09:26:26.125997+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-20T09:26:15.267842+02:00", 
          "endDate": "2019-03-23T09:26:15.267842+02:00"
        }, 
        "id": "0a8503018b1d477a953f6c0666dc66dc", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }, 
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-20T09:26:15.267842+02:00", 
          "endDate": "2019-03-23T09:26:15.267842+02:00"
        }, 
        "id": "57ab505c29004d7797c055e405f774a7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

