GET /api/2.5/tenders/e370d1ede4574bb8aebd9cd6976fd5f8/bids/52449e36dab845f9be9b0c127d838af9?acc_token=91dcc75d681d451ab8f2d1c1a9ab82a0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e370d1ede4574bb8aebd9cd6976fd5f8/bids/52449e36dab845f9be9b0c127d838af9/documents/de7b6cb5343a43ea9c5a458be921d599?download=3b61262d3abc4f6ba38b9db66d2df41e", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:10:00+03:00", 
        "id": "de7b6cb5343a43ea9c5a458be921d599", 
        "dateModified": "2019-04-01T01:10:00+03:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-04-01T01:10:00+03:00", 
    "id": "52449e36dab845f9be9b0c127d838af9", 
    "participationUrl": "http://auction-sandbox.prozorro.gov.ua/tenders/e370d1ede4574bb8aebd9cd6976fd5f8?key_for_bid=52449e36dab845f9be9b0c127d838af9"
  }
}

