GET /api/2.5/tenders/c144d0002ce84223b070a0f3dd0e4b96/bids/33fde7eb77c44772a33e71ba45511839?acc_token=7ee3fe6524e8478a9cbfbbe5b31463b2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/c144d0002ce84223b070a0f3dd0e4b96/bids/33fde7eb77c44772a33e71ba45511839/documents/12ec3e2c4c2b40159608a547db4f157a?download=8f5993cbd3bf4d9094a78a8cbd8695cc", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:26.943546+02:00", 
        "id": "12ec3e2c4c2b40159608a547db4f157a", 
        "dateModified": "2019-03-18T09:26:26.943564+02:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-03-18T09:26:26.831616+02:00", 
    "id": "33fde7eb77c44772a33e71ba45511839", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/c144d0002ce84223b070a0f3dd0e4b96?key_for_bid=33fde7eb77c44772a33e71ba45511839"
  }
}

