GET /api/2.5/tenders/386592f3dce34fd89c6dd9e0e73855a8/bids/2d661a6d4df840dca51dec5065df7ce2?acc_token=8119fa02b8ac4d058072e8a7c07d6dae HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/386592f3dce34fd89c6dd9e0e73855a8/bids/2d661a6d4df840dca51dec5065df7ce2/documents/6ffc890ad40b4205bbd9d070fb263b27?download=72e54142363b4d1da65b7020806a47b0", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-19T16:42:29.480063+02:00", 
        "id": "6ffc890ad40b4205bbd9d070fb263b27", 
        "dateModified": "2019-03-19T16:42:29.480083+02:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-03-19T16:42:29.187587+02:00", 
    "id": "2d661a6d4df840dca51dec5065df7ce2", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/386592f3dce34fd89c6dd9e0e73855a8?key_for_bid=2d661a6d4df840dca51dec5065df7ce2"
  }
}

