PATCH /api/2.4/tenders/a9fa8c33df924d25b648931e89bd8ea8/awards/29a8f3118a6b4e03add227da7b71a44f?acc_token=b3696ab04e114fd79a1f01177d689f22 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2019-02-06T06:09:49.557780+02:00", 
      "endDate": "2019-02-08T06:09:49.645613+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "bid_id": "ab6a1288ecdc4e9f92f3b8b5f58886bc", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-02-06T06:09:49.649557+02:00", 
    "id": "29a8f3118a6b4e03add227da7b71a44f"
  }
}

