PATCH /api/2.4/tenders/da9e871316f3458da1a38198d0fcaf58/awards/791820972e054ac795cdb7b240b21aad?acc_token=557900748f364b7394e7efc706b1375e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2018-08-14T18:53:09.049479+03:00", 
      "endDate": "2018-08-16T18:53:09.225981+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "bid_id": "cdc92710133e4534bfd13de0595a32c3", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-14T18:53:09.230012+03:00", 
    "id": "791820972e054ac795cdb7b240b21aad"
  }
}

