POST /api/2.5/tenders?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 4342
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "funders": [
      {
        "additionalIdentifiers": [], 
        "contactPoint": {
          "url": "https://www.theglobalfund.org/en/", 
          "faxNumber": "+41 44 580 6820", 
          "telephone": "+41 58 791 1700", 
          "name": "", 
          "email": "ccm@theglobalfund.org"
        }, 
        "identifier": {
          "scheme": "XM-DAC", 
          "id": "47045", 
          "legalName": "Глобальний Фонд для боротьби зі СНІДом, туберкульозом і малярією"
        }, 
        "name": "Глобальний фонд", 
        "address": {
          "countryName": "Switzerland", 
          "postalCode": "1218", 
          "region": "Grand-Saconnex", 
          "streetAddress": "Global Health Campus, Chemin du Pommier 40", 
          "locality": "Geneva"
        }
      }
    ], 
    "tenderPeriod": {
      "endDate": "2019-04-11T06:47:07.288622"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "enquiryPeriod": {
      "endDate": "2019-04-04T06:47:07.288622"
    }, 
    "procurementMethodType": "belowThreshold", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "id": "44617100-9", 
          "description": "Cartons"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-30T06:47:07.288622", 
          "endDate": "2019-04-02T06:47:07.288622"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }, 
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "id": "44617100-9", 
          "description": "Cartons"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-30T06:47:07.288622", 
          "endDate": "2019-04-02T06:47:07.288622"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ]
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/3c1bde5dd8b94e82a5ccfd5780d245ed

{
  "access": {
    "token": "83acd335af6b4cc4a5336fd3cb6f0b27"
  }, 
  "data": {
    "funders": [
      {
        "contactPoint": {
          "url": "https://www.theglobalfund.org/en/", 
          "email": "ccm@theglobalfund.org", 
          "telephone": "+41 58 791 1700", 
          "name": "", 
          "faxNumber": "+41 44 580 6820"
        }, 
        "identifier": {
          "scheme": "XM-DAC", 
          "id": "47045", 
          "legalName": "Глобальний Фонд для боротьби зі СНІДом, туберкульозом і малярією"
        }, 
        "name": "Глобальний фонд", 
        "address": {
          "postalCode": "1218", 
          "countryName": "Switzerland", 
          "streetAddress": "Global Health Campus, Chemin du Pommier 40", 
          "region": "Grand-Saconnex", 
          "locality": "Geneva"
        }
      }
    ], 
    "procurementMethod": "open", 
    "awardCriteria": "lowestCost", 
    "tenderPeriod": {
      "startDate": "2019-04-04T06:47:07.288622+03:00", 
      "endDate": "2019-04-11T06:47:07.288622+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-30T06:47:07.288622+02:00", 
          "endDate": "2019-04-02T06:47:07.288622+03:00"
        }, 
        "id": "4556cf309b7e42adb6c087cbd09bc29a", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }, 
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-30T06:47:07.288622+02:00", 
          "endDate": "2019-04-02T06:47:07.288622+03:00"
        }, 
        "id": "9b65e80c367c4a658dae2ae83a0e9084", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "procurementMethodType": "belowThreshold", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2019-03-28T06:47:19.778158+02:00", 
    "dateModified": "2019-03-28T06:47:19.780746+02:00", 
    "status": "active.enquiries", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "enquiryPeriod": {
      "startDate": "2019-03-28T06:47:19.778091+02:00", 
      "endDate": "2019-04-04T06:47:07.288622+03:00"
    }, 
    "owner": "broker", 
    "next_check": "2019-04-04T06:47:07.288622+03:00", 
    "id": "3c1bde5dd8b94e82a5ccfd5780d245ed", 
    "tenderID": "UA-2019-03-28-000003"
  }
}

