GET /api/2.5/tenders/cfe8d9ecde7d49cba990bed08065d7d4/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "dateAnswered": "2019-01-01T00:10:00+02:00", 
      "title": "Калорійність", 
      "date": "2019-01-01T00:10:00+02:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "cf05e478c9744a3db1542bb2243bce86", 
      "questionOf": "tender"
    }
  ]
}

