GET /api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "dateAnswered": "2019-04-01T01:10:00+03:00", 
      "title": "Калорійність", 
      "date": "2019-04-01T01:10:00+03:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "5095c548ac884ac6b57bc6998b40fe47", 
      "questionOf": "tender"
    }
  ]
}

