PATCH /api/2.4/tenders/da9e871316f3458da1a38198d0fcaf58/cancellations/85cd5c74349742338213a5c2e0f86c65/documents/a3c7d1f79ce14aabb62758de273fed4c?acc_token=557900748f364b7394e7efc706b1375e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "Changed description"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/2649ccbdffc14f7bb14f9dab5c49dd19?KeyID=a384cf0c&Signature=kkgisc5VPwzXvsJGN%2FUQe%2FS3CTbUNT6KfGyidFtOlo7pz9TXq2BGOxOhUaXQF4f5ZxXTDozl4yVJG7hx5pPFBA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-14T18:53:11.065496+03:00", 
    "id": "a3c7d1f79ce14aabb62758de273fed4c", 
    "dateModified": "2018-08-14T18:53:11.065515+03:00"
  }
}

