POST /api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/cancellations?acc_token=39ff2f89f67742519e7b78cad264aeac HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/cancellations/af04938817b746ce8f3757db71cbd7d3
{
  "data": {
    "date": "2019-04-01T01:00:03+03:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "af04938817b746ce8f3757db71cbd7d3"
  }
}

