POST /api/2.4/tenders/da9e871316f3458da1a38198d0fcaf58/cancellations?acc_token=557900748f364b7394e7efc706b1375e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reason": "cancellation reason"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/da9e871316f3458da1a38198d0fcaf58/cancellations/85cd5c74349742338213a5c2e0f86c65

{
  "data": {
    "date": "2018-08-14T18:53:10.943728+03:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "85cd5c74349742338213a5c2e0f86c65"
  }
}

