POST /api/2.5/tenders/e370d1ede4574bb8aebd9cd6976fd5f8/cancellations?acc_token=855549743758426abe02dad7618aea90 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e370d1ede4574bb8aebd9cd6976fd5f8/cancellations/206e63f9048a441c8d641f9604fdf59c
{
  "data": {
    "date": "2019-04-01T01:30:00+03:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "206e63f9048a441c8d641f9604fdf59c"
  }
}

