POST /api/2.4/tenders/2208281bd1694de2a6f4b2fa36d47a52/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1367
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/5fc503bad46c488ea67de7134b151f8d?KeyID=2c53b94d&Signature=rGoeTSbh8wAhQCIlRrUy7Tmk26SNXeFljWjLsAd9fgas4xU3NT4X5Eqa7JKlhyfBZTKQBD9ExQ5zJy0F0QwvAg%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/e7ae2b31556245f5993528f9e56ed862?KeyID=2c53b94d&Signature=Cr2qhM4OLpSXjrQuJw5Q9ePWehrASstHq4a3Hj%2Br4%2FWkI3CF24J16WOg3VXlXjqgeUXK5qVjQozuASRMp0SxDQ%3D%3D", 
        "title": "Proposal_part2.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "value": {
      "amount": 499
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк", 
          "email": "aagt@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/2208281bd1694de2a6f4b2fa36d47a52/bids/b9f6f012de8a4777bb67a422b0cac295

{
  "access": {
    "token": "160c2472972d4c628700f217ba4c16b4"
  }, 
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/2208281bd1694de2a6f4b2fa36d47a52/bids/b9f6f012de8a4777bb67a422b0cac295/documents/e2c0ef487c3a497a960d6f3f6da5bdcd?download=5fc503bad46c488ea67de7134b151f8d", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:23:16.597574+03:00", 
        "id": "e2c0ef487c3a497a960d6f3f6da5bdcd", 
        "dateModified": "2018-09-21T05:23:16.597612+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/2208281bd1694de2a6f4b2fa36d47a52/bids/b9f6f012de8a4777bb67a422b0cac295/documents/6db1e6900eb648a1b733bfee05285d06?download=e7ae2b31556245f5993528f9e56ed862", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:23:16.598526+03:00", 
        "id": "6db1e6900eb648a1b733bfee05285d06", 
        "dateModified": "2018-09-21T05:23:16.598562+03:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2018-09-21T05:23:16.596301+03:00", 
    "id": "b9f6f012de8a4777bb67a422b0cac295"
  }
}

