POST /api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1377
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "documents": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/bedb498035d14457a2ff19f714e66742?KeyID=a8968c46&Signature=ROYWP6tfJHpdZepAkTYPekeNA90ZB%2F6YOxWU5fRn0stnJmJppRNEqZTyTLXnuF1Vxkcv6Avq6rj5B9FWrVdGAA%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0cdf947d136649f69f7899ad3a397f35?KeyID=a8968c46&Signature=t4tlxjgotIowcY%2BHYRxz8VmhqoWflMtYcsJZgfytDfo75h2MOP0GAWnGRjXfqhgBd0j7cv%2BGQIA31oM3hGwtCw%3D%3D", 
        "title": "Proposal_part2.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "value": {
      "amount": 499
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/bids/dd2dfd7fc83b40f08daeaeaf947bf53c
{
  "access": {
    "token": "c2a1bc4376d84a01a52a0fa53f4d4862"
  }, 
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part1.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/bids/dd2dfd7fc83b40f08daeaeaf947bf53c/documents/9d2e753fda8242e3b39e80713ce4b01f?download=bedb498035d14457a2ff19f714e66742", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:01+03:00", 
        "id": "9d2e753fda8242e3b39e80713ce4b01f", 
        "dateModified": "2019-04-01T01:00:01+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal_part2.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/bids/dd2dfd7fc83b40f08daeaeaf947bf53c/documents/7e09f0eb2da8400cbfd4fc9cdf4cc25f?download=0cdf947d136649f69f7899ad3a397f35", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:01+03:00", 
        "id": "7e09f0eb2da8400cbfd4fc9cdf4cc25f", 
        "dateModified": "2019-04-01T01:00:01+03:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-04-01T01:00:01+03:00", 
    "id": "dd2dfd7fc83b40f08daeaeaf947bf53c"
  }
}

