GET /api/2.4/tenders?mode=__all__ HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "next_page": {
    "path": "/api/2.4/tenders?offset=2018-08-14T18%3A53%3A06.087894%2B03%3A00", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.4/tenders?offset=2018-08-14T18%3A53%3A06.087894%2B03%3A00", 
    "offset": "2018-08-14T18:53:06.087894+03:00"
  }, 
  "data": [
    {
      "id": "da9e871316f3458da1a38198d0fcaf58", 
      "dateModified": "2018-08-14T18:53:06.087894+03:00"
    }
  ]
}

