PATCH /api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/contracts/c5e474c0f1da4c11890902435e04748d?acc_token=c51d5449ff804fa4a8f52a47ac9fc180 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_first_document.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b14d108d05334ed5aacb7326035f26e5?KeyID=a8968c46&Signature=X0xheEdgbLr18jrKKbXPer0ClEWO4dUlpxf%2FCdw2%252BGa2D%2FNatZX%2FQOhmWulUnTUmexxeAwcR7f61Z7iDw49TBQ%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:30:00+03:00", 
        "id": "49a28ee57dc54341b0121a1820155824", 
        "dateModified": "2019-04-01T01:30:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_second_document.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/41d50bd754e14c399f7168a9dd7cae58?KeyID=a8968c46&Signature=91HzI%2FiYzzJmMvEo3VYrnVjN7bVaxWMleRwCZ1YafT2YBZKNkK%2F%2FzPwx44HOqiaiOzhMNCJo5eUanzulSZcuDw%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:30:00+03:00", 
        "id": "37987725166a4af28590bd85396d9fb6", 
        "dateModified": "2019-04-01T01:30:00+03:00"
      }
    ], 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-03T01:00:00+03:00", 
          "endDate": "2019-04-06T01:00:00+03:00"
        }, 
        "id": "a5ae5e7676734c5aba4e4aa6277b9af0", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "period": {
      "startDate": "2019-04-01T01:30:00+03:00", 
      "endDate": "2020-03-31T01:30:00+03:00"
    }, 
    "dateSigned": "2019-04-01T01:30:00+03:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-04-01T01:30:00+03:00", 
    "awardID": "3d7b07d9d3524ac9bf10984a45d34b13", 
    "id": "c5e474c0f1da4c11890902435e04748d", 
    "contractID": "UA-2019-04-01-000001-1"
  }
}

