PATCH /api/2.4/tenders/73a450aa50d44d2d820e3de760464c72/contracts/abe0ff951bf6433fb53085525b5f18d2?acc_token=28085084532948b6a59f88f952000daa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 73
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "contractNumber": "contract #13111", 
    "value": {
      "amount": 238
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-08-16T19:03:39.833852+03:00", 
          "endDate": "2018-08-19T19:03:39.833852+03:00"
        }, 
        "id": "9567dc9ea31b4e8caa35ad3f19d5e12a", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-14T19:03:58.951008+03:00", 
    "awardID": "e6eeb30c967441998088d785f4d33a87", 
    "id": "abe0ff951bf6433fb53085525b5f18d2", 
    "contractID": "UA-2018-08-14-000001-1"
  }
}

