GET /api/2.5/tenders/c144d0002ce84223b070a0f3dd0e4b96/contracts/edc4be4a366243ecad844076b67f778e/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_first_document.doc", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/e86942da8bb04bd1a6acc1ee56e60a60?KeyID=2a7aab19&Signature=wYPxSDhy6IXXX64GJNP%2FGKyXfg4kTGjyVBLu6d3U7epi4NVInHWip3PS6bMUz2%252BKpGwf7%2F8YcZUZn8oB%252BVnXDQ%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2019-03-18T09:26:27.876266+02:00", 
      "id": "86ff8973497941b3b3ec28f94dfd8e82", 
      "dateModified": "2019-03-18T09:26:27.876279+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_second_document.doc", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/918f6abb3a874b3d8da70f0d287949bf?KeyID=2a7aab19&Signature=2atO9wDwoAu1PLNniMSxd06XeJa1J66OBRfx8LAgLfkjSMDdaS4WHlFG5HMV5F7uKi%2FuACUWbPFm8gH9lMF%252BAw%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2019-03-18T09:26:27.981954+02:00", 
      "id": "5ad565faa2d34f008a548fe7bcdcbf96", 
      "dateModified": "2019-03-18T09:26:27.981968+02:00"
    }
  ]
}

