PATCH /api/2.4/tenders/2208281bd1694de2a6f4b2fa36d47a52/contracts/a7a897a41257418a8f4e24d924064278?acc_token=96e4d8f1b0524eae8883e050dace84d7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 91
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "contractNumber": "contract #13111", 
    "value": {
      "amount": 238, 
      "amountNet": 230
    }
  }
}


200 OK
Content-Type: application/json

{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-23T05:22:56.321617+03:00", 
          "endDate": "2018-09-26T05:22:56.321617+03:00"
        }, 
        "id": "379f7b47fc5a4a1094b2ce88b68eab58", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-09-21T05:23:17.853704+03:00", 
    "awardID": "4108fea15d8345cc8dc01f40bd66c504", 
    "id": "a7a897a41257418a8f4e24d924064278", 
    "contractID": "UA-2018-09-21-000001-1"
  }
}

