GET /api/2.4/tenders/a9fa8c33df924d25b648931e89bd8ea8/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/728d579316ad494099a426df1e5c44f5?KeyID=dfcba93d&Signature=WPjkOTwWQHchhRpvgPq84VL3ZmcGljXOKBT9iAsq0%252BtdZCACtqeya05QjsyO%252BYFk%2FiQzXKApW0WiUfSQnIJrDQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-02-06T06:09:48.820233+02:00", 
      "author": "tender_owner", 
      "documentType": "technicalSpecifications", 
      "id": "23c8ccc49569450d895a5abe20c6a1b8", 
      "dateModified": "2019-02-06T06:09:48.820246+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/a83e1bf8525040c5a3d8174a88046f00?KeyID=dfcba93d&Signature=S7DC4zq%252BiUCtz0qrypoMhDR3DBky6o8DIu8fhWBV45yjadlXog%2FZu691662fxW0VtSdK%2FHeghFtjRlnYe0BMDQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-02-06T06:09:48.915551+02:00", 
      "id": "d10e3115509c499680dfbe91bcf3e0e4", 
      "dateModified": "2019-02-06T06:09:48.915565+02:00"
    }
  ]
}

