PATCH /api/2.4/tenders/16873c1122b54ba29b5b450904d9c659/contracts/199eaa0d62614fe994695d8a7c579200?acc_token=1fdd8971eef14852a98fb3a6bcf43a71 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 91
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "contractNumber": "contract #13111", 
    "value": {
      "amount": 238, 
      "amountNet": 230
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-07T03:22:02.453878+03:00", 
          "endDate": "2018-09-10T03:22:02.453878+03:00"
        }, 
        "id": "7bc6adfc389848eda0876cefcc0d0244", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-09-05T03:22:16.449062+03:00", 
    "awardID": "af8dbd8c321b4b4ca6877461d22ba897", 
    "id": "199eaa0d62614fe994695d8a7c579200", 
    "contractID": "UA-2018-09-05-000001-1"
  }
}

