GET /api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9d6aa744b5b84cabbd238ffd59f47f59?KeyID=a8968c46&Signature=iBhdFaNxJwyzltVkJPbJgBykVrz27dIndnK1tZLjDbYFmuEREt8i5nsNzsOvhKOuyg5ODeur4WyoT6DV9JiyBA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:10:00+03:00", 
      "id": "93160afc024a49118333d1f355d960f6", 
      "dateModified": "2019-04-01T01:10:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/43bf8d44f69a45a1be501ef8543fe888?KeyID=a8968c46&Signature=V0A%252BnAfQdFw5QGH1bCI8GX909z9NcfPdxtEYuncC6YkYpZQUvpv866phhVa45bh4e0luFbN%2F3o7qJjmZIy3aDw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:10:00+03:00", 
      "author": "tender_owner", 
      "documentType": "technicalSpecifications", 
      "id": "1cacd13139d34e8596ca5b500043714b", 
      "dateModified": "2019-04-01T01:10:00+03:00"
    }
  ]
}

