GET /api/2.5/tenders/c144d0002ce84223b070a0f3dd0e4b96/documents/a7db6924f00c4d6881ab41998c11065d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/38d35c7276b741a880393eb16b98c7a6?KeyID=2a7aab19&Signature=DIkEl1mY9kB9ck6tkbSfPYWO10OFtt%252BaHW5vWjHFsjN%252Bx4l0vKaEsacqlQxItNZiX%252BX9lR6LCTi%252Bp4yPGbeDCw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-18T09:26:26.490921+02:00", 
    "previousVersions": [], 
    "id": "a7db6924f00c4d6881ab41998c11065d", 
    "dateModified": "2019-03-18T09:26:26.490941+02:00"
  }
}

