GET /api/2.5/tenders HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "next_page": {
    "path": "/api/2.5/tenders?offset=2019-01-01T00%3A00%3A00%2B02%3A00", 
    "uri": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders?offset=2019-01-01T00%3A00%3A00%2B02%3A00", 
    "offset": "2019-01-01T00:00:00+02:00"
  }, 
  "data": [
    {
      "id": "cfe8d9ecde7d49cba990bed08065d7d4", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }
  ]
}

