POST /api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/contracts/c5e474c0f1da4c11890902435e04748d/documents?acc_token=39ff2f89f67742519e7b78cad264aeac HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 348
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b14d108d05334ed5aacb7326035f26e5?KeyID=a8968c46&Signature=zbRhlNr4c%2BvngNKt4roTKUkN%2Fjwr%2F6CsnBOaQhcoMjpXyCHO%2FGM1cll3kDmG2vIrClr6RsumBzUoAg9F%2Bi8ABA%3D%3D", 
    "title": "contract_first_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/contracts/c5e474c0f1da4c11890902435e04748d/documents/49a28ee57dc54341b0121a1820155824
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "contract_first_document.doc", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b14d108d05334ed5aacb7326035f26e5?KeyID=a8968c46&Signature=X0xheEdgbLr18jrKKbXPer0ClEWO4dUlpxf%2FCdw2%252BGa2D%2FNatZX%2FQOhmWulUnTUmexxeAwcR7f61Z7iDw49TBQ%253D%253D", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:03+03:00", 
    "id": "49a28ee57dc54341b0121a1820155824", 
    "dateModified": "2019-04-01T01:00:03+03:00"
  }
}

