GET /api/2.5/tenders/cfe8d9ecde7d49cba990bed08065d7d4/contracts/5edfcbe1d28046cd8e72d8e8847c3ece/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_first_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f49bdb61f7e94de582d7ec5762f17174?KeyID=573d3072&Signature=9hMg1lbkP0p8tglGVxUAwybnNKXOvnpih7ND9kuEktfN7FlPgVfB5UsfpqVRE9D6wLCEZdpKH8CZYuBvXxYkCg%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2019-01-01T00:30:00+02:00", 
      "id": "210f09eec10141c885a7b8fa26f01f29", 
      "dateModified": "2019-01-01T00:30:00+02:00"
    }
  ]
}

