GET /api/2.4/tenders/a9fa8c33df924d25b648931e89bd8ea8/contracts/2773dd7c20af4e7e83ff45104ee38463/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_first_document.doc", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/783b337b07374355b6fda62eaa88bc36?KeyID=dfcba93d&Signature=CMLy%2FCYonoDN7i%252BJRp6SCcbmcfb2mYEzQ46wjki2zZ2%2F%252BnO50ji7pgbhqol2SvgSs9c5m9Kufo5pAOKLmlaDDQ%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2019-02-06T06:09:49.959722+02:00", 
      "id": "d3ad1d37f3a54f05870a6fe20a3b2240", 
      "dateModified": "2019-02-06T06:09:49.959735+02:00"
    }
  ]
}

