GET /api/2.5/tenders/cfe8d9ecde7d49cba990bed08065d7d4/documents/0306df77df5448f08bc6cb08a74bf597 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/8803fb0b09964b7c96a5e6a52976da42?KeyID=573d3072&Signature=dH9ANSpDIk0%252BYialLPmTKuvab283b8TY%252Be5P3fqR%2FkfpYyiflPE7%2F9VWOV3ihkyRjoXMCT5ht6t6yaQcWyOUAw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "previousVersions": [], 
    "id": "0306df77df5448f08bc6cb08a74bf597", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

