PATCH /api/2.4/tenders/da9e871316f3458da1a38198d0fcaf58/contracts/a378dd35721644708cbc762b9b165908?acc_token=557900748f364b7394e7efc706b1375e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 106
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "period": {
      "startDate": "2018-08-14T18:52:49.860459", 
      "endDate": "2019-08-14T18:52:49.860459"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-08-16T18:52:49.842199+03:00", 
          "endDate": "2018-08-19T18:52:49.842199+03:00"
        }, 
        "id": "3a2e75048a7849639e8b79d7d34cde99", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "period": {
      "startDate": "2018-08-14T18:52:49.860459+03:00", 
      "endDate": "2019-08-14T18:52:49.860459+03:00"
    }, 
    "dateSigned": "2018-08-14T18:53:09.609056+03:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-14T18:53:09.226036+03:00", 
    "awardID": "791820972e054ac795cdb7b240b21aad", 
    "id": "a378dd35721644708cbc762b9b165908", 
    "contractID": "UA-2018-08-14-000001-1"
  }
}

