GET /api/2.4/tenders/2208281bd1694de2a6f4b2fa36d47a52/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/d986273d14ad47018cb49da369c61087?KeyID=2c53b94d&Signature=XY59s0VSZCutqyWE6zUb5Yiq4vMcEkfStWzPoKpBCNzIJEIBeubPAOHWlBHk8FhbjOrZQvDVImFoTG%2FyzSY5AA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-09-21T05:23:14.858132+03:00", 
      "author": "tender_owner", 
      "documentType": "technicalSpecifications", 
      "id": "1123ef527e2e4bc5a8a49c6944472a44", 
      "dateModified": "2018-09-21T05:23:14.858177+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/dc2eb809bedf40ca8640c2d61795d80c?KeyID=2c53b94d&Signature=MJuUvD8BqPe1mgfrIp3k6di0wCXWuVdNgudoQtfRHb9oamxOxkataNd0tJf%252BD%252BpLJdWBViDX94U%2FrMAmJgwWDw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-09-21T05:23:15.243398+03:00", 
      "id": "2b6d4e9cc0404c84a34f25f8352c7ad1", 
      "dateModified": "2018-09-21T05:23:15.243456+03:00"
    }
  ]
}

