PATCH /api/2.4/tenders/a9fa8c33df924d25b648931e89bd8ea8/contracts/2773dd7c20af4e7e83ff45104ee38463?acc_token=b3696ab04e114fd79a1f01177d689f22 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "dateSigned": "2019-02-06T06:09:50.129183+02:00"
  }
}


200 OK
Content-Type: application/json

{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_first_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/783b337b07374355b6fda62eaa88bc36?KeyID=dfcba93d&Signature=CMLy%2FCYonoDN7i%252BJRp6SCcbmcfb2mYEzQ46wjki2zZ2%2F%252BnO50ji7pgbhqol2SvgSs9c5m9Kufo5pAOKLmlaDDQ%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2019-02-06T06:09:49.959722+02:00", 
        "id": "d3ad1d37f3a54f05870a6fe20a3b2240", 
        "dateModified": "2019-02-06T06:09:49.959735+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_second_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/1fe83ab1b257418d900de1461da18c50?KeyID=dfcba93d&Signature=E1DF%2FMMSbSa7aUhhCGDJEU5PQ9Nurot9z99fuTB%2FyW6jD%2FdxJWBGZRx3nRhpauYBgqzEnmXY10MEs8S7CmdHAQ%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2019-02-06T06:09:50.057317+02:00", 
        "id": "c04eeccc238a4051a628f1347c9a205f", 
        "dateModified": "2019-02-06T06:09:50.057331+02:00"
      }
    ], 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-02-08T06:09:42.495419+02:00", 
          "endDate": "2019-02-11T06:09:42.495419+02:00"
        }, 
        "id": "f3eb6ded8773482cb1f1e837f84965ba", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract #13111", 
    "period": {
      "startDate": "2019-02-06T06:09:42.534031+02:00", 
      "endDate": "2020-02-06T06:09:42.534031+02:00"
    }, 
    "dateSigned": "2019-02-06T06:09:50.129183+02:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-02-06T06:09:49.645671+02:00", 
    "awardID": "29a8f3118a6b4e03add227da7b71a44f", 
    "id": "2773dd7c20af4e7e83ff45104ee38463", 
    "contractID": "UA-2019-02-06-000001-1"
  }
}

