GET /api/2.5/tenders/386592f3dce34fd89c6dd9e0e73855a8/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description modified", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/a19303446b6b4360920842741cbccff3?KeyID=6de3e88f&Signature=vs7JmyOnnZw8WcpGZTWJlHKTiaLDVNjUKGO9%2FyleT2YMLgUliSutfkBQqJRUJVvC53jtkP93PF2NnjhnW9QqBA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-03-19T16:42:27.997749+02:00", 
      "author": "tender_owner", 
      "documentType": "technicalSpecifications", 
      "id": "e5fa1208b4b1486795e5790401a9a38f", 
      "dateModified": "2019-03-19T16:42:27.997909+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/9289a7f847a7428e932a832664a51e26?KeyID=6de3e88f&Signature=OslXlAh2kAfjGtmnswKsSPaHrOFN%2Fl2gG0NgaS9E6mUbhSR0Wv8%252Brg6Ab4N7a3aUp5shseil82QXwRXfYW4EBw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-03-19T16:42:28.404000+02:00", 
      "id": "ae64f18303cc40a0a17806cf3b36fcd7", 
      "dateModified": "2019-03-19T16:42:28.523723+02:00"
    }
  ]
}

