PUT /api/2.5/tenders/4e72a84032424e519ab51eb3c1c98dbf/cancellations/dbe979d8f0884b62a4a0b0653d1a5590/documents/0120ed6a34c24558afd4fb809c035ea0?acc_token=40505a9e3a774f6e9cd51e16d68e457a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 330
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/004e1041fe6b456c87e9d49227d08ef5?KeyID=782d7111&Signature=0KXUkEkWJwp04U5d1qwMWS%2BCvrEHl4%2BiHA897cOR8UIwuSBxlA8nCDYoQh2MayZkBXgoOg2QiLcKJg%2BOVWA1Dg%3D%3D", 
    "title": "Notice-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice-2.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/004e1041fe6b456c87e9d49227d08ef5?KeyID=782d7111&Signature=kcOFE5krAJI1w4H0j%2FHy0j00zymn%252B8fj%2FEfMxOISvKCTkO5nJoO6WZ4MGYuGXb8BXEZUgwynqkksSr32GyzrDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-28T06:47:22.470510+02:00", 
    "id": "0120ed6a34c24558afd4fb809c035ea0", 
    "dateModified": "2019-03-28T06:47:22.680469+02:00"
  }
}

