PUT /api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/documents/93160afc024a49118333d1f355d960f6?acc_token=39ff2f89f67742519e7b78cad264aeac HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 333
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9d6aa744b5b84cabbd238ffd59f47f59?KeyID=a8968c46&Signature=6NWJpWbHib5uCRpxa2Kxp5yL7LoYx5%2FW%2FbLaMeD0bdYOhnEyO7QNTK2Wv26t%2BxS94arvQiFDydqNVYnoWF9HBQ%3D%3D", 
    "title": "AwardCriteria-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9d6aa744b5b84cabbd238ffd59f47f59?KeyID=a8968c46&Signature=iBhdFaNxJwyzltVkJPbJgBykVrz27dIndnK1tZLjDbYFmuEREt8i5nsNzsOvhKOuyg5ODeur4WyoT6DV9JiyBA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:01+03:00", 
    "id": "93160afc024a49118333d1f355d960f6", 
    "dateModified": "2019-04-01T01:00:01+03:00"
  }
}

