PUT /api/2.4/tenders/a9fa8c33df924d25b648931e89bd8ea8/documents/d10e3115509c499680dfbe91bcf3e0e4?acc_token=b3696ab04e114fd79a1f01177d689f22 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 339
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/9236d378fcc4449c99ddecf7ee46c1ae?KeyID=dfcba93d&Signature=VU38froNvqSLW%2FVwJVI9CoLrGdE8%2FkzagwfXZzUNMHqnaudsTptKPKj5VfHqUHV2%2BYCw8oHN%2FN8MoP6N7fUUCA%3D%3D", 
    "title": "AwardCriteria-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/9236d378fcc4449c99ddecf7ee46c1ae?KeyID=dfcba93d&Signature=1rzPYS%2F7eYlVwbH8QA%2F85AeTVOTcAMGIUCsdaIBZY1eLvgOzY44UPJ9ZYbPbnn%2FfBMqq8nPXkPCuQoujcC7oBA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-02-06T06:09:48.915551+02:00", 
    "id": "d10e3115509c499680dfbe91bcf3e0e4", 
    "dateModified": "2019-02-06T06:09:48.953953+02:00"
  }
}

