POST /api/2.4/tenders/73a450aa50d44d2d820e3de760464c72/documents?acc_token=28085084532948b6a59f88f952000daa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 330
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/d7d30c35ce31410c8209c8b0e8bf3609?KeyID=912fcd33&Signature=F7girpLSgGQazwIY%2B9s9d%2F%2Fg1Vq5c3rNuEfoKuKiYdlrHRRsrK0SWADeriYA2pI9jobtxkEGtSMuFq4G%2BkDFBQ%3D%3D", 
    "title": "Notice.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/73a450aa50d44d2d820e3de760464c72/documents/da071f29bd024efa8b63b7ccae6b100c

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/d7d30c35ce31410c8209c8b0e8bf3609?KeyID=912fcd33&Signature=uE1zpBLAU2icckAXtMpe57aBPvAGnjsB5hm4vkAH0btm%2F4hHNiUv8VkeA%2FteHHex1wJeCVRE97GZTvK%2FEyrcAQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-14T19:03:56.615797+03:00", 
    "id": "da071f29bd024efa8b63b7ccae6b100c", 
    "dateModified": "2018-08-14T19:03:56.615818+03:00"
  }
}

