POST /api/2.5/tenders/4e72a84032424e519ab51eb3c1c98dbf/documents?acc_token=40505a9e3a774f6e9cd51e16d68e457a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 324
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/7f582c3fe17b4d22b312206e40e7abba?KeyID=782d7111&Signature=kQsDro%2BJNcXb3dlk9aZ51rtDPtGSVn88icHMFLLe18nC6u79QCRI6tPRJxIwHW39mYLTUoetSkfsDgILa6GZDA%3D%3D", 
    "title": "Notice.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/4e72a84032424e519ab51eb3c1c98dbf/documents/a0e07c2c12d44f9fbe3d0ffe229dcd94

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/7f582c3fe17b4d22b312206e40e7abba?KeyID=782d7111&Signature=bEWrpMB9DsLPKl1CX%252Bbu%2FAQOLwn1iYOGs5XdYflV6gnCvHJpl%252Byil2E83ks1EyFWvbQd6zFXlQ2kYh29LHO8DA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-28T06:47:20.089427+02:00", 
    "id": "a0e07c2c12d44f9fbe3d0ffe229dcd94", 
    "dateModified": "2019-03-28T06:47:20.089447+02:00"
  }
}

