POST /api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/documents?acc_token=c51d5449ff804fa4a8f52a47ac9fc180 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 324
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/43bf8d44f69a45a1be501ef8543fe888?KeyID=a8968c46&Signature=V9H2EZgo%2FASHAfLhAeG8yOG3ov7VLBmz91FZ7KVMSl2ykKOm7JCT3sPGvZbaSN%2BVsUMQXWNCH7cIOaCPzoz%2BDQ%3D%3D", 
    "title": "Notice.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/2fc8039bb7864bfabe6dc2c3ab451b69/documents/1cacd13139d34e8596ca5b500043714b
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/43bf8d44f69a45a1be501ef8543fe888?KeyID=a8968c46&Signature=V0A%252BnAfQdFw5QGH1bCI8GX909z9NcfPdxtEYuncC6YkYpZQUvpv866phhVa45bh4e0luFbN%2F3o7qJjmZIy3aDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:01+03:00", 
    "id": "1cacd13139d34e8596ca5b500043714b", 
    "dateModified": "2019-04-01T01:00:01+03:00"
  }
}

