PATCH /api/2.5/tenders/d4132712eb7b4d3f91083564bc1ddf26/bids/db9c3692e9e34e789d708bf8d92c9a04?acc_token=dc28318f3f344c729239495a0ef58d46 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 124
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "cd0a788afea24ea0a3d145f1702f419f", 
        "value": {
          "amount": 500
        }
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "cd0a788afea24ea0a3d145f1702f419f", 
        "date": "2019-04-01T01:00:00+03:00", 
        "status": "pending", 
        "value": {
          "yearlyPaymentsPercentage": 0.9, 
          "valueAddedTaxIncluded": true, 
          "currency": "UAH", 
          "amount": 9629.01, 
          "contractDuration": {
            "days": 0, 
            "years": 7
          }, 
          "amountPerformance": 2015.18, 
          "annualCostsReduction": [
            700.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0
          ]
        }
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "db9c3692e9e34e789d708bf8d92c9a04"
  }
}

