GET /api/2.5/tenders/8999a1d343ba4c6b8a32f33256fb9aa5/bids/23b00365f9d147a18ddfdc71de93df8b?acc_token=555d1e43603e4aaeb81bd19f274698d2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "23b00365f9d147a18ddfdc71de93df8b"
  }
}

