PATCH /api/2.5/tenders/a5737d7e05a4451a8a502a9d763357f0/bids/cd09b8b5ea5b4259a2128e077ae0e557?acc_token=1fce02a0714b42b893df6ba28b879de2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 124
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "b7292dba1ee3436db63fee17b2d09579", 
        "value": {
          "amount": 500
        }
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "b7292dba1ee3436db63fee17b2d09579", 
        "date": "2019-03-28T06:49:20.720130+02:00", 
        "status": "pending", 
        "value": {
          "yearlyPaymentsPercentage": 0.9, 
          "valueAddedTaxIncluded": true, 
          "currency": "UAH", 
          "amount": 9613.23, 
          "contractDuration": {
            "days": 0, 
            "years": 7
          }, 
          "amountPerformance": 2013.75, 
          "annualCostsReduction": [
            700.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0
          ]
        }
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-03-28T06:49:20.719909+02:00", 
    "id": "cd09b8b5ea5b4259a2128e077ae0e557"
  }
}

