GET /api/2.5/tenders/e54514398db3478a934ed7e8472b1516/bids/431dc9a9dfaf485ab1a030f0d3bf89d8?acc_token=a45b9ab6009f495d9305aaa4a9b452ae HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "431dc9a9dfaf485ab1a030f0d3bf89d8"
  }
}

