POST /api/2.5/tenders/8999a1d343ba4c6b8a32f33256fb9aa5/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1188
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "selfQualified": true, 
    "lotValues": [
      {
        "relatedLot": "5b14a30befc1462385a1fe5aaa823e39", 
        "value": {
          "contractDuration": {
            "years": 7
          }, 
          "yearlyPaymentsPercentage": 0.87, 
          "annualCostsReduction": [
            200, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000, 
            1000
          ]
        }, 
        "subcontractingDetails": "ДКП «Орфей», Україна"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк", 
          "email": "soleksuk@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/8999a1d343ba4c6b8a32f33256fb9aa5/bids/23b00365f9d147a18ddfdc71de93df8b
{
  "access": {
    "token": "555d1e43603e4aaeb81bd19f274698d2"
  }, 
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "5b14a30befc1462385a1fe5aaa823e39", 
        "date": "2019-03-18T16:13:30.900934+02:00", 
        "status": "pending", 
        "value": {
          "yearlyPaymentsPercentage": 0.87, 
          "valueAddedTaxIncluded": true, 
          "currency": "UAH", 
          "amount": 5577.53, 
          "contractDuration": {
            "days": 0, 
            "years": 7
          }, 
          "amountPerformance": 1321.16, 
          "annualCostsReduction": [
            200.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0, 
            1000.0
          ]
        }, 
        "subcontractingDetails": "ДКП «Орфей», Україна"
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-03-18T16:13:30.900542+02:00", 
    "id": "23b00365f9d147a18ddfdc71de93df8b"
  }
}

