POST /api/2.4/tenders/924cca868371469cac978bd088aab46a/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1454
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "selfQualified": true, 
    "lotValues": [
      {
        "relatedLot": "b95d552463884b6db822a57c4242db3d", 
        "value": {
          "contractDuration": {
            "years": 7
          }, 
          "yearlyPaymentsPercentage": 0.9, 
          "annualCostsReduction": [
            700, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600, 
            1600
          ]
        }
      }, 
      {
        "relatedLot": "79259e73f9cc4b4baacc326e2e6e8f8e", 
        "value": {
          "contractDuration": {
            "years": 9
          }, 
          "yearlyPaymentsPercentage": 0.96, 
          "annualCostsReduction": [
            600, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200, 
            1200
          ]
        }, 
        "subcontractingDetails": "ДКП «Укр Прінт», Україна"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк", 
          "email": "aagt@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/924cca868371469cac978bd088aab46a/bids/40e444895cf5484597aad433b5af63f8
{
  "access": {
    "token": "dae3506208d3444194d0587c3171e3dc"
  }, 
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "b95d552463884b6db822a57c4242db3d", 
        "date": "2018-09-21T05:47:29.614328+03:00", 
        "status": "pending", 
        "value": {
          "yearlyPaymentsPercentage": 0.9, 
          "valueAddedTaxIncluded": true, 
          "currency": "UAH", 
          "amount": 10311.53, 
          "contractDuration": {
            "days": 0, 
            "years": 7
          }, 
          "amountPerformance": 2082.16, 
          "annualCostsReduction": [
            700.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0, 
            1600.0
          ]
        }
      }, 
      {
        "relatedLot": "79259e73f9cc4b4baacc326e2e6e8f8e", 
        "date": "2018-09-21T05:47:29.616432+03:00", 
        "status": "pending", 
        "value": {
          "yearlyPaymentsPercentage": 0.96, 
          "valueAddedTaxIncluded": true, 
          "currency": "UAH", 
          "amount": 10625.23, 
          "contractDuration": {
            "days": 0, 
            "years": 9
          }, 
          "amountPerformance": 914.87, 
          "annualCostsReduction": [
            600.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0, 
            1200.0
          ]
        }, 
        "subcontractingDetails": "ДКП «Укр Прінт», Україна"
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2018-09-21T05:47:29.613685+03:00", 
    "id": "40e444895cf5484597aad433b5af63f8"
  }
}

