PATCH /api/2.4/tenders/924cca868371469cac978bd088aab46a/lots/79259e73f9cc4b4baacc326e2e6e8f8e?acc_token=3503d77e5e194549816da4b6afeae452 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 39
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "minValue": {
      "amount": 400
    }
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №2", 
    "fundingKind": "other", 
    "title": "Лот №2", 
    "auctionPeriod": {
      "shouldStartAfter": "2018-11-27T00:00:00+03:00"
    }, 
    "minValue": {
      "currency": "UAH", 
      "amount": 0.0, 
      "valueAddedTaxIncluded": true
    }, 
    "minimalStepPercentage": 0.006, 
    "yearlyPaymentsPercentageRange": 0.8, 
    "date": "2018-09-21T05:47:28.828530+03:00", 
    "id": "79259e73f9cc4b4baacc326e2e6e8f8e"
  }
}

