PATCH /api/2.5/tenders/860d74a785364c238fc2e06190d4c25d/qualifications/b5f773c5fad742339924ed1d47682257?acc_token=6fe807aaf8204458b6b0b3ca4e5fe9b3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "lotID": "c610d778e48445eda6c38b497d348925", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "57488ff8930c45f38b782a50340d0664", 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "b5f773c5fad742339924ed1d47682257"
  }
}

