PATCH /api/2.5/tenders/d4132712eb7b4d3f91083564bc1ddf26/qualifications/f5c3b02421bd43ddb248df9091b3f6ed?acc_token=8dbe405e21b44fb7b40a411b4a9fa159 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "lotID": "cd0a788afea24ea0a3d145f1702f419f", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "c6b567442dcb492d8873bd698420ceaa", 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "f5c3b02421bd43ddb248df9091b3f6ed"
  }
}

