GET /api/2.5/tenders/8999a1d343ba4c6b8a32f33256fb9aa5?acc_token=5603313b6b9c44f98724fb5b84e2adf5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification", 
    "complaintPeriod": {
      "startDate": "2019-02-16T16:13:33.574083+02:00", 
      "endDate": "2019-03-14T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-02-16T16:13:33.574083+02:00", 
      "clarificationsUntil": "2019-03-14T00:00:00+02:00", 
      "endDate": "2019-03-08T16:13:33.574083+02:00", 
      "invalidationDate": "2019-03-18T16:13:31.948073+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "8999a1d343ba4c6b8a32f33256fb9aa5", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "fundingKind": "other", 
        "title": "Лот №1", 
        "minValue": {
          "currency": "UAH", 
          "amount": 0.0, 
          "valueAddedTaxIncluded": true
        }, 
        "minimalStepPercentage": 0.006, 
        "yearlyPaymentsPercentageRange": 0.8, 
        "date": "2019-03-18T16:13:30.054523+02:00", 
        "id": "5b14a30befc1462385a1fe5aaa823e39"
      }, 
      {
        "status": "unsuccessful", 
        "description": "Опис Лот №2", 
        "fundingKind": "other", 
        "title": "Лот №2", 
        "minValue": {
          "currency": "UAH", 
          "amount": 0.0, 
          "valueAddedTaxIncluded": true
        }, 
        "minimalStepPercentage": 0.006, 
        "yearlyPaymentsPercentageRange": 0.8, 
        "date": "2019-03-18T16:13:34.173563+02:00", 
        "id": "6d27b81f6f0642469a135f3e154ed51a"
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2019-03-18T16:13:34.094066+02:00"
    }, 
    "tenderID": "UA-2019-03-18-000001", 
    "minimalStepPercentage": 0.006, 
    "yearlyPaymentsPercentageRange": 0.8, 
    "dateModified": "2019-03-18T16:13:34.173563+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2019-02-16T16:13:33.574083+02:00", 
      "endDate": "2019-03-18T16:13:33.574083+02:00"
    }, 
    "qualifications": [
      {
        "status": "pending", 
        "lotID": "5b14a30befc1462385a1fe5aaa823e39", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "23b00365f9d147a18ddfdc71de93df8b", 
        "date": "2019-03-18T16:13:34.101748+02:00", 
        "id": "7ffac4e9273a439c973929d42f25cc7c"
      }, 
      {
        "status": "pending", 
        "lotID": "5b14a30befc1462385a1fe5aaa823e39", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "fc288f42cd7d48d48b3c526252028985", 
        "date": "2019-03-18T16:13:34.103627+02:00", 
        "id": "c212becea5ec4daba58c13cf8d1515ea"
      }
    ], 
    "procurementMethodType": "esco", 
    "date": "2019-03-18T16:13:34.173563+02:00", 
    "NBUdiscountRate": 0.22986, 
    "minValue": {
      "currency": "UAH", 
      "amount": 0.0, 
      "valueAddedTaxIncluded": true
    }, 
    "fundingKind": "other", 
    "items": [
      {
        "relatedLot": "5b14a30befc1462385a1fe5aaa823e39", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "c4b006c6e5624067accf6391b481e96a", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }
      }, 
      {
        "relatedLot": "6d27b81f6f0642469a135f3e154ed51a", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "cafd934d9f9843c5b82551e03d9ae85f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }
      }
    ], 
    "bids": [
      {
        "status": "pending", 
        "id": "23b00365f9d147a18ddfdc71de93df8b", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "pending", 
        "id": "fc288f42cd7d48d48b3c526252028985", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }
    ], 
    "noticePublicationDate": "2019-03-18T16:13:29.854229+02:00", 
    "awardCriteria": "ratedCriteria"
  }
}

