PATCH /api/2.4/tenders/277e62dfb09742939184a9c5082f5ab1/cancellations/38d203e7c3f04b76ad3bca583319ce12?acc_token=e8509ae132974f299912390eb918c9d8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "description": "Changed description", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/277e62dfb09742939184a9c5082f5ab1/cancellations/38d203e7c3f04b76ad3bca583319ce12/documents/9346f33ba39e476486843b78ae753c4f?download=a4806ab64ea24197ab7242fbc5303ff3", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:26:11.058916+03:00", 
        "id": "9346f33ba39e476486843b78ae753c4f", 
        "dateModified": "2018-09-21T05:26:11.058972+03:00"
      }, 
      {
        "description": "Changed description", 
        "title": "Notice-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/277e62dfb09742939184a9c5082f5ab1/cancellations/38d203e7c3f04b76ad3bca583319ce12/documents/9346f33ba39e476486843b78ae753c4f?download=eeb30f120a2749d6a5c4a9947902c99b", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:26:11.058916+03:00", 
        "id": "9346f33ba39e476486843b78ae753c4f", 
        "dateModified": "2018-09-21T05:26:11.386538+03:00"
      }
    ], 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2018-09-21T05:26:11.606285+03:00", 
    "cancellationOf": "tender", 
    "id": "38d203e7c3f04b76ad3bca583319ce12"
  }
}

