POST /api/2.5/tenders/1fcdcf96493f4d77a683da7811e1753b/awards?acc_token=360cf0f8387c4d5b9e989a121ed3f5e6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1282
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "date": "2016-01-14T18:07:00.628073+02:00", 
    "status": "pending", 
    "suppliers": [
      {
        "contactPoint": {
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк", 
          "email": "soleksuk@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "id": "d373338bc3324f14b8b3d4af68922773", 
    "value": {
      "currency": "UAH", 
      "amount": 475000, 
      "valueAddedTaxIncluded": true
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/1fcdcf96493f4d77a683da7811e1753b/awards/a37aeb242dcf492b8d41c36739346e70
{
  "data": {
    "status": "pending", 
    "complaintPeriod": {
      "startDate": "2019-03-28T06:49:39.513790+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-28T06:49:39.512839+02:00", 
    "id": "a37aeb242dcf492b8d41c36739346e70"
  }
}

