PATCH /api/2.4/tenders/444a3230914b45558d9f9ef5e63a535f/awards/164da4d604384410939e007400f32562/complaints/7fd26cf1a9ab45a49e665a053507bf8d?acc_token=cedcc39931ad4b8d8784c71d04509c90 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "scale": "micro", 
      "name": "ДКП «Школяр»", 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2019-02-06T06:11:19.817101+02:00", 
    "complaintID": "UA-2019-02-06-000001.7", 
    "date": "2019-02-06T06:11:19.822291+02:00", 
    "type": "complaint", 
    "id": "7fd26cf1a9ab45a49e665a053507bf8d"
  }
}

