POST /api/2.4/tenders/e69456ad48d24ef3897ea666d6dc691a/awards/fbfdbeb2319d45e88dadfdbf62dbc017/complaints HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1682
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "author": {
      "contactPoint": {
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк", 
        "email": "soleksuk@gmail.com"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }, 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/e69456ad48d24ef3897ea666d6dc691a/awards/fbfdbeb2319d45e88dadfdbf62dbc017/complaints/a627c8793f9145b2b885db15617bc3db
{
  "access": {
    "token": "8c02c6b1b8854065bae4b9303c3bc2df"
  }, 
  "data": {
    "status": "draft", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "complaintID": "UA-2018-09-21-000001.1", 
    "date": "2018-09-21T05:26:27.619911+03:00", 
    "type": "complaint", 
    "id": "a627c8793f9145b2b885db15617bc3db"
  }
}

