GET /api/2.5/tenders/b5ebaee7fd9741fcae5aaa5a1410f6b4/awards/0dcca3f213cf40e9b6516f8eecbef9b1/complaints HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "satisfied", 
      "dateDecision": "2019-01-01T00:10:00+02:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5eedb5d0e7fc4a05988a892531bfeaf7?KeyID=ffd8d102&Signature=X9CDSrLsW%252BXyS2h7oBzUqklT1epR514gkjY59BxrWmnAAW7AxWEHUNyeHwexpJL8Cn%2FjNZ7ezWSWskHuXiYICA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-01-01T00:10:00+02:00", 
          "id": "761c4499f51e4c89b99002e7a4a7d2dc", 
          "dateModified": "2019-01-01T00:10:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/b99ad52f1e8f4f1387607ec7ba880251?KeyID=ffd8d102&Signature=mdoQBuz8KaLQh9ZXN%252BSKyfZl%2Fa3XgvUMOvbymb9alxDSHQVAOwktt13aSR5XhObNogwKe6jqcqIh3XeFksDHAw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-01-01T00:10:00+02:00", 
          "id": "6076fbf524c547b39d1967eba9fc8794", 
          "dateModified": "2019-01-01T00:10:00+02:00"
        }
      ], 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateAccepted": "2019-01-01T00:10:00+02:00", 
      "dateSubmitted": "2019-01-01T00:10:00+02:00", 
      "complaintID": "UA-2019-01-01-000001.1", 
      "date": "2019-01-01T00:10:00+02:00", 
      "acceptance": true, 
      "type": "complaint", 
      "id": "e42bbe96edfd42b19d58b42939b44694"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2019-01-01T00:10:00+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2019-01-01T00:10:00+02:00", 
      "complaintID": "UA-2019-01-01-000001.2", 
      "date": "2019-01-01T00:10:00+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "b4d81a2c86644574a99536f5cf734d91"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2019-01-01T00:10:00+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2019-01-01T00:10:00+02:00", 
      "dateSubmitted": "2019-01-01T00:10:00+02:00", 
      "complaintID": "UA-2019-01-01-000001.3", 
      "date": "2019-01-01T00:10:00+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "8e25e6bd700b41e29184038b0bcac867"
    }, 
    {
      "status": "accepted", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2019-01-01T00:10:00+02:00", 
      "dateSubmitted": "2019-01-01T00:10:00+02:00", 
      "complaintID": "UA-2019-01-01-000001.4", 
      "date": "2019-01-01T00:10:00+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "45f2ba6521154ee9aeeb90fcff046abf"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-01-01T00:10:00+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2019-01-01T00:10:00+02:00", 
      "dateAccepted": "2019-01-01T00:10:00+02:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-01-01T00:10:00+02:00", 
      "complaintID": "UA-2019-01-01-000001.5", 
      "date": "2019-01-01T00:10:00+02:00", 
      "type": "complaint", 
      "id": "2dcb5e8c90f849bdb822868627b6ecc0"
    }
  ]
}

