PATCH /api/2.5/tenders/1fcdcf96493f4d77a683da7811e1753b/awards/d181505e4a4e489db422c9d5229e5c53/complaints/eccda54a01034ac59de2f0d7711613fa?acc_token=360cf0f8387c4d5b9e989a121ed3f5e6 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 361
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "resolved", 
    "tendererAction": "Умови виправлено, вибір переможня буде розгянуто повторно"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "dateDecision": "2019-03-28T06:49:38.985835+02:00", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/1fcdcf96493f4d77a683da7811e1753b/awards/d181505e4a4e489db422c9d5229e5c53/complaints/eccda54a01034ac59de2f0d7711613fa/documents/8495e9c58fc1473282fc5f9301f124fc?download=2f5f2fbaf21244b9b5424b5ffe9fc715", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:49:38.067458+02:00", 
        "id": "8495e9c58fc1473282fc5f9301f124fc", 
        "dateModified": "2019-03-28T06:49:38.067480+02:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/1fcdcf96493f4d77a683da7811e1753b/awards/d181505e4a4e489db422c9d5229e5c53/complaints/eccda54a01034ac59de2f0d7711613fa/documents/c731770f6e374a6a8b8c683fcbfa2f13?download=de12f1ea135840c39e4d74e55a8f0aac", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:49:38.879491+02:00", 
        "id": "c731770f6e374a6a8b8c683fcbfa2f13", 
        "dateModified": "2019-03-28T06:49:38.879549+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "tendererAction": "Умови виправлено, вибір переможня буде розгянуто повторно", 
    "tendererActionDate": "2019-03-28T06:49:39.621707+02:00", 
    "dateSubmitted": "2019-03-28T06:49:38.123529+02:00", 
    "complaintID": "UA-2019-03-28-000001.1", 
    "date": "2019-03-28T06:49:39.626097+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "eccda54a01034ac59de2f0d7711613fa", 
    "dateAccepted": "2019-03-28T06:49:38.550101+02:00"
  }
}

