PATCH /api/2.4/tenders/4d6faa01d3a749e686880b9e3b2d2d19/awards/f84073df8598447a8cc6720d0e187606/complaints/59c79c21d9594e75a19be306491ffd6b HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 217
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "stopped", 
    "decision": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "stopped", 
    "dateDecision": "2018-08-15T10:28:41.150867+03:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "decision": "Тендер скасовується замовником", 
    "acceptance": true, 
    "cancellationReason": "Тендер скасовується замовником", 
    "dateCanceled": "2018-08-15T10:28:41.001199+03:00", 
    "dateAccepted": "2018-08-15T10:28:39.435985+03:00", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2018-08-15T10:28:38.663358+03:00", 
    "complaintID": "UA-2018-08-15-000001.4", 
    "date": "2018-08-15T10:28:41.155710+03:00", 
    "type": "complaint", 
    "id": "59c79c21d9594e75a19be306491ffd6b"
  }
}

