POST /api/2.5/tenders/f47b72d7038b4fee8f4e54dd929385bd/awards/186a24bf1898451488731088dd71f908/complaints/729344721bff4cee98e4dcff3e1ed1ae/documents?acc_token=e80485efb78f4f198471d917107fae0c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 151
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/f47b72d7038b4fee8f4e54dd929385bd/awards/186a24bf1898451488731088dd71f908/complaints/729344721bff4cee98e4dcff3e1ed1ae/documents/44b80c37bd104e6b9e31378ec38ef053
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/96009f501632419fa2419da84922c313?KeyID=a8968c46&Signature=Y%2FqAHiUURFF5Onir7D7J23u8VLMfFpshkbjowTXCOG6YngpEn6W4qCfySskKM8SXZydhcqviyMoqIm2UiouhAg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "44b80c37bd104e6b9e31378ec38ef053", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

