PATCH /api/2.5/tenders/1fcdcf96493f4d77a683da7811e1753b/awards/a37aeb242dcf492b8d41c36739346e70/complaints/47dabcd40aaa4cc4905d74cb196ff2c4?acc_token=7521475b7fd34fbb8edf9b6e51353d5c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2019-03-28T06:49:40.316426+02:00", 
    "complaintID": "UA-2019-03-28-000001.7", 
    "date": "2019-03-28T06:49:40.322105+02:00", 
    "type": "complaint", 
    "id": "47dabcd40aaa4cc4905d74cb196ff2c4"
  }
}

