PATCH /api/2.5/tenders/3bc87b3141e649b7a6a1c01d5ea04e3a/awards/6f6e613c4aaf4531845fc0e5d7bb0775/complaints/b3f54f20432040a4beaa599ca118a846 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 217
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "stopped", 
    "decision": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "stopped", 
    "dateDecision": "2019-03-18T09:27:36.700286+02:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "decision": "Тендер скасовується замовником", 
    "acceptance": true, 
    "cancellationReason": "Тендер скасовується замовником", 
    "dateCanceled": "2019-03-18T09:27:36.615364+02:00", 
    "dateAccepted": "2019-03-18T09:27:35.758167+02:00", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2019-03-18T09:27:35.400748+02:00", 
    "complaintID": "UA-2019-03-18-000001.4", 
    "date": "2019-03-18T09:27:36.704059+02:00", 
    "type": "complaint", 
    "id": "b3f54f20432040a4beaa599ca118a846"
  }
}

