PATCH /api/2.4/tenders/e69456ad48d24ef3897ea666d6dc691a/awards/fbfdbeb2319d45e88dadfdbf62dbc017/complaints/3104caaaa72f42c9a29d7f793cb3f36b HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "declined"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "declined", 
    "dateDecision": "2018-09-21T05:26:30.351329+03:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "dateAccepted": "2018-09-21T05:26:29.304231+03:00", 
    "dateSubmitted": "2018-09-21T05:26:28.282830+03:00", 
    "complaintID": "UA-2018-09-21-000001.3", 
    "date": "2018-09-21T05:26:30.359302+03:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "3104caaaa72f42c9a29d7f793cb3f36b"
  }
}

