POST /api/2.5/tenders/3bc87b3141e649b7a6a1c01d5ea04e3a/awards/6f6e613c4aaf4531845fc0e5d7bb0775/complaints HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1703
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "pending", 
    "title": "Недостатньо інформації", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк", 
        "email": "soleksuk@gmail.com"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/3bc87b3141e649b7a6a1c01d5ea04e3a/awards/6f6e613c4aaf4531845fc0e5d7bb0775/complaints/6e25e02b313542279b15a7733364d1c2
{
  "access": {
    "token": "a11d733e0efc44a3ad7eba287311f921"
  }, 
  "data": {
    "status": "pending", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "dateSubmitted": "2019-03-18T09:27:35.290005+02:00", 
    "complaintID": "UA-2019-03-18-000001.2", 
    "date": "2019-03-18T09:27:35.289990+02:00", 
    "type": "complaint", 
    "id": "6e25e02b313542279b15a7733364d1c2"
  }
}

