PATCH /api/2.4/tenders/e69456ad48d24ef3897ea666d6dc691a/awards/fbfdbeb2319d45e88dadfdbf62dbc017/complaints/a627c8793f9145b2b885db15617bc3db HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "satisfied"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2018-09-21T05:26:30.132716+03:00", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/e69456ad48d24ef3897ea666d6dc691a/awards/fbfdbeb2319d45e88dadfdbf62dbc017/complaints/a627c8793f9145b2b885db15617bc3db/documents/777e70768e114ca7a2f2a462228034e7?download=e8d7c0b9c6f84133811582113bf0cb6e", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:26:27.801671+03:00", 
        "id": "777e70768e114ca7a2f2a462228034e7", 
        "dateModified": "2018-09-21T05:26:27.801728+03:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/e69456ad48d24ef3897ea666d6dc691a/awards/fbfdbeb2319d45e88dadfdbf62dbc017/complaints/a627c8793f9145b2b885db15617bc3db/documents/eb2b682b60a2476f98dc2b00c38e842b?download=b4fb45bbb65941dfa58ab74affeb2ce8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:26:29.911998+03:00", 
        "id": "eb2b682b60a2476f98dc2b00c38e842b", 
        "dateModified": "2018-09-21T05:26:29.912059+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2018-09-21T05:26:29.091376+03:00", 
    "dateSubmitted": "2018-09-21T05:26:27.995689+03:00", 
    "complaintID": "UA-2018-09-21-000001.1", 
    "date": "2018-09-21T05:26:30.139041+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "a627c8793f9145b2b885db15617bc3db"
  }
}

