PATCH /api/2.5/tenders/411eba73a7e241eab1e17cf80cbe33c6/cancellations/e76fb74733a14d6da0cd563107141e61/documents/a6dd62cb4a174821ac66f0b1d90ae5be?acc_token=aa8f9663e1ac4382ac0d69917f93e5f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/95a3fcbd4c3f472c889c9363b6b8ef90?KeyID=a8968c46&Signature=gydp5%2FK8927wAY4nE0PWP%2Fq3fU0%2FIzGPTJwiy0hXJU2kV1wz9t0uVq3WNbXOSC9%252BP0Mhp487HU9bGlPAZKZbDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:10:00+03:00", 
    "id": "a6dd62cb4a174821ac66f0b1d90ae5be", 
    "dateModified": "2019-04-01T01:10:00+03:00"
  }
}

