PATCH /api/2.5/tenders/279d5688a5e943168632df3b5d169d63/cancellations/1801b1c29b8145a99ef19f50a1a92104/documents/ab68cc0013ab4bd9af7ae07d99d35a6b?acc_token=7ee2cdca6b0d482f9449372b899ea5c8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d1b986f18bf340e48ec25d1e9080205a?KeyID=e2e24154&Signature=PO8C1%2FGZ%2FHzloWeKrU8%2Fo%2FYC94XW2pVk7jeauv93ZpYNncqnE9OSA3v027Yz0Bk3uU77YcVHfOv6ZrMsbxanCA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "ab68cc0013ab4bd9af7ae07d99d35a6b", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

