PATCH /api/2.4/tenders/4f128d1939fa467e84f2bea0edecb23b/cancellations/7975a967b0704a6281d3f1ab97763a5c/documents/b631532a4b2547c19d47d03544ae306e?acc_token=c41e24d4bfb946e2a9f424ba724ba862 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/4f128d1939fa467e84f2bea0edecb23b/cancellations/7975a967b0704a6281d3f1ab97763a5c/documents/b631532a4b2547c19d47d03544ae306e?download=b556e83034ec4929aeb8de07376638bc", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-15T10:29:06.700788+03:00", 
    "id": "b631532a4b2547c19d47d03544ae306e", 
    "dateModified": "2018-08-15T10:29:06.700815+03:00"
  }
}

