POST /api/2.5/tenders/411eba73a7e241eab1e17cf80cbe33c6/cancellations?acc_token=aa8f9663e1ac4382ac0d69917f93e5f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/411eba73a7e241eab1e17cf80cbe33c6/cancellations/e76fb74733a14d6da0cd563107141e61
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2019-04-01T01:10:00+03:00", 
    "cancellationOf": "tender", 
    "id": "e76fb74733a14d6da0cd563107141e61"
  }
}

