POST /api/2.4/tenders/277e62dfb09742939184a9c5082f5ab1/cancellations?acc_token=e8509ae132974f299912390eb918c9d8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/277e62dfb09742939184a9c5082f5ab1/cancellations/38d203e7c3f04b76ad3bca583319ce12
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2018-09-21T05:26:10.749220+03:00", 
    "cancellationOf": "tender", 
    "id": "38d203e7c3f04b76ad3bca583319ce12"
  }
}

