PATCH /api/2.5/tenders/8ebbedbb7e114716a175fa053af7cda6/contracts/065161db6ca14f6c858c1d37613650d6?acc_token=cd8238cb6f7449eeab3bfcf5cd5d6579 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "contract_first_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/8ebbedbb7e114716a175fa053af7cda6/contracts/065161db6ca14f6c858c1d37613650d6/documents/058f38eabeaf417eba945f324785a9ca?download=5f59550c3eaa41e58f7daea17f4c660f", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:49:31.273916+02:00", 
        "id": "058f38eabeaf417eba945f324785a9ca", 
        "dateModified": "2019-03-28T06:49:31.273942+02:00"
      }, 
      {
        "title": "contract_second_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/8ebbedbb7e114716a175fa053af7cda6/contracts/065161db6ca14f6c858c1d37613650d6/documents/028b32b1fcc145548dac655a39c8ec28?download=fe38e893ad794cb293b3098a499e0f49", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:49:31.343343+02:00", 
        "id": "028b32b1fcc145548dac655a39c8ec28", 
        "dateModified": "2019-03-28T06:49:31.343367+02:00"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-30T06:47:08.632098+02:00", 
          "endDate": "2019-04-02T06:47:08.632098+03:00"
        }, 
        "description_ru": "Услуги школьных столовых", 
        "id": "2dc54675d6364e2baffbc0f8e74432ac", 
        "unit": {
          "code": "MON", 
          "name": "month", 
          "value": {
            "currency": "UAH", 
            "amount": 12.0, 
            "valueAddedTaxIncluded": true
          }
        }, 
        "quantity": 9.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "period": {
      "startDate": "2019-03-28T06:47:08.632098+02:00", 
      "endDate": "2020-03-27T06:47:08.632098+02:00"
    }, 
    "dateSigned": "2019-03-28T06:47:08.632098+02:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-28T06:49:31.432313+02:00", 
    "awardID": "ab93425d1b974090bbcf0c97e20269d7", 
    "id": "065161db6ca14f6c858c1d37613650d6", 
    "contractID": "UA-2019-03-28-000001-1"
  }
}

