PATCH /api/2.4/tenders/4f128d1939fa467e84f2bea0edecb23b/awards/ccc66eb6b0724166972b55eb6376170b?acc_token=c41e24d4bfb946e2a9f424ba724ba862 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "award_first_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/4f128d1939fa467e84f2bea0edecb23b/awards/ccc66eb6b0724166972b55eb6376170b/documents/b2a848d82adc46d6b15df3142255c245?download=d606d3deed924436983171690a3a0127", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:29:04.677226+03:00", 
        "id": "b2a848d82adc46d6b15df3142255c245", 
        "dateModified": "2018-08-15T10:29:04.677250+03:00"
      }, 
      {
        "title": "award_second_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/4f128d1939fa467e84f2bea0edecb23b/awards/ccc66eb6b0724166972b55eb6376170b/documents/d904431c969643afbfc24acdfbc8bbb0?download=5276cb1fa38b47e787c287c883795d8a", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:29:04.823959+03:00", 
        "id": "d904431c969643afbfc24acdfbc8bbb0", 
        "dateModified": "2018-08-15T10:29:04.823983+03:00"
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-15T10:29:04.975008+03:00", 
    "id": "ccc66eb6b0724166972b55eb6376170b"
  }
}

