POST /api/2.5/tenders/279d5688a5e943168632df3b5d169d63/awards?acc_token=7ee2cdca6b0d482f9449372b899ea5c8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 812
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "pending", 
    "suppliers": [
      {
        "contactPoint": {
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк", 
          "email": "soleksuk@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000, 
      "valueAddedTaxIncluded": true
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/279d5688a5e943168632df3b5d169d63/awards/fa1bbbea9ef84ff2a45e2ea91ad27237
{
  "data": {
    "status": "pending", 
    "date": "2019-01-01T00:00:00+02:00", 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "id": "fa1bbbea9ef84ff2a45e2ea91ad27237", 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }
  }
}

