PATCH /api/2.4/tenders/233d6809342d4f118e5ae90c58a50d0e/contracts/dfd7c78f071c46e9a2383d2b27b3e052?acc_token=0d1a3368e41f487da8cb7ca4474c715c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 106
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "period": {
      "startDate": "2018-08-15T10:28:21.528967", 
      "endDate": "2019-08-15T10:28:21.528967"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-08-17T10:28:21.528967+03:00", 
          "endDate": "2018-08-20T10:28:21.528967+03:00"
        }, 
        "description_ru": "Услуги школьных столовых", 
        "id": "2dc54675d6364e2baffbc0f8e74432ac", 
        "unit": {
          "code": "MON", 
          "name": "month", 
          "value": {
            "currency": "UAH", 
            "amount": 12.0, 
            "valueAddedTaxIncluded": true
          }
        }, 
        "quantity": 9
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "period": {
      "startDate": "2018-08-15T10:28:21.528967+03:00", 
      "endDate": "2019-08-15T10:28:21.528967+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2018-08-15T10:28:21.528967+03:00", 
    "date": "2018-08-15T10:28:26.370964+03:00", 
    "awardID": "b3c41ca2aaf34fa8948dd9d6fe672465", 
    "id": "dfd7c78f071c46e9a2383d2b27b3e052", 
    "contractID": "UA-2018-08-15-000001-1"
  }
}

