PATCH /api/2.4/tenders/b59fb0e6e51c4c7ca951d5278b3cb548/awards/3c8fbaae6c5145b5a9654154dbfe4d45?acc_token=d3ef8c8186ea45a78696a65a2e98c3f2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 49
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active", 
    "qualified": true
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2019-02-06T06:11:20.613944+02:00", 
      "endDate": "2019-02-12T00:00:00+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "date": "2019-02-06T06:11:20.642795+02:00", 
    "id": "3c8fbaae6c5145b5a9654154dbfe4d45"
  }
}

