GET /api/2.5/tenders/411eba73a7e241eab1e17cf80cbe33c6/contracts/a1b42145e86d4eb7b71ebd7570c708cc/documents?acc_token=aa8f9663e1ac4382ac0d69917f93e5f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_first_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a379c3c5dfbd4e59844f1a8a615a4770?KeyID=a8968c46&Signature=Uj3j1qkt%252BLAL%252BqIuxWqaWcrfDuLQ%2FA0CPnPGhBdHsoxjmlVxlknpaBUtOGT3ciuUcfdk17XkvRHKhaUB46%252BVBQ%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2019-01-01T00:00:00+02:00", 
      "id": "49976b27a5364eedb70dd1c6678fbf11", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }
  ]
}

