POST /api/2.5/tenders/411eba73a7e241eab1e17cf80cbe33c6/awards/efe76415cff24b1b97ccf889eecbe556/documents?acc_token=aa8f9663e1ac4382ac0d69917f93e5f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 153
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="award_first_document.doc"
Content-Type: application/msword

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/411eba73a7e241eab1e17cf80cbe33c6/awards/efe76415cff24b1b97ccf889eecbe556/documents/622caec07fe746f19e95d014292d62e9
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "award_first_document.doc", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/847949f43730426e98f3de98647e94d0?KeyID=a8968c46&Signature=AEGbF10y%252BxiT8fyrnHBcIf35OKCe8wUNHpwOkSHWDeUSNXiXf76Z9KPAwomwxmQErsyb1pbqwbLazTRHa8VsBQ%253D%253D", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "622caec07fe746f19e95d014292d62e9", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

