POST /api/2.5/tenders/411eba73a7e241eab1e17cf80cbe33c6/contracts/a1b42145e86d4eb7b71ebd7570c708cc/documents?acc_token=aa8f9663e1ac4382ac0d69917f93e5f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 207
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy908716485509$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/411eba73a7e241eab1e17cf80cbe33c6/contracts/a1b42145e86d4eb7b71ebd7570c708cc/documents/f547698475c94163aa5b226f19cb4c4f
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "contract_second_document.doc", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/42f948d9a0e8427da6b7b586af16595b?KeyID=a8968c46&Signature=%2F0lH2H%2FR8FiECTigJBQ%252BwQ4Q6dSR%2F4UBfJ2cMAuEA0k4WG%2FC5xiSET59TLo2LkrZYuFGZJCjyEAlqmHORFtuAA%253D%253D", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "f547698475c94163aa5b226f19cb4c4f", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

