PATCH /api/2.5/tenders/ac7b87e071bf4d58afeb21bf9e0ef36b/awards/2759acede5ec4c19b486e9488c5d76b8?acc_token=4a4e0a3f19d7452faaf35859bd8574a3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 49
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active", 
    "qualified": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2019-03-18T09:27:37.953458+02:00", 
      "endDate": "2019-03-24T00:00:00+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "date": "2019-03-18T09:27:37.984723+02:00", 
    "id": "2759acede5ec4c19b486e9488c5d76b8"
  }
}

