POST /api/2.4/tenders/b59fb0e6e51c4c7ca951d5278b3cb548/awards?acc_token=d3ef8c8186ea45a78696a65a2e98c3f2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1302
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "date": "2016-01-14T18:07:00.628073+02:00", 
    "status": "pending", 
    "suppliers": [
      {
        "contactPoint": {
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк", 
          "email": "soleksuk@gmail.com"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "id": "d373338bc3324f14b8b3d4af68922773", 
    "value": {
      "currency": "UAH", 
      "amount": 475000, 
      "valueAddedTaxIncluded": "true"
    }
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/b59fb0e6e51c4c7ca951d5278b3cb548/awards/3c8fbaae6c5145b5a9654154dbfe4d45
{
  "data": {
    "status": "pending", 
    "complaintPeriod": {
      "startDate": "2019-02-06T06:11:20.613944+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-02-06T06:11:20.613244+02:00", 
    "id": "3c8fbaae6c5145b5a9654154dbfe4d45"
  }
}

