PATCH /api/2.5/tenders/411eba73a7e241eab1e17cf80cbe33c6/contracts/a1b42145e86d4eb7b71ebd7570c708cc?acc_token=aa8f9663e1ac4382ac0d69917f93e5f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_first_document.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a379c3c5dfbd4e59844f1a8a615a4770?KeyID=a8968c46&Signature=Uj3j1qkt%252BLAL%252BqIuxWqaWcrfDuLQ%2FA0CPnPGhBdHsoxjmlVxlknpaBUtOGT3ciuUcfdk17XkvRHKhaUB46%252BVBQ%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "49976b27a5364eedb70dd1c6678fbf11", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "contract_second_document.doc", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/42f948d9a0e8427da6b7b586af16595b?KeyID=a8968c46&Signature=%2F0lH2H%2FR8FiECTigJBQ%252BwQ4Q6dSR%2F4UBfJ2cMAuEA0k4WG%2FC5xiSET59TLo2LkrZYuFGZJCjyEAlqmHORFtuAA%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "f547698475c94163aa5b226f19cb4c4f", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-21T00:00:00+02:00", 
          "endDate": "2019-05-21T00:00:00+02:00"
        }, 
        "id": "6754413a93e449cd9f59855ae81932f1", 
        "unit": {
          "code": "MON", 
          "name": "month", 
          "value": {
            "currency": "UAH", 
            "amount": 12.0, 
            "valueAddedTaxIncluded": true
          }
        }, 
        "quantity": 9.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "period": {
      "startDate": "2019-04-01T01:00:00+03:00", 
      "endDate": "2020-03-31T01:00:00+03:00"
    }, 
    "dateSigned": "2019-04-01T01:00:00+03:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-04-01T01:10:00+03:00", 
    "awardID": "efe76415cff24b1b97ccf889eecbe556", 
    "id": "a1b42145e86d4eb7b71ebd7570c708cc", 
    "contractID": "UA-2019-04-01-000001-1"
  }
}

