PATCH /api/2.4/tenders/c7142ef0e3664a588fba9e0ebc1e8daf/cancellations/3e2926f2007d4ce0842092c1bbc5a2df?acc_token=c1f06501277b4865aba01383c849bfce HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-02-06T06:11:13.057704+02:00", 
    "cancellationOf": "tender", 
    "id": "3e2926f2007d4ce0842092c1bbc5a2df"
  }
}

