PUT /api/2.5/tenders/eb89d2d7a14d43098ec93f05eac5797e/cancellations/a06c2ff1b6ff4a3982835159a73b7012/documents/e784be5161ee488ca0abfc66f68065d9?acc_token=4e92561f0bb9471f8046010d32b72973 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 139
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Notice-2.pdf"
Content-Type: application/pdf

content2
--BOUNDARY--


Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice-2.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/028955e3e93c4d0b828271ec49584669?KeyID=a8968c46&Signature=2saFPeZG3aI0wLNnBlde6TecK%252BGTHGX%252BjNtFKfpJKliHE1230yJNMY4qrkwQ0TZQWuSYmArpk5EdZVfpwBImAA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:10:00+03:00", 
    "id": "e784be5161ee488ca0abfc66f68065d9", 
    "dateModified": "2019-04-01T01:10:00+03:00"
  }
}

