PATCH /api/2.5/tenders/3616b4f5d1d048c2a2aedec30d80fb17/cancellations/903024a4a3cd421c983b84f8ac051dc0?acc_token=47eab536748b4d269f93b452eba848bd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-03-18T09:27:29.890685+02:00", 
    "cancellationOf": "tender", 
    "id": "903024a4a3cd421c983b84f8ac051dc0"
  }
}

