POST /api/2.5/tenders/6418a8ebfc3b47cb95b0ec6de0c3bdb1/lots?acc_token=1aed17756aad4f0aaacdff130f87dc0a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 199
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Опис Лот №1", 
    "value": {
      "currency": "UAH", 
      "amount": 500000, 
      "valueAddedTaxIncluded": false
    }, 
    "title": "Лот №1"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/6418a8ebfc3b47cb95b0ec6de0c3bdb1/lots/1db1d75a56454f7ea600991417121e9f
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №1", 
    "title": "Лот №1", 
    "value": {
      "currency": "UAH", 
      "amount": 500000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "1db1d75a56454f7ea600991417121e9f"
  }
}

