PATCH /api/2.5/tenders/d6f650be0d1542c6a20a479caf62a273/contracts/853611334deb438292929d5bcf7de0c4?acc_token=880c3dfdeea7465b80e627e76953516a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 54
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "value": {
      "amount": 238, 
      "amountNet": 230
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "relatedLot": "1b4b112ff70544b68f89cac8499ae6e2", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-20T09:26:16.307641+02:00", 
          "endDate": "2019-03-23T09:26:16.307641+02:00"
        }, 
        "description_ru": "Услуги школьных столовых", 
        "id": "2dc54675d6364e2baffbc0f8e74432ac"
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-18T09:27:39.035249+02:00", 
    "awardID": "243356b305274a3c853f1c78ec3d43fb", 
    "id": "853611334deb438292929d5bcf7de0c4", 
    "contractID": "UA-2019-03-18-000001-1"
  }
}

