PATCH /api/2.4/tenders/3bbba56136a34a209049e5d0f966bd9e?acc_token=68be8616f9b641a8a6e60a9ceaf5cd88 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 73
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "items": [
      {
        "relatedLot": "e1c72b9d0e314e5187a06a75265eac9c"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "procurementMethod": "limited", 
    "status": "active", 
    "causeDescription": "оригінальний тендер не вдався двічі", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "value": {
          "currency": "UAH", 
          "amount": 500000.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2018-09-21T05:26:40.079005+03:00", 
        "id": "e1c72b9d0e314e5187a06a75265eac9c"
      }
    ], 
    "items": [
      {
        "relatedLot": "e1c72b9d0e314e5187a06a75265eac9c", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-23T05:26:01.267704+03:00", 
          "endDate": "2018-09-26T05:26:01.267704+03:00"
        }, 
        "description_ru": "Услуги школьных столовых", 
        "id": "2dc54675d6364e2baffbc0f8e74432ac"
      }
    ], 
    "procurementMethodType": "negotiation.quick", 
    "value": {
      "currency": "UAH", 
      "amount": 500000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateModified": "2018-09-21T05:26:40.238420+03:00", 
    "causeDescription_ru": "оригинальный тендер не получился дважды", 
    "date": "2018-09-21T05:26:39.943578+03:00", 
    "causeDescription_en": "original tender has failed twice", 
    "description_ru": "Услуги школьных столовых", 
    "description_en": "Services in school canteens", 
    "title_ru": "Услуги школьных столовых", 
    "owner": "broker", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "kind": "general", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title_en": "Services in school canteens", 
    "id": "3bbba56136a34a209049e5d0f966bd9e", 
    "tenderID": "UA-2018-09-21-000001"
  }
}

