POST /api/2.4/tenders/5a482ae17b1143eb83ee16b1408cae11/lots?acc_token=6fbdde1d2c5444099e28affff42de1fc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 198
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "Опис Лот №1", 
    "value": {
      "currency": "UAH", 
      "amount": 500000, 
      "valueAddedTaxIncluded": true
    }, 
    "title": "Лот №1"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/5a482ae17b1143eb83ee16b1408cae11/lots/cdf774908e454840a206c6956b5b920f
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №1", 
    "title": "Лот №1", 
    "value": {
      "currency": "UAH", 
      "amount": 500000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-15T10:28:45.441175+03:00", 
    "id": "cdf774908e454840a206c6956b5b920f"
  }
}

