PATCH /api/2.5/tenders/f930e795d51e4d0897efd6abd044cab3/contracts/7904238244a145d29c9af569c2cca0aa?acc_token=de5684b7316349acb1774b8332e102ab HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 54
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "value": {
      "amount": 238, 
      "amountNet": 230
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "relatedLot": "d24866d6eade408d988ac6dc679460fe", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-30T06:47:08.632098+02:00", 
          "endDate": "2019-04-02T06:47:08.632098+03:00"
        }, 
        "description_ru": "Услуги школьных столовых", 
        "id": "2dc54675d6364e2baffbc0f8e74432ac"
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-28T06:49:42.774090+02:00", 
    "awardID": "75c5007d80ee4a4796999af3719ae58b", 
    "id": "7904238244a145d29c9af569c2cca0aa", 
    "contractID": "UA-2019-03-28-000001-1"
  }
}

