POST /api/2.5/tenders?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 3480
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "procurementMethod": "limited", 
    "status": "active", 
    "causeDescription": "оригінальний тендер не вдався двічі", 
    "title": "Послуги шкільних їдалень", 
    "procurementMethodType": "negotiation.quick", 
    "title_en": "Services in school canteens", 
    "description_en": "Services in school canteens", 
    "causeDescription_ru": "оригинальный тендер не получился дважды", 
    "causeDescription_en": "original tender has failed twice", 
    "procuringEntity": {
      "kind": "special", 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21027", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Стахурського. 22", 
        "locality": "м. Вінниця"
      }, 
      "name": "ЗОСШ #10 м.Вінниці"
    }, 
    "title_ru": "Услуги школьных столовых", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-21T00:00:00+02:00", 
          "endDate": "2019-05-21T00:00:00+02:00"
        }, 
        "quantity": 1
      }
    ], 
    "owner": "broker", 
    "value": {
      "currency": "UAH", 
      "amount": 500000, 
      "valueAddedTaxIncluded": true
    }, 
    "description_ru": "Услуги школьных столовых"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/4c2fb227599241228a172c3850ebdb4a
{
  "access": {
    "token": "3f25dc8beb7f4dc691a7f23bfdc0c758"
  }, 
  "data": {
    "procurementMethod": "limited", 
    "status": "active", 
    "causeDescription": "оригінальний тендер не вдався двічі", 
    "title": "Послуги шкільних їдалень", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-21T00:00:00+02:00", 
          "endDate": "2019-05-21T00:00:00+02:00"
        }, 
        "id": "0db0fd6bd26441e9a7f089695ac4da60", 
        "quantity": 1.0
      }
    ], 
    "procurementMethodType": "negotiation.quick", 
    "value": {
      "currency": "UAH", 
      "amount": 500000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateModified": "2019-04-01T01:00:00+03:00", 
    "causeDescription_ru": "оригинальный тендер не получился дважды", 
    "date": "2019-04-01T01:00:00+03:00", 
    "causeDescription_en": "original tender has failed twice", 
    "description_ru": "Услуги школьных столовых", 
    "description_en": "Services in school canteens", 
    "title_ru": "Услуги школьных столовых", 
    "owner": "broker", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "kind": "special", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title_en": "Services in school canteens", 
    "id": "4c2fb227599241228a172c3850ebdb4a", 
    "tenderID": "UA-2019-04-01-000001"
  }
}

