PATCH /api/2.4/tenders/5a482ae17b1143eb83ee16b1408cae11/awards/ed9d5b8f22b64e658d417088aa02246f?acc_token=6fbdde1d2c5444099e28affff42de1fc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 49
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active", 
    "qualified": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "lotID": "cdf774908e454840a206c6956b5b920f", 
    "complaintPeriod": {
      "startDate": "2018-08-15T10:28:46.220046+03:00", 
      "endDate": "2018-08-21T00:00:00+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "date": "2018-08-15T10:28:46.338509+03:00", 
    "id": "ed9d5b8f22b64e658d417088aa02246f"
  }
}

