PATCH /api/2.4/tenders/af43359e2d0242ac8e43ab58cbff5749/awards/2dc7c54df2d0440cb7594567e7c46556?acc_token=436e7c43f6b841a4b51fe3259caed5f5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 49
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active", 
    "qualified": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "lotID": "f138ebe69c144b6bbf06b7c014a0e812", 
    "complaintPeriod": {
      "startDate": "2018-08-15T10:29:24.675202+03:00", 
      "endDate": "2018-08-21T00:00:00+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "date": "2018-08-15T10:29:24.794776+03:00", 
    "id": "2dc7c54df2d0440cb7594567e7c46556"
  }
}

