POST /api/2.5/tenders/f930e795d51e4d0897efd6abd044cab3/lots?acc_token=de5684b7316349acb1774b8332e102ab HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 199
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "description": "Опис Лот №1", 
    "value": {
      "currency": "UAH", 
      "amount": 500000, 
      "valueAddedTaxIncluded": false
    }, 
    "title": "Лот №1"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/f930e795d51e4d0897efd6abd044cab3/lots/d24866d6eade408d988ac6dc679460fe
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №1", 
    "title": "Лот №1", 
    "value": {
      "currency": "UAH", 
      "amount": 500000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-28T06:49:42.552349+02:00", 
    "id": "d24866d6eade408d988ac6dc679460fe"
  }
}

