PATCH /api/2.4/tenders/1c3503bb54724a1da48c0212e68dfc8c/awards/f77d4802601e4d3486973338d563e10a?acc_token=b7d1633a38824873bc5c63f43462e1ef HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 49
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active", 
    "qualified": true
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "lotID": "6ade06998f2a42f999943af5c6a16883", 
    "complaintPeriod": {
      "startDate": "2019-02-06T06:11:21.512643+02:00", 
      "endDate": "2019-02-12T00:00:00+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "date": "2019-02-06T06:11:21.544422+02:00", 
    "id": "f77d4802601e4d3486973338d563e10a"
  }
}

