PATCH /api/2.5/tenders/4ad1cf0c6e304022a48bd15e68797ee2/cancellations/7a29f0f12fa7437ab40e2756bfcef894?acc_token=aa42dc7013d84acd84c46a580e4ef534 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/df128074845548c9890740f1a7b80acc?KeyID=a8968c46&Signature=SXaHOS90FdVKaUGAPuAWbuoPj1C1OqgmGlbkl0bng8ejDkFu1tOvf82RnvMX%2FyyofwS9zLiIY%2FH0sbn%252Bfh0nDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:10:00+03:00", 
        "id": "5c5208b485cb4b24b9598d134d69def7", 
        "dateModified": "2019-04-01T01:10:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "language": "uk", 
        "title": "Notice-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/91a10d4215de426082eb52ac5acb37b7?KeyID=a8968c46&Signature=ozAM3w3GWpRqWHyElxMa4wUBiFFQCG9ixRzThT86k8kXIdPNbFxbTd5e7p4x1Y4LpAJBGPY7YrznkwFXoE8HBQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:10:00+03:00", 
        "id": "5c5208b485cb4b24b9598d134d69def7", 
        "dateModified": "2019-04-01T01:10:00+03:00"
      }
    ], 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-04-01T01:10:00+03:00", 
    "cancellationOf": "tender", 
    "id": "7a29f0f12fa7437ab40e2756bfcef894"
  }
}

