PATCH /api/2.5/tenders/d305cbefe8194d4f87288d7da8bc9cc6/questions/2de2bc6f812943f2b5ba4699c964522a?acc_token=23f3d8cdadaa4dd9a937b97ece3143f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2019-03-18T09:27:47.895355+02:00", 
    "title": "Калорійність", 
    "date": "2019-03-18T09:27:47.852962+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "2de2bc6f812943f2b5ba4699c964522a", 
    "questionOf": "tender"
  }
}

