PATCH /api/2.5/tenders/d305cbefe8194d4f87288d7da8bc9cc6/qualifications/65f1d5b1d32945e8b6754c985db05ee1?acc_token=23f3d8cdadaa4dd9a937b97ece3143f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "3b6533a0886043a2a23608b94a5cb267", 
    "date": "2019-03-18T09:27:49.396480+02:00", 
    "id": "65f1d5b1d32945e8b6754c985db05ee1"
  }
}

