PATCH /api/2.4/tenders/d93f62e755b94ccbaaf86790df865507/qualifications/e5da03c0a04648969bea03e6a3733724?acc_token=6a891e76951f47fe929173f74e9e4168 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "0f32dd73b1894cb49fa0ab68c1cc03a9", 
    "date": "2019-02-06T06:11:33.256905+02:00", 
    "id": "e5da03c0a04648969bea03e6a3733724"
  }
}

