PATCH /api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/qualifications/397b910332e64ae69d9a8ca3e732a457?acc_token=3cd12c0429cf4dd3b49122aacd01f40a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "7d22de3d543c4d26bb6b7da036b0e177", 
    "date": "2018-08-15T10:41:12.710108+03:00", 
    "id": "397b910332e64ae69d9a8ca3e732a457"
  }
}

