POST /api/2.5/tenders/4734fdc349674070a77a0f59d097d45d/awards/ca1663f6e324456c9c65c54ca71588ca/complaints?acc_token=6d601aa3e5b64b67ae5a3bf3de8bccb8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1088
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "author": {
      "contactPoint": {
        "email": "aagt@gmail.com", 
        "telephone": "+380 (322) 91-69-30", 
        "name": "Андрій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137226", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Книга»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "79013", 
        "region": "м. Львів", 
        "streetAddress": "вул. Островського, 34", 
        "locality": "м. Львів"
      }
    }, 
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/4734fdc349674070a77a0f59d097d45d/awards/ca1663f6e324456c9c65c54ca71588ca/complaints/1a0d16a4082543fe9bf46d0bf9b0906c
{
  "access": {
    "token": "2a4ec80277964bf2ab8035ef472af027"
  }, 
  "data": {
    "status": "draft", 
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "author": {
      "contactPoint": {
        "email": "aagt@gmail.com", 
        "telephone": "+380 (322) 91-69-30", 
        "name": "Андрій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137226", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Книга»", 
      "address": {
        "postalCode": "79013", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 34", 
        "region": "м. Львів", 
        "locality": "м. Львів"
      }
    }, 
    "title": "Калорійність", 
    "complaintID": "UA-2019-04-01-000001.9", 
    "date": "2019-04-01T01:10:00+03:00", 
    "type": "claim", 
    "id": "1a0d16a4082543fe9bf46d0bf9b0906c"
  }
}

