PATCH /api/2.5/tenders/06a1c6e903ef4917a09ab91e44fcd422/awards/bbaef77b751146c090c7e9e75313f478?acc_token=6148c875394244b0b43456ae1c5ff971 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/06a1c6e903ef4917a09ab91e44fcd422/awards/c3c5126e738d406c8694fd15ede92c2d
{
  "data": {
    "status": "cancelled", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-04-01T01:00:00+03:00", 
      "endDate": "2019-04-01T01:10:00+03:00"
    }, 
    "bid_id": "fb78cb473abc4b698ca86dfb368cc826", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-04-01T01:10:00+03:00", 
    "qualified": true, 
    "complaints": [
      {
        "status": "resolved", 
        "dateDecision": "2019-04-01T01:10:00+03:00", 
        "tendererActionDate": "2019-04-01T01:10:00+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Недостатньо інформації", 
        "id": "2d3ce8413b0b4d6393fd42734ca7b77d", 
        "tendererAction": "Умови виправлено, вибір переможня буде розгянуто повторно", 
        "dateSubmitted": "2019-04-01T01:10:00+03:00", 
        "complaintID": "UA-2019-04-01-000001.1", 
        "date": "2019-04-01T01:10:00+03:00", 
        "acceptance": true, 
        "type": "complaint", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "complaint_owner", 
            "language": "uk", 
            "title": "Complaint_Attachement.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/50c36d10cb304ce68dd90e6c4d9034b3?KeyID=a8968c46&Signature=dYSu%252BCnixAB3adnOZrTWd2j2OWkyOjmGwOirD7yRduQ6klo9RgHvWVY5g%2Fi0qYRdgyISPC8%252Bn6K3OrX4AyHlCQ%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:10:00+03:00", 
            "id": "b6006875c4c14dff974d26293cd7d80f", 
            "dateModified": "2019-04-01T01:10:00+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "aboveThresholdReviewers", 
            "language": "uk", 
            "title": "ComplaintResolution.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e1370f979e27401798b86d94e73a89aa?KeyID=a8968c46&Signature=t9nNvQgR2aAkwzltYRlOScd8ylL4AQE1eE1i1MaFKGqKdTOkXnMhNC7AwVHzKv3Pec7yBV5zQ852364BJPAQDg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:10:00+03:00", 
            "id": "58d457f0fc4642ebacf78b482a64cca5", 
            "dateModified": "2019-04-01T01:10:00+03:00"
          }
        ], 
        "dateAccepted": "2019-04-01T01:10:00+03:00"
      }, 
      {
        "status": "invalid", 
        "dateDecision": "2019-04-01T01:10:00+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": false, 
        "dateSubmitted": "2019-04-01T01:10:00+03:00", 
        "complaintID": "UA-2019-04-01-000001.2", 
        "date": "2019-04-01T01:10:00+03:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "15155aaa9c6648a19036858af292f228"
      }, 
      {
        "status": "declined", 
        "dateDecision": "2019-04-01T01:10:00+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": true, 
        "dateAccepted": "2019-04-01T01:10:00+03:00", 
        "dateSubmitted": "2019-04-01T01:10:00+03:00", 
        "complaintID": "UA-2019-04-01-000001.3", 
        "date": "2019-04-01T01:10:00+03:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "2530fb17a19f4b91823d8cb5a572237c"
      }, 
      {
        "status": "stopped", 
        "dateDecision": "2019-04-01T01:10:00+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "decision": "Тендер скасовується замовником", 
        "acceptance": true, 
        "cancellationReason": "Тендер скасовується замовником", 
        "dateCanceled": "2019-04-01T01:10:00+03:00", 
        "dateAccepted": "2019-04-01T01:10:00+03:00", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateSubmitted": "2019-04-01T01:10:00+03:00", 
        "complaintID": "UA-2019-04-01-000001.4", 
        "date": "2019-04-01T01:10:00+03:00", 
        "type": "complaint", 
        "id": "35036c7817b34461a6ad3df642fb3066"
      }, 
      {
        "status": "stopped", 
        "dateDecision": "2019-04-01T01:10:00+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "decision": "Тендер скасовується замовником", 
        "acceptance": true, 
        "dateCanceled": "2019-04-01T01:10:00+03:00", 
        "dateAccepted": "2019-04-01T01:10:00+03:00", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateSubmitted": "2019-04-01T01:10:00+03:00", 
        "complaintID": "UA-2019-04-01-000001.5", 
        "date": "2019-04-01T01:10:00+03:00", 
        "type": "complaint", 
        "id": "b4ae5b7ee5544c249603ff25fbf9dcfc"
      }, 
      {
        "status": "answered", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "Недостатньо інформації", 
        "satisfied": true, 
        "dateAnswered": "2019-04-01T01:10:00+03:00", 
        "dateSubmitted": "2019-04-01T01:10:00+03:00", 
        "complaintID": "UA-2019-04-01-000001.6", 
        "date": "2019-04-01T01:10:00+03:00", 
        "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
        "id": "06fcbc1b218b423296f4d189fe41caf2"
      }, 
      {
        "status": "answered", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "invalid", 
        "type": "claim", 
        "title": "Недостатньо інформації", 
        "satisfied": false, 
        "dateAnswered": "2019-04-01T01:10:00+03:00", 
        "dateSubmitted": "2019-04-01T01:10:00+03:00", 
        "complaintID": "UA-2019-04-01-000001.7", 
        "date": "2019-04-01T01:10:00+03:00", 
        "resolution": "Вимога не відповідає предмету закупівлі", 
        "id": "9d8de22480d644c58cb7d3fa94e35140"
      }, 
      {
        "status": "claim", 
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "author": {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }, 
        "title": "Калорійність", 
        "dateSubmitted": "2019-04-01T01:10:00+03:00", 
        "complaintID": "UA-2019-04-01-000001.8", 
        "date": "2019-04-01T01:10:00+03:00", 
        "type": "claim", 
        "id": "ca0eb40fae3b44f588568a30d75fc1ab"
      }
    ], 
    "id": "bbaef77b751146c090c7e9e75313f478"
  }
}

