PATCH /api/2.4/tenders/b1d6d328d9bb4ec2b8e3848d15a515ae/awards/4c0c122e194c4882b9ca6dcf85c0a687?acc_token=b838bb0726144c9cb585eec4fa84b7dc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/b1d6d328d9bb4ec2b8e3848d15a515ae/awards/179ec205c83a4c94872d89b2beb07d9d
{
  "data": {
    "status": "cancelled", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-08-15T10:41:51.404727+03:00", 
      "endDate": "2018-08-15T10:41:56.774221+03:00"
    }, 
    "bid_id": "1c08242f42834d8abbaafeba165887b5", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-15T10:41:56.783203+03:00", 
    "qualified": true, 
    "complaints": [
      {
        "status": "resolved", 
        "dateDecision": "2018-08-15T10:41:55.284122+03:00", 
        "tendererActionDate": "2018-08-15T10:41:56.115370+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Недостатньо інформації", 
        "id": "d814783bd817410dab22954dea5e8a05", 
        "tendererAction": "Умови виправлено, вибір переможня буде розгянуто повторно", 
        "dateSubmitted": "2018-08-15T10:41:52.133977+03:00", 
        "complaintID": "UA-2018-08-15-000001.1", 
        "date": "2018-08-15T10:41:56.123950+03:00", 
        "acceptance": true, 
        "type": "complaint", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "complaint_owner", 
            "language": "uk", 
            "title": "Complaint_Attachement.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/1ca60363991242cda13add77145493f0?KeyID=fb33ef3e&Signature=5AB6yTqIaJLec3jkmVvDil7%2F9MQVey%252B%252Bge0Sa%252BfQF8bYLWZo1tWYQW6ytSQYtMubt0LxE3IN0sfqjMiwVF3TCA%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2018-08-15T10:41:51.961031+03:00", 
            "id": "44cf85bdbf9f4370891797bed948b7fd", 
            "dateModified": "2018-08-15T10:41:51.961056+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "aboveThresholdReviewers", 
            "language": "uk", 
            "title": "ComplaintResolution.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/b7e35a0bbe7b46988b78db83f42783b9?KeyID=fb33ef3e&Signature=dUEFJeq7UDgpHToUi4AGmubAAw%2Fi0L16iwLxD4gB%252Bkz5NoQtzl51dStl1c%2FseKc5XCdyXnQmzHuMukQSZDBQDw%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2018-08-15T10:41:55.083638+03:00", 
            "id": "fe8c5fa33ecb488892c04db2bbc0befa", 
            "dateModified": "2018-08-15T10:41:55.083665+03:00"
          }
        ], 
        "dateAccepted": "2018-08-15T10:41:54.372650+03:00"
      }, 
      {
        "status": "invalid", 
        "dateDecision": "2018-08-15T10:41:54.194421+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": false, 
        "dateSubmitted": "2018-08-15T10:41:52.261753+03:00", 
        "complaintID": "UA-2018-08-15-000001.2", 
        "date": "2018-08-15T10:41:54.201721+03:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "096144c2713842a99e9df60e285a641b"
      }, 
      {
        "status": "declined", 
        "dateDecision": "2018-08-15T10:41:55.472945+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": true, 
        "dateAccepted": "2018-08-15T10:41:54.540394+03:00", 
        "dateSubmitted": "2018-08-15T10:41:52.394268+03:00", 
        "complaintID": "UA-2018-08-15-000001.3", 
        "date": "2018-08-15T10:41:55.480931+03:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "d98e2b2fa96c4de2adc03e82f9f3b0c0"
      }, 
      {
        "status": "stopped", 
        "dateDecision": "2018-08-15T10:41:56.505182+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "decision": "Тендер скасовується замовником", 
        "acceptance": true, 
        "cancellationReason": "Тендер скасовується замовником", 
        "dateCanceled": "2018-08-15T10:41:56.309425+03:00", 
        "dateAccepted": "2018-08-15T10:41:54.715165+03:00", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateSubmitted": "2018-08-15T10:41:52.540083+03:00", 
        "complaintID": "UA-2018-08-15-000001.4", 
        "date": "2018-08-15T10:41:56.512876+03:00", 
        "type": "complaint", 
        "id": "f773ec186c3f4bb7bf61af397193ab30"
      }, 
      {
        "status": "stopped", 
        "dateDecision": "2018-08-15T10:41:55.771906+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "decision": "Тендер скасовується замовником", 
        "acceptance": true, 
        "dateCanceled": "2018-08-15T10:41:55.771931+03:00", 
        "dateAccepted": "2018-08-15T10:41:54.897101+03:00", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateSubmitted": "2018-08-15T10:41:52.686912+03:00", 
        "complaintID": "UA-2018-08-15-000001.5", 
        "date": "2018-08-15T10:41:55.779769+03:00", 
        "type": "complaint", 
        "id": "1949e4ba51404eca8d866e49369b0165"
      }, 
      {
        "status": "answered", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "Недостатньо інформації", 
        "satisfied": true, 
        "dateAnswered": "2018-08-15T10:41:53.004858+03:00", 
        "dateSubmitted": "2018-08-15T10:41:52.843301+03:00", 
        "complaintID": "UA-2018-08-15-000001.6", 
        "date": "2018-08-15T10:41:53.011499+03:00", 
        "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
        "id": "057f4349963548d59865d321a5e9a7ec"
      }, 
      {
        "status": "answered", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "invalid", 
        "type": "claim", 
        "title": "Недостатньо інформації", 
        "satisfied": false, 
        "dateAnswered": "2018-08-15T10:41:53.495080+03:00", 
        "dateSubmitted": "2018-08-15T10:41:53.324232+03:00", 
        "complaintID": "UA-2018-08-15-000001.7", 
        "date": "2018-08-15T10:41:53.502489+03:00", 
        "resolution": "Вимога не відповідає предмету закупівлі", 
        "id": "88877b8929c94a6b873dbd4bd696ecc0"
      }, 
      {
        "status": "claim", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Недостатньо інформації", 
        "dateSubmitted": "2018-08-15T10:41:54.016033+03:00", 
        "complaintID": "UA-2018-08-15-000001.8", 
        "date": "2018-08-15T10:41:54.023257+03:00", 
        "type": "claim", 
        "id": "fc657fc48de64216bb835a35ef592646"
      }
    ], 
    "id": "4c0c122e194c4882b9ca6dcf85c0a687"
  }
}

