PATCH /api/2.4/tenders/a52ed53136934caebd88ebc337e40057/awards/47b693f99f9e4ccbbe4850f26c67e3a4/complaints/7a10b978248147a99027dd240928b83e?acc_token=4db1d704a17c4f739193156f8dd5ed40 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "satisfied": false
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "invalid", 
    "type": "claim", 
    "title": "Недостатньо інформації", 
    "satisfied": false, 
    "dateAnswered": "2018-08-15T10:40:58.526906+03:00", 
    "dateSubmitted": "2018-08-15T10:40:58.362605+03:00", 
    "complaintID": "UA-2018-08-15-000001.7", 
    "date": "2018-08-15T10:40:58.533755+03:00", 
    "resolution": "Вимога не відповідає предмету закупівлі", 
    "id": "7a10b978248147a99027dd240928b83e"
  }
}

