POST /api/2.5/tenders/06a1c6e903ef4917a09ab91e44fcd422/awards/bbaef77b751146c090c7e9e75313f478/complaints/2d3ce8413b0b4d6393fd42734ca7b77d/documents?acc_token=a991598cad4847bbab8d4729c8356d69 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 151
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/06a1c6e903ef4917a09ab91e44fcd422/awards/bbaef77b751146c090c7e9e75313f478/complaints/2d3ce8413b0b4d6393fd42734ca7b77d/documents/b6006875c4c14dff974d26293cd7d80f
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/50c36d10cb304ce68dd90e6c4d9034b3?KeyID=a8968c46&Signature=dYSu%252BCnixAB3adnOZrTWd2j2OWkyOjmGwOirD7yRduQ6klo9RgHvWVY5g%2Fi0qYRdgyISPC8%252Bn6K3OrX4AyHlCQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:10:00+03:00", 
    "id": "b6006875c4c14dff974d26293cd7d80f", 
    "dateModified": "2019-04-01T01:10:00+03:00"
  }
}

