PATCH /api/2.5/tenders/b476898ca0d34edf83b57406f5b6ce8a/awards/a308cc32716547708e74e42b62e4275d?acc_token=b848e108ba964bfbbf92f02fcc3b0b78 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/b476898ca0d34edf83b57406f5b6ce8a/awards/76eb8e030b4a49d19fbccbf5596e589e
{
  "data": {
    "status": "cancelled", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-03-28T06:49:44.558856+02:00", 
      "endDate": "2019-03-28T06:49:48.694954+02:00"
    }, 
    "bid_id": "8d59369daaca45d795f7a92486d14c27", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-28T06:49:48.703892+02:00", 
    "qualified": true, 
    "complaints": [
      {
        "status": "resolved", 
        "dateDecision": "2019-03-28T06:49:47.541728+02:00", 
        "tendererActionDate": "2019-03-28T06:49:48.167099+02:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Недостатньо інформації", 
        "id": "57ecd36e6aca4ce4af5dc663392e3fc6", 
        "tendererAction": "Умови виправлено, вибір переможня буде розгянуто повторно", 
        "dateSubmitted": "2019-03-28T06:49:44.894429+02:00", 
        "complaintID": "UA-2019-03-28-000001.1", 
        "date": "2019-03-28T06:49:48.177647+02:00", 
        "acceptance": true, 
        "type": "complaint", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "complaint_owner", 
            "language": "uk", 
            "title": "Complaint_Attachement.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/2a3ef840d4264b59b789f3fecef2c119?KeyID=387cfce5&Signature=flmvxX3meETEoGLEG2yGCGjdzpe0PQEUAsfyQ%252BF9xSoWElddsx4ReANzr6gdgfKkstV8G0QqBZkKYROc2tEZBA%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-28T06:49:44.808065+02:00", 
            "id": "0fd92ee99d97469f8d9cf253a4205a64", 
            "dateModified": "2019-03-28T06:49:44.808081+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "aboveThresholdReviewers", 
            "language": "uk", 
            "title": "ComplaintResolution.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/594f285efe9b41a8ba1459ac499ffe23?KeyID=387cfce5&Signature=05z1IwHY9nZ9tI18dz5%2FdDFiuWDcAtMb0oTbg%2FRGU0T%2FOu8g%252B%252BAWFqLJnDfJCXIftZlzUCnx1slFSwGt8OQOBg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-28T06:49:47.349981+02:00", 
            "id": "f24ff7354d3c4c12aeaa91bd772b25a7", 
            "dateModified": "2019-03-28T06:49:47.350001+02:00"
          }
        ], 
        "dateAccepted": "2019-03-28T06:49:46.772465+02:00"
      }, 
      {
        "status": "invalid", 
        "dateDecision": "2019-03-28T06:49:46.622918+02:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": false, 
        "dateSubmitted": "2019-03-28T06:49:44.994935+02:00", 
        "complaintID": "UA-2019-03-28-000001.2", 
        "date": "2019-03-28T06:49:46.631947+02:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "f997b712b3874e439fee235def980fdc"
      }, 
      {
        "status": "declined", 
        "dateDecision": "2019-03-28T06:49:47.713207+02:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": true, 
        "dateAccepted": "2019-03-28T06:49:46.955308+02:00", 
        "dateSubmitted": "2019-03-28T06:49:45.116284+02:00", 
        "complaintID": "UA-2019-03-28-000001.3", 
        "date": "2019-03-28T06:49:47.722426+02:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "a6df34435f2e456c8790d7e53f3e6ffe"
      }, 
      {
        "status": "stopped", 
        "dateDecision": "2019-03-28T06:49:48.453214+02:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "decision": "Тендер скасовується замовником", 
        "acceptance": true, 
        "cancellationReason": "Тендер скасовується замовником", 
        "dateCanceled": "2019-03-28T06:49:48.310597+02:00", 
        "dateAccepted": "2019-03-28T06:49:47.081612+02:00", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateSubmitted": "2019-03-28T06:49:45.239845+02:00", 
        "complaintID": "UA-2019-03-28-000001.4", 
        "date": "2019-03-28T06:49:48.462701+02:00", 
        "type": "complaint", 
        "id": "d6bcd7a55c8b48d48c64c22385886037"
      }, 
      {
        "status": "stopped", 
        "dateDecision": "2019-03-28T06:49:47.883989+02:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "decision": "Тендер скасовується замовником", 
        "acceptance": true, 
        "dateCanceled": "2019-03-28T06:49:47.884017+02:00", 
        "dateAccepted": "2019-03-28T06:49:47.205937+02:00", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateSubmitted": "2019-03-28T06:49:45.365499+02:00", 
        "complaintID": "UA-2019-03-28-000001.5", 
        "date": "2019-03-28T06:49:47.895749+02:00", 
        "type": "complaint", 
        "id": "3fe69280887c4584a4672a0e6318c0a9"
      }, 
      {
        "status": "answered", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "Недостатньо інформації", 
        "satisfied": true, 
        "dateAnswered": "2019-03-28T06:49:45.644888+02:00", 
        "dateSubmitted": "2019-03-28T06:49:45.490213+02:00", 
        "complaintID": "UA-2019-03-28-000001.6", 
        "date": "2019-03-28T06:49:45.652517+02:00", 
        "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
        "id": "7e87c601f5e8481baf839fd59a0e63f0"
      }, 
      {
        "status": "answered", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "invalid", 
        "type": "claim", 
        "title": "Недостатньо інформації", 
        "satisfied": false, 
        "dateAnswered": "2019-03-28T06:49:46.014597+02:00", 
        "dateSubmitted": "2019-03-28T06:49:45.895875+02:00", 
        "complaintID": "UA-2019-03-28-000001.7", 
        "date": "2019-03-28T06:49:46.025742+02:00", 
        "resolution": "Вимога не відповідає предмету закупівлі", 
        "id": "6d7b71ba49ea472bb7e024153906c986"
      }, 
      {
        "status": "claim", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Недостатньо інформації", 
        "dateSubmitted": "2019-03-28T06:49:46.458508+02:00", 
        "complaintID": "UA-2019-03-28-000001.8", 
        "date": "2019-03-28T06:49:46.467807+02:00", 
        "type": "claim", 
        "id": "111b36fcbc7149baac574acaf7e2e57d"
      }
    ], 
    "id": "a308cc32716547708e74e42b62e4275d"
  }
}

