PATCH /api/2.5/tenders/4734fdc349674070a77a0f59d097d45d/awards/ca1663f6e324456c9c65c54ca71588ca/complaints/1a0d16a4082543fe9bf46d0bf9b0906c?acc_token=2a4ec80277964bf2ab8035ef472af027 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "author": {
      "contactPoint": {
        "email": "aagt@gmail.com", 
        "telephone": "+380 (322) 91-69-30", 
        "name": "Андрій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137226", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Книга»", 
      "address": {
        "postalCode": "79013", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 34", 
        "region": "м. Львів", 
        "locality": "м. Львів"
      }
    }, 
    "title": "Калорійність", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2019-04-01T01:00:01+03:00", 
    "complaintID": "UA-2019-04-01-000001.9", 
    "date": "2019-04-01T01:00:01+03:00", 
    "type": "claim", 
    "id": "1a0d16a4082543fe9bf46d0bf9b0906c"
  }
}

