GET /api/2.4/tenders/2cde8ec7c2104c50a25e86879ab6305c/awards/c50549b4223c480badf1e0d497dafd61/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "status": "satisfied", 
      "dateDecision": "2018-09-21T05:26:56.922336+03:00", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/ab822103f9174e48b4ff547c17045195?KeyID=9b0df68a&Signature=KNf6kIWEw4zpBdH%252BloLIg3lFaGjiDPEiQxSgrno4VBjbMAoJgq3vGzO2icNzy8fJ79nrVsSMrI0T9gyp5P0YBg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-09-21T05:26:51.247633+03:00", 
          "id": "e8338cdc572046aeab6719d2fa3250ae", 
          "dateModified": "2018-09-21T05:26:51.247717+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/550e58f871ac415f84bf6517c1cfdf97?KeyID=9b0df68a&Signature=uHvFyaAPJVRhJB8LSaXOLK2ns0CCBCazFstFHoJ7vS6I%252B9NhNfNU%252By7ssW7JggOQYxzBlbGmGvT0dGBB0rMiDQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-09-21T05:26:56.584520+03:00", 
          "id": "c7b7aa027f974c62890772a034146df9", 
          "dateModified": "2018-09-21T05:26:56.584579+03:00"
        }
      ], 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2018-09-21T05:26:55.383089+03:00", 
      "dateSubmitted": "2018-09-21T05:26:51.485822+03:00", 
      "complaintID": "UA-2018-09-21-000001.1", 
      "date": "2018-09-21T05:26:56.934820+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "65d575b29fa44aa88048d5fea13d7b7a"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2018-09-21T05:26:55.079334+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2018-09-21T05:26:51.702969+03:00", 
      "complaintID": "UA-2018-09-21-000001.2", 
      "date": "2018-09-21T05:26:55.092169+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "70f2a1d819304334a131917b9c6dbdbb"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2018-09-21T05:26:57.235937+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2018-09-21T05:26:55.681684+03:00", 
      "dateSubmitted": "2018-09-21T05:26:51.934126+03:00", 
      "complaintID": "UA-2018-09-21-000001.3", 
      "date": "2018-09-21T05:26:57.248906+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "c919042b7e7d47a6ae23c926de4a01ac"
    }, 
    {
      "status": "accepted", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2018-09-21T05:26:55.979676+03:00", 
      "dateSubmitted": "2018-09-21T05:26:52.165634+03:00", 
      "complaintID": "UA-2018-09-21-000001.4", 
      "date": "2018-09-21T05:26:55.991439+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "97b959c99ea3495f90ba3efda8cc8dcf"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-09-21T05:26:57.562038+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2018-09-21T05:26:57.562084+03:00", 
      "dateAccepted": "2018-09-21T05:26:56.281199+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-09-21T05:26:52.418945+03:00", 
      "complaintID": "UA-2018-09-21-000001.5", 
      "date": "2018-09-21T05:26:57.574678+03:00", 
      "type": "complaint", 
      "id": "03bfb2e7a52247829adc3669a0182d3f"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "resolutionType": "resolved", 
      "type": "claim", 
      "title": "Недостатньо інформації", 
      "satisfied": true, 
      "dateAnswered": "2018-09-21T05:26:52.972576+03:00", 
      "dateSubmitted": "2018-09-21T05:26:52.673995+03:00", 
      "complaintID": "UA-2018-09-21-000001.6", 
      "date": "2018-09-21T05:26:52.986067+03:00", 
      "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
      "id": "28499c656f2840829f021ab31d3cfd3e"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "resolutionType": "invalid", 
      "type": "claim", 
      "title": "Недостатньо інформації", 
      "satisfied": false, 
      "dateAnswered": "2018-09-21T05:26:53.894584+03:00", 
      "dateSubmitted": "2018-09-21T05:26:53.563500+03:00", 
      "complaintID": "UA-2018-09-21-000001.7", 
      "date": "2018-09-21T05:26:53.906268+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "f7fe6e7d24994e71b5536f1a50be6f2b"
    }, 
    {
      "status": "claim", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "dateSubmitted": "2018-09-21T05:26:54.775997+03:00", 
      "complaintID": "UA-2018-09-21-000001.8", 
      "date": "2018-09-21T05:26:54.788229+03:00", 
      "type": "claim", 
      "id": "3234034b59af49849d4d34501befae1c"
    }
  ]
}

