GET /api/2.4/tenders/e1269242824f43b1831cc5f5b4932e32/bids/f3f26ca93a344e01bf82b751fa6cdaef?acc_token=91b598f1175e4aeaa806f09c7ac39e7e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "invalid", 
    "id": "f3f26ca93a344e01bf82b751fa6cdaef"
  }
}

