PATCH /api/2.4/tenders/e1269242824f43b1831cc5f5b4932e32/bids/f3f26ca93a344e01bf82b751fa6cdaef?acc_token=91b598f1175e4aeaa806f09c7ac39e7e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/e1269242824f43b1831cc5f5b4932e32/bids/f3f26ca93a344e01bf82b751fa6cdaef/documents/22bba5fa55c74f25bf41431b4374fc5a?download=7ccf01f6a35d4262894dab412205bf3d", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:27:11.217904+03:00", 
        "id": "22bba5fa55c74f25bf41431b4374fc5a", 
        "dateModified": "2018-09-21T05:27:11.217969+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/e1269242824f43b1831cc5f5b4932e32/bids/f3f26ca93a344e01bf82b751fa6cdaef/documents/b0a84621d27747a588189ba44e0d6a69?download=4904bb41ead64948a79d7058d0aedd3d", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_top_secrets.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:27:11.386718+03:00", 
        "id": "b0a84621d27747a588189ba44e0d6a69", 
        "dateModified": "2018-09-21T05:27:11.386761+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/e1269242824f43b1831cc5f5b4932e32/bids/f3f26ca93a344e01bf82b751fa6cdaef/eligibility_documents/308fdf31e73346d5ad96f6fb58b098bc?download=6668988544c04a2bbb9621d1192211d8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:27:12.153659+03:00", 
        "id": "308fdf31e73346d5ad96f6fb58b098bc", 
        "dateModified": "2018-09-21T05:27:12.153699+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "f3f26ca93a344e01bf82b751fa6cdaef", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/e1269242824f43b1831cc5f5b4932e32/bids/f3f26ca93a344e01bf82b751fa6cdaef/financial_documents/cbf50f17bdb44241b0d1d3ee7fe6a5d5?download=dd6c991f990e4001ba679d41f860df6c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:27:11.703933+03:00", 
        "id": "cbf50f17bdb44241b0d1d3ee7fe6a5d5", 
        "dateModified": "2018-09-21T05:27:11.703972+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/e1269242824f43b1831cc5f5b4932e32/bids/f3f26ca93a344e01bf82b751fa6cdaef/financial_documents/46bb290e9f81432d959886d97dfb459a?download=0f8eb5f7177c4a1a8cc41879dcb816f7", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:27:11.874563+03:00", 
        "id": "46bb290e9f81432d959886d97dfb459a", 
        "dateModified": "2018-09-21T05:27:11.874617+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2018-09-21T05:27:10.882638+03:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/e1269242824f43b1831cc5f5b4932e32/bids/f3f26ca93a344e01bf82b751fa6cdaef/qualification_documents/f56014273dc244cf97c9112ac42d02a0?download=bcf304689e81420ba2223810460e2661", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:27:12.352740+03:00", 
        "id": "f56014273dc244cf97c9112ac42d02a0", 
        "dateModified": "2018-09-21T05:27:12.352781+03:00"
      }
    ]
  }
}

