PATCH /api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/7d22de3d543c4d26bb6b7da036b0e177?acc_token=dca8364ffd774362b159903d7e6a4a46 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/7d22de3d543c4d26bb6b7da036b0e177/documents/67a84e6ace8040c9a920789ed650f5ff?download=0910851ad89d489e800b74486bf165e8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:41:10.342926+03:00", 
        "id": "67a84e6ace8040c9a920789ed650f5ff", 
        "dateModified": "2018-08-15T10:41:10.342945+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/7d22de3d543c4d26bb6b7da036b0e177/documents/4638305018984b96aed41ad93652c51e?download=044ea81a7fa64bc28a860fbb97562b96", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_top_secrets.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:41:10.488940+03:00", 
        "id": "4638305018984b96aed41ad93652c51e", 
        "dateModified": "2018-08-15T10:41:10.488962+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/7d22de3d543c4d26bb6b7da036b0e177/eligibility_documents/f9b38e7dd4264bc69e013b5c3c74b54c?download=bfecc191ec884a618189423ffd9ffc91", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:41:11.139346+03:00", 
        "id": "f9b38e7dd4264bc69e013b5c3c74b54c", 
        "dateModified": "2018-08-15T10:41:11.139366+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "7d22de3d543c4d26bb6b7da036b0e177", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/7d22de3d543c4d26bb6b7da036b0e177/financial_documents/adacea3de7474983955c5026bd232aaf?download=a53c70bd13ba4d3781b3c7516f519d8e", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:41:10.777164+03:00", 
        "id": "adacea3de7474983955c5026bd232aaf", 
        "dateModified": "2018-08-15T10:41:10.777186+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/7d22de3d543c4d26bb6b7da036b0e177/financial_documents/f4171c5c3b774e159ea0d8edeebf4a1b?download=d12db930c3494d37b686e66a7cf5b647", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:41:10.926798+03:00", 
        "id": "f4171c5c3b774e159ea0d8edeebf4a1b", 
        "dateModified": "2018-08-15T10:41:10.926818+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2018-08-15T10:41:10.064644+03:00", 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/7d22de3d543c4d26bb6b7da036b0e177/qualification_documents/e1540951eff4448ca663dcdfe824e727?download=85d64a51b7544c468315ac59de5bf2df", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:41:11.294254+03:00", 
        "id": "e1540951eff4448ca663dcdfe824e727", 
        "dateModified": "2018-08-15T10:41:11.294275+03:00"
      }
    ]
  }
}

