GET /api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/babd3150a23e4d908abc1979cf0a3693?acc_token=f4ff2914a7f04c73ac0ecf83356c7877 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "selfEligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2018-08-15T10:41:11.903178+03:00", 
    "id": "babd3150a23e4d908abc1979cf0a3693", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/3514b9464efc494e8137301c6df9c0a7?key_for_bid=babd3150a23e4d908abc1979cf0a3693"
  }
}

