GET /api/2.5/tenders/4ad1cf0c6e304022a48bd15e68797ee2/bids/5af88e0087214e77acb434261fe9430e?acc_token=ce9f753c5b514fa5a4cedad717db2040 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "5af88e0087214e77acb434261fe9430e"
  }
}

