GET /api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "awardCriteria": "lowestCost", 
    "tenderPeriod": {
      "startDate": "2018-08-15T10:41:08.097047+03:00", 
      "endDate": "2018-09-15T10:40:52.888842+03:00"
    }, 
    "title": "Послуги шкільних їдалень", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2018-10-21T00:00:00+03:00"
    }, 
    "complaintPeriod": {
      "startDate": "2018-08-15T10:41:08.097047+03:00", 
      "endDate": "2018-09-11T00:00:00+03:00"
    }, 
    "title_en": "Services in school canteens", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2018-08-15T10:41:08.208345+03:00", 
    "dateModified": "2018-08-15T10:41:08.211598+03:00", 
    "procurementMethodType": "aboveThresholdEU", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "enquiryPeriod": {
      "startDate": "2018-08-15T10:41:08.097047+03:00", 
      "clarificationsUntil": "2018-09-10T10:40:52.888842+03:00", 
      "endDate": "2018-09-05T10:40:52.888842+03:00"
    }, 
    "owner": "broker", 
    "next_check": "2018-09-15T10:40:52.888842+03:00", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-04T10:40:52.888765+03:00", 
          "endDate": "2018-10-04T10:40:52.888805+03:00"
        }, 
        "id": "e4333e62bfb44808ae425a8b570e41bc", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-04T10:40:52.888822+03:00", 
          "endDate": "2018-10-04T10:40:52.888831+03:00"
        }, 
        "id": "e8702857ebec4cd3a797ece2bcdd01d9", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "id": "3514b9464efc494e8137301c6df9c0a7", 
    "tenderID": "UA-2018-08-15-000001"
  }
}

