GET /api/2.5/tenders/8609b26009dd4da1bda83e43dbfed3f2/complaints HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2019-04-01T01:00:00+03:00", 
      "tendererActionDate": "2019-04-01T01:00:00+03:00", 
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "author": {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }, 
      "title": "Калорійність", 
      "id": "d1f739c4e90949269b64f72d5c389980", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.1", 
      "date": "2019-04-01T01:00:00+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a27314e903d144bb953c0c3d6449c173?KeyID=a8968c46&Signature=%2FnyAk7NW83GwEyEMuOs1yWUTL3tSLx36MmPqnn2mwq4AxMQK1nX3GaynJiVWhylQ2ZVZG%252BkK1XbRfl8ZZuDeCw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:00+03:00", 
          "id": "33e95631f1194a86a997a6c6c199b6d7", 
          "dateModified": "2019-04-01T01:00:00+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/9b8a5e29ed77454a9bc5736d148df36c?KeyID=a8968c46&Signature=TgNmFN5%2F%2FUEOyTqQD5iwZqA8Ks6FPisukk5ZIBGmJGRacsHucYtiTjNc%252B2wIPuWzT0dQ1H4C7aLIYK2In6cZDA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:00+03:00", 
          "id": "e26956a0e31e435abc67c136aba9bff4", 
          "dateModified": "2019-04-01T01:00:00+03:00"
        }
      ], 
      "dateAccepted": "2019-04-01T01:00:00+03:00"
    }, 
    {
      "status": "resolved", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "dateAnswered": "2019-04-01T01:00:00+03:00", 
      "dateSubmitted": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.2", 
      "date": "2019-04-01T01:00:00+03:00", 
      "resolution": "Виправлено неконкурентні умови", 
      "id": "c4617c4c3ccb4896b6031536ec04efa3"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2019-04-01T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2019-04-01T01:00:00+03:00", 
      "dateSubmitted": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.3", 
      "date": "2019-04-01T01:00:00+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "6186a8670a5c494a8f676c7e77bf6040"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2019-04-01T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "complaint", 
      "acceptance": false, 
      "satisfied": false, 
      "dateEscalated": "2019-04-01T01:00:00+03:00", 
      "dateAnswered": "2019-04-01T01:00:00+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.4", 
      "date": "2019-04-01T01:00:00+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "97cb6f93b5814b7a94249335cf0561a5"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-04-01T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2019-04-01T01:00:00+03:00", 
      "dateAccepted": "2019-04-01T01:00:00+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.5", 
      "date": "2019-04-01T01:00:00+03:00", 
      "type": "complaint", 
      "id": "b7a6a679529a4bdda63c40bcc0b61f0a"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-04-01T01:00:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2019-04-01T01:00:00+03:00", 
      "dateAccepted": "2019-04-01T01:00:00+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.6", 
      "date": "2019-04-01T01:00:00+03:00", 
      "type": "complaint", 
      "id": "fd79d5000b974b279ff3f6e9e15460a6"
    }, 
    {
      "status": "cancelled", 
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "title": "Калорійність", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2019-04-01T01:00:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.7", 
      "date": "2019-04-01T01:00:00+03:00", 
      "type": "claim", 
      "id": "ba5d252a97b34eb59da17576585be390"
    }
  ]
}

