PATCH /api/2.4/tenders/0d61666d8cd4462ba51f6c3b87ed5ae2/complaints/f64834200d15482a933872cb9b87076c?acc_token=5eccb419f7fe42ce9a51b0f678d9c20e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/a517b40784e54778a0b10577e0f09045?KeyID=427d4149&Signature=kikGLzhe7Tvj0vapszXeHS44Y3Qk4oVv6PXJSZsAUdX5qAv7tVr6%252BobcrELtVWBrOOhjv9Qi8NwN5TOC9WsqBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-02-06T06:11:29.546734+02:00", 
        "id": "9d710d296c04457da7b32e95adad437b", 
        "dateModified": "2019-02-06T06:11:29.546752+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "scale": "micro", 
      "name": "ДКП «Школяр»", 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "dateSubmitted": "2019-02-06T06:11:29.747631+02:00", 
    "complaintID": "UA-2019-02-06-000001.1", 
    "date": "2019-02-06T06:11:29.750777+02:00", 
    "type": "complaint", 
    "id": "f64834200d15482a933872cb9b87076c"
  }
}

