PATCH /api/2.5/tenders/3f5562211c674ad59a6d4eb6d208950a/complaints/d2943631411348e68a4073a7a05a0244?acc_token=e32b0adec33d4e6f845ce7ea678b7927 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": true, 
    "dateAnswered": "2019-03-18T09:27:45.784126+02:00", 
    "dateSubmitted": "2019-03-18T09:27:45.574502+02:00", 
    "complaintID": "UA-2019-03-18-000001.2", 
    "date": "2019-03-18T09:27:45.884769+02:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "d2943631411348e68a4073a7a05a0244"
  }
}

