GET /api/2.4/tenders/34eccb56914f4c4dac23d97aad014c27/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2018-09-21T05:27:05.356445+03:00", 
      "tendererActionDate": "2018-09-21T05:27:05.984250+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "0bb1b67874f8431cbf4d88a7b517937f", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2018-09-21T05:27:03.052149+03:00", 
      "complaintID": "UA-2018-09-21-000001.1", 
      "date": "2018-09-21T05:27:05.991747+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/9f42e52104674bc18eb4024c1ff9f1d9?KeyID=24bda3e0&Signature=BmWfij90FJX5frBcuq5yNU3wHc8TYWZSHb9%2FFngH7bDFUummJVRkF3cYINSF7MSeRD9%252BdLC8uzyWUtq3uoBNCA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-09-21T05:27:02.296287+03:00", 
          "id": "9f086bd296cd4fcb89dd7ccb41ced06d", 
          "dateModified": "2018-09-21T05:27:02.296343+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/4d851cd0c40247f388e3782c3f91a5f9?KeyID=24bda3e0&Signature=YBwtFHsCyaCjEnn8LLjx0L7RFbiJ666wwEXWIUl3PlSMtSipP6M73XkCkzvS9T86ATgMrPWrttscYe6euM1CCg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-09-21T05:27:05.151376+03:00", 
          "id": "0db42374bb604cdaabf4a5a5182a9813", 
          "dateModified": "2018-09-21T05:27:05.151431+03:00"
        }
      ], 
      "dateAccepted": "2018-09-21T05:27:04.407521+03:00"
    }, 
    {
      "status": "resolved", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "dateAnswered": "2018-09-21T05:27:03.205272+03:00", 
      "dateSubmitted": "2018-09-21T05:27:02.563005+03:00", 
      "complaintID": "UA-2018-09-21-000001.2", 
      "date": "2018-09-21T05:27:03.528686+03:00", 
      "resolution": "Виправлено неконкурентні умови", 
      "id": "d0e15489bf6b40d999cea421dd7d8070"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2018-09-21T05:27:05.550051+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2018-09-21T05:27:04.599641+03:00", 
      "dateSubmitted": "2018-09-21T05:27:02.735940+03:00", 
      "complaintID": "UA-2018-09-21-000001.3", 
      "date": "2018-09-21T05:27:05.557068+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "444237c4dc4845c696b144b3e532609a"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2018-09-21T05:27:04.216049+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "complaint", 
      "acceptance": false, 
      "satisfied": false, 
      "dateEscalated": "2018-09-21T05:27:03.686657+03:00", 
      "dateAnswered": "2018-09-21T05:27:03.359306+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-09-21T05:27:02.883336+03:00", 
      "complaintID": "UA-2018-09-21-000001.4", 
      "date": "2018-09-21T05:27:04.223742+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "53249d49509b4b0c979c1ff997a2a0e8"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-09-21T05:27:05.755047+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2018-09-21T05:27:05.755101+03:00", 
      "dateAccepted": "2018-09-21T05:27:04.788682+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-09-21T05:27:03.849271+03:00", 
      "complaintID": "UA-2018-09-21-000001.5", 
      "date": "2018-09-21T05:27:05.762323+03:00", 
      "type": "complaint", 
      "id": "709b2ddcb31346dbbb266552c835c8e2"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-09-21T05:27:06.409031+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2018-09-21T05:27:06.208096+03:00", 
      "dateAccepted": "2018-09-21T05:27:04.976061+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-09-21T05:27:04.030157+03:00", 
      "complaintID": "UA-2018-09-21-000001.6", 
      "date": "2018-09-21T05:27:06.416752+03:00", 
      "type": "complaint", 
      "id": "f1993d59d6094d919dbc1f75045a75db"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2018-09-21T05:27:06.830739+03:00", 
      "complaintID": "UA-2018-09-21-000001.7", 
      "date": "2018-09-21T05:27:06.838982+03:00", 
      "type": "claim", 
      "id": "a60fb2707fbf459dbcfd92ae2b7d10b0"
    }
  ]
}

