POST /api/2.5/tenders/3f5562211c674ad59a6d4eb6d208950a/complaints/279dc6607aa84bb3aa8eb3f1b7195a78/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 199
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy536030813607$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/3f5562211c674ad59a6d4eb6d208950a/complaints/279dc6607aa84bb3aa8eb3f1b7195a78/documents/0a08ff48740a4af081fd68339bf51cc0
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/effe539dec8345409a15a53c2a060c98?KeyID=4ee0d407&Signature=zqDbjUA2tMkpJz69sm8Il0aiCMuaIIfLPNsCHvYhz0KWNqQDtX%252BDT%2FPwxYAIK4rBhm0MYAqhAxAqfTjQgPszDg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-18T09:27:46.465510+02:00", 
    "id": "0a08ff48740a4af081fd68339bf51cc0", 
    "dateModified": "2019-03-18T09:27:46.465525+02:00"
  }
}

