GET /api/2.4/tenders/4db60d3572b54b7f90700daf504dc8ee/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2018-08-15T10:41:06.046316+03:00", 
      "tendererActionDate": "2018-08-15T10:41:06.544357+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "bd570905f79b431793afd434b9c56289", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2018-08-15T10:41:04.088307+03:00", 
      "complaintID": "UA-2018-08-15-000001.1", 
      "date": "2018-08-15T10:41:06.548944+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/0873835d5b9548afad1902cf1fb755cc?KeyID=7272c50f&Signature=llEFd6YKOZebVdIo5dEVRH8tQfSbbXS1k9mIMC2QbUYdMNfhqleHcapyq16S9XvhYiKRvQs4oClxx70qErYFDw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T10:41:03.435868+03:00", 
          "id": "d64a12e47bfb454f8fc438ad81e5df02", 
          "dateModified": "2018-08-15T10:41:03.435892+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/b284678f871b447696c16c43789b5abd?KeyID=7272c50f&Signature=GrHpumH%2F0M1wq5y%2Fdiln5Mh3wXmbJMvlsd7FIz5iuuaM2kpMytF8Wq%2FFd5DtC4JCzOfn45BUs9gw6LpScxNHDw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T10:41:05.880933+03:00", 
          "id": "6f54a02026364e7abc81e61f8d0e5398", 
          "dateModified": "2018-08-15T10:41:05.880954+03:00"
        }
      ], 
      "dateAccepted": "2018-08-15T10:41:05.257125+03:00"
    }, 
    {
      "status": "resolved", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "dateAnswered": "2018-08-15T10:41:04.228232+03:00", 
      "dateSubmitted": "2018-08-15T10:41:03.681023+03:00", 
      "complaintID": "UA-2018-08-15-000001.2", 
      "date": "2018-08-15T10:41:04.512391+03:00", 
      "resolution": "Виправлено неконкурентні умови", 
      "id": "8f9b36adbeda4e13bffe50ccfd5424dd"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2018-08-15T10:41:06.212156+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2018-08-15T10:41:05.414043+03:00", 
      "dateSubmitted": "2018-08-15T10:41:03.812378+03:00", 
      "complaintID": "UA-2018-08-15-000001.3", 
      "date": "2018-08-15T10:41:06.216731+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "19e25e7dea2e4d5494c28887b3f4b707"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2018-08-15T10:41:05.100397+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "complaint", 
      "acceptance": false, 
      "satisfied": false, 
      "dateEscalated": "2018-08-15T10:41:04.648600+03:00", 
      "dateAnswered": "2018-08-15T10:41:04.367779+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-08-15T10:41:03.941763+03:00", 
      "complaintID": "UA-2018-08-15-000001.4", 
      "date": "2018-08-15T10:41:05.104863+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "016574cc1caa4537b446a64916027927"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-08-15T10:41:06.373751+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2018-08-15T10:41:06.373778+03:00", 
      "dateAccepted": "2018-08-15T10:41:05.570239+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-08-15T10:41:04.791270+03:00", 
      "complaintID": "UA-2018-08-15-000001.5", 
      "date": "2018-08-15T10:41:06.378651+03:00", 
      "type": "complaint", 
      "id": "bff28663c21a4a95a8c0be0ce8cc7a8d"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-08-15T10:41:06.840557+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2018-08-15T10:41:06.675460+03:00", 
      "dateAccepted": "2018-08-15T10:41:05.731978+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-08-15T10:41:04.942599+03:00", 
      "complaintID": "UA-2018-08-15-000001.6", 
      "date": "2018-08-15T10:41:06.845696+03:00", 
      "type": "complaint", 
      "id": "24128a437fa3495994d013f3981c8ec8"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2018-08-15T10:41:07.112195+03:00", 
      "complaintID": "UA-2018-08-15-000001.7", 
      "date": "2018-08-15T10:41:07.117289+03:00", 
      "type": "claim", 
      "id": "b4ae6ce93bf24acda70b6b7a3386cda1"
    }
  ]
}

