PATCH /api/2.5/tenders/056d3399d7c2442193fde6999dd58a11/complaints/b1c7ffb0660e467f86f6b4e01f3d2b43?acc_token=21da91a483604646a98b72cd5398fc0d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2019-04-01T01:00:00+03:00", 
    "complaintID": "UA-2019-04-01-000001.7", 
    "date": "2019-04-01T01:00:00+03:00", 
    "type": "claim", 
    "id": "b1c7ffb0660e467f86f6b4e01f3d2b43"
  }
}

