POST /api/2.4/tenders/4db60d3572b54b7f90700daf504dc8ee/complaints/bd570905f79b431793afd434b9c56289/documents?acc_token=39f18bcf634c4743908edfcee57d0c88 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 201
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy197026043483$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/4db60d3572b54b7f90700daf504dc8ee/complaints/bd570905f79b431793afd434b9c56289/documents/d64a12e47bfb454f8fc438ad81e5df02
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/0873835d5b9548afad1902cf1fb755cc?KeyID=7272c50f&Signature=llEFd6YKOZebVdIo5dEVRH8tQfSbbXS1k9mIMC2QbUYdMNfhqleHcapyq16S9XvhYiKRvQs4oClxx70qErYFDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-15T10:41:03.435868+03:00", 
    "id": "d64a12e47bfb454f8fc438ad81e5df02", 
    "dateModified": "2018-08-15T10:41:03.435892+03:00"
  }
}

