PATCH /api/2.5/tenders/3e7eabcb058f47c492c03f1b2cb05d76/awards/3129964f62d74a8b9e49da6097e44743?acc_token=f6b69a804f20492fa60852bdcba9a296 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-03-28T06:49:55.836184+02:00", 
      "endDate": "2019-04-08T00:00:00+02:00"
    }, 
    "bid_id": "2c833a4cb5b54c16a623fc3e09e18a2a", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "date": "2019-03-28T06:49:56.030246+02:00", 
    "id": "3129964f62d74a8b9e49da6097e44743"
  }
}

