GET /api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/questions/380433c79bb343dea7693f11ceb28140 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2018-08-15T10:41:09.371484+03:00", 
    "title": "Калорійність", 
    "date": "2018-08-15T10:41:09.247358+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "380433c79bb343dea7693f11ceb28140", 
    "questionOf": "tender"
  }
}

