GET /api/2.4/tenders/d93f62e755b94ccbaaf86790df865507/questions/22856ac6de324a29975916c17d0af000 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2019-02-06T06:11:31.871341+02:00", 
    "title": "Калорійність", 
    "date": "2019-02-06T06:11:31.834020+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "22856ac6de324a29975916c17d0af000", 
    "questionOf": "tender"
  }
}

