GET /api/2.5/tenders/3e7eabcb058f47c492c03f1b2cb05d76/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "dateAnswered": "2019-03-28T06:49:52.819728+02:00", 
      "title": "Калорійність", 
      "date": "2019-03-28T06:49:52.777560+02:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "fdaf2190393f4532b285537edac5350f", 
      "questionOf": "tender"
    }
  ]
}

