PATCH /api/2.5/tenders/3e7eabcb058f47c492c03f1b2cb05d76/bids/5e25e8f3dee84ca5864c70feba845911/documents/8a79a74c0fb64f2abedb2f7d4cfff350?acc_token=cdf842dc7b244ba89b04748fef75426d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "confidentiality": "buyerOnly"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "buyerOnly", 
    "language": "uk", 
    "format": "application/pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/3e7eabcb058f47c492c03f1b2cb05d76/bids/5e25e8f3dee84ca5864c70feba845911/documents/8a79a74c0fb64f2abedb2f7d4cfff350?download=5fe2cfe1db2b441bb31b5aefbc1e167a", 
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "title": "Proposal_top_secrets.pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-28T06:49:53.283837+02:00", 
    "id": "8a79a74c0fb64f2abedb2f7d4cfff350", 
    "dateModified": "2019-03-28T06:49:53.283854+02:00"
  }
}

