PATCH /api/2.4/tenders/d93f62e755b94ccbaaf86790df865507/bids/0f32dd73b1894cb49fa0ab68c1cc03a9/documents/bc4cea4d3c514f3eb59d4007b5fc6625?acc_token=99888947cfba40f2b64dcc66a891d995 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "confidentiality": "buyerOnly"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "buyerOnly", 
    "language": "uk", 
    "format": "application/pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/d93f62e755b94ccbaaf86790df865507/bids/0f32dd73b1894cb49fa0ab68c1cc03a9/documents/bc4cea4d3c514f3eb59d4007b5fc6625?download=edcc583bc42e40a2a8382e6c3c28fab5", 
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "title": "Proposal_top_secrets.pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-02-06T06:11:32.245698+02:00", 
    "id": "bc4cea4d3c514f3eb59d4007b5fc6625", 
    "dateModified": "2019-02-06T06:11:32.245711+02:00"
  }
}

