PATCH /api/2.4/tenders/852e1ff0222c4f33aa30c0431e97eba8/bids/a2515f649cae416c9176b2905616bc83/documents/19169f5b42bf407cb9d7e67487b22ce4?acc_token=d49391d5b7e04c24b26d9b006dde2d26 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "confidentiality": "buyerOnly"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "buyerOnly", 
    "language": "uk", 
    "format": "application/pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/852e1ff0222c4f33aa30c0431e97eba8/bids/a2515f649cae416c9176b2905616bc83/documents/19169f5b42bf407cb9d7e67487b22ce4?download=5e38a32d01fd4e7fbc824db34b82bdd8", 
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "title": "Proposal_top_secrets.pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-15T10:42:05.479663+03:00", 
    "id": "19169f5b42bf407cb9d7e67487b22ce4", 
    "dateModified": "2018-08-15T10:42:05.479682+03:00"
  }
}

