PATCH /api/2.4/tenders/e1269242824f43b1831cc5f5b4932e32?acc_token=a388147820ef413bbc00669d121a9b0c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 75
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2018-10-21T05:27:18.700731+03:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "awardCriteria": "lowestCost", 
    "tenderPeriod": {
      "startDate": "2018-09-21T05:27:08.425839+03:00", 
      "endDate": "2018-10-21T05:27:18.700731+03:00"
    }, 
    "title": "Послуги шкільних їдалень", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2018-11-26T00:00:00+03:00"
    }, 
    "complaintPeriod": {
      "startDate": "2018-09-21T05:27:08.425839+03:00", 
      "endDate": "2018-10-17T00:00:00+03:00"
    }, 
    "title_en": "Services in school canteens", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2018-09-21T05:27:08.507188+03:00", 
    "dateModified": "2018-09-21T05:27:08.788022+03:00", 
    "procurementMethodType": "aboveThresholdEU", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "enquiryPeriod": {
      "startDate": "2018-09-21T05:27:08.425839+03:00", 
      "clarificationsUntil": "2018-10-17T05:27:18.700731+03:00", 
      "endDate": "2018-10-11T05:27:18.700731+03:00", 
      "invalidationDate": "2018-09-21T05:27:08.784064+03:00"
    }, 
    "owner": "broker", 
    "next_check": "2018-10-21T05:27:18.700731+03:00", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-10-11T05:26:44.921035+03:00", 
          "endDate": "2018-11-10T05:26:44.921116+03:00"
        }, 
        "id": "136d7b306dda4ddba685602dec43cf71", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-10-11T05:26:44.921152+03:00", 
          "endDate": "2018-11-10T05:26:44.921177+03:00"
        }, 
        "id": "e25d233aa8b7486e9aeca130ee1b44e0", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "id": "e1269242824f43b1831cc5f5b4932e32", 
    "tenderID": "UA-2018-09-21-000001"
  }
}

