PATCH /api/2.5/tenders/d305cbefe8194d4f87288d7da8bc9cc6?acc_token=23f3d8cdadaa4dd9a937b97ece3143f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification.stand-still", 
    "complaintPeriod": {
      "startDate": "2019-02-15T09:26:16.345193+02:00", 
      "endDate": "2019-03-14T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-02-15T09:26:16.345193+02:00", 
      "clarificationsUntil": "2019-03-14T00:00:00+02:00", 
      "endDate": "2019-03-08T09:26:16.345193+02:00", 
      "invalidationDate": "2019-03-18T09:27:48.777149+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "3b6533a0886043a2a23608b94a5cb267", 
        "date": "2019-03-18T09:27:49.396480+02:00", 
        "id": "65f1d5b1d32945e8b6754c985db05ee1"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "b8e572b7329640eda2be6124f84311ab", 
        "date": "2019-03-18T09:27:49.483364+02:00", 
        "id": "4b323974c529434382cdafcaa81cfbce"
      }, 
      {
        "status": "unsuccessful", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "543fc0e22d8e44a0bb351ff5dd24f86b", 
        "date": "2019-03-18T09:27:49.566196+02:00", 
        "id": "4e722ee207ea4ae59f4033bdde20fd82"
      }
    ], 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-03-24T00:00:00+02:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-03-18T09:27:47.895355+02:00", 
        "title": "Калорійність", 
        "date": "2019-03-18T09:27:47.852962+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "2de2bc6f812943f2b5ba4699c964522a", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "d305cbefe8194d4f87288d7da8bc9cc6", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/f47695263561455a971fc864b022662b?KeyID=0dc08b21&Signature=EZfXeN11ZRfRpxmicm33DjWukUpLwnvRiWqHY%252BIJJib0a%252BD1s4L5lEyADfQw8IRMfb5ocToLwat5a0Ojm0nRAQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:27:47.698965+02:00", 
        "id": "5a5f1093325f4646891dc3c9cbd35307", 
        "dateModified": "2019-03-18T09:27:47.698986+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/9b1eb5d4fefe48d59eb1c990d230ca5a?KeyID=0dc08b21&Signature=x58kV78cuaKAhBA6mwMt4imk3x6%2FJvsPI%252ByTCA%252Ba4zLfdQKik7bz3BLqkxXLeU4T57CkGoIU4lRTIENvRwNpDA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:27:47.739489+02:00", 
        "id": "8f32010951e041e3a7bb3f74a76053d9", 
        "dateModified": "2019-03-18T09:27:47.739503+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/1ab61d9827a24ba19c7e5473d2fed091?KeyID=0dc08b21&Signature=niUMnqIoBqE8YZvc0VbHWety1fqVnKHOPytvitTN1%252B46W0z5NeswHc04Z4LkrivZvCauWOWWPe%252Bimve8onzqCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:27:47.739489+02:00", 
        "id": "8f32010951e041e3a7bb3f74a76053d9", 
        "dateModified": "2019-03-18T09:27:47.782616+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2019-03-18T09:27:49.269095+02:00", 
      "endDate": "2019-03-24T00:00:00+02:00"
    }, 
    "tenderID": "UA-2019-03-18-000001", 
    "dateModified": "2019-03-18T09:27:49.836396+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2019-02-15T09:26:16.345193+02:00", 
      "endDate": "2019-03-18T09:26:16.345193+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-03-24T00:00:00+02:00"
    }, 
    "procurementMethodType": "aboveThresholdEU", 
    "date": "2019-03-18T09:27:49.836396+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-07T09:26:16.564711+02:00", 
          "endDate": "2019-05-07T09:26:16.564741+02:00"
        }, 
        "id": "d369c46c520141ed800cfb11f5a4e51d", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-07T09:26:16.564751+02:00", 
          "endDate": "2019-05-07T09:26:16.564758+02:00"
        }, 
        "id": "d03b22ddf3e1451f8b3ff83ffcdc31a8", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/995ab7f74a92436a8946fd6ec70c3591?KeyID=0dc08b21&Signature=AHGfyDnL2pTwRt0vOiVCBUohmNCeRDAkMhepzGf6vPMjNX95eHVh4yNnmPfhVdQqRHGaLIOoNb2gkchsIK3hAg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T09:27:48.231101+02:00", 
            "id": "88fab4f7410b49a68e3d7558052085fc", 
            "dateModified": "2019-03-18T09:27:48.231114+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/d305cbefe8194d4f87288d7da8bc9cc6/bids/3b6533a0886043a2a23608b94a5cb267/documents/e2dc19ea70a3444cace536d1e8188d4c?download=b9102345d42d4cb6b56185a252ba0ea7", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_top_secrets.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T09:27:48.279725+02:00", 
            "id": "e2dc19ea70a3444cace536d1e8188d4c", 
            "dateModified": "2019-03-18T09:27:48.279740+02:00"
          }
        ], 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ], 
        "id": "3b6533a0886043a2a23608b94a5cb267", 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/7010b15ccf8841e2ae6d8b4e615a0a06?KeyID=0dc08b21&Signature=gNs%2F6KoXdRhbTjXg6usI%2F7G6LsmqKLbnV8hn67nsEYU1D7dcOthBwJGBy%252B2QEQPxE7LZ1IhdWieuce8Bu%2FizCg%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T09:27:48.592464+02:00", 
            "id": "3a5ea85e49fc456dae484b6d7c7f9122", 
            "dateModified": "2019-03-18T09:27:48.592477+02:00"
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "b8e572b7329640eda2be6124f84311ab", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "unsuccessful", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal_part1.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/d6d26b2d34a045fdae46852904637785?KeyID=0dc08b21&Signature=p0yvep9dLhYJIroGCEuFtTicEnlZdOd6MzaA56cNxf8YAmphtTzm2x5OT9ffSwL9Pg%252Bl%252Bk%2FHHC7%2Fsgcd7Gq%252BCQ%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T09:27:49.047822+02:00", 
            "id": "56f4919fd2584590b2cca95325bdab0d", 
            "dateModified": "2019-03-18T09:27:49.047838+02:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/d305cbefe8194d4f87288d7da8bc9cc6/bids/543fc0e22d8e44a0bb351ff5dd24f86b/documents/c037b887914e4e2a924f1cc57e463493?download=a44fd64f11bd422a9fbc2ef9e65b658d", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_part2.pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T09:27:49.048306+02:00", 
            "id": "c037b887914e4e2a924f1cc57e463493", 
            "dateModified": "2019-03-18T09:27:49.048321+02:00"
          }
        ], 
        "eligibilityDocuments": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "eligibility_doc.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/303ad3042cb647c299c24bcd6d5f0c28?KeyID=0dc08b21&Signature=4RsNlyhSwlpmWJSKmeg24y%252Bbovq1rASONoPPn9vzurxU5uUOcl%2FD%252B%252B8nsg157rDnBq6FUE%252B4UGkQlCY4ZLvBDA%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T09:27:49.049282+02:00", 
            "id": "dccfc7a1080244e6a71fc4481f4c2bec", 
            "dateModified": "2019-03-18T09:27:49.049297+02:00"
          }
        ], 
        "selfEligible": true, 
        "selfQualified": true, 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ], 
        "id": "543fc0e22d8e44a0bb351ff5dd24f86b"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

