POST /api/2.4/tenders/852e1ff0222c4f33aa30c0431e97eba8/cancellations?acc_token=66c47e3a427c4c0b8edf341b57be739e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/852e1ff0222c4f33aa30c0431e97eba8/cancellations/06d305d939d9414a815c7c7a7c2c91e9
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2018-08-15T10:42:11.414377+03:00", 
    "cancellationOf": "tender", 
    "id": "06d305d939d9414a815c7c7a7c2c91e9"
  }
}

