POST /api/2.4/tenders/d93f62e755b94ccbaaf86790df865507/cancellations?acc_token=6a891e76951f47fe929173f74e9e4168 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/d93f62e755b94ccbaaf86790df865507/cancellations/774b35f71a274038a6abeec2bd9adf67
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2019-02-06T06:11:35.394131+02:00", 
    "cancellationOf": "tender", 
    "id": "774b35f71a274038a6abeec2bd9adf67"
  }
}

