POST /api/2.5/tenders/d305cbefe8194d4f87288d7da8bc9cc6/cancellations?acc_token=23f3d8cdadaa4dd9a937b97ece3143f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/d305cbefe8194d4f87288d7da8bc9cc6/cancellations/49323e8fa0ae44719d7e5eb45ae17550
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2019-03-18T09:27:51.594078+02:00", 
    "cancellationOf": "tender", 
    "id": "49323e8fa0ae44719d7e5eb45ae17550"
  }
}

