PATCH /api/2.5/tenders/7a8abe303b8c47b49a9ff7d612a5fbc7/qualifications/1733653bd6344bd195081adda1a0cffb/complaints/aff7ecace5c848a08553eb589bcaf584?acc_token=bb883a70c18642a1a15f67595ea68c5e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 387
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "answered", 
    "resolutionType": "resolved", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "bid_id": "d56e1dbabc9946b0892b26460cef1c95", 
    "dateAnswered": "2019-03-28T06:50:02.559909+02:00", 
    "dateSubmitted": "2019-03-28T06:50:02.455462+02:00", 
    "complaintID": "UA-2019-03-28-000001.6", 
    "date": "2019-03-28T06:50:02.565050+02:00", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
    "id": "aff7ecace5c848a08553eb589bcaf584"
  }
}

