POST /api/2.5/tenders/b3b518464b274354b841065be848658b/qualifications/aabb043ee27f451ebf0b54cc997c3027/complaints/7c9825c9e2ae4badaf87c757bea624ab/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 149
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="ComplaintResolution.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b3b518464b274354b841065be848658b/qualifications/aabb043ee27f451ebf0b54cc997c3027/complaints/7c9825c9e2ae4badaf87c757bea624ab/documents/f3f7e22d2f4641eb97eecbbc385c27db
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/75099aeabb0f4bb8939d5c4512e3f941?KeyID=a8968c46&Signature=avc%252B05km1g7o46W6tNeclVBL3SmxtDjDe%252BXScPpNrNzTcE%252BMwFzerjGsa9NyNI1jC%252BFO%2FSIsXi0xfyAkEbxZBw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:01+03:00", 
    "id": "f3f7e22d2f4641eb97eecbbc385c27db", 
    "dateModified": "2019-04-01T01:00:01+03:00"
  }
}

