PATCH /api/2.4/tenders/dde551f7d0434648949ecc13ea69eed6/qualifications/d838061be1dc42829aec2a6472184ab7/complaints/6be7e0e58723458980e96640c026872d HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "satisfied"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2018-09-21T05:27:37.209545+03:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/0b2e1a230d8146afbd8817acc4f109e9?KeyID=02f2ae69&Signature=70ZKE04X15QcuRzBbo%252BtWKm%2FyrhIU9sahi8AW7HH%252B6FNo%2F9JtEaRdV6PgmpTHfv2037QkUqQpTz7217M%252B3mCAg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:27:30.043531+03:00", 
        "id": "ba8d0ba926ad402397ec1c82a5d0c6f4", 
        "dateModified": "2018-09-21T05:27:30.043605+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/6c73982a6722483fa47c54e1d8a9ed01?KeyID=02f2ae69&Signature=4Y6hZDDlXDSmL8ZqpBEgxPDMTd70Yn9gpzTFG26ZLulPpN7Bo4MfjJKAJHlFjEaKuQk1pucRcwt%2FJrTfOn0FAg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:27:36.767268+03:00", 
        "id": "fd1caa9eb1fd469ea26fdc873c1cee78", 
        "dateModified": "2018-09-21T05:27:36.767328+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "dateAccepted": "2018-09-21T05:27:35.367606+03:00", 
    "dateSubmitted": "2018-09-21T05:27:30.236491+03:00", 
    "complaintID": "UA-2018-09-21-000001.1", 
    "date": "2018-09-21T05:27:37.227500+03:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "6be7e0e58723458980e96640c026872d"
  }
}

