PATCH /api/2.5/tenders/7a8abe303b8c47b49a9ff7d612a5fbc7/qualifications/1733653bd6344bd195081adda1a0cffb/complaints/2507e3c05a6e4a1a8d636200bfd582cd?acc_token=98b3253e3a6741b2b7899a16704fc8c2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "claim"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "claim", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "d56e1dbabc9946b0892b26460cef1c95", 
    "dateSubmitted": "2019-03-28T06:50:03.246455+02:00", 
    "complaintID": "UA-2019-03-28-000001.8", 
    "date": "2019-03-28T06:50:03.252075+02:00", 
    "type": "claim", 
    "id": "2507e3c05a6e4a1a8d636200bfd582cd"
  }
}

