PATCH /api/2.4/tenders/d96aafa99deb471c93dbf373065d0ceb/qualifications/5ca806fe2ba44b2aab9b927f997930af/complaints/0b6a8056527c4979938f5c190d675237?acc_token=fd73cfbd9e674446b18d63e56bb872f2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "claim"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "claim", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "43b31649deea4284b8d432fc444ace99", 
    "dateSubmitted": "2018-08-15T10:42:19.466904+03:00", 
    "complaintID": "UA-2018-08-15-000001.8", 
    "date": "2018-08-15T10:42:19.475962+03:00", 
    "type": "claim", 
    "id": "0b6a8056527c4979938f5c190d675237"
  }
}

