GET /api/2.5/tenders/3e7eabcb058f47c492c03f1b2cb05d76/bids?acc_token=f6b69a804f20492fa60852bdcba9a296 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/db4f7e0139ad427fbaa0e0c81b2ac82c?KeyID=0053977a&Signature=SPRZ8zn8HqmecOkgwxg348BRlzc2iw7aRWm6icDzrYBYt73CuUOBNStHKeE1cmm62I%2FA54DZwhadbTYzdJ5wBA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:49:53.192047+02:00", 
          "id": "e5a91aaacec341e6ba6b1f09d2f40610", 
          "dateModified": "2019-03-28T06:49:53.192062+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/3e7eabcb058f47c492c03f1b2cb05d76/bids/5e25e8f3dee84ca5864c70feba845911/documents/8a79a74c0fb64f2abedb2f7d4cfff350?download=5fe2cfe1db2b441bb31b5aefbc1e167a", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_top_secrets.pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:49:53.283837+02:00", 
          "id": "8a79a74c0fb64f2abedb2f7d4cfff350", 
          "dateModified": "2019-03-28T06:49:53.283854+02:00"
        }
      ], 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "id": "5e25e8f3dee84ca5864c70feba845911", 
      "eligibilityDocuments": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "eligibility_doc.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/8533884facae412eb1c671bd963e3b43?KeyID=0053977a&Signature=a6Hi0KuIwZnRxDkL9IkiM2QV2zEkSOUTBQT%252BWtXYhpaOawm0qyCvtUBGuQqAoTkb4QcH%2FhDkZzHxxZx%2Fua4CDw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:49:53.599234+02:00", 
          "id": "2d78323042d04e56a4759d5c39489a2a", 
          "dateModified": "2019-03-28T06:49:53.599254+02:00"
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "2c833a4cb5b54c16a623fc3e09e18a2a", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal_part1.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/2530b5d06cfb49daaba2e4286a397040?KeyID=0053977a&Signature=Db3lyYT0JgKh1dVCV%252By8aUuvQguvKTSyTq6smkdY4NSU6Rx17WkALoP8NfsMm%252BAuaP1ZgJs2JZAKDYYA5tomDw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:49:54.114048+02:00", 
          "id": "918f1e04a3bc48c6b55c22352bd69336", 
          "dateModified": "2019-03-28T06:49:54.114062+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/3e7eabcb058f47c492c03f1b2cb05d76/bids/5ef63057e3a94a79bdfa7c720ea2dda8/documents/1dc54b636fd947f4a4d96778c5091174?download=21524a4ad0c7422a81da5c01e1299ef8", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_part2.pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:49:54.114444+02:00", 
          "id": "1dc54b636fd947f4a4d96778c5091174", 
          "dateModified": "2019-03-28T06:49:54.114457+02:00"
        }
      ], 
      "eligibilityDocuments": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "eligibility_doc.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/ddd1c8c7f56d44de9ded0718cc702a79?KeyID=0053977a&Signature=9kTA9fVd4QfpT9jl%252B8v%2Fnkt7Eudi%252BySlCwiDhvskr%252ByaR%2FdZu56mpTWNuQGtKeG%252Bsgmw2t3oeIzdi9FV6e49AQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:49:54.115293+02:00", 
          "id": "0470b591f15344edb4591214018203bb", 
          "dateModified": "2019-03-28T06:49:54.115305+02:00"
        }
      ], 
      "selfEligible": true, 
      "selfQualified": true, 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "id": "5ef63057e3a94a79bdfa7c720ea2dda8"
    }
  ]
}

