GET /api/2.5/tenders/0724be8be323436b997b4efbcc4a7003/qualifications/93b4447bdba2455ca05ea882c76c6c54/complaints/44f4f39a4ef94b59ae5418634ea5c8c7 HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "dateDecision": "2019-04-01T01:10:00+03:00", 
    "tendererActionDate": "2019-04-01T01:10:00+03:00", 
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "author": {
      "contactPoint": {
        "email": "aagt@gmail.com", 
        "telephone": "+380 (322) 91-69-30", 
        "name": "Андрій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137226", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Книга»", 
      "address": {
        "postalCode": "79013", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 34", 
        "region": "м. Львів", 
        "locality": "м. Львів"
      }
    }, 
    "title": "Калорійність", 
    "id": "44f4f39a4ef94b59ae5418634ea5c8c7", 
    "tendererAction": "Умови виправлено", 
    "dateSubmitted": "2019-04-01T01:10:00+03:00", 
    "complaintID": "UA-2019-04-01-000001.1", 
    "date": "2019-04-01T01:10:00+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/94c82cb196854a9a94ac22ed4914c3c1?KeyID=a8968c46&Signature=XtPNT06X0JTItFS9MbtNaWqXEkk2Lka%2FY9ftNp%2FaRXQhetbXMK2h1jrw9Xsjm3Q9iie9csr7nDgwvqFp%2F%252BTkDQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:10:00+03:00", 
        "id": "02610b8a2aee4fdd9283859d7b6d78d5", 
        "dateModified": "2019-04-01T01:10:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/34c7e6f0af5d4beb982c2c6b70e85e22?KeyID=a8968c46&Signature=miLiDxEO8aq3f2f0sviNH1NL7tnM37Cc3M%252Bjh5Hx5lUBiApurVFGYF1uNjWXtNZZ9d5vMa%2FmTrshThUPO5LVAw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:10:00+03:00", 
        "id": "dc2a7ecc43b34b498904b7ae3e4c8c01", 
        "dateModified": "2019-04-01T01:10:00+03:00"
      }
    ], 
    "dateAccepted": "2019-04-01T01:10:00+03:00"
  }
}

