POST /api/2.5/tenders/0724be8be323436b997b4efbcc4a7003/qualifications/93b4447bdba2455ca05ea882c76c6c54/complaints/44f4f39a4ef94b59ae5418634ea5c8c7/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 149
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="ComplaintResolution.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/0724be8be323436b997b4efbcc4a7003/qualifications/93b4447bdba2455ca05ea882c76c6c54/complaints/44f4f39a4ef94b59ae5418634ea5c8c7/documents/dc2a7ecc43b34b498904b7ae3e4c8c01
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d275190427084ffd8fec71c4c13fc4e2?KeyID=a8968c46&Signature=Lh4gEXxHoqgY%252BJRQ%252B8oFmvOSBkWQvyaAFkUeiZCQyh8mRGofKGhWmdMJRl3UAItc%252BtImrWbqekGgyVymON9aDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "dc2a7ecc43b34b498904b7ae3e4c8c01", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

