POST /api/2.5/tenders/2402fabf83304ca19e0d37ba3ad33ea4/qualifications/761e0e540d1d4472b53a5bd3e141e0de/complaints?acc_token=8088bb3ab3fb4b4aa620b2734a836f56 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1682
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "author": {
      "contactPoint": {
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк", 
        "email": "soleksuk@gmail.com"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }, 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/2402fabf83304ca19e0d37ba3ad33ea4/qualifications/761e0e540d1d4472b53a5bd3e141e0de/complaints/3423196945a6467ea2fd50e26d8f0484
{
  "access": {
    "token": "964cb0382681486cbb76fe99d2646f55"
  }, 
  "data": {
    "status": "draft", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "42810f2dc60e4d2ba2d38117fcc07c47", 
    "complaintID": "UA-2019-03-18-000001.1", 
    "date": "2019-03-18T09:27:54.351618+02:00", 
    "type": "claim", 
    "id": "3423196945a6467ea2fd50e26d8f0484"
  }
}

