POST /api/2.4/tenders/dde551f7d0434648949ecc13ea69eed6/qualifications/d838061be1dc42829aec2a6472184ab7/complaints/6be7e0e58723458980e96640c026872d/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 199
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy574512476129$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/dde551f7d0434648949ecc13ea69eed6/qualifications/d838061be1dc42829aec2a6472184ab7/complaints/6be7e0e58723458980e96640c026872d/documents/fd1caa9eb1fd469ea26fdc873c1cee78
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/6c73982a6722483fa47c54e1d8a9ed01?KeyID=02f2ae69&Signature=4Y6hZDDlXDSmL8ZqpBEgxPDMTd70Yn9gpzTFG26ZLulPpN7Bo4MfjJKAJHlFjEaKuQk1pucRcwt%2FJrTfOn0FAg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-09-21T05:27:36.767268+03:00", 
    "id": "fd1caa9eb1fd469ea26fdc873c1cee78", 
    "dateModified": "2018-09-21T05:27:36.767328+03:00"
  }
}

