PATCH /api/2.5/tenders/2402fabf83304ca19e0d37ba3ad33ea4/qualifications/761e0e540d1d4472b53a5bd3e141e0de/complaints/f3422f18e3ad42d69d1b7f205aa26854?acc_token=fdb49ed52d7d48c2beacc5f26022a003 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "satisfied": false
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "invalid", 
    "type": "claim", 
    "satisfied": false, 
    "bid_id": "42810f2dc60e4d2ba2d38117fcc07c47", 
    "dateAnswered": "2019-03-18T09:27:55.153183+02:00", 
    "dateSubmitted": "2019-03-18T09:27:55.061091+02:00", 
    "complaintID": "UA-2019-03-18-000001.7", 
    "date": "2019-03-18T09:27:55.158032+02:00", 
    "resolution": "Вимога не відповідає предмету закупівлі", 
    "id": "f3422f18e3ad42d69d1b7f205aa26854"
  }
}

