PATCH /api/2.5/tenders/2402fabf83304ca19e0d37ba3ad33ea4/qualifications/761e0e540d1d4472b53a5bd3e141e0de/complaints/3423196945a6467ea2fd50e26d8f0484 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "satisfied"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2019-03-18T09:27:56.405442+02:00", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/bec0a49f884e4001a5e2bebbbd0919a7?KeyID=a7644175&Signature=5N7BBa2T3AVemb6DQIL%2FhRkL0ALs9SE2K47pB6DOgvMQkL1%2FM1juYcQ%252BTBXVrQgbxoCDcigCP%252BLUtWlruQ%2FtCQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:27:54.400018+02:00", 
        "id": "cf20f49e0afb47199ee58b7622f2eb15", 
        "dateModified": "2019-03-18T09:27:54.400033+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/377640a4375f4a509ee0a7c3aa660b56?KeyID=a7644175&Signature=aYI6HjPAXrGAip40s%2Fs68kwg7xnuAZYrnhBv5emn8J6sb%252Bp%2FF%252BcBpx8%252B7hwsv1uNUVi4LHev5tjgItLBRLmdBA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:27:56.295552+02:00", 
        "id": "287c3ce9ad174c5eb0120b317f290673", 
        "dateModified": "2019-03-18T09:27:56.295566+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "dateAccepted": "2019-03-18T09:27:55.855782+02:00", 
    "dateSubmitted": "2019-03-18T09:27:54.457895+02:00", 
    "complaintID": "UA-2019-03-18-000001.1", 
    "date": "2019-03-18T09:27:56.411229+02:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "3423196945a6467ea2fd50e26d8f0484"
  }
}

