GET /api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids?acc_token=3cd12c0429cf4dd3b49122aacd01f40a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/0910851ad89d489e800b74486bf165e8?KeyID=b582744b&Signature=cMVDijMW0rcK8Mg%2FCJjrP%252BGHT32bTzwrDL8SDrudElJZeZcfKEN%252B9ujYROHkZQek3Txu9qxWd%2FZ8IkVZUHXNBw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T10:41:10.342926+03:00", 
          "id": "67a84e6ace8040c9a920789ed650f5ff", 
          "dateModified": "2018-08-15T10:41:10.342945+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/7d22de3d543c4d26bb6b7da036b0e177/documents/4638305018984b96aed41ad93652c51e?download=044ea81a7fa64bc28a860fbb97562b96", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_top_secrets.pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T10:41:10.488940+03:00", 
          "id": "4638305018984b96aed41ad93652c51e", 
          "dateModified": "2018-08-15T10:41:10.488962+03:00"
        }
      ], 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "id": "7d22de3d543c4d26bb6b7da036b0e177", 
      "eligibilityDocuments": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "eligibility_doc.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/bfecc191ec884a618189423ffd9ffc91?KeyID=b582744b&Signature=dmAveR%252Bp%252BnRTo3IoUejJ34g%252BnpZoTgxDNsxBrxVYZcxq%252BG72qu7hQzswRvUIAVAoV%2FxyJbLGL%2F06e%252Bd%2FT0muAQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T10:41:11.139346+03:00", 
          "id": "f9b38e7dd4264bc69e013b5c3c74b54c", 
          "dateModified": "2018-08-15T10:41:11.139366+03:00"
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "babd3150a23e4d908abc1979cf0a3693", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal_part1.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/77f365d7b22c4e01b8663dec891224a8?KeyID=b582744b&Signature=QniyZ%2FvF5Us3GfD5bOsZWF5Dp%2FMqdiQ2EaCGNuS4RDyyw82YCJ9U2qCLKQhVFMZJt40KiPGq%2FVuIbQcQnY1UCg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T10:41:12.073031+03:00", 
          "id": "6a2d479dc6244d07960a3093122e320e", 
          "dateModified": "2018-08-15T10:41:12.073050+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/3081fc3a3e5b4bbe935c603e2eeeb581/documents/34c157ac54f04910a224a0fbee75313d?download=9a08672ad10742e9a09267d451a53c8f", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_part2.pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T10:41:12.073701+03:00", 
          "id": "34c157ac54f04910a224a0fbee75313d", 
          "dateModified": "2018-08-15T10:41:12.073721+03:00"
        }
      ], 
      "eligibilityDocuments": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "eligibility_doc.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/984d7951586b46ecb15093ade75be239?KeyID=b582744b&Signature=%252Bp3FbTC2hsJaKU4reN%252B%252B7LTy0HUSrsJZz3RBxzCHz8V3hjfkNaFjZZFTFG3yu4keH%252Bzo88TUWrCPLxCe4yqiCQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T10:41:12.075016+03:00", 
          "id": "8bb40c1b2d41426c963f8f2089c256fb", 
          "dateModified": "2018-08-15T10:41:12.075035+03:00"
        }
      ], 
      "selfEligible": true, 
      "selfQualified": true, 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "id": "3081fc3a3e5b4bbe935c603e2eeeb581"
    }
  ]
}

