PATCH /api/2.5/tenders/0724be8be323436b997b4efbcc4a7003/qualifications/93b4447bdba2455ca05ea882c76c6c54/complaints/9799e27cd3eb48e59d9ef13857c5f6b2?acc_token=7c308be79fa14ce4bbdfd771238b9666 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "satisfied": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": true, 
    "bid_id": "3452ad4012604e918d098f69612e9fb5", 
    "dateAnswered": "2019-04-01T01:10:00+03:00", 
    "dateSubmitted": "2019-04-01T01:10:00+03:00", 
    "complaintID": "UA-2019-04-01-000001.6", 
    "date": "2019-04-01T01:10:00+03:00", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
    "id": "9799e27cd3eb48e59d9ef13857c5f6b2"
  }
}

