POST /api/2.5/tenders/b3b518464b274354b841065be848658b/qualifications/aabb043ee27f451ebf0b54cc997c3027/complaints?acc_token=2019737040e24a208a32f9684e09c1dd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1088
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "author": {
      "contactPoint": {
        "email": "aagt@gmail.com", 
        "telephone": "+380 (322) 91-69-30", 
        "name": "Андрій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137226", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Книга»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "79013", 
        "region": "м. Львів", 
        "streetAddress": "вул. Островського, 34", 
        "locality": "м. Львів"
      }
    }, 
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b3b518464b274354b841065be848658b/qualifications/aabb043ee27f451ebf0b54cc997c3027/complaints/7c9825c9e2ae4badaf87c757bea624ab
{
  "access": {
    "token": "85389a9edbeb4feca9a2a54ae4db879e"
  }, 
  "data": {
    "status": "draft", 
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "bid_id": "28676013bb8949c798543345fcd3aab5", 
    "complaintID": "UA-2019-04-01-000001.1", 
    "date": "2019-04-01T01:00:01+03:00", 
    "type": "claim", 
    "id": "7c9825c9e2ae4badaf87c757bea624ab"
  }
}

