GET /api/2.5/tenders/7a8abe303b8c47b49a9ff7d612a5fbc7/qualifications/1733653bd6344bd195081adda1a0cffb/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2019-03-28T06:50:04.441673+02:00", 
      "tendererActionDate": "2019-03-28T06:50:04.863595+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "c8062a7c4cd64694ad1a44f2a68a8464", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2019-03-28T06:50:02.048834+02:00", 
      "complaintID": "UA-2019-03-28-000001.1", 
      "date": "2019-03-28T06:50:04.871056+02:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/f6f08d7c3a7347c4a8721db0721e0b7f?KeyID=05922d01&Signature=m6SJM5gm0zrrSz7wGy8GfOQZFAMfDvR9vOTx07BG5mV27mU66Vi%252B2QRQwT9ThBu9Z%2FKUWV%252BSM5REHZ71IcRzBg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:50:01.979254+02:00", 
          "id": "5b2e20a052ae4479ab25cba01de403d8", 
          "dateModified": "2019-03-28T06:50:01.979286+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/f45394e63307466285883072ec2f25c7?KeyID=05922d01&Signature=O5RPSH66tdK5zBAChXzSU1nqcZ%2FjtfJi8nE87SYvJirtyGc%2FcNyH3bQuVdO8tG39LLNf%252BywJI0RLSdjxHf%252BUCg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:50:04.315468+02:00", 
          "id": "7eca0d1a0f3040cb9231099689bc4ea5", 
          "dateModified": "2019-03-28T06:50:04.315485+02:00"
        }
      ], 
      "dateAccepted": "2019-03-28T06:50:03.736834+02:00"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2019-03-28T06:50:03.614014+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2019-03-28T06:50:02.110796+02:00", 
      "complaintID": "UA-2019-03-28-000001.2", 
      "date": "2019-03-28T06:50:03.619950+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "5d2792957eca4c1787679f2815b60fe3"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2019-03-28T06:50:04.614717+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2019-03-28T06:50:03.859270+02:00", 
      "dateSubmitted": "2019-03-28T06:50:02.211392+02:00", 
      "complaintID": "UA-2019-03-28-000001.3", 
      "date": "2019-03-28T06:50:04.622604+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "1e4151a83c394dcd8d4df0ecba9eca3a"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-03-28T06:50:05.120969+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2019-03-28T06:50:04.992232+02:00", 
      "dateAccepted": "2019-03-28T06:50:04.045067+02:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-03-28T06:50:02.282538+02:00", 
      "complaintID": "UA-2019-03-28-000001.4", 
      "date": "2019-03-28T06:50:05.128501+02:00", 
      "type": "complaint", 
      "id": "39fd7befd45c4271a082b1ce67e3dc0b"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-03-28T06:50:04.732298+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2019-03-28T06:50:04.732315+02:00", 
      "dateAccepted": "2019-03-28T06:50:04.190105+02:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-03-28T06:50:02.376238+02:00", 
      "complaintID": "UA-2019-03-28-000001.5", 
      "date": "2019-03-28T06:50:04.738134+02:00", 
      "type": "complaint", 
      "id": "55ce105889d54cb09692463efb12361b"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "bid_id": "d56e1dbabc9946b0892b26460cef1c95", 
      "dateAnswered": "2019-03-28T06:50:02.559909+02:00", 
      "dateSubmitted": "2019-03-28T06:50:02.455462+02:00", 
      "complaintID": "UA-2019-03-28-000001.6", 
      "date": "2019-03-28T06:50:02.565050+02:00", 
      "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
      "id": "aff7ecace5c848a08553eb589bcaf584"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "claim", 
      "satisfied": false, 
      "bid_id": "d56e1dbabc9946b0892b26460cef1c95", 
      "dateAnswered": "2019-03-28T06:50:02.914771+02:00", 
      "dateSubmitted": "2019-03-28T06:50:02.782581+02:00", 
      "complaintID": "UA-2019-03-28-000001.7", 
      "date": "2019-03-28T06:50:02.922055+02:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "adf2bc39799a44d9a5390e0e0adde189"
    }, 
    {
      "status": "claim", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "bid_id": "d56e1dbabc9946b0892b26460cef1c95", 
      "dateSubmitted": "2019-03-28T06:50:03.246455+02:00", 
      "complaintID": "UA-2019-03-28-000001.8", 
      "date": "2019-03-28T06:50:03.252075+02:00", 
      "type": "claim", 
      "id": "2507e3c05a6e4a1a8d636200bfd582cd"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "bid_id": "d56e1dbabc9946b0892b26460cef1c95", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2019-03-28T06:50:03.506405+02:00", 
      "complaintID": "UA-2019-03-28-000001.9", 
      "date": "2019-03-28T06:50:03.512225+02:00", 
      "type": "claim", 
      "id": "224c110a9015448c9c844f96857b49cd"
    }
  ]
}

