POST /api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2572
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/77f365d7b22c4e01b8663dec891224a8?KeyID=b582744b&Signature=CtkU5Sj3wFt0jbyR9B5J2gWk7kLTdm1kbbhq6MdzYJuv4XfRFztYoDdXtZC0DjSukvd7SDBw10MBMe5%2BfUjnDg%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "title": "Proposal_part2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/9a08672ad10742e9a09267d451a53c8f?KeyID=b582744b&Signature=XsK0qwsuynIgMnqUIBVClVZI5sHdKe9Va22G3QrDS1vTsVwLbbl4FiN3b9lR%2Bp%2FgUYhpL%2FRep%2BP%2B%2F1J2xuA0AA%3D%3D", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf"
      }
    ], 
    "eligibilityDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/984d7951586b46ecb15093ade75be239?KeyID=b582744b&Signature=IxUqcoyZSwla6%2FnbhHMtJdnkSMyjUEKcThb2H7IBkISyNTMdlNNnBi9DaRmBTIndrwMP9NAuRdulQY72Lxr6Dg%3D%3D", 
        "title": "eligibility_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "selfEligible": true, 
    "value": {
      "amount": 5
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/c49e616977ee4796995a8e1fd6da9ee9?KeyID=b582744b&Signature=H4ly7b%2FzUVMwTl76P7tE66LVV2e9uakBjIq1IqbygZ%2BJtwenMDzhIMqTyZdn2wQb3SCIk7exC6qDOnA4A0%2F7Bg%3D%3D", 
        "title": "financial_doc.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко", 
          "email": "fake@mail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 35", 
          "locality": "м. Львів"
        }
      }
    ], 
    "qualificationDocuments": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/17a89912009a46288ccef506e1238478?KeyID=b582744b&Signature=Oan3jcozz00U36zxwgr5GyH1DqTUbRFUTGQ%2FPTiOO9OpkDyyGtSWEySTs3TDBS88n7LZDqtbw2DH4Qeg3KI1Dg%3D%3D", 
        "title": "qualification_document.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/3081fc3a3e5b4bbe935c603e2eeeb581
{
  "access": {
    "token": "2a084ab4e80e4b20a32822409ea02bf5"
  }, 
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/3081fc3a3e5b4bbe935c603e2eeeb581/documents/6a2d479dc6244d07960a3093122e320e?download=77f365d7b22c4e01b8663dec891224a8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:41:12.073031+03:00", 
        "id": "6a2d479dc6244d07960a3093122e320e", 
        "dateModified": "2018-08-15T10:41:12.073050+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/3081fc3a3e5b4bbe935c603e2eeeb581/documents/34c157ac54f04910a224a0fbee75313d?download=9a08672ad10742e9a09267d451a53c8f", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:41:12.073701+03:00", 
        "id": "34c157ac54f04910a224a0fbee75313d", 
        "dateModified": "2018-08-15T10:41:12.073721+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/3081fc3a3e5b4bbe935c603e2eeeb581/eligibility_documents/8bb40c1b2d41426c963f8f2089c256fb?download=984d7951586b46ecb15093ade75be239", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:41:12.075016+03:00", 
        "id": "8bb40c1b2d41426c963f8f2089c256fb", 
        "dateModified": "2018-08-15T10:41:12.075035+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "3081fc3a3e5b4bbe935c603e2eeeb581", 
    "value": {
      "currency": "UAH", 
      "amount": 5.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "financialDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/3081fc3a3e5b4bbe935c603e2eeeb581/financial_documents/7e158d2823694f9e8142f3630cd3589b?download=c49e616977ee4796995a8e1fd6da9ee9", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:41:12.074346+03:00", 
        "id": "7e158d2823694f9e8142f3630cd3589b", 
        "dateModified": "2018-08-15T10:41:12.074366+03:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 35", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2018-08-15T10:41:12.072201+03:00", 
    "qualificationDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "qualification_document.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/3514b9464efc494e8137301c6df9c0a7/bids/3081fc3a3e5b4bbe935c603e2eeeb581/qualification_documents/7e7d5724bc654b51ba4aaa3ee23c75f7?download=17a89912009a46288ccef506e1238478", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:41:12.075701+03:00", 
        "id": "7e7d5724bc654b51ba4aaa3ee23c75f7", 
        "dateModified": "2018-08-15T10:41:12.075721+03:00"
      }
    ]
  }
}

