GET /api/2.4/tenders/e1269242824f43b1831cc5f5b4932e32/bids/4b0f325b7efa4b3795de8325802ee0aa?acc_token=a388147820ef413bbc00669d121a9b0c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/663a4ba9912a433a93f6cb335afe695f?KeyID=58243f29&Signature=2x6yE0g1HrNC4q%2FwdyM59GC45n158DBGVKPffIGAZpN2IXwyjtjNB9ZeScuZuX8suyGKUrAc2qHAKr9fNkAxAA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:27:13.455801+03:00", 
        "id": "b838642a41a94c8e86974f142f4eafb3", 
        "dateModified": "2018-09-21T05:27:13.455839+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/e1269242824f43b1831cc5f5b4932e32/bids/4b0f325b7efa4b3795de8325802ee0aa/documents/5f8ecc9006704bdeb17b4d16023ce4a4?download=530f803ded434a1185c981a9aad0d8f8", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:27:13.456803+03:00", 
        "id": "5f8ecc9006704bdeb17b4d16023ce4a4", 
        "dateModified": "2018-09-21T05:27:13.456840+03:00"
      }
    ], 
    "eligibilityDocuments": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "eligibility_doc.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/7ed4cf7fc81c42f1a170e14386e2462b?KeyID=58243f29&Signature=CzEkTO71xrMSn9Y9z%2FQhueNP%252B40AcdxocyKjKbL6qEVFs%252BrLVuktKuljLNeYJ2iqw7lniz%252BOO6sqswg%252BTW9YBw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:27:13.458816+03:00", 
        "id": "6fbc1ef866a34567b5d8cf743e790e9d", 
        "dateModified": "2018-09-21T05:27:13.458851+03:00"
      }
    ], 
    "selfEligible": true, 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 35", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "id": "4b0f325b7efa4b3795de8325802ee0aa"
  }
}

