PATCH /api/2.5/tenders/3e7eabcb058f47c492c03f1b2cb05d76/qualifications/9655e03c60c0473091ddfc68a2923d48?acc_token=f6b69a804f20492fa60852bdcba9a296 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "eligible": false, 
    "qualified": false, 
    "bidID": "5ef63057e3a94a79bdfa7c720ea2dda8", 
    "date": "2019-03-28T06:49:54.787270+02:00", 
    "id": "9655e03c60c0473091ddfc68a2923d48"
  }
}

