PATCH /api/2.5/tenders/d305cbefe8194d4f87288d7da8bc9cc6/qualifications/4e722ee207ea4ae59f4033bdde20fd82?acc_token=23f3d8cdadaa4dd9a937b97ece3143f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "eligible": false, 
    "qualified": false, 
    "bidID": "543fc0e22d8e44a0bb351ff5dd24f86b", 
    "date": "2019-03-18T09:27:49.566196+02:00", 
    "id": "4e722ee207ea4ae59f4033bdde20fd82"
  }
}

