GET /api/2.5/tenders?opt_pretty=1 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "next_page": {
    "path": "/api/2.5/tenders?offset=2019-03-18T09%3A27%3A47.536233%2B02%3A00", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.5/tenders?offset=2019-03-18T09%3A27%3A47.536233%2B02%3A00", 
    "offset": "2019-03-18T09:27:47.536233+02:00"
  }, 
  "data": [
    {
      "id": "d305cbefe8194d4f87288d7da8bc9cc6", 
      "dateModified": "2019-03-18T09:27:47.536233+02:00"
    }
  ]
}

