GET /api/2.5/tenders/d305cbefe8194d4f87288d7da8bc9cc6/documents?acc_token=23f3d8cdadaa4dd9a937b97ece3143f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/f47695263561455a971fc864b022662b?KeyID=0dc08b21&Signature=EZfXeN11ZRfRpxmicm33DjWukUpLwnvRiWqHY%252BIJJib0a%252BD1s4L5lEyADfQw8IRMfb5ocToLwat5a0Ojm0nRAQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-03-18T09:27:47.698965+02:00", 
      "id": "5a5f1093325f4646891dc3c9cbd35307", 
      "dateModified": "2019-03-18T09:27:47.698986+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/9b1eb5d4fefe48d59eb1c990d230ca5a?KeyID=0dc08b21&Signature=x58kV78cuaKAhBA6mwMt4imk3x6%2FJvsPI%252ByTCA%252Ba4zLfdQKik7bz3BLqkxXLeU4T57CkGoIU4lRTIENvRwNpDA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-03-18T09:27:47.739489+02:00", 
      "id": "8f32010951e041e3a7bb3f74a76053d9", 
      "dateModified": "2019-03-18T09:27:47.739503+02:00"
    }
  ]
}

