GET /api/2.4/tenders/d93f62e755b94ccbaaf86790df865507/contracts/b499603da0f34800bff0d5745d06a9cb/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "language": "uk", 
      "title": "contract_first_document.doc", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/ee76ce1b33f7425487fe7388c29bd9e3?KeyID=9333ae90&Signature=ba3AjihXnM%2FFkiiTDZVD2twUc7yOUxVkzeg%252Be1I1sweVnAem24nklA%2FAiQIOhH00ybRKpuET8ze%2FYFsx%252BvFICA%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2019-02-06T06:11:34.862146+02:00", 
      "id": "8fe34a4c92f14e78a593da6a41fb917b", 
      "dateModified": "2019-02-06T06:11:34.862161+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "language": "en", 
      "title": "contract_second_document.doc", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/1d41cada4f3c495b9a2b0a60e55a33a9?KeyID=9333ae90&Signature=BQP%2FyG4oRDmYZdkxwmK0fQIbDxRu%2FpLIlrbixCOIMTyRymhb7kslQDNvHQ8rFGQraKiHtvnTD7yYlIkI%252BAi%2FBQ%253D%253D", 
      "format": "application/msword", 
      "title_en": "Title of Document", 
      "description_en": "Description of Document", 
      "datePublished": "2019-02-06T06:11:35.005414+02:00", 
      "documentOf": "tender", 
      "id": "4e539e4c81394c7cb713f6ec80034d29", 
      "dateModified": "2019-02-06T06:11:35.005427+02:00"
    }
  ]
}

