POST /api/2.4/tenders/20a0dca396fe4af29bf2f49051d36ec7/contracts/a78be9359ffe4189a3da6c22f92bf0b0/documents?acc_token=ccfe307a7ddc41d49143f329067ae414 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 206
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy106488985013$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/20a0dca396fe4af29bf2f49051d36ec7/contracts/a78be9359ffe4189a3da6c22f92bf0b0/documents/3d01d0834b87432abdebedc070f65afa
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "language": "uk", 
    "title": "contract_first_document.doc", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/4ff8137d586440b38e0c04c51eee5dc1?KeyID=d0377af1&Signature=ScDEVvqWVpDyAU3%2FcVu4mAhjAHwgSParg%252Bqg6oqWprpKzb5ms%2FlK9gozc6R1v7K5RSFxP6KHnWNzu6h%252B4OIOCQ%253D%253D", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2018-09-09T23:40:41.376826+03:00", 
    "id": "3d01d0834b87432abdebedc070f65afa", 
    "dateModified": "2018-09-09T23:40:41.376917+03:00"
  }
}

