GET /api/2.4/tenders/d93f62e755b94ccbaaf86790df865507/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/2966126d40e044f7b1c9c9da1fe123ca?KeyID=9333ae90&Signature=bamiiHTGFWNU%2Fq93GshCuhjPrDjOQaAefZ1wOeUC7uG0Mmpmu7WgxagvhGrFQiCAtCRMFdMBwLnMAwFXc%2F3BAA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-02-06T06:11:31.693727+02:00", 
      "id": "61cc437c4bef4f24b065e3620427b89f", 
      "dateModified": "2019-02-06T06:11:31.693740+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/ddc87e82135442639ab1a72d0dc147c5?KeyID=9333ae90&Signature=JD9uIPVCtvnhczQyH%2F49kY6tDZtbuZoEADQm775kKOLyuTurc4Xzif5YAUhydddMnGkuHMBs0QQxYT2g5IVGCA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-02-06T06:11:31.733580+02:00", 
      "id": "1af48f4625194f2d9aaf3a16f202e8d1", 
      "dateModified": "2019-02-06T06:11:31.786600+02:00"
    }
  ]
}

