POST /api/2.5/tenders/4ad1cf0c6e304022a48bd15e68797ee2/contracts/ad0cb6b6f24b416cb06fdd4902eb56a2/documents?acc_token=aa42dc7013d84acd84c46a580e4ef534 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 156
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="contract_first_document.doc"
Content-Type: application/msword

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/4ad1cf0c6e304022a48bd15e68797ee2/contracts/ad0cb6b6f24b416cb06fdd4902eb56a2/documents/bf1a90e878704a84afa96c9157f2a84e
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "language": "uk", 
    "title": "contract_first_document.doc", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/16ff0adee81d4bd18c905268e13f9363?KeyID=a8968c46&Signature=jEmfDofN%2FbabmEE3j1mH%2Fli7IRlRYWYA4Zkow72Sq159q0P%252BjRyZnDhbKEGTo%252Bv%252BLTJyKQ5lMaIYhk5fNlVxAw%253D%253D", 
    "format": "application/msword", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:10:00+03:00", 
    "id": "bf1a90e878704a84afa96c9157f2a84e", 
    "dateModified": "2019-04-01T01:10:00+03:00"
  }
}

