GET /api/2.5/tenders/3e7eabcb058f47c492c03f1b2cb05d76/contracts/09a9a605422941e7bb869ad0cd46324a/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "language": "uk", 
      "title": "contract_first_document.doc", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/1ff9f1cfbd5b41448c281d0cafa95996?KeyID=0053977a&Signature=vb0HPXEzCn91ehvgUveAY9ViorWvc20Ny4V4nlizRxyZRXfws7mVHxJPM3e%2FY5pmVNiSG0VB1koVyuyo%252BhnOCg%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2019-03-28T06:49:56.647026+02:00", 
      "id": "783aba7e1e1f4ab5bf7fa758bec21402", 
      "dateModified": "2019-03-28T06:49:56.647042+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "language": "en", 
      "title": "contract_second_document.doc", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/0c93d29daa1243f088c19e0a18016978?KeyID=0053977a&Signature=7On3jhPmtCACTqBrickf3FXAzSksx5s3M2HBt3kR81vE9QbxyMpY9OoAPnt6YnKspmUey%252BvmtEecK5wtP9uNDQ%253D%253D", 
      "format": "application/msword", 
      "title_en": "Title of Document", 
      "description_en": "Description of Document", 
      "datePublished": "2019-03-28T06:49:56.812291+02:00", 
      "documentOf": "tender", 
      "id": "3e4844fcc2364065b9bad8aed64437ad", 
      "dateModified": "2019-03-28T06:49:56.812325+02:00"
    }
  ]
}

