GET /api/2.4/tenders/852e1ff0222c4f33aa30c0431e97eba8/contracts/3f23f441b1ba467aaec8f7ebc4bf76b7/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "language": "uk", 
      "title": "contract_first_document.doc", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/7c1d56077cf94b38a486a2e308e00b80?KeyID=d0524399&Signature=oNPqybnYFD6PtuAG7kRkxjYrt%252BckAP7XL4r757Wf3SufCgFE1LlKuuH0go9V3XsVV%252BCEkyijaiOLr%2FTWPPQPBg%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2018-08-15T10:42:10.597329+03:00", 
      "id": "0992e397538c4cd0ac64bc86f8d01c3f", 
      "dateModified": "2018-08-15T10:42:10.597357+03:00"
    }
  ]
}

