GET /api/2.5/tenders/3e7eabcb058f47c492c03f1b2cb05d76/contracts/09a9a605422941e7bb869ad0cd46324a?acc_token=f6b69a804f20492fa60852bdcba9a296 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "uk", 
        "title": "contract_first_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/1ff9f1cfbd5b41448c281d0cafa95996?KeyID=0053977a&Signature=vb0HPXEzCn91ehvgUveAY9ViorWvc20Ny4V4nlizRxyZRXfws7mVHxJPM3e%2FY5pmVNiSG0VB1koVyuyo%252BhnOCg%253D%253D", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:49:56.647026+02:00", 
        "id": "783aba7e1e1f4ab5bf7fa758bec21402", 
        "dateModified": "2019-03-28T06:49:56.647042+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "language": "en", 
        "title": "contract_second_document.doc", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/0c93d29daa1243f088c19e0a18016978?KeyID=0053977a&Signature=7On3jhPmtCACTqBrickf3FXAzSksx5s3M2HBt3kR81vE9QbxyMpY9OoAPnt6YnKspmUey%252BvmtEecK5wtP9uNDQ%253D%253D", 
        "format": "application/msword", 
        "title_en": "Title of Document", 
        "description_en": "Description of Document", 
        "datePublished": "2019-03-28T06:49:56.812291+02:00", 
        "documentOf": "tender", 
        "id": "3e4844fcc2364065b9bad8aed64437ad", 
        "dateModified": "2019-03-28T06:49:56.812325+02:00"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-17T06:47:08.947035+02:00", 
          "endDate": "2019-05-17T06:47:08.947066+02:00"
        }, 
        "id": "458801e6c4554bd99d040ab560a256bd", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-17T06:47:08.947077+02:00", 
          "endDate": "2019-05-17T06:47:08.947084+02:00"
        }, 
        "id": "33bd4a45adf04470b73fbf111005df6c", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "contractNumber": "contract#1", 
    "period": {
      "startDate": "2019-03-28T06:49:56.448290+02:00", 
      "endDate": "2020-03-27T06:49:56.448312+02:00"
    }, 
    "dateSigned": "2019-03-28T06:49:56.313159+02:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-28T06:49:56.022161+02:00", 
    "awardID": "3129964f62d74a8b9e49da6097e44743", 
    "id": "09a9a605422941e7bb869ad0cd46324a", 
    "contractID": "UA-2019-03-28-000001-1"
  }
}

