GET /api/2.5/tenders/e993c22e00e04a7aa24bf6820fc7ca4f/contracts/f19e1384c5724d4c9d13903089ea7251/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "language": "uk", 
      "title": "contract_first_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/925c9d7c257d46af8abc182b0906c8ca?KeyID=a8968c46&Signature=58nBz5bfi34CCxa56TRRvZ1kvRLvY0OcubEgikz%252BI2w758Pedymp8teBtqrpR4LyTiAE7IYalaZeHK%252BAck%252BIBQ%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:01+03:00", 
      "id": "527038f9465447da876e656d6959a737", 
      "dateModified": "2019-04-01T01:00:01+03:00"
    }
  ]
}

