GET /api/2.5/tenders/e993c22e00e04a7aa24bf6820fc7ca4f/documents?acc_token=bcb1d42ee92c404aba7b0642920a3d67 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/51567431f59d446b85f6f4eb1b0a24d9?KeyID=a8968c46&Signature=nV%2F6rd3rJvkWcqLO7G3ZLONh%2Fjv%2Fk8CpdFl8%2FlZQ6p7kpvparYLOs8A1cm%2FpduWmFP9Y1zKpu0AhkQvt%252BItfAA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "923d3bf684b24f78ac7a3cb37d6b082d", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5134e1a7f4744ab59756ccbb872255e3?KeyID=a8968c46&Signature=qi7HI9qAK0NJpBObDOTBSVwGPVpO%252Bq%252BCFo1%252BgWVyo5LnwZ6qNkKhtM2rpay1kl0IRw5W76gW1YcMCMtdNHPxCw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "8d6f45d57c264a56bae4c74c5ffeef89", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }
  ]
}

