PATCH /api/2.4/tenders/e1269242824f43b1831cc5f5b4932e32/cancellations/4b9877af29b742749025511905630998?acc_token=a388147820ef413bbc00669d121a9b0c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2018-09-21T05:27:20.993549+03:00", 
    "cancellationOf": "tender", 
    "id": "4b9877af29b742749025511905630998"
  }
}

