PATCH /api/2.5/tenders/4ad1cf0c6e304022a48bd15e68797ee2/cancellations/7a29f0f12fa7437ab40e2756bfcef894?acc_token=aa42dc7013d84acd84c46a580e4ef534 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-04-01T01:10:00+03:00", 
    "cancellationOf": "tender", 
    "id": "7a29f0f12fa7437ab40e2756bfcef894"
  }
}

