GET /api/2.5/tenders/d305cbefe8194d4f87288d7da8bc9cc6?acc_token=23f3d8cdadaa4dd9a937b97ece3143f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2019-02-18T09:27:47.945824+02:00", 
      "endDate": "2019-03-16T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-02-18T09:27:47.945824+02:00", 
      "clarificationsUntil": "2019-03-14T00:00:00+02:00", 
      "endDate": "2019-03-10T09:27:47.945824+02:00", 
      "invalidationDate": "2019-03-18T09:27:47.783105+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-03-20T09:27:47.945824+02:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-03-18T09:27:47.895355+02:00", 
        "title": "Калорійність", 
        "date": "2019-03-18T09:27:47.852962+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "2de2bc6f812943f2b5ba4699c964522a", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "d305cbefe8194d4f87288d7da8bc9cc6", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/f47695263561455a971fc864b022662b?KeyID=0dc08b21&Signature=EZfXeN11ZRfRpxmicm33DjWukUpLwnvRiWqHY%252BIJJib0a%252BD1s4L5lEyADfQw8IRMfb5ocToLwat5a0Ojm0nRAQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:27:47.698965+02:00", 
        "id": "5a5f1093325f4646891dc3c9cbd35307", 
        "dateModified": "2019-03-18T09:27:47.698986+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/9b1eb5d4fefe48d59eb1c990d230ca5a?KeyID=0dc08b21&Signature=x58kV78cuaKAhBA6mwMt4imk3x6%2FJvsPI%252ByTCA%252Ba4zLfdQKik7bz3BLqkxXLeU4T57CkGoIU4lRTIENvRwNpDA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:27:47.739489+02:00", 
        "id": "8f32010951e041e3a7bb3f74a76053d9", 
        "dateModified": "2019-03-18T09:27:47.739503+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/1ab61d9827a24ba19c7e5473d2fed091?KeyID=0dc08b21&Signature=niUMnqIoBqE8YZvc0VbHWety1fqVnKHOPytvitTN1%252B46W0z5NeswHc04Z4LkrivZvCauWOWWPe%252Bimve8onzqCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:27:47.739489+02:00", 
        "id": "8f32010951e041e3a7bb3f74a76053d9", 
        "dateModified": "2019-03-18T09:27:47.782616+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "tenderID": "UA-2019-03-18-000001", 
    "dateModified": "2019-03-18T09:27:47.899034+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2019-02-18T09:27:47.945824+02:00", 
      "endDate": "2019-03-20T09:27:47.945824+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-04-25T00:00:00+02:00"
    }, 
    "procurementMethodType": "aboveThresholdEU", 
    "date": "2019-03-18T09:27:47.533863+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-07T09:26:16.564711+02:00", 
          "endDate": "2019-05-07T09:26:16.564741+02:00"
        }, 
        "id": "d369c46c520141ed800cfb11f5a4e51d", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-07T09:26:16.564751+02:00", 
          "endDate": "2019-05-07T09:26:16.564758+02:00"
        }, 
        "id": "d03b22ddf3e1451f8b3ff83ffcdc31a8", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

PATCH /api/2.5/tenders/d305cbefe8194d4f87288d7da8bc9cc6?acc_token=23f3d8cdadaa4dd9a937b97ece3143f3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 38
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "value": {
      "amount": 501.0
    }
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "tenderPeriod should be extended by 7 days", 
      "location": "body", 
      "name": "data"
    }
  ]
}

