POST /api/2.5/tenders/e993c22e00e04a7aa24bf6820fc7ca4f/documents?acc_token=bcb1d42ee92c404aba7b0642920a3d67 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 136
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Notice.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e993c22e00e04a7aa24bf6820fc7ca4f/documents/923d3bf684b24f78ac7a3cb37d6b082d
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/51567431f59d446b85f6f4eb1b0a24d9?KeyID=a8968c46&Signature=nV%2F6rd3rJvkWcqLO7G3ZLONh%2Fjv%2Fk8CpdFl8%2FlZQ6p7kpvparYLOs8A1cm%2FpduWmFP9Y1zKpu0AhkQvt%252BItfAA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "923d3bf684b24f78ac7a3cb37d6b082d", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

