POST /api/2.5/tenders/3e7eabcb058f47c492c03f1b2cb05d76/documents?acc_token=f6b69a804f20492fa60852bdcba9a296 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 193
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy232218795858$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/3e7eabcb058f47c492c03f1b2cb05d76/documents/4966ee40046346cd817971a80a55eb95
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "AwardCriteria.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/95131e28705d48da8c0493c580564ed4?KeyID=0053977a&Signature=iACoS6FV4Iw%252BqLXmbCOUg93ghYjdlqv0W5IUNzSHl0ZrQZ4PRjjvWnkMbDPFmLCZ%252BDa7OygkxlSEcreoBFMOAg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-28T06:49:52.675335+02:00", 
    "id": "4966ee40046346cd817971a80a55eb95", 
    "dateModified": "2019-03-28T06:49:52.675353+02:00"
  }
}

