POST /api/2.4/tenders/852e1ff0222c4f33aa30c0431e97eba8/documents?acc_token=66c47e3a427c4c0b8edf341b57be739e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy440649454121$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/852e1ff0222c4f33aa30c0431e97eba8/documents/0461ba691ea04b4ab422545b2c3747d8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/d4f5d12d64c44a4f81a354525116ec0b?KeyID=d0524399&Signature=wMgGKCtEDF5tDY7Vl%2FNEWcLDXcx5c5cFmXpZ3lctYuCmzirbGQNj%2FE8pG5iBQ%252BvQTgaUeZCOLOYylZSlE6kfDQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-15T10:42:03.737080+03:00", 
    "id": "0461ba691ea04b4ab422545b2c3747d8", 
    "dateModified": "2018-08-15T10:42:03.737101+03:00"
  }
}

