POST /api/2.5/tenders/e993c22e00e04a7aa24bf6820fc7ca4f/bids/d255287e13ad4261a9488f5c40f11fbf/financial_documents?acc_token=9d273580a15c4686b453a780b0783371 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 141
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="financial_doc.pdf"
Content-Type: application/pdf

1000$
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e993c22e00e04a7aa24bf6820fc7ca4f/bids/d255287e13ad4261a9488f5c40f11fbf/financial_documents/240e894110e84cf38b7aea07592c1701
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "public", 
    "language": "uk", 
    "title": "financial_doc.pdf", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e993c22e00e04a7aa24bf6820fc7ca4f/bids/d255287e13ad4261a9488f5c40f11fbf/financial_documents/240e894110e84cf38b7aea07592c1701?download=31b9946575134ae38948f8c868eb4325", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "240e894110e84cf38b7aea07592c1701", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

