PATCH /api/2.4/tenders/22e87e1eab6c4c7aac50c27b4f7ea426/cancellations/a2b0105655024f89b5f8de32d1433e6b?acc_token=dc4b67578f404c6594c38bd2b8a77daf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "description": "Changed description", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/22e87e1eab6c4c7aac50c27b4f7ea426/cancellations/a2b0105655024f89b5f8de32d1433e6b/documents/5d5523e483b9473ca53f4481bd59c5e5?download=5478f6c840cd4c4f9b2f78b8af886e78", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:51:43.186058+03:00", 
        "id": "5d5523e483b9473ca53f4481bd59c5e5", 
        "dateModified": "2018-08-15T10:51:43.186080+03:00"
      }, 
      {
        "description": "Changed description", 
        "title": "Notice-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/22e87e1eab6c4c7aac50c27b4f7ea426/cancellations/a2b0105655024f89b5f8de32d1433e6b/documents/5d5523e483b9473ca53f4481bd59c5e5?download=232b5dee37ed45a9ad983a82558f8d1c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:51:43.186058+03:00", 
        "id": "5d5523e483b9473ca53f4481bd59c5e5", 
        "dateModified": "2018-08-15T10:51:43.493386+03:00"
      }
    ], 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2018-08-15T10:51:43.642856+03:00", 
    "cancellationOf": "tender", 
    "id": "a2b0105655024f89b5f8de32d1433e6b"
  }
}

