PATCH /api/2.4/tenders/22e87e1eab6c4c7aac50c27b4f7ea426/bids/48bcd7f43e484a8d9a582a1246b05f71?acc_token=03c6664f433b4132944ab43cdb13ea4d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
null

