PATCH /api/2.4/tenders/7d413660f66643638984a728c325ba28/bids/0b200a8696c64b99a5a0928c76d575e8?acc_token=b432b66d4b2a42699e96e0a25e068f39 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json
null

