PATCH /api/2.4/tenders/6ade0a2779c442fb8ebc0f7e8867eec0/bids/54c05795c0404f9f840937339ac3819e?acc_token=91192505a6aa43779e88d313955903cc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json
null

