PATCH /api/2.5/tenders/44aafce4c8b3419388f00517b05142c0/questions/b9fd831611d649c1b99cbdc32c184e32?acc_token=102c2b5517b74546859baa840a337113 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2019-04-01T01:00:00+03:00", 
    "title": "Калорійність", 
    "date": "2019-04-01T01:00:00+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "b9fd831611d649c1b99cbdc32c184e32", 
    "questionOf": "tender"
  }
}

