PATCH /api/2.4/tenders/e925b9a969c14e6e91dc2236fb288798/questions/fc3418947a9247c394f3484ad8d6fe3a?acc_token=da27ac85a9134c97b2ae4cc678001521 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2018-08-15T17:58:56.473550+03:00", 
    "title": "Калорійність", 
    "date": "2018-08-15T17:58:56.354569+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "fc3418947a9247c394f3484ad8d6fe3a", 
    "questionOf": "tender"
  }
}

