POST /api/2.4/tenders/e925b9a969c14e6e91dc2236fb288798/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1506
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "author": {
      "contactPoint": {
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк", 
        "email": "soleksuk@gmail.com"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "00137226", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }, 
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/e925b9a969c14e6e91dc2236fb288798/questions/fc3418947a9247c394f3484ad8d6fe3a
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "00137226", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Калорійність", 
    "date": "2018-08-15T17:58:56.354569+03:00", 
    "id": "fc3418947a9247c394f3484ad8d6fe3a", 
    "questionOf": "tender"
  }
}

