GET /api/2.4/tenders/6b2b340d30d64178904847faf7a8267c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2018-07-30T11:03:10.222234+03:00", 
      "endDate": "2018-08-11T00:00:00+03:00"
    }, 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/6b2b340d30d64178904847faf7a8267c", 
    "enquiryPeriod": {
      "startDate": "2018-07-30T11:03:10.222234+03:00", 
      "clarificationsUntil": "2018-08-09T00:00:00+03:00", 
      "endDate": "2018-08-05T11:03:10.222234+03:00", 
      "invalidationDate": "2018-08-15T11:03:26.365070+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-08-15T11:39:10.222234+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "kind": "special", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2018-08-15T11:03:25.247782+03:00", 
        "title": "Калорійність", 
        "date": "2018-08-15T11:03:25.129591+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "b42629f3996f415b8f6cdc3a23b243fc", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "6b2b340d30d64178904847faf7a8267c", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "author": "tender_owner", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/6b2b340d30d64178904847faf7a8267c/documents/8ac526e9a2a84e3581b8209644bacb65?download=41a88b0d6842472a9452b877a5ef51e8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T11:03:24.743610+03:00", 
        "id": "8ac526e9a2a84e3581b8209644bacb65", 
        "dateModified": "2018-08-15T11:03:24.743632+03:00"
      }, 
      {
        "author": "tender_owner", 
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/6b2b340d30d64178904847faf7a8267c/documents/7681ecf22723403296ebf1b17cd1a71d?download=fb035b6fe9864ac885b3e016c2c37e27", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T11:03:24.868203+03:00", 
        "id": "7681ecf22723403296ebf1b17cd1a71d", 
        "dateModified": "2018-08-15T11:03:24.868223+03:00"
      }, 
      {
        "author": "tender_owner", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/6b2b340d30d64178904847faf7a8267c/documents/7681ecf22723403296ebf1b17cd1a71d?download=1bb711d8a24b42e180353e92852a896d", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T11:03:24.868203+03:00", 
        "id": "7681ecf22723403296ebf1b17cd1a71d", 
        "dateModified": "2018-08-15T11:03:25.000494+03:00"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderID": "UA-2018-08-15-000001", 
    "dateModified": "2018-08-15T11:03:27.004748+03:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2018-07-30T11:03:10.222234+03:00", 
      "endDate": "2018-08-15T11:03:10.222234+03:00"
    }, 
    "auctionPeriod": {
      "startDate": "2018-08-15T11:03:10.222234+03:00", 
      "shouldStartAfter": "2018-08-16T00:00:00+03:00"
    }, 
    "procurementMethodType": "aboveThresholdUA", 
    "date": "2018-08-15T11:03:24.319020+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-04T11:03:10.728924+03:00", 
          "endDate": "2018-10-04T11:03:10.728965+03:00"
        }, 
        "id": "cafa2a24418a404d90cae296c2859892", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

