GET /api/2.4/tenders/54c2bbcc5d3e429c952ffbf9c050d7f5/awards/e79ca05ef07a4b21892f4b12e09a628f/complaints/b4f90a5a4a8b44ee9ec70b14080b7ee0 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2018-09-21T05:27:56.656297+03:00", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/54c2bbcc5d3e429c952ffbf9c050d7f5/awards/e79ca05ef07a4b21892f4b12e09a628f/complaints/b4f90a5a4a8b44ee9ec70b14080b7ee0/documents/035187fd29ec49b0abf9d68aa2e1d07c?download=e3ef983691484dbf81ac8d619c997085", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:27:49.376467+03:00", 
        "id": "035187fd29ec49b0abf9d68aa2e1d07c", 
        "dateModified": "2018-09-21T05:27:49.376562+03:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/54c2bbcc5d3e429c952ffbf9c050d7f5/awards/e79ca05ef07a4b21892f4b12e09a628f/complaints/b4f90a5a4a8b44ee9ec70b14080b7ee0/documents/80655569ab9e46efb26101b745d3ac0c?download=c3edeaca67994b6f82a191055ede2e0d", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:27:56.208692+03:00", 
        "id": "80655569ab9e46efb26101b745d3ac0c", 
        "dateModified": "2018-09-21T05:27:56.208780+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2018-09-21T05:27:54.579330+03:00", 
    "dateSubmitted": "2018-09-21T05:27:49.664156+03:00", 
    "complaintID": "UA-2018-09-21-000001.1", 
    "date": "2018-09-21T05:27:56.667724+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "b4f90a5a4a8b44ee9ec70b14080b7ee0"
  }
}

