PATCH /api/2.4/tenders/e7d2741915764685a98acb6492724de5/awards/f92a8fbc69b14c9fb14e9fa6272a0199/complaints/1ebb0458e61945b69251be57f09dbb52 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 217
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "stopped", 
    "decision": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "stopped", 
    "dateDecision": "2018-08-15T17:58:47.922748+03:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "decision": "Тендер скасовується замовником", 
    "acceptance": true, 
    "dateCanceled": "2018-08-15T17:58:47.922774+03:00", 
    "dateAccepted": "2018-08-15T17:58:47.238676+03:00", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2018-08-15T17:58:45.205825+03:00", 
    "complaintID": "UA-2018-08-15-000001.5", 
    "date": "2018-08-15T17:58:47.930281+03:00", 
    "type": "complaint", 
    "id": "1ebb0458e61945b69251be57f09dbb52"
  }
}

