PATCH /api/2.4/tenders/54c2bbcc5d3e429c952ffbf9c050d7f5/awards/7ff0c94b25d144968d88cc06d349083d/complaints/fdc26bf0d3bd4286adc7a51f6272aad2?acc_token=d9d4af2745df44889995081b60b4fa74 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2018-09-21T05:28:00.868356+03:00", 
    "complaintID": "UA-2018-09-21-000001.9", 
    "date": "2018-09-21T05:28:00.882211+03:00", 
    "type": "claim", 
    "id": "fdc26bf0d3bd4286adc7a51f6272aad2"
  }
}

