PATCH /api/2.5/tenders/73c208d134f944ac8f48b32c9afe1d02/awards/56b11c3c5f28484c91f11d3f0b68e1b2?acc_token=57e566dcc0f94dcda2e3db471280698a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/73c208d134f944ac8f48b32c9afe1d02/awards/8e6f03f4f9e94ea497a36c05eb4102cc
{
  "data": {
    "status": "cancelled", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-03-18T09:27:57.801437+02:00", 
      "endDate": "2019-03-18T09:28:00.746015+02:00"
    }, 
    "bid_id": "dffd209e3dfc445190204cb2c3e9a69a", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-18T09:28:00.752482+02:00", 
    "qualified": true, 
    "complaints": [
      {
        "status": "resolved", 
        "dateDecision": "2019-03-18T09:27:59.925079+02:00", 
        "documents": [
          {
            "author": "complaint_owner", 
            "title": "Complaint_Attachement.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/73c208d134f944ac8f48b32c9afe1d02/awards/56b11c3c5f28484c91f11d3f0b68e1b2/complaints/fc2b9aa5e096476684bb0a609277915d/documents/f5ed547fabe54375b5c867a12ef13d42?download=3b2783f0537d44e38e992d5e2b3d4040", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T09:27:57.985462+02:00", 
            "id": "f5ed547fabe54375b5c867a12ef13d42", 
            "dateModified": "2019-03-18T09:27:57.985477+02:00"
          }, 
          {
            "author": "aboveThresholdReviewers", 
            "title": "ComplaintResolution.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/73c208d134f944ac8f48b32c9afe1d02/awards/56b11c3c5f28484c91f11d3f0b68e1b2/complaints/fc2b9aa5e096476684bb0a609277915d/documents/4a1bd3fcf04e4c72a1037dcc0b250523?download=882cd74b2bdd44069106defc41b09665", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T09:27:59.811445+02:00", 
            "id": "4a1bd3fcf04e4c72a1037dcc0b250523", 
            "dateModified": "2019-03-18T09:27:59.811460+02:00"
          }
        ], 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Недостатньо інформації", 
        "tendererAction": "Умови виправлено, вибір переможня буде розгянуто повторно", 
        "tendererActionDate": "2019-03-18T09:28:00.350615+02:00", 
        "dateSubmitted": "2019-03-18T09:27:58.047809+02:00", 
        "complaintID": "UA-2019-03-18-000001.1", 
        "date": "2019-03-18T09:28:00.356396+02:00", 
        "acceptance": true, 
        "type": "complaint", 
        "id": "fc2b9aa5e096476684bb0a609277915d", 
        "dateAccepted": "2019-03-18T09:27:59.348457+02:00"
      }, 
      {
        "status": "invalid", 
        "dateDecision": "2019-03-18T09:27:59.244929+02:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": false, 
        "dateSubmitted": "2019-03-18T09:27:58.107482+02:00", 
        "complaintID": "UA-2019-03-18-000001.2", 
        "date": "2019-03-18T09:27:59.250592+02:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "d18a348d55554bf596febdc2891a8120"
      }, 
      {
        "status": "declined", 
        "dateDecision": "2019-03-18T09:28:00.033828+02:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": true, 
        "dateAccepted": "2019-03-18T09:27:59.448903+02:00", 
        "dateSubmitted": "2019-03-18T09:27:58.174945+02:00", 
        "complaintID": "UA-2019-03-18-000001.3", 
        "date": "2019-03-18T09:28:00.039542+02:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "3b02fb0e9c87472bb8045143a4e8b4c3"
      }, 
      {
        "status": "stopped", 
        "dateDecision": "2019-03-18T09:28:00.573222+02:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "decision": "Тендер скасовується замовником", 
        "acceptance": true, 
        "cancellationReason": "Тендер скасовується замовником", 
        "dateCanceled": "2019-03-18T09:28:00.462156+02:00", 
        "dateAccepted": "2019-03-18T09:27:59.581936+02:00", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateSubmitted": "2019-03-18T09:27:58.242307+02:00", 
        "complaintID": "UA-2019-03-18-000001.4", 
        "date": "2019-03-18T09:28:00.578838+02:00", 
        "type": "complaint", 
        "id": "b65d139b101041db9ed222c9513b9237"
      }, 
      {
        "status": "stopped", 
        "dateDecision": "2019-03-18T09:28:00.148732+02:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "decision": "Тендер скасовується замовником", 
        "acceptance": true, 
        "dateCanceled": "2019-03-18T09:28:00.148749+02:00", 
        "dateAccepted": "2019-03-18T09:27:59.709033+02:00", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateSubmitted": "2019-03-18T09:27:58.316260+02:00", 
        "complaintID": "UA-2019-03-18-000001.5", 
        "date": "2019-03-18T09:28:00.154848+02:00", 
        "type": "complaint", 
        "id": "c603c5383a394c628b403928227351cf"
      }, 
      {
        "status": "answered", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "Недостатньо інформації", 
        "satisfied": true, 
        "dateAnswered": "2019-03-18T09:27:58.547671+02:00", 
        "dateSubmitted": "2019-03-18T09:27:58.397377+02:00", 
        "complaintID": "UA-2019-03-18-000001.6", 
        "date": "2019-03-18T09:27:58.552600+02:00", 
        "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
        "id": "c22398f964f946d694df68a2a7cb0619"
      }, 
      {
        "status": "answered", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "invalid", 
        "type": "claim", 
        "title": "Недостатньо інформації", 
        "satisfied": false, 
        "dateAnswered": "2019-03-18T09:27:58.816852+02:00", 
        "dateSubmitted": "2019-03-18T09:27:58.725094+02:00", 
        "complaintID": "UA-2019-03-18-000001.7", 
        "date": "2019-03-18T09:27:58.822007+02:00", 
        "resolution": "Вимога не відповідає предмету закупівлі", 
        "id": "a4bad94cd0ee429d8dbc3f7422c63781"
      }, 
      {
        "status": "claim", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "13313462", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Недостатньо інформації", 
        "dateSubmitted": "2019-03-18T09:27:59.134851+02:00", 
        "complaintID": "UA-2019-03-18-000001.8", 
        "date": "2019-03-18T09:27:59.140428+02:00", 
        "type": "claim", 
        "id": "c0f5649915474c11ba5c2b33055b9c22"
      }
    ], 
    "id": "56b11c3c5f28484c91f11d3f0b68e1b2"
  }
}

