PATCH /api/2.4/tenders/37cc502a3ab04b2eaae73e7950201d4b/awards/91485a72adf549d5a8c05f98a1d5534b/complaints/d710f50e93da4be29bb13fb5ea53f2e3?acc_token=89240b0938a14b0594342c885899ba50 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/37cc502a3ab04b2eaae73e7950201d4b/awards/91485a72adf549d5a8c05f98a1d5534b/complaints/d710f50e93da4be29bb13fb5ea53f2e3/documents/be389b2c5d22492ab962d093695eda7f?download=424b424573e6488693fe6054e1c2497c", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:51:27.793375+03:00", 
        "id": "be389b2c5d22492ab962d093695eda7f", 
        "dateModified": "2018-08-15T10:51:27.793399+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2018-08-15T10:51:27.950129+03:00", 
    "complaintID": "UA-2018-08-15-000001.1", 
    "date": "2018-08-15T10:51:27.955025+03:00", 
    "type": "complaint", 
    "id": "d710f50e93da4be29bb13fb5ea53f2e3"
  }
}

