PATCH /api/2.4/tenders/37cc502a3ab04b2eaae73e7950201d4b/awards/91485a72adf549d5a8c05f98a1d5534b/complaints/f4421ae64c294757a1d79ef074257eae HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 217
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "stopped", 
    "decision": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "stopped", 
    "dateDecision": "2018-08-15T10:51:31.179040+03:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "decision": "Тендер скасовується замовником", 
    "acceptance": true, 
    "dateCanceled": "2018-08-15T10:51:31.179058+03:00", 
    "dateAccepted": "2018-08-15T10:51:30.504896+03:00", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2018-08-15T10:51:28.571038+03:00", 
    "complaintID": "UA-2018-08-15-000001.5", 
    "date": "2018-08-15T10:51:31.185914+03:00", 
    "type": "complaint", 
    "id": "f4421ae64c294757a1d79ef074257eae"
  }
}

