PATCH /api/2.4/tenders/4dd7bb40b7424bd69cc35e875bd4fbd6/awards/716af8bf9fbd43ba9b454543de2aa2b7/complaints/fde09d8d3ffb4d078589bb13733f7e9b?acc_token=f98e0a604b984432bb5f319b40b5c5fc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "claim"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "claim", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "dateSubmitted": "2018-08-15T17:58:36.324642+03:00", 
    "complaintID": "UA-2018-08-15-000001.8", 
    "date": "2018-08-15T17:58:36.331501+03:00", 
    "type": "claim", 
    "id": "fde09d8d3ffb4d078589bb13733f7e9b"
  }
}

