POST /api/2.5/tenders/e2abb7afb5b5439c9b3a31b7b89c4050/awards/af22100d11ba467d94af5c5a7b7bee67/complaints/331effb8795a4b90949f0ceb1b8bda18/documents?acc_token=01a44a7d46654a41834abe8944be4808 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 203
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy0648373442748$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/e2abb7afb5b5439c9b3a31b7b89c4050/awards/af22100d11ba467d94af5c5a7b7bee67/complaints/331effb8795a4b90949f0ceb1b8bda18/documents/760875f8dd1a4d14876c21b9a8acaa6e
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ea5cd511ee7e4ebf848ad39e36d24917?KeyID=e6c6f06e&Signature=MWF7mi%2FvpEau5zq60YIVNZsRoeRiQj2OWTbSawl0VRNmwXi1dgS6QFt4E5aFOmTOM0rQVb%2FQjcGJo4xOMyi1Bg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "760875f8dd1a4d14876c21b9a8acaa6e", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

