GET /api/2.4/tenders/20e641d96b7b4e0a85054863f4935d2d/awards/47e9c1a980e14124aee85a39f995fe30/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "satisfied", 
      "dateDecision": "2018-08-15T11:03:16.667768+03:00", 
      "documents": [
        {
          "author": "complaint_owner", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/20e641d96b7b4e0a85054863f4935d2d/awards/47e9c1a980e14124aee85a39f995fe30/complaints/e01a0ca201ae4c379184eb710c63c5dc/documents/2b448c1e12e54ffcbc40465adf24f96a?download=8c01ee5adc82403a900842ac8d0459aa", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T11:03:13.536527+03:00", 
          "id": "2b448c1e12e54ffcbc40465adf24f96a", 
          "dateModified": "2018-08-15T11:03:13.536550+03:00"
        }, 
        {
          "author": "aboveThresholdReviewers", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/20e641d96b7b4e0a85054863f4935d2d/awards/47e9c1a980e14124aee85a39f995fe30/complaints/e01a0ca201ae4c379184eb710c63c5dc/documents/9fbc25eb3e7945caada2d58c79a9bca2?download=9024e250474b4880af588c1f018e6110", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T11:03:16.489364+03:00", 
          "id": "9fbc25eb3e7945caada2d58c79a9bca2", 
          "dateModified": "2018-08-15T11:03:16.489393+03:00"
        }
      ], 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateAccepted": "2018-08-15T11:03:15.827250+03:00", 
      "dateSubmitted": "2018-08-15T11:03:13.690412+03:00", 
      "complaintID": "UA-2018-08-15-000001.1", 
      "date": "2018-08-15T11:03:16.674510+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "id": "e01a0ca201ae4c379184eb710c63c5dc"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2018-08-15T11:03:15.662862+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2018-08-15T11:03:13.836943+03:00", 
      "complaintID": "UA-2018-08-15-000001.2", 
      "date": "2018-08-15T11:03:15.669423+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "89f77a4490044ffaa40ec6e6b9a11bfe"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2018-08-15T11:03:16.841971+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2018-08-15T11:03:15.988910+03:00", 
      "dateSubmitted": "2018-08-15T11:03:13.990873+03:00", 
      "complaintID": "UA-2018-08-15-000001.3", 
      "date": "2018-08-15T11:03:16.848979+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "5b87b5294b9b4d2f8dc751e69c196a5d"
    }, 
    {
      "status": "accepted", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2018-08-15T11:03:16.153470+03:00", 
      "dateSubmitted": "2018-08-15T11:03:14.149503+03:00", 
      "complaintID": "UA-2018-08-15-000001.4", 
      "date": "2018-08-15T11:03:16.159856+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "3b32298a94f847439f5d0f01872ff562"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-08-15T11:03:17.012260+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2018-08-15T11:03:17.012279+03:00", 
      "dateAccepted": "2018-08-15T11:03:16.320711+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-08-15T11:03:14.315632+03:00", 
      "complaintID": "UA-2018-08-15-000001.5", 
      "date": "2018-08-15T11:03:17.019369+03:00", 
      "type": "complaint", 
      "id": "a9bad40d38c74629b595d3ddbf546027"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "resolutionType": "resolved", 
      "type": "claim", 
      "title": "Недостатньо інформації", 
      "satisfied": true, 
      "dateAnswered": "2018-08-15T11:03:14.594752+03:00", 
      "dateSubmitted": "2018-08-15T11:03:14.452336+03:00", 
      "complaintID": "UA-2018-08-15-000001.6", 
      "date": "2018-08-15T11:03:14.600447+03:00", 
      "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
      "id": "90583d5d857645b0840c91e8eb4e45bc"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "resolutionType": "invalid", 
      "type": "claim", 
      "title": "Недостатньо інформації", 
      "satisfied": false, 
      "dateAnswered": "2018-08-15T11:03:15.032942+03:00", 
      "dateSubmitted": "2018-08-15T11:03:14.880642+03:00", 
      "complaintID": "UA-2018-08-15-000001.7", 
      "date": "2018-08-15T11:03:15.040981+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "8c686ccb3cbb4501bbbe3717c7942b8c"
    }, 
    {
      "status": "claim", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "dateSubmitted": "2018-08-15T11:03:15.499833+03:00", 
      "complaintID": "UA-2018-08-15-000001.8", 
      "date": "2018-08-15T11:03:15.506421+03:00", 
      "type": "claim", 
      "id": "bdf45c16b594470c987380d4e7e7ae75"
    }
  ]
}

