PATCH /api/2.5/tenders/59d0b67423864278a983b4169d541645/awards/e8dca6f4ea8d4b909a9981f8b4e0f90d/complaints/4e750546e651458faa34230f0709f0f0?acc_token=4546585f49d542fca378e21c63ef578f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 29
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "satisfied": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "answered", 
    "transfer_token": "6736f1cc14b2e11fe9d6807a0562a3e2937c5ae976f353e8094b3748cc6ff1f476963d23a4842c9bb5420e90426e761ff28db0c9d2a85565ce958a1ec97702cc", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "satisfied": true, 
    "dateAnswered": "2019-04-01T01:00:01+03:00", 
    "dateSubmitted": "2019-04-01T01:00:01+03:00", 
    "complaintID": "UA-2019-04-01-000001.6", 
    "date": "2019-04-01T01:00:01+03:00", 
    "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
    "id": "4e750546e651458faa34230f0709f0f0", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс."
  }
}

