GET /api/2.4/tenders/22e87e1eab6c4c7aac50c27b4f7ea426/bids/48bcd7f43e484a8d9a582a1246b05f71?acc_token=03c6664f433b4132944ab43cdb13ea4d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/22e87e1eab6c4c7aac50c27b4f7ea426/bids/48bcd7f43e484a8d9a582a1246b05f71/documents/cb66ffc93d904141b78045edf36277bb?download=483e1f06362b40b8a92b31a30fc555b7", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-15T10:51:40.412002+03:00", 
        "id": "cb66ffc93d904141b78045edf36277bb", 
        "dateModified": "2018-08-15T10:51:40.412021+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "48bcd7f43e484a8d9a582a1246b05f71", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "subcontractingDetails": "ДКП «книга», Україна, м. Львів, вул. Островського, 33", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2018-08-15T10:51:40.209389+03:00", 
    "selfQualified": true, 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/22e87e1eab6c4c7aac50c27b4f7ea426?key_for_bid=48bcd7f43e484a8d9a582a1246b05f71"
  }
}

