GET /api/2.5/tenders/e98f6645e699429dbd9f81a745a81784/bids/27824d18035f4375bc2adcae82767e07?acc_token=7bb8f79380b44c2391551f8f1ed0b08b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "selfEligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "27824d18035f4375bc2adcae82767e07", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-03-18T09:28:04.316763+02:00", 
    "selfQualified": true, 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/e98f6645e699429dbd9f81a745a81784?key_for_bid=27824d18035f4375bc2adcae82767e07"
  }
}

