GET /api/2.5/tenders/fd3bff85b6cf4847a886943870d4ed9d/bids/d05627950b7c45ce8d8608e78487fa31?acc_token=df6a6cd774914cbaa7ac78717d798ca9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "d05627950b7c45ce8d8608e78487fa31"
  }
}

