GET /api/2.4/tenders/6ade0a2779c442fb8ebc0f7e8867eec0/bids/54c05795c0404f9f840937339ac3819e?acc_token=91192505a6aa43779e88d313955903cc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/6ade0a2779c442fb8ebc0f7e8867eec0/bids/54c05795c0404f9f840937339ac3819e/documents/adf27194727d4a99bedafad014c12227?download=abefb0fd53a64deb99a860f2270b40ae", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-02-06T06:11:49.439517+02:00", 
        "id": "adf27194727d4a99bedafad014c12227", 
        "dateModified": "2019-02-06T06:11:49.439530+02:00"
      }
    ], 
    "selfEligible": true, 
    "id": "54c05795c0404f9f840937339ac3819e", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "subcontractingDetails": "ДКП «книга», Україна, м. Львів, вул. Островського, 33", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-02-06T06:11:49.372401+02:00", 
    "selfQualified": true, 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/6ade0a2779c442fb8ebc0f7e8867eec0?key_for_bid=54c05795c0404f9f840937339ac3819e"
  }
}

