GET /api/2.4/tenders/7d413660f66643638984a728c325ba28/bids/0b200a8696c64b99a5a0928c76d575e8?acc_token=b432b66d4b2a42699e96e0a25e068f39 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/7d413660f66643638984a728c325ba28/bids/0b200a8696c64b99a5a0928c76d575e8/documents/813cb717e1344c71a8d0b7d2f63e30fa?download=b121b6899f6a4713a5bde0c202d8711a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:28:11.799622+03:00", 
        "id": "813cb717e1344c71a8d0b7d2f63e30fa", 
        "dateModified": "2018-09-21T05:28:11.799694+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "0b200a8696c64b99a5a0928c76d575e8", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "subcontractingDetails": "ДКП «книга», Україна, м. Львів, вул. Островського, 33", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2018-09-21T05:28:11.548858+03:00", 
    "selfQualified": true, 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/7d413660f66643638984a728c325ba28?key_for_bid=0b200a8696c64b99a5a0928c76d575e8"
  }
}

