PATCH /api/2.5/tenders/44aafce4c8b3419388f00517b05142c0/bids/3255bc832a8c4490a8f4dffd9a784e0a?acc_token=1cbee7a7dbda4ab7b03dfb939ee5193f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "Proposal.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/44aafce4c8b3419388f00517b05142c0/bids/3255bc832a8c4490a8f4dffd9a784e0a/documents/67451197c834416989821c6cd4dcf2d2?download=d29e0bc66ec1409fb318fa2351b6d912", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "67451197c834416989821c6cd4dcf2d2", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "selfEligible": true, 
    "id": "3255bc832a8c4490a8f4dffd9a784e0a", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-04-01T01:00:00+03:00", 
    "selfQualified": true
  }
}

