PATCH /api/2.4/tenders/1c604f7cf7b44f8298379f8988c28216/complaints/9a8280633d394635b6252842691ba5d3?acc_token=d9b905f233df4f7d902db45e73a06e7f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2018-09-21T05:28:07.488190+03:00", 
    "complaintID": "UA-2018-09-21-000001.7", 
    "date": "2018-09-21T05:28:07.498856+03:00", 
    "type": "claim", 
    "id": "9a8280633d394635b6252842691ba5d3"
  }
}

