PATCH /api/2.4/tenders/2d3728482f284156ba8fb6474be5be0f/complaints/57d457a627914ecda7d9f79cbaf12d47?acc_token=9a63e88dc5c54723b8144d692813f330 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 228
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "stopping", 
    "cancellationReason": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "stopping", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "scale": "micro", 
      "name": "ДКП «Школяр»", 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "cancellationReason": "Тендер скасовується замовником", 
    "dateCanceled": "2019-02-06T06:11:48.289767+02:00", 
    "dateAccepted": "2019-02-06T06:11:47.893148+02:00", 
    "dateSubmitted": "2019-02-06T06:11:47.551943+02:00", 
    "complaintID": "UA-2019-02-06-000001.6", 
    "date": "2019-02-06T06:11:48.293626+02:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "57d457a627914ecda7d9f79cbaf12d47"
  }
}

