POST /api/2.4/tenders/1fc024d3d72f4da5985c97f78b3d12d1/complaints/61e2d835ffa14780a904015d6b3fa50f/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 199
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy652663082931$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/1fc024d3d72f4da5985c97f78b3d12d1/complaints/61e2d835ffa14780a904015d6b3fa50f/documents/22dcfd14b9374eb4bd416b97e8eba764
{
  "data": {
    "author": "aboveThresholdReviewers", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/1fc024d3d72f4da5985c97f78b3d12d1/complaints/61e2d835ffa14780a904015d6b3fa50f/documents/22dcfd14b9374eb4bd416b97e8eba764?download=74a84f77ecd746de8830006b40ea98f6", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-15T10:51:36.082423+03:00", 
    "id": "22dcfd14b9374eb4bd416b97e8eba764", 
    "dateModified": "2018-08-15T10:51:36.082447+03:00"
  }
}

