PATCH /api/2.4/tenders/518e55607ba84504b873d4f336903ded/complaints/3aaa61e0682a4bc9bd8ea964d69befc7?acc_token=cdb3821ce5924750a7459c40318312ac HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending", 
    "satisfied": false
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "resolutionType": "invalid", 
    "type": "complaint", 
    "title": "Недостатньо інформації", 
    "satisfied": false, 
    "dateEscalated": "2018-08-15T17:58:41.588416+03:00", 
    "dateAnswered": "2018-08-15T17:58:41.322685+03:00", 
    "dateSubmitted": "2018-08-15T17:58:40.925992+03:00", 
    "complaintID": "UA-2018-08-15-000001.4", 
    "date": "2018-08-15T17:58:41.591885+03:00", 
    "resolution": "Вимога не відповідає предмету закупівлі", 
    "id": "3aaa61e0682a4bc9bd8ea964d69befc7"
  }
}

