PATCH /api/2.4/tenders/f0ffe8dd6bf647cc80ffb44c3eec86bc/complaints/dce0edd00a33445d94d95c4691e6b666?acc_token=24bf1df4d1fc4b6787ddf0ef391e60fd HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": true, 
    "dateAnswered": "2018-08-15T11:03:20.359417+03:00", 
    "dateSubmitted": "2018-08-15T11:03:19.849797+03:00", 
    "complaintID": "UA-2018-08-15-000001.2", 
    "date": "2018-08-15T11:03:20.631516+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "dce0edd00a33445d94d95c4691e6b666"
  }
}

