GET /api/2.4/tenders/1fc024d3d72f4da5985c97f78b3d12d1/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2018-08-15T10:51:36.251014+03:00", 
      "documents": [
        {
          "author": "complaint_owner", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/1fc024d3d72f4da5985c97f78b3d12d1/complaints/61e2d835ffa14780a904015d6b3fa50f/documents/9b4546ca93ea40628544cab421b3497f?download=a0e8411a9afa49dc8727ef3806ad1bee", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T10:51:33.745345+03:00", 
          "id": "9b4546ca93ea40628544cab421b3497f", 
          "dateModified": "2018-08-15T10:51:33.745369+03:00"
        }, 
        {
          "author": "aboveThresholdReviewers", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/1fc024d3d72f4da5985c97f78b3d12d1/complaints/61e2d835ffa14780a904015d6b3fa50f/documents/22dcfd14b9374eb4bd416b97e8eba764?download=74a84f77ecd746de8830006b40ea98f6", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T10:51:36.082423+03:00", 
          "id": "22dcfd14b9374eb4bd416b97e8eba764", 
          "dateModified": "2018-08-15T10:51:36.082447+03:00"
        }
      ], 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "tendererAction": "Умови виправлено", 
      "tendererActionDate": "2018-08-15T10:51:36.673671+03:00", 
      "dateSubmitted": "2018-08-15T10:51:34.358978+03:00", 
      "complaintID": "UA-2018-08-15-000001.1", 
      "date": "2018-08-15T10:51:36.678167+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "id": "61e2d835ffa14780a904015d6b3fa50f", 
      "dateAccepted": "2018-08-15T10:51:35.482058+03:00"
    }, 
    {
      "status": "resolved", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "dateAnswered": "2018-08-15T10:51:34.492480+03:00", 
      "dateSubmitted": "2018-08-15T10:51:33.978594+03:00", 
      "complaintID": "UA-2018-08-15-000001.2", 
      "date": "2018-08-15T10:51:34.768999+03:00", 
      "resolution": "Виправлено неконкурентні умови", 
      "id": "aa7f369b917b4b63813dc3678b5c74cf"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2018-08-15T10:51:36.376679+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2018-08-15T10:51:35.631187+03:00", 
      "dateSubmitted": "2018-08-15T10:51:34.098879+03:00", 
      "complaintID": "UA-2018-08-15-000001.3", 
      "date": "2018-08-15T10:51:36.381844+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "5b8cf1bd92564e87903a612aa96d8f20"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2018-08-15T10:51:35.326781+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "complaint", 
      "acceptance": false, 
      "satisfied": false, 
      "dateEscalated": "2018-08-15T10:51:34.901579+03:00", 
      "dateAnswered": "2018-08-15T10:51:34.628709+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-08-15T10:51:34.223328+03:00", 
      "complaintID": "UA-2018-08-15-000001.4", 
      "date": "2018-08-15T10:51:35.331024+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "ffcc35a6ea914470a84d1a2b0ca5de8e"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-08-15T10:51:36.539226+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2018-08-15T10:51:36.539255+03:00", 
      "dateAccepted": "2018-08-15T10:51:35.780051+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-08-15T10:51:35.038062+03:00", 
      "complaintID": "UA-2018-08-15-000001.5", 
      "date": "2018-08-15T10:51:36.544150+03:00", 
      "type": "complaint", 
      "id": "1f5b6ca02c1d48beae48f5560220490e"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-08-15T10:51:37.029774+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2018-08-15T10:51:36.836536+03:00", 
      "dateAccepted": "2018-08-15T10:51:35.935979+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-08-15T10:51:35.177808+03:00", 
      "complaintID": "UA-2018-08-15-000001.6", 
      "date": "2018-08-15T10:51:37.037168+03:00", 
      "type": "complaint", 
      "id": "2ee8565212fd4ebeb2342a6680aa5620"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2018-08-15T10:51:37.376081+03:00", 
      "complaintID": "UA-2018-08-15-000001.7", 
      "date": "2018-08-15T10:51:37.383379+03:00", 
      "type": "claim", 
      "id": "5cc6c19c76cf4c42b714e34004e4c5b4"
    }
  ]
}

