POST /api/2.5/tenders/64e0b6f7a9744698ade391c330fbbe9c/complaints/65346a9b20df4a448bcfdf7dd0ac4bcc/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 199
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy716675358205$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/64e0b6f7a9744698ade391c330fbbe9c/complaints/65346a9b20df4a448bcfdf7dd0ac4bcc/documents/3c6f320734dd412b8d828817d45e8986
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/cc691b68bc574857937960b928aa91c1?KeyID=a8968c46&Signature=zHmoCML15SGx02i%2F8FJkIsg7lq%2FWuQUWhXN4PQptXsRVzmF%252BiO2%252B%2FaLVDK53420XCBa2joOVzU%2FzExGU%252B37eCg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "3c6f320734dd412b8d828817d45e8986", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

