GET /api/2.4/tenders/f0ffe8dd6bf647cc80ffb44c3eec86bc/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2018-08-15T11:03:22.090664+03:00", 
      "documents": [
        {
          "author": "complaint_owner", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/f0ffe8dd6bf647cc80ffb44c3eec86bc/complaints/d12a70c659e74c6bafc1c93c855ebcea/documents/5b71ee27defd4296bda4c7d5d6988c59?download=f7a7378175cf43b1b6a9f7169695448d", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T11:03:19.616622+03:00", 
          "id": "5b71ee27defd4296bda4c7d5d6988c59", 
          "dateModified": "2018-08-15T11:03:19.616645+03:00"
        }, 
        {
          "author": "aboveThresholdReviewers", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/f0ffe8dd6bf647cc80ffb44c3eec86bc/complaints/d12a70c659e74c6bafc1c93c855ebcea/documents/fcff11b5c46d4e28b05b54e2b82c57dc?download=29ec1f484d21401bad21223bf59d8576", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-15T11:03:21.929837+03:00", 
          "id": "fcff11b5c46d4e28b05b54e2b82c57dc", 
          "dateModified": "2018-08-15T11:03:21.929860+03:00"
        }
      ], 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "tendererAction": "Умови виправлено", 
      "tendererActionDate": "2018-08-15T11:03:22.568059+03:00", 
      "dateSubmitted": "2018-08-15T11:03:20.226487+03:00", 
      "complaintID": "UA-2018-08-15-000001.1", 
      "date": "2018-08-15T11:03:22.572455+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "id": "d12a70c659e74c6bafc1c93c855ebcea", 
      "dateAccepted": "2018-08-15T11:03:21.337678+03:00"
    }, 
    {
      "status": "resolved", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "dateAnswered": "2018-08-15T11:03:20.359417+03:00", 
      "dateSubmitted": "2018-08-15T11:03:19.849797+03:00", 
      "complaintID": "UA-2018-08-15-000001.2", 
      "date": "2018-08-15T11:03:20.631516+03:00", 
      "resolution": "Виправлено неконкурентні умови", 
      "id": "dce0edd00a33445d94d95c4691e6b666"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2018-08-15T11:03:22.246505+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2018-08-15T11:03:21.486457+03:00", 
      "dateSubmitted": "2018-08-15T11:03:19.968595+03:00", 
      "complaintID": "UA-2018-08-15-000001.3", 
      "date": "2018-08-15T11:03:22.251152+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "11a02e0122034b3bb17247deac0474e8"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2018-08-15T11:03:21.186631+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "complaint", 
      "acceptance": false, 
      "satisfied": false, 
      "dateEscalated": "2018-08-15T11:03:20.764637+03:00", 
      "dateAnswered": "2018-08-15T11:03:20.492043+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-08-15T11:03:20.090497+03:00", 
      "complaintID": "UA-2018-08-15-000001.4", 
      "date": "2018-08-15T11:03:21.191067+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "00a64b0124e64b4daa402cf9e8bc9262"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-08-15T11:03:22.402995+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2018-08-15T11:03:22.403021+03:00", 
      "dateAccepted": "2018-08-15T11:03:21.634989+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-08-15T11:03:20.901172+03:00", 
      "complaintID": "UA-2018-08-15-000001.5", 
      "date": "2018-08-15T11:03:22.407956+03:00", 
      "type": "complaint", 
      "id": "adddf53feec346afa8411082ef284cf8"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-08-15T11:03:22.883312+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2018-08-15T11:03:22.726290+03:00", 
      "dateAccepted": "2018-08-15T11:03:21.786784+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-08-15T11:03:21.041444+03:00", 
      "complaintID": "UA-2018-08-15-000001.6", 
      "date": "2018-08-15T11:03:22.887741+03:00", 
      "type": "complaint", 
      "id": "13141ec75d75429195e1bb4484d8a267"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2018-08-15T11:03:23.203967+03:00", 
      "complaintID": "UA-2018-08-15-000001.7", 
      "date": "2018-08-15T11:03:23.208707+03:00", 
      "type": "claim", 
      "id": "b29df4f0d09c4eb19450e74223e15589"
    }
  ]
}

