GET /api/2.4/tenders/22e87e1eab6c4c7aac50c27b4f7ea426/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "dateAnswered": "2018-08-15T10:51:39.548784+03:00", 
      "title": "Калорійність", 
      "date": "2018-08-15T10:51:39.427564+03:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "1778436402d4496ebb15ea8b784781af", 
      "questionOf": "tender"
    }
  ]
}

