PATCH /api/2.5/tenders/425a24b7b03d49759b19d37ac7e51561?acc_token=9339c9eca13f47388862c5e3b8cb3d23 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 75
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2019-04-12T06:50:23.220327+02:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "awardCriteria": "lowestCost", 
    "tenderPeriod": {
      "startDate": "2019-03-28T06:50:13.173790+02:00", 
      "endDate": "2019-04-12T06:50:23.220327+02:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "enquiryPeriod": {
      "startDate": "2019-03-28T06:50:13.173790+02:00", 
      "clarificationsUntil": "2019-04-05T06:50:23.220327+02:00", 
      "endDate": "2019-04-02T06:50:23.220327+02:00", 
      "invalidationDate": "2019-03-28T06:50:13.253165+02:00"
    }, 
    "complaintPeriod": {
      "startDate": "2019-03-28T06:50:13.173790+02:00", 
      "endDate": "2019-04-08T00:00:00+03:00"
    }, 
    "procurementMethodType": "aboveThresholdUA", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2019-03-28T06:50:13.191039+02:00", 
    "next_check": "2019-04-12T07:50:23.220327+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "kind": "special", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-04-13T00:00:00+02:00"
    }, 
    "owner": "broker", 
    "dateModified": "2019-03-28T06:50:13.255236+02:00", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-17T06:47:08.962424+02:00", 
          "endDate": "2019-05-17T06:47:08.962464+02:00"
        }, 
        "id": "55c10c6897b8430bbed91d63761a9ce7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "id": "425a24b7b03d49759b19d37ac7e51561", 
    "tenderID": "UA-2019-03-28-000001"
  }
}

