PATCH /api/2.5/tenders/92f0a69805904e71be9e717fad623af5/cancellations/b8dd02c4d0e347669b146cb7344f625c/documents/047cb43ee1c14f5e93645a882db02382?acc_token=a7b6575bd2064c97b965ea003187c336 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/fc9223d3e76744c6a073250955fba6ad?KeyID=a8968c46&Signature=PYzqi2a7zrscEVB6LyzOd%252BVvxF6B0MXWQt%2F9%2Fg3WaenCJaMG1IrzXkGvYY0TMKOBTeR08goZ%252BEE7iwUbn1c%2FDA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:10:00+03:00", 
    "id": "047cb43ee1c14f5e93645a882db02382", 
    "dateModified": "2019-04-01T01:10:00+03:00"
  }
}

