POST /api/2.4/tenders/7d413660f66643638984a728c325ba28/cancellations?acc_token=12e688f20b5f44fe8d28c3d67582799c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/7d413660f66643638984a728c325ba28/cancellations/fe55ea5a63db4c43b87622b4cfb7ad15
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2018-09-21T05:28:16.019626+03:00", 
    "cancellationOf": "tender", 
    "id": "fe55ea5a63db4c43b87622b4cfb7ad15"
  }
}

