PATCH /api/2.5/tenders/e98f6645e699429dbd9f81a745a81784?acc_token=82ddff8fd558479b8e88233ab22c8691 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 57
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "guarantee": {
      "currency": "USD", 
      "amount": 8
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "auctionPeriod": {
      "shouldStartAfter": "2019-04-03T00:00:00+02:00"
    }, 
    "awardCriteria": "lowestCost", 
    "tenderPeriod": {
      "startDate": "2019-03-18T09:28:03.504448+02:00", 
      "endDate": "2019-04-02T09:28:13.552926+02:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-07T09:26:16.575809+02:00", 
          "endDate": "2019-05-07T09:26:16.575892+02:00"
        }, 
        "id": "1e0f9a227ca94601baf52a2b88863e75", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-03-18T09:28:03.504448+02:00", 
      "endDate": "2019-03-29T00:00:00+03:00"
    }, 
    "procurementMethodType": "aboveThresholdUA", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2019-03-18T09:28:03.519268+02:00", 
    "next_check": "2019-04-02T10:28:13.552926+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name": "Куца Світлана Валентинівна", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name": "ЗОСШ #10 м.Вінниці", 
      "kind": "special", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "enquiryPeriod": {
      "startDate": "2019-03-18T09:28:03.504448+02:00", 
      "clarificationsUntil": "2019-03-28T00:00:00+02:00", 
      "endDate": "2019-03-23T09:28:13.552926+02:00", 
      "invalidationDate": "2019-03-18T09:28:03.632454+02:00"
    }, 
    "owner": "broker", 
    "dateModified": "2019-03-18T09:28:03.634028+02:00", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "id": "e98f6645e699429dbd9f81a745a81784", 
    "tenderID": "UA-2019-03-18-000001"
  }
}

