PATCH /api/2.4/tenders/286e5a0cef9143858208497fd628fc24?acc_token=9547545aca8640c8bb7887b26b1e46b3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 57
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "guarantee": {
      "currency": "USD", 
      "amount": 8
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "auctionPeriod": {
      "shouldStartAfter": "2018-08-31T00:00:00+03:00"
    }, 
    "awardCriteria": "lowestCost", 
    "tenderPeriod": {
      "startDate": "2018-08-15T17:58:45.427608+03:00", 
      "endDate": "2018-08-30T17:58:55.684231+03:00"
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "description_en": "Cases for state awards", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-08-17T17:58:31.082579+03:00", 
          "endDate": "2018-08-20T17:58:31.082579+03:00"
        }, 
        "id": "3c303fdd8e6440b798989a96860c5c73", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-08-15T17:58:45.427608+03:00", 
      "endDate": "2018-08-26T00:00:00+03:00"
    }, 
    "procurementMethodType": "aboveThresholdUA", 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "date": "2018-08-15T17:58:45.530889+03:00", 
    "next_check": "2018-08-30T17:58:55.684231+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "enquiryPeriod": {
      "startDate": "2018-08-15T17:58:45.427608+03:00", 
      "clarificationsUntil": "2018-08-23T17:58:55.684231+03:00", 
      "endDate": "2018-08-20T17:58:55.684231+03:00", 
      "invalidationDate": "2018-08-15T17:58:45.892209+03:00"
    }, 
    "owner": "broker", 
    "dateModified": "2018-08-15T17:58:45.893930+03:00", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "id": "286e5a0cef9143858208497fd628fc24", 
    "tenderID": "UA-2018-08-15-000001"
  }
}

