GET /api/2.5/tenders/425a24b7b03d49759b19d37ac7e51561/contracts/3efe5c5edf2c40e39afa62819acb9ba4?acc_token=9339c9eca13f47388862c5e3b8cb3d23 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "title": "contract_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/425a24b7b03d49759b19d37ac7e51561/contracts/3efe5c5edf2c40e39afa62819acb9ba4/documents/2d5eef76ff0441a8b729cbad4d29a1e8?download=3a8ec234a0cf470bb0c893ca8a23d1cb", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:50:15.088092+02:00", 
        "id": "2d5eef76ff0441a8b729cbad4d29a1e8", 
        "dateModified": "2019-03-28T06:50:15.088114+02:00"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-17T06:47:08.962424+02:00", 
          "endDate": "2019-05-17T06:47:08.962464+02:00"
        }, 
        "id": "55c10c6897b8430bbed91d63761a9ce7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2019-03-28T06:50:14.951178+02:00", 
      "endDate": "2020-03-27T06:50:14.951206+02:00"
    }, 
    "dateSigned": "2019-03-28T06:50:14.851540+02:00", 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "amountNet": 230.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-28T06:50:14.637004+02:00", 
    "awardID": "ce51a7a410124584ad0d3a05fdfb68e4", 
    "id": "3efe5c5edf2c40e39afa62819acb9ba4", 
    "contractID": "UA-2019-03-28-000001-1"
  }
}

