GET /api/2.5/tenders/92f0a69805904e71be9e717fad623af5/documents?acc_token=a7b6575bd2064c97b965ea003187c336 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a1e0c4515d9d403b861045d2e0ac6a54?KeyID=a8968c46&Signature=jL%2FHesjUiuaQrTawAPXaS0AiaPj%2FhZHsgOaxFzrCXbjjrJZFplNUKcHrNo12vmr2XlLng1iuCYY18CmyZqyyBQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "59bb4288a60f42a2bf54d77d51f4a321", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/fb4560982c8d4cf582479699751da52b?KeyID=a8968c46&Signature=gxBAX3kunb9Ajo5UUO5pAOM3Ohbn%2Fjg8OLfwbUYnH6Zwhk4Hx1MWLl8Ek%252BLfL0m3GPwJcbqzdft4OAwzP2IIAA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-04-01T01:00:00+03:00", 
      "id": "3698b0dee82a45e7b52f17508dbf6248", 
      "dateModified": "2019-04-01T01:00:00+03:00"
    }
  ]
}

