GET /api/2.4/tenders/e925b9a969c14e6e91dc2236fb288798/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "author": "tender_owner", 
      "title": "Notice.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/e925b9a969c14e6e91dc2236fb288798/documents/69a1c55e7e3c49f5941b4838b90bf4e9?download=e2c3826b90064bd488205cf7ebd8d036", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-08-15T17:58:55.949710+03:00", 
      "id": "69a1c55e7e3c49f5941b4838b90bf4e9", 
      "dateModified": "2018-08-15T17:58:55.949732+03:00"
    }, 
    {
      "author": "tender_owner", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/e925b9a969c14e6e91dc2236fb288798/documents/5427fc3cb6ae4f1393cefdfbb3bac98f?download=704ce2f92abd4e8a95e96caf8d91eeef", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-08-15T17:58:56.087768+03:00", 
      "id": "5427fc3cb6ae4f1393cefdfbb3bac98f", 
      "dateModified": "2018-08-15T17:58:56.223267+03:00"
    }
  ]
}

