GET /api/2.5/tenders/fd3bff85b6cf4847a886943870d4ed9d/documents/aaf144a47d704dd3813cff2b82488da7?acc_token=6d2e380f62774b8185d05caad8151221 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d6a28f4188fd425bb220b65964ccd64a?KeyID=ac787512&Signature=ltPgSROCzCwwoqU%252BIvxW6ZBf9eSViWyDTDLlWa6ys5VoVL8UvS4nGBupKMozSe%252BM5vqklG3l%2FTNJklNmFr6nDA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "previousVersions": [], 
    "id": "aaf144a47d704dd3813cff2b82488da7", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

