PATCH /api/2.4/tenders/22e87e1eab6c4c7aac50c27b4f7ea426/contracts/1c6d41a8804747c28183fec03b372e76?acc_token=dc4b67578f404c6594c38bd2b8a77daf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 118
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "period": {
      "startDate": "2018-08-15T10:51:42.419885+03:00", 
      "endDate": "2019-08-15T10:51:42.419921+03:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-04T10:51:24.884191+03:00", 
          "endDate": "2018-10-04T10:51:24.884232+03:00"
        }, 
        "id": "17cd4064a081473faba712b32f5fe0f5", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2018-08-15T10:51:42.419885+03:00", 
      "endDate": "2019-08-15T10:51:42.419921+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2018-08-15T10:51:42.285744+03:00", 
    "awardID": "225604e0daf84ab4b76041e2e5478e2a", 
    "id": "1c6d41a8804747c28183fec03b372e76", 
    "contractID": "UA-2018-08-15-000001-1"
  }
}

