GET /api/2.5/tenders/fd3bff85b6cf4847a886943870d4ed9d/documents?acc_token=6d2e380f62774b8185d05caad8151221 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e3f3e943f8924abda47140dc695aabf9?KeyID=ac787512&Signature=AG%252BZA66zmCqPSoIVsvF4ieXdUMZYgXgb8hp4MiVRwl83sBZ0ZUB10D1ROM8D7dh1bW2RDasfaZMaKKssmwgoCA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-01-01T00:00:00+02:00", 
      "id": "96fa8e440c2b4abeafae6e6b3b5a0780", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d6a28f4188fd425bb220b65964ccd64a?KeyID=ac787512&Signature=ltPgSROCzCwwoqU%252BIvxW6ZBf9eSViWyDTDLlWa6ys5VoVL8UvS4nGBupKMozSe%252BM5vqklG3l%2FTNJklNmFr6nDA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-01-01T00:00:00+02:00", 
      "id": "aaf144a47d704dd3813cff2b82488da7", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }
  ]
}

