GET /api/2.4/tenders/6ade0a2779c442fb8ebc0f7e8867eec0/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "author": "tender_owner", 
      "title": "Notice.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/6ade0a2779c442fb8ebc0f7e8867eec0/documents/c160e53c9c784526979f468379c949ef?download=c268a087e7ed4eddb5edc73bc5fa8234", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-02-06T06:11:49.008171+02:00", 
      "id": "c160e53c9c784526979f468379c949ef", 
      "dateModified": "2019-02-06T06:11:49.008185+02:00"
    }, 
    {
      "author": "tender_owner", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/6ade0a2779c442fb8ebc0f7e8867eec0/documents/93678a35b8eb4b489893f40ba888c0de?download=84ef577f37b844f5b80d044aa1fa152f", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-02-06T06:11:49.045505+02:00", 
      "id": "93678a35b8eb4b489893f40ba888c0de", 
      "dateModified": "2019-02-06T06:11:49.083967+02:00"
    }
  ]
}

