GET /api/2.5/tenders/e98f6645e699429dbd9f81a745a81784/documents?acc_token=82ddff8fd558479b8e88233ab22c8691 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "author": "tender_owner", 
      "title": "Notice.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/e98f6645e699429dbd9f81a745a81784/documents/a98b546ceae94a298b380c1df3867a4c?download=e85abfa793bc42459b7fb8f725989af7", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-03-18T09:28:03.659682+02:00", 
      "id": "a98b546ceae94a298b380c1df3867a4c", 
      "dateModified": "2019-03-18T09:28:03.659697+02:00"
    }, 
    {
      "author": "tender_owner", 
      "title": "AwardCriteria.pdf", 
      "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/e98f6645e699429dbd9f81a745a81784/documents/94642363abcc4830aef19a882a7b6165?download=73291e43c7014ed596f7fdb2f797bc5c", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-03-18T09:28:03.697956+02:00", 
      "id": "94642363abcc4830aef19a882a7b6165", 
      "dateModified": "2019-03-18T09:28:03.697970+02:00"
    }
  ]
}

