PATCH /api/2.5/tenders/44aafce4c8b3419388f00517b05142c0/cancellations/bb5241cccd6e4ee9b49b3a04ec8f7655?acc_token=102c2b5517b74546859baa840a337113 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-04-01T01:10:00+03:00", 
    "cancellationOf": "tender", 
    "id": "bb5241cccd6e4ee9b49b3a04ec8f7655"
  }
}

