PATCH /api/2.5/tenders/92f0a69805904e71be9e717fad623af5/cancellations/b8dd02c4d0e347669b146cb7344f625c?acc_token=a7b6575bd2064c97b965ea003187c336 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-01-01T00:10:00+02:00", 
    "cancellationOf": "tender", 
    "id": "b8dd02c4d0e347669b146cb7344f625c"
  }
}

