PUT /api/2.5/tenders/44aafce4c8b3419388f00517b05142c0/cancellations/bb5241cccd6e4ee9b49b3a04ec8f7655/documents/46a8d807a9394e9fb6ae0a1e5e145a9a?acc_token=102c2b5517b74546859baa840a337113 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 139
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Notice-2.pdf"
Content-Type: application/pdf

content2
--BOUNDARY--


Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "title": "Notice-2.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c8691062eb714da4bbaeed3a2cc0c691?KeyID=a8968c46&Signature=bL4m%2FssDTxl8X9y0taH3mDvbGJ6LaH5LA0fu0E%2FaGDPMcBAsTnFgbm3%252BHCO5Pn4nwA89eCfSRPODdht1lPvTBQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:10:00+03:00", 
    "id": "46a8d807a9394e9fb6ae0a1e5e145a9a", 
    "dateModified": "2019-04-01T01:10:00+03:00"
  }
}

