PATCH /api/2.5/tenders/92f0a69805904e71be9e717fad623af5?acc_token=a7b6575bd2064c97b965ea003187c336 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 38
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "value": {
      "amount": 501.0
    }
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "tenderPeriod should be extended by 7 days", 
      "location": "body", 
      "name": "data"
    }
  ]
}

