PUT /api/2.5/tenders/44aafce4c8b3419388f00517b05142c0/documents/e132f63e55ca4540b437472696cd39d7?acc_token=102c2b5517b74546859baa840a337113 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 146
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="AwardCriteria-2.pdf"
Content-Type: application/pdf

content2
--BOUNDARY--


Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1d1f1de489d94ce89a5c6329e9d65347?KeyID=a8968c46&Signature=yk0RZj7ZEAj7Z3lDxz09C2odO%252B7aVMKu37%2FxROTL7b%2Fenl9ZEouGC71EB4iYfawWBMHkoDXleUyS3cHTL%2FLTDA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "e132f63e55ca4540b437472696cd39d7", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

