PATCH /api/2.4/tenders/286e5a0cef9143858208497fd628fc24/cancellations/86b7d932ad694b24931da6a25bc586bb?acc_token=9547545aca8640c8bb7887b26b1e46b3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2018-08-15T17:58:49.969692+03:00", 
    "cancellationOf": "tender", 
    "id": "86b7d932ad694b24931da6a25bc586bb"
  }
}

