POST /api/2.4/tenders/286e5a0cef9143858208497fd628fc24/documents?acc_token=9547545aca8640c8bb7887b26b1e46b3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 191
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy83516429538$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/286e5a0cef9143858208497fd628fc24/documents/613f35a16bad46fd9468eb553a6a612d
{
  "data": {
    "author": "tender_owner", 
    "title": "AwardCriteria.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/286e5a0cef9143858208497fd628fc24/documents/613f35a16bad46fd9468eb553a6a612d?download=b44287c9e02b4160a88cfd1a4b7b77b6", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-15T17:58:46.097923+03:00", 
    "id": "613f35a16bad46fd9468eb553a6a612d", 
    "dateModified": "2018-08-15T17:58:46.097945+03:00"
  }
}

