POST /api/2.5/tenders/92f0a69805904e71be9e717fad623af5/documents?acc_token=a7b6575bd2064c97b965ea003187c336 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 188
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy0211683743787$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/92f0a69805904e71be9e717fad623af5/documents/59bb4288a60f42a2bf54d77d51f4a321
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c6a2afca9f234ec88ca4acdfa52b6595?KeyID=a8968c46&Signature=xEfXLG2Dqr2eb%252BYnx8tm3KxIgJ4TofqycfmdRC%252BJEW8NvWzKJ13quvah6odczdjy6Be2Fs7aSaqgPWc2d9gQBQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "59bb4288a60f42a2bf54d77d51f4a321", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

