POST /api/2.5/tenders/92f0a69805904e71be9e717fad623af5/cancellations/b8dd02c4d0e347669b146cb7344f625c/documents?acc_token=a7b6575bd2064c97b965ea003187c336 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 136
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Notice.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/92f0a69805904e71be9e717fad623af5/cancellations/b8dd02c4d0e347669b146cb7344f625c/documents/047cb43ee1c14f5e93645a882db02382
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/616e8987c71741e39cc50c70074d1e59?KeyID=a8968c46&Signature=OVIMgeOVBbOH8np4i%2F2s1do%252BjFM87XXrOtFQ0jReEZ%2FHAbs0aa67lq96f6jPGw9AN8F2WJXkNDeBNiI%252BhtA6Bw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:10:00+03:00", 
    "id": "047cb43ee1c14f5e93645a882db02382", 
    "dateModified": "2019-04-01T01:10:00+03:00"
  }
}

