POST /api/2.4/tenders/e925b9a969c14e6e91dc2236fb288798/documents?acc_token=da27ac85a9134c97b2ae4cc678001521 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy227609932543$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/e925b9a969c14e6e91dc2236fb288798/documents/69a1c55e7e3c49f5941b4838b90bf4e9
{
  "data": {
    "author": "tender_owner", 
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/e925b9a969c14e6e91dc2236fb288798/documents/69a1c55e7e3c49f5941b4838b90bf4e9?download=e2c3826b90064bd488205cf7ebd8d036", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-15T17:58:55.949710+03:00", 
    "id": "69a1c55e7e3c49f5941b4838b90bf4e9", 
    "dateModified": "2018-08-15T17:58:55.949732+03:00"
  }
}

