POST /api/2.5/tenders/44aafce4c8b3419388f00517b05142c0/cancellations/bb5241cccd6e4ee9b49b3a04ec8f7655/documents?acc_token=102c2b5517b74546859baa840a337113 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 136
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Notice.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/44aafce4c8b3419388f00517b05142c0/cancellations/bb5241cccd6e4ee9b49b3a04ec8f7655/documents/46a8d807a9394e9fb6ae0a1e5e145a9a
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3d71d073fc6b4950b28037b8b6b1863b?KeyID=a8968c46&Signature=6td4YcGQAOhg4mLERUISs0LJ0g4LKiGV2EitK9XamycdMjKfPrVWbYwcUN7GerM1XD6n7fXZS%252BV5pEmJy0%252B1Aw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:10:00+03:00", 
    "id": "46a8d807a9394e9fb6ae0a1e5e145a9a", 
    "dateModified": "2019-04-01T01:10:00+03:00"
  }
}

