POST /api/2.5/transfers HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 12
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {}
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
{
  "access": {
    "transfer": "b492d6fd4a1c4d05ab46c8db0e21f206", 
    "token": "4bc49849ef09435ab3e61eccfb1115af"
  }, 
  "data": {
    "date": "2019-04-01T01:00:01+03:00", 
    "id": "e910d1255a0a5dcdaabbee9f0f4e0961"
  }
}

