POST /api/2.5/transfers HTTP/1.0
Authorization: Basic YnJva2VyMzo=
Content-Length: 12
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {}
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
{
  "access": {
    "transfer": "29a6c5df28d64fdca14efd62569851f2", 
    "token": "a113e876a3714f07a19248928aff7deb"
  }, 
  "data": {
    "date": "2019-04-01T01:00:01+03:00", 
    "id": "a6db879380f3435aa87db64038a5a1f3"
  }
}

