POST /api/2.5/transfers HTTP/1.0
Authorization: Basic YnJva2VyMTo=
Content-Length: 12
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {}
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
{
  "access": {
    "transfer": "8d950b913f2948fc9ba1bc2f08c8b8dc", 
    "token": "7035908e26f04e4dba9300b2ac73baa6"
  }, 
  "data": {
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "9bd9ded8ee1a1b68b2c227ebab0a7945"
  }
}

