GET /api/2.5/transfers/e910d1255a0a5dcdaabbee9f0f4e0961 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "date": "2019-04-01T01:00:01+03:00", 
    "id": "e910d1255a0a5dcdaabbee9f0f4e0961", 
    "usedFor": "/tenders/9fc052c7d8c94d93abebd1c68246f240/complaints/d533dbd0327c4b29983a479a778872d6"
  }
}

