GET /api/2.5/transfers/9bd9ded8ee1a1b68b2c227ebab0a7945 HTTP/1.0
Authorization: Basic YnJva2VyMTo=
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "9bd9ded8ee1a1b68b2c227ebab0a7945"
  }
}

