GET /api/2.5/transfers/e910d1255a0a5dcdaabbee9f0f4e07dd HTTP/1.0
Authorization: Basic YnJva2VyMTo=
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "e910d1255a0a5dcdaabbee9f0f4e07dd", 
    "usedFor": "/tenders/9fc052c7d8c94d93abebd1c68246f240"
  }
}

