POST /api/2.4/tenders/a7e6332ad01341cca08e5560a337c884/awards/bda17a262d254d6bb9c6e78c3d221aec/documents?acc_token=77270018915e44c0825a54ecc6cc89dc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 341
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/704cb366c28749faa00d667085b125d9?KeyID=d0d2cc30&Signature=gjRx7Mye2ULpOgx3sIPQXRs%2FoYZHSLc8ME5vhl3gLeu%2FJv7ZxZHjJM6mt844ra3FUPtLUTOZZk6yBEZwEjf%2FBA%3D%3D", 
    "title": "Unsuccessful_Reason.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/a7e6332ad01341cca08e5560a337c884/awards/bda17a262d254d6bb9c6e78c3d221aec/documents/028f2f9e5f89408e958aa94b6e935ee0

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Unsuccessful_Reason.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/704cb366c28749faa00d667085b125d9?KeyID=d0d2cc30&Signature=biSk0h1YkH43MDxXsweGsf4bzWCyRWmOGBG8miFpfH8nBxZXiJb0IMC%2Fh4sTGpDrOaefRUjN3FeNchAFqJ7XAQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-14T18:53:00.888798+03:00", 
    "id": "028f2f9e5f89408e958aa94b6e935ee0", 
    "dateModified": "2018-08-14T18:53:00.888819+03:00"
  }
}

