PATCH /api/2.4/tenders/811652d707394b568daf079e30ca0192/awards/c47bf1bde752415c974c2d0eb9fb9344?acc_token=19a08594e4c14b54b8abcf0f6005bb7c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2019-02-06T06:09:45.188347+02:00", 
      "endDate": "2019-02-08T06:09:45.291546+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "scale": "micro", 
        "name": "Державне управління справами", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "60e3913480144d9599739a06c60dc6fe", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-02-06T06:09:45.297397+02:00", 
    "id": "c47bf1bde752415c974c2d0eb9fb9344"
  }
}

