POST /api/2.5/tenders/4bdc8f70ca4d45b0956ab3afbadcc50c/awards/966567aa3e264025974df64bc7e5a66c/documents?acc_token=b9d491f8ba8643bd9cddd249d67610d3 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 341
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/8c9b7659984a4af3ad4b14b417d718dd?KeyID=ddecca24&Signature=d1C4JwiKBdXaVcw5EN%2BA3lxsH2lkjds860nGTK8lMYPPzUbmkXWjisL%2FEUbhhvnVIBUKRqRJA8kv5BV%2BDHqVAg%3D%3D", 
    "title": "Cancellation_Reason.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/4bdc8f70ca4d45b0956ab3afbadcc50c/awards/966567aa3e264025974df64bc7e5a66c/documents/ee8800da939a41509c38efc84517cd64

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Cancellation_Reason.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/8c9b7659984a4af3ad4b14b417d718dd?KeyID=ddecca24&Signature=88jUcVqVYqmANH3hBYOQ8rJmjAT0P82usaqZN1l3H6gp770%252Bm9zb5xBwIU8aSObdhSAB3M1fx0OJQGLhPwPOCQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-28T06:47:15.526072+02:00", 
    "id": "ee8800da939a41509c38efc84517cd64", 
    "dateModified": "2019-03-28T06:47:15.526090+02:00"
  }
}

