GET /api/2.4/tenders/5723be5db56f4853b0a5f6ae6153b82f/awards/bcd3c59a3a0a406cb9b8a49958881bd0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2018-09-21T05:23:05.690524+03:00", 
      "endDate": "2018-09-25T05:23:06.047878+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "94f2ddc6015742a0ab24475f81a90f2b", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-09-21T05:23:06.061569+03:00", 
    "id": "bcd3c59a3a0a406cb9b8a49958881bd0"
  }
}

