PATCH /api/2.5/tenders/16a0247dd30047b490e2890ebc1530ff/awards/a83c789e3961471aba2da545a53b46cc?acc_token=f560f2cda61e4b3da9798551bd6700ae HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/16a0247dd30047b490e2890ebc1530ff/awards/63d5700ab1004d588bedd94530f1d492

{
  "data": {
    "status": "cancelled", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Unsuccessful_Reason.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/a4d79bf0a41848ecb67ae2d35cecefe2?KeyID=eb72328f&Signature=0mOwJxbymxc314UKtG%2F3VbZFWi0Dm4Hs1Y5kgNDVExs1HjOn6C7PnlJb1iBUZjAXGnKIVUxraF1ImsXpgdxJBQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:22.111148+02:00", 
        "id": "20d9dc8191b74e80ac3419b152f3aef4", 
        "dateModified": "2019-03-18T09:26:22.111161+02:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-03-18T09:26:22.007642+02:00", 
      "endDate": "2019-03-18T09:26:24.959399+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "eb42352531ab424d983fa1e9865ddc15", 
    "value": {
      "currency": "UAH", 
      "amount": 450.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-18T09:26:24.968593+02:00", 
    "complaints": [
      {
        "status": "resolved", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "complaint_owner", 
            "title": "Complaint_Attachement.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/cdcf99dc852f400a93853b8e65523c4c?KeyID=eb72328f&Signature=6nE6zFMdgewB%2FHjdZihsw1AtOIlffC%252B4mrJrVnj2O4yqhoNnpTkEHxvW7NIGrefh3xMdfgzCfRgvwEKk45K2Ag%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-03-18T09:26:23.001433+02:00", 
            "id": "af1a86d3ee0443f8964c244cf706ceb2", 
            "dateModified": "2019-03-18T09:26:23.001446+02:00"
          }
        ], 
        "description": "complaint description", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "complaint title", 
        "satisfied": true, 
        "tendererAction": "Виправлено неконкурентні умови", 
        "dateAnswered": "2019-03-18T09:26:23.462896+02:00", 
        "tendererActionDate": "2019-03-18T09:26:23.462915+02:00", 
        "dateSubmitted": "2019-03-18T09:26:23.122274+02:00", 
        "complaintID": "UA-2019-03-18-000001.5", 
        "date": "2019-03-18T09:26:23.593920+02:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "ae25373d3ed443979c8ccf1279e74c51"
      }, 
      {
        "status": "resolved", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2019-03-18T09:26:23.715556+02:00", 
        "dateSubmitted": "2019-03-18T09:26:23.238624+02:00", 
        "complaintID": "UA-2019-03-18-000001.6", 
        "date": "2019-03-18T09:26:23.854609+02:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "4d640a8a0b434905a20bec5078ba3b42"
      }, 
      {
        "status": "resolved", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2019-03-18T09:26:24.126794+02:00", 
        "dateSubmitted": "2019-03-18T09:26:23.990218+02:00", 
        "complaintID": "UA-2019-03-18-000001.7", 
        "date": "2019-03-18T09:26:24.264550+02:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "a2c17a00808d4dc395978913efd2f76e"
      }, 
      {
        "status": "resolved", 
        "description": "complaint description", 
        "title": "complaint title", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2019-03-18T09:26:24.529903+02:00", 
        "dateSubmitted": "2019-03-18T09:26:24.385099+02:00", 
        "complaintID": "UA-2019-03-18-000001.8", 
        "date": "2019-03-18T09:26:24.696833+02:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "4185dc7df31a4c8db41eec73093dc482"
      }
    ], 
    "id": "a83c789e3961471aba2da545a53b46cc"
  }
}

