GET /api/2.5/tenders/4bdc8f70ca4d45b0956ab3afbadcc50c/awards/c8e8b73e12144aa7b491c03c608b30ac HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2019-03-28T06:47:15.058266+02:00", 
      "endDate": "2019-04-01T06:47:15.179897+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "94aa36e83bb74c96a6009f27ab9c73cc", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-28T06:47:15.186025+02:00", 
    "id": "c8e8b73e12144aa7b491c03c608b30ac"
  }
}

