GET /api/2.4/tenders/94e7af37e39840cd925a424cda8e0bb8/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Unsuccessful_Reason.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/d6e196ffb5eb4149817bb81fd1571aeb?KeyID=82a13eea&Signature=ekXoklb4iLI1S0ClwYzfcJSuFG2sQvaMroetpXFzDAlKr7qShQi%252BFWfHceocCuffFcahgixk%2FZr80i3NxU3CAA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-14T19:03:50.754143+03:00", 
          "id": "b126ed071f3c4fcc9b5cd29970c1b242", 
          "dateModified": "2018-08-14T19:03:50.754165+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-08-14T19:03:50.557413+03:00", 
        "endDate": "2018-08-14T19:03:54.832479+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "e3d8623cf13d48a9b1e7a7e855bf7ea1", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-14T19:03:54.842438+03:00", 
      "complaints": [
        {
          "status": "resolved", 
          "documents": [
            {
              "hash": "md5:00000000000000000000000000000000", 
              "author": "complaint_owner", 
              "title": "Complaint_Attachement.pdf", 
              "url": "http://public.docs-sandbox.openprocurement.org/get/a042714d76674da69aa716ffaf6c2c69?KeyID=82a13eea&Signature=CtMyGs4lHurOukazbsCXP0CsFz7kkavvC9jveWPKhxhn58VIGTrVnwMlq9Ms%2Fro14atTblry9cZA3EZPrtDQDQ%253D%253D", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2018-08-14T19:03:52.099487+03:00", 
              "id": "d8003e51d76e47ac8257720b5dcbd121", 
              "dateModified": "2018-08-14T19:03:52.099506+03:00"
            }
          ], 
          "description": "complaint description", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "complaint title", 
          "satisfied": true, 
          "tendererAction": "Виправлено неконкурентні умови", 
          "dateAnswered": "2018-08-14T19:03:52.805905+03:00", 
          "tendererActionDate": "2018-08-14T19:03:52.805922+03:00", 
          "dateSubmitted": "2018-08-14T19:03:52.278956+03:00", 
          "complaintID": "UA-2018-08-14-000001.5", 
          "date": "2018-08-14T19:03:52.996943+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "67af09683670413a89de3f5f28a3a08b"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-14T19:03:53.171119+03:00", 
          "dateSubmitted": "2018-08-14T19:03:52.448610+03:00", 
          "complaintID": "UA-2018-08-14-000001.6", 
          "date": "2018-08-14T19:03:53.357924+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "70d0b980071c49d7ad2d8292c74ef13b"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-14T19:03:53.721283+03:00", 
          "dateSubmitted": "2018-08-14T19:03:53.534176+03:00", 
          "complaintID": "UA-2018-08-14-000001.7", 
          "date": "2018-08-14T19:03:53.920690+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "20ca46d18df2448faff3944ab088df84"
        }, 
        {
          "status": "resolved", 
          "description": "complaint description", 
          "title": "complaint title", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2018-08-14T19:03:54.296406+03:00", 
          "dateSubmitted": "2018-08-14T19:03:54.102938+03:00", 
          "complaintID": "UA-2018-08-14-000001.8", 
          "date": "2018-08-14T19:03:54.504190+03:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "bc475a84988842a1ad6b427355a59f11"
        }
      ], 
      "id": "2b3ab88ca505453b8c3eb546d850c4d6"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2018-08-14T19:03:50.928661+03:00", 
        "endDate": "2018-08-14T19:03:54.832479+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "53f050c894fb42a4a7b8e307e0b4027d", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-14T19:03:51.380712+03:00", 
      "id": "ea24e2437ba148ac98d8398b863fc301"
    }, 
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Cancellation_Reason.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/394302adfa7f4affb1db4d242fe30694?KeyID=82a13eea&Signature=XT4fUecbieCJBT3Csl8inyBTvNyaeJIW7%252BR5fIzisYhViXMsrNYIUrStE%2FQl2J7fOfFFaHgH4%252B%252B1JwVpIWV7BQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-08-14T19:03:51.604069+03:00", 
          "id": "9835b4fb8b3b4efcbd83b4788b67dd87", 
          "dateModified": "2018-08-14T19:03:51.604088+03:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-08-14T19:03:51.372904+03:00", 
        "endDate": "2018-08-14T19:03:54.832479+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "53f050c894fb42a4a7b8e307e0b4027d", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-14T19:03:54.842438+03:00", 
      "id": "88ebfa52bf2842499720f2b8166b707b"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2018-08-14T19:03:51.769278+03:00", 
        "endDate": "2018-08-14T19:03:54.832479+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "ebea097e696c45c29d16c05a18b454b3", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-14T19:03:54.842438+03:00", 
      "id": "8ac5c3147cde42c0a0ba432c315ea937"
    }, 
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2018-08-14T19:03:54.833022+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "e3d8623cf13d48a9b1e7a7e855bf7ea1", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-08-14T19:03:54.833011+03:00", 
      "id": "6b17c31e1b3248aa868cb346a4745d20"
    }
  ]
}

