POST /api/2.4/tenders/94e7af37e39840cd925a424cda8e0bb8/awards/2b3ab88ca505453b8c3eb546d850c4d6/documents?acc_token=8dc92a1473fd4ed68d2e01a8926c1365 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 341
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.openprocurement.org/get/d6e196ffb5eb4149817bb81fd1571aeb?KeyID=82a13eea&Signature=ZrTi3WOA8AqGfJAm%2BdZ8w%2BPjvKsnefaIsjxtTa6ELHtEHLDaJBI0ZkC74LyeIHRBTYI8%2F6Zq67Bz6ozC1UCKBg%3D%3D", 
    "title": "Unsuccessful_Reason.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/94e7af37e39840cd925a424cda8e0bb8/awards/2b3ab88ca505453b8c3eb546d850c4d6/documents/b126ed071f3c4fcc9b5cd29970c1b242

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "title": "Unsuccessful_Reason.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/d6e196ffb5eb4149817bb81fd1571aeb?KeyID=82a13eea&Signature=ekXoklb4iLI1S0ClwYzfcJSuFG2sQvaMroetpXFzDAlKr7qShQi%252BFWfHceocCuffFcahgixk%2FZr80i3NxU3CAA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-08-14T19:03:50.754143+03:00", 
    "id": "b126ed071f3c4fcc9b5cd29970c1b242", 
    "dateModified": "2018-08-14T19:03:50.754165+03:00"
  }
}

