PATCH /api/2.4/tenders/94e7af37e39840cd925a424cda8e0bb8/awards/88ebfa52bf2842499720f2b8166b707b?acc_token=8dc92a1473fd4ed68d2e01a8926c1365 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/94e7af37e39840cd925a424cda8e0bb8/awards/8ac5c3147cde42c0a0ba432c315ea937

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Cancellation_Reason.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/394302adfa7f4affb1db4d242fe30694?KeyID=82a13eea&Signature=XT4fUecbieCJBT3Csl8inyBTvNyaeJIW7%252BR5fIzisYhViXMsrNYIUrStE%2FQl2J7fOfFFaHgH4%252B%252B1JwVpIWV7BQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-08-14T19:03:51.604069+03:00", 
        "id": "9835b4fb8b3b4efcbd83b4788b67dd87", 
        "dateModified": "2018-08-14T19:03:51.604088+03:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2018-08-14T19:03:51.372904+03:00", 
      "endDate": "2018-08-16T19:03:51.768805+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "53f050c894fb42a4a7b8e307e0b4027d", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-14T19:03:51.777459+03:00", 
    "id": "88ebfa52bf2842499720f2b8166b707b"
  }
}

