GET /api/2.5/tenders/8f11f82d19b64b859827cc941fd7f839/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Unsuccessful_Reason.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7a47460395a64c238b4b75f9de2eb455?KeyID=a0b3a3fd&Signature=WEORK2UtDqy4vDyXFgCNyXt7VSDAH%252B%2FiSEiF%2F1hK4rPitpthZ6elYTQ9X20RTBAofvBfITxf41kMWXttXGIyAg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-01-01T00:00:00+02:00", 
          "id": "feb49b3dfa38456bb45fdb66e013412a", 
          "dateModified": "2019-01-01T00:00:00+02:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2019-01-01T00:00:00+02:00", 
        "endDate": "2019-01-01T00:10:00+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "e0538ea0ef0d4ec8ad7ffdb6c380dd58", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2019-01-01T00:10:00+02:00", 
      "complaints": [
        {
          "status": "resolved", 
          "documents": [
            {
              "hash": "md5:00000000000000000000000000000000", 
              "author": "complaint_owner", 
              "title": "Complaint_Attachement.pdf", 
              "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3cec94f61e6646d0afc3e00c0c83fa15?KeyID=a0b3a3fd&Signature=ZV85ZDeTPAUjPKT5xlnX%2F1LQoapRnDH7CiAotn8UTvD1SavbkHgxPpCTrgkIDI2ZTQ78b9sf2kH5jpVUg7ZXBg%253D%253D", 
              "format": "application/pdf", 
              "documentOf": "tender", 
              "datePublished": "2019-01-01T00:10:00+02:00", 
              "id": "3444ef6c99be465b8f698c7a43ba5b8e", 
              "dateModified": "2019-01-01T00:10:00+02:00"
            }
          ], 
          "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "resolutionType": "resolved", 
          "type": "claim", 
          "title": "Недостатньо інформації", 
          "satisfied": true, 
          "tendererAction": "Виправлено неконкурентні умови", 
          "dateAnswered": "2019-01-01T00:10:00+02:00", 
          "tendererActionDate": "2019-01-01T00:10:00+02:00", 
          "dateSubmitted": "2019-01-01T00:10:00+02:00", 
          "complaintID": "UA-2019-01-01-000001.5", 
          "date": "2019-01-01T00:10:00+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "4e28a045331943eb89c6be15c7a9f570"
        }, 
        {
          "status": "resolved", 
          "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
          "title": "Недостатньо інформації", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2019-01-01T00:10:00+02:00", 
          "dateSubmitted": "2019-01-01T00:10:00+02:00", 
          "complaintID": "UA-2019-01-01-000001.6", 
          "date": "2019-01-01T00:10:00+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "7c737a2238d844aea9756fee79b35ddd"
        }, 
        {
          "status": "resolved", 
          "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
          "title": "Недостатньо інформації", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2019-01-01T00:10:00+02:00", 
          "dateSubmitted": "2019-01-01T00:10:00+02:00", 
          "complaintID": "UA-2019-01-01-000001.7", 
          "date": "2019-01-01T00:10:00+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "9fa0707acf2046b49c1a63e317c48382"
        }, 
        {
          "status": "resolved", 
          "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
          "title": "Недостатньо інформації", 
          "resolutionType": "resolved", 
          "type": "claim", 
          "author": {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }, 
          "satisfied": false, 
          "dateAnswered": "2019-01-01T00:10:00+02:00", 
          "dateSubmitted": "2019-01-01T00:10:00+02:00", 
          "complaintID": "UA-2019-01-01-000001.8", 
          "date": "2019-01-01T00:10:00+02:00", 
          "resolution": "Виправлено неконкурентні умови", 
          "id": "fbbda3cdc1574c25843fc2c2a0d0053f"
        }
      ], 
      "id": "be28a579af2b47788dfb441328f844bc"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2019-01-01T00:00:00+02:00", 
        "endDate": "2019-01-01T00:10:00+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "ea83947de09d46209f02151bdc8bb94e", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2019-01-01T00:00:00+02:00", 
      "id": "7e555e05fab143f08714ceb8966afe38"
    }, 
    {
      "status": "cancelled", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "tender_owner", 
          "title": "Cancellation_Reason.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/193865a689684a39811efe697b975535?KeyID=a0b3a3fd&Signature=aonigjBKL5bhmsos7Azg1vMya2dApl%2Fzw879Jv10Y%2FJtY9CSskQ3Wj%252Bk5dqWil%252B8FjLOQOFoNJlG6oQyaB9JCg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-01-01T00:00:00+02:00", 
          "id": "b5b4e933e0d641cb8e56434ca6ac180a", 
          "dateModified": "2019-01-01T00:00:00+02:00"
        }
      ], 
      "complaintPeriod": {
        "startDate": "2019-01-01T00:00:00+02:00", 
        "endDate": "2019-01-01T00:10:00+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "name": "Державне управління справами", 
            "telephone": "0440000000"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00037256", 
            "uri": "http://www.dus.gov.ua/"
          }, 
          "name": "Державне управління справами", 
          "address": {
            "postalCode": "01220", 
            "countryName": "Україна", 
            "streetAddress": "вул. Банкова, 11, корпус 1", 
            "region": "м. Київ", 
            "locality": "м. Київ"
          }
        }
      ], 
      "bid_id": "ea83947de09d46209f02151bdc8bb94e", 
      "value": {
        "currency": "UAH", 
        "amount": 469.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2019-01-01T00:10:00+02:00", 
      "id": "ad8989e2987e4277a7e347fb51daa7e1"
    }, 
    {
      "status": "cancelled", 
      "complaintPeriod": {
        "startDate": "2019-01-01T00:00:00+02:00", 
        "endDate": "2019-01-01T00:10:00+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "9e15f02375a2430cb9ebaac1472a0e2b", 
      "value": {
        "currency": "UAH", 
        "amount": 475.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2019-01-01T00:10:00+02:00", 
      "id": "a8c6a46342e645919666b0e350bf2cde"
    }, 
    {
      "status": "pending", 
      "complaintPeriod": {
        "startDate": "2019-01-01T00:10:00+02:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "e0538ea0ef0d4ec8ad7ffdb6c380dd58", 
      "value": {
        "currency": "UAH", 
        "amount": 450.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2019-01-01T00:10:00+02:00", 
      "id": "70c52e3a116443fc8da473c9381c5287"
    }
  ]
}

