PATCH /api/2.5/tenders/40c17dbea3ba43fab389cc55c80183fc/awards/8cba908aedee4f7d90a81f67a2b69ad7?acc_token=74ec625f693841c0ad3e8bc4538041bc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/40c17dbea3ba43fab389cc55c80183fc/awards/7db363b58924421e9e2c06b7150b3cd4
{
  "data": {
    "status": "cancelled", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Unsuccessful_Reason.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3400b052972d4dc68a1e9ad72b458ae6?KeyID=a8968c46&Signature=K3x9TFR4sowV66e%252BhKyv32waBxCMyavtEBWOPr%252BBTPI4I%2FMA231OTHVylr%252BZbqYNGTcJM%2Fl6Sj3OEloysWwcBA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "4ac91ff67c3246f6b42650dd93895c5b", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-04-01T01:00:00+03:00", 
      "endDate": "2019-04-01T01:10:00+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "058beff354b44f24a1e4a44ab60f4801", 
    "value": {
      "currency": "UAH", 
      "amount": 450.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-04-01T01:10:00+03:00", 
    "complaints": [
      {
        "status": "resolved", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "complaint_owner", 
            "title": "Complaint_Attachement.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/16f633ca7b08404a9a9e9cc34e2d820f?KeyID=a8968c46&Signature=dGewQZC2Q04jTzp1fjaIIUWsSezX3jb5Q2w6Myq334%252BH8efVELc3%252BAHRisHwC9PWCVwPyOFc0KxBhEucqfGPCA%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:10:00+03:00", 
            "id": "3eb2c3216ee04affb60172f19887faed", 
            "dateModified": "2019-04-01T01:10:00+03:00"
          }
        ], 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "resolutionType": "resolved", 
        "type": "claim", 
        "title": "Недостатньо інформації", 
        "satisfied": true, 
        "tendererAction": "Виправлено неконкурентні умови", 
        "dateAnswered": "2019-04-01T01:10:00+03:00", 
        "tendererActionDate": "2019-04-01T01:10:00+03:00", 
        "dateSubmitted": "2019-04-01T01:10:00+03:00", 
        "complaintID": "UA-2019-04-01-000001.5", 
        "date": "2019-04-01T01:10:00+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "74bdfc3672d841d5a019cf8b36eef953"
      }, 
      {
        "status": "resolved", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2019-04-01T01:10:00+03:00", 
        "dateSubmitted": "2019-04-01T01:10:00+03:00", 
        "complaintID": "UA-2019-04-01-000001.6", 
        "date": "2019-04-01T01:10:00+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "cc6a802c0a7e4127b6de35401a843e24"
      }, 
      {
        "status": "resolved", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2019-04-01T01:10:00+03:00", 
        "dateSubmitted": "2019-04-01T01:10:00+03:00", 
        "complaintID": "UA-2019-04-01-000001.7", 
        "date": "2019-04-01T01:10:00+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "6bac2bdaabbc4460b94dba7624b32bb4"
      }, 
      {
        "status": "resolved", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "resolutionType": "resolved", 
        "type": "claim", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "satisfied": false, 
        "dateAnswered": "2019-04-01T01:10:00+03:00", 
        "dateSubmitted": "2019-04-01T01:10:00+03:00", 
        "complaintID": "UA-2019-04-01-000001.8", 
        "date": "2019-04-01T01:10:00+03:00", 
        "resolution": "Виправлено неконкурентні умови", 
        "id": "911a5c3081b14d64b94cc1ccd6d243df"
      }
    ], 
    "id": "8cba908aedee4f7d90a81f67a2b69ad7"
  }
}

