PATCH /api/2.5/tenders/40c17dbea3ba43fab389cc55c80183fc/awards/8cba908aedee4f7d90a81f67a2b69ad7?acc_token=74ec625f693841c0ad3e8bc4538041bc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/40c17dbea3ba43fab389cc55c80183fc/awards/6b0f4f603de4444e9e030620b26c3974
{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Unsuccessful_Reason.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/1bc0e3c6b6014da99c141450a723d3a1?KeyID=a8968c46&Signature=eLX2bLO%252BCh7Q3UBSzsDCJyyp58L5luiaQeMZow%2Fjof8b9yNG0fsIhWXWRzf26KfB4VdUtRnNb14xM%252BWvmSWyCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "4ac91ff67c3246f6b42650dd93895c5b", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-04-01T01:00:00+03:00", 
      "endDate": "2019-04-03T01:00:00+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "058beff354b44f24a1e4a44ab60f4801", 
    "value": {
      "currency": "UAH", 
      "amount": 450.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "8cba908aedee4f7d90a81f67a2b69ad7"
  }
}

