PATCH /api/2.5/tenders/16a0247dd30047b490e2890ebc1530ff/awards/a83c789e3961471aba2da545a53b46cc?acc_token=f560f2cda61e4b3da9798551bd6700ae HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "unsuccessful"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/16a0247dd30047b490e2890ebc1530ff/awards/8619ef73b6ef41f9b6539b4cd9678583

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Unsuccessful_Reason.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/a4d79bf0a41848ecb67ae2d35cecefe2?KeyID=eb72328f&Signature=0mOwJxbymxc314UKtG%2F3VbZFWi0Dm4Hs1Y5kgNDVExs1HjOn6C7PnlJb1iBUZjAXGnKIVUxraF1ImsXpgdxJBQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T09:26:22.111148+02:00", 
        "id": "20d9dc8191b74e80ac3419b152f3aef4", 
        "dateModified": "2019-03-18T09:26:22.111161+02:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-03-18T09:26:22.007642+02:00", 
      "endDate": "2019-03-20T09:26:22.216788+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "eb42352531ab424d983fa1e9865ddc15", 
    "value": {
      "currency": "UAH", 
      "amount": 450.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-18T09:26:22.222574+02:00", 
    "id": "a83c789e3961471aba2da545a53b46cc"
  }
}

