PATCH /api/2.5/tenders/8f11f82d19b64b859827cc941fd7f839/awards/ad8989e2987e4277a7e347fb51daa7e1?acc_token=7a12fff2b5f14f698f4c22ad8addc97e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/8f11f82d19b64b859827cc941fd7f839/awards/a8c6a46342e645919666b0e350bf2cde
{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "title": "Cancellation_Reason.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/193865a689684a39811efe697b975535?KeyID=a0b3a3fd&Signature=aonigjBKL5bhmsos7Azg1vMya2dApl%2Fzw879Jv10Y%2FJtY9CSskQ3Wj%252Bk5dqWil%252B8FjLOQOFoNJlG6oQyaB9JCg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "b5b4e933e0d641cb8e56434ca6ac180a", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-01-01T00:00:00+02:00", 
      "endDate": "2019-01-04T00:00:00+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "ea83947de09d46209f02151bdc8bb94e", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "ad8989e2987e4277a7e347fb51daa7e1"
  }
}

