PATCH /api/2.4/tenders/a7e6332ad01341cca08e5560a337c884/awards/91b2153644b94ef99466fe3a54ad076a?acc_token=77270018915e44c0825a54ecc6cc89dc HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2018-08-14T18:53:01.038787+03:00", 
      "endDate": "2018-08-16T18:53:01.274371+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "bid_id": "21f45bbb9c564a9090315ebf5735c20a", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-08-14T18:53:01.281009+03:00", 
    "id": "91b2153644b94ef99466fe3a54ad076a"
  }
}

