GET /api/2.5/tenders/d31f5c7085db4e08912359274057ea4d/bids/4a2d1aeb0f7f4519a6891437efead6ef?acc_token=4ef450f085ab4997935dd7b20e16807d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "4a2d1aeb0f7f4519a6891437efead6ef"
  }
}

