POST /api/2.4/tenders/f3bc07ebff534a04b13c6d3f0c02dd37/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1002
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "selfQualified": true, 
    "lotValues": [
      {
        "relatedLot": "1f77a97485ca4fb3bebeaf5802a8609b", 
        "value": {
          "amount": 500
        }, 
        "subcontractingDetails": "ДКП «Орфей», Україна"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк", 
          "email": "soleksuk@gmail.com"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "21100", 
          "region": "м. Вінниця", 
          "streetAddress": "вул. Островського, 33", 
          "locality": "м. Вінниця"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/f3bc07ebff534a04b13c6d3f0c02dd37/bids/6f69f4be052946f1acfcbc837fd6e65a
{
  "access": {
    "token": "b31755c006a64495adcddb09191e6139"
  }, 
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "1f77a97485ca4fb3bebeaf5802a8609b", 
        "date": "2019-02-06T06:11:36.596316+02:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "subcontractingDetails": "ДКП «Орфей», Україна"
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "scale": "micro", 
        "name": "ДКП «Школяр»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2019-02-06T06:11:36.596032+02:00", 
    "id": "6f69f4be052946f1acfcbc837fd6e65a"
  }
}

