GET /api/2.4/tenders/f3bc07ebff534a04b13c6d3f0c02dd37/bids/6f69f4be052946f1acfcbc837fd6e65a?acc_token=b31755c006a64495adcddb09191e6139 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "invalid", 
    "id": "6f69f4be052946f1acfcbc837fd6e65a"
  }
}

