POST /api/2.4/tenders/306f4c106ae448b89b6d1c0f5792dab5/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1047
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "selfQualified": true, 
    "lotValues": [
      {
        "relatedLot": "5b9893e9ddc24276a1e1329469882df3", 
        "value": {
          "amount": 500
        }
      }, 
      {
        "relatedLot": "13385faa11c844b7954b7e823426da2a", 
        "value": {
          "amount": 500
        }, 
        "subcontractingDetails": "ДКП «Укр Прінт», Україна"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк", 
          "email": "aagt@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/306f4c106ae448b89b6d1c0f5792dab5/bids/d0ea1d7b271c491281eb6cda5a8e1310
{
  "access": {
    "token": "8a660ed95a2144c98923cc1d1fdb902a"
  }, 
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "5b9893e9ddc24276a1e1329469882df3", 
        "date": "2018-08-15T10:42:14.057366+03:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }, 
      {
        "relatedLot": "13385faa11c844b7954b7e823426da2a", 
        "date": "2018-08-15T10:42:14.057703+03:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "subcontractingDetails": "ДКП «Укр Прінт», Україна"
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2018-08-15T10:42:14.056917+03:00", 
    "id": "d0ea1d7b271c491281eb6cda5a8e1310"
  }
}

