PATCH /api/2.5/tenders/d31f5c7085db4e08912359274057ea4d/bids/3e97dabd5f824c34b5dc05642eb4409a?acc_token=7a8f39cc67244f18bf5cf5952502c530 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 124
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "d7e3888f747f4927a519c996c72eb677", 
        "value": {
          "amount": 500
        }
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "lotValues": [
      {
        "relatedLot": "d7e3888f747f4927a519c996c72eb677", 
        "date": "2019-03-28T06:49:58.862970+02:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-03-28T06:49:58.862530+02:00", 
    "id": "3e97dabd5f824c34b5dc05642eb4409a"
  }
}

