GET /api/2.5/tenders/f79202ed72aa4df58b23e22a833948e3/qualifications?acc_token=b74885a1dd3b4781927e9e335d2ee742 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "pending", 
      "lotID": "9c681dd3701140aeb8c6d83ae1a31e38", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "6b7fb0e3b86d4427aba6d08b7bf4c1b7", 
      "date": "2019-04-01T01:00:00+03:00", 
      "id": "c5410d234aa74254bd9636f3e2c1a651"
    }, 
    {
      "status": "pending", 
      "lotID": "9c681dd3701140aeb8c6d83ae1a31e38", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "92d3348340fa46f8b031aeec7990dba0", 
      "date": "2019-04-01T01:00:00+03:00", 
      "id": "795a11ac481d41d5b588f1f032fad07a"
    }
  ]
}

