GET /api/2.5/tenders/c7bc76c4afe1401292e0d567b37eab99/qualifications?acc_token=52541937675a4250922ff33b145f5b0f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "pending", 
      "lotID": "ce64571476054cff89bc1c2dd50e323e", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "59fea58d161a47049fb09df599b762e7", 
      "date": "2019-01-01T00:00:00+02:00", 
      "id": "a23dd813d5474911ade6467c8077693d"
    }, 
    {
      "status": "pending", 
      "lotID": "ce64571476054cff89bc1c2dd50e323e", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "83c1121358ef48cab5216e6c7620e657", 
      "date": "2019-01-01T00:00:00+02:00", 
      "id": "c4db9bf31f2a42c5a755f23b6e97ac9f"
    }
  ]
}

