PATCH /api/2.5/tenders/c7bc76c4afe1401292e0d567b37eab99?acc_token=52541937675a4250922ff33b145f5b0f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 125
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "items": [
      {
        "relatedLot": "ce64571476054cff89bc1c2dd50e323e"
      }, 
      {
        "relatedLot": "661ada0b9e224d4a9495c8c8b357746a"
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.tendering", 
    "date": "2019-01-01T00:00:00+02:00", 
    "tenderPeriod": {
      "startDate": "2019-01-01T00:00:00+02:00", 
      "endDate": "2019-05-19T06:49:21.594933+03:00"
    }, 
    "title": "Послуги шкільних їдалень", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procurementMethodType": "aboveThresholdEU", 
    "complaintPeriod": {
      "startDate": "2019-01-01T00:00:00+02:00", 
      "endDate": "2019-05-15T00:00:00+03:00"
    }, 
    "title_en": "Services in school canteens", 
    "value": {
      "currency": "UAH", 
      "amount": 1000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "submissionMethod": "electronicAuction", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2019-06-24T00:00:00+03:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "ce64571476054cff89bc1c2dd50e323e"
      }, 
      {
        "status": "active", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2019-06-24T00:00:00+03:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-01-01T00:00:00+02:00", 
        "id": "661ada0b9e224d4a9495c8c8b357746a"
      }
    ], 
    "next_check": "2019-05-19T06:49:21.594933+03:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "awardCriteria": "lowestCost", 
    "enquiryPeriod": {
      "startDate": "2019-01-01T00:00:00+02:00", 
      "clarificationsUntil": "2019-05-15T00:00:00+03:00", 
      "endDate": "2019-05-09T06:49:21.594933+03:00", 
      "invalidationDate": "2019-01-01T00:00:00+02:00"
    }, 
    "owner": "broker", 
    "dateModified": "2019-01-01T00:00:00+02:00", 
    "items": [
      {
        "relatedLot": "ce64571476054cff89bc1c2dd50e323e", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-05-08T06:49:21.594579+03:00", 
          "endDate": "2019-06-07T06:49:21.594605+03:00"
        }, 
        "id": "dde86b8a192142d8adbd0182b4c18b87", 
        "quantity": 1.0
      }, 
      {
        "relatedLot": "661ada0b9e224d4a9495c8c8b357746a", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-05-08T06:49:21.594619+03:00", 
          "endDate": "2019-06-07T06:49:21.594627+03:00"
        }, 
        "id": "c08df272f6144dd9abb037c698cdae51", 
        "quantity": 1.0
      }
    ], 
    "id": "c7bc76c4afe1401292e0d567b37eab99", 
    "tenderID": "UA-2019-01-01-000001"
  }
}

