PATCH /api/2.5/tenders/d31f5c7085db4e08912359274057ea4d?acc_token=4d5dc6f3d89c4aeb8c5ff278c262ed54 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification.stand-still", 
    "complaintPeriod": {
      "startDate": "2019-02-26T06:49:59.136885+02:00", 
      "endDate": "2019-03-24T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-02-26T06:49:59.136885+02:00", 
      "clarificationsUntil": "2019-03-21T06:49:59.136885+02:00", 
      "endDate": "2019-03-18T06:49:59.136885+02:00", 
      "invalidationDate": "2019-03-28T06:49:58.934797+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-04-03T01:00:00+03:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "d31f5c7085db4e08912359274057ea4d", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2019-04-03T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-03-28T06:49:58.573794+02:00", 
        "id": "d7e3888f747f4927a519c996c72eb677"
      }, 
      {
        "status": "unsuccessful", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 400.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2019-03-28T06:49:59.232985+02:00", 
        "id": "c3784ef3e3b448788bba15480aaed581"
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2019-03-28T06:49:59.227419+02:00", 
      "endDate": "2019-04-03T00:00:00+02:00"
    }, 
    "tenderID": "UA-2019-03-28-000001", 
    "dateModified": "2019-03-28T06:49:59.625411+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2019-02-26T06:49:59.136885+02:00", 
      "endDate": "2019-03-28T06:49:59.136885+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "lotID": "d7e3888f747f4927a519c996c72eb677", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "4a2d1aeb0f7f4519a6891437efead6ef", 
        "date": "2019-03-28T06:49:59.347305+02:00", 
        "id": "f2f65c47598c4249b705c9545b1fa623"
      }, 
      {
        "status": "active", 
        "lotID": "d7e3888f747f4927a519c996c72eb677", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "3e97dabd5f824c34b5dc05642eb4409a", 
        "date": "2019-03-28T06:49:59.453692+02:00", 
        "id": "f3e1193aa95940a1b0744220c76fd741"
      }
    ], 
    "procurementMethodType": "aboveThresholdEU", 
    "date": "2019-03-28T06:49:59.625411+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "d7e3888f747f4927a519c996c72eb677", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-17T06:47:08.947035+02:00", 
          "endDate": "2019-05-17T06:47:08.947066+02:00"
        }, 
        "id": "538450d2801d4fd29277a6265087452a", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }, 
      {
        "relatedLot": "c3784ef3e3b448788bba15480aaed581", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-17T06:47:08.947077+02:00", 
          "endDate": "2019-05-17T06:47:08.947084+02:00"
        }, 
        "id": "318cc0eb0b0e45d589e5eb90d5e69b31", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "id": "4a2d1aeb0f7f4519a6891437efead6ef", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "3e97dabd5f824c34b5dc05642eb4409a", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 900.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

