POST /api/2.5/tenders/c7bc76c4afe1401292e0d567b37eab99/lots?acc_token=52541937675a4250922ff33b145f5b0f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 214
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "description": "Опис Лот №1", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "title": "Лот №1"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/c7bc76c4afe1401292e0d567b37eab99/lots/ce64571476054cff89bc1c2dd50e323e
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №1", 
    "title": "Лот №1", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-06-24T00:00:00+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "ce64571476054cff89bc1c2dd50e323e"
  }
}

