PATCH /api/2.5/tenders/1383287972d14f3f9c6b63c63040032e/lots/1f0eaa2db4cf4aaa8ef49759231fa3dd?acc_token=e5c7229f8cbf4286a56aff52acbe0e9b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "value": {
      "amount": 400
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №2", 
    "title": "Лот №2", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-05-24T00:00:00+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 400.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-18T09:27:52.732139+02:00", 
    "id": "1f0eaa2db4cf4aaa8ef49759231fa3dd"
  }
}

