PATCH /api/2.5/tenders/d31f5c7085db4e08912359274057ea4d/lots/c3784ef3e3b448788bba15480aaed581?acc_token=4d5dc6f3d89c4aeb8c5ff278c262ed54 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "value": {
      "amount": 400
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №2", 
    "title": "Лот №2", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-06-03T00:00:00+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 400.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-03-28T06:49:58.608359+02:00", 
    "id": "c3784ef3e3b448788bba15480aaed581"
  }
}

