PATCH /api/2.5/tenders/167bc218c6a347f0affb12c1cb33f317/lots/9d4fc4783ebb4a99b10cc9a2f7d7552f?acc_token=1c6df7c6b242477a971912ece9a0a193 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "value": {
      "amount": 400
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №2", 
    "title": "Лот №2", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2019-06-06T00:00:00+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 400.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "9d4fc4783ebb4a99b10cc9a2f7d7552f"
  }
}

