PATCH /api/2.4/tenders/306f4c106ae448b89b6d1c0f5792dab5?acc_token=0e8185f01cce40c288f8f4095638d39c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification.stand-still", 
    "complaintPeriod": {
      "startDate": "2018-07-16T10:42:14.609763+03:00", 
      "endDate": "2018-08-11T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2018-07-16T10:42:14.609763+03:00", 
      "clarificationsUntil": "2018-08-09T00:00:00+03:00", 
      "endDate": "2018-08-05T10:42:14.609763+03:00", 
      "invalidationDate": "2018-08-15T10:42:14.193214+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-08-21T00:00:00+03:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "306f4c106ae448b89b6d1c0f5792dab5", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2018-08-21T00:00:00+03:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2018-08-15T10:42:13.539041+03:00", 
        "id": "5b9893e9ddc24276a1e1329469882df3"
      }, 
      {
        "status": "unsuccessful", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 400.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2018-08-15T10:42:14.827997+03:00", 
        "id": "13385faa11c844b7954b7e823426da2a"
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2018-08-15T10:42:14.822499+03:00", 
      "endDate": "2018-08-21T00:00:00+03:00"
    }, 
    "tenderID": "UA-2018-08-15-000001", 
    "dateModified": "2018-08-15T10:42:15.404414+03:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2018-07-16T10:42:14.609763+03:00", 
      "endDate": "2018-08-15T10:42:14.609763+03:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "lotID": "5b9893e9ddc24276a1e1329469882df3", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "f3a576bffa554a14aa231d372bd0e7df", 
        "date": "2018-08-15T10:42:15.062076+03:00", 
        "id": "87927d8a5cd747249fe282a79cd54eaa"
      }, 
      {
        "status": "active", 
        "lotID": "5b9893e9ddc24276a1e1329469882df3", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "d0ea1d7b271c491281eb6cda5a8e1310", 
        "date": "2018-08-15T10:42:15.197928+03:00", 
        "id": "1ec8bd8f53cf47d5823326a371f3bdec"
      }
    ], 
    "procurementMethodType": "aboveThresholdEU", 
    "date": "2018-08-15T10:42:15.404414+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "5b9893e9ddc24276a1e1329469882df3", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-04T10:41:47.677546+03:00", 
          "endDate": "2018-10-04T10:41:47.677590+03:00"
        }, 
        "id": "ba0f3bbcf0424cdc8fd56e15d1e7f58b", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "relatedLot": "13385faa11c844b7954b7e823426da2a", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-04T10:41:47.677607+03:00", 
          "endDate": "2018-10-04T10:41:47.677617+03:00"
        }, 
        "id": "3735e2d6f3f8482891dd5cd780d8be8e", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "id": "f3a576bffa554a14aa231d372bd0e7df", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "d0ea1d7b271c491281eb6cda5a8e1310", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 900.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

