POST /api/2.5/tenders/23d35a5c2e6844dc9fc7578261093930/awards/c87123b05f14484c857bb03bb1f025eb/complaints/b5ed32ee643d40dd9c0c372e9a7c475f/documents?acc_token=4f533142bae74436820eb25db0c46721 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 151
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/23d35a5c2e6844dc9fc7578261093930/awards/c87123b05f14484c857bb03bb1f025eb/complaints/b5ed32ee643d40dd9c0c372e9a7c475f/documents/37e60f2b05e8405f83726e76db2db2a7
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/521a22389c324ab99bf1a317b61b26bb?KeyID=a8968c46&Signature=3JnEpoLtPZkFCo50sbH%252BAfSlqwYfSgskDVaPn5G%2FjIZm%252BZMbzwyT57%2FGqQ7h%2FiXcGWDpGzBr6Gbnbj0JGepUBA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:01+03:00", 
    "id": "37e60f2b05e8405f83726e76db2db2a7", 
    "dateModified": "2019-04-01T01:00:01+03:00"
  }
}

