POST /api/2.5/tenders/23d35a5c2e6844dc9fc7578261093930/awards/c87123b05f14484c857bb03bb1f025eb/complaints/b5ed32ee643d40dd9c0c372e9a7c475f/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 149
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="ComplaintResolution.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/23d35a5c2e6844dc9fc7578261093930/awards/c87123b05f14484c857bb03bb1f025eb/complaints/b5ed32ee643d40dd9c0c372e9a7c475f/documents/dc38681af71c4ab28e582878bc592e38
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/79d093fe932a4855a1898cabe5ea9c83?KeyID=a8968c46&Signature=LuSis2RPIo%2FMQI6hqGrKSrOu1P3O9ZAleehyE539NUeG6zfKMK6gR%2Fx%2FN77NmEs46T52zI%252B0OaqhW2S%2FamofAQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:01+03:00", 
    "id": "dc38681af71c4ab28e582878bc592e38", 
    "dateModified": "2019-04-01T01:00:01+03:00"
  }
}

