GET /api/2.5/tenders/5fb29c8fb65c4a12b69dd3531cfe7bce/contracts/58ac53c9808c41f6b9bef2cc04d5235f/documents?acc_token=bc6711b5ba434b92bbba26699dca3104 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "title": "contract_first_document.doc", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ec032704e12b46419043bb7ecae8db59?KeyID=a8968c46&Signature=iH87D4mk2SPPmKQ%252BpGxPT3dG%2FSiCdX4LxHuxE4XOd0CB%2FqMHqRIr5lSerj21nfa8IP6NeUl6tqgpQdDvAF4eCg%253D%253D", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2019-10-01T01:00:00+03:00", 
      "id": "c617e21e8b9c4d25889112d0d9613a86", 
      "dateModified": "2019-10-01T01:00:00+03:00"
    }
  ]
}

