PATCH /api/2.5/tenders/3380abd6dac247a394ea054cfe23249b/awards/02e73dd649794aeaa7214ad1005d1272/complaints/9bbba3b10b73436f86c179f790a913da HTTP/1.0
Authorization: Bearer reviewer
Content-Length: 31
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "invalid"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "dateDecision": "2019-10-25T01:00:01+03:00", 
    "transfer_token": "504495d396fac102e5e8a2ac5e029f4860b0dfd7cb0475ead81af8c3fcef47a7e0cd0a547f3a15d011cf3e8d36c801fbd580e370c99dc9fe62429c0cc6e9bce4", 
    "title": "Недостатньо інформації", 
    "acceptance": false, 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2019-10-25T01:00:01+03:00", 
    "complaintID": "UA-2019-10-25-000001.2", 
    "date": "2019-10-25T01:00:01+03:00", 
    "type": "complaint", 
    "id": "9bbba3b10b73436f86c179f790a913da", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс."
  }
}

