PATCH /api/2.5/tenders/ef61695c05174b37b2bb6a8da114cc9d/cancellations/d35ec63713a7471d89b664fb191f9815/documents/f91424c533a24036b319313e97116979?acc_token=13e38459f2944eb0a08a6e5152a10b3e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/24357fdcda3c45ffbd74239e45329edd?KeyID=a8968c46&Signature=hGrgwRJ2kx0DUxhPElg3ybUTsPGIWMdRvEFZvT3pxNlNOc97ghtiNbe%2FBJt0GxJbPho%252BQUUZU5B3dBFZbQjPBA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:01+03:00", 
    "id": "f91424c533a24036b319313e97116979", 
    "dateModified": "2019-04-01T01:00:01+03:00"
  }
}

