GET /api/2.5/tenders/96c58765139d4dfb9ff274018c231eb8/qualifications/6f34bf7d14e94a5bae1658e16d777f8f/complaints HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2019-04-01T01:00:01+03:00", 
      "tendererActionDate": "2019-04-01T01:00:01+03:00", 
      "transfer_token": "3f2b8b696c336be60812e404e821a4db53bf758415a102c4bb5e6f5d6aa9f353fdff7658e2cc3bfee80d2e55225f3a5cf8ea413a3a86531521cb66e1187e007f", 
      "title": "Калорійність", 
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "author": {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }, 
      "tendererAction": "Умови виправлено", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/051f731a9f104688b0c137e9a5c04777?KeyID=a8968c46&Signature=wF0jmg%2FdaOtDz2eZLiv0oHu6GizdzAhR6wiUU3HT1V29D%2FB39AjM5iVenZ9HUslsUJV5BAi%252BoEwg3VKoH6nvBQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:01+03:00", 
          "id": "25a1bd26690742f7980731cb3c7fbf30", 
          "dateModified": "2019-04-01T01:00:01+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/08f1759d6a0e4137af1abaf78b4d01ec?KeyID=a8968c46&Signature=AHtkpGXRJgpZp%252BystfZWIdntrUUQjOUvvdQd%252BgBgqoUoZn5xDz%252B05D%252By77i34byv69LccMUkKYwBsPC7oAw2Dw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:00:01+03:00", 
          "id": "e7879700976142d98ccc748f8a14f163", 
          "dateModified": "2019-04-01T01:00:01+03:00"
        }
      ], 
      "dateSubmitted": "2019-04-01T01:00:01+03:00", 
      "complaintID": "UA-2019-04-01-000001.1", 
      "date": "2019-04-01T01:00:01+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "id": "91b4ff9fd2ea4cf0a3f514415544d394", 
      "dateAccepted": "2019-04-01T01:00:01+03:00"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2019-04-01T01:00:01+03:00", 
      "transfer_token": "42d29584602934d3ce7eceb4fbca6b050c8cc8625d821c77049fc5a72064bf5434e29132533e76bee6639a68ea33d4a92b58373954d8c8fc9947db23bb5fcc66", 
      "title": "Недостатньо інформації", 
      "acceptance": false, 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-04-01T01:00:01+03:00", 
      "complaintID": "UA-2019-04-01-000001.2", 
      "date": "2019-04-01T01:00:01+03:00", 
      "type": "complaint", 
      "id": "369efe809d7342e6ac52d7b63caec9dc", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс."
    }, 
    {
      "status": "declined", 
      "dateDecision": "2019-04-01T01:00:01+03:00", 
      "transfer_token": "610f8a2df9afaa080c799a936e17f6d9991ecb305006a07f96a0df1627502fe6b349341135f1c60db8b9903531bfa99308a83be6bcd49cf748461797ff9db11c", 
      "title": "Недостатньо інформації", 
      "acceptance": true, 
      "dateAccepted": "2019-04-01T01:00:01+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-04-01T01:00:01+03:00", 
      "complaintID": "UA-2019-04-01-000001.3", 
      "date": "2019-04-01T01:00:01+03:00", 
      "type": "complaint", 
      "id": "25c98965719a4534aa16a2e710c36ace", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс."
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-04-01T01:00:01+03:00", 
      "transfer_token": "bf729472630137d4236c1681332a4a246ec1440eb727bb88f0be65c3d337ba0df7581101dbff1c5bc8ec87ff9197fe510cf221e8f2951a8db67305f080624d11", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2019-04-01T01:00:01+03:00", 
      "dateAccepted": "2019-04-01T01:00:01+03:00", 
      "dateSubmitted": "2019-04-01T01:00:01+03:00", 
      "complaintID": "UA-2019-04-01-000001.4", 
      "date": "2019-04-01T01:00:01+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "34b78915dd754db7a215360fa11eeb0a", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс."
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-04-01T01:00:01+03:00", 
      "transfer_token": "bb40467a0c54ede5632d7f0a3a61f35c7176e9caac12f480d14816dbd8a82a0f1cb1d8d5372ced02767662083a6bcdd5b098b9734b1dcddafae5840cf977c379", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2019-04-01T01:00:01+03:00", 
      "dateAccepted": "2019-04-01T01:00:01+03:00", 
      "dateSubmitted": "2019-04-01T01:00:01+03:00", 
      "complaintID": "UA-2019-04-01-000001.5", 
      "date": "2019-04-01T01:00:01+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "17e772d985614e05bc1af9006a57c17d", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс."
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "bid_id": "c1eb30e6f1dd4063b94519c80ff7c1e8", 
      "dateAnswered": "2019-04-01T01:00:01+03:00", 
      "dateSubmitted": "2019-04-01T01:00:01+03:00", 
      "complaintID": "UA-2019-04-01-000001.6", 
      "date": "2019-04-01T01:00:01+03:00", 
      "resolution": "Умови виправлено, вибір переможня буде розгянуто повторно", 
      "id": "445641d405ae47a5968776b9e848fc2e"
    }, 
    {
      "status": "answered", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "claim", 
      "satisfied": false, 
      "bid_id": "c1eb30e6f1dd4063b94519c80ff7c1e8", 
      "dateAnswered": "2019-04-01T01:00:01+03:00", 
      "dateSubmitted": "2019-04-01T01:00:01+03:00", 
      "complaintID": "UA-2019-04-01-000001.7", 
      "date": "2019-04-01T01:00:01+03:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "260e7b8c78dc4a419eadbe913fd64567"
    }, 
    {
      "status": "claim", 
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "title": "Калорійність", 
      "bid_id": "c1eb30e6f1dd4063b94519c80ff7c1e8", 
      "dateSubmitted": "2019-04-01T01:00:01+03:00", 
      "complaintID": "UA-2019-04-01-000001.8", 
      "date": "2019-04-01T01:00:01+03:00", 
      "type": "claim", 
      "id": "ae2f38235cfe4bd19664f7fcc385abc1"
    }, 
    {
      "status": "cancelled", 
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "title": "Калорійність", 
      "bid_id": "c1eb30e6f1dd4063b94519c80ff7c1e8", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2019-04-01T01:00:01+03:00", 
      "complaintID": "UA-2019-04-01-000001.9", 
      "date": "2019-04-01T01:00:01+03:00", 
      "type": "claim", 
      "id": "747f82f1f5e64bc4a791b5dce0feb508"
    }
  ]
}

