PATCH /api/2.5/tenders/96c58765139d4dfb9ff274018c231eb8/qualifications/6f34bf7d14e94a5bae1658e16d777f8f/complaints/25c98965719a4534aa16a2e710c36ace HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "declined"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "declined", 
    "dateDecision": "2019-04-01T01:00:01+03:00", 
    "transfer_token": "610f8a2df9afaa080c799a936e17f6d9991ecb305006a07f96a0df1627502fe6b349341135f1c60db8b9903531bfa99308a83be6bcd49cf748461797ff9db11c", 
    "title": "Недостатньо інформації", 
    "acceptance": true, 
    "dateAccepted": "2019-04-01T01:00:01+03:00", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2019-04-01T01:00:01+03:00", 
    "complaintID": "UA-2019-04-01-000001.3", 
    "date": "2019-04-01T01:00:01+03:00", 
    "type": "complaint", 
    "id": "25c98965719a4534aa16a2e710c36ace", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс."
  }
}

