GET /api/2.5/tenders/96c58765139d4dfb9ff274018c231eb8/qualifications/6f34bf7d14e94a5bae1658e16d777f8f/complaints/91b4ff9fd2ea4cf0a3f514415544d394 HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "dateDecision": "2019-04-01T01:00:01+03:00", 
    "tendererActionDate": "2019-04-01T01:00:01+03:00", 
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "author": {
      "contactPoint": {
        "email": "aagt@gmail.com", 
        "telephone": "+380 (322) 91-69-30", 
        "name": "Андрій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137226", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Книга»", 
      "address": {
        "postalCode": "79013", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 34", 
        "region": "м. Львів", 
        "locality": "м. Львів"
      }
    }, 
    "title": "Калорійність", 
    "id": "91b4ff9fd2ea4cf0a3f514415544d394", 
    "tendererAction": "Умови виправлено", 
    "dateSubmitted": "2019-04-01T01:00:01+03:00", 
    "complaintID": "UA-2019-04-01-000001.1", 
    "date": "2019-04-01T01:00:01+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/051f731a9f104688b0c137e9a5c04777?KeyID=a8968c46&Signature=wF0jmg%2FdaOtDz2eZLiv0oHu6GizdzAhR6wiUU3HT1V29D%2FB39AjM5iVenZ9HUslsUJV5BAi%252BoEwg3VKoH6nvBQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:01+03:00", 
        "id": "25a1bd26690742f7980731cb3c7fbf30", 
        "dateModified": "2019-04-01T01:00:01+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/08f1759d6a0e4137af1abaf78b4d01ec?KeyID=a8968c46&Signature=AHtkpGXRJgpZp%252BystfZWIdntrUUQjOUvvdQd%252BgBgqoUoZn5xDz%252B05D%252By77i34byv69LccMUkKYwBsPC7oAw2Dw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:01+03:00", 
        "id": "e7879700976142d98ccc748f8a14f163", 
        "dateModified": "2019-04-01T01:00:01+03:00"
      }
    ], 
    "dateAccepted": "2019-04-01T01:00:01+03:00"
  }
}

