PATCH /api/2.5/tenders/636f8ed2b38c43ceb7d481bb2c0bf72b/questions/7ba57e064ecb4964bf3e93159b375cdd?acc_token=53dd6cedd9bf46d59d2ec79baf9bd876 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2019-03-18T16:26:56.493735+02:00", 
    "title": "Калорійність", 
    "date": "2019-03-18T16:26:55.814122+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "7ba57e064ecb4964bf3e93159b375cdd", 
    "questionOf": "tender"
  }
}

