PATCH /api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/qualifications/990ce8fb4a3343e98425d97a5363f591?acc_token=0d11f7c340f04eb68da346a7b621ccc5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "b5767f4d83754df8bfc04bd54e3dd5a0", 
    "date": "2018-09-21T05:24:19.233336+03:00", 
    "id": "990ce8fb4a3343e98425d97a5363f591"
  }
}

