PATCH /api/2.5/tenders/d0fb203f920043de865a7f95960754e6/qualifications/20c2d93f7b254986a1fa2111cedf20b7?acc_token=7ac178c1bd1d4afa85045400eac1f72c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "1ed39182ee004710b81381117ac43978", 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "20c2d93f7b254986a1fa2111cedf20b7"
  }
}

