PATCH /api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/qualifications/4388a6e9cf6b47dc8544d020224099b4?acc_token=0d11f7c340f04eb68da346a7b621ccc5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "551d2116a66948fdae44b93c84c53b2b", 
    "date": "2018-09-21T05:24:19.450643+03:00", 
    "id": "4388a6e9cf6b47dc8544d020224099b4"
  }
}

