PATCH /api/2.5/tenders/636f8ed2b38c43ceb7d481bb2c0bf72b/qualifications/f0a4d10952824b65a9d29ca11008c99b?acc_token=53dd6cedd9bf46d59d2ec79baf9bd876 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 67
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active", 
    "qualified": true, 
    "eligible": true
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "eligible": true, 
    "qualified": true, 
    "bidID": "5456ed6a72344945a29facb0b378690e", 
    "date": "2019-03-18T16:27:08.279359+02:00", 
    "id": "f0a4d10952824b65a9d29ca11008c99b"
  }
}

