PATCH /api/2.5/tenders/4567a13c28924551ab5f0c058e75943d/awards/860893ad77134595b3fb665849edbab9?acc_token=9688a4268a0b441cacb9a88275b19320 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "cancelled"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/4567a13c28924551ab5f0c058e75943d/awards/62c0dc8d9e864c48bc35e15ca5b6f06a
{
  "data": {
    "status": "cancelled", 
    "eligible": true, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "scale": "sme", 
        "name": "ДКП «Книга»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "complaintPeriod": {
      "startDate": "2019-04-01T01:00:01+03:00", 
      "endDate": "2019-04-01T01:00:03+03:00"
    }, 
    "bid_id": "3f632e62e8d74c2798537ae114567dc6", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2019-04-01T01:00:03+03:00", 
    "qualified": true, 
    "complaints": [
      {
        "status": "satisfied", 
        "dateDecision": "2019-04-01T01:00:03+03:00", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "complaint_owner", 
            "language": "uk", 
            "title": "Complaint_Attachement.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/bcf8cff2b7234094907cd0a278d5e22a?KeyID=a8968c46&Signature=76EpwNcyISva2MXpzBr4Ms%252BkCh4ghTiffxUwGHKZXQlTLcQZXEabyIUwWXOXs91MQynZA30fGJK227FfcyXLCw%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:03+03:00", 
            "id": "eac8f89e72804cb7a835e7a88194af0d", 
            "dateModified": "2019-04-01T01:00:03+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "author": "aboveThresholdReviewers", 
            "language": "uk", 
            "title": "ComplaintResolution.pdf", 
            "url": "http://public-docs-sandbox.prozorro.gov.ua/get/21bdb98a234a4368a2ed74d224a76dc3?KeyID=a8968c46&Signature=joutqKA6MvEOg45DKC7MmfT9d2Ix1WFY5gSUJAuJWaBfNRUMM6aVVYNrqZ%252BIEnB3bQXCR6pouAX9HXSbPfCBAQ%253D%253D", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2019-04-01T01:00:03+03:00", 
            "id": "ba9fe9ce72b54063b49c1ebf1dd0d962", 
            "dateModified": "2019-04-01T01:00:03+03:00"
          }
        ], 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": true, 
        "dateAccepted": "2019-04-01T01:00:03+03:00", 
        "dateSubmitted": "2019-04-01T01:00:03+03:00", 
        "complaintID": "UA-2019-04-01-000001.1", 
        "date": "2019-04-01T01:00:03+03:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "9c187bbc01aa4229bac6bccdd70fa823"
      }, 
      {
        "status": "invalid", 
        "dateDecision": "2019-04-01T01:00:03+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": false, 
        "dateSubmitted": "2019-04-01T01:00:03+03:00", 
        "complaintID": "UA-2019-04-01-000001.2", 
        "date": "2019-04-01T01:00:03+03:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "bfd25ad2251b474b99c1b8522c367158"
      }, 
      {
        "status": "declined", 
        "dateDecision": "2019-04-01T01:00:03+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "acceptance": true, 
        "dateAccepted": "2019-04-01T01:00:03+03:00", 
        "dateSubmitted": "2019-04-01T01:00:03+03:00", 
        "complaintID": "UA-2019-04-01-000001.3", 
        "date": "2019-04-01T01:00:03+03:00", 
        "title": "Недостатньо інформації", 
        "type": "complaint", 
        "id": "dff7602ac83841c88f8aa3a6bdd9916c"
      }, 
      {
        "status": "stopped", 
        "dateDecision": "2019-04-01T01:00:03+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "decision": "Тендер скасовується замовником", 
        "acceptance": true, 
        "cancellationReason": "Тендер скасовується замовником", 
        "dateCanceled": "2019-04-01T01:00:03+03:00", 
        "dateAccepted": "2019-04-01T01:00:03+03:00", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateSubmitted": "2019-04-01T01:00:03+03:00", 
        "complaintID": "UA-2019-04-01-000001.4", 
        "date": "2019-04-01T01:00:03+03:00", 
        "type": "complaint", 
        "id": "2580b561cd1d406a954049db6a9d545d"
      }, 
      {
        "status": "stopped", 
        "dateDecision": "2019-04-01T01:00:03+03:00", 
        "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
        "title": "Недостатньо інформації", 
        "decision": "Тендер скасовується замовником", 
        "acceptance": true, 
        "dateCanceled": "2019-04-01T01:00:03+03:00", 
        "dateAccepted": "2019-04-01T01:00:03+03:00", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "dateSubmitted": "2019-04-01T01:00:03+03:00", 
        "complaintID": "UA-2019-04-01-000001.5", 
        "date": "2019-04-01T01:00:03+03:00", 
        "type": "complaint", 
        "id": "91b76ba5a8914e418c06a4536dee2041"
      }
    ], 
    "id": "860893ad77134595b3fb665849edbab9"
  }
}

