PATCH /api/2.5/tenders/80e220d0e49845a59a9077d56e66288f/awards/b4f04add5866446fa2fb375f9579234e/complaints/c8df1c935b244db3a9b7807b2e3ee4a0?acc_token=587301e140dc4e41a24ed98b3ff6ef0a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/64eb1ea16d654b149108350f01d9357f?KeyID=a8968c46&Signature=G4ItL4FlXn8a9LbeC%2FeSVOIld0mXq1isTkeOQ7zK5J44HBI6JiVKC2uoWsd5mLpauG9%252Bdap8sFgDFFgskWHYBw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:30:00+02:00", 
        "id": "83a704af49eb45d89d529ce442e2d6d3", 
        "dateModified": "2019-01-01T00:30:00+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "dateSubmitted": "2019-01-01T00:30:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.1", 
    "date": "2019-01-01T00:30:00+02:00", 
    "type": "complaint", 
    "id": "c8df1c935b244db3a9b7807b2e3ee4a0"
  }
}

