POST /api/2.5/tenders/4567a13c28924551ab5f0c058e75943d/awards/860893ad77134595b3fb665849edbab9/complaints/9c187bbc01aa4229bac6bccdd70fa823/documents?acc_token=31772d3922c5482e8b3543f66e570fce HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 151
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/4567a13c28924551ab5f0c058e75943d/awards/860893ad77134595b3fb665849edbab9/complaints/9c187bbc01aa4229bac6bccdd70fa823/documents/eac8f89e72804cb7a835e7a88194af0d
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/bcf8cff2b7234094907cd0a278d5e22a?KeyID=a8968c46&Signature=76EpwNcyISva2MXpzBr4Ms%252BkCh4ghTiffxUwGHKZXQlTLcQZXEabyIUwWXOXs91MQynZA30fGJK227FfcyXLCw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:03+03:00", 
    "id": "eac8f89e72804cb7a835e7a88194af0d", 
    "dateModified": "2019-04-01T01:00:03+03:00"
  }
}

