PATCH /api/2.5/tenders/80e220d0e49845a59a9077d56e66288f/awards/b4f04add5866446fa2fb375f9579234e/complaints/c8df1c935b244db3a9b7807b2e3ee4a0?acc_token=40701c9987894aefbd3eaba89e499399 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 361
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "resolved", 
    "tendererAction": "Умови виправлено, вибір переможня буде розгянуто повторно"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "dateDecision": "2019-04-01T01:30:00+03:00", 
    "tendererActionDate": "2019-04-01T01:30:00+03:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "id": "c8df1c935b244db3a9b7807b2e3ee4a0", 
    "tendererAction": "Умови виправлено, вибір переможня буде розгянуто повторно", 
    "dateSubmitted": "2019-04-01T01:30:00+03:00", 
    "complaintID": "UA-2019-04-01-000001.1", 
    "date": "2019-04-01T01:30:00+03:00", 
    "acceptance": true, 
    "type": "complaint", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/a669e8ee8969423284f359afded3fb27?KeyID=a8968c46&Signature=Aavs3uOmXgngwz59JBSWfRfRpk72RKLwrSeOA3uzJFuEqLli67vwmqLCfLnt2FuEf0Q%2FQ16yfOGTwPw1ZXZxDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:30:00+03:00", 
        "id": "83a704af49eb45d89d529ce442e2d6d3", 
        "dateModified": "2019-04-01T01:30:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e73912fd31d743ab8129eeef3d555ae4?KeyID=a8968c46&Signature=Hv6N3MOTd6SV27Q2OkcVbjyWM1WiVm8Z5kHV0siFVz%252BuY89PZNWMnW62FCDV4c9lhz0YpB8U7mqwWKwU5DwFBA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:30:00+03:00", 
        "id": "4e9956bca8c144049d47c8ad1eefc2ee", 
        "dateModified": "2019-04-01T01:30:00+03:00"
      }
    ], 
    "dateAccepted": "2019-04-01T01:30:00+03:00"
  }
}

