GET /api/2.5/tenders/fc67c57b5cdb4a06a99e35bd632b9366/bids/1c1eaf538f1f4fe4adf25d98f1a5eadd?acc_token=eb47ea6ba2de430bbc71e541ce5a3254 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "1c1eaf538f1f4fe4adf25d98f1a5eadd"
  }
}

