PATCH /api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids/b5767f4d83754df8bfc04bd54e3dd5a0?acc_token=4657c697784c435790b5e4e1c240aa1b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids/b5767f4d83754df8bfc04bd54e3dd5a0/documents/6833acfe1e5c4f29b78cca7f43eb5d40?download=601166d26167465992ac99a64cdc2f1d", 
        "format": "application/pdf", 
        "isDescriptionDecision": false, 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:24:16.279340+03:00", 
        "id": "6833acfe1e5c4f29b78cca7f43eb5d40", 
        "dateModified": "2018-09-21T05:24:16.279382+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "title": "DescriptiveProposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids/b5767f4d83754df8bfc04bd54e3dd5a0/documents/cb78fcf969614c249a778ad09364a810?download=113863eddfb846fd8b20d58ca923d0e3", 
        "format": "application/pdf", 
        "isDescriptionDecision": true, 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:24:16.439513+03:00", 
        "id": "cb78fcf969614c249a778ad09364a810", 
        "dateModified": "2018-09-21T05:24:16.439564+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids/b5767f4d83754df8bfc04bd54e3dd5a0/documents/3d60e2a7b9574e6b8282f544255b8ac1?download=2a6a97b9257a4d4190e9bfe76920c474", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_top_secrets.pdf", 
        "isDescriptionDecision": false, 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:24:16.760020+03:00", 
        "id": "3d60e2a7b9574e6b8282f544255b8ac1", 
        "dateModified": "2018-09-21T05:24:16.760064+03:00"
      }
    ], 
    "selfEligible": true, 
    "subcontractingDetails": "ДКП «Орфей», Україна", 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2018-09-21T05:24:15.961031+03:00", 
    "id": "b5767f4d83754df8bfc04bd54e3dd5a0"
  }
}

