PATCH /api/2.4/tenders/0bb5330bac844b2eb6dd5f4ecccc6e0c/complaints/d68d4aee22914132b12a06169857aed2?acc_token=a13f6d7dab7d4356bc87a946eb065049 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 51
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "resolved", 
    "satisfied": true
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "resolved", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "resolutionType": "resolved", 
    "type": "claim", 
    "satisfied": true, 
    "dateAnswered": "2018-09-21T05:23:49.178441+03:00", 
    "dateSubmitted": "2018-09-21T05:23:48.521783+03:00", 
    "complaintID": "UA-2018-09-21-000001.2", 
    "date": "2018-09-21T05:23:49.542141+03:00", 
    "resolution": "Виправлено неконкурентні умови", 
    "id": "d68d4aee22914132b12a06169857aed2"
  }
}

