PATCH /api/2.5/tenders/cbb1cc5b119d48b89a2459d7db3dcb72/complaints/0080c2a9ef634f6d92a8cba7ab3b2168?acc_token=4c838a33d8ed426da798ab8dd009ad18 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2019-01-01T00:10:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.7", 
    "date": "2019-01-01T00:10:00+02:00", 
    "type": "claim", 
    "id": "0080c2a9ef634f6d92a8cba7ab3b2168"
  }
}

