PATCH /api/2.5/tenders/6efaabd003ea40f0be90e9f0c1af3ece/complaints/fb760994215f4cfebe2ed2705bc40890 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "accepted"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "accepted", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f2ae617ca62a45aba5b6f9801863be25?KeyID=a8968c46&Signature=rcBobwdUxR9mH8aJwmn6uV6%2FVbf7nDnBt8YS27qqM7NxbKADZSYkYz5ZwFC9TJ5Fm%252BBBckNGNSPoO%252BagoiNmDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:01+03:00", 
        "id": "387f54bbff3d4aa3a180cfd70a678bde", 
        "dateModified": "2019-04-01T01:00:01+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "dateAccepted": "2019-04-01T01:00:01+03:00", 
    "dateSubmitted": "2019-04-01T01:00:01+03:00", 
    "complaintID": "UA-2019-04-01-000001.1", 
    "date": "2019-04-01T01:00:01+03:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "fb760994215f4cfebe2ed2705bc40890"
  }
}

