PATCH /api/2.5/tenders/349e0700a0a943709bf6699665e0c4f7/complaints/8d7a1a485d764655a60105fc8a9e088e?acc_token=e4a67d4973c04a6e834d2d5e3fba5fcb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 145
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "resolved", 
    "tendererAction": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "dateDecision": "2019-03-28T06:48:22.807623+02:00", 
    "tendererActionDate": "2019-03-28T06:48:23.063268+02:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "id": "8d7a1a485d764655a60105fc8a9e088e", 
    "tendererAction": "Умови виправлено", 
    "dateSubmitted": "2019-03-28T06:48:21.814282+02:00", 
    "complaintID": "UA-2019-03-28-000001.1", 
    "date": "2019-03-28T06:48:23.067765+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/28e11e8128c1413db120e3b6236d562d?KeyID=6e37a347&Signature=kLkL0QaZVGV6YUsIPt1FVKdk%2FYZ1kwsHX1e3mr5INjj9FLVkHDtYl%2FX7k1Bqm1l7qAoRnaWfJ8aR6fWR25gJBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:48:21.544125+02:00", 
        "id": "788c4f1373c44431b101275a17b8257f", 
        "dateModified": "2019-03-28T06:48:21.544141+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/c62f190655114fe2aca83723dd7a9ec9?KeyID=6e37a347&Signature=fNj5Hq2q4lzcmAfv0M54va%2F4gJUiBCGSbkrTACLPAfltYM%2FWEGhMOtm8faSShGKJj%2F1vpszMyQkiRDXfzNsMDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:48:22.732130+02:00", 
        "id": "bee25a1809084592a3ef10bdae839d16", 
        "dateModified": "2019-03-28T06:48:22.732146+02:00"
      }
    ], 
    "dateAccepted": "2019-03-28T06:48:22.406428+02:00"
  }
}

