PATCH /api/2.4/tenders/0bb5330bac844b2eb6dd5f4ecccc6e0c/complaints/3b53ae9424264ba0be645c5310925412?acc_token=9096443de95d4238a14589f6f0dc1d65 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 31
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/76005741af8c4ebabb960567a903a9c5?KeyID=f8b501ef&Signature=CsCdU4GbpMUfdJi1TU3aHHNemhAHWSplgdu6fJx8UsQMJzhqYrO2BO4%252B%2F6I%252BZNYuz4ElPRXr5Y2RmEf4qxM8AQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:23:48.225359+03:00", 
        "id": "f5dc03079bb1409e8f34e11e3386fb10", 
        "dateModified": "2018-09-21T05:23:48.225413+03:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "dateSubmitted": "2018-09-21T05:23:49.023521+03:00", 
    "complaintID": "UA-2018-09-21-000001.1", 
    "date": "2018-09-21T05:23:49.030542+03:00", 
    "type": "complaint", 
    "id": "3b53ae9424264ba0be645c5310925412"
  }
}

