POST /api/2.5/tenders/349e0700a0a943709bf6699665e0c4f7/complaints/8d7a1a485d764655a60105fc8a9e088e/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 199
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy425180197555$
Host: api-sandbox.openprocurement.org


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/349e0700a0a943709bf6699665e0c4f7/complaints/8d7a1a485d764655a60105fc8a9e088e/documents/bee25a1809084592a3ef10bdae839d16
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/c62f190655114fe2aca83723dd7a9ec9?KeyID=6e37a347&Signature=fNj5Hq2q4lzcmAfv0M54va%2F4gJUiBCGSbkrTACLPAfltYM%2FWEGhMOtm8faSShGKJj%2F1vpszMyQkiRDXfzNsMDw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-28T06:48:22.732130+02:00", 
    "id": "bee25a1809084592a3ef10bdae839d16", 
    "dateModified": "2019-03-28T06:48:22.732146+02:00"
  }
}

