GET /api/2.5/tenders/cbb1cc5b119d48b89a2459d7db3dcb72/complaints/9a97fc270cd84026a9797b4eced84600 HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "resolved", 
    "dateDecision": "2019-01-01T00:00:00+02:00", 
    "tendererActionDate": "2019-01-01T00:00:00+02:00", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "title": "Недостатньо інформації", 
    "id": "9a97fc270cd84026a9797b4eced84600", 
    "tendererAction": "Умови виправлено", 
    "dateSubmitted": "2019-01-01T00:00:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.1", 
    "date": "2019-01-01T00:00:00+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/6f9e744eb780458d860cb2c71ffca378?KeyID=a8968c46&Signature=5KzGxw6UlpF2rkPC0GRzMsw5fITtFuAwng5QWmYUKsd77IBhYdpIHllbJ46KfxvFi%2FxGQAUjjqK7RQmVZnjSDw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "92ac2cca5609426a88f8c4ac673fcd18", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "aboveThresholdReviewers", 
        "language": "uk", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/f905139b0ac14109845ee79bace19429?KeyID=a8968c46&Signature=b7IyFzUH4wL%252B1sMu99jQilnrZ6V1Q0K33nn3BvJN47sbQvnXSQKM1YRa%2Ffbgmsfh3AOi1mMDBzhuB68RntJfCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "a478d4cdca854e979ea4658e2d2c5ff2", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "dateAccepted": "2019-01-01T00:00:00+02:00"
  }
}

