PATCH /api/2.5/tenders/93161bc5e35041a4bbd188852c1c29be/complaints/62b877d8b52e459a9a9d4baaf04032e2?acc_token=e69586b437fb4df18a42cfae317f7dd2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 228
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "stopping", 
    "cancellationReason": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "stopping", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "cancellationReason": "Тендер скасовується замовником", 
    "dateCanceled": "2019-03-18T16:26:08.057739+02:00", 
    "dateAccepted": "2019-03-18T16:26:05.819442+02:00", 
    "dateSubmitted": "2019-03-18T16:26:03.304326+02:00", 
    "complaintID": "UA-2019-03-18-000001.6", 
    "date": "2019-03-18T16:26:08.089446+02:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "62b877d8b52e459a9a9d4baaf04032e2"
  }
}

