POST /api/2.5/tenders/6efaabd003ea40f0be90e9f0c1af3ece/complaints/fb760994215f4cfebe2ed2705bc40890/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 149
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="ComplaintResolution.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/6efaabd003ea40f0be90e9f0c1af3ece/complaints/fb760994215f4cfebe2ed2705bc40890/documents/14abd3c2154e479fb7242cfab8b52939
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/d8941be5fea142bfa1977e8cdff39732?KeyID=a8968c46&Signature=OZh4Z8HGZyrWpQKD6sB6%252BtnaNMtbuD6ew9WF41QfYTekZpn%252BtNIhOkFb6xMKhSORMmTwctHHz22kPepijV8CDA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:10:00+03:00", 
    "id": "14abd3c2154e479fb7242cfab8b52939", 
    "dateModified": "2019-04-01T01:10:00+03:00"
  }
}

