GET /api/2.5/tenders/349e0700a0a943709bf6699665e0c4f7/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2019-03-28T06:48:22.807623+02:00", 
      "tendererActionDate": "2019-03-28T06:48:23.063268+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "8d7a1a485d764655a60105fc8a9e088e", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2019-03-28T06:48:21.814282+02:00", 
      "complaintID": "UA-2019-03-28-000001.1", 
      "date": "2019-03-28T06:48:23.067765+02:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/28e11e8128c1413db120e3b6236d562d?KeyID=6e37a347&Signature=kLkL0QaZVGV6YUsIPt1FVKdk%2FYZ1kwsHX1e3mr5INjj9FLVkHDtYl%2FX7k1Bqm1l7qAoRnaWfJ8aR6fWR25gJBg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:48:21.544125+02:00", 
          "id": "788c4f1373c44431b101275a17b8257f", 
          "dateModified": "2019-03-28T06:48:21.544141+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/c62f190655114fe2aca83723dd7a9ec9?KeyID=6e37a347&Signature=fNj5Hq2q4lzcmAfv0M54va%2F4gJUiBCGSbkrTACLPAfltYM%2FWEGhMOtm8faSShGKJj%2F1vpszMyQkiRDXfzNsMDw%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:48:22.732130+02:00", 
          "id": "bee25a1809084592a3ef10bdae839d16", 
          "dateModified": "2019-03-28T06:48:22.732146+02:00"
        }
      ], 
      "dateAccepted": "2019-03-28T06:48:22.406428+02:00"
    }, 
    {
      "status": "resolved", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "resolved", 
      "type": "claim", 
      "satisfied": true, 
      "dateAnswered": "2019-03-28T06:48:21.874192+02:00", 
      "dateSubmitted": "2019-03-28T06:48:21.622308+02:00", 
      "complaintID": "UA-2019-03-28-000001.2", 
      "date": "2019-03-28T06:48:22.050526+02:00", 
      "resolution": "Виправлено неконкурентні умови", 
      "id": "bb2a8d12ad9a4b559cc096b99636d354"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2019-03-28T06:48:22.885963+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2019-03-28T06:48:22.471012+02:00", 
      "dateSubmitted": "2019-03-28T06:48:21.696598+02:00", 
      "complaintID": "UA-2019-03-28-000001.3", 
      "date": "2019-03-28T06:48:22.894927+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "122f9cf0b6434b2fa21338d9c9c22003"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2019-03-28T06:48:22.336740+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "resolutionType": "invalid", 
      "type": "complaint", 
      "acceptance": false, 
      "satisfied": false, 
      "dateEscalated": "2019-03-28T06:48:22.114083+02:00", 
      "dateAnswered": "2019-03-28T06:48:21.974252+02:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-03-28T06:48:21.753814+02:00", 
      "complaintID": "UA-2019-03-28-000001.4", 
      "date": "2019-03-28T06:48:22.342102+02:00", 
      "resolution": "Вимога не відповідає предмету закупівлі", 
      "id": "e3c7b74c6fb146cd9958d573bb844a3d"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-03-28T06:48:22.977689+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2019-03-28T06:48:22.977716+02:00", 
      "dateAccepted": "2019-03-28T06:48:22.575339+02:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-03-28T06:48:22.184498+02:00", 
      "complaintID": "UA-2019-03-28-000001.5", 
      "date": "2019-03-28T06:48:22.982733+02:00", 
      "type": "complaint", 
      "id": "59d4d9f7a9ed4f2b98dd4f7b0b85efec"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-03-28T06:48:23.274002+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2019-03-28T06:48:23.179366+02:00", 
      "dateAccepted": "2019-03-28T06:48:22.644576+02:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-03-28T06:48:22.257057+02:00", 
      "complaintID": "UA-2019-03-28-000001.6", 
      "date": "2019-03-28T06:48:23.279633+02:00", 
      "type": "complaint", 
      "id": "be41880c560847ba8bda6f316f774948"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2019-03-28T06:48:23.468222+02:00", 
      "complaintID": "UA-2019-03-28-000001.7", 
      "date": "2019-03-28T06:48:23.473663+02:00", 
      "type": "claim", 
      "id": "1cb0399f212e48d785b2fc74c22d004b"
    }
  ]
}

