GET /api/2.5/tenders/73c2c3f9cc6349f0a144ed40c9e3dfa7/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "dateAnswered": "2019-03-28T06:48:32.436239+02:00", 
      "title": "Калорійність", 
      "date": "2019-03-28T06:48:32.372642+02:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "99748b3b16684deeb3bcdfae2cbb7ea4", 
      "questionOf": "tender"
    }
  ]
}

