PATCH /api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/bids/597f8b71d8db469398b44e7a96cbafd8/documents/8f40b558de0548ac97aa61703820c3e4?acc_token=5f58f48da5674b2cb4f489a5e8240849 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "confidentiality": "buyerOnly"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "buyerOnly", 
    "language": "uk", 
    "format": "application/pdf", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/bids/597f8b71d8db469398b44e7a96cbafd8/documents/8f40b558de0548ac97aa61703820c3e4?download=4b2f959ae599443a9a13a865aa48ea41", 
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "title": "Proposal_top_secrets.pdf", 
    "isDescriptionDecision": false, 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "8f40b558de0548ac97aa61703820c3e4", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

