PATCH /api/2.5/tenders/fc67c57b5cdb4a06a99e35bd632b9366/bids/1c1eaf538f1f4fe4adf25d98f1a5eadd/documents/2bc5e0f9340c4aaca323ff0a676bc998?acc_token=eb47ea6ba2de430bbc71e541ce5a3254 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "confidentiality": "buyerOnly"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "buyerOnly", 
    "language": "uk", 
    "format": "application/pdf", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/fc67c57b5cdb4a06a99e35bd632b9366/bids/1c1eaf538f1f4fe4adf25d98f1a5eadd/documents/2bc5e0f9340c4aaca323ff0a676bc998?download=90600f951fae40d6ac133eb2548fdfc4", 
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "title": "Proposal_top_secrets.pdf", 
    "isDescriptionDecision": false, 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "2bc5e0f9340c4aaca323ff0a676bc998", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

