POST /api/2.5/tenders/365920b7e25c4152b9ec963f9d833276/cancellations?acc_token=4ab602baa1514fd2ad22ab15d03f3eb2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/365920b7e25c4152b9ec963f9d833276/cancellations/31918af8488e4933b838906a30813b2c
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2019-03-18T16:25:55.271238+02:00", 
    "cancellationOf": "tender", 
    "id": "31918af8488e4933b838906a30813b2c"
  }
}

