POST /api/2.5/tenders/b7d72feed52443d495445a562a4753fa/qualifications/db65225fe2b04ebf842a22c1156f8211/complaints/179a0214863d4055bacce55d041d4308/documents?acc_token=9d48cb2b109a45fb8687a10c09144319 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 151
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Complaint_Attachement.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/b7d72feed52443d495445a562a4753fa/qualifications/db65225fe2b04ebf842a22c1156f8211/complaints/179a0214863d4055bacce55d041d4308/documents/ac2e7cc0f53c495aa4fd87a38f05322a
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "complaint_owner", 
    "language": "uk", 
    "title": "Complaint_Attachement.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/973415a2fa1843259235eedcc4ce8369?KeyID=a8968c46&Signature=UD%252Bjry4b05xgfeb0V%2F%2FEgAdzPzipMos4DG%252BSeI5HxzkcbD8c2LghAWnWqlryscVZ9ZIY0iHA46ohpqQVmRNcDg%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:30:00+03:00", 
    "id": "ac2e7cc0f53c495aa4fd87a38f05322a", 
    "dateModified": "2019-04-01T01:30:00+03:00"
  }
}

