PATCH /api/2.5/tenders/12945e225d354946b18d02218caf5dc6/qualifications/a66c180e5bb44b2c957e605d257a2eeb/complaints/0dbfbb69240d4631a36160586142a573?acc_token=b4ce5ba2d0d84a57b65bdfb60d78068b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 228
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "stopping", 
    "cancellationReason": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "stopping", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "cancellationReason": "Тендер скасовується замовником", 
    "dateCanceled": "2019-01-01T00:10:00+02:00", 
    "dateAccepted": "2019-01-01T00:10:00+02:00", 
    "dateSubmitted": "2019-01-01T00:10:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.4", 
    "date": "2019-01-01T00:10:00+02:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "0dbfbb69240d4631a36160586142a573"
  }
}

