GET /api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids?acc_token=0d11f7c340f04eb68da346a7b621ccc5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/601166d26167465992ac99a64cdc2f1d?KeyID=b2351eac&Signature=s97Kqu%2FBoD7nLvtYf58ZyHIF9%252BOIxOQzxsrErAzzyAUTuc4Ub7zuVpeUWKpKdyz%2FCvhjmdCJrMkj4yd5cUR%252BDA%253D%253D", 
          "format": "application/pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2018-09-21T05:24:16.279340+03:00", 
          "id": "6833acfe1e5c4f29b78cca7f43eb5d40", 
          "dateModified": "2018-09-21T05:24:16.279382+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "title": "DescriptiveProposal.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids/b5767f4d83754df8bfc04bd54e3dd5a0/documents/cb78fcf969614c249a778ad09364a810?download=113863eddfb846fd8b20d58ca923d0e3", 
          "format": "application/pdf", 
          "isDescriptionDecision": true, 
          "documentOf": "tender", 
          "datePublished": "2018-09-21T05:24:16.439513+03:00", 
          "id": "cb78fcf969614c249a778ad09364a810", 
          "dateModified": "2018-09-21T05:24:16.439564+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids/b5767f4d83754df8bfc04bd54e3dd5a0/documents/3d60e2a7b9574e6b8282f544255b8ac1?download=2a6a97b9257a4d4190e9bfe76920c474", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_top_secrets.pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2018-09-21T05:24:16.760020+03:00", 
          "id": "3d60e2a7b9574e6b8282f544255b8ac1", 
          "dateModified": "2018-09-21T05:24:16.760064+03:00"
        }
      ], 
      "id": "b5767f4d83754df8bfc04bd54e3dd5a0", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "551d2116a66948fdae44b93c84c53b2b", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "selfEligible": true, 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137227", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "selfQualified": true, 
      "id": "07dcf485aa474632a79339aca20d0dd3"
    }, 
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal_part1.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/0d00cb7a43f74d3a955c74dce3338fa4?KeyID=b2351eac&Signature=Qtk8npKy4KUxdJzicv8W9s0KnC7n7kiqt0PnL8h8cAIskwdNb3VeMT9Yj%252Bmy5zFGak6yjehHRw16w1MibNH1Bg%253D%253D", 
          "format": "application/pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2018-09-21T05:24:18.256293+03:00", 
          "id": "e5bffdc3e8d64e48970be21d95f92d2b", 
          "dateModified": "2018-09-21T05:24:18.256329+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids/ec4dccb11d954f329d6fb8f2443c20c5/documents/5799bb944c9a4450be71dfc5211be58c?download=2a0936ed77d143fbbaf43252c7f6703e", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_part2.pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2018-09-21T05:24:18.257337+03:00", 
          "id": "5799bb944c9a4450be71dfc5211be58c", 
          "dateModified": "2018-09-21T05:24:18.257372+03:00"
        }
      ], 
      "id": "ec4dccb11d954f329d6fb8f2443c20c5", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Карпенко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137228", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Кенгуру»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Коцюбинського, 15", 
            "region": "м. Запоріжжя", 
            "locality": "м. Запоріжя"
          }
        }
      ]
    }
  ]
}

