GET /api/2.5/tenders/73c2c3f9cc6349f0a144ed40c9e3dfa7/qualifications HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "a61a2127708340aaad0bf11bb627eb15", 
      "date": "2019-03-28T06:48:33.963111+02:00", 
      "id": "89de66b3ed604d528ac9a2759450bdb9"
    }, 
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "f1c05d51be8842d2838dfcadd6b621e5", 
      "date": "2019-03-28T06:48:33.963301+02:00", 
      "id": "f90c83d810a5417fb9d5416a044db6c4"
    }, 
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "64c69906987a4fe9ab5551011ed3eea8", 
      "date": "2019-03-28T06:48:33.963481+02:00", 
      "id": "0b028c1a213e4800886217243ffde838"
    }, 
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "1df69052c8004ed5ad6d80e969ed7b4c", 
      "date": "2019-03-28T06:48:33.963661+02:00", 
      "id": "c73cbe9e4ed34542a2be130af51f740f"
    }
  ]
}

