PATCH /api/2.5/tenders/4b54c519fdbc4ee69a4fc0f1d1ce346f/qualifications/b0dcc7bb76414ca8b685ec2037c7ca7d/complaints/0cd81d9e1f474f6296956d56e05ec924?acc_token=381e7a05cd25411bb460e73907522342 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "406d9a31c8ac4dc1aba4a1328c67bb70", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2019-04-01T01:30:00+03:00", 
    "complaintID": "UA-2019-04-01-000001.6", 
    "date": "2019-04-01T01:30:00+03:00", 
    "type": "claim", 
    "id": "0cd81d9e1f474f6296956d56e05ec924"
  }
}

