GET /api/2.5/tenders/73c2c3f9cc6349f0a144ed40c9e3dfa7/bids?acc_token=62a4f7692eab4a6cbb0af2c34f9dd6c0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/ae8a4890e39a4c5089017bb1159db9de?KeyID=17aaf97f&Signature=NftTYYknxTK6BXmWp7gIUjkW8Q%252BZ7IxJCkC8bDXRmfFcBvAI9k8EZfE%2FmHTHULjgcCLpQJ2HFLvmA%252BdAUGNjBw%253D%253D", 
          "format": "application/pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:48:32.807710+02:00", 
          "id": "94bcdc34059f42a78e589d1a8f085a75", 
          "dateModified": "2019-03-28T06:48:32.807722+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "title": "DescriptiveProposal.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/73c2c3f9cc6349f0a144ed40c9e3dfa7/bids/a61a2127708340aaad0bf11bb627eb15/documents/935b980663b74219b1be05ac8ef11f5c?download=4b1cc4708e1a42db8dc31a9ec90afebb", 
          "format": "application/pdf", 
          "isDescriptionDecision": true, 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:48:32.870261+02:00", 
          "id": "935b980663b74219b1be05ac8ef11f5c", 
          "dateModified": "2019-03-28T06:48:32.870277+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/73c2c3f9cc6349f0a144ed40c9e3dfa7/bids/a61a2127708340aaad0bf11bb627eb15/documents/58670c0d126d4ab4ae6bb60f5078b510?download=6be2bcad51b340cd97c62971632bde7b", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_top_secrets.pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:48:33.004476+02:00", 
          "id": "58670c0d126d4ab4ae6bb60f5078b510", 
          "dateModified": "2019-03-28T06:48:33.004494+02:00"
        }
      ], 
      "id": "a61a2127708340aaad0bf11bb627eb15", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "f1c05d51be8842d2838dfcadd6b621e5", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "selfEligible": true, 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137227", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "selfQualified": true, 
      "id": "64c69906987a4fe9ab5551011ed3eea8"
    }, 
    {
      "status": "active", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal_part1.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/7750b0e90ed342378ae26103293031b3?KeyID=17aaf97f&Signature=bCNeyJ5QrOUSu9Aim%2Fsf4aZtgfhuzwHWctG8kYs3jejnImlawcMnslMFYgXBeUPkdxA4YOzg6XMpHDshTpqpCg%253D%253D", 
          "format": "application/pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:48:33.749154+02:00", 
          "id": "1a18c763c52f4e9cba84abb8420906d9", 
          "dateModified": "2019-03-28T06:48:33.749165+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "format": "application/pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/73c2c3f9cc6349f0a144ed40c9e3dfa7/bids/1df69052c8004ed5ad6d80e969ed7b4c/documents/b2d34029d52042be875dc38534caa719?download=8a7e8e9aae274486a596378eb7e8a9c2", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "title": "Proposal_part2.pdf", 
          "isDescriptionDecision": false, 
          "documentOf": "tender", 
          "datePublished": "2019-03-28T06:48:33.749547+02:00", 
          "id": "b2d34029d52042be875dc38534caa719", 
          "dateModified": "2019-03-28T06:48:33.749558+02:00"
        }
      ], 
      "id": "1df69052c8004ed5ad6d80e969ed7b4c", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Карпенко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137228", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Кенгуру»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Коцюбинського, 15", 
            "region": "м. Запоріжжя", 
            "locality": "м. Запоріжя"
          }
        }
      ]
    }
  ]
}

