GET /api/2.5/tenders/12945e225d354946b18d02218caf5dc6/qualifications/a66c180e5bb44b2c957e605d257a2eeb/complaints HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2019-01-01T00:10:00+02:00", 
      "tendererActionDate": "2019-01-01T00:10:00+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "5408339b4dfe436686b6a701583b9aaf", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2019-01-01T00:10:00+02:00", 
      "complaintID": "UA-2019-01-01-000001.1", 
      "date": "2019-01-01T00:10:00+02:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7e9f340d5dde49a4989f123352cb5047?KeyID=d6c48c50&Signature=4c%2FFDqAaTV6%252B1dSNXVfujyGbKqup%252B4vheCwXbL3yip68OPV%2FDbA0aA9y9EAWz3MQwRHDuBIj11YQpKjc6rxRCQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-01-01T00:10:00+02:00", 
          "id": "414eb8e4314745e0a42e3866ae617c99", 
          "dateModified": "2019-01-01T00:10:00+02:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4c85c87fd3f240939213f8467966b5df?KeyID=d6c48c50&Signature=vWvs3s%2FhylHtGam7OTZWtofmGsPHmFUsNVPK0zTpOOLf3ckZ0HAKQtcUa9C5xhHKXQOJ5v4sEUcLvDlscRlVAg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-01-01T00:10:00+02:00", 
          "id": "e496ee4abb3f41b88ae2519876a147a6", 
          "dateModified": "2019-01-01T00:10:00+02:00"
        }
      ], 
      "dateAccepted": "2019-01-01T00:10:00+02:00"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2019-01-01T00:10:00+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2019-01-01T00:10:00+02:00", 
      "complaintID": "UA-2019-01-01-000001.2", 
      "date": "2019-01-01T00:10:00+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "136e9d12158840e98f28d66b066b8e75"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2019-01-01T00:10:00+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2019-01-01T00:10:00+02:00", 
      "dateSubmitted": "2019-01-01T00:10:00+02:00", 
      "complaintID": "UA-2019-01-01-000001.3", 
      "date": "2019-01-01T00:10:00+02:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "e2969a0254174b7ca6f75e0ea28cbe70"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-01-01T00:10:00+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2019-01-01T00:10:00+02:00", 
      "dateAccepted": "2019-01-01T00:10:00+02:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-01-01T00:10:00+02:00", 
      "complaintID": "UA-2019-01-01-000001.4", 
      "date": "2019-01-01T00:10:00+02:00", 
      "type": "complaint", 
      "id": "0dbfbb69240d4631a36160586142a573"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-01-01T00:10:00+02:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2019-01-01T00:10:00+02:00", 
      "dateAccepted": "2019-01-01T00:10:00+02:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-01-01T00:10:00+02:00", 
      "complaintID": "UA-2019-01-01-000001.5", 
      "date": "2019-01-01T00:10:00+02:00", 
      "type": "complaint", 
      "id": "239ed802bc50466da70a808e125bc094"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "bid_id": "c4d4d3b2df634e059a04dc4d28eeb26a", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2019-01-01T00:10:00+02:00", 
      "complaintID": "UA-2019-01-01-000001.6", 
      "date": "2019-01-01T00:10:00+02:00", 
      "type": "claim", 
      "id": "43e372b7d9824331a66d80218a244414"
    }
  ]
}

