PATCH /api/2.5/tenders/7288daeb2b3b43d289b0d0ac8dc5f68a/qualifications/168271bb27664510a98129b34a38c996/complaints/1a43acfa83d249029109105aaad393e3 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "accepted"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "accepted", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "complaint_owner", 
        "language": "uk", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/13a58a6c05634c369d2ec866069c2039?KeyID=87b1c89b&Signature=qqdAGxHMDp9bU%252BLYUnl7i%252Bij1ikSHutt4IBhWXSwLmt2uccav1A3gNjHdoqrBXB5OoInGVrh6pLPUPhymQ8EBQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:26:31.169573+02:00", 
        "id": "2c855bb4e02b41ce80da7c9941367c3d", 
        "dateModified": "2019-03-18T16:26:31.169603+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "dateAccepted": "2019-03-18T16:26:34.362493+02:00", 
    "dateSubmitted": "2019-03-18T16:26:31.487733+02:00", 
    "complaintID": "UA-2019-03-18-000001.1", 
    "date": "2019-03-18T16:26:34.394687+02:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "1a43acfa83d249029109105aaad393e3"
  }
}

