POST /api/2.5/tenders/4b54c519fdbc4ee69a4fc0f1d1ce346f/qualifications/b0dcc7bb76414ca8b685ec2037c7ca7d/complaints/37c218519bd04153ac22938c0a7e6df4/documents HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 149
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="ComplaintResolution.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/4b54c519fdbc4ee69a4fc0f1d1ce346f/qualifications/b0dcc7bb76414ca8b685ec2037c7ca7d/complaints/37c218519bd04153ac22938c0a7e6df4/documents/6ce2294e2adb44ba904ccc2e62fe6d2b
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "aboveThresholdReviewers", 
    "language": "uk", 
    "title": "ComplaintResolution.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7f2c0d5bec654a19865e583db1f69403?KeyID=a8968c46&Signature=qjvVaxFb6l0fLYXfSBUMBC1RmkiQW9nOL9UfCmVNB4Qo43lfm63JiiVeKGvxXRxs7KPqZ91oE%2FCFzL9kjzivCA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:30:00+03:00", 
    "id": "6ce2294e2adb44ba904ccc2e62fe6d2b", 
    "dateModified": "2019-04-01T01:30:00+03:00"
  }
}

