PATCH /api/2.5/tenders/12945e225d354946b18d02218caf5dc6/qualifications/a66c180e5bb44b2c957e605d257a2eeb/complaints/43e372b7d9824331a66d80218a244414?acc_token=2499831972424723b2478d3e60cdee98 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "c4d4d3b2df634e059a04dc4d28eeb26a", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2019-01-01T00:10:00+02:00", 
    "complaintID": "UA-2019-01-01-000001.6", 
    "date": "2019-01-01T00:10:00+02:00", 
    "type": "claim", 
    "id": "43e372b7d9824331a66d80218a244414"
  }
}

