GET /api/2.4/tenders/949b7170af7e4ea89d62bf58cf40e7d0/qualifications/31dae56814614f879585ab1d8d93175d/complaints HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2018-09-21T05:24:09.445756+03:00", 
      "tendererActionDate": "2018-09-21T05:24:10.302551+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "c54e8db270f34218a938604c7406ac1e", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2018-09-21T05:24:06.358826+03:00", 
      "complaintID": "UA-2018-09-21-000001.1", 
      "date": "2018-09-21T05:24:10.312404+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/a8e6f100dae8446cb32419fb1d22ad5a?KeyID=90f5593d&Signature=23qRV65GvQbI4%2Fb0pP5iTYmI%252BzHRMHGnuEC9Jv4sTn9TMAz8on4l5qTHvQUDC%252BWNSuLwxV78kqoi0%2FmBwzILCg%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-09-21T05:24:06.166488+03:00", 
          "id": "005be3c9f718457d962da82372ac41a2", 
          "dateModified": "2018-09-21T05:24:06.166542+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public.docs-sandbox.openprocurement.org/get/78ab34b22f904c8687ae2f693b2fecd5?KeyID=90f5593d&Signature=6%252BQ5KAktVlzfMCE2fyhNP%252B1InwEeV6%2F02qX1FIdnOHj7TQy0Hl2CaMR4QmDQxt7mnnSaT54yp89OxTNMsXIBCA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2018-09-21T05:24:09.155192+03:00", 
          "id": "7eaa7f263ea54f148b51407f4b56c170", 
          "dateModified": "2018-09-21T05:24:09.155276+03:00"
        }
      ], 
      "dateAccepted": "2018-09-21T05:24:08.127745+03:00"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2018-09-21T05:24:07.841776+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2018-09-21T05:24:06.545823+03:00", 
      "complaintID": "UA-2018-09-21-000001.2", 
      "date": "2018-09-21T05:24:07.852571+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "4a29b4f2b6c6416a99adbd73f72bea88"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2018-09-21T05:24:09.705098+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2018-09-21T05:24:08.414387+03:00", 
      "dateSubmitted": "2018-09-21T05:24:06.738462+03:00", 
      "complaintID": "UA-2018-09-21-000001.3", 
      "date": "2018-09-21T05:24:09.715292+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "8eaa74b876794fb3ac70f0cdfed0a159"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-09-21T05:24:10.855039+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2018-09-21T05:24:10.589309+03:00", 
      "dateAccepted": "2018-09-21T05:24:08.671445+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-09-21T05:24:06.934635+03:00", 
      "complaintID": "UA-2018-09-21-000001.4", 
      "date": "2018-09-21T05:24:10.872252+03:00", 
      "type": "complaint", 
      "id": "87f3b8e7850542d188ce5581204426bd"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2018-09-21T05:24:09.977813+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2018-09-21T05:24:09.977874+03:00", 
      "dateAccepted": "2018-09-21T05:24:08.915781+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2018-09-21T05:24:07.149812+03:00", 
      "complaintID": "UA-2018-09-21-000001.5", 
      "date": "2018-09-21T05:24:09.988333+03:00", 
      "type": "complaint", 
      "id": "994ad9619fe94585b1318d32f44fd7ce"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "bid_id": "4e5cf2a4c2874309817899ab0f6680a5", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2018-09-21T05:24:07.597144+03:00", 
      "complaintID": "UA-2018-09-21-000001.6", 
      "date": "2018-09-21T05:24:07.607135+03:00", 
      "type": "claim", 
      "id": "707d5238e78b4634a6121f7719a0e4c6"
    }
  ]
}

