GET /api/2.5/tenders/d0fb203f920043de865a7f95960754e6/qualifications HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "1ed39182ee004710b81381117ac43978", 
      "date": "2019-04-01T01:00:00+03:00", 
      "id": "20c2d93f7b254986a1fa2111cedf20b7"
    }, 
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "57a48bcebac14db3a1d0720a67d0182e", 
      "date": "2019-04-01T01:00:00+03:00", 
      "id": "139860f367224d6f8743fc6d09f81120"
    }, 
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "1bb8a19131484ea686779682c1cd5117", 
      "date": "2019-04-01T01:00:00+03:00", 
      "id": "74ae5d592559459f9fa9dabc974885b0"
    }, 
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "83e5b543d67842b3a2289769af78b4e7", 
      "date": "2019-04-01T01:00:00+03:00", 
      "id": "fd400d4b238f4f00b9501461f06ab62a"
    }
  ]
}

