PATCH /api/2.5/tenders/5133e89c95af4bea9a9c805c6e02f950/qualifications/7062a8144cf74f999eff42e04151db9b/complaints/0385c1753bf24865b5fdda93ba0e4523?acc_token=0a2ecf53760f423a980654773013a880 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 228
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "stopping", 
    "cancellationReason": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "stopping", 
    "transfer_token": "f0688d26642a9016f57f7dc661a47576ade14a4072b5eae7e6aff54d5958a29bb851f4b570230631577c0fba63423d5f995acc1bbe1178ecb5027e7680e65780", 
    "title": "Недостатньо інформації", 
    "acceptance": true, 
    "cancellationReason": "Тендер скасовується замовником", 
    "dateCanceled": "2019-04-01T01:00:03+03:00", 
    "dateAccepted": "2019-04-01T01:00:03+03:00", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00137256", 
        "uri": "http://www.sc.gov.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateSubmitted": "2019-04-01T01:00:03+03:00", 
    "complaintID": "UA-2019-04-01-000001.4", 
    "date": "2019-04-01T01:00:03+03:00", 
    "type": "complaint", 
    "id": "0385c1753bf24865b5fdda93ba0e4523", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс."
  }
}

