POST /api/2.5/tenders/4b1ccbca40fa4d84989dd960e3e28fe9/qualifications/4ab71f5d25bc440080e7816de5d7c490/complaints?acc_token=f085fcf08e534af29a6272e999af24eb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1682
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "author": {
      "contactPoint": {
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк", 
        "email": "soleksuk@gmail.com"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "21100", 
        "region": "м. Вінниця", 
        "streetAddress": "вул. Островського, 33", 
        "locality": "м. Вінниця"
      }
    }, 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/4b1ccbca40fa4d84989dd960e3e28fe9/qualifications/4ab71f5d25bc440080e7816de5d7c490/complaints/f3c709fe83c34dd096a57952c1689ba0
{
  "access": {
    "token": "23cd8180151843ec924d7b23159c0a86"
  }, 
  "data": {
    "status": "draft", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "5e6ca43ade2e409b91f1570ba7388076", 
    "complaintID": "UA-2019-03-28-000001.1", 
    "date": "2019-03-28T06:48:28.690361+02:00", 
    "type": "claim", 
    "id": "f3c709fe83c34dd096a57952c1689ba0"
  }
}

