GET /api/2.5/tenders/636f8ed2b38c43ceb7d481bb2c0bf72b/qualifications HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "5456ed6a72344945a29facb0b378690e", 
      "date": "2019-03-18T16:27:07.542550+02:00", 
      "id": "f0a4d10952824b65a9d29ca11008c99b"
    }, 
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "e8d143208cac46ad8979ba5e12cba695", 
      "date": "2019-03-18T16:27:07.543033+02:00", 
      "id": "9325615472f445e289092cb982fdd82e"
    }, 
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "845508b14c9641d2b120ea3bf3b9a1ad", 
      "date": "2019-03-18T16:27:07.543578+02:00", 
      "id": "3f5eac8cf113475ea48690de015e8ff7"
    }, 
    {
      "status": "pending", 
      "eligible": false, 
      "qualified": false, 
      "bidID": "a50e242b14f040a292bda644bedf3f11", 
      "date": "2019-03-18T16:27:07.547806+02:00", 
      "id": "e39399f6d27a40138180960062fa951c"
    }
  ]
}

