PATCH /api/2.4/tenders/949b7170af7e4ea89d62bf58cf40e7d0/qualifications/31dae56814614f879585ab1d8d93175d/complaints/87f3b8e7850542d188ce5581204426bd?acc_token=0e79dd5ce3e7441bad17b40b17c74bfa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 228
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "stopping", 
    "cancellationReason": "Тендер скасовується замовником"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "stopping", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "acceptance": true, 
    "cancellationReason": "Тендер скасовується замовником", 
    "dateCanceled": "2018-09-21T05:24:10.589309+03:00", 
    "dateAccepted": "2018-09-21T05:24:08.671445+03:00", 
    "dateSubmitted": "2018-09-21T05:24:06.934635+03:00", 
    "complaintID": "UA-2018-09-21-000001.4", 
    "date": "2018-09-21T05:24:10.600098+03:00", 
    "title": "Недостатньо інформації", 
    "type": "complaint", 
    "id": "87f3b8e7850542d188ce5581204426bd"
  }
}

