PATCH /api/2.5/tenders/4b1ccbca40fa4d84989dd960e3e28fe9/qualifications/4ab71f5d25bc440080e7816de5d7c490/complaints/5348f3093f954baf800ab5829118b4f2?acc_token=ea1330f4738f4c62b1fe41c1b7fe2982 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 150
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "cancelled", 
    "cancellationReason": "Умови виправлено"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "cancelled", 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "bid_id": "5e6ca43ade2e409b91f1570ba7388076", 
    "cancellationReason": "Умови виправлено", 
    "dateCanceled": "2019-03-28T06:48:29.437532+02:00", 
    "complaintID": "UA-2019-03-28-000001.6", 
    "date": "2019-03-28T06:48:29.444344+02:00", 
    "type": "claim", 
    "id": "5348f3093f954baf800ab5829118b4f2"
  }
}

