GET /api/2.5/tenders/4b54c519fdbc4ee69a4fc0f1d1ce346f/qualifications/b0dcc7bb76414ca8b685ec2037c7ca7d/complaints HTTP/1.0
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "resolved", 
      "dateDecision": "2019-04-01T01:30:00+03:00", 
      "tendererActionDate": "2019-04-01T01:30:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "title": "Недостатньо інформації", 
      "id": "37c218519bd04153ac22938c0a7e6df4", 
      "tendererAction": "Умови виправлено", 
      "dateSubmitted": "2019-04-01T01:30:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.1", 
      "date": "2019-04-01T01:30:00+03:00", 
      "acceptance": true, 
      "type": "complaint", 
      "documents": [
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "complaint_owner", 
          "language": "uk", 
          "title": "Complaint_Attachement.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/bb49906084b049198be0971b791a6331?KeyID=a8968c46&Signature=KG1JMIZ4967D4rhWb5X22D97qyFiKQBerV6B%2Fg3mFKftFNGnYgy2kdkNwEHHM1wK0w%2FXjE%252BG1yv5JFZSCyx9AQ%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:30:00+03:00", 
          "id": "8e946d08269848a3b4f36e21cbce1d84", 
          "dateModified": "2019-04-01T01:30:00+03:00"
        }, 
        {
          "hash": "md5:00000000000000000000000000000000", 
          "author": "aboveThresholdReviewers", 
          "language": "uk", 
          "title": "ComplaintResolution.pdf", 
          "url": "http://public-docs-sandbox.prozorro.gov.ua/get/7f2c0d5bec654a19865e583db1f69403?KeyID=a8968c46&Signature=qjvVaxFb6l0fLYXfSBUMBC1RmkiQW9nOL9UfCmVNB4Qo43lfm63JiiVeKGvxXRxs7KPqZ91oE%2FCFzL9kjzivCA%253D%253D", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2019-04-01T01:30:00+03:00", 
          "id": "6ce2294e2adb44ba904ccc2e62fe6d2b", 
          "dateModified": "2019-04-01T01:30:00+03:00"
        }
      ], 
      "dateAccepted": "2019-04-01T01:30:00+03:00"
    }, 
    {
      "status": "invalid", 
      "dateDecision": "2019-04-01T01:30:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": false, 
      "dateSubmitted": "2019-04-01T01:30:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.2", 
      "date": "2019-04-01T01:30:00+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "3610b3e785804b0b9593a59b4a310eb2"
    }, 
    {
      "status": "declined", 
      "dateDecision": "2019-04-01T01:30:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "acceptance": true, 
      "dateAccepted": "2019-04-01T01:30:00+03:00", 
      "dateSubmitted": "2019-04-01T01:30:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.3", 
      "date": "2019-04-01T01:30:00+03:00", 
      "title": "Недостатньо інформації", 
      "type": "complaint", 
      "id": "c207dd09a5bb44d6a85f2af31c455f94"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-04-01T01:30:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "cancellationReason": "Тендер скасовується замовником", 
      "dateCanceled": "2019-04-01T01:30:00+03:00", 
      "dateAccepted": "2019-04-01T01:30:00+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-04-01T01:30:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.4", 
      "date": "2019-04-01T01:30:00+03:00", 
      "type": "complaint", 
      "id": "ffea51ed3bda4c12937e3c8ea788b4b5"
    }, 
    {
      "status": "stopped", 
      "dateDecision": "2019-04-01T01:30:00+03:00", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "decision": "Тендер скасовується замовником", 
      "acceptance": true, 
      "dateCanceled": "2019-04-01T01:30:00+03:00", 
      "dateAccepted": "2019-04-01T01:30:00+03:00", 
      "author": {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }, 
      "dateSubmitted": "2019-04-01T01:30:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.5", 
      "date": "2019-04-01T01:30:00+03:00", 
      "type": "complaint", 
      "id": "57e7da65f3f34fd7a0d5c418b4cdb75c"
    }, 
    {
      "status": "cancelled", 
      "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
      "title": "Недостатньо інформації", 
      "bid_id": "406d9a31c8ac4dc1aba4a1328c67bb70", 
      "cancellationReason": "Умови виправлено", 
      "dateCanceled": "2019-04-01T01:30:00+03:00", 
      "complaintID": "UA-2019-04-01-000001.6", 
      "date": "2019-04-01T01:30:00+03:00", 
      "type": "claim", 
      "id": "0cd81d9e1f474f6296956d56e05ec924"
    }
  ]
}

