POST /api/2.5/tenders/fc67c57b5cdb4a06a99e35bd632b9366/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 727
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "selfEligible": true, 
    "selfQualified": true, 
    "value": {
      "amount": 5
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137227", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 35", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/fc67c57b5cdb4a06a99e35bd632b9366/bids/997a3c2c741d4d6ead1de39877e3dffa
{
  "access": {
    "token": "8bb4bf5c2b6b4c6cbd044f1d08dd6b97"
  }, 
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Іваненко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137227", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Снігур»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 35", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "997a3c2c741d4d6ead1de39877e3dffa"
  }
}

