POST /api/2.5/tenders/73c2c3f9cc6349f0a144ed40c9e3dfa7/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1556
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/7750b0e90ed342378ae26103293031b3?KeyID=17aaf97f&Signature=4LKc2LD1qPA4%2FaaA7eMQlO3y0ZyPjybKsgLu6%2FoMIPGgz1J8hZw4ugYn3uKTvBKvtK3c33Aana9NrtHQzuKdCg%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "title": "Proposal_part2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/8a7e8e9aae274486a596378eb7e8a9c2?KeyID=17aaf97f&Signature=97SVbRodu5SZaPscSdYqvGKWwCC2pN4acOrsMuuDvvwSL7yGua%2FLkmr3eHvP69hdjmv867JCrqV1hNCWYHJ6DQ%3D%3D", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf"
      }
    ], 
    "selfQualified": true, 
    "value": {
      "amount": 5
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Карпенко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Запоріжжя", 
          "streetAddress": "вул. Коцюбинського, 15", 
          "locality": "м. Запоріжя"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.5/tenders/73c2c3f9cc6349f0a144ed40c9e3dfa7/bids/1df69052c8004ed5ad6d80e969ed7b4c
{
  "access": {
    "token": "fa0f5a6287d84c5e9ab0c0e4cbff8ed0"
  }, 
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/73c2c3f9cc6349f0a144ed40c9e3dfa7/bids/1df69052c8004ed5ad6d80e969ed7b4c/documents/1a18c763c52f4e9cba84abb8420906d9?download=7750b0e90ed342378ae26103293031b3", 
        "format": "application/pdf", 
        "isDescriptionDecision": false, 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:48:33.749154+02:00", 
        "id": "1a18c763c52f4e9cba84abb8420906d9", 
        "dateModified": "2019-03-28T06:48:33.749165+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/tenders/73c2c3f9cc6349f0a144ed40c9e3dfa7/bids/1df69052c8004ed5ad6d80e969ed7b4c/documents/b2d34029d52042be875dc38534caa719?download=8a7e8e9aae274486a596378eb7e8a9c2", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "isDescriptionDecision": false, 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:48:33.749547+02:00", 
        "id": "b2d34029d52042be875dc38534caa719", 
        "dateModified": "2019-03-28T06:48:33.749558+02:00"
      }
    ], 
    "selfEligible": true, 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Карпенко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Коцюбинського, 15", 
          "region": "м. Запоріжжя", 
          "locality": "м. Запоріжя"
        }
      }
    ], 
    "date": "2019-03-28T06:48:33.748785+02:00", 
    "id": "1df69052c8004ed5ad6d80e969ed7b4c"
  }
}

