POST /api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1568
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "documents": [
      {
        "url": "http://public.docs-sandbox.openprocurement.org/get/0d00cb7a43f74d3a955c74dce3338fa4?KeyID=b2351eac&Signature=HHyCAlJhmMlb4Yn7%2FX2NeTXZu0FovH88PxbhdUOMq2dnvhkL%2BTycAfKgXQdzO6v%2Fnoc8%2FLyFHKK5CE4Ez2QTCQ%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "title": "Proposal_part2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/2a0936ed77d143fbbaf43252c7f6703e?KeyID=b2351eac&Signature=fVxNKk4Iv%2BYdCJ5orkOLdr%2BGd%2BdbunLUNbHQqBxa58ZovPAE2Ef7MFPnfGw%2FMpb0plwlJwPsgzDMh%2F6B30fNBA%3D%3D", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf"
      }
    ], 
    "selfQualified": true, 
    "value": {
      "amount": 5
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Карпенко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Запоріжжя", 
          "streetAddress": "вул. Коцюбинського, 15", 
          "locality": "м. Запоріжя"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://api-sandbox.openprocurement.org/api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids/ec4dccb11d954f329d6fb8f2443c20c5
{
  "access": {
    "token": "459f40070e61474bbc163c057705aeb1"
  }, 
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids/ec4dccb11d954f329d6fb8f2443c20c5/documents/e5bffdc3e8d64e48970be21d95f92d2b?download=0d00cb7a43f74d3a955c74dce3338fa4", 
        "format": "application/pdf", 
        "isDescriptionDecision": false, 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:24:18.256293+03:00", 
        "id": "e5bffdc3e8d64e48970be21d95f92d2b", 
        "dateModified": "2018-09-21T05:24:18.256329+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids/ec4dccb11d954f329d6fb8f2443c20c5/documents/5799bb944c9a4450be71dfc5211be58c?download=2a0936ed77d143fbbaf43252c7f6703e", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "isDescriptionDecision": false, 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:24:18.257337+03:00", 
        "id": "5799bb944c9a4450be71dfc5211be58c", 
        "dateModified": "2018-09-21T05:24:18.257372+03:00"
      }
    ], 
    "selfEligible": true, 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Карпенко"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "«Кенгуру»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Коцюбинського, 15", 
          "region": "м. Запоріжжя", 
          "locality": "м. Запоріжя"
        }
      }
    ], 
    "date": "2018-09-21T05:24:18.255130+03:00", 
    "id": "ec4dccb11d954f329d6fb8f2443c20c5"
  }
}

