POST /api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 1574
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "selfEligible": true, 
    "documents": [
      {
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/4aa91964cb8947fd98b1e569afbe848b?KeyID=a8968c46&Signature=yhsEg5r4%2FemwDMsdU31uip3Q99gHmDcxGN9JEyTv3Io3kjW%2FkfPl0rNsvRF059mxXbx8OGobkWQzoQxgSUdkAA%3D%3D", 
        "title": "Proposal_part1.pdf", 
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "format": "application/pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/5d176ddeade14bbb9d1e5cd6e1086939?KeyID=a8968c46&Signature=CyMGQeepdX8237S%2BrN4%2Fo9IZIqvfQbknGMmT%2FNDGMJO2GlYcNnUJWEWExSvj7JxUdqpTqLI%2BoYkf%2FvJctzPICg%3D%3D", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf"
      }
    ], 
    "selfQualified": true, 
    "value": {
      "amount": 5
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "name": "Іван Карпенко", 
          "telephone": "+380 (322) 12-34-56"
        }, 
        "scale": "large", 
        "name": "«Кенгуру»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Запоріжжя", 
          "streetAddress": "вул. Коцюбинського, 15", 
          "locality": "м. Запоріжя"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/bids/c083b93126884fb490faca2f53a547bb
{
  "access": {
    "token": "2d0347734f754723a63e69ea4e351c3a"
  }, 
  "data": {
    "status": "pending", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal_part1.pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/bids/c083b93126884fb490faca2f53a547bb/documents/7ccbaa50b58e4986b57c8c5a9975107d?download=4aa91964cb8947fd98b1e569afbe848b", 
        "format": "application/pdf", 
        "isDescriptionDecision": false, 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "7ccbaa50b58e4986b57c8c5a9975107d", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "format": "application/pdf", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/bids/c083b93126884fb490faca2f53a547bb/documents/c5dcf3d6ce584bb89bcc091f2f1a0378?download=5d176ddeade14bbb9d1e5cd6e1086939", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "title": "Proposal_part2.pdf", 
        "isDescriptionDecision": false, 
        "documentOf": "tender", 
        "datePublished": "2019-04-01T01:00:00+03:00", 
        "id": "c5dcf3d6ce584bb89bcc091f2f1a0378", 
        "dateModified": "2019-04-01T01:00:00+03:00"
      }
    ], 
    "selfEligible": true, 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "fake@mail.com", 
          "telephone": "+380 (322) 12-34-56", 
          "name": "Іван Карпенко"
        }, 
        "scale": "large", 
        "name": "«Кенгуру»", 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137228", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Коцюбинського, 15", 
          "region": "м. Запоріжжя", 
          "locality": "м. Запоріжя"
        }
      }
    ], 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "c083b93126884fb490faca2f53a547bb"
  }
}

