PATCH /api/2.5/tenders/fc67c57b5cdb4a06a99e35bd632b9366/qualifications/eec9783eade24408864519fbaa84c51d?acc_token=170761b45ca447fd912a2e36a9379c91 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "eligible": false, 
    "qualified": false, 
    "bidID": "997a3c2c741d4d6ead1de39877e3dffa", 
    "date": "2019-01-01T00:00:00+02:00", 
    "id": "eec9783eade24408864519fbaa84c51d"
  }
}

