PATCH /api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/qualifications/c507dabcc2c84cf19d20389404d9fe1d?acc_token=57e796bd207d4695964c4d14060285c7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "eligible": false, 
    "qualified": false, 
    "bidID": "8a1a5a06de004862b4809d24cb2fed4f", 
    "date": "2019-04-01T01:00:00+03:00", 
    "id": "c507dabcc2c84cf19d20389404d9fe1d"
  }
}

