PATCH /api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef?acc_token=0d11f7c340f04eb68da346a7b621ccc5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 45
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active.stage2.waiting"
  }
}

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.stage2.waiting", 
    "complaintPeriod": {
      "startDate": "2018-08-11T05:23:23.418725+03:00", 
      "endDate": "2018-09-07T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2018-08-11T05:23:23.418725+03:00", 
      "clarificationsUntil": "2018-09-06T00:00:00+03:00", 
      "endDate": "2018-09-01T05:23:23.418725+03:00", 
      "invalidationDate": "2018-09-21T05:24:17.446315+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "00137226", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Калорійність", 
        "date": "2018-09-21T05:24:14.841381+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "dateAnswered": "2018-09-21T05:24:14.970351+03:00", 
        "id": "490d85ae17f7415599576e76100a9c83", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "d72e2cfe05454662b4b0a96b587436ef", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/bb9ebac07fcb405b9dcb58b24d1125a2?KeyID=b2351eac&Signature=KBKw8HLtQ2QMbReuT3qxDOZfznfj%2FDBsNxg4f3J4Bs7D3owiV2JADSwvWN8cLty%252BXOQM0gboJNpncdvB2xxzAg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:24:14.312205+03:00", 
        "id": "83a79169fe12488bb32a6de37c52e453", 
        "dateModified": "2018-09-21T05:24:14.312254+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/5f1362258dd94c999ed1b4381dd42b6e?KeyID=b2351eac&Signature=BC%252BiYAropPp40ozjWV76SkpBFMmjGB6wkxpEqARXEd%252BZFPHlP54JwVtn5BdKR7v5FQ3SY5yq1lPW1MC5RdNsBQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:24:14.515656+03:00", 
        "id": "1f9e9ac97f124f9bac712938a8c0b8bd", 
        "dateModified": "2018-09-21T05:24:14.515702+03:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/c8c94ef7c45545c18e4b56eb2e42f269?KeyID=b2351eac&Signature=AwfRrKC5YcmHZLsF4lCzjQkS7fAvcjthVAyd3Bz%252BFAvo6R63l5a4C1P3Hw6M0Ls8bD45w3W%2FrN4GNpWNmBZ1DA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-09-21T05:24:14.515656+03:00", 
        "id": "1f9e9ac97f124f9bac712938a8c0b8bd", 
        "dateModified": "2018-09-21T05:24:14.681650+03:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2018-09-11T05:23:23.418725+03:00", 
      "endDate": "2018-09-21T05:23:23.418725+03:00"
    }, 
    "tenderID": "UA-2018-09-21-000001", 
    "dateModified": "2018-09-21T05:24:21.902348+03:00", 
    "numberOfBids": 3, 
    "tenderPeriod": {
      "startDate": "2018-08-11T05:23:23.418725+03:00", 
      "endDate": "2018-09-11T05:23:23.418725+03:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "b5767f4d83754df8bfc04bd54e3dd5a0", 
        "date": "2018-09-21T05:24:19.233336+03:00", 
        "id": "990ce8fb4a3343e98425d97a5363f591"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "551d2116a66948fdae44b93c84c53b2b", 
        "date": "2018-09-21T05:24:19.450643+03:00", 
        "id": "4388a6e9cf6b47dc8544d020224099b4"
      }, 
      {
        "status": "unsuccessful", 
        "eligible": false, 
        "qualified": false, 
        "bidID": "07dcf485aa474632a79339aca20d0dd3", 
        "date": "2018-09-21T05:24:19.685722+03:00", 
        "id": "4b76e828831e4e1caeb6259ac7e6441f"
      }, 
      {
        "status": "active", 
        "eligible": true, 
        "qualified": true, 
        "bidID": "ec4dccb11d954f329d6fb8f2443c20c5", 
        "date": "2018-09-21T05:24:19.928139+03:00", 
        "id": "4597544504b1463a8522c1bd0a7ff742"
      }
    ], 
    "procurementMethodType": "competitiveDialogueEU", 
    "date": "2018-09-21T05:24:21.902348+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-10-11T05:23:23.453649+03:00", 
          "endDate": "2018-11-10T05:23:23.453757+03:00"
        }, 
        "id": "17450abf040b4175bc20d32d08751636", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-10-11T05:23:23.453794+03:00", 
          "endDate": "2018-11-10T05:23:23.453817+03:00"
        }, 
        "id": "c8fd2d6a12924049a184a27b678d4f14", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/601166d26167465992ac99a64cdc2f1d?KeyID=b2351eac&Signature=s97Kqu%2FBoD7nLvtYf58ZyHIF9%252BOIxOQzxsrErAzzyAUTuc4Ub7zuVpeUWKpKdyz%2FCvhjmdCJrMkj4yd5cUR%252BDA%253D%253D", 
            "format": "application/pdf", 
            "isDescriptionDecision": false, 
            "documentOf": "tender", 
            "datePublished": "2018-09-21T05:24:16.279340+03:00", 
            "id": "6833acfe1e5c4f29b78cca7f43eb5d40", 
            "dateModified": "2018-09-21T05:24:16.279382+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "title": "DescriptiveProposal.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids/b5767f4d83754df8bfc04bd54e3dd5a0/documents/cb78fcf969614c249a778ad09364a810?download=113863eddfb846fd8b20d58ca923d0e3", 
            "format": "application/pdf", 
            "isDescriptionDecision": true, 
            "documentOf": "tender", 
            "datePublished": "2018-09-21T05:24:16.439513+03:00", 
            "id": "cb78fcf969614c249a778ad09364a810", 
            "dateModified": "2018-09-21T05:24:16.439564+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids/b5767f4d83754df8bfc04bd54e3dd5a0/documents/3d60e2a7b9574e6b8282f544255b8ac1?download=2a6a97b9257a4d4190e9bfe76920c474", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_top_secrets.pdf", 
            "isDescriptionDecision": false, 
            "documentOf": "tender", 
            "datePublished": "2018-09-21T05:24:16.760020+03:00", 
            "id": "3d60e2a7b9574e6b8282f544255b8ac1", 
            "dateModified": "2018-09-21T05:24:16.760064+03:00"
          }
        ], 
        "id": "b5767f4d83754df8bfc04bd54e3dd5a0", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "551d2116a66948fdae44b93c84c53b2b", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "unsuccessful", 
        "id": "07dcf485aa474632a79339aca20d0dd3", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137227", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "active", 
        "documents": [
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal_part1.pdf", 
            "url": "http://public.docs-sandbox.openprocurement.org/get/0d00cb7a43f74d3a955c74dce3338fa4?KeyID=b2351eac&Signature=Qtk8npKy4KUxdJzicv8W9s0KnC7n7kiqt0PnL8h8cAIskwdNb3VeMT9Yj%252Bmy5zFGak6yjehHRw16w1MibNH1Bg%253D%253D", 
            "format": "application/pdf", 
            "isDescriptionDecision": false, 
            "documentOf": "tender", 
            "datePublished": "2018-09-21T05:24:18.256293+03:00", 
            "id": "e5bffdc3e8d64e48970be21d95f92d2b", 
            "dateModified": "2018-09-21T05:24:18.256329+03:00"
          }, 
          {
            "hash": "md5:00000000000000000000000000000000", 
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "format": "application/pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.4/tenders/d72e2cfe05454662b4b0a96b587436ef/bids/ec4dccb11d954f329d6fb8f2443c20c5/documents/5799bb944c9a4450be71dfc5211be58c?download=2a0936ed77d143fbbaf43252c7f6703e", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "title": "Proposal_part2.pdf", 
            "isDescriptionDecision": false, 
            "documentOf": "tender", 
            "datePublished": "2018-09-21T05:24:18.257337+03:00", 
            "id": "5799bb944c9a4450be71dfc5211be58c", 
            "dateModified": "2018-09-21T05:24:18.257372+03:00"
          }
        ], 
        "id": "ec4dccb11d954f329d6fb8f2443c20c5", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Карпенко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137228", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Кенгуру»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Коцюбинського, 15", 
              "region": "м. Запоріжжя", 
              "locality": "м. Запоріжя"
            }
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

