GET /api/2.5/tenders/636f8ed2b38c43ceb7d481bb2c0bf72b/documents?acc_token=53dd6cedd9bf46d59d2ec79baf9bd876 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/d4ecdf49e0364887b370ecf0c6a653b1?KeyID=c7d5e428&Signature=9R1Y8k4%252BxqPEygC61j%252Bskn7IGVwet5mxxB7IhTQFeKANVm6o1WK3z5trmFPJ1RvzqlboPwuOPpE6LWKidM0sCQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-03-18T16:26:53.615730+02:00", 
      "id": "21ec916b17d24661a33fb80abf3a77bd", 
      "dateModified": "2019-03-18T16:26:53.615825+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria.pdf", 
      "url": "http://public.docs-sandbox.openprocurement.org/get/0efea23700bc412590d9a3be0b5ecd09?KeyID=c7d5e428&Signature=cH4WgoHVWHVukl79XPDJpxex6%252Bqs6TJSQR1Qkt0BPCtKiuIIHWJ2wSp6B2t98W%252BE6Ds7%252B8x%2FPfStqszJ5A9xCQ%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-03-18T16:26:54.221780+02:00", 
      "id": "6c0cf8c1c0b44e12a74e8691cfecd451", 
      "dateModified": "2019-03-18T16:26:54.222769+02:00"
    }
  ]
}

