GET /api/2.5/tenders/fc67c57b5cdb4a06a99e35bd632b9366/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "AwardCriteria-2.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/14e34b14cde74e2491beb7ced3dc32f6?KeyID=40b19d1c&Signature=%2FuA%2FXYMT6ZHeTvSBrSqRTp6JgQBLnHrHkrAECtrVHEM0wBnxml9WsQPlmYUJy74qJvPSSHrbYulEsxs1FUZsAA%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-01-01T00:00:00+02:00", 
      "id": "b075aa094b8d403b930d304197667350", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "author": "tender_owner", 
      "language": "uk", 
      "title": "Notice.pdf", 
      "url": "http://public-docs-sandbox.prozorro.gov.ua/get/842a41f281554f39b5b01ec2f812e713?KeyID=40b19d1c&Signature=%252BvHkNmyMibp0YWz1rwHspEKgyeAUoNBEEpiuw33DVVjxfU78bRHoqz9fRR9qw82v49nNtBwFKRQXQv%2FsN2MVCw%253D%253D", 
      "format": "application/pdf", 
      "documentOf": "tender", 
      "datePublished": "2019-01-01T00:00:00+02:00", 
      "id": "eb5011cabe124facb6b6c222793a0ca8", 
      "dateModified": "2019-01-01T00:00:00+02:00"
    }
  ]
}

