PUT /api/2.5/tenders/fc67c57b5cdb4a06a99e35bd632b9366/documents/b075aa094b8d403b930d304197667350?acc_token=170761b45ca447fd912a2e36a9379c91 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 196
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy526543226979$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/14e34b14cde74e2491beb7ced3dc32f6?KeyID=40b19d1c&Signature=%2FuA%2FXYMT6ZHeTvSBrSqRTp6JgQBLnHrHkrAECtrVHEM0wBnxml9WsQPlmYUJy74qJvPSSHrbYulEsxs1FUZsAA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "b075aa094b8d403b930d304197667350", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

