PATCH /api/2.5/tenders/758ee1a76e934b439e1c72d25b8ab9d1/cancellations/de6a564ea6d84a119232997f67b37fef?acc_token=7adc5cc127ca43dfbd62642f00c646d8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-04-01T01:00:00+03:00", 
    "cancellationOf": "tender", 
    "id": "de6a564ea6d84a119232997f67b37fef"
  }
}

