PATCH /api/2.5/tenders/365920b7e25c4152b9ec963f9d833276/cancellations/31918af8488e4933b838906a30813b2c?acc_token=4ab602baa1514fd2ad22ab15d03f3eb2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reasonType": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "unsuccessful", 
    "date": "2019-03-18T16:25:55.439105+02:00", 
    "cancellationOf": "tender", 
    "id": "31918af8488e4933b838906a30813b2c"
  }
}

