PUT /api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/documents/e98688ab06c148108b5f07cec928f8da?acc_token=57e796bd207d4695964c4d14060285c7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 196
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy556820536562$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "AwardCriteria-2.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/ed5401a01f654c23967dbdd089fcba54?KeyID=a8968c46&Signature=hZbKYK8Y9pnKkqJTlrLh9DldBXUzwvIPXLb3DmAUlX2Li9IbJQOZt4r7ndqa5u%252BHj6HSpBxPLV41yK8bzuuLCQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "e98688ab06c148108b5f07cec928f8da", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

