PATCH /api/2.5/tenders/73c2c3f9cc6349f0a144ed40c9e3dfa7?acc_token=62a4f7692eab4a6cbb0af2c34f9dd6c0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2019-04-05T06:48:32.596820+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2019-02-28T06:48:32.496267+02:00", 
      "endDate": "2019-04-01T00:00:00+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-02-28T06:48:32.496267+02:00", 
      "clarificationsUntil": "2019-03-29T06:48:32.596820+02:00", 
      "endDate": "2019-03-26T06:48:32.596820+02:00", 
      "invalidationDate": "2019-03-28T06:48:32.663255+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-04-05T07:48:32.596820+03:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-03-28T06:48:32.436239+02:00", 
        "title": "Калорійність", 
        "date": "2019-03-28T06:48:32.372642+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "99748b3b16684deeb3bcdfae2cbb7ea4", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "73c2c3f9cc6349f0a144ed40c9e3dfa7", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/e9b6b6ef7faa41bbaef7c4dda5222553?KeyID=17aaf97f&Signature=sEfTHgIOPeS4e98iTh2vIAkPmvG80sKRghdtHhckQceoSLzW5FvXNURlG%2FQ2DcThzhVmoasvDexF0xfYgms%252BAg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:48:32.196875+02:00", 
        "id": "3950220e604d49b79237e0797c0e16ba", 
        "dateModified": "2019-03-28T06:48:32.196903+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/fe1d729de2844e1aa563e171b54a1296?KeyID=17aaf97f&Signature=W0YJT%252BCx1fVVqPuiWao3mTwjtEFCmgeHKVuWTUK5skfCuQCtLApvAUImZM2YBa5UgZUKRSlkvlF8q9yD4PK%2FCA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:48:32.246569+02:00", 
        "id": "f0cb14f55b2947258c7d1dd04fdeea36", 
        "dateModified": "2019-03-28T06:48:32.246590+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/27f836743ec6499e9479615413d84bc3?KeyID=17aaf97f&Signature=X07YnIcRNVq3GjqmqquoSV2TIEUmH3KnrRtBdd3UIWlSAmfzYNxZRMQRQ3To%252BUc4Yiz9vIjsSnqL3YQkg0kfCA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-28T06:48:32.246569+02:00", 
        "id": "f0cb14f55b2947258c7d1dd04fdeea36", 
        "dateModified": "2019-03-28T06:48:32.302010+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "tenderID": "UA-2019-03-28-000001", 
    "dateModified": "2019-03-28T06:48:32.665812+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2019-02-28T06:48:32.496267+02:00", 
      "endDate": "2019-04-05T06:48:32.596820+02:00"
    }, 
    "title_en": "Services in school canteens", 
    "procurementMethodType": "competitiveDialogueEU", 
    "date": "2019-03-28T06:48:31.990273+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-17T06:47:07.975510+02:00", 
          "endDate": "2019-05-17T06:47:07.975543+02:00"
        }, 
        "id": "7f6efd4a2f2949d783da759c660da3d3", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-17T06:47:07.975557+02:00", 
          "endDate": "2019-05-17T06:47:07.975571+02:00"
        }, 
        "id": "a4dfa4eea6864907b12cc3484dd9cc26", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

