PUT /api/2.5/tenders/2bd2d6246680491fa01f7e1c51e03fcd/cancellations/5cbae87de9214ce0be0c174fd980264d/documents/b27e3e73568f459bad0341587153cada?acc_token=a02e17b4964743a29ad34331d588631c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 189
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy718254788847$
Host: api-sandbox.openprocurement.org


Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "language": "uk", 
    "title": "Notice-2.pdf", 
    "url": "http://public.docs-sandbox.openprocurement.org/get/1d4fd15ef87d440eab6f5a28c9926629?KeyID=71c53a63&Signature=kSTbvRj6pT2AnhojOABGbjw2HkvN2HtUg3E0LNVzvkx9ceKPxbP%2FwzDZsNh%2FBxzuUkQ0jbw3xbjOf%2FO8BLskCQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-03-28T06:48:20.410766+02:00", 
    "id": "b27e3e73568f459bad0341587153cada", 
    "dateModified": "2019-03-28T06:48:20.490996+02:00"
  }
}

