GET /api/2.5/tenders/636f8ed2b38c43ceb7d481bb2c0bf72b?acc_token=53dd6cedd9bf46d59d2ec79baf9bd876 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2019-02-18T16:26:57.152606+02:00", 
      "endDate": "2019-03-16T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2019-02-18T16:26:57.152606+02:00", 
      "clarificationsUntil": "2019-03-14T00:00:00+02:00", 
      "endDate": "2019-03-10T16:26:57.152606+02:00", 
      "invalidationDate": "2019-03-18T16:26:54.913959+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-03-20T16:26:57.152606+02:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-03-18T16:26:56.493735+02:00", 
        "title": "Калорійність", 
        "date": "2019-03-18T16:26:55.814122+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "7ba57e064ecb4964bf3e93159b375cdd", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "636f8ed2b38c43ceb7d481bb2c0bf72b", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/d4ecdf49e0364887b370ecf0c6a653b1?KeyID=c7d5e428&Signature=9R1Y8k4%252BxqPEygC61j%252Bskn7IGVwet5mxxB7IhTQFeKANVm6o1WK3z5trmFPJ1RvzqlboPwuOPpE6LWKidM0sCQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:26:53.615730+02:00", 
        "id": "21ec916b17d24661a33fb80abf3a77bd", 
        "dateModified": "2019-03-18T16:26:53.615825+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/0efea23700bc412590d9a3be0b5ecd09?KeyID=c7d5e428&Signature=cH4WgoHVWHVukl79XPDJpxex6%252Bqs6TJSQR1Qkt0BPCtKiuIIHWJ2wSp6B2t98W%252BE6Ds7%252B8x%2FPfStqszJ5A9xCQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:26:54.221780+02:00", 
        "id": "6c0cf8c1c0b44e12a74e8691cfecd451", 
        "dateModified": "2019-03-18T16:26:54.222769+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public.docs-sandbox.openprocurement.org/get/d997d8da6e6c4bb2b24b420579e5351f?KeyID=c7d5e428&Signature=VWYC1AysXDEA7IEqystV%252B8W%252BkpwXv3hJP%252BU1Tw0pOPmD2n1vHVOX3aJIIyQ2VDgi4djEmEMO2cLFnY0uGEQLBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-03-18T16:26:54.221780+02:00", 
        "id": "6c0cf8c1c0b44e12a74e8691cfecd451", 
        "dateModified": "2019-03-18T16:26:54.886904+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "tenderID": "UA-2019-03-18-000001", 
    "dateModified": "2019-03-18T16:26:56.556753+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2019-02-18T16:26:57.152606+02:00", 
      "endDate": "2019-03-20T16:26:57.152606+02:00"
    }, 
    "title_en": "Services in school canteens", 
    "procurementMethodType": "competitiveDialogueEU", 
    "date": "2019-03-18T16:26:50.773797+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-07T16:25:23.279560+02:00", 
          "endDate": "2019-05-07T16:25:23.279783+02:00"
        }, 
        "id": "153533de04aa4c248eeff56045e606ee", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-07T16:25:23.279854+02:00", 
          "endDate": "2019-05-07T16:25:23.279919+02:00"
        }, 
        "id": "1722588c347c47b1b4a2ac1cd6bc558e", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

PATCH /api/2.5/tenders/636f8ed2b38c43ceb7d481bb2c0bf72b?acc_token=53dd6cedd9bf46d59d2ec79baf9bd876 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 38
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "value": {
      "amount": 501.0
    }
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "tenderPeriod should be extended by 7 days", 
      "location": "body", 
      "name": "data"
    }
  ]
}

