GET /api/2.5/tenders/fc67c57b5cdb4a06a99e35bd632b9366?acc_token=170761b45ca447fd912a2e36a9379c91 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2018-12-04T00:00:00+02:00", 
      "endDate": "2018-12-30T00:00:00+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2018-12-04T00:00:00+02:00", 
      "clarificationsUntil": "2018-12-28T00:00:00+02:00", 
      "endDate": "2018-12-24T00:00:00+02:00", 
      "invalidationDate": "2019-01-01T00:00:00+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2019-01-03T00:00:00+02:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2019-01-01T00:00:00+02:00", 
        "title": "Калорійність", 
        "date": "2019-01-01T00:00:00+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "03171100ba074523bc87fe866536c31b", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "fc67c57b5cdb4a06a99e35bd632b9366", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/842a41f281554f39b5b01ec2f812e713?KeyID=40b19d1c&Signature=%252BvHkNmyMibp0YWz1rwHspEKgyeAUoNBEEpiuw33DVVjxfU78bRHoqz9fRR9qw82v49nNtBwFKRQXQv%2FsN2MVCw%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "eb5011cabe124facb6b6c222793a0ca8", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/e825bc8b86f14c38b702972ae267f7f5?KeyID=40b19d1c&Signature=s72Y1E%252BdNMf%2Fx482%252BH1KpDskAsG3yhfifiYMRSTqhk0LPw%2FZWa%252BhT3Zj2qLtTrsKHMyBH78Y306CSVPlpwXjBg%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "b075aa094b8d403b930d304197667350", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "tender_owner", 
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://public-docs-sandbox.prozorro.gov.ua/get/14e34b14cde74e2491beb7ced3dc32f6?KeyID=40b19d1c&Signature=%2FuA%2FXYMT6ZHeTvSBrSqRTp6JgQBLnHrHkrAECtrVHEM0wBnxml9WsQPlmYUJy74qJvPSSHrbYulEsxs1FUZsAA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2019-01-01T00:00:00+02:00", 
        "id": "b075aa094b8d403b930d304197667350", 
        "dateModified": "2019-01-01T00:00:00+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "tenderID": "UA-2019-01-01-000001", 
    "dateModified": "2019-01-01T00:00:00+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2018-12-04T00:00:00+02:00", 
      "endDate": "2019-01-03T00:00:00+02:00"
    }, 
    "title_en": "Services in school canteens", 
    "procurementMethodType": "competitiveDialogueEU", 
    "date": "2019-01-01T00:00:00+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-05-08T06:49:21.594579+03:00", 
          "endDate": "2019-06-07T06:49:21.594605+03:00"
        }, 
        "id": "747deaafa6c0492389d02a0fc8e451ca", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-05-08T06:49:21.594619+03:00", 
          "endDate": "2019-06-07T06:49:21.594627+03:00"
        }, 
        "id": "211faed1bf11494bb34c498a29d420bf", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1.0
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

PATCH /api/2.5/tenders/fc67c57b5cdb4a06a99e35bd632b9366?acc_token=170761b45ca447fd912a2e36a9379c91 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 38
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "value": {
      "amount": 501.0
    }
  }
}

Response: 403 Forbidden
Content-Type: application/json; charset=UTF-8
{
  "status": "error", 
  "errors": [
    {
      "description": "tenderPeriod should be extended by 7 days", 
      "location": "body", 
      "name": "data"
    }
  ]
}

