POST /api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/documents?acc_token=57e796bd207d4695964c4d14060285c7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 136
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Notice.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/documents/4f48a9390f2a43388b4e2e0b33446ac2
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/82bde92d2b3746af92caf8b8e844067e?KeyID=a8968c46&Signature=tggiW86LiC7xAfijpr8ubXeQaRhKHFiz%2FSVCNU%252BtVrFdI6cMXSCyQzEdgrH7PGJEbQbhfB8RT%252BQEHYJl26eUAw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "4f48a9390f2a43388b4e2e0b33446ac2", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

