POST /api/2.5/tenders/758ee1a76e934b439e1c72d25b8ab9d1/cancellations/de6a564ea6d84a119232997f67b37fef/documents?acc_token=7adc5cc127ca43dfbd62642f00c646d8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 136
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Notice.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/758ee1a76e934b439e1c72d25b8ab9d1/cancellations/de6a564ea6d84a119232997f67b37fef/documents/28e5df44452c4e79b392f6383e3531ba
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/0b966d8fb99b404eb09222dc468820d3?KeyID=a8968c46&Signature=FcAsJLKgyY4GGnBxghscOUqH0tRAo7dDxiWXn67py0ZD1usv6KrypzwEuzQ3rrARo80UQewxr3Z49iF3eyvzDQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-04-01T01:00:00+03:00", 
    "id": "28e5df44452c4e79b392f6383e3531ba", 
    "dateModified": "2019-04-01T01:00:00+03:00"
  }
}

