POST /api/2.5/tenders/fc67c57b5cdb4a06a99e35bd632b9366/documents?acc_token=170761b45ca447fd912a2e36a9379c91 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy651775504123$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/fc67c57b5cdb4a06a99e35bd632b9366/documents/eb5011cabe124facb6b6c222793a0ca8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/842a41f281554f39b5b01ec2f812e713?KeyID=40b19d1c&Signature=%252BvHkNmyMibp0YWz1rwHspEKgyeAUoNBEEpiuw33DVVjxfU78bRHoqz9fRR9qw82v49nNtBwFKRQXQv%2FsN2MVCw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "eb5011cabe124facb6b6c222793a0ca8", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

