POST /api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/documents?acc_token=57e796bd207d4695964c4d14060285c7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 193
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy209640728032$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/documents/e98688ab06c148108b5f07cec928f8da
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "AwardCriteria.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/52d237dc51ad48bca402dcff491cb39d?KeyID=a8968c46&Signature=b51UBYFq%2F8PRpk8Pn5rUJEuEUOa2qBvl2TqE%252BA%252BPaZy0lfnpgoJGEsgKqhNZf5hMgAYi1SYNJY9Ryq%252BWx%2FUJCA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "e98688ab06c148108b5f07cec928f8da", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

