POST /api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/bids/597f8b71d8db469398b44e7a96cbafd8/documents?acc_token=5f58f48da5674b2cb4f489a5e8240849 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 138
Content-Type: multipart/form-data; boundary=BOUNDARY
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="Proposal.pdf"
Content-Type: application/pdf

content
--BOUNDARY--


Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/bids/597f8b71d8db469398b44e7a96cbafd8/documents/c2c45be873094186820e36644c9368e8
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "confidentiality": "public", 
    "language": "uk", 
    "title": "Proposal.pdf", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/bids/597f8b71d8db469398b44e7a96cbafd8/documents/c2c45be873094186820e36644c9368e8?download=f3f392d62cff49a88b52aec015601816", 
    "format": "application/pdf", 
    "isDescriptionDecision": false, 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "c2c45be873094186820e36644c9368e8", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

