POST /api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/documents?acc_token=57e796bd207d4695964c4d14060285c7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy227364963289$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/ee151acde21d47749df3a412b1b1c5b9/documents/4f48a9390f2a43388b4e2e0b33446ac2
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "tender_owner", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/3a5e3a40fbb74fd68bea2547af64a273?KeyID=a8968c46&Signature=KSwEOQC%252BoEKUBzjmzCIKQPxCVlo%2F3iUOGC%252B7U7icGcVOK00f111chY77yb3PuZHYodhEhBpxxxZgMJvFpaOjAA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "4f48a9390f2a43388b4e2e0b33446ac2", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

