POST /api/2.5/tenders/90b464fca24048c4a691040dbe85e781/cancellations/3aa1447c0e2a453e9baad3e9c6d9a550/documents?acc_token=6c048585eae24a9b98a248714eaff897 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 184
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy82289511573$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/tenders/90b464fca24048c4a691040dbe85e781/cancellations/3aa1447c0e2a453e9baad3e9c6d9a550/documents/8f46bff175444f4b811b84b9ee841b8e
{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://public-docs-sandbox.prozorro.gov.ua/get/c4bb1d82e3b447c4b937cf9c0a36f73a?KeyID=a411437f&Signature=I8EmJx5%252Br83z6%252BcYXFa4MQhwVK3EQlmdVzRSW9ohC%252BYYNgn1TbJPecvFMUfXfGdyAxoUjHmbucpGlmEIkcQiDQ%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2019-01-01T00:00:00+02:00", 
    "id": "8f46bff175444f4b811b84b9ee841b8e", 
    "dateModified": "2019-01-01T00:00:00+02:00"
  }
}

