POST /api/2.5/contracts/67b7dce91c0b47b18c266d187c2a132c/documents?acc_token=bc3cb0a3a68149d982aa218bc75c15d2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 199
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy532785248802$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/contracts/67b7dce91c0b47b18c266d187c2a132c/documents/373d507a93244bc5a0c438df4e98c139
{
  "data": {
    "title": "contract_changes.doc", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/contracts/67b7dce91c0b47b18c266d187c2a132c/documents/373d507a93244bc5a0c438df4e98c139?download=33b5900f28384463bbb357d7c172aa8a", 
    "format": "application/msword", 
    "documentOf": "contract", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "373d507a93244bc5a0c438df4e98c139", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

