PATCH /api/2.5/contracts/2da2605ce00540ab896900209a9d3bbd?acc_token=bb2d1340e85b4a33b1108c36928e6eed HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "period": {
      "startDate": "2019-03-28T06:48:49.146735+02:00", 
      "endDate": "2019-04-27T06:48:49.146759+02:00"
    }, 
    "value": {
      "amount": 438, 
      "amountNet": 430
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "contract_changes.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.5/contracts/2da2605ce00540ab896900209a9d3bbd/documents/23bafb857786461e9e6f65e99d34fbbc?download=74e9fbe3ea8548c2a614c9880e708927", 
        "format": "application/msword", 
        "documentOf": "change", 
        "datePublished": "2019-03-28T06:48:49.095199+02:00", 
        "id": "23bafb857786461e9e6f65e99d34fbbc", 
        "relatedItem": "a60b5cf2e58f4e0ab405d92484b71019", 
        "dateModified": "2019-03-28T06:48:49.095223+02:00"
      }
    ], 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-30T06:47:07.288622+02:00", 
          "endDate": "2019-04-02T06:47:07.288622+03:00"
        }, 
        "id": "57ecdbb89a09425ab4fa5a75dc2d40f1", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }, 
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-03-30T06:47:07.288622+02:00", 
          "endDate": "2019-04-02T06:47:07.288622+03:00"
        }, 
        "id": "ba8e3f23cf8441c28e60009e8f3073c1", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "period": {
      "startDate": "2019-03-28T06:48:49.146735+02:00", 
      "endDate": "2019-04-27T06:48:49.146759+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 438.0, 
      "amountNet": 430.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateModified": "2019-03-28T06:48:49.202175+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "dateSigned": "2019-03-28T06:48:48.661676+02:00", 
    "contractID": "UA-2019-03-28-000001-1", 
    "owner": "broker", 
    "awardID": "0070ab5f96df47ecae302c40ab7335bb", 
    "changes": [
      {
        "status": "pending", 
        "rationaleTypes": [
          "volumeCuts", 
          "priceReduction"
        ], 
        "rationale_en": "Contract change cause", 
        "rationale": "Друга і третя поставка має бути розфасована", 
        "date": "2019-03-28T06:48:49.017543+02:00", 
        "id": "a60b5cf2e58f4e0ab405d92484b71019"
      }
    ], 
    "id": "2da2605ce00540ab896900209a9d3bbd", 
    "tender_id": "d29dcbb84cbe4be191e2dc2690bddd1b"
  }
}

