PATCH /api/2.5/contracts/78ebf0cac78f45d6a6772cb5d8f26bc3?acc_token=c27cf4b1333e4596984912883852e6e0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 148
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "period": {
      "startDate": "2019-01-01T00:10:00+02:00", 
      "endDate": "2019-01-31T00:10:00+02:00"
    }, 
    "value": {
      "amount": 438, 
      "amountNet": 430
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "contract_changes.doc", 
        "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/contracts/78ebf0cac78f45d6a6772cb5d8f26bc3/documents/b6bd38087cfc47788d04cfa6f130f57b?download=a12dbef28be440ea8d609d32f68ea7db", 
        "format": "application/msword", 
        "documentOf": "change", 
        "datePublished": "2019-01-01T00:10:00+02:00", 
        "id": "b6bd38087cfc47788d04cfa6f130f57b", 
        "relatedItem": "6da9e1f7c92a4cd5b528daa9fe56ff9b", 
        "dateModified": "2019-01-01T00:10:00+02:00"
      }
    ], 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-20T06:49:21.547544+03:00", 
          "endDate": "2019-04-23T06:49:21.547544+03:00"
        }, 
        "id": "ed2f6d44fb254ad9ab0d628d5737002a", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }, 
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2019-04-20T06:49:21.547544+03:00", 
          "endDate": "2019-04-23T06:49:21.547544+03:00"
        }, 
        "id": "1dc056ea4a57422a80e0a3a7f1d4de63", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "period": {
      "startDate": "2019-01-01T00:10:00+02:00", 
      "endDate": "2019-01-31T00:10:00+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 438.0, 
      "amountNet": 430.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateModified": "2019-01-01T00:10:00+02:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "dateSigned": "2019-01-01T00:10:00+02:00", 
    "contractID": "UA-2019-01-01-000001-1", 
    "owner": "broker", 
    "awardID": "20844293153543d7afabad719b6a7b88", 
    "changes": [
      {
        "status": "pending", 
        "rationaleTypes": [
          "volumeCuts", 
          "priceReduction"
        ], 
        "rationale_en": "Contract change cause", 
        "rationale": "Друга і третя поставка має бути розфасована", 
        "date": "2019-01-01T00:10:00+02:00", 
        "id": "6da9e1f7c92a4cd5b528daa9fe56ff9b"
      }
    ], 
    "id": "78ebf0cac78f45d6a6772cb5d8f26bc3", 
    "tender_id": "bd4410ceb3a949858ccdc3141d32898f"
  }
}

