GET /api/2.4/tenders/d12d2b2ffd664ac7b2883de29b1257c0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "procurementMethod": "open", 
    "status": "complete", 
    "awardPeriod": {
      "startDate": "2018-09-11T05:22:42.118232+03:00", 
      "endDate": "2018-09-11T05:22:42.118232+03:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2018-08-27T05:22:42.118232+03:00", 
      "endDate": "2018-09-03T05:22:42.118232+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "id": "d12d2b2ffd664ac7b2883de29b1257c0", 
    "title": "футляри до державних нагород", 
    "tenderID": "UA-2018-09-21-000001", 
    "dateModified": "2018-09-21T05:22:47.062502+03:00", 
    "numberOfBids": 1, 
    "tenderPeriod": {
      "startDate": "2018-09-03T05:22:42.118232+03:00", 
      "endDate": "2018-09-10T05:22:42.118232+03:00"
    }, 
    "contracts": [
      {
        "status": "active", 
        "items": [
          {
            "description": "футляри до державних нагород", 
            "classification": {
              "scheme": "ДК021", 
              "description": "Cartons", 
              "id": "44617100-9"
            }, 
            "additionalClassifications": [
              {
                "scheme": "ДКПП", 
                "id": "17.21.1", 
                "description": "папір і картон гофровані, паперова й картонна тара"
              }
            ], 
            "deliveryAddress": {
              "postalCode": "79000", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "deliveryDate": {
              "startDate": "2018-09-23T05:22:42.118232+03:00", 
              "endDate": "2018-09-26T05:22:42.118232+03:00"
            }, 
            "id": "5a44a463d0844b96a84bb44d5d6d3ae2", 
            "unit": {
              "code": "44617100-9", 
              "name": "item"
            }, 
            "quantity": 5
          }, 
          {
            "description": "футляри до державних нагород", 
            "classification": {
              "scheme": "ДК021", 
              "description": "Cartons", 
              "id": "44617100-9"
            }, 
            "additionalClassifications": [
              {
                "scheme": "ДКПП", 
                "id": "17.21.1", 
                "description": "папір і картон гофровані, паперова й картонна тара"
              }
            ], 
            "deliveryAddress": {
              "postalCode": "79000", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }, 
            "deliveryDate": {
              "startDate": "2018-09-23T05:22:42.118232+03:00", 
              "endDate": "2018-09-26T05:22:42.118232+03:00"
            }, 
            "id": "252da634c0b04e85a3783f5691b7ff38", 
            "unit": {
              "code": "44617100-9", 
              "name": "item"
            }, 
            "quantity": 5
          }
        ], 
        "suppliers": [
          {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }
        ], 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "amountNet": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "dateSigned": "2018-09-21T05:22:47.057256+03:00", 
        "date": "2018-09-21T05:22:47.062502+03:00", 
        "awardID": "d4c8d86605fd41a8837fadc7160e382e", 
        "id": "62b3738a8ea24260bb7a1f314c62a5b1", 
        "contractID": "UA-2018-09-21-000001-1"
      }
    ], 
    "auctionPeriod": {
      "startDate": "2018-09-10T05:22:42.118232+03:00", 
      "endDate": "2018-09-11T05:22:42.118232+03:00"
    }, 
    "procurementMethodType": "belowThreshold", 
    "awards": [
      {
        "status": "active", 
        "complaintPeriod": {
          "startDate": "2018-09-21T05:22:46.347607+03:00", 
          "endDate": "2018-09-21T05:22:46.347607+03:00"
        }, 
        "suppliers": [
          {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }
        ], 
        "bid_id": "0880fa75e11c422895ec83c365285a4f", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2018-09-21T05:22:46.522657+03:00", 
        "id": "d4c8d86605fd41a8837fadc7160e382e"
      }
    ], 
    "date": "2018-09-21T05:22:47.062502+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-23T05:22:42.118232+03:00", 
          "endDate": "2018-09-26T05:22:42.118232+03:00"
        }, 
        "id": "5a44a463d0844b96a84bb44d5d6d3ae2", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }, 
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-23T05:22:42.118232+03:00", 
          "endDate": "2018-09-26T05:22:42.118232+03:00"
        }, 
        "id": "252da634c0b04e85a3783f5691b7ff38", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "bids": [
      {
        "date": "2018-09-21T05:22:46.059970+03:00", 
        "status": "active", 
        "id": "0880fa75e11c422895ec83c365285a4f", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "tenderers": [
          {
            "contactPoint": {
              "name": "Державне управління справами", 
              "telephone": "0440000000"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00037256", 
              "uri": "http://www.dus.gov.ua/"
            }, 
            "name": "Державне управління справами", 
            "address": {
              "postalCode": "01220", 
              "countryName": "Україна", 
              "streetAddress": "вул. Банкова, 11, корпус 1", 
              "region": "м. Київ", 
              "locality": "м. Київ"
            }
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

