PATCH /api/2.5/contracts/3b9954bd6622406887527e603c795dcb/changes/553dd9ae348842acb185edc54bdfe197?acc_token=2b3c58ccf4eb409a9642e408a9eb753d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 255
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "rationale": "Друга і третя поставка має бути розфасована"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "rationaleTypes": [
      "volumeCuts", 
      "priceReduction"
    ], 
    "rationale_en": "Contract change cause", 
    "rationale": "Друга і третя поставка має бути розфасована", 
    "date": "2019-03-18T09:27:17.518486+02:00", 
    "id": "553dd9ae348842acb185edc54bdfe197"
  }
}

