PATCH /api/2.5/contracts/78ebf0cac78f45d6a6772cb5d8f26bc3/documents/b6bd38087cfc47788d04cfa6f130f57b?acc_token=c27cf4b1333e4596984912883852e6e0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 85
Content-Type: application/json
Host: lb-api-sandbox.prozorro.gov.ua
DATA:
{
  "data": {
    "documentOf": "change", 
    "relatedItem": "6da9e1f7c92a4cd5b528daa9fe56ff9b"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "title": "contract_changes.doc", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/contracts/78ebf0cac78f45d6a6772cb5d8f26bc3/documents/b6bd38087cfc47788d04cfa6f130f57b?download=a12dbef28be440ea8d609d32f68ea7db", 
    "format": "application/msword", 
    "documentOf": "change", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "b6bd38087cfc47788d04cfa6f130f57b", 
    "relatedItem": "6da9e1f7c92a4cd5b528daa9fe56ff9b", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

