PATCH /api/2.4/contracts/822ae0edf19348bbbd3ea104577bae4b/documents/5c90416d4f9743008566f7ec8efb9c47?acc_token=b1b01ccd4f61456db571e7b698d88d57 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 85
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "documentOf": "change", 
    "relatedItem": "298fe4c4fa6b4503830e7bf9ddbafce5"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "title": "contract_changes.doc", 
    "url": "http://api-sandbox.openprocurement.org/api/2.4/contracts/822ae0edf19348bbbd3ea104577bae4b/documents/5c90416d4f9743008566f7ec8efb9c47?download=ddb14781ffa04039b4545acce76e0c05", 
    "format": "application/msword", 
    "documentOf": "change", 
    "datePublished": "2018-08-15T09:42:50.214489+03:00", 
    "id": "5c90416d4f9743008566f7ec8efb9c47", 
    "relatedItem": "298fe4c4fa6b4503830e7bf9ddbafce5", 
    "dateModified": "2018-08-15T09:42:50.214518+03:00"
  }
}

