POST /api/2.5/contracts/78ebf0cac78f45d6a6772cb5d8f26bc3/documents?acc_token=c27cf4b1333e4596984912883852e6e0 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 215
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy010584362262$
Host: lb-api-sandbox.prozorro.gov.ua

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://lb-api-sandbox.prozorro.gov.ua/api/2.5/contracts/78ebf0cac78f45d6a6772cb5d8f26bc3/documents/9318d6e85c0a4d0c9005bf118e9aebca
{
  "data": {
    "title": "contract_additional_docs.doc", 
    "url": "http://lb-api-sandbox.prozorro.gov.ua/api/2.5/contracts/78ebf0cac78f45d6a6772cb5d8f26bc3/documents/9318d6e85c0a4d0c9005bf118e9aebca?download=a6cc12a168024e14ad92555160a2f8a0", 
    "format": "application/msword", 
    "documentOf": "contract", 
    "datePublished": "2019-01-01T00:10:00+02:00", 
    "id": "9318d6e85c0a4d0c9005bf118e9aebca", 
    "dateModified": "2019-01-01T00:10:00+02:00"
  }
}

