PUT /api/2.4/contracts/fac3a341fed1428487268fa4dec62bc4/documents/2404ec221ea141b1b9b02dd61a48a58a?acc_token=5abc0448690540ee9c29b65a1751bd12 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 224
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy647262067069$
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "title": "contract_additional_docs.doc", 
    "url": "http://api-sandbox.openprocurement.org/api/2.4/contracts/fac3a341fed1428487268fa4dec62bc4/documents/2404ec221ea141b1b9b02dd61a48a58a?download=2c6549b32ca8499faef94d0a02c9760e", 
    "format": "application/msword", 
    "documentOf": "contract", 
    "datePublished": "2018-08-15T09:33:38.315866+03:00", 
    "id": "2404ec221ea141b1b9b02dd61a48a58a", 
    "dateModified": "2018-08-15T09:33:38.427207+03:00"
  }
}

