POST /api/2.4/contracts/fac3a341fed1428487268fa4dec62bc4/documents?acc_token=5abc0448690540ee9c29b65a1751bd12 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 191
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy330502766608$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.4/contracts/fac3a341fed1428487268fa4dec62bc4/documents/448ee0ecf8b641b3ac1bfeb333eeb095
{
  "data": {
    "title": "contract.doc", 
    "url": "http://api-sandbox.openprocurement.org/api/2.4/contracts/fac3a341fed1428487268fa4dec62bc4/documents/448ee0ecf8b641b3ac1bfeb333eeb095?download=abed4076cd05483d98760c6433fafcca", 
    "format": "application/msword", 
    "documentOf": "contract", 
    "datePublished": "2018-08-15T09:33:38.163207+03:00", 
    "id": "448ee0ecf8b641b3ac1bfeb333eeb095", 
    "dateModified": "2018-08-15T09:33:38.163229+03:00"
  }
}

