GET /api/2.4/contracts/62b3738a8ea24260bb7a1f314c62a5b1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "contract_changes.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.4/contracts/62b3738a8ea24260bb7a1f314c62a5b1/documents/2bd1172367bb480c8ae9c2c1be66c87f?download=bc995730e72a496782bf32f9dc8d5795", 
        "format": "application/msword", 
        "documentOf": "change", 
        "datePublished": "2018-09-21T05:22:48.267194+03:00", 
        "id": "2bd1172367bb480c8ae9c2c1be66c87f", 
        "relatedItem": "1c60b17f46b844b0876dd93859764bcc", 
        "dateModified": "2018-09-21T05:22:48.267303+03:00"
      }
    ], 
    "items": [
      {
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "ДК021", 
          "description": "Cartons", 
          "id": "44617100-9"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "папір і картон гофровані, паперова й картонна тара"
          }
        ], 
        "deliveryAddress": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2018-09-23T05:22:42.118232+03:00", 
          "endDate": "2018-09-26T05:22:42.118232+03:00"
        }, 
        "id": "5a44a463d0844b96a84bb44d5d6d3ae2", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 2
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "period": {
      "startDate": "2018-09-21T05:22:48.423330+03:00", 
      "endDate": "2018-10-21T05:22:48.423392+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 438.0, 
      "amountNet": 430.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateModified": "2018-09-21T05:22:49.077005+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "dateSigned": "2018-09-21T05:22:47.057256+03:00", 
    "contractID": "UA-2018-09-21-000001-1", 
    "owner": "broker", 
    "awardID": "d4c8d86605fd41a8837fadc7160e382e", 
    "changes": [
      {
        "status": "active", 
        "rationaleTypes": [
          "volumeCuts", 
          "priceReduction"
        ], 
        "rationale_en": "Contract change cause", 
        "dateSigned": "2018-09-21T05:22:49.006927+03:00", 
        "rationale": "Друга і третя поставка має бути розфасована", 
        "date": "2018-09-21T05:22:49.072913+03:00", 
        "id": "1c60b17f46b844b0876dd93859764bcc"
      }
    ], 
    "id": "62b3738a8ea24260bb7a1f314c62a5b1", 
    "tender_id": "d12d2b2ffd664ac7b2883de29b1257c0"
  }
}

