GET /api/2.5/contracts/67b7dce91c0b47b18c266d187c2a132c/changes HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb-api-sandbox.prozorro.gov.ua

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "rationaleTypes": [
        "volumeCuts", 
        "priceReduction"
      ], 
      "rationale_en": "Contract change cause", 
      "dateSigned": "2019-01-01T00:10:00+02:00", 
      "rationale": "Друга і третя поставка має бути розфасована", 
      "date": "2019-01-01T00:10:00+02:00", 
      "id": "06b792d9cb3d418e9776e35c697de03c"
    }
  ]
}

